### PR TITLE
fix: address book jrs test failing

### LINKED ISSUE #10926: address book jrs test failures due to state AB not starting with `Address` or `nextNodeId`
```
ERROR | EXCEPTION | <<platform-core: thread-cons 0>> | AddressBookTestingToolState: | Exception occurred in Test Scenario GENESIS_FORCE_CONFIG_AB.

java.text.ParseException: The line [The State Saved Address Book W] does not start with `address` or `nextNodeId`. 	at com.swirlds.platform.system.address.AddressBookUtils.parseAddressBookText(AddressBookUtils.java:118) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.demo.addressbook.AddressBookTestingToolState.parseAddressBook(AddressBookTestingToolState.java:815) ~[?:?] 	
at com.swirlds.demo.addressbook.AddressBookTestingToolState.getDebugAddressBookAfterHeader(AddressBookTestingToolState.java:770) ~[?:?] 	
at com.swirlds.demo.addressbook.AddressBookTestingToolState.getStateAddressBook(AddressBookTestingToolState.java:757) ~[?:?] 	
at com.swirlds.demo.addressbook.AddressBookTestingToolState.genesisForceUseOfConfigAddressBookTrue(AddressBookTestingToolState.java:516) ~[?:?] 	
at com.swirlds.demo.addressbook.AddressBookTestingToolState.validateTestScenario(AddressBookTestingToolState.java:337) ~[?:?] 	
at com.swirlds.demo.addressbook.AddressBookTestingToolState.handleConsensusRound(AddressBookTestingToolState.java:212) ~[?:?] 	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:190) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:376) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?] 	
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### PR DESCRIPTION
**Pull request by edward-swirldslabs**
Fixes #10926 

Also contains fix for a randomly breaking unit test in `OrphanBufferTests`

JRS Tests Passing: 
https://swirldslabs.slack.com/archives/C05HGK5HS6Q/p1705007081902669

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java [hunk 1]
```diff
@@ -127,7 +127,21 @@ public AddressBookInitializer(
...
+        AddressBook stateAddressBook;
+        try {
+            stateAddressBook = initialState.getAddressBook();
+        } catch (final NullPointerException ex) {
+            if (!initialState.isGenesisState()) {
+                throw new IllegalStateException("Null state address books are only allowed at genesis.");
+            }
+            stateAddressBook = null;
+        }
+        this.stateAddressBook = stateAddressBook;
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java:143]: Instead of just catching nullpointer exceptions, a better approach I think would be to drill down into the object and directly check. IMO, it's riskly doing this type of check, since it's plausible that we may accidentally catch a different problem that also throws a nullpointer exception.

Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java:143]: fair point.

**Review by cody-littley — DISMISSED** [review]

**Review by alittley — DISMISSED** [review]

**Review by cody-littley — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]
