### PR TITLE
fix: HAS.isAuthorizedRaw: Choose proper gas amount for EC vs ED signature verification

### LINKED ISSUE #14156: fix: HAS `isAuthorizedRaw` charges ED gas for both EC and ED
Hedera Account Service (HAS)`isAuthorizedRaw` charges the large ED gas (1.5M) for both ED and EC signature verification.  Should charge only 3000gas for EC.

### PR DESCRIPTION
**Pull request by david-bakin-sl**
**Description**:

Chooses gas requirement for `isAuthorizedRaw` based on whether you're verifying an EC key (3000) or an ED key (1.5M).

**Related issue(s)**:

Fixes #14156 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java [hunk 1]
```diff
@@ -90,27 +95,38 @@ public IsAuthorizedRawCall(
...
+
+        // Prepare the short-circuit error status returns
+        final Function<ResponseCodeEnum, PricedResult> bail = rce -> reversionWith(rce, gasRequirement);
+
+        // Must have a valid signature type to continue
         if (signatureType == SignatureType.INVALID)
             return bail.apply(INVALID_TRANSACTION_BODY /* should be: "invalid argument to precompile" */);
 
+        // Fail immediately if user didn't supply sufficient gas
+        final long availableGas = frame.getRemainingGas();
```
Comment (MrValioBg) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:122]: I think we can remove this, as its already performed in CustomMessageCallProcessor.doExecuteSystemContract, right after IsAuthorizedRawCall.execute() has been called.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java [hunk 2]
```diff
@@ -90,27 +95,38 @@ public IsAuthorizedRawCall(
...
+        if (availableGas < gasRequirement) return bail.apply(INSUFFICIENT_GAS);
+
```
Comment (MrValioBg) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:124]: I think we can remove this, as its already performed in `CustomMessageCallProcessor.doExecuteSystemContract`, right after `IsAuthorizedRawCall.execute()` has been called.

Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:124]: If we wait until then the expensive crypto operation will already have been done.  I thought there was value in avoiding that.  Do you agree?

Comment (MrValioBg) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:124]: Oh, okay. Got it, that makes sense.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java [hunk 3]
```diff
@@ -62,7 +62,12 @@ public class IsAuthorizedRawCall extends AbstractCall {
 
     // FUTURE: Gas for system contract method calls needs to be a) determined by measurement of
     // resources consumed, and b) incorporated into the fee schedule
-    private static final long HARDCODED_GAS_REQUIREMENT_GAS = 1_500_000L;
+
+    // Gas charge for an ED key - (rough) estimate of resources used (FUTURE: to be refined)
+    private static final long HARDCODED_ED_GAS_REQUIREMENT_GAS = 1_500_000L;
+
+    // Gas charge for an EC key - this is what Ethereum charges for ECRECOVER precompile
+    private static final long HARDCODED_EC_GAS_REQUIREMENT_GAS = 3_000;
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:70]: is it possible to use something like `gasCalculator().getEcrecPrecompiledContractGasCost()` so that if this value changes we are covered?

Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java]: Done.

**Review by lukelee-sl — APPROVED** [review]
LGTM
