### PR TITLE
Fix AllProtectedFilesUpdate-Reconnect-1-12m

### LINKED ISSUE #1248: AllProtectedFilesUpdate-Reconnect-1-12m fails ReconnectStreamValidator
**Summary of the defect**
`AllProtectedFilesUpdate-Reconnect-1-12m.json` test that runs daily fails in `ReconnectStreamValidator` with `IndexOutOfBoundsException` . Investigate the reason for the failure.

**How to reproduce (if possible)**
Slack: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1617953478241800
Slack summary : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1617956426018900

### LINKED ISSUE #1251: HAPIClientValidator fails for AllProtectedFilesUpdate-Reconnect-1-12m
**Summary of the defect**
`AllProtectedFilesUpdate-Reconnect-1-12m` failed for HAPIClientValidator, with the below error
```
2021-04-12 07:20:58.645 INFO   208  HapiTxnOp - 'UpdateAllProtectedFilesDuringReconnect' -  HapiContractCreate{sigs=2, node=0.0.6, contract=testContract, bytecode=contractFile, autoRenewPeriod=15} Wrong actual precheck status OK, expecting AUTORENEW_DURATION_NOT_IN_RANGE
2021-04-12 07:20:58.647 WARN   214  HapiSpecOperation - 'UpdateAllProtectedFilesDuringReconnect' - HapiContractCreate{sigs=2, node=0.0.6, contract=testContract, bytecode=contractFile, autoRenewPeriod=15} failed Wrong precheck status! Expected AUTORENEW_DURATION_NOT_IN_RANGE, actual OK!
2021-04-12 07:20:58.730 INFO   330  HapiApiSpec - 'UpdateAllProtectedFilesDuringReconnect' - final status: FAILED!
```
Summary Link - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618215709021400
Slack Link - https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618212750273200

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #1251 
Closes #1248

Passed test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618352417340700

**Summary of the change**:
Because of the issue #1224, overriding the property `"minimumAutoRenewDuration", "20"` did not update `ledger.autoRenewPeriod.minDuration` and from hgcaa.log the values are as 
` ledger.autoRenewPeriod.maxDuration=1000000000, ledger.autoRenewPeriod.minDuration=10`. So, the precheck did not pass `AUTORENEW_DURATION_NOT_IN_RANGE` .

Modified to override the property `"ledger.autoRenewPeriod.minDuration"` instead

### CODE REVIEW

**Review by anighanta — DISMISSED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java [hunk 1]
```diff
@@ -153,7 +153,7 @@ private HapiApiSpec updateAllProtectedFilesDuringReconnect() {
 								.path(ContractResources.VALID_BYTECODE_PATH),
 						contractCreate("testContract")
 								.bytecode("contractFile")
-								.autoRenewSecs(15)
+								.autoRenewSecs(1)
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java:156]: This change is not correct! `.autoRenewSecs(15)` expects `.hasPrecheck(AUTORENEW_DURATION_NOT_IN_RANGE)` because there was an update to the `APP_PROPERTIES` when a node is disconnected
https://github.com/hashgraph/hedera-services/blob/8ce8e05f6d6a0c360b5ac0159f2f721d0b9c47c7/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java#L95-L97

**Review by qnswirlds — CHANGES_REQUESTED** [review]
No

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/UpdateAllProtectedFilesDuringReconnect.java]: Thanks @qnswirlds . Fixed by using as suggested 
```
fileUpdate(APP_PROPERTIES).payingWith(GENESIS)
								.overridingProps(Map.of("ledger.autoRenewPeriod.minDuration", "20"))
								.erasingProps(Set.of("minimumAutoRenewDuration")),
```
Passed test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1618360190343900

**Review by qnswirlds — APPROVED** [review]
