### PR TITLE
fix: getInputWire concurrency issue

### LINKED ISSUE #23756: HAPI (Misc) failure potentially linked to a node facing a nondeterministic failure
We run into a test failure during this XTS run, https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/22235485512/job/64327245546.

Initial investigation thinks this may be related to a node having a nondeterministic failure, https://swirldslabs.slack.com/archives/C07PQPT2H18/p1771616120882369?thread_ts=1771615038.836899&cid=C07PQPT2H18

We should investigate and come up with a fix if this is accurate.

```
2026-02-20 18:38:30.643 <n1> 28       ERROR EXCEPTION        <<scheduler TransactionHandler>> DefaultTransactionHandler: error invoking ConsensusStateEventHandler.onHandleConsensusRound() [ nodeId = 1 ] with round 2
java.lang.IllegalArgumentException: Provided lambda is not a method on the component interface.
	at com.swirlds.component.framework@0.72.0-SNAPSHOT/com.swirlds.component.framework.component.internal.WiringComponentProxy.getMostRecentlyInvokedMethod(WiringComponentProxy.java:44)
	at com.swirlds.component.framework@0.72.0-SNAPSHOT/com.swirlds.component.framework.component.ComponentWiring.getInputWire(ComponentWiring.java:248)
	at com.swirlds.component.framework@0.72.0-SNAPSHOT/com.swirlds.component.framework.component.ComponentWiring.getInputWire(ComponentWiring.java:223)
	at org.hiero.consensus.event.creator.impl@0.72.0-SNAPSHOT/org.hiero.consensus.event.creator.impl.DefaultEventCreatorModule.quiescenceCommandInputWire(DefaultEventCreatorModule.java:156)
	at com.swirlds.platform.core@0.72.0-SNAPSHOT/com.swirlds.platform.wiring.PlatformCoordinator.quiescenceCommand(PlatformCoordinator.java:233)
	at com.swirlds.platform.core@0.72.0-SNAPSHOT/com.swirlds.platform.SwirldsPlatform.quiescenceCommand(SwirldsPlatform.java:387)
	at com.hedera.node.app@0.72.0-SNAPSHOT/com.hedera.node.app.records.impl.BlockRecordManagerImpl.maybeQuiesce(BlockRecordManagerImpl.java:350)
```

### PR DESCRIPTION
**Pull request by lpetrovic05**
closes #23756

### CODE REVIEW

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/component/ComponentWiring.java [hunk 1]
```diff
@@ -237,9 +233,10 @@ public <INPUT_TYPE> InputWire<INPUT_TYPE> getInputWire(
             @NonNull final BiConsumer<COMPONENT_TYPE, INPUT_TYPE> handler, @Nullable final String name) {
 
         Objects.requireNonNull(handler);
-
+        // Since multiple threads can call getInputWire at the same time, we create a new proxy instance every time
+        final WiringComponentProxy<COMPONENT_TYPE> proxy = new WiringComponentProxy<>(clazz);
```
Comment (mxtartaglia-sl) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/component/ComponentWiring.java:237]: I fear this will have a substantial impact on performance.

I'm guessing that the original intent for getInputWire was never to become a runtime API but to be used only at startup. 

I'm guessing that we moved away from that approach since modularization, right?

Comment (abies) [reply platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/component/ComponentWiring.java:237]: I suppose that we still don't use getInputWire on runtime, except for some very rare cases? In such case, it might be enough to write a big javadoc warning ("it is SLOW!") and ignore the issue?

Comment (lpetrovic05) [reply platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/component/ComponentWiring.java:237]: I feel like the whole framework is not thought out completely. `getInputWire` was always intended to be used when soldering, and this is how we use it mostly. Maybe the thing that makes the most sense is to not allow this method to be called after everything has been wired together. So if you need an input wire, you save an instance at startup and use that. But even that doesnt really address everything. So I would rather open a separate ticket for constraining the usage of the framework.

**Review by mxtartaglia-sl — APPROVED** [review]
