### PR TITLE
9512 Prevented MerkleDbStatistics from throwing exceptions if its methods called before `registerMetrics`

### LINKED ISSUE #9512: Reconnect test failed due to IndexOutOfBoundsException from fileStoreHashStoreDisk
### Description

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1698304243316709

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20231026-063724-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-NI-3NReconnect-2k-30m/

```
2023-10-26 07:01:26.880 2341     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 3 -> 1]
2023-10-26 07:01:27.793 2393     ERROR EXCEPTION        <<merkledb: Compacting #0>> CompactionTask: [fileStoreHashStoreDisk] Compaction failed
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.swirlds.merkledb.MerkleDbStatistics.setHashesStoreCompactionTimeMs(MerkleDbStatistics.java:447) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbStatisticsUpdater.setHashesStoreCompactionTimeMs(MerkleDbStatisticsUpdater.java:225) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCompactor.compact(DataFileCompactor.java:431) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbCompactionCoordinator$CompactionTask.call(MerkleDbCompactionCoordinator.java:257) [swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbCompactionCoordinator$CompactionTask.call(MerkleDbCompactionCoordinator.java:250) [swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to reproduce

Nightly regression panel `GCP-Daily-Comp-3NReconnect-15N-4C`

### Additional context

_No response_

### Hedera network

other

### Version

latest

### Operating system

None

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This is a fix for the test failure described in #9512 and is a follow up for https://github.com/hashgraph/hedera-services/pull/9060

**Related issue(s)**:

Fixes #9512 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java [hunk 1]
```diff
@@ -455,6 +458,9 @@ public void setHashesStoreCompactionTimeMs(final Integer compactionLevel, final
      */
     public void setHashesStoreCompactionSavedSpaceMb(final int compactionLevel, final double value) {
         assert compactionLevel >= 1 && compactionLevel <= config.maxCompactionLevel();
+        if (hashesStoreCompactionTimeMsList.isEmpty()) {
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java:461]: It is not a good idea to check `hashesStoreCompactionTimeMsList` when you are going to access `hashesStoreCompactionSavedSpaceMbList`.

Suggested fix:
```
        if (compactionLevel <= hashesStoreCompactionSavedSpaceMbList.size()) {
            hashesStoreCompactionSavedSpaceMbList.get(compactionLevel - 1).update(value);
        }
```
with a possible comment that the method may be called before metrics are registered.

**Review by OlegMazurov — CHANGES_REQUESTED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java:461]: I agree that the comment can be helpful but the suggested fix is not going to work because if the list is empty, it means that `register` method hasn't been called yet and, therefore `hashesStoreCompactionSavedSpaceMbList.get(compactionLevel - 1)` returns null.

Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java:462]: I added comments for these `if` statements.

Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java:462]: Agreed.

Comment (artemananiev) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java]: Why is `hashesStoreCompactionTimeMsList` checked in every method? Should each method check its own metrics list? Assume in the future there are many `registerMetrics()` calls, so lists are populated independently. To me, if a method works with, e.g. `leavesStoreCompactionTimeMsList`, then it should check `leavesStoreCompactionTimeMsList`, not `hashesStoreCompactionTimeMsList`

**Review by artemananiev — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java]: Yes, agreed. I fixed it.

**Review by OlegMazurov — APPROVED** [review]
