### PR TITLE
Remove from BackingAccounts during AutoRemoval.

### LINKED ISSUE #1876: AutoRemoved Account still exists in `BackingAccounts` accounts set.
### Description

When an Expired Account is removed because if exhausting its Grace Period, we remove it from the FCMap but not from the `BackingAccounts`. This causes an NPE when for example doing a cryptoTrasnfer to the autoRemoved expired Account causing a `FAIL_INVALID` response code instead of `INVALID_ACCOUNT_ID`. 

**Possible Resolution**
Also use `BackingAccounts` in `RenewalHelper` to remove the account. 

### Steps to reproduce

1. Create an Account with very short expiry. 'tbd'
2. Wait enough time that the grace period will also pass.
3. Do a transaction that would trigger AutoRenew process which will duly remove the expired account 'tbd' from the FCMap
4. Perform a cryptoTransfer to that 'tbd' and observe `FAIL_INVALID` instead of `INVALID_ACCOUNT_ID`

### Additional context

hgcaa.log

```
2021-07-26 10:24:53.499 ERROR 119  AwareProcessLogic - Possibly CATASTROPHIC failure in txn processing :: sigMap {
  sigPair {
    pubKeyPrefix: "\n"
    ed25519: "\334\230e\n\347\0176M\320\362b\336\t\024RU\a\231Z\036[a\246\225\\Q*H%\354\377\336\002\206Q\235\310_\006\315~,\365\022\036MF\2217\205:\321j\253aC\"\332\377\031\317L\217\001"
  }
}
bodyBytes: "\n\017\n\t\b\210\247\373\207\006\020\342\006\022\002\030\002\022\002\030\003\030\252\220\005\"\002\bx2 \303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216r\023\n\021\n\a\n\003\030\202\b\020\002\n\006\n\002\030\002\020\001"
 ==>> --- ACCOUNTS ---
{}
--- TOKEN RELATIONSHIPS ---
{}
--- NFTS ---
{} ==>>
java.lang.NullPointerException: null
	at com.hedera.services.sigs.metadata.lookups.BackedAccountLookup.safeLookup(BackedAccountLookup.java:45) ~[classes/:?]
	at com.hedera.services.sigs.metadata.DelegatingSigMetadataLookup.accountSigningMetaFor(DelegatingSigMetadataLookup.java:185) ~[classes/:?]
	at com.hedera.services.sigs.order.HederaSigningOrder.includeIfPresentAndNecessary(HederaSigningOrder.java:1034) ~[classes/:?]
	at com.hedera.services.sigs.order.HederaSigningOrder.cryptoTransfer(HederaSigningOrder.java:574) ~[classes/:?]
	at com.hedera.services.sigs.order.HederaSigningOrder.forCrypto(HederaSigningOrder.java:223) ~[classes/:?]
	at com.hedera.services.sigs.order.HederaSigningOrder.keysForOtherParties(HederaSigningOrder.java:147) ~[classes/:?]
	at com.hedera.services.sigs.Rationalization.expandIn(Rationalization.java:150) ~[classes/:?]
	at com.hedera.services.sigs.Rationalization.execute(Rationalization.java:91) ~[classes/:?]
	at com.hedera.services.sigs.HederaToPlatformSigOps.rationalizeIn(HederaToPlatformSigOps.java:139) ~[classes/:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.rationalizeWithPreConsensusSigs(AwareProcessLogic.java:197) ~[classes/:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.doProcess(AwareProcessLogic.java:154) ~[classes/:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.processTxnInCtx(AwareProcessLogic.java:109) ~[classes/:?]
	at com.hedera.services.state.logic.ServicesTxnManager.process(ServicesTxnManager.java:69) ~[classes/:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.incorporateConsensusTxn(AwareProcessLogic.java:96) ~[classes/:?]
	at com.hedera.services.ServicesState.handleTransaction(ServicesState.java:315) ~[classes/:?]
	at com.swirlds.platform.EventFlow.handleTransaction(EventFlow.java:787) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.EventFlow.takeHandlePut(EventFlow.java:1263) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.EventFlow.doCons(EventFlow.java:856) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.common.threading.StoppableThread.doWork(StoppableThread.java:255) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.threading.StoppableThread.run(StoppableThread.java:112) ~[swirlds-common-0.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]

```

### Hedera network

testnet, other

### Version

v0.16.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by anighanta**
**Description**:

Also remove the account that is AutoRemoved because of exhausted grace period from BackingAccounts

**Related issue(s)**:

Fixes #1876 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java [hunk 1]
```diff
@@ -63,6 +64,9 @@
 	private final Supplier<FCMap<MerkleEntityId, MerkleAccount>> accounts;
 	private final Supplier<FCMap<MerkleEntityAssociation, MerkleTokenRelStatus>> tokenRels;
 
+	/* Only needed for interoperability, will be removed during refactor */
+	private final BackingAccounts backingAccounts;
+
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java:69]: Why don't we just use `BackingStore` to avoid the type cast in `ServicesContext`?

**Review by abhishek-hedera — DISMISSED** [review]
LGTM

**Review by tinker-michaelj — APPROVED** [review]
LGTM! If you want the `continuous-integration-gcp` check to pass before merging, you can merge `master` into this branch; CI is fixed there.
