### PR TITLE
Distinguish `0.0.<alias>` from the removal sentinel AccountID `0.0.0`

### LINKED ISSUE #2688: Updating AutoRenew Account on HCS Topic using Alias form Removes AutoRenew Account from Topic instead of Updating
### Description

When attempting to update a HCS renew account to an account using the Alias form, expect the HCS topic to be updated with the new account OR and error thrown.  Instead, a data corruption bug results with the clearing of the auto renew account to NONE.

### Steps to reproduce

Create a topic with an auto renew account
verify the topic info returns the auto renew account
create an account using an alias
update the topic with the auto renew account using the alias form
re-retrieve the top info 
The topic info should include the address for the updated renew account

instead it reports NONE.  Instead of failing, it erased the pre-existing auto renew account.

### Additional context

Integration Test Log:

```
 Update Topic: Can Update Auto Renew Account to Alias Account
   Source: UpdateTopicTests.cs line 277
   Duration: 9.7 sec

  Message: 
Assert.Equal() Failure
Expected: Address { ShardNum = 0, RealmNum = 0, AccountNum = 51520 }
Actual:   (null)

  Stack Trace: 
UpdateTopicTests.CanUpdateAutoRenewAccountToAliasAccount() line 293
UpdateTopicTests.CanUpdateAutoRenewAccountToAliasAccount() line 293
UpdateTopicTests.CanUpdateAutoRenewAccountToAliasAccount() line 293
--- End of stack trace from previous location ---

  Standard Output: 
STARTING SETUP: Test Topic Instance
STARTING SETUP: Test Account Instance
1/2/2022 3:11:29 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1641136289", "nanos": 440070800 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ECDSASecp256k1": "Apfy9d6njL7sZ1o+JHITSkMFF9/zuEY1OkDNnp8D2dyS" }, "initialBalance": "17", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "t9ZczUJN5GKASz9G", "maxAutomaticTokenAssociations": 7 } }
1/2/2022 3:11:29 PM  └─ SIG → { "sigPair": [ { "ed25519": "/GFCOhunDqIJ3HUIgfJkrxd0v7QkBsOyu2lvz4qmzgkIQWV1nh78WGXy3wrePe6ekz/Wqg2oM4noh7S8nIKzDg==" } ] }
1/2/2022 3:11:29 PM  RX:(00)  { }
1/2/2022 3:11:29 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1641136289", "nanos": 440070800 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:30 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:30 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "51518" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
1/2/2022 3:11:30 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1641136289", "nanos": 440070800 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:30 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
1/2/2022 3:11:30 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1641136290", "nanos": 602185600 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "1499" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
1/2/2022 3:11:30 PM  ├─ SIG → { "sigPair": [ { "ed25519": "ubI932MrLjZYYuk/W7JilWI9A21YLbjZy3Ro4sJ/0wen9lNqvPJzss3FL1FKl8cU1xzCLfl7Xvo4qJSXb5trBg==" } ] }
1/2/2022 3:11:30 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnEKEwoMCKKBx44GEIC/kp8CEgMY2wsSAhgDGID4gq0WIgIIeDI3VGVzdCBBY2NvdW50IEluc3RhbmNlOiBDcmVhdGluZyBUZXN0IEFjY291bnQgb24gTmV0d29ya3ITChEKBwoDGNsLEA8KBgoCGAMQEBJECkIaQLmyPd9jKy42WGLpP1uyYpViPQNtWC242ct0aOLCf9MHp/ZTarzyc7LNxS9RSpfHFNccwi35e176OKiUl2+bawY=" } }, "transactionID": { "transactionValidStart": { "seconds": "1641136289", "nanos": 440070800 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:30 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "51518" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "t+WYvHgfitrDTlmZN+ylfFUlSzoCFOt3I/Ign4jYOrNHReFuFrzRrXiNsGFLb1n6", "consensusTimestamp": { "seconds": "1641136290", "nanos": 747304000 }, "transactionID": { "transactionValidStart": { "seconds": "1641136289", "nanos": 440070800 }, "accountID": { "accountNum": "1499" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "52410859", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "1072819" }, { "accountID": { "accountNum": "98" }, "amount": "51338040" }, { "accountID": { "accountNum": "1499" }, "amount": "-52410876" }, { "accountID": { "accountNum": "51518" }, "amount": "17" } ] } } } }
SETUP COMPLETED: Test Account Instance
1/2/2022 3:11:30 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1641136290", "nanos": 652120800 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestTopic Setup: Test Topic: I6Yf0R8zCLm0iIcKHsbg", "consensusCreateTopic": { "memo": "Test Topic: I6Yf0R8zCLm0iIcKHsbg", "adminKey": { "ECDSASecp256k1": "Aw0GgNIxA+WZMm9VvjotiWYDxfDtxU5QEoCxip8WrHD5" }, "submitKey": { "ECDSASecp256k1": "A70BmZ2OvVyMFhJ+JLWMDwL6pdNO6gjX/bvI31GcDPSB" }, "autoRenewPeriod": { "seconds": "7776000" }, "autoRenewAccount": { "accountNum": "51518" } } }
1/2/2022 3:11:30 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Zv0=", "ed25519": "xrgZThPY0O6M6gqsan/GRq9Qlj3JABB8OrYFK7L5qGh1WBckt31gsXFNzPHTWSuWF1OVuC3fB3aunz4RITVtAg==" }, { "pubKeyPrefix": "Aw0=", "ECDSASecp256k1": "a8DzB0y8dW2yWnlnhqF52OyX3HyY9GC4AltyTuOiLaaT5jTxPl8Zoeq3icR6cOsXaOU9QSwSyV/aRQpB931ImQ==" }, { "pubKeyPrefix": "A70=", "ECDSASecp256k1": "/WNYfH1WXep/0KjggBGuAK8ebQEHp9zLQrGjBRQJNFVW2g0FQDsfTqckGKyXddZYSOuDtGG1mlTmlGsTgX1Slw==" }, { "pubKeyPrefix": "Apc=", "ECDSASecp256k1": "hOWKuQ+kFlQabWVaYxKyRt4gQkMzd2sxWiHlWfT8XYrpo27PfLY/Gfc67Shsm6qGkNGD+jHcaWp+Wjlh9aorLQ==" } ] }
1/2/2022 3:11:30 PM  RX:(00)  { }
1/2/2022 3:11:30 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1641136290", "nanos": 652120800 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:30 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:30 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:31 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:31 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "topicID": { "topicNum": "51519" } } } }
1/2/2022 3:11:31 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1641136290", "nanos": 652120800 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:31 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
1/2/2022 3:11:31 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 480321800 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestTopic Setup: Test Topic: I6Yf0R8zCLm0iIcKHsbg", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "1499" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
1/2/2022 3:11:31 PM  ├─ SIG → { "sigPair": [ { "ed25519": "kc7Stnbg+m0ocAgCNAxj+khDGJFjKc3sZ5fSZ1Xp/dBuwDORui/J3tZQUUvptF94xETOtk+4uxZxIPrccSz1Cw==" } ] }
1/2/2022 3:11:31 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CmsKEwoMCKOBx44GEIjChOUBEgMY2wsSAhgDGID4gq0WIgIIeDIxVGVzdFRvcGljIFNldHVwOiBUZXN0IFRvcGljOiBJNllmMFI4ekNMbTBpSWNLSHNiZ3ITChEKBwoDGNsLEA8KBgoCGAMQEBJECkIaQJHO0rZ24PptKHAIAjQMY/pIQxiRYynN7GeX0mdV6f3QbsAzkbovyd7WUFFL6bRfeMREzrZPuLsWcSD63HEs9Qs=" } }, "transactionID": { "transactionValidStart": { "seconds": "1641136290", "nanos": 652120800 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:31 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "topicID": { "topicNum": "51519" } }, "transactionHash": "pRN5WEM5n5jMHjr+OklMKvxPOfG8QkOxMfX1ivS9Njx3GuOTAJoC78cdjVej8kGg", "consensusTimestamp": { "seconds": "1641136291", "nanos": 655491461 }, "transactionID": { "transactionValidStart": { "seconds": "1641136290", "nanos": 652120800 }, "accountID": { "accountNum": "1499" } }, "memo": "TestTopic Setup: Test Topic: I6Yf0R8zCLm0iIcKHsbg", "transactionFee": "24237629", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "450654" }, { "accountID": { "accountNum": "98" }, "amount": "23786975" }, { "accountID": { "accountNum": "1499" }, "amount": "-24237629" } ] } } } }
SETUP COMPLETED: Test Topic Instance
STARTING SETUP: Pay to Alias Account Instance
1/2/2022 3:11:31 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "1499" }, "amount": "-130428336" }, { "accountID": { "alias": "OiECU0hz/57jqzWYm06IPd1gYz6rF5EY+YGETVKeg9f8ZH0=" }, "amount": "130428336" } ] } } }
1/2/2022 3:11:31 PM  └─ SIG → { "sigPair": [ { "ed25519": "UNcecxHt3gFdfcWF4EC0KLgLDDZiysY+LZze62HcI+TTSEdu8y/iu55C048GGxtpRvo/c2UP03JdT08CWuKtAw==" } ] }
1/2/2022 3:11:31 PM  RX:(00)  { }
1/2/2022 3:11:31 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:31 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:31 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:31 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:32 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:32 PM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:33 PM  RX:(05)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:33 PM  RX:(06)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
1/2/2022 3:11:33 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:33 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
1/2/2022 3:11:33 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1641136293", "nanos": 905238400 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "1499" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
1/2/2022 3:11:33 PM  ├─ SIG → { "sigPair": [ { "ed25519": "CQZkCjL17RpkwQGBUmf0FKPCdzM7tzO7/Q/Z5tzxc01h7eSsRNolbuzVUFC5cP/DkST79DK45DD3zsrl52daAw==" } ] }
1/2/2022 3:11:33 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnEKEwoMCKWBx44GEICv068DEgMY2wsSAhgDGID4gq0WIgIIeDI3VGVzdCBBY2NvdW50IEluc3RhbmNlOiBDcmVhdGluZyBUZXN0IEFjY291bnQgb24gTmV0d29ya3ITChEKBwoDGNsLEA8KBgoCGAMQEBJECkIaQAkGZAoy9e0aZMEBgVJn9BSjwnczO7czu/0P2ebc8XNNYe3krETaJW7s1VBQuXD/w5Ek+/QyuOQw987K5ednWgM=" } }, "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:33 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "un2UVLXEJZDk3JWrBm6XYFowGId5F0PLbb4if6M/WLu6YdpeR7A5zif92+v2FWKO", "consensusTimestamp": { "seconds": "1641136293", "nanos": 701110041 }, "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "84434", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "3423" }, { "accountID": { "accountNum": "98" }, "amount": "39499874" }, { "accountID": { "accountNum": "1499" }, "amount": "-130512770" }, { "accountID": { "accountNum": "51520" }, "amount": "91009473" } ] } } } }
1/2/2022 3:11:33 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" }, "nonce": 1 } } }
1/2/2022 3:11:33 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "51520" } } } }
1/2/2022 3:11:33 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" }, "nonce": 1 } } }
1/2/2022 3:11:33 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "7" } } }
1/2/2022 3:11:33 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1641136293", "nanos": 985249700 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "1499" }, "amount": "-7" }, { "accountID": { "accountNum": "3" }, "amount": "7" } ] } } }
1/2/2022 3:11:33 PM  ├─ SIG → { "sigPair": [ { "ed25519": "xUqA89zzt2v7n4vfaKTNcDXastZqKYC6FQDtM7hI2XD9+kAqwb08ZLDwsoxa22oX09H3TYbWE6FRYZPRqjfAAw==" } ] }
1/2/2022 3:11:33 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCKWBx44GEKTv5tUDEgMY2wsSAhgDGID4gq0WIgIIeHITChEKBwoDGNsLEA0KBgoCGAMQDhJECkIaQMVKgPPc87dr+5+L32ikzXA12rLWaimAuhUA7TO4SNlw/fpAKsG9PGSw8LKMWttqF9PR902G1hOhUWGT0ao3wAM=" } }, "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" }, "nonce": 1 } } }
1/2/2022 3:11:34 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "51520" } }, "transactionHash": "z5+9U/qAS9l8Vu5jbeM5L5j+Xui0+aVtnZVtTOwVFpqOszTG4ZMeIwwTnQdlH6zu", "consensusTimestamp": { "seconds": "1641136293", "nanos": 701110040 }, "transactionID": { "transactionValidStart": { "seconds": "1641136291", "nanos": 514555100 }, "accountID": { "accountNum": "1499" }, "nonce": 1 }, "memo": "auto-created account", "transferList": { }, "alias": "OiECU0hz/57jqzWYm06IPd1gYz6rF5EY+YGETVKeg9f8ZH0=" } } }
SETUP COMPLETED: Pay to Alias Account Instance
1/2/2022 3:11:34 PM  TX     → { "consensusGetTopicInfo": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "topicID": { "topicNum": "51519" } } }
1/2/2022 3:11:34 PM  RX:(00)  { "consensusGetTopicInfo": { "header": { "responseType": "COST_ANSWER", "cost": "9" }, "topicID": { "topicNum": "51519" } } }
1/2/2022 3:11:34 PM  TX     → { "consensusGetTopicInfo": { "header": { "payment": { "signedTransactionBytes": "CjcKEgoLCKaBx44GEISo6BQSAxjbCxICGAMYgPiCrRYiAgh4chMKEQoHCgMY2wsQEQoGCgIYAxASEkQKQhpA981MgynhuUqmiILN62wR4SHzfKImka3PE2M8oy8WGZ6gvGqyc+OQJ4g7lWuFlYkwW7wryU0zOxBXUtC6MqPGAA==" } }, "topicID": { "topicNum": "51519" } } }
1/2/2022 3:11:34 PM  RX:(00)  { "consensusGetTopicInfo": { "header": { }, "topicID": { "topicNum": "51519" }, "topicInfo": { "memo": "Test Topic: I6Yf0R8zCLm0iIcKHsbg", "runningHash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "expirationTime": { "seconds": "1648912291", "nanos": 655491461 }, "adminKey": { "ECDSASecp256k1": "Aw0GgNIxA+WZMm9VvjotiWYDxfDtxU5QEoCxip8WrHD5" }, "submitKey": { "ECDSASecp256k1": "A70BmZ2OvVyMFhJ+JLWMDwL6pdNO6gjX/bvI31GcDPSB" }, "autoRenewPeriod": { "seconds": "7776000" }, "autoRenewAccount": { "accountNum": "51518" } } } }
1/2/2022 3:11:34 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1641136294", "nanos": 88699000 }, "accountID": { "accountNum": "1499" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "consensusUpdateTopic": { "topicID": { "topicNum": "51519" }, "autoRenewAccount": { "alias": "OiECU0hz/57jqzWYm06IPd1gYz6rF5EY+YGETVKeg9f8ZH0=" } } }
1/2/2022 3:11:34 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Zg==", "ed25519": "FveQnww4+k/ih8jp2Lb95hhKh37dMrmHDz6QT5RxTR8kttD4NJx/MSPoj1B1SWmzobli3NTcc/xO4lw+fQ3vCQ==" }, { "pubKeyPrefix": "Aw==", "ECDSASecp256k1": "NmqgnaIkV3nNwE7mv2HxQG5yNRT+WE39fK+IMy/8mK/TztI6fSmqB/PZNWpLIVaf9ZW42tH0IroQm0BMJS7cAg==" }, { "pubKeyPrefix": "Ag==", "ECDSASecp256k1": "5XYl2WV/RIMTjW7Z7CmGcgA1/ZUGKg9RPcLiZ/soXLmIaGxT9030LxxHAGacGDC1LRh4eE8Bm/IcfUi7VEGfeg==" } ] }
1/2/2022 3:11:34 PM  RX:(00)  { }
1/2/2022 3:11:34 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1641136294", "nanos": 88699000 }, "accountID": { "accountNum": "1499" } } } }
1/2/2022 3:11:34 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:34 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:34 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:34 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
1/2/2022 3:11:35 PM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
1/2/2022 3:11:35 PM  TX     → { "consensusGetTopicInfo": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "topicID": { "topicNum": "51519" } } }
1/2/2022 3:11:35 PM  RX:(00)  { "consensusGetTopicInfo": { "header": { "responseType": "COST_ANSWER", "cost": "9" }, "topicID": { "topicNum": "51519" } } }
1/2/2022 3:11:35 PM  TX     → { "consensusGetTopicInfo": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCKeBx44GEKjax6MBEgMY2wsSAhgDGID4gq0WIgIIeHITChEKBwoDGNsLEBEKBgoCGAMQEhJECkIaQCyLniVDihMKkHELJ+6EXJFfwSJ9cz19a7gCT2GxHocKiDGLWPLU2DXD4ev/xx8O4hh3q29ErIJPx+6aLcgnnw8=" } }, "topicID": { "topicNum": "51519" } } }
1/2/2022 3:11:35 PM  RX:(00)  { "consensusGetTopicInfo": { "header": { }, "topicID": { "topicNum": "51519" }, "topicInfo": { "memo": "Test Topic: I6Yf0R8zCLm0iIcKHsbg", "runningHash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "expirationTime": { "seconds": "1648912291", "nanos": 655491461 }, "adminKey": { "ECDSASecp256k1": "Aw0GgNIxA+WZMm9VvjotiWYDxfDtxU5QEoCxip8WrHD5" }, "submitKey": { "ECDSASecp256k1": "A70BmZ2OvVyMFhJ+JLWMDwL6pdNO6gjX/bvI31GcDPSB" }, "autoRenewPeriod": { "seconds": "7776000" } } } }
```

### Hedera network

previewnet

### Version

Current PREVIEWNET

### Operating system

Windows

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
- In a `TopicUpdate`, if the auto-renew account is set to an alias `AccountID`, returns `INVALID_ACCOUNT_ID`.

**Related issue(s)**:
- Fixes #2688

### CODE REVIEW

**Review by anighanta — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]

File: hedera-node/src/main/java/com/hedera/services/txns/consensus/TopicUpdateTransitionLogic.java [hunk 1]
```diff
@@ -233,7 +233,7 @@ private void applyNewAutoRenewPeriod(ConsensusUpdateTopicTransactionBody op, Mer
 	}
 
 	private boolean designatesAccountRemoval(AccountID id) {
-		return id.getShardNum() == 0 && id.getRealmNum() == 0 && id.getAccountNum() == 0;
+		return id.getShardNum() == 0 && id.getRealmNum() == 0 && id.getAccountNum() == 0 && id.getAlias().isEmpty();
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/txns/consensus/TopicUpdateTransitionLogic.java:236]: This is repeated. Perhaps we should move this function to a utils class (`MiscUtils`)

File: hedera-node/src/test/java/com/hedera/services/txns/consensus/MerkleTopicUpdateTransitionLogicTest.java [hunk 2]
```diff
@@ -396,6 +397,21 @@ void clearsAutoRenewAccount() throws Throwable {
...
+	void doesntClearAutoRenewAccountIfSentinelWithAliasUsed() throws Throwable {
+		// given:
+		givenExistingTopicWithAutoRenewAccount();
+		givenTransactionChangingAutoRenewAccountWithAliasId();
+
+		// when:
+		subject.doStateTransition();
+
+		// then:
+		var topic = topics.get(EntityNum.fromTopicId(TOPIC_ID));
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/txns/consensus/MerkleTopicUpdateTransitionLogicTest.java:410]: nit: `final`, also remove the unnecessary comments.

**Review by qnswirlds — APPROVED** [review]

**Review by anighanta — APPROVED** [review]
