### PR TITLE
Fix Misc issues in `CryptoTransfer` Logic

### LINKED ISSUE #9024: Fix CustomFee errors when running `royaltyCollectorsCanUseAutoAssociation` in `CryptoTransferSuite`
Fix CustomFee errors when running `royaltyCollectorsCanUseAutoAssociation` in `CryptoTransferSuite`

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fix Misc issues in `CryptoTransfer` Logic
Fixes #9024

### CODE REVIEW

**Review by iwsimon — DISMISSED** [review]
LGTM

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java [hunk 1]
```diff
@@ -226,6 +226,7 @@ private List<TransferStep> decomposeIntoSteps(
         final var customFeeAssessedOps = customFeeStep.assessCustomFees(transferContext);
 
         for (final var txn : customFeeAssessedOps) {
+            steps.add(new AssociateTokenRecipientsStep(txn));
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:229]: 🙌

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
