### PR TITLE
fix: 23930 `apply-block` shouldn't fail fast on hash mismatch

### LINKED ISSUE #23930: `apply-block` shouldn't fail early on hash mismatch
Current implementation of `BlockStreamRecoveryWorkflow#applyBlocks` fails immediately after it recognizes that the resulting state hash doesn't match the provided hash. However, it would be great to have the resulting state anyway to see where exactly the mismatch is.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

Once this PR is merged, `apply-block` will save a resulting state and only then fail on hash mismatch

**Related issue(s)**:

Fixes #23930 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/blockstream/BlockStreamRecoveryWorkflow.java [hunk 1]
```diff
@@ -159,6 +154,11 @@ public void applyBlocks(
         } catch (IOException e) {
             throw new RuntimeException(e);
         }
+
+        if (!expectedRootHash.isEmpty() && !expectedRootHash.equals(rootHash.toString())) {
+            throw new RuntimeException("Excepted and actual hashes do not match. \n Expected: %s \n Actual: %s "
+                    .formatted(expectedRootHash, rootHash));
+        }
```
Comment (anthony-swirldslabs) [inline hedera-state-validator/src/main/java/com/hedera/statevalidation/blockstream/BlockStreamRecoveryWorkflow.java:161]: Note that we'll never know about the mismatched hash if an IOException occurs.

Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/blockstream/BlockStreamRecoveryWorkflow.java:161]: And this is fine because it will result in the script failure anyway.
