### PR TITLE
fix: 10315 fix leftovers (ERCPrecompileSuite fuzzy match)

### LINKED ISSUE #10315: Enable fuzzy record matching for ERCPrecompileSuite
Fixed by:

- https://github.com/hashgraph/hedera-services/pull/11164
- https://github.com/hashgraph/hedera-services/pull/11178
- https://github.com/hashgraph/hedera-services/pull/11179
- https://github.com/hashgraph/hedera-services/pull/11183
- https://github.com/hashgraph/hedera-services/pull/11185

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

This PR adds contract call result for SetApprovalCall, adds gas for TotalSupplyCall and proper is_approval to Erc721TransferFromCall.

**Related issue(s)**:

#10315 

Fixes specs:
someErc721SetApprovedForAllScenariosPass - missing contract call result
getErc721TotalSupply -  missing gas used
getErc20TotalSupply - missing gas used
someErc721NegativeTransferFromScenariosPass - missing is_approval

**Notes for reviewer**:

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java [hunk 1]
```diff
@@ -96,17 +98,17 @@ public PricedResult execute() {
...
+            return completionWith(gasRequirement, recordBuilder, encodedRc(standardized(status)));
         }
     }
 
     @Override
     public @NonNull PricedResult execute(final MessageFrame frame) {
         final var result = execute();
 
-        if (result.fullResult().result().getState().equals(MessageFrame.State.COMPLETED_SUCCESS)) {
+        if (result.responseCode().equals(ResponseCodeEnum.SUCCESS)) {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java:111]: Ah vn catch. 🙌

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/totalsupply/TotalSupplyCall.java [hunk 2]
```diff
@@ -46,6 +46,6 @@ public TotalSupplyCall(
     protected @NonNull FullResult resultOfViewingToken(@NonNull Token token) {
         final var output =
                 TotalSupplyTranslator.TOTAL_SUPPLY.getOutputs().encodeElements(BigInteger.valueOf(token.totalSupply()));
-        return successResult(output, 0L);
+        return successResult(output, 100L);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/totalsupply/TotalSupplyCall.java:49]: Should be `gasCalculator.viewGasRequirement()` but this will be fixed in [this PR](https://github.com/hashgraph/hedera-services/pull/11148) so no worries here.

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, tyvm @JivkoKelchev !

**Comment by MiroslavGatsanoga** [comment]
All specs mentioned in the description are passing locally for me, it seem like we have one new spec introduced in `develop` from another suite failing i.e. `LeakyContractTestsSuite.htsTransferFromForNFTViaContractCreateLazyCreate`, I will integrate it into and fix it in [the PR for `LeakyContractTestsSuite` fuzzy matching](https://github.com/hashgraph/hedera-services/pull/10631).
