### PR TITLE
fix: Create file 0.0.113 during post upgrade if missing 

### LINKED ISSUE #23842: Create file 0.0.113 (simpleFeeSchedule) during post-upgrade if missing

### PR DESCRIPTION
**Pull request by aderevets**
**Description**:
 - When upgrading from a pre-simple-fees version (e.g. v0.71.1), file 0.0.113 doesn't exist in state because the old genesis never created it. doPostUpgradeSetup() only dispatches FileUpdate via tryIfPresent,
  which fails with INVALID_FILE_ID on a non-existent entity. This adds a check in doPostUpgradeSetup() that creates the file via createGenesisSimpleFeesSchedule() if it's missing before attempting any updates.
  - Reverts test script workarounds that skipped upload/validation steps due to this bug.
**Related issue(s)**:

Fixes #23842

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java [hunk 1]
```diff
@@ -457,6 +460,17 @@ ctx, createFileID(filesConfig.hapiPermissions(), config), bytes),
...
+        if (feesConfig.createSimpleFeeSchedule()) {
+            final var simpleFeesFileId = createFileID(filesConfig.simpleFeesSchedules(), config);
+            final var filesState = state.getReadableStates(FileService.NAME)
+                    .<FileID, File>get(V0490FileSchema.FILES_STATE_ID);
+            if (filesState.get(simpleFeesFileId) == null) {
+                log.info(
+                        "Creating simple fee schedule file 0.0.{} (upgrading from pre-simple-fees version)",
+                        filesConfig.simpleFeesSchedules());
+                fileService.fileSchema().createGenesisSimpleFeesSchedule(systemContext);
+            }
```
Comment (ibankov) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java:474]: you can put the file update here in else block instead of checking for the feature flag again

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java [hunk 2]
```diff
@@ -457,6 +460,17 @@ ctx, createFileID(filesConfig.hapiPermissions(), config), bytes),
                         adminConfig.upgradePermissionOverridesFile(),
                         in -> parseConfig("override HAPI permissions", in))));
         final var feesConfig = config.getConfigData(FeesConfig.class);
+        if (feesConfig.createSimpleFeeSchedule()) {
+            final var simpleFeesFileId = createFileID(filesConfig.simpleFeesSchedules(), config);
+            final var filesState = state.getReadableStates(FileService.NAME)
+                    .<FileID, File>get(V0490FileSchema.FILES_STATE_ID);
+            if (filesState.get(simpleFeesFileId) == null) {
+                log.info(
+                        "Creating simple fee schedule file 0.0.{} (upgrading from pre-simple-fees version)",
```
Comment (ibankov) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java]: log {}.{}.{}, file.shard(), file.realm(), file.id() instead of 0.0.{}

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/SimpleFeeScheduleUpgradeTest.java [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+    final Stream<DynamicTest> simpleFeeScheduleUpdatableAfterUpgrade() {
+        return hapiTest(
+                cryptoTransfer(tinyBarsFromTo(GENESIS, FEE_SCHEDULE_CONTROL, 1_000_000_000_000L)),
+                getFileContents(SIMPLE_FEE_SCHEDULE).saveToRegistry("originalSimpleFees"),
+                updateLargeFile(FEE_SCHEDULE_CONTROL, SIMPLE_FEE_SCHEDULE, "originalSimpleFees"),
+                // Verify the file can still be read after update
+                getFileContents(SIMPLE_FEE_SCHEDULE).consumedBy(bytes -> {
+                    assertTrue(bytes.length > 0, "Simple fee schedule should have content after update");
+                }));
+    }
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/SimpleFeeScheduleUpgradeTest.java]: Just put this scenario in 1 HapiTest that can be run on its own and validates that the upgrade path works
