### PR TITLE
Fix E2E tests in TokenUpdatePrecompileSuite

### LINKED ISSUE #9566: Fix E2E tests in TokenUpdatePrecompileSuite
Fix E2E tests in `TokenUpdatePrecompileSuite`

### PR DESCRIPTION
**Pull request by petreze**
**Description**:
This PR fixes `TokenUpdatePrecompileSuite` e2e tests. Some changes were also needed in how we attach the child records and some additional handles inside `TokenKeyCall` in order to catch some of the corner cases

**Related issue(s)**:

Fixes #9566 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractNonRevertibleTokenViewCall.java [hunk 1]
```diff
@@ -64,7 +65,8 @@ protected AbstractNonRevertibleTokenViewCall(
                 .systemOperations()
                 .externalizeResult(
                         contractFunctionResultSuccessFor(gasRequirement, output, contractID),
-                        SystemContractUtils.ResultStatus.IS_SUCCESS);
+                        SystemContractUtils.ResultStatus.IS_SUCCESS,
+                        SUCCESS);
```
[the remark this answers is not in the document]
Comment (petreze) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractNonRevertibleTokenViewCall.java:69]: Because previously it was hardcoded to be `FAIL_INVALID` in [HandleSystemContractOperations](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleSystemContractOperations.java#L122) and in some cases like [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java#L294) and [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java#L298) we expect the specific reason why the contract failed

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java [hunk 2]
```diff
@@ -69,10 +82,51 @@ public TokenKeyCall(
...
-        if (isStaticCall && status != SUCCESS) {
+        if ((isStaticCall && status != SUCCESS) || status == INVALID_TOKEN_ID || status == KEY_NOT_PROVIDED) {
             return revertResult(status, 0);
         }
         return successResult(
                 TOKEN_KEY.getOutputs().encodeElements(status.protoOrdinal(), keyTupleFor(key)), gasRequirement);
     }
+
+    @Override
+    public @NonNull PricedResult execute() {
```
[the remark this answers is not in the document]
Comment (petreze) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java:93]: In some suite test cases we compare the returned status represented in string with the expected string representation like [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java#L260) (more occurrences in the same file) and also in those two cases we would have to fail, so `contractFunctionResultFailedFor()` should be called instead of `contractFunctionResultSuccessFor()`

**Review by kimbor — APPROVED** [review]

**Review by agadzhalov — DISMISSED** [review]
LGTM

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java [hunk 3]
```diff
@@ -69,10 +81,51 @@ public TokenKeyCall(
     private @NonNull FullResult fullResultsFor(
             @NonNull final ResponseCodeEnum status, final long gasRequirement, @NonNull final Key key) {
         // @Future remove to revert #9069 after modularization is completed
-        if (isStaticCall && status != SUCCESS) {
+        if ((isStaticCall && status != SUCCESS) || status == INVALID_TOKEN_ID || status == KEY_NOT_PROVIDED) {
```
Comment (MrValioBg) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java:84]: Why do we need to add INVALID_TOKEN_ID here? 
For non static calls to match mono behaviour in [call-results-snapshot.json](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/resource/call-results-snapshot.json) Invalid token ID should result in top-level SUCCESS status with INVALID_TOKEN_ID without revert

**Review by MrValioBg — CHANGES_REQUESTED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java (hunk 3 above)
Comment (petreze) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java:84]: True but the suite tests expect the call to revert and since the task here is to adapt the logic so that the suites result in success. So basically the expected result from the suite test and the one from [call-results-snapshot.json](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/resource/call-results-snapshot.json) contradict each other

**Review by MrValioBg — DISMISSED** [review]
LGTM! Great work 💯

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java (hunk 3 above)
Comment (MrValioBg) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java:84]: I tested with this branch locally and removed the INVALID_TOKEN_ID from this if check and the test are still passing.

From what I saw from the suite it seems like this check that requires REVERT with INVALID_TOKEN_ID is for Update_TXN and not for tokenKey. Could you double-check, please?

Comment (petreze) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java:84]: Yes, they do indeed. I've removed the mentioned checks. Good catch!

**Review by dikel — APPROVED** [review]
LGTM

**Review by agadzhalov — APPROVED** [review]

**Review by MrValioBg — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
Very nice work, LGTM!
