### PR TITLE
fix: move uptime tracker

### LINKED ISSUE #20952: Move the UptimeTracker
This ticket was created based on an incident in testnet, details in [slack channel](https://swirldslabs.slack.com/archives/C09DURS01S5).

The source of the problem is that the `UptimeTracker` is called from the `SwirldStateManager`. The `UptimeTracker` does not get called until a round has been handled completely. If round handling is slow, the uptime tracker does not get called, even if there are rounds reaching consensus. Since the checking state is based on wall clock time, nodes can go into checking when transaction handling is slow, which is probably not desired. 

If this behavior is not desired (it probably isn't), we should make the calls to `UptimeTracker` independent of transaction handling.

### PR DESCRIPTION
**Pull request by lpetrovic05**
closes #20952

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+ */
+public interface PlatformMonitor {
+    /**
+     * Inform the state machine that time has elapsed
+     *
+     * @param time the current time
+     * @return the new status after processing the time update, or null if the status did not change
+     */
+    @Nullable
+    @InputWireLabel("evaluate status")
```
Comment (mxtartaglia-sl) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java:26]: Should we rename the method to match what it is doing instead of where it is wired? e.g.: evaluateStatus

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java [hunk 2]
```diff
@@ -1,34 +1,155 @@
...
+     * If the logic method throws an {@link IllegalPlatformStatusException}, this method will log the exception and
+     * return null.
+     *
+     * @param action the action to process
+     * @return a new logic object, or null if the logic method threw an exception
      */
     @Nullable
-    @InputWireLabel("PlatformStatusAction")
-    PlatformStatus submitStatusAction(@NonNull final PlatformStatusAction action);
+    private PlatformStatusLogic getNewLogic(@NonNull final PlatformStatusAction action) {
```
Comment (mxtartaglia-sl) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java:80]: Can we change the name to `create` or something like that? 
newLogic makes me think about the old logic we are not aware of anymore

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java [hunk 3]
```diff
@@ -1,34 +1,155 @@
...
+
+        try {
+            if (actionClass == CatastrophicFailureAction.class) {
+                return currentStatusLogic.processCatastrophicFailureAction((CatastrophicFailureAction) action);
+            } else if (actionClass == DoneReplayingEventsAction.class) {
+                return currentStatusLogic.processDoneReplayingEventsAction((DoneReplayingEventsAction) action);
+            } else if (actionClass == FallenBehindAction.class) {
+                return currentStatusLogic.processFallenBehindAction((FallenBehindAction) action);
+            } else if (actionClass == FreezePeriodEnteredAction.class) {
+                return currentStatusLogic.processFreezePeriodEnteredAction((FreezePeriodEnteredAction) action);
```
Comment (mxtartaglia-sl) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java]: Given that we are already in this refactor, a possibility to analyze, maybe for a different issue, is to delegate this logic to each Logic instance instead of this hardcoded if statement.

Comment (mxtartaglia-sl) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java]: Or, at the very least, changing to use  https://openjdk.org/jeps/406

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java (hunk 1 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java:26]: I think I would prefer these heartbeat methods remain like this, I think it will be less confusing. the current name implies that it should be called frequently and that it is dependent on the wall-clock

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java (hunk 2 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java:80]: This is actually old code that I did not change, I just moved it. I don't know if create makes sense either....

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java (hunk 3 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java]: I did the latter, since this PR is not about refactoring the state machine

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java (hunk 1 above)
Comment (mxtartaglia-sl) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java:26]: IMO you need to know a lot so that the implication is evident.
your call

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java (hunk 2 above)
Comment (mxtartaglia-sl) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/status/StatusStateMachine.java:80]: Yes, I see, sorry, it was a paste error, I meant `getPlatformStatusLogic`

**Review by abies — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+    /**
+     * Submit a status action
+     *
+     * @param action the action to submit
+     * @return the new status after processing the action, or null if the status did not change
+     */
+    @Nullable
+    @InputWireLabel("PlatformStatusAction")
+    PlatformStatus submitStatusAction(@NonNull final PlatformStatusAction action);
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java:56]: I'm a little confused by the presence of this method along with the others, like `stateWrittenToDisk`. There is a `PlatformStatusAction` for this - `StateWrittenToDiskAction`. Why do we need both?

Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java:56]: I might understand now. Some actions are very straightforward and simple, so other components send the status action. Others, like the new one that looks for self events, is one we want (at least for now) to be done by the status monitor.

The state to disk one could be eliminated because it's so simple. But it's also fine if it stays.

It would be nice to add some documentation that explains why both kinds of methods are provided in some cases, since it seems strange on first read.

**Review by mxtartaglia-sl — COMMENTED** [review]
Initially, I was ok with the change, then I evaluated the impact of this and the refactor of the Reconnect logic, and realized that I had some issues with the idea. I'm posting the comments with the intent to discuss in a call:

**What I like:** 

The idea of a monitor that one can invoke and tell what happened in the platform.

**What I don't like:**
I’m not convinced the current shape is better. PlatformMonitor became a component with multiple entry points and mixed responsibilities.
It is easier to follow when components have a single input wire for the logic, and the rest are used for updating the internal state, but here, we removed (and consolidated) small transformation methods, and gained additional entrypoints and a more complex API for the component. 
And really, the only object that is actually monitoring is UpTimeTracker; PlatformMonitor is a wrapper/delegator of the state machine. 
I have my doubts about extending the monitor to other use cases. We previously rejected converting FallenBehindManager to a component because doing so forced asynchronous interactions. The same concern applies here in other cases that could use the concept of a monitor.

Have you considered making the UpTimeTracker a component instead? It feels that PlatformMonitor is just there to call UptimeTracker in one specific use case, with no real benefit.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java (hunk 4 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/PlatformMonitor.java:56]: Previously, this transformations was kind of done in the wiring via a method in another component:
`.getTransformedOutput(StateSnapshotManager::toStateWrittenToDiskAction)`
I think this is much clearer and a better place for this responsibility. I did a similar thing with ISS notifications. I think that ideally, `submitStatusAction` should be deprecated and removed in the future. We can discuss this if you like.

**Comment by lpetrovic05** [comment]
> Initially, I was ok with the change, then I evaluated the impact of this and the refactor of the Reconnect logic, and realized that I had some issues with the idea. I'm posting the comments with the intent to discuss in a call:
> 
> **What I like:**
> 
> The idea of a monitor that one can invoke and tell what happened in the platform.
> 
> **What I don't like:** I’m not convinced the current shape is better. PlatformMonitor became a component with multiple entry points and mixed responsibilities. It is easier to follow when components have a single input wire for the logic, and the rest are used for updating the internal state, but here, we removed (and consolidated) small transformation methods, and gained additional entrypoints and a more complex API for the component. And really, the only object that is actually monitoring is UpTimeTracker; PlatformMonitor is a wrapper/delegator of the state machine. I have my doubts about extending the monitor to other use cases. We previously rejected converting FallenBehindManager to a component because doing so forced asynchronous interactions. The same concern applies here in other cases that could use the concept of a monitor.
> 
> Have you considered making the UpTimeTracker a component instead? It feels that PlatformMonitor is just there to call UptimeTracker in one specific use case, with no real benefit.

Lets discuss this on zoom

**Comment by poulok** [comment]
>Lets discuss this on zoom

What was the resolution on this?

**Comment by lpetrovic05** [comment]
> > Lets discuss this on zoom
> 
> What was the resolution on this?

We still don't have one ☹️
