### PR TITLE
chore: Fix StakingSuite in mono and modular service

### LINKED ISSUE #10555: Fix StakingSuite to run against mono and as HapiTest in CI

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes `StakingSuite` and enables all tests in mono-service and mod service

Fixes #10555

### CODE REVIEW

**Review by nathanklick — APPROVED** [review]

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java [hunk 1]
```diff
@@ -35,13 +35,17 @@
...
+import org.apache.logging.log4j.Logger;
 
 /**
  * Base class for both {@link com.hedera.node.app.service.token.records.ParentRecordFinalizer} and {@link
  * com.hedera.node.app.service.token.records.ChildRecordFinalizer}. This contains methods that are common to both
  * classes.
  */
 public class RecordFinalizerBase {
+
+    Logger log = LogManager.getLogger(RecordFinalizerBase.class);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java:48]: Intentional?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java [hunk 2]
```diff
@@ -43,6 +45,7 @@
  * class is not complete, it will be extended with other methods like remove, update etc.,
  */
 public class WritableAccountStore extends ReadableAccountStoreImpl {
+    private static final Logger log = LogManager.getLogger(WritableAccountStore.class);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java:48]: Leftover?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java [hunk 3]
```diff
@@ -391,6 +393,8 @@ private Account buildAccount(CryptoCreateTransactionBody op, HandleContext handl
                 .tinybarBalance(op.initialBalance())
                 .declineReward(op.declineReward())
                 .key(op.keyOrThrow())
+                .stakeAtStartOfLastRewardedPeriod(NOT_REWARDED_SINCE_LAST_STAKING_META_CHANGE)
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java:396]: Ah quite important. 😌

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java [hunk 4]
```diff
@@ -202,13 +203,19 @@ private Account.Builder updateBuilder(
             builder.declineReward(op.declineReward().booleanValue());
         }
         if (op.hasStakedAccountId()) {
+            // 0.0.0 is used a sentinel value for removing staked account id
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:206]: In both the sentinel `if` blocks we will instead reset this `oneof staked_id` to `UNSET` once https://github.com/hashgraph/pbj/issues/160 is closed, right?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeIdChangeType.java [hunk 5]
```diff
@@ -142,6 +141,26 @@ public static StakeIdChangeType forCase(
         }
     }
 
+    /**
+     * Returns the current stakedId case for the given account.
+     * A temporary measure until PBJ supports setting UNSET values for OneOfTypes.
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeIdChangeType.java:146]: Ah nice comment. 💯

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java [hunk 6]
```diff
@@ -28,12 +28,15 @@
...
 import javax.inject.Singleton;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
 
 /**
  * This class manages the current stake period and the previous stake period.
  */
 @Singleton
 public class StakePeriodManager {
+    private static final Logger log = LogManager.getLogger(StakePeriodManager.class);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java:39]: Leftover?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeRewardCalculatorImpl.java [hunk 7]
```diff
@@ -40,10 +43,13 @@ public StakeRewardCalculatorImpl(@NonNull final StakePeriodManager stakePeriodMa
     /** {@inheritDoc} */
     @Override
     public long computePendingReward(
-            @NonNull final Account account,
+            @Nullable final Account account,
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeRewardCalculatorImpl.java:46]: Is it actually acceptable for client code to pass `null` here? (Not immediately obvious when that would happen as part of normal operations.)

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsDistributor.java [hunk 8]
```diff
@@ -97,12 +97,16 @@ public Map<AccountID, Long> payRewardsIfPending(
                     } while (beneficiary.deleted());
                 }
             }
-
-            if (!beneficiary.declineReward() && reward > 0) {
-                // even if reward is zero it will be added to rewardsPaid
-                applyReward(reward, beneficiary, writableStore);
-                rewardsPaid.merge(receiverId, reward, Long::sum);
+            // Even if the account has declineReward set or if reward is 0, it should still
+            // be added to the rewardsPaid map
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsDistributor.java:101]: Good comment; could be improved by adding one more bit of context,
```
            // Even if the account has declineReward set or if reward is 0, it should still
            // be added to the rewardsPaid map because ONLY this map's keys have their
            // stakeAtStartOfLastRewardedPeriod value updated; and for some reward=0
            // situations it is critical to update stakeAtStartOfLastRewardedPeriod
```

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java [hunk 9]
```diff
@@ -72,20 +75,25 @@ public Map<AccountID, Long> applyStakingRewards(final FinalizeContext context) {
...
-        adjustStakeMetadata(writableStore, stakingInfoStore, stakingRewardsStore, consensusNow, rewardsPaid);
+        // Apply all changes related to stakedId changes, and adjust stakedToMe
+        // for all accounts staking to an account
+        adjustStakedToMeForAccountStakees(writableStore);
+        // Adjust stakes for nodes and account's staking metadata
+        adjustStakeMetadata(
+                writableStore, stakingInfoStore, stakingRewardsStore, consensusNow, rewardsPaid, rewardReceivers);
         // Decrease staking reward account balance by rewardPaid amount
         decreaseStakeRewardAccountBalance(rewardsPaid, stakingRewardAccountId, writableStore);
+        log.info("Rewards paid are {}", rewardsPaid);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java:96]: Leftover.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:206]: Yes agreed, will add comment.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java (hunk 6 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java:39]: yes

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java:39]: Removed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java [hunk 10]
```diff
@@ -273,13 +368,22 @@ private void adjustNodeStakes(
...
+     * @return true if the account need to update stakeAtStartOfLastRewardedPeriod, false otherwise
+     */
+    public boolean shouldUpdateStakeAtStartOfLastRewardPeriod(
             @Nullable final Account account,
             final boolean isRewarded,
             final long reward,
             @NonNull final ReadableNetworkStakingRewardsStore stakingRewardStore,
             @NonNull final Instant consensusNow) {
-        if (account == null || account.hasStakedAccountId() || account.declineReward()) {
+        if (account == null || !account.hasStakedNodeId() || account.declineReward()) {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java:386]: Hmm...until we have https://github.com/hashgraph/pbj/issues/160 from PBJ and can truly "unset" the `oneof staking_id`, doesn't this `!account.hasStakedNodeId()` need to be,
```
account.stakedNodeIdOrElse(SENTINEL_NODE_ID) == SENTINEL_NODE_ID
```
to make sure we behave properly for an account that _was_ staking to a node, but then stopped staking?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeRewardCalculatorImpl.java (hunk 7 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeRewardCalculatorImpl.java:46]: yes agreed. It wont be possible. Changed it.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsDistributor.java (hunk 8 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsDistributor.java:101]: Changed. Thank you very much! 💯

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHelper.java [hunk 11]
```diff
@@ -84,18 +88,17 @@ public static Set<AccountID> getPossibleRewardReceivers(final WritableAccountSto
     private static boolean isRewardSituation(
             @NonNull final Account modifiedAccount, @Nullable final Account originalAccount) {
         requireNonNull(modifiedAccount);
-        if (originalAccount == null) {
+        if (originalAccount == null || !originalAccount.hasStakedNodeId()) {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHelper.java:91]: For now again,
```
if (originalAccount == null || originalAccount.stakedNodeIdOrElse(SENTINEL_NODE_ID) == SENTINEL_NODE_ID) {
```

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingUtilities.java [hunk 12]
```diff
@@ -53,7 +54,7 @@ public static boolean hasStakeMetaChanges(
         }
         final var differDeclineReward = originalAccount.declineReward() != modifiedAccount.declineReward();
         final var differStakedNodeId =
-                !originalAccount.stakedNodeIdOrElse(0L).equals(modifiedAccount.stakedNodeIdOrElse(0L));
+                !originalAccount.stakedNodeIdOrElse(-1L).equals(modifiedAccount.stakedNodeIdOrElse(-1L));
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingUtilities.java:57]: Could use `SENTINEL_NODE_ID` here for improved readability.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/TokenSchema.java [hunk 13]
```diff
@@ -265,28 +265,31 @@ public static long[] nonContractSystemNums(final long numReservedSystemEntities)
...
+        final var addressBook = ctx.networkInfo().addressBook();
+        final var numberOfNodes = addressBook.size();
 
         final long maxStakePerNode = ledgerConfig.totalTinyBarFloat() / numberOfNodes;
         final long minStakePerNode = maxStakePerNode / 2;
 
         final var numRewardHistoryStoredPeriods = stakingConfig.rewardHistoryNumStoredPeriods();
         final var stakingInfoState = ctx.newStates().get(STAKING_INFO_KEY);
-        final var rewardSumHistory = new Long[numRewardHistoryStoredPeriods];
+        final var rewardSumHistory = new Long[numRewardHistoryStoredPeriods + 1];
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/TokenSchema.java:279]: Ah nice. 😁

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java [hunk 14]
```diff
@@ -29,12 +29,15 @@
...
 import javax.inject.Singleton;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
 
 /**
  * Validations needed for staking related fields in token operations
  */
 @Singleton
 public class StakingValidator {
+    Logger log = LogManager.getLogger(StakingValidator.class);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java:40]: Leftover.

File: hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/StakingRewardsApi.java [hunk 15]
```diff
@@ -174,6 +178,7 @@ private static long rewardFor(
         if (rewardFrom == 0) {
             return 0;
         }
+        log.info("RewardFrom is {}", rewardFrom);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/StakingRewardsApi.java:181]: Leftover.

File: hedera-node/test-clients/src/itest/java/SequentialSuites.java [hunk 16]
```diff
@@ -47,6 +48,7 @@ static Supplier<HapiSuite>[] sequentialSuites() {
             LeakyCryptoTestsSuite::new,
             LeakySecurityModelV1Suite::new,
             Create2OperationSuite::new,
+            StakingSuite::new
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/itest/java/SequentialSuites.java:51]: FINALLY. 🎉 🙌

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java [hunk 17]
```diff
@@ -83,9 +81,8 @@ final HapiSpec chainIdWorks() {
         final Set<Object> acceptableChainIds = Set.of(devChainId, defaultChainId);
         return defaultHapiSpec("chainIdWorks")
                 .given(
-                        snapshotMode(FUZZY_MATCH_AGAINST_HAPI_TEST_STREAMS),
-                        uploadInitCode(CONTRACT),
-                        contractCreate(CONTRACT))
+                        //                        snapshotMode(FUZZY_MATCH_AGAINST_HAPI_TEST_STREAMS),
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java:84]: I've just started deleting these FYI.

**Review by tinker-michaelj — COMMENTED** [review]
Amazing work @Neeharika-Sompalli , tyvm!

Made some comments, but none really blocking if you want to address in a future PR, lmk.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java:48]: Meh doesn't matter I guess, hard to believe it has any measurable overhead. 😁

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java (hunk 10 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java:386]: Ah yes makes sense. Changed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHelper.java (hunk 11 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHelper.java:91]: Changed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingUtilities.java (hunk 12 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingUtilities.java:57]: Changed. Thanks

File: hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/StakingRewardsApi.java (hunk 15 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/StakingRewardsApi.java:181]: Removed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java (hunk 17 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java:84]: Thanks Michael!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java:48]: Removed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java]: Removed.

**Review by tinker-michaelj — DISMISSED** [review]
LGTM! 🎉

**Review by nathanklick — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
💯

**Review by nathanklick — APPROVED** [review]
