### PR TITLE
Set GENESIS to be 0.0.2 always

### LINKED ISSUE #572: ProtectedFileUpdateSuite - error when default.payer is not 0.0.2
**Summary of the defect**
When default payer is not `0.0.2`, we still use that as `GENESIS` account ID and do file update operations on protected files which will result in `AUTHORIZATION_FAILED` error. 

**How to reproduce (if possible)**
Run `ProtectedFileUpdateSuite` spec with a default.payer set to anything other than 0.0.2 and you can reproduce this error.

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

### PR DESCRIPTION
**Pull request by anighanta**
**Related issue(s)**:
Closes #572 

**Summary of the change**:
Add a sperate property for `GENESIS` with fixing it as account 0.0.2 and renaming default payer to `DEFALUT_PAYER` instead of `GENESIS`

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/file/ProtectedFilesUpdateSuite.java [hunk 1]
```diff
@@ -53,6 +53,7 @@
 import static com.hedera.services.bdd.spec.assertions.AccountInfoAsserts.changeFromSnapshot;
 import static com.hedera.services.bdd.spec.queries.QueryVerbs.getAccountBalance;
 import static com.hedera.services.bdd.spec.queries.QueryVerbs.getFileContents;
+import static com.hedera.services.bdd.spec.transactions.TxnUtils.asId;
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/file/ProtectedFilesUpdateSuite.java:56]: This `import` doesn't seem to be used.

**Review by qnswirlds — COMMENTED** [review]
Some `import` statements seem to be unnecessarily introduced. Please clean up all import statements in all files that are changed. Thanks!

File: .circleci/config.yml [hunk 2]
```diff
@@ -381,7 +381,7 @@ commands:
             - provision-testnet-hosts:
                 liveness-timeout-secs: 120
                 var-file: '<< parameters.var-file >>'
-                var-region: "us-east-1"
+                var-region: "us-west-2"
```
Comment (ljianghedera) [inline .circleci/config.yml:384]: I think we moved the region to "us-east-1" already since last week. Please make sure do we want to move back to "us-west-2" again.

Comment (anighanta) [reply .circleci/config.yml:384]: CI runs this morning failed in us-east-1. so changed to west-2. Once the PR is approved, I will change it back to east-1 before merging.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/file/ProtectedFilesUpdateSuite.java (hunk 1 above)
Comment (anighanta) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/file/ProtectedFilesUpdateSuite.java:56]: Thanks @qnswirlds. fixed it.

**Review by ljianghedera — APPROVED** [review]
LGTM.
