### PR TITLE
Fix the type casting error of Java generics.

### LINKED ISSUE #1782: Most master branch's reconnect JRS tests failed for ClassCastException
### Description

Last night's reconnect JRS regression tests most failed for the same error.

### Steps to reproduce

Follow the slack summary link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625743204145100

and get into any of its result: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210708-073305-GCP-Daily-Reconnect-Correctness-6N-1C/AllProtectedFilesUpdate-NDReconnect-1-16m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

In hapi-client-combined.log, the following error messages:

```
2021-07-08 07:36:10.964 INFO   176  CryptoCreateForSuiteRunner - Spec{name=CreatePayerAccountForEachClient, status=PASSED}
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lcom.hedera.services.bdd.suites.HapiApiSuite; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lcom.hedera.services.bdd.suites.HapiApiSuite; is in unnamed module of loader 'app')
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$collectTargetCategories$12(SuiteRunner.java:585)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hedera.services.bdd.suites.SuiteRunner.collectTargetCategories(SuiteRunner.java:586)
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:544)
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:466)


```

### Hedera network

other

### Version

v0.16.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by ljianghedera**
**Description**:
This PR changes the aof(...) from generic to non-generic method. Seems like java has issue with casting in some special occasions.

https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625842058325100

**Related issue(s)**:

Fixes #1782

Slack report link for passing test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625842058325100
And summary link: https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1625842089325200

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by tinker-michaelj — APPROVED** [review]
LGTM, thanks Leo!

File: test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java [hunk 1]
```diff
@@ -658,12 +658,22 @@ static private String rightPadded(String s, int width) {
 		}
 	}
 
-	@SafeVarargs
-	public static <T> Supplier<T[]> aof(Supplier<T>... items) {
-		return () -> (T[]) List.of(items)
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java:663]: I think the problem is `(T[])` casting is not type-safe. You should also delete the old code, @ljianghedera.

Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java:663]: It seems like so. I googled around, but no particular explanation why. The old code seems to be fine.  
(I kept the old code as a reminder for us to revisit it later when we have spare time.)
