### PR TITLE
06141 - Fix AddressBookTestingToolState errors for test scenarios

### LINKED ISSUE #6141: Fix AddressBookTestingToolState errors for test scenarios
The test scenarios need to be updated to reflect the fact that starting from genesis no longer performs an `SwirldState.updateWeight` call. 

change the numeric indicators for tests to descriptive strings.

### PR DESCRIPTION
**Pull request by edward-swirldslabs**
**Description**:
- changes the names of tests from numbers to descriptions in settings.
- changes `staking` to `weighting` throughout platform.
- adds the PlatformContext as a second argument to the `updateWeight` method in SwirldState.java.
- fixes test conditions in AddresBookTestingToolState.
- updates unit tests.
- replaces the AddressBookConfig argument with PlatformContext in AddressBookInitializer constructor.

**Related issue(s)**:

Fixes #6141

### CODE REVIEW

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java [hunk 1]
```diff
@@ -24,13 +24,13 @@
  *
  * @param softwareVersion
  * 		The integer value of the software version of the AddressBookTestingToolMain SwirldMain application.
- * @param stakingBehavior
- *      The integer value of the staking behavior of the AddressBookTestingToolState SwirldState.
+ * @param weightingBehavior
+ *      The integer value of the weighting behavior of the AddressBookTestingToolState SwirldState.
  * @param testScenario
  *     The integer value of the test scenario being run for validation.
```
Comment (alittley) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java:30]: this is no longer an int

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java [hunk 2]
```diff
@@ -298,23 +311,25 @@ private boolean validateTestScenario() {
         if (platform == null) {
             throw new IllegalStateException("platform is null, init has not been called.");
         }
-        logStakingBehavior.set(false);
-        final int testScenario = testingToolConfig.testScenario();
+        logWeightingBehavior.set(false);
+        final String testScenario = testingToolConfig.testScenario();
         try {
             logger.info(DEMO_INFO.getMarker(), "Validating test scenario {}.", testScenario);
             switch (testScenario) {
```
Comment (alittley) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:318]: Is there a reason that `testScenario` can't be an enum?

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java (hunk 1 above)
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java]: updated.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java (hunk 2 above)
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:318]: turned into an enum of AddressBookTestScenario

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java [hunk 3]
```diff
@@ -482,18 +485,20 @@ private void assertAddressBookFileContent(
...
-     * Creates an AddressBookConfig object with the given forceUseOfConfigAddressBook value.
+     * Creates an PlatformContext object with a configuration able to return AddressBookConfiguration with the given
+     * forceUseOfConfigAddressBook value.
      *
      * @param forceUseOfConfigAddressBook the value to use for the forceUseOfConfigAddressBook property.
-     * @return the AddressBookConfig object.
+     * @return the PlatformContext object.
      */
-    private AddressBookConfig getAddressBookConfig(boolean forceUseOfConfigAddressBook) {
+    private PlatformContext getPlatformContext(boolean forceUseOfConfigAddressBook) {
```
Comment (hendrikebbers) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java:494]: We already have `TestPlatformContextBuilder` that should be used here.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java [hunk 4]
```diff
@@ -24,13 +24,13 @@
...
- *     The integer value of the test scenario being run for validation.
+ *     The string value of the test scenario being run for validation. This must match an enumerated value in {@link AddressBookTestScenario}.
  */
 @ConfigData("addressBookTestingTool")
 public record AddressBookTestingToolConfig(
         @ConfigProperty(defaultValue = "1") int softwareVersion,
-        @ConfigProperty(defaultValue = "0") int stakingBehavior,
-        @ConfigProperty(defaultValue = "0") int testScenario) {}
+        @ConfigProperty(defaultValue = "0") int weightingBehavior,
+        @ConfigProperty(defaultValue = "SKIP_VALIDATION") String testScenario) {}
```
Comment (hendrikebbers) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java:36]: Once https://github.com/hashgraph/hedera-services/issues/6106 is fixed we can easily use the enum type directly. Maybe you can add that as a comment for future.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java [hunk 5]
```diff
@@ -243,17 +251,22 @@ public int getVersion() {
      */
     @Override
     @NonNull
-    public AddressBook updateWeight(@NonNull final AddressBook addressBook) {
+    public synchronized AddressBook updateWeight(
```
Comment (hendrikebbers) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:254]: Can this be called before init has been called? otherwise I do not see why we need to pass the context.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java [hunk 6]
```diff
@@ -97,18 +101,20 @@ public class AddressBookInitializer {
      * @param softwareUpgrade   Indicate that the software version has upgraded.
      * @param signedState       The signed state loaded from disk.  May be null.
      * @param configAddressBook The address book derived from config.txt. Must not be null.
-     * @param addressBookConfig The configuration settings for AddressBooks.
+     * @param platformContext   The context for the platform. Must not be null.
```
Comment (hendrikebbers) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java:104]: @NonNull and @Nullable annotation are part of the JavaDoc. Therefore I do not get why you add the "Must not be null" text to all params.

**Review by hendrikebbers — APPROVED** [review]

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java (hunk 5 above)
Comment (cody-littley) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:254]: This is exactly the problem... we must call this before we construct the `SwirldsPlatform` instance, but `init()` requires an instance of the `SwirldsPlatform` and therefore has to be called afterwards.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java [hunk 7]
```diff
@@ -243,17 +251,22 @@ public int getVersion() {
...
+            @NonNull final AddressBook addressBook, @NonNull final PlatformContext context) {
         Objects.requireNonNull(addressBook, "the address book cannot be null");
-        final int stakingBehavior = testingToolConfig.stakingBehavior();
-        logger.info("updateWeight called in State. Staking Behavior: {}", stakingBehavior);
-        switch (stakingBehavior) {
+        this.context = Objects.requireNonNull(context, "the platform context cannot be null");
+        final int weightingBehavior = context.getConfiguration()
+                .getConfigData(AddressBookTestingToolConfig.class)
+                .weightingBehavior();
+        logger.info("updateWeight called in State. Weighting Behavior: {}", weightingBehavior);
```
Comment (cody-littley) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:261]: missing log marker

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java [hunk 8]
```diff
@@ -644,14 +681,21 @@ private AddressBook parseAddressBook(@NonNull final String addressBookString) th
     @NonNull
     private String getLastAddressBookFileEndsWith(@NonNull final String suffix) throws IOException {
         final Path addressBookDirectory = Path.of(addressBookConfig.addressBookDirectory());
+        File[] files = addressBookDirectory.toFile().listFiles(File::isFile);
```
Comment (cody-littley) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:684]: It's ok if you don't change this since you've already got it working. But in general and in the future, we should try and use the newer `Path` APIs instead of the old `File` ones.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java [hunk 9]
```diff
@@ -644,14 +681,21 @@ private AddressBook parseAddressBook(@NonNull final String addressBookString) th
...
         final AtomicReference<Path> lastAddressBookDebugFile = new AtomicReference<>(null);
-        try (final Stream<Path> files = Files.list(addressBookDirectory)) {
-            files.sorted().forEach(file -> {
-                if (file.toString().endsWith(suffix)) {
-                    lastAddressBookDebugFile.set(file);
+        for (int i = 0; i < files.length; i++) {
+            if (files[i].getName().endsWith(suffix)) {
+                String fileName = files[i].getName();
+                Path lastAddressBookDebugFilePath = lastAddressBookDebugFile.get();
```
Comment (cody-littley) [inline platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:689]:
```suggestion
                final String fileName = files[i].getName();
                final Path lastAddressBookDebugFilePath = lastAddressBookDebugFile.get();
```

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java (hunk 3 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java:494]: replaced the implementation of `getPlatformContext()` to use the `TestPlatformContextBuilder`

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java (hunk 4 above)
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java:36]: added comment.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java (hunk 5 above)
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:254]: The instance of `SwirldState` is not constructed until the platform is started.   `updateWeight()` needs to be called as part of the address book initialization before the platform is constructed.   In order to avoid adding static methods, this was the only way I saw to get the configuration settings to the `SwirldState `as a context for performing the `updateWeight()` operation.   I am open to hearing other solutions.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java (hunk 6 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java:104]: Copilot auto-complete based off of existing comments.   I'll remove them from all comments.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestScenario.java [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.swirlds.demo.addressbook;
+
+public enum AddressBookTestScenario {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestScenario.java:19]: added javadoc comment.

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java (hunk 7 above)
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:261]: added

File: platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java (hunk 8 above)
Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java:684]: I had a [prior implementation that was using `Files.list()` in a try with resources](https://github.com/hashgraph/hedera-services/blob/c94fc287e997dd84489dcd24f4fd1a6a5aa721c3/platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java#L648), but I was baffled why it was not listing all files.  I went with this because I could get it to work.   Leaving it in for now.

**Review by cody-littley — APPROVED** [review]

**Review by hendrikebbers — APPROVED** [review]
