### PR TITLE
fix: streamsAreValid flake from incomplete next-block lookup

### LINKED ISSUE #24709: [Flaky Test] com.hedera.services.bdd.suites.validation.StreamValidationTest#streamsAreValid
## Flaky Test Detected

| Field | Value |
|---|---|
| Module | `test-clients` |
| Class | `com.hedera.services.bdd.suites.validation.StreamValidationTest` |
| Method | `streamsAreValid` |
| First detected | 2026-04-02 |
| Workflow | [Node: Build Application #7430](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/23905434004) |

### Failure Detail (first occurrence)
```
java.lang.AssertionError: Block stream validation failed:
  - Invalid signature in proof (start round #8945) - BlockProof[block=562, proof=OneOf[kind=SIGNED_BLOCK_PROOF, value=TssSignedBlockProof[blockSignature=08000000000000000046766ef16ca30000000000000000000000000000000000000000000000000017f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb08b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e113e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb80606c4a02ea734cc32acd2b02bc28b99cb3e287e85a763af267492ab572e99ab3f370d275cec1da1aaa9075ff05f79be0ce5d527727d6e118cc9cdc6da2e351aadfd9baa8cbdd3a76d429a695160d12c923ac9cc3baca289e193548608b8280119b03caf5ce4e0958f6a7bb5e3c9ca08db15325ed950aeaab2f37b5f8f9ce5cc00f7f76939ea7c6f0c01c5032cfbcd800bd25fb78d1876a50b574aed833b776f73c91bd63e357c9c4a7bee13a42219f9783d04c67d2fb17d1a8f501d1918b4b00a7d8801f6ba1e7babdab256166aa64f0835a16657f8fbd5a3b222c5ca181b21bdf67943c37eec90cf33d875562d7f5409cac1382635dc0058d9775c0094ed9fef97b6596f973817f9d46bcea7ac92c48d8cc65b5071dfbafbce76ecf1d5b4960c708b1477bcff8796b59f561139ac1b4619bbab33ba06252caf3906e6c00fca3fbf90164e82793ec0d58918a080584815ddab1760625fd943c24d347512b3c76e18e4cb9be4caffc80c050f9a3ffc679057a1c12e70370b995afb330178e9ab0cdc951cd57cc7697fdce95422a91b1135506efa8b7e7dc10a629d99556b4ee1b1644492a74815952748c1f1d48d32960c11d9cb84c51a9f4b1b5b2cd64b6e51c0c2ba09a0d89418b380f1d4286c0ddb0d3a6e0e8afe5924a3f5b40cb981977100db45de39572b37d8cf0d12a477f623afe8107039e3c592273b20b43102186eead58c2cd5208e8012aeb1411445045b0046c0a542193d99b8a8c648d5e2d21eccdaa29e77e089afe01f9afa968156b125d03082ecf781d180128b851ae03ffb139d043735d06544fbb3ad669e586db40b835fb452bbbe9330bb5cf1bb03e3d52aa55085cadc0dbe053f80c533ee1b1418428e048325c3d0fa07c2181f18e7e9b3b8338d1846dcdb8220b68b6c4a4d692079f75f4882a... (truncated)
```

### PR DESCRIPTION
**Pull request by AlexKehayov**
## Summary

Fixes #24709 — `StreamValidationTest#streamsAreValid` flaked intermittently on DAB-heavy restart tests (e.g. `DabEnabledUpgradeTest`) with:
```
Invalid signature in proof (start round #X) - BlockProof[block=Y, ...]
```

### Root cause
`StateChangesValidator` maintains an `IncrementalStreamingHasher` that must hold exactly one entry per block; a sampled proof later reconstructs the expected block hash from it. When the validator processes a **complete** block it is not sampling for full verification, it reads that block's own hash from the *next* block's footer field `previousBlockRootHash`.

Since #24147 that lookup assumed the next block is also complete (footer at `items.size() - 2`, proof at `size - 1`). But when the next block is **incomplete** — i.e. flushed at a freeze round before its async hinTS signature arrived, so it ends with `[..., footer]` and no proof — `items.get(size - 2)` is the header, the `hasBlockFooter()` guard returns false, and the code silently fell through. `previousBlockHash` stayed stale, got re-added to `incrementalBlockHashes`, and the chain desynced by one entry for every subsequent iteration.

From that point every sampled proof reconstructed the wrong `prevBlocksRootHash`, producing the wrong `expectedBlockHash` — so valid signatures legitimately failed to verify against them. This matches every observed trait of the flake:
- Random (depends on `PROOF_VERIFICATION_PROB = 0.05` landing on a block after the stale entry).
- All four nodes produced byte-identical blocks (bug is purely validator-side).
- Never hits block 0 or `lastVerifiableIndex` (they are always proof-verified).
- DAB tests only (rapid freezes produce the incomplete-block shape).

### Fix
1. **Extracted helper** `currentBlockHashFromNextBlockFooter(Block)` that checks the last item first (incomplete shape) before falling back to `size - 2` (complete shape). Produces identical output to the old code for complete next-blocks; correctly recovers the hash for incomplete next-blocks.
2. **OOB guard** `else if (i + 1 < n)` — the `hashChainBroken` branch from #24147 forces `shouldVerifyProof=false` regardless of index, so the fall-through can be reached when `i == n - 1`. Previously this would have thrown `IndexOutOfBoundsException`.
3. **Observability** — `logger.warn` when the helper returns `null` so any future malformed next-block shape surfaces instead of silently corrupting the chain.
4. **Comment cleanup** in the `hashChainBroken` branch.

### Regression tests
Added `StateChangesValidatorTest.java` with 6 tests:
- Complete / incomplete / empty / no-footer shape coverage.
- **Equivalence proof**: complete and incomplete next-blocks with the same footer data produce identical helper output — this is the central invariant of the fix.
- **Bug-mechanics proof**: inlines the pre-fix `size - 2` lookup and asserts it finds a `BlockHeader` (not a footer) on an incomplete block, then asserts the helper recovers correctly. A future refactor that accidentally restores the old shortcut would fail this test loudly.

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java [hunk 1]
```diff
@@ -292,24 +292,44 @@ private static Optional<List<Block>> readBlocksFromDisk(@NonNull final HapiSpec
...
                 continue;
             }
-            try {
-                final var block = BlockStreamAccess.blockFrom(candidatePath);
-                final var items = block.items();
-                if (!items.isEmpty() && items.getLast().hasBlockProof()) {
-                    return block;
-                }
+            final List<Path> candidates;
+            try (final var stream = Files.walk(dir)) {
```
Comment (Grigorov-Georgi) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java]: `Files.walk(dir)` is unbounded in depth. Currently `blockStreams/` is one level deep, but you can still add a depth limit `Files.walk(dir, 2)`

**Review by Grigorov-Georgi — APPROVED** [review]

**Comment by Grigorov-Georgi** [comment]
In this CI run, I added targeted instrumentation around the suspected failure points: https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/24848846316/job/72744946430?pr=25095 The logs clearly show both bugs that this PR fixes.

Issue 1: `StateChangesValidator` silently desyncs when a complete block is followed by an incomplete one 

This shows up directly at block 275: 
```ERROR StateChangesValidator - STALE-FALLTHROUGH: block=275 i=275 next=276 nextItemCount=1419 nextLastKind=BLOCK_FOOTER nextHasProof=false nextSize-2Kind=STATE_CHANGES sizeMinus2HasFooter=false previousBlockHash(unchanged)=81b9522b511e370f680db5e28fb7d3b8```

What’s happening here: Block 275 is complete, but it wasn’t sampled for proof verification. Because of that, the validator tries to read its root hash from block 276’s footer. That logic assumes the footer is at `items.get(size - 2)`, which only holds for complete blocks `([..., footer, proof])`. But block 276 is incomplete - its last item is the footer and `size - 2` is `STATE_CHANGES` item. So `hasBlockFooter()` returns false. The code path that updates `previousBlockHash` is skipped. The hash from block 274 is incorrectly reused. You can see the effect in the audit logs: 
```addNodeByHash: i=274 sourceBlockNumber=274 hash=81b9522b511e370f680db5e28fb7d3b8 addNodeByHash: i=275 sourceBlockNumber=275 hash=81b9522b511e370f680db5e28fb7d3b8``` The same hash gets inserted twice into `incrementalBlockHashes`, so block 275 effectively inherits block 274’s hash. From there, the validator is off by one, and a few blocks later (279), a sampled block fails with a `Previous block hash mismatch`.

Issue 2: `StreamValidationOp.findCompleteBlockIn` fails to locate a valid block on any peer

The fallback mechanism is supposed to repair incomplete blocks by pulling a complete version from another node. In this run, it returned null every time. The logs explain why, using block 276 as an example: 
```findCompleteBlockIn: candidate[0] - reason=incomplete block=276 dir=.../node2/data/blockStreams candidatePath=.../node2/.../block-11.12.3/000…276.blk.gz exists=false siblingSubdirs=[block-11.12.1656, block-11.12.1657, block-11.12.5, block-11.12.905] correctSubdirProbe=[block-11.12.5/000…276.blk.gz [itemCount=1420 lastIsProof=true], …]```
Each node writes blocks into a subdirectory based on its own account ID 
```FileBlockItemWriter.nodeScopedBlockDir = blockDir.resolve("block-" + asAccountString(selfAccount))```
So in this case: node0 (the winner, account 11.12.3) writes to `node0/blockStreams/block-11.12.3/` and node2 writes to `node2/blockStreams/block-11.12.5/`. The bug is that the fallback logic reuses the winner’s relative path `block-11.12.3/...` and resolves it under peer directories without modification. On node2, that path simply doesn’t exist, because node2 never writes under `block-11.12.3/`. The diagnostic output confirms this -> `exists=false` for the incorrect path while `correctSubdirProbe` shows the valid block is actually present under `block-11.12.5/`. That means the fallback wasn’t failing because the data was missing - it just couldn’t reach it due to the path construction.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java (hunk 1 above)
Comment (AlexKehayov) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java]: nice catch, change applied

**Review by JivkoKelchev — APPROVED** [review]
LGTM. Ty @AlexKehayov

**Comment by AlexKehayov** [comment]
The flake is already fixed, the current branch does not contain the commit.
