### PR TITLE
fix: matching the signature for NonFungibleTokenInfo and FungibleTokenInfo on failure

### LINKED ISSUE #11132: Matching the signature for NonFungibleTokenInfo and FungibleTokenInfo on failure
If there is a failure when executing the precompile, we seem to be just returning a responseCode to the user by calling Precompile.getFailureResultFor instead of matching the signature for those precompiles which also include a NonFungibleTokenInfo and FungibleTokenInfo.

### PR DESCRIPTION
**Pull request by mustafauzunn**
**Description**:

If there is a failure when executing the precompile, we seem to be just returning a responseCode to the user by calling Precompile.getFailureResultFor instead of matching the signature for those precompiles which also include a NonFungibleTokenInfo and FungibleTokenInfo.

**Related issue(s)**:

Fixes #11132 

**Notes for reviewer**:

In the modularised codebase, it seems that now we are not filling `contractCallResult` on failure. 
For now we comment out these assertions until we have the mod-service contractCallResult management fixed  

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by mhess-swl — APPROVED** [review]
Makes sense to me 👍

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java [hunk 1]
```diff
@@ -286,7 +287,20 @@ final HapiSpec htsTokenAllowance() {
...
+                        //                                asHeadlongAddress(
+                        //
+                        // asAddress(spec.registry().getTokenID(FUNGIBLE_TOKEN))),
+                        //                                HapiParserUtil.asHeadlongAddress(notAnAddress),
+                        //                                        asHeadlongAddress(
+                        //
+                        // asAddress(spec.registry().getAccountID(theSpender))))
+                        //                                        .payingWith(OWNER)
+                        //                                        .via("fakeAddressAllowance")
+                        )))
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java:303]: Is commenting this (and other assertion code blocks) intentional?

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @mustafauzunn !

**Review by stoqnkpL — APPROVED** [review]

**Review by mhess-swl — APPROVED** [review]

**Review by stoqnkpL — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM, nice work @mustafauzunn !

File: hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/codec/EvmEncodingFacade.java [hunk 2]
```diff
@@ -67,6 +68,14 @@ public Bytes encodeGetTokenType(final int tokenType) {
                 .build();
     }
 
+    public Bytes encodeGetTokenTypeFailure(final ResponseCodeEnum status, final int tokenType) {
```
Comment (Nana-EC) [inline hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/codec/EvmEncodingFacade.java:71]: Q: would a smaller footprint and a more general name be an overload or a replacement of the method
```suggestion
   public Bytes encodeGetTokenType(final int tokenType) {
        return encodeGetTokenType(tokenType, SUCCESS.getNumber());
    }

    public Bytes encodeGetTokenType(final int tokenType, final ResponseCodeEnum status) {
```

Same for all the others to reduce duplication and reuse code.

**Review by Nana-EC — COMMENTED** [review]
Maybe consider code reuse

**Review by lukelee-sl — APPROVED** [review]
LGTM.  ty

**Review by mhess-swl — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
