### PR TITLE
fix: set block's timestamp to round's first consensus timestamp

### LINKED ISSUE #22184: Set block's timestamp to the first consensus timestamp of the round
The block stream manager is currently using `round.getConsensusTimestamp()` to assign `blockTimestamp`, which is an artifact of a previous paradigm. The round's consensus timestamp is documented to return the _last_ timestamp, not the first. We need to correct this behavior to the first in order to comply with the block merkle tree design.

### PR DESCRIPTION
**Pull request by mhess-swl**
**Description**:
Moves the block's timestamp from the last consensus timestamp of the round to the earliest consensus timestamp (if one exists). Beginning at the earliest timestamp will align indirect state proofs with the _starting_ state of the block instead of its end. 

Closes #22184

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java [hunk 1]
```diff
@@ -369,6 +370,8 @@ public void init(@NonNull final State state, @Nullable final Bytes lastBlockHash
         requireNonNull(calculatedLastBlockHash);
         this.lastBlockHash = calculatedLastBlockHash;
         previousBlockHashes.addLeaf(calculatedLastBlockHash.toByteArray());
+        consensusTimeLastRound =
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java]: Why do we need this change?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java [hunk 2]
```diff
@@ -419,11 +423,10 @@ public void startRound(@NonNull final Round round, @NonNull final State state) {
                     .number(blockNumber)
                     .hashAlgorithm(SHA2_384)
                     .softwareVersion(platformStateFacade.creationSemanticVersionOf(state))
-                    .blockTimestamp(asTimestamp(blockTimestamp))
+                    .blockTimestamp(blockTimestamp)
                     .hapiProtoVersion(hapiVersion);
             worker.addItem(BlockItem.newBuilder().blockHeader(header).build());
         }
-        consensusTimeLastRound = round.getConsensusTimestamp();
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:426]: This should be updated every round. Why are we removing it here ?

Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:426]: Reverted

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java [hunk 3]
```diff
@@ -1251,6 +1252,36 @@ private static RootAndSiblingHashes combine(
...
 
+    private static Instant firstConsensusTimestampOf(final Round round) {
+        Instant earliestEventTimestamp = null;
+        for (final ConsensusEvent consensusEvent : round) {
+            // Find the earliest event timestamp in the round (possibly needed later)
+            if (earliestEventTimestamp == null) {
+                final var eventTimestamp = consensusEvent.getConsensusTimestamp();
+                if (eventTimestamp != null
+                        && eventTimestamp.isAfter(Instant.EPOCH)
+                        && eventTimestamp.isBefore(round.getConsensusTimestamp())) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:1263]: Isn't this implied already that event timestamps in a round should be before round timestamp, if there re any events?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java [hunk 4]
```diff
@@ -1251,6 +1252,36 @@ private static RootAndSiblingHashes combine(
...
+                    earliestEventTimestamp = eventTimestamp;
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:1264]: can break here?

**Review by Neeharika-Sompalli — APPROVED** [review]
Overall LGTM! Thanks @mhess-swl. Some minor comments

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java (hunk 3 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:1263]: Possibly, but it's not specified in any documentation I can find

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java (hunk 4 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:1264]: Transaction timestamps should still take precedence over event timestamps. Instead of iterating over all transactions, finding no timestamp, then iterating over the events again, there's just one iteration over all events, saving both the earliest transaction timestamp and the earliest event timestamp. So the iteration should continue in case future events have an earlier transaction instead of breaking

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java (hunk 1 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java]: Reverted

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java (hunk 3 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamManagerImpl.java:1263]: If this happens, may be its a bug ? So we could probably log there and remove this check. Can probably fix in next PR
