### PR TITLE
07357 - Removing SelfId From State in StatsSigningTestingToolState

### LINKED ISSUE #7357: Fix the StatsSigningTestingToolState broken by commit 7329
Adding null check on SelfId broke the StatsSigningTestingToolState.

### PR DESCRIPTION
**Pull request by edward-swirldslabs**
Fixes #7357 

Manually verified that the app failed before fix and works after fix.

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]

**Review by alittley — APPROVED** [review]

File: platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java [hunk 1]
```diff
@@ -282,7 +282,7 @@ private synchronized void generateTransactions() {
 
     @Override
     public SwirldState newState() {
-        return new StatsSigningTestingToolState(selfId, () -> transactionPool);
```
Comment (poulok) [inline platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java:285]: can `selfId` be removed from this class as well?

Comment (edward-swirldslabs) [reply platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java:285]: removed

**Review by cody-littley — APPROVED** [review]
