### PR TITLE
fix: Added asserts for threads in all modifying methods

### LINKED ISSUE #10583: Add validation for a modifying thread in VirtualMap
### Problem

This is issue is a follow up for recent ISS investigation. The following exception happened 
```
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.add(VirtualRootNode.java:1582) ~[swirlds-virtualmap-0.43.4.jar:?]
at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.put(VirtualRootNode.java:833) ~[swirlds-virtualmap-0.43.4.jar:?]
at com.swirlds.virtualmap.VirtualMap.put(VirtualMap.java:463) ~[swirlds-virtualmap-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.adapters.VirtualMapLike$1.put(VirtualMapLike.java:99) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.migration.TokenRelStorageAdapter.put(TokenRelStorageAdapter.java:67) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.expiry.TokenRelsListMutation.put(TokenRelsListMutation.java:55) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.expiry.TokenRelsListMutation.put(TokenRelsListMutation.java:27) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.utils.MapValueListUtils.internalAddFirstInPlaceForMapValueList(MapValueListUtils.java:198) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.utils.MapValueListUtils.insertInPlaceAtMapValueListHead(MapValueListUtils.java:48) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.ledger.interceptors.TokenRelsLinkManager.updateLinks(TokenRelsLinkManager.java:81) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.ledger.interceptors.LinkAwareTokenRelsCommitInterceptor.lambda$preview$2(LinkAwareTokenRelsCommitInterceptor.java:120) ~[app-service-mono-0.43.4.jar:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
at com.hedera.node.app.service.mono.ledger.interceptors.LinkAwareTokenRelsCommitInterceptor.preview(LinkAwareTokenRelsCommitInterceptor.java:119) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.ledger.TransactionalLedger.commit(TransactionalLedger.java:240) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.ledger.HederaLedger.commit(HederaLedger.java:206) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.logic.ServicesTxnManager.attemptCommit(ServicesTxnManager.java:149) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.logic.ServicesTxnManager.process(ServicesTxnManager.java:132) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.logic.StandardProcessLogic.doProcess(StandardProcessLogic.java:178) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.logic.StandardProcessLogic.incorporate(StandardProcessLogic.java:137) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.state.logic.StandardProcessLogic.incorporateConsensusTxn(StandardProcessLogic.java:108) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.txns.ProcessLogic.lambda$incorporateConsensus$0(ProcessLogic.java:40) ~[app-service-mono-0.43.4.jar:?]
at com.swirlds.common.system.Round.forEachEventTransaction(Round.java:95) ~[swirlds-common-0.43.4.jar:?]
at com.hedera.node.app.service.mono.txns.ProcessLogic.incorporateConsensus(ProcessLogic.java:39) ~[app-service-mono-0.43.4.jar:?]
at com.hedera.node.app.service.mono.ServicesState.handleConsensusRound(ServicesState.java:302) ~[app-service-mono-0.43.4.jar:?]
at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.43.4.jar:?]
at com.swirlds.platform.state.SwirldStateManagerImpl.handleConsensusRound(SwirldStateManagerImpl.java:210) ~[swirlds-platform-core-0.43.4.jar:?]
at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:414) ~[swirlds-platform-core-0.43.4.jar:?]
at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253) ~[swirlds-common-0.43.4.jar:?]
at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.43.4.jar:?]
at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.43.4.jar:?]
at java.lang.Thread.run(Thread.java:833) 
```

@OlegMazurov conducted thorough investigation and figured out that the best theory explaining this that `VirtualMap` may be used improperly. Specifically, it may happen if there are two concurrent modifications of it, and this data structure is designed so that it does not guarantee correct behavior in this case. That is, there should be only one modifying thread at a time, otherwise it may result in the above-mentioned exception. 

### Solution

To catch situations like this `VirtualRootNode` modifying methods including but not limited to `put` and `add` must have asserts verifying that there is no other thread at the moment executing any modifying method on this `VirtualMap`

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

Added asserts to make sure that modifying methods of `VirtualMap` are never used by different threads at the same time. 

**Related issue(s)**:

Fixes #10583

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java [hunk 1]
```diff
@@ -1520,6 +1532,7 @@ public void warm(final K key) {
     private void add(final K key, final V value) {
         throwIfImmutable();
         assert !isHashed() : "Cannot modify already hashed node";
+        assert currentModifyingThreadRef.compareAndSet(null, Thread.currentThread());
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:1535]: This method is only called from `put()`, which already has the assertion. No need to assert anything here.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java [hunk 2]
```diff
@@ -316,6 +316,11 @@ public static class ClassVersion {
 
     private VirtualMapStatistics statistics;
 
+    /**
+     * This reference is used to assert that there is only one thread modifying the VM at a time.
+     */
+    private AtomicReference<Thread> currentModifyingThreadRef;
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:322]: Why not final?

Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:322]: Please, add a comment to JavaDoc that this field is only used in assertions. If assertions are disabled, the field is always null.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java [hunk 3]
```diff
@@ -840,6 +847,7 @@ public void put(final K key, final V value) {
         final VirtualLeafRecord<K, V> leaf = new VirtualLeafRecord<>(path, key, value);
         cache.putLeaf(leaf);
         statistics.countUpdatedEntities();
+        assert currentModifyingThreadRef.compareAndSet(Thread.currentThread(), null);
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:850]: I assume all these calls to reset `currentMofdifyingThreadRef` to null should be done in try-finally (e.g. there is a `return null` call in the middle of `remove()`, which leaves the ref not null after the method is finished).

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java]: Removed

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java]: Yes. It totally should be

Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java]: Done

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java (hunk 3 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java]: Added try/finally blocks for all asserts

**Review by OlegMazurov — DISMISSED** [review]

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java [hunk 4]
```diff
@@ -880,69 +900,74 @@ public V replace(final K key, final V value) {
...
+        assert currentModifyingThreadRef.compareAndSet(null, Thread.currentThread());
         throwIfImmutable();
         Objects.requireNonNull(key);
 
-        // Verify whether the current leaf exists. If not, we can just return null.
-        VirtualLeafRecord<K, V> leafToDelete = records.findLeafRecord(key, true);
-        if (leafToDelete == null) {
-            return null;
-        }
+        try {
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:907]: Minor: it would look more consistent if the assert at line 903 is right above the opening `try {`, just like you do in other places in this fix. This also builds a clear mental connection with the subsequent `finally{}` block where the atomicRef is cleared.

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java (hunk 4 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java]: Fair enough

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by OlegMazurov — APPROVED** [review]
