### PR TITLE
Fix records for `CryptoTransferSuite`

### LINKED ISSUE #9750: Fuzzy match records with mono-service for CryptoTransferSuite
- [x] transferWithMissingAccountGetsInvalidAccountId(),
- [x]  complexKeyAcctPaysForOwnTransfer(),
- [x]   twoComplexKeysRequired(),
- [x]  specialAccountsBalanceCheck(),
- [x]  tokenTransferFeesScaleAsExpected(),
- [x] okToSetInvalidPaymentHeaderForCostAnswer(),
- [x] baseCryptoTransferFeeChargedAsExpected(),
- [x] autoAssociationRequiresOpenSlots(),
- [x] royaltyCollectorsCanUseAutoAssociation(),
- [x]  royaltyCollectorsCannotUseAutoAssociationWithoutOpenSlots(),
- [x] dissociatedRoyaltyCollectorsCanUseAutoAssociation(),
- [x] hbarAndFungibleSelfTransfersRejectedBothInPrecheckAndHandle(),
- [x] transferToNonAccountEntitiesReturnsInvalidAccountId(),
- [x] nftSelfTransfersRejectedBothInPrecheckAndHandle(),
- [x]  checksExpectedDecimalsForFungibleTokenTransferList(),
- [x] allowanceTransfersWorkAsExpected(),
- [x]  allowanceTransfersWithComplexTransfersWork(),
- [x] canUseMirrorAliasesForNonContractXfers(),
- [x] canUseEip1014AliasesForXfers(),
- [x] cannotTransferFromImmutableAccounts(),
- [x] nftTransfersCannotRepeatSerialNos(),
- [x]  vanillaTransferSucceeds(),
- [x]  aliasKeysAreValidated(),
- [x]  hapiTransferFromForNFTWithCustomFeesWithAllowance(),
- [x] hapiTransferFromForFungibleTokenWithCustomFeesWithAllowance(),
- [x] okToRepeatSerialNumbersInWipeList(),
- [x]  okToRepeatSerialNumbersInBurnList(),
- [x] canUseAliasAndAccountCombinations()

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #9750 
Fixes https://github.com/hashgraph/hedera-services/issues/9822

**Mono-Service Fixes :** 
- Fixes AutoCreationLogic in mono-service to [not charge fees for super user](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java#L201). 
- Sorted automaticTokenAssociations while building records, so to be in a consistent order for differential testing

**Modular Service Fixes:** 
- Enable records for `CryptoTransferSuite`
- Fixes all conditions to not charge fees [when super user is the payer](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java#L404) in `HandleWorkflow`
- When nonce is increased in transaction record in `RecordStreamItem` we need to increase the noce in the synthetic transaction body submitted as per mono-service. Fixed using [syncBodyIdFromRecordId()](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java#L382)
- In mono-service exchangeRate is not set in precedingChild records, [fixed here.](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java#L238) This should be reverted after differential testing.
- Sorts automatic-token-associations while writing to records in both[ mono-service](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java#L310) and [modular service](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java#L255) to be in deterministic order.
- When a CryptoTransfer transaction including customFees fails while assessing customFees, [we should still charge ](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java#L537)fees with SubType `TOKEN_FUNGIBLE_COMMON_WITH_CUSTOM_FEES` or `TOKEN_NON_FUNGIBLE_UNIQUE_WITH_CUSTOM_FEES`, which is twice as expensive as default crypto transfer. Chose to use `TOKEN_FUNGIBLE_COMMON_WITH_CUSTOM_FEES` since both are same values here
- While creating transfer lists in RecordFinalizerBase, when receiverAccountId and SenderAccountId are the same , we [should not be adding](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java#L200) to the TransferList
- Fixed setting `newTotalSupply` field in TokenWipe records
- Since we don't write any records if there are any failures in Ingest in mono-service and we write them out in modular service,[ ignored comparing records ](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java#L290)that are in `spec.streamlinedIngestChecks` added a new SnapShotModeOp to not skip them if needed using `EXPECT_STREAMLINED_INGEST_RECORDS`
- feeCollector should not be automatically associated when specified in royalty fee. So, deleted from adding to requireAutomaticAssociations [here](https://github.com/hashgraph/hedera-services/blob/83550e54425d3a5273b674cc37173858a609b699/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java#L277)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 1]
```diff
@@ -399,17 +399,19 @@ private void handleUserTransaction(
...
-                        feeAccumulator.chargeNetworkFee(creator.accountId(), fees.networkFee());
-                    } else if (validationResult.status() == PAYER_UNWILLING_OR_UNABLE_TO_PAY_SERVICE_FEE) {
-                        // We do not charge partial service fees; if the payer is unwilling or unable to cover
-                        // the entire service fee, then we only charge network and node fees (prioritizing
-                        // the network fee in case of a very low payer balance)
-                        feeAccumulator.chargeFees(payer, creator.accountId(), fees.withoutServiceComponent());
-                    } else {
-                        feeAccumulator.chargeFees(payer, creator.accountId(), fees);
+                    // If the payer is authorized to waive fees, then we don't charge them
+                    if (!authorizer.hasWaivedFees(payer, transactionInfo.functionality(), txBody)) {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:404]: Looks like we make this same `hasWaivedFees()` call several times in the `handleUserTransaction()` lexical scope; is it possible to define a `boolean areFeesWaived` once and re-use?

(Can't imagine it matters for performance, but imo readability improves if possible.)

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java [hunk 2]
```diff
@@ -375,8 +377,10 @@ public Result build() {
         int count = precedingTxnRecordBuilders == null ? 0 : precedingTxnRecordBuilders.size();
         for (int i = count - 1; i >= 0; i--) {
             final var recordBuilder = precedingTxnRecordBuilders.get(i);
-            records.add(
-                    recordBuilder.transactionID(idBuilder.nonce(i + 1).build()).build());
+            records.add(recordBuilder
+                    .transactionID(idBuilder.nonce(i + 1).build())
+                    .syncBodyIdFromRecordId()
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java:382]: Ah very nice. 🙌

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java [hunk 3]
```diff
@@ -243,7 +251,10 @@ public SingleTransactionRecord build() {
         final Timestamp consensusTimestamp = HapiUtils.asTimestamp(consensusNow);
         final Timestamp parentConsensusTimestamp =
                 parentConsensus != null ? HapiUtils.asTimestamp(parentConsensus) : null;
-
+        // sort the automatic associations to match the order of mono-service records
+        automaticTokenAssociations.sort(
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:255]: I'd lean toward making defining this `Comparator` in a `private static final` field.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java [hunk 4]
```diff
@@ -342,6 +353,35 @@ public SingleTransactionRecordBuilderImpl transactionID(@NonNull final Transacti
...
+            final var newBodyBytes = TransactionBody.PROTOBUF.toBytes(body);
+            final var newSignedTransaction =
+                    SignedTransaction.newBuilder().bodyBytes(newBodyBytes).build();
+            final var signedTransactionBytes = SignedTransaction.PROTOBUF.toBytes(newSignedTransaction);
+            this.transaction = Transaction.newBuilder()
+                    .signedTransactionBytes(signedTransactionBytes)
+                    .build();
+            return this;
+        } catch (Exception e) {
+            return this;
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:381]: Ofc it's all-but-impossible to reach this `catch` clause; but if we _did_, we'd prob want to propagate `e` via  `throw new IllegalStateException(e)` or the like.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java [hunk 5]
```diff
@@ -303,7 +304,14 @@ public void trackRewardPayment(final long accountNum, final long amount) {
      * @return the created auto-associations
      */
     public List<FcTokenAssociation> getTrackedAutoAssociations() {
-        return autoAssociations.isEmpty() ? Collections.emptyList() : new ArrayList<>(autoAssociations);
+        final var newAssociations = new ArrayList<>(autoAssociations);
+        // Sort the associations by token id and then by account id to ensure a consistent order
+        // to be matched with modular service
+        if (!autoAssociations.isEmpty()) {
+            newAssociations.sort(
+                    Comparator.comparingLong(FcTokenAssociation::token).thenComparingLong(FcTokenAssociation::account));
```
Comment (tinker-michaelj) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java:312]: Same comment re: `private static final`.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java [hunk 6]
```diff
@@ -160,6 +161,10 @@ public void doZeroSum(final List<BalanceChange> changes) {
             adjustBalancesAndAllowances(changes);
             if (autoCreationFee > 0) {
                 payAutoCreationFee(autoCreationFee);
+            }
+            // If the auto creation is successful submit the records to historian,
```
Comment (tinker-michaelj) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java:165]: Nice comment.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java [hunk 7]
```diff
@@ -95,12 +95,13 @@ public AccountID create(@NonNull final Bytes alias, int maxAutoAssociations) {
                 key -> handleContext.verificationFor(key).passed();
         // dispatch the auto-creation record as a preceding record
         final var childRecord = handleContext.dispatchRemovablePrecedingTransaction(
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java:97]: Haha mono-service record stream items are too much sometimes. 😝

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java [hunk 8]
```diff
@@ -275,7 +275,6 @@ private void validateRoyaltyFeeForCreation(
                 validateTrue(denominatingTokenId.tokenNum() != 0, CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON);
                 validateExplicitTokenDenomination(
                         fee.feeCollectorAccountId(), denominatingTokenId, tokenRelationStore, tokenStore);
-                fees.add(fee);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:278]: What's the significance of this deletion?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotMatchMode.java [hunk 9]
```diff
@@ -38,4 +38,11 @@ public enum SnapshotMatchMode {
      * <p>We need this to let such specs to opt out of auto record snapshots, since fuzzy-matching would never pass.
      */
     FULLY_NONDETERMINISTIC,
+    /**
+     * Some of the ingest checks in mono-service are moved into pureChecks or handle in modular service. So any
+     * response code added in spec.streamlinedIngestChecks will not produce a record in mono-service, as it is rejected in ingest.
+     * But in modular service we produce a record. This will not cause any issue for differential testing, because we test
+     * transactions that have reached consensus. Use this snapshot mode to ignore the extra produced records during fuzzy matching.
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotMatchMode.java:45]: Comment is out-of-date here; probably intended to be,
```
Use this snapshot mode to still fuzzy-match against records whose `receipt#status` would have been rejected in pre-check by mono-service.
```

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java [hunk 10]
```diff
@@ -177,6 +178,7 @@ public static void main(String... args) throws IOException {
                 dumpLoc.write("➡️\n\n");
                 dumpLoc.write(item.itemRecord() + "\n\n");
             }
+            dumpLoc.flush();
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java:181]: @david-bakin-sl pointed out if we use a `try`-with-resources here we don't need this; upstream branch should work now without the explicit `flush()`.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java [hunk 11]
```diff
@@ -315,12 +327,14 @@ public void finishLifecycle() {
...
      * @param postPlaceholderItems the list of parsed items from the record stream
+     * @param spec
      */
-    private void fuzzyMatchAgainstSnapshot(@NonNull final List<ParsedItem> postPlaceholderItems) {
+    private void fuzzyMatchAgainstSnapshot(@NonNull final List<ParsedItem> postPlaceholderItems, final HapiSpec spec) {
         log.info("Now fuzzy-matching {} post-placeholder records against snapshot", postPlaceholderItems.size());
         final var itemsFromSnapshot = snapshotToMatchAgainst.parsedItems();
         final var minItems = Math.min(postPlaceholderItems.size(), itemsFromSnapshot.size());
         final var snapshotPlaceholderNum = snapshotToMatchAgainst.getPlaceholderNum();
+        final var streamLinedIngestChecks = spec.setup().streamlinedIngestChecks();
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java:337]: This assignment is unused, right?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java (hunk 8 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:278]: FeeCollector specified in `fallBackFee` should not be automatically associated as I see it. So, deleted from adding to requireAutomaticAssociations

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java (hunk 10 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java:181]: Ah awesome will update it

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java [hunk 12]
```diff
@@ -249,6 +252,7 @@ private HapiSpec okToRepeatSerialNumbersInWipeList() {
         final var ownerWith4AutoAssoc = "ownerWith4AutoAssoc";
         return defaultHapiSpec("OkToRepeatSerialNumbersInWipeList")
                 .given(
+                        snapshotMode(FUZZY_MATCH_AGAINST_MONO_STREAMS),
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:255]: Left here by accident?

Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:255]: No, to run in CI. Doesn't it work ?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java [hunk 13]
```diff
@@ -243,7 +251,10 @@ public SingleTransactionRecord build() {
         final Timestamp consensusTimestamp = HapiUtils.asTimestamp(consensusNow);
         final Timestamp parentConsensusTimestamp =
                 parentConsensus != null ? HapiUtils.asTimestamp(parentConsensus) : null;
-
+        // sort the automatic associations to match the order of mono-service records
+        automaticTokenAssociations.sort(
+                Comparator.<TokenAssociation>comparingLong(a -> a.tokenId().tokenNum())
+                        .thenComparingLong(a -> a.accountIdOrThrow().accountNum()));
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:257]: Can we find a single place to use this instead of spreading it across different files?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java (hunk 8 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:278]: Ohhh...got it, that makes sense.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java [hunk 14]
```diff
@@ -342,6 +353,35 @@ public SingleTransactionRecordBuilderImpl transactionID(@NonNull final Transacti
...
+            final var existingTransactionBody =
+                    TransactionBody.PROTOBUF.parse(signedTransaction.bodyBytes().toReadableSequentialData());
+            final var body = existingTransactionBody
+                    .copyBuilder()
+                    .transactionID(newTransactionID)
+                    .build();
+            final var newBodyBytes = TransactionBody.PROTOBUF.toBytes(body);
+            final var newSignedTransaction =
+                    SignedTransaction.newBuilder().bodyBytes(newBodyBytes).build();
+            final var signedTransactionBytes = SignedTransaction.PROTOBUF.toBytes(newSignedTransaction);
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:375]: Do key checks still pass if we modify the signed bytes?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 13 above)
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:257]: Also, given this `sort()`, appears we need to change `TokenCreateSpecs.validateNewTokenAssociations()` to assert 
```
                        getTxnRecord(creationTxn)
                                .hasPriority(recordWith()
                                        .autoAssociated(accountTokenPairs(List.of(
                                                Pair.of(fractionalCollector, A_TOKEN),
                                                Pair.of(selfDenominatedFixedCollector, A_TOKEN),
                                                Pair.of(otherSelfDenominatedFixedCollector, A_TOKEN),
                                                Pair.of(treasury, A_TOKEN))))),
```
[here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java#L210).

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java (hunk 12 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:255]: The `itest` and `eet` [`TargetNetworkType`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/TargetNetworkType.java#L36)'s are `CI_DOCKER_NETWORK`, whose streams are (currently) never fuzzy-matched against snapshots.

But if we want our CI `@HapiTest` to fuzzy-match its streams against the snapshot, we need to use `FUZZY_MATCH_AGAINST_HAPI_TEST_STREAMS`.

Created https://github.com/hashgraph/hedera-services/issues/9811 to eliminate all these extra parameters and properties.

Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:255]: Created https://github.com/hashgraph/hedera-services/issues/9812 so we won't have to explicitly opt-in each `HapiSpec` to fuzzy-matching in CI.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:404]: Agreed. Fixed. Thanks Michael

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 3 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:255]: Makes sense. Done. Thanks

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java (hunk 12 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:255]: Got it. Will remove these then 😄  Thank you very much

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java [hunk 15]
```diff
@@ -385,9 +389,11 @@ public Result build() {
         count = childRecordBuilders == null ? 0 : childRecordBuilders.size();
         for (int i = 0; i < count; i++) {
             final var recordBuilder = childRecordBuilders.get(i);
-            records.add(recordBuilder
+            final var maybeRecord = recordBuilder
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java:392]: yes, name came while merging conflicts removed

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:404]: Done. Thanks @mhess-swl

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 13 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:257]: Declared as private static variable in same file. 
Do you have any recommendations where to move it ? It is just used in this file afaik 🤔 . Other one was `FcTokenAssociation`

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:257]: Ah thank you 🙏 for checking this. Changed

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 14 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:384]: I don't think it should. But some HapiTests are failing. Will look. Thanks!

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java [hunk 16]
```diff
@@ -160,6 +161,10 @@ public void doZeroSum(final List<BalanceChange> changes) {
...
+            // even if auto creation fee is 0 (which can be the case if the payer is a superuser)
+            if (hasSuccessfulAutoCreation) {
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java:167]: It should not have any major effect on anything. Since we don't use Genesis as payer anywhere

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java (hunk 7 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java:97]: True true 😄

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java (hunk 5 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java]: Fixed

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java:167]: Seems like a good idea. Will open a different issue and PR

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 17]
```diff
@@ -399,19 +400,22 @@ private void handleUserTransaction(
...
+                            // We do not charge partial service fees; if the payer is unwilling or unable to cover
+                            // the entire service fee, then we only charge network and node fees (prioritizing
+                            // the network fee in case of a very low payer balance)
+                            feeAccumulator.chargeFees(payer, creator.accountId(), fees.withoutServiceComponent());
+                        } else {
+                            feeAccumulator.chargeFees(payer, creator.accountId(), fees);
+                        }
                     }
                 } catch (final HandleException ex) {
+                    ex.printStackTrace();
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:418]: Leftover.

Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:418]: `log.error()` instead? Curious why the use of `printStackTrace()`?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 18]
```diff
@@ -477,8 +483,11 @@ private void handleUserTransaction(
                     dualStateUpdateFacility.handleTxBody(stack, dualState, txBody);
 
                 } catch (final HandleException e) {
+                    e.printStackTrace();
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:486]: Same here, log instead of stdout?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java:167]: Opened this PR https://github.com/hashgraph/hedera-services/tree/9822-D-fix-auto-creation-fees

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java [hunk 19]
```diff
@@ -210,10 +210,10 @@ private HapiSpec validateNewTokenAssociations() {
                         getTxnRecord(creationTxn)
                                 .hasPriority(recordWith()
                                         .autoAssociated(accountTokenPairs(List.of(
-                                                Pair.of(treasury, A_TOKEN),
                                                 Pair.of(fractionalCollector, A_TOKEN),
                                                 Pair.of(selfDenominatedFixedCollector, A_TOKEN),
-                                                Pair.of(otherSelfDenominatedFixedCollector, A_TOKEN))))),
+                                                Pair.of(otherSelfDenominatedFixedCollector, A_TOKEN),
+                                                Pair.of(treasury, A_TOKEN))))),
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java:216]: What's the difference having this here as opposed to underneath `.autoAssociated(...)`?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 17 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:418]: ah yes 😓

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: No it was all debugging. Removed it. Thanks

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 18 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: Removed Thanks!

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java [hunk 20]
```diff
@@ -303,7 +306,13 @@ public void trackRewardPayment(final long accountNum, final long amount) {
      * @return the created auto-associations
      */
     public List<FcTokenAssociation> getTrackedAutoAssociations() {
-        return autoAssociations.isEmpty() ? Collections.emptyList() : new ArrayList<>(autoAssociations);
+        final var newAssociations = new ArrayList<>(autoAssociations);
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java:309]: yeah I just moved it inside if condition 😄

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java (hunk 19 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java:216]: Since we sorted all auto-associations, it fails in assertions.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java]: Threw RunTimeException

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (mhess-swl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java:167]: 🙌

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 13 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java]: Oh I didn't realize these were different classes. One has `Fc` in front 😇 my mistake!

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 14 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:384]: This isn't an issue because this transaction is a synthetic child transaction, not the bytes that the user signed.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java [hunk 21]
```diff
@@ -344,6 +362,35 @@ public SingleTransactionRecordBuilderImpl transactionID(@NonNull final Transacti
...
+            this.transaction = Transaction.newBuilder()
+                    .signedTransactionBytes(signedTransactionBytes)
+                    .build();
+            return this;
+        } catch (Exception e) {
```
Comment (iwsimon) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:389]: A few updates here for the transaction. Maybe we want to catch the specific exception and do something, log. If just throwing a RuntimeException, what's going to happen to the calling code if failed?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java [hunk 22]
```diff
@@ -202,6 +202,8 @@ public Fees calculate() {
         failIfLegacyOnly();
         // Use the "hapi-fees" module to calculate the fees, and convert to one of our "Fees" objects.
         final var overflowCalc = new OverflowCheckingCalc();
+        System.out.println("Usage: " + usage);
+        System.out.println("FeeData: " + feeData);
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java:206]: debugging lines?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java [hunk 23]
```diff
@@ -495,19 +504,42 @@ public Fees calculateFees(@NonNull final FeeContext feeContext) {
...
         /* Get subType based on the above information */
         final var subType = getSubType(
-                numNftOwnershipChanges, totalTokenTransfers, customFeeHbarTransfers, customFeeTokenTransfers);
-        return feeContext
+                numNftOwnershipChanges,
+                totalTokenTransfers,
+                customFeeHbarTransfers,
+                customFeeTokenTransfers,
+                triedAndFailedToUseCustomFees);
+        System.out.println("subType: " + subType);
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:512]: debugging?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java [hunk 24]
```diff
@@ -495,19 +504,42 @@ public Fees calculateFees(@NonNull final FeeContext feeContext) {
...
+        final var ans = feeContext
                 .feeCalculator(subType)
                 .addBytesPerTransaction(bpt)
                 .addRamByteSeconds(rbs * USAGE_PROPERTIES.legacyReceiptStorageSecs())
                 .calculate();
+        System.out.println("  -> " + ans.totalFee());
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:518]: debugging?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java [hunk 25]
```diff
@@ -495,19 +504,42 @@ public Fees calculateFees(@NonNull final FeeContext feeContext) {
...
+        return ans;
     }
 
+    /**
+     * Get the subType based on the number of NFT ownership changes, number of fungible token transfers,
+     * number of custom fee hbar transfers, number of custom fee token transfers and whether the transaction
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:524]: `and whether the transaction ` ...? Is this supposed to be the end of the sentence?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java [hunk 26]
```diff
@@ -125,6 +125,10 @@ public long forActivityBasedOp(
             throws Throwable {
         final FeeData activityMetrics = metricsFor(txn, numPayerSigs, metricsCalculator);
         final var subType = activityMetrics.getSubType();
+        if (op == HederaFunctionality.CryptoTransfer) {
+            System.out.println("subType: " + subType);
+            System.out.println("CryptoTransfer fee: " + forOp(op, subType, activityMetrics));
+        }
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java:131]: debugging?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java [hunk 27]
```diff
@@ -538,6 +538,7 @@ public static FeeData usageEstimate(final TransactionBody txn, final SigValueObj
 
         final var accumulator = new UsageAccumulator();
         cryptoOpsUsage.cryptoTransferUsage(suFrom(svo), xferUsageMeta, baseMeta, accumulator);
+        System.out.println("UsageAccumulator: " + accumulator);
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java:541]: debugging?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java [hunk 28]
```diff
@@ -153,7 +157,9 @@ public long forActivityBasedOp(
     private FeeData metricsFor(final Transaction txn, final int numPayerSigs, final ActivityMetrics metricsCalculator)
             throws Throwable {
         final SigValueObj sigUsage = sigUsageGiven(txn, numPayerSigs);
+        System.out.println(sigUsage);
         final TransactionBody body = CommonUtils.extractTransactionBody(txn);
+        System.out.println(body);
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java:162]: debugging?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java (hunk 22 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java:206]: yes removed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java (hunk 23 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:512]: yes removed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java (hunk 24 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:518]: yes removed

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java (hunk 25 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:524]: fixed. thanks

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java (hunk 26 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java:131]: yes removed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java (hunk 27 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java:541]: yes removed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java (hunk 28 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java:162]: yes removed

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 21 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:389]: I see we are throwing RuntimeException in one other place in this class, so chose to do that 🤔

**Review by tinker-michaelj — DISMISSED** [review]
LGTM!

**Review by tinker-michaelj — APPROVED** [review]
LGTM! 🎉
