### PR TITLE
06010 - pcli event stream info command to accept timestamp

### LINKED ISSUE #5308: Disaster handling and healing
### Event Recovery
- [x] https://github.com/swirlds/swirlds-platform/issues/6004
- [x] https://github.com/swirlds/swirlds-platform/issues/6276
- [x] https://github.com/swirlds/swirlds-platform/issues/6267
- [x] https://github.com/swirlds/swirlds-platform/issues/6311
- [x] https://github.com/swirlds/swirlds-platform/issues/6295
- [x] https://github.com/swirlds/swirlds-platform/issues/6313
- [x] https://github.com/swirlds/swirlds-platform/issues/6338
- [ ] https://github.com/swirlds/swirlds-platform/issues/6666
- [ ] https://github.com/swirlds/swirlds-platform/issues/6401
- [ ] https://github.com/swirlds/swirlds-platform/issues/6697

### Emergency State Loading / Reconnect
  - [x] https://github.com/swirlds/swirlds-platform/issues/6057
  - [x] https://github.com/swirlds/swirlds-platform/issues/6311
  - [ ] Emergency reconnect breaks the event stream (what do we do about this?)
  - [ ] Tom should test every release (Lazar)
    
### ISS Healing
- [x] https://github.com/swirlds/swirlds-platform/issues/6072
- [x] https://github.com/swirlds/swirlds-platform/issues/5987 ([regression ticket 2786](https://github.com/swirlds/swirlds-platform-regression/issues/2786))

### Additional tasks
- [ ] Platform should probably have a status for ISS, that way we can stop accepting new transactions and also notify the app. (discuss with Cody)

### NMT Tickets
- [ ] https://github.com/swirlds/swirlds-docker/issues/365

### Services Tickets
- [ ] https://github.com/hashgraph/hedera-services/issues/4132
- [ ] https://github.com/hashgraph/hedera-services/issues/4142
- [x] https://github.com/hashgraph/hedera-services/issues/4995

### Mirror Node Tickets
- [ ] https://github.com/hashgraph/hedera-mirror-node/issues/4805

### Docs
- [Disaster Recovery](https://www.notion.so/swirldslabs/Disaster-Recovery-bc892e76ec424743a87dfa7d9c2ddff8)
- [Phase 1 Procedures](https://www.notion.so/swirldslabs/Manual-Recovery-Procedures-89a6bed518ff4e4f8b13178dcd41fe21)

### LINKED ISSUE #6010: Enhance PCLI event-stream info command to accept a timestamp
The current PCLI event-stream info command prints a report including all events in the provided stream files. It would be more useful to print the same report but only for events that occur at or after a specified timestamp. When comparing multiple event streams, this is more convenient then ensuring the set of files in every stream has the same timestamp.

### PR DESCRIPTION
**Pull request by edward-swirldslabs**
**Description**:
- Added option for timestamp to EventStreamInfoCommand
- Created `EventStreamBound` to hold round and timestamp set as command parameters.
- Modified iterator classes with use of EventStreamBound
- Added unit tests to `EventStreamPathIteratorTest` and `EventStreamMultiFileIteratorTest` and  `EventStreamResportingToolTest`
- blocked simultaneous setting of round and timestamp in the command. 
- Added `EventStreamBoundTest` unit test.

**Related issue(s)**:

Fixes #6010  

**Notes for reviewer**:
The unit tests in the iterators validate setting both timestamp and bound.  It is only blocked at the command line level. 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamMultiFileIterator.java [hunk 1]
```diff
@@ -54,46 +56,38 @@ public class EventStreamMultiFileIterator implements IOIterator<DetailedConsensu
...
-     * 		the directory in question
-     * @param startingRound
-     * 		the round to start with, or {@link EventStreamPathIterator#FIRST_ROUND_AVAILABLE}
-     * 		if all events should be walked by this iterator
-     * @throws IOException
-     * 		if there is a problem reading the event stream
-     * @throws NoSuchElementException
-     * 		if the starting round can't be found
+     * @param eventStreamDirectory the directory in question
+     * @param bound                the  bound for the events in the event stream to be walked by this iterator
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamMultiFileIterator.java:84]: nit: extra space between `the` and `bound`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java [hunk 2]
```diff
@@ -59,10 +66,26 @@ public EventStreamPathIterator(final Path eventStreamDirectory, final long start
...
+        }
+
+        final DetailedConsensusEvent firstEvent = getFirstEventInEventStreamFile(eventStreamFiles.get(0));
+        if (bound.isUnbounded() || bound.compareTo(firstEvent, BoundType.LOWER) == 0) {
+            // We are attempting to get events from the beginning of the event stream.
             iterator = eventStreamFiles.iterator();
         } else {
+            final EventStreamBound usedBound;
+            if (bound.hasRound()) {
+                // corner case: get the file containing the round prior since the file may also contain events
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:81]: I'm having trouble wrapping my head around *why* this corner case exists. Could this explanation be expanded a bit to make it more clear what's happening here?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java [hunk 3]
```diff
@@ -96,18 +119,18 @@ private static boolean isFileAnEventStreamFile(final Path path) {
...
     /**
-     * Look inside an event stream file and return the round of the first event.
+     * Look inside an event stream file and return the first event
      *
      * @param path
      * 		a path to an event stream file
      * @return the round of the first event in the file
      */
-    private static long getFirstRoundInEventStreamFile(final Path path) throws IOException {
+    private static DetailedConsensusEvent getFirstEventInEventStreamFile(final Path path) throws IOException {
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:128]: Return object and param can be annotated

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java [hunk 4]
```diff
@@ -48,7 +55,20 @@ private void setEventStreamDirectory(final Path eventStreamDirectory) {
             names = {"-f", "--first-round"},
             description = "The first to be considered.")
     private void setFirstRound(final long firstRound) {
-        this.firstRound = firstRound;
+        boundBuilder.setRound(firstRound);
+    }
+
+    @CommandLine.Option(
+            names = {"-t", "--timestamp"},
+            description = "The the timestamp to be considered.")
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:63]: "the the"

I'd be specific and say that this is is a lower bound. Not obvious based on this sentence alone that you want to start looking at the stream at this timestamp. Perhaps something like "The minimum timestamp to be considered".

I'd describe the format here. Ideally somebody could figure out how to use this tool without reading the source code.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java [hunk 5]
```diff
@@ -48,7 +55,20 @@ private void setEventStreamDirectory(final Path eventStreamDirectory) {
...
+    private void setTimestamp(final String timestamp) {
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:64]: probably a good idea to add them... at the very least we signal that the author of the code doesn't expect to see a null value in the method

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 6]
```diff
@@ -0,0 +1,287 @@
...
+     * Compares the round received and consensus timestamp of the consensusData to the bound.  The comparison is made
+     * with the frame of reference of the consensus data. If the data is higher, a value greater than 0 is returned, if
+     * the data is lower, a valued less than 0 is returned, otherwise 0 is returned.
+     * <p>
+     * If the bound is a LOWER bound, if both the round and the timestamp are present in the bound then the consensus
+     * data is greater than bound if both the bound's round and the timestamp are lower than the consensus data round
+     * received and consensus timestamp, the consensus data is less than the bound if either the bound's round or the
+     * timestamp are strictly greater, and equal otherwise.   If only one of the timestamp or round is present, the
+     * normal comparison rules apply. If neither the timestamp nor round is present, the bound is an unbounded lower
+     * bound and the event is always greater than it.
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:161]: The first sentence in this paragraph is hard to understand, possibly two sentences got jammed together here?

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:161]: What do you mean by "if both the round and the timestamp are present"? I thought you don't allow both to be set at the same time.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 7]
```diff
@@ -0,0 +1,287 @@
...
+     * <p>
+     * If the bound is an UPPER bound, if both the round and the timestamp are present then the consensus data is less
+     * than the bound if both the bound's round and the timestamp are greater than the consensus data round received and
+     * consensus timestamp, the consensus data is greater than the bound if either bound's the round or the timestamp
+     * are strictly less, and equal otherwise.   If only one of the timestamp or round is present, the normal comparison
+     * rules apply. If neither the timestamp nor round is present, the bound is an unbounded upper bound and the event
+     * is always less than it.
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:168]: Is this class ever used as an upper bound (i.e. read the stream until we hit this boundary)? Our are we currently just using it as a lower bound (i.e. start reading the stream at this boundary)?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 8]
```diff
@@ -0,0 +1,287 @@
...
+            return compareTimestamp(consensusData);
+        }
+        if (timestamp == NO_TIMESTAMP) {
+            return compareRound(consensusData);
+        }
+
+        int roundCompare = compareRound(consensusData);
+        int timestampCompare = compareTimestamp(consensusData);
+
+        if (boundType == BoundType.LOWER) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:189]: Is it possible to reach this code using the CLI since it prevents both the round and the timestamp from being set?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 9]
```diff
@@ -0,0 +1,287 @@
...
+    public boolean isUnbounded() {
+        return round == NO_ROUND && timestamp == NO_TIMESTAMP;
+    }
+
+    /**
+     * The type of bound.
+     */
+    public enum BoundType {
+        LOWER,
+        UPPER
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:241]: I don't see this upper bound used anywhere except for unit tests... is the complexity for supporting both upper and lower bounds worth it?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:81]: I don't think this is a corner case, it's the standard case if we say "start at round X".

The reason why we subtract 1 from the bound is because we only read the first event from each file when we are doing the binary search. This means that if we find a file that starts with an event from the correct round, we can't be guaranteed that the previous file doesn't have events at the end with the round we need. So we keep searching until we find a file with a previous round, which guarantees that the events we need are in this file or later files.

It might be useful to add a comment saying as much for future readers of this code.

Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:81]: @cody-littley Is it guaranteed that the events of a single round will not span more than 2 stream files?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java [hunk 10]
```diff
@@ -66,9 +86,15 @@ private EventStreamInfoCommand() {}
...
-                new EventStreamScanner(eventStreamDirectory, firstRound, Duration.ofSeconds(granularityInSeconds), true)
-                        .createReport());
+        EventStreamBound bound = boundBuilder.build();
+        // Implementation and unit tests will work with both timestamp and round set.
+        // Current thoughts is that both should not be used at the same time.
+        if (bound.hasRound() && bound.hasTimestamp()) {
+            throw buildParameterException("Cannot set both round and timestamp");
+        }
+        System.out.println(new EventStreamScanner(
+                        eventStreamDirectory, boundBuilder.build(), Duration.ofSeconds(granularityInSeconds), true)
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:96]: Fixed in next commit.  That was an oversight after adding the block to using both bounds at once.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java [hunk 11]
```diff
@@ -33,9 +38,11 @@
 @SubcommandOf(EventStreamCommand.class)
 public final class EventStreamInfoCommand extends AbstractCommand {
 
+    private static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:41]: made final

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java [hunk 12]
```diff
@@ -33,9 +38,11 @@
...
+
     private Path eventStreamDirectory;
 
-    private long firstRound = -1;
+    private BoundBuilder boundBuilder = EventStreamBound.create();
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:45]: made final

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java [hunk 13]
```diff
@@ -66,9 +86,15 @@ private EventStreamInfoCommand() {}
     @Override
     public Integer call() throws Exception {
         setupConstructableRegistry();
-        System.out.println(
-                new EventStreamScanner(eventStreamDirectory, firstRound, Duration.ofSeconds(granularityInSeconds), true)
-                        .createReport());
+        EventStreamBound bound = boundBuilder.build();
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:89]: made final

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 14]
```diff
@@ -0,0 +1,287 @@
...
+
+    /**
+     * Create an event stream bound with the specified round and timestamp.
+     *
+     * @param round     the round
+     * @param timestamp the timestamp
+     */
+    public EventStreamBound(@NonNull final long round, @NonNull final Instant timestamp) {
+        this.round = round;
+        this.timestamp = timestamp;
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:51]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 15]
```diff
@@ -0,0 +1,287 @@
...
+
+    /**
+     * Compares the detailed consensus event to this bound based on the consensus data in the event.
+     *
+     * @param event     the detailed consensus event to compare to
+     * @param boundType the type of bound to compare as
+     * @return a negative integer, zero, or a positive integer based on whether the consensus data is less, equal or
+     * greater than the bound.
+     */
+    public Integer compareTo(DetailedConsensusEvent event, BoundType boundType) {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:135]: added `@NonNull final` and changed return value to int.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 16]
```diff
@@ -0,0 +1,287 @@
...
+        return new BoundBuilder();
+    }
+
+    /**
+     * The string representation of the event stream bound.
+     *
+     * @return the string representation
+     */
+    @Override
+    public String toString() {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:123]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 17]
```diff
@@ -0,0 +1,287 @@
...
+    public Instant getTimestamp() {
+        return timestamp;
+    }
+
+    /**
+     * Creates an instance of a builder for a bound.
+     *
+     * @return the builder
+     */
+    public static BoundBuilder create() {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:113]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 18]
```diff
@@ -0,0 +1,287 @@
...
+     * are strictly less, and equal otherwise.   If only one of the timestamp or round is present, the normal comparison
+     * rules apply. If neither the timestamp nor round is present, the bound is an unbounded upper bound and the event
+     * is always less than it.
+     *
+     * @param consensusData the consensus data to compare to
+     * @param boundType     the type of bound
+     * @return A positive value if the consensus data is greater than the bound, A negative value if the consensus data
+     * is less than the bound, and 0 otherwise.
+     */
+    public int compareTo(@NonNull final ConsensusData consensusData, BoundType boundType) {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:175]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 19]
```diff
@@ -0,0 +1,287 @@
...
+        /** The timestamp of the bound. */
+        private Instant timestamp = NO_TIMESTAMP;
+
+        /**
+         * Sets the round of the bound.
+         *
+         * @param round the round
+         * @return the builder
+         */
+        public BoundBuilder setRound(final long round) {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:259]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 20]
```diff
@@ -0,0 +1,287 @@
...
+            this.timestamp = timestamp;
+            return this;
+        }
+
+        /**
+         * Builds the event stream bound.
+         *
+         * @return the event stream bound
+         */
+        public EventStreamBound build() {
```
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:280]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamMultiFileIterator.java (hunk 1 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamMultiFileIterator.java:84]: removed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java (hunk 2 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:81]: updated wording.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java (hunk 3 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:128]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java (hunk 4 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java:63]: updated

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 7 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:168]: Just as a lower bound.  I generalized to support use as an upper bound as well.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 8 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:189]: The unit tests test the code, but in production the exception in the EventStreamCommandInfo prevents making this code reachable.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 9 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:241]: If we ever want a bounded query of the event stream (upper and lower) then it could be done with having two of these bounds.  

I don't know how to answer if it is "worth it".

Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:241]: I am willing to remove the non-executing code (Upper bound) and either remove the exception blocking the use of both bounds, or remove the unreachable code if that is what is preferred.

Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java]: I have removed the non-executing code.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 8 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java]: I have removed the simultaneous use of round and timestamp.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 7 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java]: I have removed the upper bound use.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 6 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java]: I have removed the support for upper bound and simultaneous use of round and timestamp

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java [hunk 21]
```diff
@@ -0,0 +1,239 @@
...
+import edu.umd.cs.findbugs.annotations.NonNull;
+import edu.umd.cs.findbugs.annotations.Nullable;
+import java.time.Instant;
+import java.util.Objects;
+
+/**
+ * A bound on the event stream. This bound can be either a round or a timestamp but not both. The bound is inclusive of
+ * exact matches to round and timestamp. If no round or timestamp is specified, then the bound is unbounded.
+ */
+public class EventStreamBound {
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:31]: I'm curious your thoughts on the following idea:

- create an interface `EventStreamBound`
- create 3 separate classes which implement `EventStreamBound`
    - `RoundBound`
    - `TimeBound`
    - `UnboundedBound`

- Each of these would implement the various comparison methods, and be generally quite simple.
- A builder would no longer be necessary, and you could skip the whole "make sure both things aren't set simultaneously" logic.
- If it ever becomes necessary, you could implement a `MultiBound`, that checks both round and time.

This strikes me as simpler and more understandable than the current configuration.

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java:31]: I bet the net number of lines required for this strategy would be smaller, even though we would have to create more classes.

**Review by cody-littley — COMMENTED** [review]
This seems close to being ready to merge, but wanted to hold off on the final approval until Austin's suggestion is resolved one way or another.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java (hunk 21 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamBound.java]: The latest solution incorporates the suggestion to break everything up into an interface and implementations.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java [hunk 22]
```diff
@@ -59,19 +67,35 @@ public EventStreamPathIterator(final Path eventStreamDirectory, final long start
...
+            // We are attempting to get events from the beginning of the event stream.
             iterator = eventStreamFiles.iterator();
         } else {
+            final EventStreamLowerBound usedBound;
+            if (bound instanceof final EventStreamRoundLowerBound roundBound) {
+                // Since we are only checking the first event in each file, if the first event is of the desired round,
+                // we can't be sure that there are not events of the same round at the end of the previous file.
+                // Therefore, we need to start at the previous round to capture all events of the desired round.
+                final long round = roundBound.getRound();
+                final long usedRound = round == FIRST_ROUND_AVAILABLE ? FIRST_ROUND_AVAILABLE : round - 1;
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:86]: With the hacky feeling of subtracting a round here, I'm wondering why we can't simply pass in the "previous" round way back at the start of this process. In `EventRecoveryWorkflow.java`, we're explicitly adding 1 to the round number

```
            final IOIterator<Round> roundIterator = new EventStreamRoundIterator(
                    eventStreamDirectory, initialState.get().getRound() + 1, allowPartialRounds);
```

Is there something preventing us from simply removing the `+ 1` in `EventRecoveryWorkflow`, and being able to discard the extra logic here?

The only change I see so far is with this condition:

```
        if (bound == UNBOUNDED || bound.compareTo(firstEvent) == 0) {
            // We are attempting to get events from the beginning of the event stream.
            iterator = eventStreamFiles.iterator();
        }
```

specifically, the `bound.compareTo(firstEvent) == 0` part. But, it's not immediately obvious to me why that's required.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamRoundLowerBound.java [hunk 23]
```diff
@@ -0,0 +1,58 @@
...
+ */
+
+package com.swirlds.platform.recovery.internal;
+
+import com.swirlds.common.system.events.ConsensusData;
+
+/**
+ * A round based lower bound on an event stream.
+ */
+public class EventStreamRoundLowerBound implements EventStreamLowerBound {
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamRoundLowerBound.java:24]: Class could be a record

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java (hunk 22 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:86]: The `bound.compareTo(firstEvent) == 0` is a necessary base case for the inductive case that the binary search performs.  

The binary search only checks the first event in the file at the index it is checking.   If the event is a match for the round, it is possible that there are more events for the same round at the end of the previous file.   This is why the search for the (round -1) is necessary.  

This is the javadoc on the binary search: 

```
an index with a value that satisfies the comparison function, or if no such index can be found the highest index that causes the comparison function to return a negative value (i.e. the largest value that does exceed the requested value)
```

Boundary / Base Case:   The round desired matches the first event in the first file.   We cannot seek for (round-1) in the inductive case because the binary search will return that there are no matches in the files.  This does happen when the files start with round 1 and the round desired is 1.  Removing the check of the base case causes the search for round 1 in the `EventStreamPathIterator` to fail.  

Suppose we universally say that input to the search should always be (round -1).   If we desire round 1, we input round 0.  That would lead to an even more inelegant base case check of bumping up the round to check against the first event in the first file.

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:86]: I think Austin makes a good point. Unless we have files stretching back to the beginning of time, we can't know for sure that we have all events from round `N` unless we observe events from round `N-1` or earlier.

The general goal of the search function, when asked to start a particular round, should be to either start iterating from the very beginning of that round, or to return an error saying it couldn't find the beginning of that round.

Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java:86]: Resolving, as this PR doesn't change the behavior here

**Review by alittley — APPROVED** [review]

**Comment by edward-swirldslabs** [comment]
Capturing our discussion in an issue about whether or not searching for the first round in the first file is sufficient or if it could be missing events. 

https://github.com/hashgraph/hedera-services/issues/6572
