### PR TITLE
03933 operation codes evm module impl

### LINKED ISSUE #3933: Add implementations for all read related custom operation codes
### Problem

In order to fully support read operations, we should include implementations for all operation codes that are related to read operations.

### Solution

Provide implementations for all read related op codes and supporting logic. These are:

- HederaBalanceOperation
- HederaCallCodeOperation
- HederaCallOperation
- HederaDelegateCallOperation
- HederaExceptionalHaltReason
- HederaExtCodeCopyOperation
- HederaExtCodeHashOperation
- HederaExtCodeSizeOperation
- HederaOperationUtil
- HederaSLoadOperation
- HederaStaticCallOperation

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by nikolovyanko**
**Description**:
Provide implementations for all read related op codes and supporting logic.

*The below classes are moved directly from "hedera-mono-service" to "evm-module-api" without any additions:
- HederaBalanceOperation
- HederaDelegateCallOperation
- HederaExtCodeCopyOperation
- HederaExtCodeHashOperation
- HederaExtCodeSizeOperation
- HederaExceptionalHaltReason

Whereas the below received a parent class version in "evm-module-api":
- HederaCallCodeOperation -> [HederaEvmCallCodeOperation](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallCodeOperation.java)
- HederaCallOperation -> [HederaEvmCallOperation](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallOperation.java)
- HederaSLoadOperation -> [HederaEvmSLoadOperation](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperation.java)
- HederaStaticCallOperation -> [HederaEvmStaticCallOperation](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmStaticCallOperation.java)

Since there are no signature checks expected in the "evm-module-api", all classes' parents are calling [HederaEvmOperationsUtil.addressCheckExecution](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmOperationsUtil.java#L45) instead of [HederaOperationUtil.addressSignatureCheckExecution](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmOperationsUtil.java#L45).

- HederaOperationUtil -> [HederaEvmOperationsUtil](https://github.com/hashgraph/hedera-services/blob/2d58071f046f54febe8de5bae3610cf569b865d7/hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmOperationsUtil.java)

**Related issue(s)**:

Fixes #3933

### CODE REVIEW

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaBalanceOperation.java [hunk 1]
```diff
@@ -46,9 +46,8 @@
 
 /**
  * Hedera adapted version of the {@link BalanceOperation}. Performs an existence check on the
- * requested {@link Address} Halts the execution of the EVM transaction with {@link
- * HederaExceptionalHaltReason#INVALID_SOLIDITY_ADDRESS} if the account does not exist or it is
- * deleted.
+ * requested {@link Address} Halts the execution of the EVM transaction with if the account does not
```
Comment (IvanKavaldzhiev) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaBalanceOperation.java:49]: Why 
`{@link * HederaExceptionalHaltReason#INVALID_SOLIDITY_ADDRESS} ` is missing?

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperation.java [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+                    warmCost, Optional.of(ExceptionalHaltReason.TOO_MANY_STACK_ITEMS));
+        }
+    }
+
+    /**
+     * A placeholder logic method to be overridden by {@link HederaEvmSLoadOperation} descendants.
+     */
+    protected void sLoadOPSpecificLogic(
+            MessageFrame frame, Address address, Bytes32 key, UInt256 storageValue) {
+        // The method is an intentionally-blank
```
Comment (IvanKavaldzhiev) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperation.java:84]: `The method is an intentionally-blank` -> `The method is intentionally-blank`

Probably we could also rename `sLoadOPSpecificLogic` to `intermediateCustomLogic`. Since the method is inside `HederaEvmSLoadOperation` it's clear that the logic is connected to `SLOAD` operation. I believe `intermediateCustomLogic` better describes the intention of this method.

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaBalanceOperation.java [hunk 3]
```diff
@@ -48,7 +48,8 @@
  * Hedera adapted version of the {@link BalanceOperation}. Performs an existence check on the
  * requested {@link Address} Halts the execution of the EVM transaction with {@link
  * HederaExceptionalHaltReason#INVALID_SOLIDITY_ADDRESS} if the account does not exist or it is
- * deleted.
+ * deleted. requested {@link Address} Halts the execution of the EVM transaction with if the account
```
Comment (shemnon) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaBalanceOperation.java:51]: It doesn't halt the execution of the whole transaction, just the MessageFrame.

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallCodeOperation.java [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+    public HederaEvmCallCodeOperation(
+            GasCalculator gasCalculator,
+            final BiPredicate<Address, MessageFrame> addressValidator) {
+        super(gasCalculator);
+        this.addressValidator = addressValidator;
+    }
+
+    @Override
+    public OperationResult execute(MessageFrame frame, EVM evm) {
+        return HederaEvmOperationsUtil.addressCheckExecution(
```
Comment (shemnon) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallCodeOperation.java:37]: Once hollow creates land we are getting rid of the address check.  Since that is the only thing done in this operation do we really need to add it?  i.e. is this expected to ship before hollow creates and full sidecar support?

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallOperation.java [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+
+    public HederaEvmCallOperation(
+            final GasCalculator gasCalculator,
+            final BiPredicate<Address, MessageFrame> addressValidator) {
+        super(gasCalculator);
+        this.addressValidator = addressValidator;
+    }
+
+    @Override
+    public OperationResult execute(MessageFrame frame, EVM evm) {
```
Comment (shemnon) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallOperation.java:37]: Same concern as HederaEvmCallCodeOperation, is this "dead code walking"?

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmStaticCallOperation.java [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+    public HederaEvmStaticCallOperation(
+            GasCalculator gasCalculator,
+            final BiPredicate<Address, MessageFrame> addressValidator) {
+        super(gasCalculator);
+        this.addressValidator = addressValidator;
+    }
+
+    @Override
+    public OperationResult execute(MessageFrame frame, EVM evm) {
+        return HederaEvmOperationsUtil.addressCheckExecution(
```
Comment (shemnon) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmStaticCallOperation.java:37]: Same Concern as HederaEvmStaticCallOperation.  If the "horizon" for historical re-execution is v0.33 we may not need this.

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExceptionalHaltReason.java [hunk 7]
```diff
@@ -50,14 +49,14 @@ public class HederaExceptionalHaltReason {
...
-     * the same as the destructed account
+     * Used when {hedera-mono-service.HederaSelfDestructOperation} is used and the beneficiary is
+     * specified to be the same as the destructed account
      */
     public static final ExceptionalHaltReason SELF_DESTRUCT_TO_SELF =
             HederaExceptionalHalt.SELF_DESTRUCT_TO_SELF;
     /**
-     * Used when there is no active signature for a given {@link
-     * com.hedera.services.state.merkle.MerkleAccount} that has {@link
+     * Used when there is no active signature for a given {
```
Comment (shemnon) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExceptionalHaltReason.java:58]: we should use the correct javadoc tags

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExceptionalHaltReason.java [hunk 8]
```diff
@@ -50,14 +49,14 @@ public class HederaExceptionalHaltReason {
     public static final ExceptionalHaltReason INVALID_SOLIDITY_ADDRESS =
             HederaExceptionalHalt.INVALID_SOLIDITY_ADDRESS;
     /**
-     * Used when {@link HederaSelfDestructOperation} is used and the beneficiary is specified to be
-     * the same as the destructed account
+     * Used when {hedera-mono-service.HederaSelfDestructOperation} is used and the beneficiary is
```
Comment (shemnon) [inline hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExceptionalHaltReason.java:52]: this is not the correct javadoc tag.

**Review by shemnon — APPROVED** [review]
only the javadoc changes require a code change. The rest can be answered in-line.

File: hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallCodeOperation.java (hunk 4 above)
Comment (IvanKavaldzhiev) [reply hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmCallCodeOperation.java:37]: I think these op code changes would land at the same time with hollow creates.

Do you refer to removing the address check even in `hedera-mono-service`? If so, won't we miss the possibility to differentiate between a hollow account with existing alias or invalid/missing account?

**Review by shemnon — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
