### PR TITLE
fix(21771): add minimum value to transactionHandler data counter 

### LINKED ISSUE #21771: Improve backpressure response time on the Consensus layer due to unacknowledged blocks
At low TPS, backpressure on the consensus layer will take a long time to engage once blocks can no longer be produced. This should be improved.

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
Even empty rounds now must exert some back pressure, since they still create blocks. If Execution loses it's connection to the block node and we reach the limit for the number of blocks we can keep locally, the handle thread will block. At high TPS, it does not take long for back pressure to engage and send the node into CHECKING.

This branch adds a minimum value to transactions in the TransactionHandler queue. The rationale is that there is a minimum cost to the system; even if the round contains few transactions, the cost is linear in the number of transactions beyond that minimum. 

The following spreadsheet shows the parameter values and their performance results on latitude envs
https://docs.google.com/spreadsheets/d/1IK8wM0Qa8RK3pdBlqGRmulhr-4yV0CBkWA7Lfd7-b8g/edit?gid=0#gid=0

**Related issue(s)**:

Fixes #21771

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformComponents.java [hunk 1]
```diff
@@ -174,126 +178,67 @@ public static PlatformComponents create(
...
+                : schedulerConfiguration.unhandledTaskCapacity();
+        // we want the mechanism of backpressure to engage soon enough in low tps set ups
+        // since even empty rounds have an effect on the load in execution side
+        final double minimumEffort = (double) capacity / LOW_TPS_TARGET_ROUNDS_CAPACITY; // 5000
 
-        final ComponentWiring<BranchDetector, PlatformEvent> branchDetectorWiring =
-                new ComponentWiring<>(model, BranchDetector.class, config.branchDetector());
-        final ComponentWiring<BranchReporter, Void> branchReporterWiring =
-                new ComponentWiring<>(model, BranchReporter.class, config.branchReporter());
+        return data -> {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformComponents.java]: can we move the calculation into a named method and add some unit testing for it?

Comment (mxtartaglia-sl) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformComponents.java]: Sure. what about creating an specific class for the counter.

**Review by lpetrovic05 — APPROVED** [review]

**Review by poulok — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]
