### PR TITLE
Fix `NullPointerException` in `HederaTracer` on obtaining call operation type

### LINKED ISSUE #3857: NPE when trying to obtain call operation type in hedera tracer
### Problem: ###

#3835 introduced call operation type in actions generated by the hedera tracer. 

However, the implementation there tries to obtain the call operation type (`CALL`, `DELEGATE_CALL`, `CREATE2`, etc) by calling `getCurrentOperation().getOpCode()` on the new child frame that has been spawned but has not yet begun executing. This throws a `NullPointerException`, since, firstly, the frame has not begun executing at the time we track the action for it, and secondly - **the operation that triggers a call (the operation that creates a child frame and from which we obtain the call operation type) is the last executed operation in the parent frame, not child frame**. 

Furthermore, top-level frames need to be handled differently -> their call operation type can be only `CALL` or `CREATE` and we can infer that from the frame type.

### LINKED ISSUE #3859: Port E2E test #SCT-001 of old traceability test plan in the new traceability suite
Contract A executes a `CALL` to Contract B, which in turn executes a `CALL` to Contract C. 

Transaction should have 2 associated sidecars:
1. State Changes
Fields in all contracts are accessed / written to, therefore there are state changes for all three contracts.
Slot 0 in Contract A is read as ≠ 0, but not written to.
Slot 1 in Contract A is written to, without first being read.
Slot 2 in Contract B is read as ≠ 0 and written to ≠ 0.
Slot 0 from Contract C is read as 0 and written as 0.
Slot 1 from Contract C is read as ≠ 0 as written as = 0.

Expected stateChanges: 3 different stateChanges for each contract.
Contract A:
  slot 0 → read only
  slot 1 → read and written
  slot 2 → absent.
Contract B:
  slot 0 → absent
  slot 1 → absent
  slot 2 → read and written
Contract C:
  slot 0 →  (А contract that reads and writes zeros to slot zero will have a message with only an empty valueWritten field)
  slot 1 → read and written
  slot 2 → absent

2. Actions - 3 actions
  * 1st action → for the top level call → type = CALL, depth = 0, callingAccount, etc
  * 2nd action → for the 1st inner call → type = CALL, depth = 1, callingContract, output, etc
  * 3rd action → for the 2nd inner call → type = CALL, depth = 2, callingContract, output, etc

### PR DESCRIPTION
**Pull request by dimitar-dinev**
**Description**:

* Changes [call operation type obtainment logic ](https://github.com/hashgraph/hedera-services/pull/3860/files#diff-41b0e01e6f2e85ce3ab1f1c5c779aa83bca590148ffa67d26ffa6a48d59cf2ecR111-R114)in HederaTracer:
  * **top level frame** -> frame type
  * **inner frame** -> operation from parent frame that triggered the call
* [Ports the first E2E scenario from the old traceability suite to the new one](https://github.com/hashgraph/hedera-services/pull/3860/files#diff-2bb3ca728e52f60027e9859f043a6bfafc29ca9a90eca42a8f233a49357832f1R119), with assertions for all sidecars - state changes, actions and bytecode.

**Related issue(s)**:

Fixes #3857 
Fixes #3859

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java [hunk 1]
```diff
@@ -89,8 +680,35 @@ private HapiApiSpec vanillaBytecodeSidecar() {
...
+                                                                    .setCallingAccount(
+                                                                            spec.registry()
+                                                                                    .getAccountID(
+                                                                                            GENESIS))
+                                                                    .setRecipientContract(
+                                                                            spec.registry()
+                                                                                    .getContractId(
+                                                                                            EMPTY_CONSTRUCTOR_CONTRACT))
+                                                                    .setGas(197000)
+                                                                    .setGasUsed(66)
```
Comment (dimitar-dinev) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java:706]: Are we concerned that the intrinsic gas cost isn't reflected in the `gas` and `gasUsed` fields for the top-level actions? So currently the `gas` field is `initialGas-intrinsicGas` and `gasUsed` is `gasUsed - intrinsicGas`

File: test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/ContractTraceabilitySuite.java [hunk 2]
```diff
@@ -79,45 +78,6 @@ public List<HapiApiSpec> getSpecsInSuite() {
...
-                                                        formattedAssertionValue(0),
-                                                        formattedAssertionValue(0),
-                                                        formattedAssertionValue(0)),
-                                                StorageChange.readAndWritten(
-                                                        formattedAssertionValue(1),
-                                                        formattedAssertionValue(11),
-                                                        formattedAssertionValue(0)))),
-                        tearDown());
-    }
-
```
Comment (lukelee-sl) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/ContractTraceabilitySuite.java:120]: why was this scenario removed?

Comment (lukelee-sl) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/ContractTraceabilitySuite.java:120]: thanks for the explanation.

**Review by lukelee-sl — DISMISSED** [review]

**Review by shemnon — DISMISSED** [review]

**Review by Nana-EC — DISMISSED** [review]

File: hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java [hunk 3]
```diff
@@ -74,35 +75,43 @@ public void traceExecution(MessageFrame frame, ExecuteOperation executeOperation
...
                 } else {
                     finalizeActionFor(currentActionsStack.pop(), frame, frameState);
                 }
             }
         }
     }
 
-    private void trackActionFor(final MessageFrame frame, final int callDepth) {
+    private void trackActionFor(
+            final MessageFrame nextFrame, final int callDepth, final MessageFrame parentFrame) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java:87]: I'd prefer to split this into two methods, `trackActionFor(@NotNull final MessageFrame initialFrame)` and `trackActionFor(@NotNull final MessageFrame nextFrame, final int callDepth, @NotNull final MessageFrame parentFrame)`.

Also, since `callDepth = nextFrame.getMessageFrameStack().size() - 1`, does it make sense to pass it as separate parameter?

File: test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java [hunk 4]
```diff
@@ -89,8 +680,35 @@ private HapiApiSpec vanillaBytecodeSidecar() {
...
+                                                                    .setOutput(EMPTY)
+                                                                    .build())));
+                                }),
+                        expectContractBytecodeSidecarFor(
+                                firstTxn, EMPTY_CONSTRUCTOR_CONTRACT, EMPTY_CONSTRUCTOR_CONTRACT));
     }
 
     HapiApiSpec vanillaBytecodeSidecar2() {
```
Comment (georg-getz) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java:714]: Could be made private for consistency with the other fn.

File: hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java (hunk 3 above)
Comment (dimitar-dinev) [reply hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java]: > Also, since callDepth must equal nextFrame.getMessageFrameStack().size() - 1 for the call to be correct, does it make sense to pass it as separate parameter?

Not really 😆 

Tried to clean it up a bit now

File: test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java (hunk 4 above)
Comment (dimitar-dinev) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java]: Changed to `private`

**Review by tinker-michaelj — APPROVED** [review]
Nice refactoring, LGTM!

**Review by stoqnkpL — APPROVED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java (hunk 1 above)
Comment (shemnon) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java:706]: This reads right to me.  The gas is deducted before the first operation is executed in the EVM.  The EVM only ever has `initialGas-intrinsicGas`

Comment (dimitar-dinev) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java:706]: Got it, thanks Danno
