### PR TITLE
05930 - fix address book init on software downgrade

### LINKED ISSUE #5930: fix address book initialization on software version regression
When forcing user of config address book the logic which checks the regression of software version is by-passed.

### PR DESCRIPTION
**Pull request by edward-swirldslabs**
**Description**:
Fixes bug where forcing the use of the config.txt address book would bypass the check and exception throw on software version downgrade.   The version comparison is moved to the browser, immediately after loading any saved signed state. 

**Related issue(s)**:

Fixes #5930

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java [hunk 1]
```diff
@@ -151,6 +161,12 @@ public AddressBook getInitialAddressBook() {
      */
     @NonNull
     private AddressBook initialize() {
+        final int versionComparison =
+                loadedSoftwareVersion == null ? 1 : currentVersion.compareTo(loadedSoftwareVersion);
+        if (versionComparison < 0) {
+            throw new IllegalStateException("The currentVersion `" + currentVersion + "` is prior to the stateVersion `"
+                    + loadedSoftwareVersion + "`");
+        }
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java:169]:
```suggestion
        if (versionComparison < 0) {
            throw new IllegalStateException("The current software version `" + currentVersion + "` is prior to the software version `"
                    + loadedSoftwareVersion + "`" + " that created the state that was loaded from disk.");
        }
```

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java [hunk 2]
```diff
@@ -167,35 +183,25 @@ private AddressBook initialize() {
...
-                candidateAddressBook = loadedSignedState
-                        .getSwirldState()
-                        .updateStake(configAddressBook.copy())
-                        .copy();
-            }
+            // versionComparison > 0, there is a software upgrade
+            logger.info(
+                    STARTUP.getMarker(),
+                    "Software Upgrade from version {} to {}. "
+                            + "The address book stake will be updated by the saved state's SwirldState.",
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java:198]:
```suggestion
                    "Software Upgrade from version {} to {}. "
                            + "The address book stake may be updated by the application using data from the state snapshot.",
```

**Review by cody-littley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java [hunk 3]
```diff
@@ -151,6 +161,12 @@ public AddressBook getInitialAddressBook() {
      */
     @NonNull
     private AddressBook initialize() {
+        final int versionComparison =
+                loadedSoftwareVersion == null ? 1 : currentVersion.compareTo(loadedSoftwareVersion);
+        if (versionComparison < 0) {
+            throw new IllegalStateException("The current software version `" + currentVersion + "` is prior to the software version `"
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java:167]: seems like this check has nothing to do with the AB. maybe it belongs somewhere else

Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java]: I have moved the version comparison into the Browser, right after loading the saved state from disk.

**Review by alittley — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java [hunk 4]
```diff
@@ -96,19 +98,22 @@ public class AddressBookInitializer {
...
+     * @param currentVersion    The current version of the application. Must not be null.
+     * @param softwareUpgrade Indicate that the software version has upgraded.
+     * @param signedState       The signed state loaded from disk.  May be null.
+     * @param genesisSupplier   The swirld application state in genesis start. Must not be null.
+     * @param configAddressBook The address book derived from config.txt. Must not be null.
+     * @param addressBookConfig The configuration settings for AddressBooks.
      */
     public AddressBookInitializer(
             @NonNull final SoftwareVersion currentVersion,
+            boolean softwareUpgrade,
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java:110]:
```suggestion
            final boolean softwareUpgrade,
```

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java [hunk 5]
```diff
@@ -636,12 +636,47 @@ private Collection<SwirldsPlatform> createLocalPlatforms(
                 final SignedState loadedSignedState = getUnmodifiedSignedStateFromDisk(
                         mainClassName, swirldName, nodeId, appVersion, addressBook.copy(), emergencyRecoveryManager);
 
+                // check software version compatibility
+                final SoftwareVersion loadedSoftwareVersion = loadedSignedState == null
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java:640]: I think this series of checks should be extracted to a static utility method, either here or in a utility class. That will make this method shorter and easier to read, and the static method can easily be unit tested.

```
static boolean detectSoftwareUpgrade(final SoftwareVersion appVersion, final SignedState loadedSignedState)
```

Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java]: The detectSoftwareUpgrade() method has been added to BootstrapUtils.java

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java [hunk 6]
```diff
@@ -637,34 +638,8 @@ private Collection<SwirldsPlatform> createLocalPlatforms(
...
-                            appVersion);
-                } else {
-                    softwareUpgrade = false;
-                    logger.info(
-                            STARTUP.getMarker(),
-                            "No Software Upgrade, continuing with software version {}.",
-                            loadedSoftwareVersion);
-                }
+                final boolean softwareUpgrade =
+                        BootstrapUtils.detectSoftwareUpgrade(appVersion, loadedSignedState, logger);
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java:642]: Better to have a new logger instance in this static class. Eventually we may end up passing a non-static log manager around, but for now it's best to follow the static log manager pattern.

**Review by cody-littley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java (hunk 6 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java]: created static logger for the util class and removed from method argument.

**Review by alittley — APPROVED** [review]
