### PR TITLE
Properly clear pipelines before a reconnect.

### LINKED ISSUE #6735: Pipelines not properly cleared during reconnect
All pipelines are not getting properly cleared during a reconnect. There are a bunch of failing reconnect tests as a result.

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #6735

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java [hunk 1]
```diff
@@ -122,6 +122,7 @@ public class SyncGossip extends AbstractGossip {
      * @param eventIntakeMetrics        metrics for event intake
      * @param updatePlatformStatus      a method that updates the platform status, when called
      * @param loadReconnectState        a method that should be called when a state from reconnect is obtained
+     * @param clearAllPipelinesForReconnect this method should be called to clear all pipelines prior to a reconnect
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java:125]: Reformat to align param docs

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java [hunk 2]
```diff
@@ -117,7 +118,8 @@ public static Gossip buildGossip(
             @NonNull final EventIntakeMetrics eventIntakeMetrics,
             @NonNull final EventLinker eventLinker,
             @NonNull final Runnable updatePlatformStatus,
-            @NonNull final Consumer<SignedState> loadReconnectState) {
+            @NonNull final Consumer<SignedState> loadReconnectState,
+            @NonNull final Runnable clearAllPipelinesForReconnect) {
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java:122]: To match the rest of the params, check `clearAllPipelinesForReconnect` with `requireNonNull`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java [hunk 3]
```diff
@@ -103,36 +103,37 @@ public class ChatterGossip extends AbstractGossip {
     private final List<StoppableThread> chatterThreads = new LinkedList<>();
     private final ChatterEventMapper chatterEventMapper = new ChatterEventMapper();
     private final SequenceCycle<EventIntakeTask> intakeCycle;
-    private final Clearable clearAllPipelines;
+    private final Clearable clearAllInternalPipelines;
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java:106]: A brief comment about why this is necessary would be very helpful

Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java:106]: the `clearAllPipelines` member variables in the other sync class should also be renamed to `clearAllInternalPipelines`

Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java:106]: Consider moving this member variable up to the abstract class. I took a look, and it seems to me like it would work. I might have missed something, though

Doing this would reduce # of member variables, and allow child classes to avoid implementing `clear()`

**Review by lpetrovic05 — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java:125]: done

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java:122]: done

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java (hunk 3 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java:106]:
```
    /**
     * Holds a list of objects that need to be cleared when {@link #clear()} is called on this object.
     */
    private final Clearable clearAllInternalPipelines;
```

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java:106]: Updated for all implementations

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java:106]: I'd like to, but it's not so simple to do. Java doesn't let us construct things prior to calling super, and there are objects we need that are constructed later that need to go into the construction of `clearAllInternalPipelines`.

**Review by alittley — APPROVED** [review]
