### PR TITLE
Fix Ethereum Suites issues

### LINKED ISSUE #9022: Error when running tests from Ethereum suites
### Problem

There is CATASTROPHIC_FAILURE error when trying to run tests from EthereumSuite and HelloWorldEthereumSuite specs.

### Solution

We need to make sure properties from `application.properties` in the dev config affect node0 as well.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by georgi-l95**
**Description**:
This PR changes the following:

 - Avoids ISS in `smallContractCreate()` by removing special treatment of `node0` in `HapiTestEnv`.
 - When un-aliasing an `0.0.<alias>` form `AccountID` in `ReadableAccountStoreImpl`, also considers "indirect" references where an ECDSA key has an implied EVM address that is an in-use alias.
 - When answering a `CryptoGetInfo` query, ensures the returned `AccountID` is a numeric `0.0.X` id.
 - Also enables a passing `ethereumCallWithCalldataBiggerThanMaxSucceeds()` spec (have not checked others).
 - Adds `contracts.chainId=298` to dev env, because ethereum tests needs it.

**Related issue(s)**:

Fixes #9022 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java [hunk 1]
```diff
@@ -132,6 +135,33 @@ protected Account getAccountLeaf(@NonNull final AccountID id) {
...
+     * @param alias the alias to look up
+     * @return the account id referenced by the alias, or null if not found
+     */
+    private @Nullable AccountID unaliasWithEvmAddressConversionIfNeeded(@NonNull final Bytes alias) {
+        final var maybeDirectReference = aliases.get(new ProtoBytes(alias));
+        if (maybeDirectReference != null) {
+            return maybeDirectReference;
+        } else {
+            try {
+                final var protoKey = Key.PROTOBUF.parseStrict(BufferedData.wrap(alias.toByteArray()));
```
Comment (rbair23) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java:151]: Nit: there is an API on bytes to get a readable stream, and you can pass that in, rather than converting to byte array and then wrapping it.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java [hunk 2]
```diff
@@ -132,6 +135,33 @@ protected Account getAccountLeaf(@NonNull final AccountID id) {
...
+                if (protoKey.hasEcdsaSecp256k1()) {
+                    final var evmAddress = recoverAddressFromPubKey(
+                            protoKey.ecdsaSecp256k1OrThrow().toByteArray());
+                    return evmAddress.length > 0 ? aliases.get(new ProtoBytes(Bytes.wrap(evmAddress))) : null;
```
Comment (rbair23) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java:155]: We could add a new method for recoverAddressFromPubKey that takes Bytes and returns Bytes, so you don't have to do the wrapping and unwrapping here. That would make the code a little more obvious.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, thanks @georgi-l95 !

**Review by rbair23 — APPROVED** [review]

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java (hunk 2 above)
Comment (georgi-l95) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java:155]: Yes, i like this, added.

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM !

**Review by tinker-michaelj — APPROVED** [review]

**Review by rbair23 — APPROVED** [review]

**Review by lukelee-sl — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java [hunk 3]
```diff
@@ -69,11 +69,7 @@ public HapiTestEnv(@NonNull final String testName, final boolean cluster) {
                 final var workingDir = Path.of("./build/hapi-test/" + testName + "/node" + nodeId)
                         .normalize();
                 setupWorkingDirectory(workingDir, configText);
-                if (nodeId == 0) {
-                    nodes.add(new InProcessHapiTestNode(workingDir, 0, FIRST_GRPC_PORT));
-                } else {
-                    nodes.add(new SubProcessHapiTestNode(workingDir, nodeId, FIRST_GRPC_PORT + (nodeId * 2)));
-                }
+                nodes.add(new SubProcessHapiTestNode(workingDir, nodeId, FIRST_GRPC_PORT + (nodeId * 2)));
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java:72]: This is obviously what was mentioned in the PR comment as "Avoids ISS in smallContractCreate() by removing special treatment of node0 in HapiTestEnv." - but ... the "InProcessHapiTestNode" is there for a reason (performance I think) ... is this the desired change?

**Review by david-bakin-sl — COMMENTED** [review]
Some comments

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java [hunk 4]
```diff
@@ -457,10 +457,7 @@ private int lookupSpenderAndToken(
             final TokenID tokenId) {
         for (int i = 0; i < ownerAllowances.size(); i++) {
             final var allowance = ownerAllowances.get(i);
-            if (allowance.tokenId() != null
-                    && allowance.spenderId() != null
-                    && allowance.spenderId().equals(spenderId)
-                    && allowance.tokenId().equals(tokenId)) {
+            if (allowance.spenderId().equals(spenderId) && allowance.tokenId().equals(tokenId)) {
```
[the remark this answers is not in the document]
Comment (georgi-l95) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java:460]: They do have this on L293 and L294

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java [hunk 5]
```diff
@@ -90,14 +90,20 @@ public AccountID create(@NonNull final Bytes alias, int maxAutoAssociations) {
...
             final var key = asKeyFromAlias(alias);
-            syntheticCreation = createAccount(alias, key, 0L, maxAutoAssociations);
+            if (key.hasEcdsaSecp256k1()) {
+                evmAddress = tryAddressRecovery(key, EthSigsUtils::recoverAddressFromPubKey);
+                syntheticCreation = createAccount(Bytes.wrap(evmAddress), key, 0L, maxAutoAssociations);
+            } else {
+                syntheticCreation = createAccount(alias, key, 0L, maxAutoAssociations);
+            }
             memo = AUTO_MEMO;
         }
```
[the remark this answers is not in the document]
Comment (georgi-l95) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java:109]: Agree, but might be a good idea to do it in a separate follow up PR, just to avoid losing approvals once again :D

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java (hunk 3 above)
Comment (georgi-l95) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java:72]: Not sure to be fair, wasn't my change, checkout this Slack [thread](https://limechain.slack.com/archives/C040H9JPQT1/p1696384945548229)

Comment (jsync-swirlds) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java:72]: The in process node supports debugging in an IDE.
It needs to be removed temporarily because it isn't playing nice with the out-of-process setup, but future work is needed to re-enable it in a way that supports IDE debugging.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (georgi-l95) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AutoAccountCreator.java:109]: Opened a issue to address this. Thank you
