### PR TITLE
00798: Most reconnect regression tests

### LINKED ISSUE #798: Add a regression test that validates most of in-memory data structures after reconnect
**Summary**
Currently, we have 7 regression tests that validate reconnect. Their duration is at most 12 minutes on average, but deploying the test and validation causes the overall suite to run over 3 hours long. 

**Possible resolution**
Given that most of the tests only execute one transaction and validate independent features, we create one test that executes most of the transactions and validations to reduce the validation time to only 30 minutes or less.

### PR DESCRIPTION
**Pull request by cesaragv**
**Related issue(s)**:
Closes #798 

**Summary of the change**:
Runs multiple updates types of updates to validate reconnect

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+				.given(
+						sleepFor(Duration.ofSeconds(25).toMillis()),
+						getAccountBalance(GENESIS)
+								.setNode("0.0.6")
+								.unavailableNode()
+				)
+				.when(
+						getAccountBalance(GENESIS)
+								.setNode("0.0.6")
+								.unavailableNode(),
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:71]: Redundant repetition, we can remove the check for unavailable node in the `when()` part.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+
+						fileUpdate(APP_PROPERTIES)
+								.payingWith(ADDRESS_BOOK_CONTROL)
+								.overridingProps(Map.of("minimumAutoRenewDuration", "20")),
+
+						fileCreate("effectivelyImmutable")
+								.contents("Can't touch me!"),
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:78]: The file name and contents might give a misleading understanding. The file is actually not updatable, due to the updated API permissions, not due to itself (ACL for example). It is still deletable though...
I would suggest we move the API permissions update to go in front of it, then provide a file name and contents to describe that the file is not updatable because of this API permissions update.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+								.hasPriority(recordWith().fee(newFee)),
+
+						cryptoCreate("civilian")
+								.setNode("0.0.6"),
+						getAccountInfo("0.0.2")
+								.payingWith("civilian")
+								.nodePayment(0L)
+								.setNode("0.0.6")
+								.hasAnswerOnlyPrecheck(OK)
+				);
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:151]: Before ending, we should restore all of the protected system files back to their original contents.

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Overall, changes look good to me. Just a few things that need to be addressed, as in my comment. Thanks!

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java (hunk 1 above)
Comment (cesaragv) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java]: Fixed

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java [hunk 4]
```diff
@@ -0,0 +1,154 @@
+package com.hedera.services.bdd.suites.reconnect;
+
```
Comment (Neeharika-Sompalli) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:2]: copyright missing

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java (hunk 3 above)
Comment (cesaragv) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:167]: @qnswirlds once the test ends, the machines are terminated. What would be the point of restoring those files?

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java (hunk 4 above)
Comment (cesaragv) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:2]: Fixed

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java (hunk 3 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java:167]: When we create a test, we don't limit ourselves to use such test only on a "testing" environment. The test could be used in prod environment like our testnet or mainnet. In this case, clean up is definitely required. Besides, cleaning up after performing any test is a better practice to follow in general.

**Review by Neeharika-Sompalli — DISMISSED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java (hunk 3 above)
Comment (cesaragv) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateChangesAfterReconnect.java]: Fixed

**Review by qnswirlds — APPROVED** [review]
@cesaragv and I fixed all the things I requested to change. @tinker-michaelj, could you please do a quick review for the final approval? Thank you!

**Review by QianSwirlds — APPROVED** [review]

**Review by ljianghedera — APPROVED** [review]
LGTM

**Review by tinker-michaelj — APPROVED** [review]
LGTM
