### PR TITLE
fix: Add separate field for AuthorisationListRlp 

### LINKED ISSUE #22557: [EIP-7702] Type 4 transaction parsing inconsistency
While the SDK team was working on the support of type 4 ethereum transactions they reported an issue with the parsing of the transactions at the consensus node.

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
Addressing additional inconsistencies in decoding and signing type 4 transactions 

**Related issue(s)**:

Fixes #22557 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java [hunk 1]
```diff
@@ -254,7 +254,14 @@ private InvolvedParties computeInvolvedParties(
             }
         }
         if (transaction.isEthereumTransaction()) {
-            validateTrue(transaction.nonce() == parties.sender().getNonce(), WRONG_NONCE);
+            // For EIP-7702 transactions with code delegations, skip nonce check here
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:257]: It seems to me that the new check in `ContextTransactionProcessor` will check the nonce regardless of whether there is an authorization list or not and therefore makes this check redundant in all circumstances.

Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:257]: Extended the statement to check for code delegations and the Pectra config.

**Review by lukelee-sl — APPROVED** [review]
LGTM.  tyvm, @stoyanov-st

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java (hunk 1 above)
Comment (lukelee-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:257]: I guess my question was, if there is a check in `ContextTransactionProcessor` that covers all `EthereumTransactions` then do we need a separate check in `TransactionProcessor` at all for these transactions?

Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:257]: I totally missed that part. So we first check the nonce in the `ContextTransactionProcessor` if there is a delegation and then we check in 'TransactionProcessor' if there is not (where the check was originally). 
I can move it all to the `ContextTransactionProcessor` to avoid confusion if you like or leave it as it is now. 
What do you think?

**Review by gkozyryatskyy — APPROVED** [review]
LGTM!

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java (hunk 1 above)
Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:257]: I decided to add this change with a separate PR so we can merge this one
