### PR TITLE
fix: Return invalid token even if expected decimals are present

### LINKED ISSUE #11335: Deal with nonexistent token IDs in decimal comparison
Typically a nonexistent token ID should result in an `INVALID_TOKEN_ID` response, but it's possible to get a `FAIL_INVALID` on crypto transfer when 1) the token ID doesn't exist, and 2) the transaction's expected decimals are set in `TokenStore#tryTokenChange` (mono service). This scenario also triggers a "possibly catastrophic" error message:

```
2024-02-02 16:02:48.342 {"body":"2024-02-02 16:02:47.793 ERROR 173  ServicesTxnManager - Possibly CATASTROPHIC failure in txn processing :: signedTransactionBytes: \"\\n\\224\\001\\n\\032\\n\\f\\b\\227\\244\\364\\255\\006\\020\\205\\203\\277\\217\\003\\022\\b\\b\\000\\020\\000\\030\\215\\366-\\030\\000\\022\\006\\b\\000\\020\\000\\030\\037\\030\\200\\302\\327/\\\"\\002\\bx2(g7OiK52Gobq0iFAJx9ZJKcnvScc4JKM9lRaG82jmr;\\n\\000\\0227\\n\\t\\b\\000\\020\\000\\030\\252\\275\\206\\001\\022\\022\\n\\b\\b\\000\\020\\000\\030\\271\\201\\v\\020\\200\\273\\302\\225\\002\\030\\000\\022\\022\\n\\b\\b\\000\\020\\000\\030\\215\\366-\\020\\377\\272\\302\\225\\002\\030\\000\\\"\\002\\b\\004\\022f\\nd\\n \\313\\244 \\220C\\a\\361\\2739\\024\\233\\211\\351\\024\\367\\252i\\216V\\351\\034\\366$\\230\\023\\026\\f\\353\\200\\266Xt\\032@\\2034\\256@z\\207\\347\\260\\276\\212\\006\\221\\227\\\\\\035\\340e\\277\\360d\\006UBrW\\315y \\330\\371\u003c\\314M\\b\\024\\330P1\\377\\242\\v\\0040\\377#\\260\\207\\243\\307\\305\\aSs\\'\\211\\253J\\3170I\\334\\306\\340\\005\"\n ==\u003e\u003e --- ACCOUNTS ---\n{0.0.31: [BALANCE -\u003e 4610631812673], 0.0.98: [BALANCE -\u003e 7570086547782165], 0.0.800: [BALANCE -\u003e 1792042913409081], 0.0.752397: [BALANCE -\u003e 2919558435527]}\n--- TOKEN RELATIONSHIPS ---\n{}\n--- NFTS ---\n{}\n--- TOKENS ---\n{} ==\u003e\u003e\njava.lang.IllegalArgumentException: Argument 'id=0.0.2203306' does not refer to a known token!\n\tat com.hedera.node.app.service.mono.store.tokens.HederaTokenStore.throwIfMissing(HederaTokenStore.java:706) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.store.tokens.HederaTokenStore.get(HederaTokenStore.java:222) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.store.tokens.HederaTokenStore.matchesTokenDecimals(HederaTokenStore.java:374) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.store.tokens.TokenStore.tryTokenChange(TokenStore.java:91) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.ledger.TransferLogic.doZeroSum(TransferLogic.java:157) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.ledger.HederaLedger.doZeroSum(HederaLedger.java:325) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.txns.crypto.CryptoTransferTransitionLogic.doStateTransition(CryptoTransferTransitionLogic.java:79) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.txns.TransitionRunner.tryTransition(TransitionRunner.java:123) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.state.logic.RequestedTransition.finishFor(RequestedTransition.java:62) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.state.logic.TopLevelTransition.run(TopLevelTransition.java:109) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.state.logic.ServicesTxnManager.process(ServicesTxnManager.java:121) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.state.logic.StandardProcessLogic.doProcess(StandardProcessLogic.java:178) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.state.logic.StandardProcessLogic.incorporate(StandardProcessLogic.java:137) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.state.logic.StandardProcessLogic.incorporateConsensusTxn(StandardProcessLogic.java:108) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.txns.ProcessLogic.lambda$incorporateConsensus$0(ProcessLogic.java:40) ~[app-service-mono-0.45.2.jar:?]\n\tat com.swirlds.common.system.Round.forEachEventTransaction(Round.java:105) ~[swirlds-common-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.txns.ProcessLogic.incorporateConsensus(ProcessLogic.java:39) ~[app-service-mono-0.45.2.jar:?]\n\tat com.hedera.node.app.service.mono.ServicesState.handleConsensusRound(ServicesState.java:302) ~[app-service-mono-0.45.2.jar:?]\n\tat com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.45.2.jar:?]\n\tat com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:177) ~[swirlds-platform-core-0.45.2.jar:?]\n\tat com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:373) ~[swirlds-platform-core-0.45.2.jar:?]\n\tat com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253) ~[swirlds-common-0.45.2.jar:?]\n\tat com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.45.2.jar:?]\n\tat com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.45.2.jar:?]\n\tat java.base/java.lang.Thread.run(Thread.java:833) [?:?]","attributes":{"gcp.log_name":"hgcaa","inventory_name":"node09 - 65.108.30.144","log.file.name":"hgcaa.log","metrics_node_id":"10"}}
```

We need to reproduce and fix this bug.

### PR DESCRIPTION
**Pull request by mhess-swl**
We had a situation occur in mainnet this morning that resulted in a `FAIL_INVALID` instead of `INVALID_TOKEN_ID`. This PR fixes the bug by returning the first error status, instead of continuing to process other potential errors. 

Closes #11335

### CODE REVIEW

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/TokenStore.java [hunk 1]
```diff
@@ -83,22 +83,22 @@ default ResponseCodeEnum delete(TokenID id) {
...
-        var validity = OK;
         var tokenId = resolve(change.tokenId());
         if (tokenId == MISSING_TOKEN) {
-            validity = INVALID_TOKEN_ID;
+            return INVALID_TOKEN_ID;
         }
+
         if (change.hasExpectedDecimals() && !matchesTokenDecimals(change.tokenId(), change.getExpectedDecimals())) {
-            validity = UNEXPECTED_TOKEN_DECIMALS;
+            return UNEXPECTED_TOKEN_DECIMALS;
```
Comment (iwsimon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/TokenStore.java:92]: Original code return validity value at the end. Seems the same?

Comment (mhess-swl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/TokenStore.java:92]: Returning in the middle of the function behaves differently than returning at the end of the function. The problem here was that the code sets `validity = INVALID_TOKEN_ID`, _but does not immediately return that status_. Instead, the code goes on to compute `!matchesTokenDecimals(...)`, which expects an existing token ID, and therefore throws an exception.

Comment (iwsimon) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/TokenStore.java:92]: I didn't see !matchesTokenDecimals(...) below since it was not changed. Thanks for explaining.

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
Makes sense to me. Thanks @mhess-swl

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @mhess-swl !
