### PR TITLE
HIP-423: Long Term Scheduled Transactions

### LINKED ISSUE #3069: Support for Long Term Scheduled Transactions - Reference implementation
### Problem

The current Scheduled Transaction implementation's main purpose is to provide an on-network mechanism for multiple parties to sign a transaction. All Scheduled Transactions must be signed within 30 minutes or they [will expire](https://docs.hedera.com/guides/docs/hedera-api/schedule-service/schedulecreate). This was seen as a sufficient amount of time for collaborating parties to all submit their signatures as well as limit the network resources needed to support the feature.

The current Scheduled Transaction implementation also limits the types of transactions that can be scheduled. This was done to reduce the attack surface, testing requirements, and throttling requirements for the feature.

In this issue we propose extending the existing Scheduled Transaction implementation to support executing transactions at an arbitrary time in the future and allowing more types of transactions to be scheduled.

### Solution

- Add an optional `expirationTime` `Timestamp` field to the `ScheduleCreate` protobuf. This field shall specify the "consensus time" when the transaction should attempt to execute and then expire.
   - If not specified, this shall default to 30 minutes in the future.
- Add an optional `waitForExpiry` `bool` field to the `ScheduleCreate` and `ScheduleInfo` protobuf.  This field shall specify that the transaction will wait till `expirationTime` to attempt to execute.
  - if not specified, this shall default to `false`.

Remainder of specs and details will be in a to-be-published HIP

This issue is for the reference implementation.

### Alternatives

_No response_

### LINKED ISSUE #3137: Potential race condition in DeterministicThrottle or associated tests
### Description

The following errors keep showing up during test runs. Filing a bug for further investigation later. It's either a race condition in the test, with synchronization primitives in DeterministicThrottle, or a bug on OSX M1 platform.

```
Exception in thread "pool-2-thread-5" java.lang.IllegalArgumentException: Throttle timeline must advance, but 2022-04-05T18:00:22.518658Z is not after 2022-04-05T18:00:22.518685Z!
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:123)
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:115)
	at com.hedera.services.throttles.ConcurrentThrottleTestHelper.lambda$runWith$0(ConcurrentThrottleTestHelper.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "pool-2-thread-3" java.lang.IllegalArgumentException: Throttle timeline must advance, but 2022-04-05T18:00:23.127106Z is not after 2022-04-05T18:00:23.127129Z!
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:123)
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:115)
	at com.hedera.services.throttles.ConcurrentThrottleTestHelper.lambda$runWith$0(ConcurrentThrottleTestHelper.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "pool-2-thread-2" java.lang.IllegalArgumentException: Throttle timeline must advance, but 2022-04-05T18:00:23.648755Z is not after 2022-04-05T18:00:23.648773Z!
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:123)
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:115)
	at com.hedera.services.throttles.ConcurrentThrottleTestHelper.lambda$runWith$0(ConcurrentThrottleTestHelper.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.068 s - in com.hedera.services.throttles.DeterministicThrottleTest
Exception in thread "pool-3-thread-3" java.lang.IllegalArgumentException: Throttle timeline must advance, but 2022-04-05T18:00:19.131577Z is not after 2022-04-05T18:00:19.131595Z!
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:123)
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:115)
	at com.hedera.services.throttles.ConcurrentThrottleTestHelper.lambda$runWith$0(ConcurrentThrottleTestHelper.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "pool-3-thread-1" java.lang.IllegalArgumentException: Throttle timeline must advance, but 2022-04-05T18:00:26.774835Z is not after 2022-04-05T18:00:26.774838Z!
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:123)
	at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:115)
	at com.hedera.services.throttles.ConcurrentThrottleTestHelper.lambda$runWith$0(ConcurrentThrottleTestHelper.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

Run `mvn test` repeatedly. Shows up 1/2 times

### Additional context

_No response_

### Hedera network

other

### Version

master

### Operating system

macOS

### PR DESCRIPTION
**Pull request by statop**
**Description**:

Implement [HIP-423](https://hips.hedera.com/hip/hip-423)

**Related issue(s)**:

- Fixes #3069
- Fixes #3137

**Notes for reviewer**:

Integration tests are being worked on.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsage.java [hunk 1]
```diff
@@ -51,7 +51,18 @@ public boolean applicableTo(TransactionBody txn) {
 
 	@Override
 	public FeeData usageGiven(TransactionBody txn, SigValueObj svo, StateView view) throws InvalidTxBodyException {
+        var op = txn.getScheduleCreate();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsage.java:54]: Indentation is off.

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java [hunk 2]
```diff
@@ -330,8 +350,12 @@ public MerkleMap<EntityNumPair, MerkleTokenRelStatus> tokenAssociations() {
 		return getChild(StateChildIndices.TOKEN_ASSOCIATIONS);
 	}
 
-	public MerkleMap<EntityNum, MerkleSchedule> scheduleTxs() {
-		return getChild(StateChildIndices.SCHEDULE_TXS);
+	public MerkleScheduledTransactions scheduleTxs() {
+		MerkleNode scheduledTxns = getChild(StateChildIndices.SCHEDULE_TXS);
+		if (scheduledTxns instanceof MerkleMap) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/ServicesState.java:355]: _(nit)_ This work-around causes [`StateInitializationFlow.runWith`](https://github.com/hashgraph/hedera-services/blob/eth-tx-interop/hedera-node/src/main/java/com/hedera/services/context/init/StateInitializationFlow.java#L88) to always report `0` saved scheduled transactions. Would it be worth allowing a `MerkleScheduledTransactions` to have a `size()` method that could report the pending size in this case?

(Since the actual number is of course logged later, during migration, this is mostly a thin justification to leave some kind of comment. 😉 )

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java [hunk 3]
```diff
@@ -0,0 +1,312 @@
...
+@Singleton
+public class ConsensusTimeTracker {
+	private static final Logger log = LogManager.getLogger(ConsensusTimeTracker.class);
+
+	@VisibleForTesting
+	static final long DEFAULT_NANOS_PER_ROUND = TransactionHandler.MIN_TRANS_TIMESTAMP_INCR_NANOS;
+
+	/**
+	 * The max number of records that can be placed before the first transaction in a round. We need this because
+	 * the first transaction might have more than a normal number of proceeding records.
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:46]: Typo I think, should be "preceding records".
```suggestion
	 * the first transaction might have more than a normal number of preceding records.
```

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java [hunk 4]
```diff
@@ -0,0 +1,312 @@
...
+
+	private boolean firstUsed;
+
+	@Inject
+	public ConsensusTimeTracker() {
+		this(DEFAULT_NANOS_PER_ROUND);
+	}
+
+	@VisibleForTesting
+	ConsensusTimeTracker(final long nanosPerRound) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:78]: The SDK `1000 = minTransTimestampIncrNanos` setting has no connection to round boundaries, afaik. So a more precise name might be be `minNanosBetweenSdkTimestamps` or the like.

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java [hunk 5]
```diff
@@ -0,0 +1,312 @@
...
+		return firstUsed;
+	}
+
+	/**
+	 * Resets this tracker, should be called at the beginning of
+	 * {@link com.hedera.services.state.logic.StandardProcessLogic#incorporateConsensusTxn}
+	 * @param consensusTime the consensusTime passed to incorporateConsensusTxn
+	 */
+	public void reset(final Instant consensusTime) {
+		roundStartConsensusTime = consensusTime;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:122]: In general, the consensus time from `incorporateConsensusTxn` will _not_ be the first in the round. (Rounds/sec is ~1/sec given typical network conditions, I think.)

File: hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java [hunk 6]
```diff
@@ -177,7 +178,8 @@ public SafeLookupResult<ScheduleSigningMetadata> scheduleSigningMetaFor(
 		if (linkedRefs != null) {
 			linkedRefs.link(id.getScheduleNum());
 		}
-		final var schedule = stateChildren.schedules().get(EntityNum.fromScheduleId(id));
+		final var schedule = stateChildren.schedules().byId().get(
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java:181]: It would be nice to hide the `.byId().get(new EntityNumVirtualKey(...` implementation details in a `schedules().getById(id)` method---[law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter#In_object-oriented_programming) and so on.

File: hedera-node/src/main/java/com/hedera/services/state/expiry/EntityAutoRenewal.java [hunk 7]
```diff
@@ -77,13 +81,18 @@ public void execute(final Instant nextAvailConsTime) {
 			return;
 		}
 
+		if (!consensusTimeTracker.hasMoreStandaloneRecordTime()) {
+			log.debug("Auto-renew scan skipped because there are no more standalone record times. {}", consensusTimeTracker);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/expiry/EntityAutoRenewal.java:85]: Nice. 😎

File: hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java [hunk 8]
```diff
@@ -156,18 +148,6 @@ public void reviewExistingPayerRecords() {
 	 */
 	public void reviewExistingShortLivedEntities() {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java:149]: This is dead code now (c.f. now only test methods call `TransactionContext.addExpiringEntities()`).

File: hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalRecordsHelper.java [hunk 9]
```diff
@@ -97,7 +99,7 @@ public void streamCryptoRenewal(
 	) {
 		assertInCycle();
 
-		final var eventTime = cycleStart.plusNanos(consensusNanosIncr++);
+		final var eventTime = consensusTimeTracker.nextStandaloneRecordTime();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalRecordsHelper.java:102]: Much nicer. ☺️

File: hedera-node/src/main/java/com/hedera/services/state/logic/SigsAndPayerKeyScreen.java [hunk 10]
```diff
@@ -43,34 +45,31 @@ public class SigsAndPayerKeyScreen {
...
 	) {
-		this.txnCtx = txnCtx;
 		this.validityTest = validityTest;
 		this.speedometers = speedometers;
 		this.rationalization = rationalization;
 		this.payerSigValidity = payerSigValidity;
 	}
 
-	public ResponseCodeEnum applyTo(SwirldsTxnAccessor accessor) {
+	public ResponseCodeEnum applyTo(SwirldsTxnAccessor accessor, Optional<TransactionContext> txnCtx) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/logic/SigsAndPayerKeyScreen.java:63]: We should try to avoid _any_ unnecessary object creations in the `handleTransaction` critical path---even `Optional`'s. So I'd suggest `@Nullable TransactionContext txnCtx` here.

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java [hunk 11]
```diff
@@ -86,42 +86,64 @@ public StandardProcessLogic(
...
-			expiries.purge(effectiveConsensusTime.getEpochSecond());
+			consensusTimeTracker.reset(consensusTime);
+
+			sigImpactHistorian.setChangeTime(consensusTime);
+			expiries.purge(consensusTime.getEpochSecond());
 			sigImpactHistorian.purge();
 			recordStreaming.resetBlockNo();
 
-			doProcess(submittingMember, consensusTime, effectiveConsensusTime, accessor);
+			doProcess(submittingMember, consensusTimeTracker.isFirstUsed()
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java:101]: Isn't `consensusTimeTracker.isFirstUsed()` guaranteed to be `false` here?

(Or is this just defensive programming, in case someday that isn't guaranteed?)

File: hedera-node/src/main/java/com/hedera/services/state/logic/TriggeredTransition.java [hunk 12]
```diff
@@ -65,6 +78,17 @@ public void run() {
 		final var now = txnCtx.consensusTime();
 
 		networkCtxManager.advanceConsensusClockTo(now);
+
+		if (accessor.isTriggeredTxn() && accessor.getScheduleRef() != null) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/logic/TriggeredTransition.java:82]: Shouldn't this always be true?

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 13]
```diff
@@ -183,49 +251,245 @@ public boolean isCreationPending() {
...
+	}
+
+	@Override
+	public boolean advanceCurrentMinSecond(Instant consensusTime) {
+
+		boolean changed = false;
+
+		long curSecond = schedules.get().getCurrentMinSecond();
+
+		while ((curSecond < Long.MAX_VALUE) && ((curSecond + 1) < Instant.MAX.getEpochSecond()) &&
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:354]: Could these three conditions be simplified to `while (consensusTime.getEpochSecond() - 1 > curSecond)`?

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 14]
```diff
@@ -183,49 +251,245 @@ public boolean isCreationPending() {
...
+				// for processing, we only use the second component for comparison, we only process stuff from the
+				// _previous_ second
+				(consensusTime.getEpochSecond() > (curSecond + 1))
+				&& (!schedules.get().byExpirationSecond().containsKey(new SecondSinceEpocVirtualKey(curSecond)))) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:358]: Law of Demeter would be nice to apply again here, so that we can e.g. do `schedules.get().hasSchedulesExpiringIn(curSecond)`.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 15]
```diff
@@ -183,49 +251,245 @@ public boolean isCreationPending() {
...
+			schedules.get().setCurrentMinSecond(curSecond);
+			return true;
+		}
+
+		return false;
+	}
+
+	@Override
+	public List<ScheduleID> nextSchedulesToExpire(Instant consensusTime) {
+		final List<ScheduleID> list = new ArrayList<>();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:374]: Since we generally won't have anything to expire, we should postpone creating this `ArrayList` until we know we need it.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 16]
```diff
@@ -183,49 +251,245 @@ public boolean isCreationPending() {
...
+
+		long curSecond = schedules.get().getCurrentMinSecond();
+
+		if (!shouldProcessSecond(consensusTime, curSecond)) {
+			return list;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:379]:
```suggestion
			return Collections.emptyList();
```

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 17]
```diff
@@ -183,49 +251,245 @@ public boolean isCreationPending() {
...
+					schedules.get().byEquality().remove(equalityKey);
+				} else {
+					schedules.get().byEquality().put(equalityKey, byEquality);
+				}
+			}
+		}
+	}
+
+	@Override
+	public boolean advanceCurrentMinSecond(Instant consensusTime) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:348]: Why is this method public? It seems more appropriate as a `private` method that is called at the beginning of `nextSchedulesToExpire()`.

File: hapi-utils/src/main/java/com/hedera/services/throttles/DeterministicThrottle.java [hunk 18]
```diff
@@ -160,6 +163,13 @@ public void resetUsageTo(final UsageSnapshot usageSnapshot) {
 		bucket.resetUsed(usageSnapshot.used());
 	}
 
+	public void resetUsage() {
```
Comment (tinker-michaelj) [inline hapi-utils/src/main/java/com/hedera/services/throttles/DeterministicThrottle.java:166]: I don't think I understand the purpose of this method. 🤔

File: hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java [hunk 19]
```diff
@@ -94,38 +107,13 @@ public boolean shouldThrottleQuery(HederaFunctionality queryFunction, Query quer
 
 	@Override
 	public boolean shouldThrottleTxn(final TxnAccessor accessor, final Instant now) {
+		resetLastAllowedUse();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java:110]: This call and on line #113 appear to change the contract of the method, as well as possibly its performance profile... 🤔 It would be **very** nice if we can only extend/compose `DeterministicThrottling` to get what we need for scheduled throttling. (The current implementation have been extensively tested to enforce the expected TPS in real networks, and if at all possible we shouldn't risk breaking it!)

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 20]
```diff
@@ -0,0 +1,267 @@
...
+		this.scheduleThrottling = scheduleThrottling;
+	}
+
+	/**
+	 * Expires all scheduled transactions, that are in a final state, having an expiry before consensusTime,
+	 * and having an expiry before any transaction that is ready to execute.
+	 */
+	public void expire(Instant consensusTime) {
+
+		while (true) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:98]: I don't understand why this particular `while (true) {...` is necessary. 🤔  But even if it is, for our collective sanity, I would **strongly** prefer we don't have any potentially unbounded iteration of any kind in `handleTransaction`. 😁

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 21]
```diff
@@ -0,0 +1,267 @@
...
+
+				var schedule = store.get(next);
+
+				var parentSignedTxn = schedule.parentAsSignedTxn();
+
+				var accessor = PlatformTxnAccessor.from(
+						SignedTxnAccessor.from(parentSignedTxn.toByteArray()),
+						new SwirldTransaction(parentSignedTxn.toByteArray()));
+
+				sigsAndPayerKeyScreen.applyTo(accessor, Optional.empty());
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:167]: ⚠️ This is a **very** expensive way to just call [`workingSigReqs.keysForOtherParties()`](https://github.com/hashgraph/hedera-services/blob/b02846a83e0076d3eb77d78a966c743eb5a34d79/hedera-node/src/main/java/com/hedera/services/sigs/SigsModule.java#L75) 😁; instead we can,
```
final var scheduledTxn =  schedule.asTxn();  // TODO - add this
final var reqsResult = workingSigReqs.keysForOtherParties(
    scheduledTxn,
    CODE_ORDER_RESULT_FACTORY);
if (requiredKeysResult.hasErrorReport()) {
    // TODO - fail, the required signers for this scheduled transaction no longer exist
}
final var activeCharacter = characteristics.inferredFor(scheduledTxn);
var allKeysActive = true;
final var ignoredSigsFn = publicKey -> INVALID_MISSING_SIG;
final var activationTest = (key, sig) -> schedule.hasValidSignatureFor(key.primitiveKeyIfPresent());
for (final var reqKey : reqsResult.getOrderedKeys()) {
    if (!HederaKeyActivation.isActive(reqKey, ignoredSigsFn, activationTest, activeCharacter)) {
        allKeysActive = false;
        break;
    }  
}
// Now L171 becomes if (allKeysAreActive) { ...
```

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java (hunk 2 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/ServicesState.java:355]: you mean it will always report 0 before the migration is complete?

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java (hunk 3 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:46]: The problem then is we need to enforce that this can only happen at the _first_ transaction that the system processes after startup. Otherwise there is no way to choose how much space to leave between transactions for any possible preceding records.

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java (hunk 5 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:122]: renaming field

File: hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java (hunk 19 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java:110]: First - this actually fixes a bug - gas will drain and not be reclaimed if we throttle based on the txn type.

Also, we need something like this to reclaim the ScheduleCreate throttles if the contained txn causes it to throttle.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 20 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:98]: That's why I added the `(next.equals(previousId))` check :-). I will update with a little more checks. As long as the db works it will not loop forever. 

We need the loop so we expire all non-executable txns until we get to one that is executable.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 21 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:167]: Yep, that should do the trick! We could encapsulate it in a new `ExpiredScheduleSigsVerifier` component that's injected with the `@WorkingStateSigReqs`; and then just call `scheduleSigsVerifier.areAllKeysActive(schedule)` in this method.

File: hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java (hunk 6 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java:181]: Would it be ok if we left these like this? It would be a major re-factor to change at this point and it basically would just be creating more boilerplate. All this is abstracted behind `HederaScheduleStore` for the most part.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 20 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:90]: fixed

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 21 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java]: fixed

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 13 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java]: fixed

File: hedera-node/src/main/java/com/hedera/services/state/logic/SigsAndPayerKeyScreen.java (hunk 10 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/logic/SigsAndPayerKeyScreen.java]: I reverted this changes since it's no longer needed

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java (hunk 3 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java]: I made it so on the first startup you can have an unlimited number of "proceeding" records.

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java (hunk 2 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/ServicesState.java:356]: fixed

**Comment by statop** [comment]
working on rebasing ...

File: hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java [hunk 22]
```diff
@@ -879,6 +877,17 @@ public static boolean isGasThrottled(HederaFunctionality hederaFunctionality) {
 		return CONSENSUS_THROTTLED_FUNCTIONS.contains(hederaFunctionality);
 	}
 
+	public static long getGasLimitForContractTx(final TransactionBody txn, final HederaFunctionality function,
```
Comment (statop) [inline hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java:880]: @shemnon does this look ok?

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java [hunk 23]
```diff
@@ -0,0 +1,323 @@
...
+	public boolean isFirstUsed() {
+		return firstUsed;
+	}
+
+	/**
+	 * Resets this tracker, should be called at the beginning of
+	 * {@link com.hedera.services.state.logic.StandardProcessLogic#incorporateConsensusTxn}
+	 * @param consensusTime the consensusTime passed to incorporateConsensusTxn
+	 */
+	public void reset(final Instant consensusTime) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:124]: Would it be possible to implement this class with the `Instant minConsensusTime` field, and then `int`s for `preTimesUsedByCurrent`, `postTimesUsedByCurrent`, etc?

May seem a bit crazy, but when on a microsecond budget, the three extra `Instant` creations here, and one extra creation in `hasMoreTime()`, actually do feel indulgent...

Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:124]: I'll see what I can do.

File: hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java [hunk 24]
```diff
@@ -67,15 +71,25 @@ public class TxnAwareRecordsHistorian implements RecordsHistorian {
...
 		this.recordCache = recordCache;
+		this.consensusTimeTracker = consensusTimeTracker;
 	}
 
 	@Override
 	public Instant nextFollowingChildConsensusTime() {
-		return txnCtx.consensusTime().plusNanos(1L + followingChildRecords.size());
+		Instant next = txnCtx.consensusTime().plusNanos(1L + followingChildRecords.size());
+
+		if (!consensusTimeTracker.isAllowableFollowingTime(next)) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java:86]: Could `consensusTimeTracker` just return the next time to use here? (And throw if no usable time exists.)

File: hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java [hunk 25]
```diff
@@ -105,6 +119,8 @@ public void saveExpirableTransactionRecords() {
 		save(precedingChildStreamObjs, effPayer, submittingMember);
 		save(topLevelRecord, effPayer, accessor.getTxnId(), submittingMember, consensusNow.getEpochSecond());
 		save(followingChildStreamObjs, effPayer, submittingMember);
+
+		consensusTimeTracker.setActualFollowingRecordsCount(followingChildStreamObjs.size());
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java:123]: Then this might not be necessary.

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java (hunk 11 above)
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java:101]: It still feels confusing that client code needs to use this
```
consensusTimeTracker.isFirstUsed()
    ? consensusTimeTracker.nextTransactionTime(true)
    : consensusTimeTracker.firstTransactionTime()
```
idiom...can we just have `consensusTimeTracker.nextAvailableForTriggeringTransaction()`?

Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java:101]: I was thinking the caller should explicitly be aware of where it allows being the first transaction and where it would only be after the first one.

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java [hunk 26]
```diff
@@ -86,42 +86,64 @@ public StandardProcessLogic(
...
+					? consensusTimeTracker.nextTransactionTime(true)
+					: consensusTimeTracker.firstTransactionTime(), accessor);
+
+			processScheduledTransactions(consensusTime, submittingMember);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java:105]: It seems almost inconceivable the full call stack `processScheduledTransactions -> triggerNextTransactionExpiringAsNeeded -> expire -> advanceCurrentMinSecond` will be inlined, so I would definitely wrap this in a,
```
if (networkCtxManager.currentTxnIsFirstInConsensusSecond()) {
    processScheduledTransactions(consensusTime, submittingMember);
}
```

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java [hunk 27]
```diff
@@ -86,42 +86,64 @@ public StandardProcessLogic(
...
 		} catch (InvalidProtocolBufferException e) {
 			log.warn("Consensus platform txn was not gRPC!", e);
 		} catch (Exception internal) {
 			log.error("Unhandled internal process failure", internal);
 		}
 	}
 
+	private void processScheduledTransactions(Instant consensusTime, long submittingMember) {
+		TxnAccessor triggeredAccessor = null;
+		while (true) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java:117]: Would feel better with a,
```
do {
    ...
} while (hasMore); 
```
construct 😉

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java (hunk 26 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java:105]: I just don't want to have to remember to come back to this if it is possbile to schedule more than a couple of hundred transactions per second ;-). 

Would it be ok to just directly check schedules.getCurrentMinSecond() via a single call to a new function in schedulestore?

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java [hunk 28]
```diff
@@ -0,0 +1,635 @@
...
+import com.swirlds.virtualmap.VirtualValue;
+
+import static com.google.protobuf.ByteString.copyFrom;
+import static com.hedera.services.utils.MiscUtils.asTimestamp;
+import static com.hedera.services.utils.MiscUtils.describe;
+import static com.hederahashgraph.api.proto.java.HederaFunctionality.NONE;
+
+public class ScheduleVirtualValue implements VirtualValue {
+
+	static final int CURRENT_VERSION = 4;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java:69]: Why does the version start at 4? 😁

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java [hunk 29]
```diff
@@ -0,0 +1,635 @@
...
+			out.writeByte((byte) 0);
+		} else {
+			out.writeByte((byte) 1);
+			out.writeLong(calculatedExpirationTime.getSeconds());
+			out.writeInt(calculatedExpirationTime.getNanos());
+		}
+		out.writeByte((byte) (calculatedWaitForExpiry ? 1 : 0));
+		out.writeByte((byte) (executed ? 1 : 0));
+		out.writeByte((byte) (deleted ? 1 : 0));
+		if (resolutionTime == null) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java:325]: `resolutionTime == null` should be true iff `!(executed || deleted)` so this byte seems redundant, but hardly important ofc.

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java (hunk 28 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java:69]: If I recall my reasoning, MerkleSchedule was at 2, and I from an abundance of caution I chose 4.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 30]
```diff
@@ -183,49 +258,239 @@ public boolean isCreationPending() {
...
+						log.error("bySecond contained a schedule in the wrong spot! Removing and expiring it! spot={}, id={}, schedule={}",
+								curSecond, scheduleId, schedule);
+						toRemove.add(Pair.of(instant, id));
+						list.add(scheduleId);
+
+					} else if (schedule.isDeleted() || schedule.isExecuted()) {
+						list.add(scheduleId);
+
+					} else {
+						break outer;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:417]: Using a labeled `break` seems confusing, the semantics would be the same with just a `break` here afaict.

Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:417]: Wouldn't the semantics of a simple `break` here be identical?

Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:417]: no, the outer loop would keep going and list would get more items from later in time.

Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:417]: I could use a bool to break out, but label break is faster ;-)

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 31]
```diff
@@ -183,49 +258,239 @@ public boolean isCreationPending() {
...
+	@Override
+	public List<ScheduleID> nextSchedulesToExpire(Instant consensusTime) {
+
+		long curSecond = schedules.get().getCurrentMinSecond();
+
+		if (!shouldProcessSecond(consensusTime, curSecond)) {
+			return Collections.emptyList();
+		}
+
+		var bySecondKey = new SecondSinceEpocVirtualKey(curSecond);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:385]: Can be `final`.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 32]
```diff
@@ -183,49 +258,239 @@ public boolean isCreationPending() {
...
+						list.add(scheduleId);
+
+					} else {
+						break outer;
+					}
+				}
+			}
+
+			if ((!toRemove.isEmpty()) || (bySecond.getIds().size() <= 0)) {
+				bySecond = schedules.get().byExpirationSecond().get(bySecondKey);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:423]: This is confusing, since we are re-fetching the same value as on line 385, and can only have arrived if that value was non-`null` (line 392). Readability of this method would improve by splitting into helper methods.

Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:423]: The re-fetch is because I was using getForModify before, I will remove. I will split up too.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 33]
```diff
@@ -183,49 +258,239 @@ public boolean isCreationPending() {
...
+		if (changed) {
+			schedules.get().setCurrentMinSecond(curSecond);
+			return true;
+		}
+
+		return false;
+	}
+
+	@Override
+	public List<ScheduleID> nextSchedulesToExpire(Instant consensusTime) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:377]: If I'm reading correctly, to preserve the class invariants, client code **must** follow this call with a loop of `expire(id)` calls for each returned id. 

To me, this suggests we really need a,
```
public void purgeExpiredSchedules(final Instant now) {
  ...
}
```

Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:377]: True. Originally it was going to be more complicated I think, thats why I broke it up.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 34]
```diff
@@ -183,49 +258,239 @@ public boolean isCreationPending() {
...
+		}
+
+		return list;
+	}
+
+	@Override
+	@Nullable
+	public ScheduleID nextScheduleToEvaluate(Instant consensusTime) {
+
+		long curSecond = schedules.get().getCurrentMinSecond();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:447]: This setup duplicates that of `nextSchedulesToExpire`; an internal `@Nullable ScheduleSecondVirtualValue nextSecondToProcess(final Instant now)` would save a few lines.

File: hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java (hunk 23 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java:124]: This is done.

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java (hunk 26 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java]: I added shouldProcessScheduledTransactions to ScheduleProcessing, which should be much faster. It probably won't get in-lined, but I think this is a good middle ground?

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java (hunk 27 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java]: Done, and limit to loops added.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 31 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java]: done

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 32 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java]: removed extra get. I didn't split out yet. Will do if I have time.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 34 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java]: I'll refactor a little time permitting ;-) Trying to get everything fixed first.

File: hedera-node/src/main/java/com/hedera/services/sigs/order/SigRequirements.java [hunk 35]
```diff
@@ -1090,40 +1110,51 @@ private <T> SigningOrderResult<T> scheduleCreate(
...
-				op,
-				ScheduleCreateTransactionBody::hasPayerAccountID,
-				ScheduleCreateTransactionBody::getPayerAccountID,
-				required,
-				linkedRefs);
-		if (failure != NONE) {
-			return accountFailure(failure, factory);
+		// We need to always add the custom payer to the sig requirements even if it equals the payer.
+		// It is still part of the "other" parties and we need to know to store it's key with the schedule
+		// in all cases. This fixes a case where the ScheduleCreate payer and the custom payer are the same payer,
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/sigs/order/SigRequirements.java:1115]: Great point! 😌

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java [hunk 36]
```diff
@@ -0,0 +1,218 @@
...
+			in.get(keyBytes);
+			var key = new String(keyBytes, StandardCharsets.UTF_8);
+			ids.put(key, in.getLong());
+		}
+	}
+
+	@Override
+	public void serialize(SerializableDataOutputStream out) throws IOException {
+		out.writeInt(ids.size());
+		for (var e : ids.entrySet()) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java:114]: ⚠️ `HashMap` iteration is non-deterministic in the presence of garbage collection and/or VM restarts. We need to either sort the keys before serializing them; or use a `SortedMap` implementation.

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java (hunk 28 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java:69]: Since you're using a new `RUNTIME_CONSTRUCTABLE_ID`, you're free to start the version at 1.

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java (hunk 36 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java:114]: Good catch!

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleSecondVirtualValue.java [hunk 37]
```diff
@@ -0,0 +1,249 @@
...
+	@Override
+	public ScheduleSecondVirtualValue copy() {
+		var fc = new ScheduleSecondVirtualValue(ids);
+
+		this.setImmutable(true);
+
+		return fc;
+	}
+
+	public void add(RichInstant instant, LongList idList) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleSecondVirtualValue.java:170]: The second argument is a `LongList` instead of `long` just to future-proof for a transaction type that schedules multiple transactions at once?

A small javadoc that clarifies why this is a `LongList` might be nice.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java [hunk 38]
```diff
@@ -164,9 +204,44 @@ public ResponseCodeEnum delete(ScheduleID id) {
 	public void commitCreation() {
 		throwIfNoCreationPending();
 
-		var id = fromScheduleId(pendingId);
-		schedules.get().put(id, pendingCreation);
-		extantSchedules.put(pendingCreation.toContentAddressableView(), id);
+		var id = new EntityNumVirtualKey(fromScheduleId(pendingId));
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:207]: Lines 207-243 feel like they should be encapsulated in `MerkleScheduledTransactions`.

File: hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java [hunk 39]
```diff
@@ -134,22 +121,32 @@ public boolean wasLastTxnGasThrottled() {
...
 		gasThrottle.leakUnusedGasPreviouslyReserved(value);
 	}
 
 	@Override
 	public boolean shouldThrottleQuery(HederaFunctionality queryFunction, Instant now, Query query) {
+		resetLastAllowedUse();
 		if (isGasThrottled(queryFunction) &&
 				dynamicProperties.shouldThrottleByGas() &&
 				(gasThrottle == null || !gasThrottle.allow(now, query.getContractCallLocal().getGas()))) {
+			reclaimLastAllowedUse();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java:137]: Is this needed? Seems we haven't yet had the opportunity to use capacity in anything but the `gas` bucket.

File: hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java [hunk 40]
```diff
@@ -288,15 +425,183 @@ private boolean shouldThrottleMint(ThrottleReqsManager manager, TokenMintTransac
...
+			}
+		}
+
+		// dedup the min tps groups
+		final IdentityHashMap<ThrottleGroup, ThrottleBucket> groups = new IdentityHashMap<>();
+		for (var grp : minMtps.values()) {
+			groups.put(grp, null);
+		}
+
+		// filter out throttle groups we no longer need and set burst periods to 1
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java:507]: I don't follow why we want to clamp all burst periods to 1; to limit scheduled transactions to some fraction `1/f` of the capacity for normal transactions, why not just take these modified buckets and do `asThrottleMapping(f)`?

(The burst periods will be auto-scaled to ensure every operation group can accept a transaction.)

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 41]
```diff
@@ -0,0 +1,288 @@
...
+			@ScheduleThrottle final TimedFunctionalityThrottling scheduleThrottling,
+			final Supplier<MerkleScheduledTransactions> schedules) {
+		this.sigImpactHistorian = sigImpactHistorian;
+		this.store = store;
+		this.scheduleExecutor = scheduleExecutor;
+		this.dynamicProperties = dynamicProperties;
+		this.scheduleThrottling = scheduleThrottling;
+		isFullySigned = scheduleSigsVerifier::areAllKeysActive;
+		this.schedules = schedules;
+		this.maxProcessingLoopIterations = dynamicProperties.schedulingMaxTxnPerSecond() * 2;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:88]: Seems unlikely this setting will need to be updated dynamically, but setting the field once here eliminates our option.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 42]
```diff
@@ -0,0 +1,288 @@
...
+	 * and having an expiry before any transaction that is ready to execute.
+	 */
+	public void expire(Instant consensusTime) {
+
+		// we _really_ don't want to loop forever. If the database isn't working, then it's possible. So we put
+		// an upper limit on the number of iterations here.
+		for (long i = 0; i < maxProcessingLoopIterations; ++i) {
+			store.advanceCurrentMinSecond(consensusTime);
+
+			List<ScheduleID> txnIdsToExpire = store.nextSchedulesToExpire(consensusTime);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:102]: Is there a reason this variable is named `txnIdsToExpire` instead of e.g., `scheduleIdsToExpire`?

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 43]
```diff
@@ -0,0 +1,288 @@
...
+			if (txnIdsToExpire.isEmpty()) {
+				return;
+			}
+
+			for (var txnId : txnIdsToExpire) {
+				store.expire(txnId);
+				sigImpactHistorian.markEntityChanged(fromScheduleId(txnId).longValue());
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:109]: Could also do,
```
sigImpactHistorian.markEntityChanged(txnId.getScheduleNum());
```

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 44]
```diff
@@ -0,0 +1,288 @@
...
+			expire(consensusTime);
+
+			var next = store.nextScheduleToEvaluate(consensusTime);
+
+			if (next == null) {
+				return null;
+			}
+
+			// avoid creating a hash set in the normal case where we don't actually process any scheduled txns
+			if (seen == null) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:142]: What's the reasoning for this test?

The code below seems to guarantee `store.expire(next.getScheduleNum())` will always be called.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 45]
```diff
@@ -0,0 +1,288 @@
...
+
+			var bySecond = store.getBySecond(curSecond);
+
+			if (bySecond != null) {
+				bySecond.getIds().values().forEach(ids -> ids.forEach(id -> {
+					var existing = store.getNoError(EntityNum.fromLong(id).toGrpcScheduleId());
+
+					if (existing != null) {
+						if (existing.calculatedExpirationTime().getSeconds() != curSecond) {
+							log.error("bySecond contained a schedule in the wrong spot! Ignoring it! spot={}, id={}, schedule={}",
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:234]: We try to reserve `ERROR` for unrecoverable events; here a `WARN` seems more appropriate, since we just skip the misplaced schedule.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 46]
```diff
@@ -0,0 +1,288 @@
...
+			for (var entry : transactions.entrySet()) {
+				for (var t : entry.getValue()) {
+					if (scheduleThrottling.shouldThrottleTxn(t, timestamp)) {
+						if (scheduleThrottling.wasLastTxnGasThrottled()) {
+							return SCHEDULE_FUTURE_GAS_LIMIT_EXCEEDED;
+						} else {
+							return SCHEDULE_FUTURE_THROTTLE_EXCEEDED;
+						}
+					}
+					timestamp = timestamp.plusNanos(1);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:261]: Should we use,
```
final var maxTxnSpacing = 1_000_000_000L / transactions.size();
...
timestamp = timestamp.plusNanos(maxTxnSpacing);
```
...to let the maximum capacity drain from the throttle bucket?

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java [hunk 47]
```diff
@@ -0,0 +1,288 @@
...
+							list.add(SignedTxnAccessor.uncheckedFrom(existing.asSignedTxn()));
+						}
+					} else {
+						log.error("bySecond contained a schedule that does not exist! Ignoring it! second={}, id={}",
+								curSecond, id);
+					}
+				}));
+			}
+
+			var list = transactions.computeIfAbsent(schedule.calculatedExpirationTime(), k -> new ArrayList<>());
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:248]: What's the reasoning for building this list and then iterating through it to check throttles?

Can we not just convert the above nested `.forEach()` into nested `for` loops and update throttle capacity immediately as we encounter each schedule?

**Review by tinker-michaelj — COMMENTED** [review]
Looking great, readability is continuously improving, I made it through all the source files in one workday for the first time! 🎉 😅

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java (hunk 26 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java]: Definitely lower-hanging fruit to pick given that change! Sounds good to me.

File: hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java (hunk 27 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java]: Awesome!

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 30 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java:417]: Ah got it. 👍

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 32 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java]: Looks much cleaner.

File: hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java (hunk 8 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryManager.java:149]: Not urgent, we could remove in a separate PR.

File: hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/sigs/metadata/StateChildrenSigMetadataLookup.java:181]: True, I think this kind of boilerplate helps the reader's eye keep moving tho.

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java (hunk 28 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleVirtualValue.java:69]: done

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleSecondVirtualValue.java (hunk 37 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleSecondVirtualValue.java:170]: Yeah, it is possible to schedule more than one thing for the same second.

File: hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java (hunk 40 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java:507]: I was finding that the auto scaling overflows very easily and causes bounds checks elsewhere to throw.

I never really followed the internal math for the buckets so I didn't dare touch them. 

Setting the burst to 1 was the most straight forward method to say "this exact ops per second" that I got to work well without errors.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 44 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:142]: If you mean the has set creation, then I just wanted to avoid creating the hash set unless it was really going to be used. The vast majority of the time we never get to this line because next is null.

If you mean the set checks in general, then it's just another defensive check to prevent database errors / my errors causing infinite loops or bad state.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 45 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:234]: Changing. Are the other logs here and in schedulestore at the appropriate level? I think the error ones really would be bad if they are happening.

File: hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java (hunk 46 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleProcessing.java:261]: I think this is one of the reasons why I set the burst period to 1.

We really don't want it to drain at all. We are limiting to a certain exact tps.

File: hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java (hunk 34 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java]: I usually avoid helper methods when they must return multiple values and the usages are slightly different. In this example it would need to return 3 different values and if we ever get getForModify working then the usages might be very different.

File: hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java (hunk 36 above)
Comment (statop) [reply hedera-node/src/main/java/com/hedera/services/state/virtual/schedule/ScheduleEqualityVirtualValue.java:117]: fixed
