### PR TITLE
Move CI to GCP

### LINKED ISSUE #851: Move continuous-integration workflow to run on GCP
**Summary**
Currently all nightly regression tests are moved to run on GCP. Move continuous-integration workflow which is dependent on infrastructure branch to GCP.
Currently all nightly regression tests are moved to GCP from AWS. Move the `continuous-integration` workflow to GCP from AWS instances.

- [x] Created much smaller size instance image with 20GB or 40GB

- [x] Add functionality to choose instance image from JSON

- [x] investigate about spot instances using `--preemptive` tag - This is not a feasible option as regression workflow is not fault tolerant and using this tag will not instantiate instances immediately sometimes. But regression workflow will stop after the time given. This will not make sure all our tests have run.

- [x] Add a workflow in config.yml for gcp continuous integration

- [x] Add all tests needed in a JSON file on regression side

- [x] Validate all tests are successfully running

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Moved Continuous Integration workflow to GCP.  Now it runs on both AWS and GCP when developer commits to their branch.

Related platform-regression PR : https://github.com/swirlds/swirlds-platform-regression/pull/724
**Don't merge until Platform-regression PR is merged**

Platform test passed: https://hedera-hashgraph.slack.com/archives/CJ1P4A2NS/p1607701422331900

**Related issue(s)**:
Closes #851 

Platform and services regression is running

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicDeleteSuite.java [hunk 1]
```diff
@@ -111,7 +111,7 @@ private HapiApiSpec deleteWithAdminKey() {
 	}
 
 	private HapiApiSpec deleteFailedWithWrongKey() {
-		long PAYER_BALANCE = 1_999_999_999_999L;
+		long PAYER_BALANCE = 1_999_999_999L;
```
Comment (JeffreyDallas) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicDeleteSuite.java:114]: reason to lower balance ?

**Review by JeffreyDallas — APPROVED** [review]

**Review by ljianghedera — APPROVED** [review]
LGTM

File: test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicDeleteSuite.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicDeleteSuite.java:114]: When running all tests together in suite, its giving `INSUFFICIENT_PAYER_BALANCE`. As we are not testing anything in this test with higher balance, I reduced the balance on two tests.
