### PR TITLE
Fix `AutoAccountCreationSuite` Fees

### LINKED ISSUE #9409: Fix tests failing with fees in AutoAccountCreationSuite

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #9409

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java [hunk 1]
```diff
@@ -285,7 +283,6 @@ private HapiSpec okToRepeatSerialNumbersInWipeList() {
     private HapiSpec okToRepeatSerialNumbersInBurnList() {
         return defaultHapiSpec("okToRepeatSerialNumbersInBurnList")
                 .given(
-                        snapshotMode(FUZZY_MATCH_AGAINST_HAPI_TEST_STREAMS),
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:288]: We _don't_ want this anymore?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java [hunk 2]
```diff
@@ -110,7 +109,7 @@
 import org.apache.logging.log4j.LogManager;
 import org.apache.logging.log4j.Logger;
 
-@HapiTestSuite
+// @HapiTestSuite
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java]: Intentional?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java [hunk 3]
```diff
@@ -418,12 +419,12 @@ public Fees calculateFees(@NonNull final FeeContext feeContext) {
         // Variable bytes plus two additional longs for balance and auto-renew period; plus a boolean for receiver sig
         // required.
         final var op = feeContext.body().cryptoCreateAccountOrThrow();
-        final var keySize = op.hasKey() ? getAccountKeyStorageSize(fromPbj(op.keyOrThrow())) : 0L;
+        final var keySize = op.hasKey() ? getAccountKeyStorageSize(fromPbj(op.keyOrElse(Key.DEFAULT))) : 0L;
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java:422]: Not a problem, but I'm curious why the change here?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java [hunk 4]
```diff
@@ -101,7 +103,10 @@ public FeeCalculatorImpl(
         // not something we really should know about here. But, since we're going to replace the fee system later
         // with a simpler model, for now, we'll go ahead and check the transaction body type here.
         final var baseMeta = new BaseTransactionMeta(
-                txBody.memo().getBytes(StandardCharsets.UTF_8).length, // Has to be a faster way...
+                // For some reason in mono-service while auto-creating we don't consider memo bytes for fees
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java:106]: Probably worth creating a ticket for after differential testing to change this

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java [hunk 5]
```diff
@@ -344,10 +345,10 @@ private static long baseSizeOf(final CryptoUpdateTransactionBody op, final long
      * @param account the {@link Account} to be updated
      * @return the calculated bytes
      */
-    private static long cryptoAutoRenewRb(final Account account) {
+    private static long cryptoAutoRenewRb(@Nullable final Account account) {
         return CRYPTO_ENTITY_SIZES.fixedBytesInAccountRepr()
-                + currentNonBaseBytes(account)
-                + account.numberAssociations() * CRYPTO_ENTITY_SIZES.bytesInTokenAssocRepr();
+                + (account == null ? 0 : currentNonBaseBytes(account))
+                + (account == null ? 0 : account.numberAssociations()) * CRYPTO_ENTITY_SIZES.bytesInTokenAssocRepr();
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:351]: How about something like
```java
private static long cryptoAutoRenewRb(@Nullable final Account account) {
    var total = CRYPTO_ENTITY_SIZES.fixedBytesInAccountRepr();
    if (account != null) {
        total += currentNonBaseBytes(account) + (account.numberAssociations() * CRYPTO_ENTITY_SIZES.bytesInTokenAssocRepr());
    }
    return total;
}
``` 

instead of checking if the account is null twice?

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java [hunk 6]
```diff
@@ -110,7 +110,7 @@
 import org.apache.logging.log4j.LogManager;
 import org.apache.logging.log4j.Logger;
 
-@HapiTestSuite
+ @HapiTestSuite
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java:113]: Nit: extra space

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java:106]: Agreed will do.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java (hunk 3 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java:422]: Yes, unnecessary. Will change back. I was just removing `throwing`  in `calculateFees`

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java (hunk 5 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:351]: Make sense. Fixed. Thanks @mhess-swl

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java (hunk 6 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java]: Fixed.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java:288]: It was failing in my local for that reason. Not sure why. I will start with `CryptoTransferSuite` Fuzzy matching and will enable it.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java]: No reverted it back

**Review by mhess-swl — APPROVED** [review]
LGTM!

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java:106]: Done https://github.com/hashgraph/hedera-services/issues/9749

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
