### PR TITLE
chore: fix wiring diagram

### LINKED ISSUE #22574: Move InternalEventValidator to EventIntakeModule

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

This PR fixes the generation of the wiring diagram. The diagram will use the actual implementation and show internal components.

**Related issue(s)**:

Fixes #22574

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/ConsensusModuleBuilder.java [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+     * @return an instance of {@code EventIntakeModule}
+     * @throws IllegalStateException if no implementation is found
+     */
+    public static EventIntakeModule createEventIntakeModule() {
+        return ServiceLoader.load(EventIntakeModule.class)
+                .findFirst()
+                .orElseThrow(() -> new IllegalStateException("No EventIntakeModule implementation found!"));
+    }
+
+    public static EventIntakeModule createNoOpEventIntakeModule(@NonNull final WiringModel model, @NonNull final
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/ConsensusModuleBuilder.java]: nit: javadoc

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java [hunk 2]
```diff
@@ -1,6 +1,15 @@
 // SPDX-License-Identifier: Apache-2.0
 package com.swirlds.platform.cli;
 
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createEventCreatorModule;
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createEventIntakeModule;
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createNoOpEventCreatorModule;
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createNoOpEventIntakeModule;
+
+import com.hedera.hapi.node.state.roster.Roster;
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java]: nit: I think many of these imports are not necessary. Did you run spotless?

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java [hunk 3]
```diff
@@ -1,11 +1,18 @@
...
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createEventCreatorModule;
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createEventIntakeModule;
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createNoOpEventCreatorModule;
+import static com.swirlds.platform.builder.ConsensusModuleBuilder.createNoOpEventIntakeModule;
 import static org.junit.jupiter.api.Assertions.assertFalse;
 import static org.mockito.Mockito.mock;
 import static org.mockito.Mockito.when;
 
 import com.hedera.hapi.node.state.roster.Roster;
+import com.hedera.hapi.node.state.roster.RosterEntry;
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java]: nit: same here, I think these imports are not needed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/ConsensusModuleBuilder.java (hunk 1 above)
Comment (netopyr) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/ConsensusModuleBuilder.java]: Added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java (hunk 2 above)
Comment (netopyr) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/DiagramCommand.java]: Darn! I forgot. Thanks for making me aware.

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java (hunk 3 above)
Comment (netopyr) [reply platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/wiring/PlatformWiringTests.java]: Fixed
