### PR TITLE
Don't recurse when assessing self-denominated fixed fees 

### LINKED ISSUE #1825: HIP-18 response code suggestion
### Problem

In the original implementation, the transaction fee payer account was responsible for paying the custom token fees. If the transaction fee-paying account did not have enough of the token to pay for the fee then `INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE` response was returned.

With the new implementation, the sender account is now responsible for paying the custom fees. When I see 'payer' in a response code I am thinking about the transaction fee payer account and not the sending account. 

### Solution

Update the response code to specify the sender account does not have enough token balance to pay for the custom fee.
`INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE`

### Alternatives

_No response_

### LINKED ISSUE #1925: Fixed fees cannot be assessed in the units of an owning token
### Description

Suppose `0.0.T` is a token with a custom fee schedule, and includes a fixed fee of `5T` units.

Say we then submit a `CryptoTransfer` that sends `100T` from account `A` to account `B`.

This will trigger a custom fee of `5T`. **Because** custom fees must be charged recursively, this `-5T` balance change will itself trigger another `-5T` fee, and so on...

Thus the result of any such `CryptoTransfer` will be `CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH`

‼️ Note there _is_ a work-around using `FractionalFee`. To achieve the fixed `5T` as above, we can create a fractional fee with:

1. `fractional_amount=1/9223372036854775807`
2. `minimum_amount=5`

Even if `T` has the maximum supply, the fraction is so tiny that the minimum fee of `5T` will always be assessed instead.

### Steps to reproduce

Create a token with a custom fee schedule that includes a fixed fee denominated by the `0.0.0` token (meaning units of the newly created token).

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.16.1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Closes #1925
- Closes #1825

**Description**:
- Add an [`exemptFromCustomFees` field](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java#L59) in `BalanceChange`.
- Pass the `chargingToken` id to the [`HtsFeeAssessor.assess()` method](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java#L83). 
- When the `chargingToken` matches an HTS fee `denom`, [set `exemptFromCustomFees=true`](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/grpc/marshalling/AdjustmentUtils.java#L63).
- In `BalanceChangeManager.nextAssessableChange()`, [ignore any `BalanceChange`](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/hedera-node/src/main/java/com/hedera/services/grpc/marshalling/BalanceChangeManager.java#L125) marked exempt.
- Add [`TokenTransactSpecs.canTransactInTokenWithSelfDenominatedFixedFee()` EET](https://github.com/hashgraph/hedera-services/blob/01925-M-TrackFeeExemptBalanceChanges/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java#L1312), along with some improvements to assertions on `tokenTransferLists` in records.
- Switch to `INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE` response code.

### CODE REVIEW

**Review by anighanta — APPROVED** [review]

**Review by ljianghedera — APPROVED** [review]
Looks awesome!

**Review by abhishek-hedera — APPROVED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java [hunk 1]
```diff
@@ -1302,6 +1309,109 @@ public HapiApiSpec nestedHtsCaseStudy() {
...
+	 *   1. Create fungible "protocolToken" to use for a custom fee.
+	 *   2. Create non-fungible "artToken" with custom fee of 1 unit protocolToken.
+	 *   3. Use account "gabriella" as treasury for both tokens.
+	 *   4. Create account "harry" associated ONLY to artToken.
+	 *   5. Mint serial no 1 for art token, transfer to harry (no custom fee since gabriella is treasury and exempt).
+	 *   6. Transfer serial no 1 back to gabriella from harry.
+	 *     - Transfer fails (correctly) with TOKEN_NOT_ASSOCIATED_TO_ACCOUNT, as harry
+	 *       isn't associated to protocolToken and can't pay the custom fee
+	 *     - But...a following getTokenNftInfo query shows that harry is no longer the owner of serial no 1!
+	 *     - This is because nftsLedger.rollback() wasn't actually called, even thought the transfer failed.
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java:1365]: nit: `even though`

**Review by qnswirlds — APPROVED** [review]
LGTM overall. Some new files in test-clients are missing license header.
