### PR TITLE
fix: 11353: Metadata HIPs - Implement TokenUpdateNftsHandler

### LINKED ISSUE #11353: Metadata HIPs - Implement TokenUpdateNftHandler and its tests

### PR DESCRIPTION
**Pull request by thomas-swirlds-labs**
**Description**:

- Add a new TokenUpdateNftsHandler under token-service that implements TransactionHandler
- In validateSemantics: 
     1. Validate the metadata to be updated has size is less than tokens.maxMetadataBytes(if metadata field is present).
     2. Validate if the Nft or list of Nfts given in the transaction body exist in state. If not throw appropriate response code.
 - Set the updated metadata on all the Nft entities from the TokenUpdateNftsTransactionBody
 
*Signing Requirements*:
 - In prehandle() of TokenUpdateNftHandler get the required keys to sign. In this case metadataKey should sign

*Fees*:
- In calculateFees() count the number of nft ids given in the list from transaction body.
- Total price should be N * $0.001, if the list contains N nft ids
- Add op.getMetadataList().size() to BPT

**Related issue(s)**:

Epic #10931 
Fixes #11353 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/configuration/dev/api-permission.properties [hunk 1]
```diff
@@ -60,6 +60,7 @@ tokenFeeScheduleUpdate=0-*
 tokenPause=0-*
 tokenUnpause=0-*
 tokenGetNftInfos=0-*
+tokenUpdateNfts=0-*
```
Comment (Neeharika-Sompalli) [inline hedera-node/configuration/dev/api-permission.properties:63]: We might not need this

File: hedera-node/data/config/api-permission.properties [hunk 2]
```diff
@@ -60,6 +60,7 @@ tokenFeeScheduleUpdate=0-*
 tokenPause=0-*
 tokenUnpause=0-*
 tokenGetNftInfos=0-*
+tokenUpdateNfts=0-*
```
Comment (Neeharika-Sompalli) [inline hedera-node/data/config/api-permission.properties:63]: same here. Need to verify though

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java [hunk 3]
```diff
@@ -128,6 +133,12 @@ public <C> C getStore(@NonNull final Class<C> storeInterface) throws IllegalArgu
             }
             return storeInterface.cast(store);
         }
+        logger.info(
+                "Creating store for {},entry {}, serviceName {}, all stores {}",
+                storeInterface,
+                entryName,
+                serviceName,
+                STORE_FACTORY.keySet());
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java:141]: Do we need this log?

File: hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json [hunk 4]
```diff
@@ -4800,6 +4846,52 @@
           ]
         }
       },
+      {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json:4849]: We should change all the `feeSChedule.json` available in the repo. Expecially ones under `configuration/mainnet` and `configuration/testnet`

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+
+    @Override
+    public void preHandle(@NonNull final PreHandleContext context) throws PreCheckException {
+        requireNonNull(context);
+        final var op = context.body().tokenUpdateNftsOrThrow();
+        pureChecks(context.body());
+        final var tokenId = op.tokenOrThrow();
+        final var tokenStore = context.createStore(ReadableTokenStore.class);
+        final var tokenMetadata = tokenStore.getTokenMeta(tokenId);
+        if (tokenMetadata == null) throw new PreCheckException(INVALID_TOKEN_ID);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:78]: We should do this check in `tokenUpdateNftValidator.validateSemantics(context, op);`

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+        final var tokenNftId = op.tokenOrThrow();
+
+        final var validationResult = tokenUpdateNftValidator.validateSemantics(context, op);
+        final var token = validationResult.token();
+        final var nftStore = context.writableStore(WritableNftStore.class);
+
+        // Wrap in Set to de-duplicate serial numbers
+        final var nftSerialNums = new ArrayList<>(new LinkedHashSet<>(op.serialNumbers()));
+        var nftCount = nftSerialNums.size();
+        validateTrue(nftCount <= nftStore.sizeOfState(), INVALID_TRANSACTION_BODY);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:95]: You think `INVALID_NFT_ID` is appropriate here ? Since the `TransactionBody` is valid , but the serials provided are wrong

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java [hunk 7]
```diff
@@ -0,0 +1,138 @@
...
+        validateTrue(!nftSerialNums.isEmpty(), INVALID_TRANSACTION_BODY);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:96]: We probably need a response like `MISSING_SERIAL_NUMBERS`

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java (hunk 3 above)
Comment (thomas-swirlds-labs) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java:141]: No. Agreed it can be removed. 👍

File: hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json (hunk 4 above)
Comment (thomas-swirlds-labs) [reply hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json:4849]: I will add the feeSchedules.json under `mono/src/test` also.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java (hunk 7 above)
Comment (thomas-swirlds-labs) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:96]: Yeah I think MISSING_SERIAL_NUMBERS is more appropriate than either this (or INVALID_NFT_ID)
