### PR TITLE
test: yahcli schedule regression tests

### LINKED ISSUE #20836: Write new yahcli regression tests exercising all existing commands from the readme
Assume a `yahcli("<command line">)` operation exists---implement as a `NoOp` for now. See branch `20836-yahcli-reg-tests` for reference. 

- [x] Creating a new account - @tinker-michaelj 
- [ ] Updating system files - @JivkoKelchev 
- [x] Preparing for an NMT upgrade - @ibankov 
- [x] Launching an NMT telemetry upgrade - @ibankov 
- [ ] Scheduling a network freeze - @JivkoKelchev 
- [x] Re-keying an account - @ibankov 
- [x] Getting deployed version info of a network - @ibankov 
- [x] Creating a new key - @ibankov 
- [x] Printing key details - @ibankov 
- [x] Changing a staking election - @ibankov 
- [ ] Scheduling a transaction - @JivkoKelchev 
- [ ] Scheduling public key list update - @JivkoKelchev 
- [x] Activating staking after a network reset - @ibankov 
- [x] (DAB) Creating a node - @ibankov 
- [x] (DAB) Deleting a node - @ibankov 
- [x] (DAB) Updating a node - @ibankov 
- [ ] Add regression test PR check

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

- Adds Yahcli regression tests for scheduling `accounts send` and `accounts update` commands examples.
- Adds Yahcli regression tests for `freeze`, `freeze-upgrade` and `freeze-abort` commands examples.

**Related issue(s)**:
Fixes #20836

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/schedules/SignCommand.java [hunk 1]
```diff
@@ -27,13 +27,19 @@ public class SignCommand implements Callable<Integer> {
             description = "schedule Id to sign")
     String scheduleId;
 
+    @CommandLine.Option(
+            names = {"-k", "--key"},
+            paramLabel = "path to the key file",
+            defaultValue = "<N/A>")
+    String keyLoc;
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/schedules/SignCommand.java]: Yahcli typically assumes the path to the `<target>/keys` directory to get the key file. This new param shouldn't be necessary.

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/ScheduleSuite.java [hunk 2]
```diff
@@ -35,10 +39,20 @@ public List<Stream<DynamicTest>> getSpecsInSuite() {
...
+        final var scheduleSign = new HapiScheduleSign(fqScheduleId);
+        final var opsList = new ArrayList<SpecOperation>();
+
+        if ("<N/A>".equals(keyFilePath)) {
+            opsList.add(scheduleSign);
+        } else {
+            final var currKey = "currKey";
+            opsList.add(UtilVerbs.keyFromFile(currKey, keyFilePath));
+            opsList.add(scheduleSign.alsoSigningWith(currKey));
+        }
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/ScheduleSuite.java]: Again, shouldn't be necessary

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/FreezeCommandsTest.java [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+                        .exposingOutputTo(output -> assertTrue(output.contains("NMT software upgrade in motion from"))),
+                yahcliFreezeAbort().exposingOutputTo(freezeAbortIsSuccessful()));
+    }
+
+    private String getFiveDaysFromNowString() {
+        final var fiveDaysFromNow = Instant.now().plus(5, DAYS);
+        DateTimeFormatter formatter =
+                DateTimeFormatter.ofPattern("yyyy-MM-dd.HH:mm:ss").withZone(systemDefault());
+        return formatter.format(fiveDaysFromNow);
+    }
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/FreezeCommandsTest.java:53]: Did I see this same method in another PR? If so, let's extract to a utility method. Otherwise, just ignore me 🤪

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java [hunk 4]
```diff
@@ -88,7 +88,8 @@ public Integer call() throws Exception {
                 effectiveMemo,
                 denomination,
                 accountsCommand.getYahcli().isScheduled(),
-                insideBatch);
+                insideBatch,
+                accountsCommand.getYahcli().getRegistryCallback());
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java]: We should avoid exposing this registry callback in the production code if at all possible

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java [hunk 5]
```diff
@@ -810,6 +843,10 @@ public void run() {
         if (specStateObserver != null) {
             specStateObserver.observe(new SpecStateObserver.SpecState(hapiRegistry, keyFactory));
         }
+
+        if (registryCb != null) {
+            registryCb.accept(hapiRegistry);
+        }
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java]: This functionality essentially already exists with `specStateObserver` (see line immediately above, the registry and the key factory are passed in)

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/UpdateSuite.java [hunk 6]
```diff
@@ -46,7 +55,7 @@ final Stream<DynamicTest> doUpdate() {
         Key newList = Key.newBuilder()
                 .setKeyList(KeyList.newBuilder().addAllKeys(keys))
                 .build();
-        HapiTxnOp<?> update = new HapiCryptoUpdate(HapiSuite.DEFAULT_SHARD_REALM + targetAccount)
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/UpdateSuite.java:49]: Yikes, I missed updating this suite with nonzero shard/realm 😳 tyvm!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java [hunk 7]
```diff
@@ -286,6 +288,13 @@ public String toString() {
      */
     @Nullable
     private SpecStateObserver specStateObserver;
+    /**
+     * If non-null, a callback function that will be invoked with this spec's registry after test execution.
+     * Used to extract or process registry information after the spec has completed.
+     */
+    @Nullable
+    private Consumer<HapiSpecRegistry> registryCb;
+
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java]: We don't need this for every spec imo. This fits better in `YahcliCallOperation` for now

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/UpdateSuite.java [hunk 8]
```diff
@@ -57,11 +66,13 @@ final Stream<DynamicTest> doUpdate() {
...
-                .withProperties(specConfig)
-                .given()
-                .when()
-                .then(update);
+        final var spec = new HapiSpec(
+                "DoUpdate", new MapPropertySource(configManager.asSpecConfig()), new SpecOperation[] {update});
+
+        if (registryCb != null) {
+            spec.setRegistryCb(registryCb);
+        }
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/UpdateSuite.java]: We want to minimize how much of the test framework is visible in this production code, so we don't want to let the hapi spec registry leak here. Instead we can get a reference to the registry using SpecStateObserver as described below for the tests.

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java [hunk 9]
```diff
@@ -44,7 +60,11 @@ protected YahcliCallOperation self() {
     @Override
     public Optional<Throwable> execFor(@NonNull final HapiSpec spec) {
         requireNonNull(spec);
-        final var commandLine = new CommandLine(new Yahcli());
+        final var yahcli = new Yahcli();
+        if (registryCb != null) {
+            yahcli.setRegistryCb(registryCb);
+        }
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: Instead of introducing an entirely new registry callback (in this class and in `HapiSpec`), we can stay consistent with the terminology and functionality of the rest of the test framework by utilizing the `SpecStateObserver` interface.  First, instead of `registryCb`, we simply call this `observer`; then we have `YahcliCallOperation` implement `SpecStateObserver`, and invoke the observer inside this `execFor` method instead. That way the `Yahcli` interface doesn't need to change at all.
I.e. something like:

```
// Only added/changed fields, methods shown
public class YahcliCallOperation ... implements SpecStateObserver {

    private SpecStateObserver observer;

    public YahcliCallOperation observing(@NonNull final Consumer<HapiSpecRegistry> registryCb) {
        this.observer = observer;
        return this;
    }

	@Override
	public void observe(@NonNull final SpecState specState) {
        observer.observe(specState);
	}

    @Override
    public Optional<Throwable> execFor(HapiSpec spec) {
        // same as before
        try {
            // same as before 
            // ... 

            // but add:
			if (observer != null) {
				observer.observe(new SpecState(spec.registry(), spec.keys()));
			}
        } catch (Throwable t) {
            return Optional.of(t);
        }
        return Optional.empty();
    }
}
```

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java [hunk 10]
```diff
@@ -0,0 +1,192 @@
...
+                                        "--to",
+                                        asAccountString(spec.accountIdFactory().apply(newAccountNum.get())),
+                                        "--memo",
+                                        "\"Never gonna give you up\"",
+                                        String.valueOf(5))
+                                .schedule()
+                                .exposingCommandSpecRegistry(registry -> {
+                                    var num = registry.getScheduleId("original").getScheduleNum();
+                                    newScheduleNum.set(num);
+                                }))),
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]: Using `SpecStateObserver` as described above, this `doingContextual(...)` then becomes:

```
doingContextual(spec -> allRunFor(
        spec,
        yahcliAccounts(
                        "send",
                        "--to",
                        asAccountString(spec.accountIdFactory().apply(newAccountNum.get())),
                        "--memo",
                        "\"Never gonna give you up\"",
                        String.valueOf(5))
                .schedule()
                .observing(specState -> {
                    var num = specState.registry().getScheduleId("original").getScheduleNum();
                    newScheduleNum.set(num);
                }))),
```

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java [hunk 11]
```diff
@@ -0,0 +1,192 @@
...
+                // Sign the schedule with all keys
+                doingContextual(spec -> allRunFor(
+                        spec,
+                        // sign with account R key
+                        yahcliScheduleSign(
+                                "sign",
+                                "--scheduleId",
+                                String.valueOf(scheduleNum.get()),
+                                "-k",
+                                accountKeyPath(String.valueOf(accountNumR.get()))),
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]: We want yahcli to assume the default `<target network>/keys` path (instead of using a new `-k` param) since that's what devops would be doing, here and in all the `yahcliScheduleSign` calls in this test

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java [hunk 12]
```diff
@@ -0,0 +1,192 @@
...
+        }
+        return path;
+    }
+
+    private String accountKeyPath(String accountNum) {
+        return newKeyFilePath(String.format("account%s.pem", accountNum));
+    }
+
+    private String newKeyFilePath(String fileName) {
+        return Path.of(DEFAULT_WORKING_DIR.get(), TEST_NETWORK, String.format("keys/%s", fileName))
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]:
```suggestion
        return Path.of(DEFAULT_WORKING_DIR.get(), TEST_NETWORK, "keys", fileName))
```

**Review by mhess-swl — CHANGES_REQUESTED** [review]
It's preferable to expose `SpecStateObserver` in yahcli's prod code over exposing two levels of registry callbacks. Open to discussion though

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/schedules/SignCommand.java (hunk 1 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/schedules/SignCommand.java]: I see. The param is deleted.
Now I’m using `-p` to set a new payer, instead of adding another signature.
Also, I had to clear the `default.payer.pemKeyResource` in the spec setup [here](https://github.com/hiero-ledger/hiero-consensus-node/pull/20924/commits/0182f03ac9dfceaee16cbc1472fd24ee6fa798b4#diff-8b6e023b201788cce2e854774bab20f3b85bca08d355ad368e2078446eae5e09R277-R278) in order to work, else it was trying to decipher the genesis pem with the new payer's passphrase.

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/ScheduleSuite.java (hunk 2 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/suites/ScheduleSuite.java]: Removed.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java (hunk 5 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java]: I didn't realize that the `specStateObserver` is the same thing :sweat_smile:
I've replaced all `registryCb` usages with the `specStateOvserver`

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java (hunk 7 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java]: Removed.

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java (hunk 9 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: I gave it a try. But unfortunately it doesn't work. 
Here we are observing the spec state of the current test.
So we still need to pass the observer to `yahcli -> command -> suite -> spec`.
Maybe instead of this observer, we should consider modifying the command output and include the resulting schedule ID. 
For the scheduled send command, it is way off anyway. It is printing the result of a successful send command :worried:.

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java (hunk 10 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]: Same as above.

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java (hunk 11 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]: I did remove this param, and I'm using the `-p` to change the payer. But maybe it's worth considering the addition of a pram for additional signers (without providing the key file path :sweat_smile:, just the account).

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java (hunk 12 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]: Fixed

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java (hunk 11 above)
Comment (mhess-swl) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java]: Sure, definitely could be. We can file a ticket to do this work if you'd like that we keep track of it

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java (hunk 9 above)
Comment (mhess-swl) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: Understood, thanks for giving it a try! I've asked devops if it's ok to tweak the command output

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java [hunk 13]
```diff
@@ -88,7 +88,8 @@ public Integer call() throws Exception {
                 effectiveMemo,
                 denomination,
                 accountsCommand.getYahcli().isScheduled(),
-                insideBatch);
+                insideBatch,
+                accountsCommand.getYahcli().getStateObserver());
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java]: Are these observers still necessary?

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java [hunk 14]
```diff
@@ -71,6 +108,9 @@ public Optional<Throwable> execFor(@NonNull final HapiSpec spec) {
                 outputCb.accept(output);
                 Files.deleteIfExists(outputPath);
             }
+            //            if (observer != null) {
+            //                observer.observe(new SpecState(spec.registry(), spec.keys()));
+            //            }
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: Intentional?

Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: Removed

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java (hunk 13 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java]: No, now we use the command output to obtain the schedule ID.

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java [hunk 15]
```diff
@@ -169,4 +166,33 @@ public static long validatedUnits(final String amountRepr, Integer decimals) {
...
+        if (isSchedule) {
+            message.append("Scheduled ");
+        }
+        return message.toString();
+    }
+
+    private String maybeScheduleFail(boolean isSchedule) {
+        final var message = new StringBuilder();
+        if (isSchedule) {
+            message.append("to schedule sent ");
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java]: If the spec failed, when will `isSchedule` be `true` here? This method's existence suggests that the schedule can be created successfully, but the spec itself wasn't successful. Is that a real use case?

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/UpdateCommand.java [hunk 16]
```diff
@@ -111,4 +110,15 @@ private List<Key> unHexListOfKeys(final List<String> hexedKeys) {
         }
         return unHexedKeys;
     }
+
+    private String maybeScheduleId(boolean isSchedule, UpdateSuite delegate) {
+        final var message = new StringBuilder();
+        if (isSchedule) {
+            final var scheduleId = delegate.getScheduleId().get();
+            message.append(" with schedule ID ");
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/UpdateCommand.java:118]: Nit
```suggestion
            message.append(" and schedule ID ");
```

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java [hunk 17]
```diff
@@ -0,0 +1,179 @@
...
+                                    .addKeys(keyT.get())
+                                    .build())
+                            .build();
+                    // validate actual key
+                    assertEquals(actualKeyS.get(), expectedKey, "Wrong key!");
+                }));
+    }
+
+    // Helpers
+    private String combinePublicKeys(String... publicKeys) {
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java:156]: Why combine separate public keys into a single file? Not familiar with this

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java (hunk 15 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java]: `isSedule` can be true here. It is just a CLI argument set by the user.
I guess the naming convention here is bad. 
This method should produce a part of the fail message, for either schedule or not.
Respectively:  `"FAILED - could not schedule send "` or `"FAILED - could not send"`

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java (hunk 17 above)
Comment (JivkoKelchev) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java:156]: I'm was not familiar, either. I just [follow the example from the README.](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/yahcli/README.md?plain=1#L671)
Basically, you can add several public keys in one file and use it to update the account key as a **list of keys**.

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/ScheduleCommandsTest.java [hunk 18]
```diff
@@ -0,0 +1,179 @@
...
+                                .payingWith(String.valueOf(accountNumS.get())))),
+                // Query all account keys
+                doingContextual(spec -> allRunFor(
+                        spec,
+                        getAccountInfo(String.valueOf(accountNumR.get())).exposingKeyTo(keyR::set),
+                        getAccountInfo(String.valueOf(accountNumT.get())).exposingKeyTo(keyT::set),
+                        getAccountInfo(String.valueOf(accountNumS.get())).exposingKeyTo(actualKeyS::set))),
+                // Validate account S new key
+                doingContextual(spec -> {
+                    // compose expected key form R and T account keys
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/ScheduleCommandsTest.java:143]: Nit (can do in a future PR):

```suggestion
                    // compose expected key from R and T account keys
```

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java (hunk 17 above)
Comment (mhess-swl) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/readme/ScheduleCommandsTest.java:156]: Interesting, thanks!
