### PR TITLE
fix: fixed diff test issue 11822

### LINKED ISSUE #11822: (2/19 - 18:15:00) Expected 'AMOUNT_EXCEEDS_ALLOWANCE', got 'TOKEN_NOT_ASSOCIATED_TO_ACCOUNT' from round 162953201
### Description

Transaction in HashScan [here](https://hashscan.io/mainnet/transaction/1708366580.214697003). 
Consensus at 1:16:20.2146 PMFeb 19, 2024, EST

A crypto transfer transaction body:
```
transactionID {
  transactionValidStart {
    seconds: 1708366568
    nanos: 592995870
  }
  accountID {
    accountNum: 1061772
  }
}
nodeAccountID {
  accountNum: 12
}
transactionFee: 100000000
transactionValidDuration {
  seconds: 120
}
memo: "Altlantis - Live Mint"
cryptoTransfer {
  transfers {
  }
  tokenTransfers {
    token {
      tokenNum: 3915869
    }
    transfers {
      accountID {
        accountNum: 1408379
      }
      amount: -4440000000
      is_approval: true
    }
    transfers {
      accountID {
        accountNum: 1729620
      }
      amount: 4440000000
      is_approval: true
    }
  }
  tokenTransfers {
    token {
      tokenNum: 4604924
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 19
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 27
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 32
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 42
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 58
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 149
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 150
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 175
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 179
      is_approval: true
    }
    nftTransfers {
      senderAccountID {
        accountNum: 1729620
      }
      receiverAccountID {
        accountNum: 1408379
      }
      serialNumber: 196
      is_approval: true
    }
  }
}
```

Got
`Mismatched values, expected 'AMOUNT_EXCEEDS_ALLOWANCE', got 'TOKEN_NOT_ASSOCIATED_TO_ACCOUNT' - Matching field 'status' Matching field 'receipt'  ==> expected: <AMOUNT_EXCEEDS_ALLOWANCE> but was: <TOKEN_NOT_ASSOCIATED_TO_ACCOUNT>
`

### Steps to reproduce

Re-run 30 mins events from round 162953201.

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

added checkTokenAllowances() in AssociateTokenRecipientsStep

**Related issue(s)**:

Fixes #11822

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java [hunk 1]
```diff
@@ -105,7 +111,7 @@ public void doIn(@NonNull final TransferContext transferContext) {
                 }
 
                 final TokenAssociation newAssociation = validateAndBuildAutoAssociation(
-                        receiverId, tokenId, token, accountStore, tokenRelStore, handleContext);
+                        receiverId, tokenId, token, accountStore, tokenRelStore, handleContext, 0);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:114]: Why is it 0 here ? We can do same check everytime right ?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java [hunk 2]
```diff
@@ -127,18 +133,24 @@ public void doIn(@NonNull final TransferContext transferContext) {
...
             @NonNull final WritableAccountStore accountStore,
             @NonNull final WritableTokenRelationStore tokenRelStore,
-            @NonNull final HandleContext handleContext) {
+            @NonNull final HandleContext handleContext,
+            long amount) {
         final var account = getIfUsable(accountId, accountStore, handleContext.expiryValidator(), INVALID_ACCOUNT_ID);
         final var tokenRel = tokenRelStore.get(accountId, tokenId);
         final var config = handleContext.configuration();
 
+        if (amount != 0) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:150]: Why do we need this check `amount != 0`

Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java]: Changed it to token.tokenType() == FUNGIBLE_COMMON check.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:115]: NftTransfer has no amount. Added amount comment in validateAndBuildAutoAssociation().

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Thanks @iwsimon

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java [hunk 3]
```diff
@@ -127,18 +134,24 @@ public void doIn(@NonNull final TransferContext transferContext) {
...
             @NonNull final WritableTokenRelationStore tokenRelStore,
-            @NonNull final HandleContext handleContext) {
+            @NonNull final HandleContext handleContext,
+            long amount) {
         final var account = getIfUsable(accountId, accountStore, handleContext.expiryValidator(), INVALID_ACCOUNT_ID);
         final var tokenRel = tokenRelStore.get(accountId, tokenId);
         final var config = handleContext.configuration();
 
+        if (token.tokenType() == FUNGIBLE_COMMON) {
+            checkTokenAllowances(account, topLevelPayer, tokenId, amount);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:152]: It only makes sense to do this check when:
   1. `amount < 0`; and,
   2. The `AccountAmount` with this `accountId`/`amount` pair has `is_approval=true`.

**Review by tinker-michaelj — APPROVED** [review]
I would rather extract these approval/allowance checks on the top-level transaction into a dedicated `validateTopLevelAllowances()` method that runs before any of the `Step` implementations.

But we can merge this now and refine later.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java [hunk 4]
```diff
@@ -153,4 +166,16 @@ private TokenAssociation validateAndBuildAutoAssociation(
...
     }
+
+    private void checkTokenAllowances(Account account, AccountID topLevelPayer, TokenID tokenId, long amount) {
+        final var tokenAllowances = account.tokenAllowancesOrElse(Collections.emptyList());
+        for (int i = 0; i < tokenAllowances.size(); i++) {
+            final var allowance = tokenAllowances.get(i);
+
+            if (topLevelPayer.equals(allowance.spenderId()) && tokenId.equals(allowance.tokenId())) {
+                final var newAllowanceAmount = allowance.amount() + amount;
+                validateTrue(newAllowanceAmount >= 0, AMOUNT_EXCEEDS_ALLOWANCE);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:177]: Note that it would be just as bad for the allowance to be missing completely, as for there to be an insufficient allowance.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java (hunk 3 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java]: Changed code to validateTopLevelAllowances() and added these checks.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java (hunk 4 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java]: Added SPENDER_DOES_NOT_HAVE_ALLOWANCE check.

**Comment by iwsimon** [comment]
> I would rather extract these approval/allowance checks on the top-level transaction into a dedicated `validateTopLevelAllowances()` method that runs before any of the `Step` implementations.
> 
> But we can merge this now and refine later. ✅

Replaced code into 

> I would rather extract these approval/allowance checks on the top-level transaction into a dedicated `validateTopLevelAllowances()` method that runs before any of the `Step` implementations.
> 
> But we can merge this now and refine later. ✅

Created validateTopLevelAllowances() in CryptoTransferHandler instead.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @iwsimon !

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !
