### PR TITLE
Fixes sufficient to see one BDD test pass.

### LINKED ISSUE #7578: UtilPrngService BDD tests fail
### Description

The tests for UtilPrngService are failing.

### Steps to reproduce

Run `./gradlew modrun` and then execute the `UtilPrngSuite` .

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### PR DESCRIPTION
**Pull request by rbair23**
Closes #7578 

- Set initial value for EntityNumber to 999, so the first generated entity is 1000.
- Fix logging level when blocks are created from "info" to "debug" to avoid spamming the logs.
- Fix genesis migration for BlockRecordService to avoid passing "null" for any of the hashes
- Add @Singleton to DeduplicationCacheImpl so only one instance is created and not 3!
- Inject HederaRecordCache into HandleWorkflow, to record records and receipts (work in progress)
- Improve diagnostics in exception for ReadableStoreFactory#getStore
- Add UtilService into WritableStoreFactory, even though there are no writable stores to return. When HandleContextImpl is created, it attempts to create a WritableStoreFactory. Rather than removing the exception, I felt it better to require us to intentionally register each service.
- Fix SingleTransactionRecordBuilder, so it doesn't throw PBJ exceptions on null Bytes or Lists.
- Switch from `getStore(RecordCache.class)` to `recordCache()` on HandleContextImpl. It was difficult to find a good way to add RecordCache to the WritableStoreFactory, because stores are ephemeral, but RecordCache is a @Singleton. So I just went back to the idea of having a recordCache method on the context (as is the case still on QueryContext).
- Fix HandleWorkflow, by moving the check for pre-handle failures to occur AFTER we update the record builder, otherwise clients will never get a result of their transaction.
- Fix HandleWorkflow, by setting the record builder status to SUCCESS if no exceptions are thrown.
- Comment out incorrect code in FileServiceUtils. This needs to be fixed properly in a follow-on PR.
- ReadableAccountStoreImpl and WritableAccountStore were loading two copies of the accounts and alias caches. I changed them to load only one copy of each. I also fixed it, so it uses Bytes for alias in WritableAccountStore instead of String. It never would have worked (ReadableAccountStoreImpl uses Bytes instead of Strings. One of them had to change).
- Fix stack commit, so it actually commits to the merkle tree. This change involved adding a new interface (HederaWritableStates) with "isModified" and "commit" methods, and carrying that change through MerkleHederaState, WrappedHederaState, WrappedWritableStates, EmptyWritableStates, and WritableQueueStateBase.
- Fix ApiPermissionConfig, which should not have been annotated with @NetworkConfig.

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/ids/EntityIdService.java [hunk 1]
```diff
@@ -67,7 +67,7 @@ public Set<StateDefinition> statesToCreate() {
             @Override
             public void migrate(@NonNull MigrationContext ctx) {
                 final var entityIdState = ctx.newStates().getSingleton(ENTITY_ID_STATE_KEY);
-                entityIdState.put(new EntityNumber(0));
+                entityIdState.put(new EntityNumber(999));
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/ids/EntityIdService.java:70]: See #7627 that discusses this magic number.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaWritableStates.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+package com.hedera.node.app.state;
+
+import com.hedera.node.app.spi.state.WritableStates;
+
+/**
+ * A {@link WritableStates} that can be committed.
+ */
+public interface HederaWritableStates extends WritableStates {
+    boolean isModified();
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaWritableStates.java:25]: You added `isModified` to `WritableQueueStateBase` above, and it already has `commit` - is there a relationship to this interface?

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM !

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/WrappedHederaState.java [hunk 3]
```diff
@@ -71,16 +71,16 @@ public ReadableStates createReadableStates(@NonNull String serviceName) {
      */
     @Override
     @NonNull
-    public WritableStates createWritableStates(@NonNull String serviceName) {
+    public HederaWritableStates createWritableStates(@NonNull String serviceName) {
         return writableStatesMap.computeIfAbsent(
-                serviceName, s -> new WrappedWritableStates(delegate.createWritableStates(s)));
+                serviceName, s -> (HederaWritableStates) delegate.createWritableStates(s));
```
Comment (netopyr) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/WrappedHederaState.java:76]: This looks wrong. Do we really need both interfaces, `HederaWritableStates` and `WritableStates`? What do you think about merging them?

**Review by netopyr — APPROVED** [review]
LGTM

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaWritableStates.java (hunk 2 above)
Comment (rbair23) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaWritableStates.java]: I agree, this was all kind of hacky. @tinker-michaelj found a better way to do this that allowed me to unroll this change.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/WrappedHederaState.java (hunk 3 above)
Comment (rbair23) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/WrappedHederaState.java]: I have reverted this and have a better solution suggested by @tinker-michaelj. This change I have here would actually be bad, in that a commit on some arbitrary point in the save stack would go straight to the merkle tree! Fortunately, the unit tests failed loudly, so it was caught.

**Review by tinker-michaelj — DISMISSED** [review]

**Review by jasperpotts — APPROVED** [review]
Looks Good

**Review by tinker-michaelj — DISMISSED** [review]

**Review by jasperpotts — APPROVED** [review]

File: hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java [hunk 4]
```diff
@@ -180,7 +186,8 @@ void setup(@Mock InstantSource instantSource) {
                 checker,
                 serviceLookup,
                 configProvider,
-                instantSource);
+                instantSource,
+                recordCache);
     }
 
     @SuppressWarnings("ConstantConditions")
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java:193]: Consider this alternative - better or worse (or no different)?

```
    @Test
    void testContructorFailsWithAnyNullArgument() {
        final var softly = new SoftAssertions();

        final var instantSource = InstantSource.system();
        final var args = List.of(
                networkInfo,
                preHandleWorkflow,
                dispatcher,
                blockRecordManager,
                signatureExpander,
                signatureVerifier,
                checker,
                serviceLookup,
                configProvider,
                instantSource,
                recordCache);
        for (int i = 0; i < args.size(); i++) {
            final var thisTestArgs = new ArrayList<>(args);
            thisTestArgs.set(i, null);
            softly.assertThatNullPointerException().as("throws if argument %d is null".formatted(i))
                    .isThrownBy(() -> new HandleWorkflow(
                            (NetworkInfo) thisTestArgs.get(0),
                            (PreHandleWorkflow) thisTestArgs.get(1),
                            (TransactionDispatcher) thisTestArgs.get(2),
                            (BlockRecordManager) thisTestArgs.get(3),
                            (SignatureExpander) thisTestArgs.get(4),
                            (SignatureVerifier) thisTestArgs.get(5),
                            (TransactionChecker) thisTestArgs.get(6),
                            (ServiceScopeLookup) thisTestArgs.get(7),
                            (ConfigProvider) thisTestArgs.get(8),
                            (InstantSource) thisTestArgs.get(9),
                            (HederaRecordCache) thisTestArgs.get(10)
                    ));
        }
        softly.assertAll();
    }
```

Comment (rbair23) [reply hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java:193]: Not sure. Maybe we should have a generic utility method that uses reflection to invoke the constructor with null in all the places where null is not allowed, and reuse it everywhere. Then it would be a single line of code from each test that needs it.

Comment (david-bakin-sl) [reply hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java:193]: I tried reflection but felt it was too obscure/hard to read when it all got put together.  But if this kind of thing happened in more than one place and the procedure was stuck in a utility method for all, that'd be different.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 5]
```diff
@@ -161,6 +167,16 @@ private void handlePlatformTransaction(
                     .transactionID(txBody.transactionID())
                     .memo(txBody.memo());
 
+            // If pre-handle was successful, we return the result. Otherwise, we charge the node or throw an exception.
+            switch (preHandleResult.status()) {
```
Comment (netopyr) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:171]: On second thought, this change is wrong. 

If we have a due diligence error or an unknown failure, `preHandleResult.txInfo()` is `null`. I don't know what the correct behavior is. What do we write into the record stream if we cannot parse the transaction?

If I remember correctly, we did not want to write anything in the record stream in the case of an unknown failure but just update the receipt.

We can keep this change for now but must revisit it once the diagram of the handle workflow with error conditions is ready.

**Review by netopyr — APPROVED** [review]
LGTM - We need to revisit error handling in the handle workflow though.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 5 above)
Comment (rbair23) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:171]: I agree, this entire method needs to be reworked. We have the pieces, but not in the right order.
