### PR TITLE
fix(19206): SequentialTaskSchedulerTests flake fixes

### LINKED ISSUE #19206: Test flake in `SequentialTaskSchedulerTests.squelching()`
The test `SequentialTaskSchedulerTests.squelching()` seems to have failed randomly: https://scans.gradle.com/s/jffolclbm2eja/tests/task/:swirlds-component-framework:test/details/com.swirlds.component.framework.schedulers.SequentialTaskSchedulerTests/squelching(String)%5B1%5D?expanded-stacktrace=WyIwIl0&top-execution=1

Needs to be investigated and the flake resolved.

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
Addresses flakiness on SequentialTaskSchedulerTests by limiting the dependency on `assertEventuallyTrue` or `assertEventuallyEquals`

Introduces a wrapper object on top of `Consumer` and `Function` that allows tracking the number of times a particular handler (that will be executed in the wiring framework) is invoked, allowing to wait until a certain number of invocations have happened, and optionally blocking the handler's execution until the user releases the block. 

**Related issue(s)**:

Fixes 
#19206
#18513
#17659
And possibly others

### CODE REVIEW

**Comment by lpetrovic05** [comment]
these test fixtures seem quite complicated at first glance

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ExecutionControl.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    public void mark() {
+        semaphore.release();
+    }
+
+    /**
+     * Awaits for the number of executions to be collected
+     * @param numberOfExecutions expected number of executions
+     */
+    public void await(int numberOfExecutions) {
+        runWrappingChecked(() -> semaphore.acquire(numberOfExecutions));
```
[the remark this answers is not in the document]
Comment (mxtartaglia-sl) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ExecutionControl.java:34]: I can add the `await(value, someDuration)` method. It will add to the complexity of the fixtures.
I certainly encountered the scenario you mentioned, but it seems to me that it is an easy catch; any local test run would be stuck forever too, making it easy to identify.

**Comment by mxtartaglia-sl** [comment]
@lpetrovic05 do you want to chat about it? What do you think about the test itself? Is it slightly more readable?

**Comment by abies** [comment]
I'm wondering if it couldn't be done considerably easier with mocks and
`verify(myMock, timeout(5000).times(99)).myMethod(...)`
After all, checking if something was invoked n times is exactly the purpose of the mock framework - in this case maybe it would be enough to add a async timeout with wait (as above) to the verification?

**Comment by mxtartaglia-sl** [comment]
@abies, the necessity is not only to verify if the method was invoked a number of times. It is also to have a mechanism to sync and delay some checks until the minimum number of invocations has already happened before the check is done.
Global waits are one source of the flakiness here. Sometimes, the operation is just too slow, and the check happens too quickly to match the result.

It's an evolution of the approach the test already used with `CountdownLatches` in some scenarios

**Comment by mxtartaglia-sl** [comment]
`Evolution` implies the change to be positive, its an overstreach on my side.

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ExecutionControl.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (lpetrovic05) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ExecutionControl.java]: yeah, we should not allow a test failure to block forever

**Comment by lpetrovic05** [comment]
> @lpetrovic05 do you want to chat about it? What do you think about the test itself? Is it slightly more readable?

Lets chat about it today

**Comment by abies** [comment]
Hmmm, `verify(myMock, timeout(5000).times(99))` delays till the proper amount of invocations are done. Can be used both to delay following code till things have happened or to wait for async calls to happen in background.
What is the specific use case we need which is not covered by that?

**Comment by mxtartaglia-sl** [comment]
@abies, I did not know you could do that with spies. Thanks for the clarification.
We would still need to be able to block the execution of a handler until the test code decides to release it, so that we would be getting rid of half of the fixture's code, but not all of it.

I see the point of not introducing new fixtures if we have a framework that fulfills the project. But mocks are special, and I think we should move away from them when possible, instead of adding them to the tests that do not have them.

I fear that introducing the usage in the test here allows for lazily developed tests in the future.

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ConsumerWithCompletionControl.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    /**
+     * {@inheritDoc}
+     */
+    @Override
+    public void accept(final H h) {
+        executionControl.gate.nock();
+        try {
+            handler.accept(h);
+        } finally {
+            executionControl.mark();
```
Comment (anthony-swirldslabs) [inline platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ConsumerWithCompletionControl.java]: Minor: regardless of the fact that these are "just test fixtures", `executionControl.gate` looks like a breach of encapsulation. Cannot `nock()` and `mark()` both be methods of the `ExecutionControl`? This would encapsulate the gate properly, and also would look more symmetric here where the methods are used. Same comment for a similar usage a bit below in this PR.

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ConsumerWithCompletionControl.java (hunk 2 above)
Comment (mxtartaglia-sl) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ConsumerWithCompletionControl.java]: You are right, thanks for the suggestion, makes sense.

**Review by anthony-swirldslabs — DISMISSED** [review]
Looks great. Thanks!

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ConsumerWithCompletionControl.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+
+    /**
+     * Creates a Consumer that automatically marks its completion and allows to wait for that completion to be marked.
+     * The consumer will not be blocked. Calling unblock will not produce results.
+     *
+     * @param handler the handler to wrap
+     * @param <H>     the type of the handler
+     * @return the new {@link ConsumerWithCompletionControl}
+     */
+    public static <H> ConsumerWithCompletionControl<H> unBlocked(@NonNull final Consumer<H> handler) {
```
Comment (anthony-swirldslabs) [inline platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ConsumerWithCompletionControl.java]: Minor: "unblocked" is an actual word. The `B` shouldn't be capitalized.

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+    Gate(int count) {
+        latch = new CountDownLatch(count);
+    }
+
+    /**
+     * Causes the calling thread to block if the gate is closed.
+     * The first call to open will cause all blocked threads to continue.
+     */
+    public void knock() {
+        ThrowingRunnableWrapper.runWrappingChecked(latch::await);
```
Comment (lpetrovic05) [inline platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java]: this seems to wait forever, it needs a timeout

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+     * Releases the previous waiting threads.
+     * The gate is now a closed gate.
+     */
+    public void close() {
+        latch.countDown();
+
+        if (latch.getCount() > 0) {
+            return;
+        }
+        latch = new CountDownLatch(1);
```
Comment (lpetrovic05) [inline platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java:62]: If we need a new variable here, seems like a semaphore is better

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ExecutionControl.java [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+    /**
+     * Awaits for the number of executions to be collected
+     * @param numberOfExecutions expected number of executions
+     * @param duration the max time to wait for the mark to complete
+     */
+    public void await(int numberOfExecutions, final Duration duration) {
+        runWrappingChecked(() -> {
+            if (!semaphore.tryAcquire(numberOfExecutions, duration.toMillis(), TimeUnit.MILLISECONDS)) {
+                throw new RuntimeException("Timed out waiting for an execution to finish");
+            }
```
Comment (lpetrovic05) [inline platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ExecutionControl.java]: If we are waiting for a number of executions to occur within a certain amount of time, the log message should say how many executions did occur during this time

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ThrowingRunnableWrapper.java [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+import edu.umd.cs.findbugs.annotations.NonNull;
+import java.util.function.Consumer;
+import org.hiero.base.concurrent.ThrowingRunnable;
+
+/**
+ * A Wrapper that allows to convert a {@link ThrowingRunnable} into a {@link Runnable} by allowing to consume a {@link Throwable} T
+ * @param runnable the throwing runnable to wrap
+ * @param throwableConsumer how to process the exception
+ */
+public record ThrowingRunnableWrapper(
```
Comment (lpetrovic05) [inline platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ThrowingRunnableWrapper.java]: I feel like this is not beneficial. It seems to be used in only 3 places, and its harder to understand than a `try/catch` since its not immediately obvious what it does

Comment (mxtartaglia-sl) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ThrowingRunnableWrapper.java]: The issue is that any method that throws a checked exception cannot be used as a lambda because if forces to deal with the exception being thrown.
Then this boilerplate code becomes the most frequent idiom in the code:
```
  something( ()->{
         try{
              doSomeOp();
          } catch(Exception e){
             throw new RuntimeException(e):
          }
        });
```
vs:
```
 something(new ThrowingRunnableWrapper( X::doSomeOp));
```

Comment (mxtartaglia-sl) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/ThrowingRunnableWrapper.java]: But it's true that I refactored out all the direct usages of sleep, await, and other functions that were the initial causes of this inclusion, so it becomes less of a problem now.

File: platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java (hunk 5 above)
Comment (mxtartaglia-sl) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java:62]: Let's discuss, tried that path, but the code is far more complicated.

Comment (lpetrovic05) [reply platform-sdk/base-concurrent/src/testFixtures/java/org/hiero/base/concurrent/test/fixtures/Gate.java:62]: if you tried it, then no need to discuss further

**Review by andrewb1269hg — APPROVED** [review]
Review and approve `platform-sdk/swirlds-component-framework/build.gradle.kts`
