### PR TITLE
fix: update prng system contract gas requirements

### LINKED ISSUE #12302: Fix PrngSystemContract gas calculation
### Description

The gas calculation in the PrngSystemContract is not correct.

### Steps to reproduce

Observe how much gas is charged by a call to the system contract

### Additional context

_No response_

### Hedera network

other

### Version

v0.48.0

### Operating system

None

### PR DESCRIPTION
**Pull request by lukelee-sl**
**Description**:
Fix to update the gas requirement for PRNG system contract.

**Related issue(s)**:

Fixes #12302 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/PrngSystemContractTest.java [hunk 1]
```diff
@@ -101,17 +116,16 @@ void onlyFullResultsAreSupported() {
...
         given(proxyWorldUpdater.entropy()).willReturn(EXPECTED_RANDOM_NUMBER);
 
         // when:
-        var actual = subject.computeFully(PSEUDO_RANDOM_SYSTEM_CONTRACT_ADDRESS, messageFrame)
-                .result();
+        var actual = subject.computeFully(PSEUDO_RANDOM_SYSTEM_CONTRACT_ADDRESS, messageFrame);
 
         // then:
-        assertEqualContractResult(PRECOMPILE_CONTRACT_SUCCESS_RESULT, actual);
+        assertEqualContractResult(PRECOMPILE_CONTRACT_SUCCESS_RESULT, actual, 100L);
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/PrngSystemContractTest.java:128]: You gave `GAS_REQUIRED` a name, why not this `100L`?  And speaking of `GAS_REQUIRED` - from **my personal POV** it wasn't really a good name as I wasn't sure whether this was gas required by any pnrg call, or this pnrg call, or what.  Suggestion would be to make this a bit more explicit to help lame readers like me?

**Review by david-bakin-sl — APPROVED** [review]
LGTM with just minor minor suggestions about naming.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @lukelee-sl !
