### PR TITLE
fix: reuse `preHandleTransaction()` in `HandleWorkflow`

### LINKED ISSUE #10447: (mod-service) Consensus `PreHandleResult` not reconstructed deterministically
### Description

A transaction using a deleted payer account made its way through pre-handle and handle in two pathways:
 1. In pre-handle the deleted payer account was detected, a result with `Status.NODE_DUE_DILIGENCE_FAILURE` was returned, and a NPE thrown in `HandleWorkflow` [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java#L355); resulting in `FAIL_INVALID`.
 2. In pre-handle the deleted payer account was **not** detected, a result with `Status.SO_FAR_SO_GOOD` was returned, `PAYER_ACCOUNT_DELETED` was detected in the `validate()` call [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java#L389); resulting in an orderly failure with the expected `PAYER_ACCOUNT_DELETED`.

### Steps to reproduce

Repeatedly run `CryptoDeleteSuite` in CI.

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #10447 
 - Updates `HandleWorkflow` to simply re-call `PreHandleWorkflow.preHandleTransaction()` at consensus to ensure no deviations in `PreHandleResult` construction when compared to pre-handle.
 - Adds a `@Nullable PreHandleResult previousResult` to `preHandleTransaction()` so that in the (overwhelming majority) of cases in which all keys linked to a transaction are unchanged at consensus, the second call can reuse the first call's verification results.
 - Avoids NPE's for due diligence failures by returning empty collections instead of `null` from `PreHandleResult` getters.
 - Fixes `preHandleTransaction()` to return due diligence failures for deleted or missing payer accounts.

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 1]
```diff
@@ -731,152 +722,21 @@ private void rollback(
     private PreHandleResult getCurrentPreHandleResult(
             @NonNull final ReadableStoreFactory storeFactory,
             @NonNull final NodeInfo creator,
-            @NonNull final ConsensusTransaction platformTxn,
-            @NonNull final VersionedConfiguration configuration)
-            throws PreCheckException {
+            @NonNull final ConsensusTransaction platformTxn) {
         final var metadata = platformTxn.getMetadata();
+        final PreHandleResult previousResult;
+        if (metadata instanceof PreHandleResult result) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:728]: We could probably add a comment here when will this result be null and when it is not 😇 .

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java [hunk 2]
```diff
@@ -41,20 +42,41 @@ void preHandle(
...
     /**
-     * Starts the pre-handle transaction workflow for a single event.
+     * A convenience method to start the pre-handle transaction workflow for a single
+     * user transaction without a reusable result.
+     *
+     * @param creator The {@link AccountID} of the node that created these transactions
+     * @param storeFactory The {@link ReadableStoreFactory} based on the current state
+     * @param accountStore The {@link ReadableAccountStore} based on the current state
+     * @param platformTx The {@link Transaction} to pre-handle
+     * @return
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java:52]: nit: 
```suggestion
     * @return preHandle result for the transaction
```

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java [hunk 3]
```diff
@@ -276,4 +314,58 @@ private PreHandleResult expandAndVerifySignatures(
...
+        // hollow accounts because we already grabbed them when expanding the "full prefix" keys above)
+        if (onlyPayerKey == VerifyOnlyPayerKey.NO) {
+            signatureExpander.expand(context.requiredNonPayerKeys(), originals, expanded);
+            signatureExpander.expand(context.optionalNonPayerKeys(), originals, expanded);
+        }
+        return signatureVerifier.verify(txInfo.signedBytes(), expanded);
+    }
+
+    private boolean wasComputedWithCurrentNodeConfiguration(@Nullable PreHandleResult previousResult) {
+        // (FUTURE) IMPORTANT: Given a completely dynamic address book, we will also need to check
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java:365]: Ah yes !! Agreed

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM other than just nits. Thanks @tinker-michaelj !

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java [hunk 4]
```diff
@@ -69,15 +70,41 @@ public record PreHandleResult(
...
+        return getPayerKey().equals(context.payerKey())
+                && getRequiredKeys().equals(context.requiredNonPayerKeys())
+                && getOptionalKeys().equals(context.optionalNonPayerKeys())
+                && getHollowAccounts().equals(context.requiredHollowAccounts());
+    }
+
+    /**
+     * Returns the key verifications for this result; or an empty map if none could be computed.
+     *
+     * @return the key verifications for this result; or an empty map if none could be computed.
```
Comment (iwsimon) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java:93]: Duplicated comment lines.

**Review by iwsimon — DISMISSED** [review]
LGTM, one small comment.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java:93]: True, I think it's ok to omit the `@return` javadoc here; but repeating it is also acceptable I believe. 🤔

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:728]: Ah true, true. 😇

**Review by jsync-swirlds — APPROVED** [review]
Good work on this.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:720]: Added `logger.error()` in `else` block since metadata should _always_ be a `PreHandleResult`.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java]: Fixed.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java:366]: Created https://github.com/hashgraph/hedera-services/issues/10514 and linked in comment here.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @tinker-michaelj

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by jsync-swirlds — APPROVED** [review]
