### PR TITLE
fix: prevent premature validation in VisibleItemsAssertion

### LINKED ISSUE #24204: Test flake: NaturalDispatchOrderingTest > irreversiblePrecedingItemsAsExpected()
```
> Task :test-clients:testSubprocessConcurrent
  given HIP-993 natural dispatch ordering > irreversible preceding stream items are as expected ✘ as written (22.2s)

    org.opentest4j.AssertionFailedError: VisibleItemsAssertion{unseenIds=[], seenIds=[finalizationBySuccess, finalizationByFailure]} ended with result: array lengths differ, expected: <2> but was: <1>



    	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
    	at java.base/java.lang.Thread.run(Thread.java:1474)
    com.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected one of [ENTITY_NOT_ALLOWED_TO_DELETE], actual OK
    	at com.hedera.node.test.clients@0.73.0-SNAPSHOT/com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:339)
    	at com.hedera.node.test.clients@0.73.0-SNAPSHOT/com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:208)
    	at com.hedera.node.test.clients@0.73.0-SNAPSHOT/com.hedera.services.bdd.spec.utilops.grouping.ParallelSpecOps.lambda$submitOp$1(ParallelSpecOps.java:42)
    	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
    	at java.base/java.lang.Thread.run(Thread.java:1474)
    com.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected one of [ENTITY_NOT_ALLOWED_TO_DELETE], actual OK
    	at com.hedera.node.test.clients@0.73.0-SNAPSHOT/com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:339)
    	at com.hedera.node.test.clients@0.73.0-SNAPSHOT/com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:208)
```

https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/23001278682/job/66786833725?pr=24147

Find the root cause and fix the issue.

### PR DESCRIPTION
**Pull request by AlexKehayov**
**Description**:
NaturalDispatchOrderingTest.irreversiblePrecedingItemsAsExpected() flakes with:                                                        
`array lengths differ, expected: <2> but was: <1>`
The VisibleItemsAssertion used a maybeFinishLastSeen state machine that tracked when a transaction's items were "done" by detecting gaps in the stream (a non-matching item after matching ones). This removed IDs from unseenIds, and when unseenIds became empty, the validator fired immediately.
                                                                                                                                                        
Issue:
If a record-stream file boundary splits a preceding child (at consensus time T-1) from its parent transaction (at T), the ID gets removed from unseenIds before the second item arrives. When the other transaction's items then complete unseenIds, the validator runs with incomplete data and fails with the array length mismatch.

Fix:
- Removed the fragile state machine - deleted unseenIds, lastSeenId, and maybeFinishLastSeen() entirely.  Simplified ifPresentOrElse to ifPresent.
- Retry-until-pass validation - once every expected ID has at least one item, test() runs the validator in a  try/catch. If it fails (items still arriving), it returns false and retries when new items arrive. Only returns true when validation passes.
- Throttled re-validation - tracks the total item count at last failed attempt. Skips the validator entirely on subsequent calls unless new items have arrived, avoiding repeated exception/log overhead.
- Switched to explicit-pass semantics - changed all 5 tests from recordStreamMustIncludeNoFailuresFrom (pass-by-timeout) to recordStreamMustIncludePassFrom (requires the validator to explicitly succeed, timeout = failure). This ensures genuinely missing items are still caught rather than silently passing.   

Fixes #24204

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java [hunk 1]
```diff
@@ -119,18 +142,74 @@ public boolean test(@NonNull final RecordStreamItem item) throws AssertionError
...
+     * Attempts to match a stream item against the registered spec IDs.
+     *
+     * @return {@code true} if the item matched a registered ID (or can be discarded),
+     *         {@code false} if no ID is registered yet for this item and it should be retried later
+     */
+    private boolean tryMatch(@NonNull final RecordStreamItem item) {
+        // Count how many IDs are currently resolvable in the registry; if none
+        // of the expected IDs are registered yet there is nothing to match against.
+        final var matched = new ArrayList<>(allIds)
+                .stream()
```
Comment (petreze) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java]: I think this could be simplified to `allIds.stream()...`

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java [hunk 2]
```diff
@@ -119,18 +142,74 @@ public boolean test(@NonNull final RecordStreamItem item) throws AssertionError
...
+                        .entries()
+                        .add(entry);
+            } else {
+                items.computeIfAbsent(seenId, ignore -> newVisibleItems()).trackSkippedSynthItem();
+            }
+            return true;
         }
+        // If all IDs are resolvable (registered) and none matched, the item is
+        // genuinely unrelated — no need to buffer it for retry.
+        return allIds.stream().allMatch(id -> spec.registry().getMaybeTxnId(id).isPresent());
```
Comment (petreze) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java]: nit: When no ids match, the `allIds` is streamed twice. This could be combined if you think the performance can be impacted depending on the set size

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java [hunk 3]
```diff
@@ -119,18 +142,74 @@ public boolean test(@NonNull final RecordStreamItem item) throws AssertionError
...
+                lastValidationError = null;
+                return true;
+            } catch (final AssertionError e) {
+                itemCountAtLastValidation = currentItemCount;
+                lastValidationError = e;
+                if (withLogging) {
+                    log.info("Validation not yet passing (items may still be arriving): {}", e.getMessage());
+                }
+                return false;
+            }
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java:200]: I think this introduces a potential false-pass path in `VisibleItemsAssertion#test()`.

`validator.assertValid(...)` failures are now caught and converted to `return false`, but these assertions are still used via `recordStreamMustIncludeNoFailuresFrom(...)`, where timeout is treated as success. So a real validator mismatch can keep retrying until timeout and still pass.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java [hunk 4]
```diff
@@ -119,18 +142,74 @@ public boolean test(@NonNull final RecordStreamItem item) throws AssertionError
...
+        }
+        if (allIdsHaveItems) {
+            // Only re-run the validator when new items have arrived since the
+            // last failed attempt, to avoid repeated exception/log overhead on
+            // every stream item while waiting for late-arriving records.
+            final var currentItemCount =
+                    items.values().stream().mapToInt(v -> v.entries().size()).sum();
+            if (currentItemCount == itemCountAtLastValidation) {
+                return false;
+            }
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java]: Small concern on the re-validation throttle: `test()` only retries when total `entries().size()` changes, but `tryMatch()` can update state via `trackSkippedSynthItem()` without adding an entry.

Since `firstExpectedUserNonce()` depends on skipped-synth count, validation-relevant state can change while `currentItemCount` stays the same, and we may skip a needed re-run.

Would it be safer to key the throttle on a broader “state version” (e.g., entries + skipped-synth totals), or rerun validation after any successful match (including skipped synthetic items)?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java (hunk 3 above)
Comment (AlexKehayov) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/VisibleItemsAssertion.java:200]: Good catch. test() now tracks how many consecutive calls occur without any state change (no new entries or skipped synth items) after a failed validation. Once that count exceeds a settle threshold (50 items, roughly one record-stream file's worth of traffic), the last AssertionError is re-thrown instead of swallowed - so result.fail() fires and the test fails immediately with the actual validation error.
The 50-item grace period exists because a transaction's preceding child and parent can be split across record-stream files (1 nanosecond apart in consensus time but straddling a file boundary). The threshold gives the next poll cycle enough time to deliver the remaining items before we conclude the mismatch is genuine.

**Comment by AlexKehayov** [comment]
@petreze @ibankov Thank you for your reviews. The comments are addressed. I will have a few dry runs to verify the changes are safe.
