### PR TITLE
02338: Use default expiry range in file test

### LINKED ISSUE #2338: CI failed on UpdateFeesCompatibleWithCreates
This test needs 
https://github.com/hashgraph/hedera-services/blob/af597d3abba0ab0ca58503a041f4693235ba5df8/hedera-node/configuration/dev/application.properties#L2-L3

### PR DESCRIPTION
**Pull request by qnswirlds**
Close #2338

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]
Apart from adding comment in issue as discussed. Changes LGTM

File: test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java [hunk 1]
```diff
@@ -98,7 +98,8 @@ private HapiApiSpec apiPermissionsChangeDynamically() {
 	}
 
 	private HapiApiSpec updateFeesCompatibleWithCreates() {
-		long origLifetime = 100_000_000;
+		final long origLifetime = 7_200_000L;
+		final long extension = 700_000L;
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java:102]: Both `origLifetime` and `origLifetime + extension` will be in the default range of
https://github.com/hashgraph/hedera-services/blob/31d81b2df3e4f37762427d1671dd564160f5416b/hedera-node/src/main/resources/bootstrap.properties#L66-L67
