### PR TITLE
fix: make pureChecks required in all handlers

### LINKED ISSUE #12566: TokenAssociate without accountID throws unexpected NPE
Discovered during Java SDK integration testing:

TokenAssociateIntegrationTest > Cannot associate account with tokens when account ID
[Link to the test](https://github.com/hashgraph/hedera-sdk-java/blob/df866e90bb796a23678aa6ea85227bf4e52b905b/sdk/src/integrationTest/java/TokenAssociateIntegrationTest.java#L89)

SDK Logs:
is not set FAILED
  java.lang.AssertionError:
  Expecting throwable message:
    "Hedera transaction `0.0.1183@1712216328.038000000` failed pre-check with the status `FAIL_INVALID`"
  to contain:
    "INVALID_ACCOUNT_ID"
  but did not.
  
hedera-services Logs:
ERROR 106  IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field account is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.hedera.hapi.node.token.TokenAssociateTransactionBody.accountOrThrow(TokenAssociateTransactionBody.java:145) ~[hapi-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.service.token.impl.handlers.TokenAssociateToAccountHandler.calculateFees(TokenAssociateToAccountHandler.java:188) ~[app-service-token-impl-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchComputeFees(TransactionDispatcher.java:128) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:242) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:92) ~[?:?]
        at com.hedera.node.app.grpc.impl.TransactionMethod.handle(TransactionMethod.java:56) ~[?:?]
        at com.hedera.node.app.grpc.impl.MethodBase.invoke(MethodBase.java:131) ~[?:?]
        at com.hedera.node.app.grpc.impl.netty.GrpcServiceBuilder$ListenerImpl.onMessage(GrpcServiceBuilder.java:252) ~[?:?]
        at com.hedera.node.app.grpc.impl.netty.GrpcServiceBuilder$ListenerImpl.onMessage(GrpcServiceBuilder.java:220) ~[?:?]
        ...

### LINKED ISSUE #12644: Validate pureChecks in smart contracts service
The integration tests of the SDK found two cases where invalid transactions led to unexpected Exceptions. We should make sure that each handler has a `pureChecks()` method (even if it is empty initially) and review the pure checks for all handlers of the smart contracts service.

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
TransactionHandler had a default empty implementation of pureChecks, which meant that all inheriting classes could optionally implement pureChecks or accept the empty default. This PR removes the default empty implementation and adds overrides for all implementing classes which previously lacked one.

**Related issue(s)**:
Fixes #12644

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java [hunk 1]
```diff
@@ -98,6 +99,11 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
         }
     }
 
+    @Override
+    public void pureChecks(@NonNull final TransactionBody txn) throws PreCheckException {
+        // nothing to do
```
Comment (netopyr) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java:104]: Here we should check if the `contractID` is set.

Comment (kimbor) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java:104]: In preHandle (line 88) we call `op.contractIDOrElse(ContractID.DEFAULT)`. Is it correct to use a default contract ID if no contract ID is set?

**Review by netopyr — APPROVED** [review]
LGTM - thanks @kimbor

**Review by tinker-michaelj — APPROVED** [review]
LGTM, it seems quite sensible to have a hook where we can detect guaranteed failures at ingest.

But it's likely that we have some `calaculateFees()` implementations that should be more robust and work around missing fields with e.g. `contractIdOrElse(ContractID.DEFAULT)` patterns.

**Review by povolev15 — APPROVED** [review]
LGTM

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java [hunk 2]
```diff
@@ -70,6 +71,11 @@ public void handle(@NonNull final HandleContext context) throws HandleException
         throwIfUnsuccessful(outcome.status());
     }
 
+    @Override
+    public void pureChecks(@NonNull final TransactionBody txn) throws PreCheckException {
+        // nothing to do
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java:76]: Question - why are we doing nothing here and in the `EthereumTransactionHandler` below instead of checking the op is the correct type?  I understand that the contractID may not exist.

Comment (kimbor) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java:76]: The handlers are dispatched based on the op type. In order for code in this class to be called, op must already be of type ContractCreate

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java [hunk 3]
```diff
@@ -72,6 +76,12 @@ public void preHandle(@NonNull final PreHandleContext context) {
         // No non-payer signatures to verify
     }
 
+    @Override
+    public void pureChecks(@NonNull TransactionBody txn) throws PreCheckException {
+        final var op = txn.contractCallOrThrow();
+        mustExist(op.contractID(), INVALID_CONTRACT_ID);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java:82]: Not a blocker for this PR, but we should be consistent in the checks done in this method. We are validating `ContractID` exists in smart-contract service. But not doing any checks in Consensus service.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java (hunk 2 above)
Comment (lukelee-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java:76]: Makes sense but it seems we are checking the type in some of the handlers.

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by JeffreyDallas — APPROVED** [review]
