### PR TITLE
Complete `MiscViewsXTest`

### LINKED ISSUE #8283: Fix `MiscViewsXTest` for ERC view functions
### Problem

We have a failing `MiscViewsXTest` for the ERC view functions provided by redirects to the `0x167` system contract. 

### Solution

Make this test pass.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #8283

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java [hunk 1]
```diff
@@ -135,6 +144,20 @@ public HtsCallAttempt(@NonNull final Bytes input, @NonNull final HederaWorldUpda
             return MintCall.from(this, senderAddress);
         } else if (BalanceOfCall.matches(selector)) {
             return BalanceOfCall.from(this);
+        } else if (IsOperatorCall.matches(selector)) {
+            return IsOperatorCall.from(this);
+        } else if (TotalSupplyCall.matches(selector)) {
+            return TotalSupplyCall.from(this);
+        } else if (NameCall.matches(selector)) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java:151]: name, symbol, ownerof, tokenuri don't appear in above checklist - also there's both getbalance and balanceof in above checklist.  checklist is useful during this development phase! can you make it match?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java [hunk 2]
```diff
@@ -17,36 +17,31 @@
 package com.hedera.node.app.service.contract.impl.exec.systemcontracts.hts.balanceof;
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java:17]: Successful refactor to `AbstractTokenViewCall` - this file is simpler/easier to read now

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java [hunk 3]
```diff
@@ -67,36 +62,35 @@ public static boolean matches(@NonNull final byte[] selector) {
      * @return the constructed {@link BalanceOfCall}
      */
     public static BalanceOfCall from(@NonNull final HtsCallAttempt attempt) {
-        final var owner = fromHeadlongAddress(
-                BALANCE_OF.decodeCall(attempt.input().toArrayUnsafe()).get(0));
+        final Address owner =
+                BALANCE_OF.decodeCall(attempt.input().toArrayUnsafe()).get(0);
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java:66]: So this `decodeCall` can throw if the `input` byte array is too short or too long (or otherwise doesn't decode).  But I traced the callers back up to `CustomMessageCallProcessor.start` and there are no exception handlers, though there is stuff dealing with manipulating and finishing frames and such.  So ... is there a handler somewhere that fixes things up?

**Review by david-bakin-sl — COMMENTED** [review]
Only reviewed as far as `BalanceOfCall` right now.  Will continue later.

Only thing I have a serious question about so far is exception handling from the `decodeCall` calls, if you can point me to the right place there.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/ownerof/OwnerOfCall.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+    @Override
+    protected @NonNull HederaSystemContract.FullResult resultOfViewingNft(
+            @NonNull final Token token, @NonNull final Nft nft) {
+        requireNonNull(token);
+        requireNonNull(nft);
+
+        // TODO - gas calculation
+        final var explicitId = nft.ownerIdOrElse(AccountID.DEFAULT);
+        final long ownerNum;
+        if (explicitId.accountNumOrElse(TREASURY_OWNER_NUM) == TREASURY_OWNER_NUM) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/ownerof/OwnerOfCall.java:63]: Here's that rule again that 0.0.0 is the treasury account.  This time though it has a proper name!

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM as per hedera-base changes. 💯

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java [hunk 5]
```diff
@@ -439,6 +497,10 @@ private static boolean isLongZeroAddress(final byte[] explicit) {
         return true;
     }
 
+    private static byte[] explicitFromHeadlong(@NonNull final com.esaulpaugh.headlong.abi.Address address) {
+        return unhex(address.toString().substring(2));
+    }
+
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java:503]: As long as you're in this file consider annotating following line with "too many arguments" to indicate _which_ sonar warning is being suppressed

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java [hunk 6]
```diff
@@ -171,26 +175,83 @@ public class TestHelpers {
...
+            .symbol("FT")
+            .decimals(6)
+            .totalSupply(666666L)
             .tokenType(TokenType.FUNGIBLE_COMMON)
             .build();
-    public static final Token NON_FUNGIBLE_TOKEN = Token.newBuilder()
-            .tokenId(NON_FUNGIBLE_TOKEN_ID)
-            .tokenType(TokenType.NON_FUNGIBLE_UNIQUE)
+
+    public static final Token UNEASONABLY_DIVISIBLE_TOKEN = Token.newBuilder()
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java:185]: `UNREASONABLY_...` ?
`   ^              `

**Review by david-bakin-sl — COMMENTED** [review]
Generally LGTM but for the question (previously asked) on exception handling.  So leaving as "comment" for now.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/isoperator/IsOperatorCall.java [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+import com.hedera.node.app.service.contract.impl.hevm.HederaWorldUpdater;
+import edu.umd.cs.findbugs.annotations.NonNull;
+import edu.umd.cs.findbugs.annotations.Nullable;
+import java.util.Arrays;
+import java.util.Optional;
+
+/**
+ * Implements the token redirect {@code isApprovedForAll()} call of the HTS system contract.
+ */
+public class IsOperatorCall extends AbstractTokenViewCall {
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/isoperator/IsOperatorCall.java:48]: Why is this class called `IsOperatorCall`?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java [hunk 8]
```diff
@@ -417,7 +475,7 @@ private static byte[] clampedBytes(
         return data;
     }
 
-    private static byte[] asEvmAddress(final long num) {
+    public static byte[] asEvmAddress(final long num) {
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java:478]: maybe a comment as this is now public?

**Review by lukelee-sl — DISMISSED** [review]
LGTM

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java [hunk 9]
```diff
@@ -113,7 +128,7 @@ public void setNonce(final long contractNumber, final long nonce) {
                 .build();
         // TODO - implement proper signature VerificationAssistant
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java:129]: Ah yes, agreed. Will do in a PR that has already incurred a `-base` review requirement. 😁

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractTokenViewCall.java [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+
+/**
+ * Implementation support for view calls that require an extant token.
+ */
+public abstract class AbstractTokenViewCall extends AbstractHtsCall {
+    @Nullable
+    private final Token token;
+
+    protected AbstractTokenViewCall(
+            @NonNull final HederaWorldUpdater.Enhancement enhancement, @Nullable final Token token) {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractTokenViewCall.java:37]: That was my thought...agreed the result looks a bit weird. 🤔

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/QueryHederaNativeOperations.java [hunk 11]
```diff
@@ -76,6 +79,18 @@ public QueryHederaNativeOperations(@NonNull final QueryContext context) {
                 TokenID.newBuilder().tokenNum(tokenNumber).build());
     }
 
+    /**
+     * {@inheritDoc}
+     */
+    @Override
+    public @Nullable Nft getNft(final long tokenNumber, final long serialNo) {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/QueryHederaNativeOperations.java]: Good idea; made all the `get*()` methods and `resolveAlias()` default methods.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java:155]: Fixed list and moved into javadoc segment.

**Review by lukelee-sl — APPROVED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/isoperator/IsOperatorCall.java (hunk 7 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/isoperator/IsOperatorCall.java]: Renamed.

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java]: Fixed typo.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java (hunk 5 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java:509]: Added comment.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java (hunk 3 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java:66]: Fixed `HtsCallAttemptFactory` to catch exceptions and halt with `INVALID_OPERATION`, consuming all remaining gas.

**Review by david-bakin-sl — APPROVED** [review]
LGTM!

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java (hunk 3 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/balanceof/BalanceOfCall.java:66]: (Actually it is in `HtsSystemContract` now, TY.)

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !
