### PR TITLE
fix: 24347 Prevent stale reads in `LongListDisk` during chunk recycling

### LINKED ISSUE #24347: VirtualMap State ID Mismatch leads to `ParseException`
By using the state on disk feature we see the following error:

```
 ERROR IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
  java.lang.RuntimeException: Failed to deserialize a value from bytes
      at com.swirlds.virtualmap.datasource.VirtualLeafBytes.value(VirtualLeafBytes.java:107)
      at com.swirlds.virtualmap.VirtualMap.get(VirtualMap.java:600)
      at com.swirlds.state.merkle.disk.OnDiskReadableKVState.readFromDataSource(OnDiskReadableKVState.java:62)
      at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:74)
      at com.hedera.node.app.service.token.impl.ReadableTokenRelationStoreImpl.get(ReadableTokenRelationStoreImpl.java:53)
      at com.hedera.node.app.throttle.ThrottleAccumulator.hasNoRelation(ThrottleAccumulator.java:743)
      ...
  Caused by: com.hedera.pbj.runtime.ParseException: State ID num mismatch: expected=9, actual=126
      at com.swirlds.state.merkle.StateValue$StateValueCodec.parse(StateValue.java:134)
```

This was found while integrating the low-memory profile for conensus-node in solo (see https://github.com/hiero-ledger/solo/pull/3536)

It can be reproduced locally with settings from PR https://github.com/hiero-ledger/hiero-consensus-node/pull/23750 and have PTT running:
```
 java -Xmx8g -Dbenchmark.maxtps=100 \
    -cp /app/lib/*:/app/network-load-generator-0.13.1.jar \
    com.hedera.benchmark.NftTransferLoadTest \
    -c 1 -a 1000 -T 10 -n 10 -S flat -p 50 -R -t 300
```

### PR DESCRIPTION
**Pull request by imalygin**
## Problem

When `merkleDb.useDiskIndices=true`, load tests produce sporadic `ParseException: State ID num mismatch` errors during ingest. The failure occurs in `StateValue$StateValueCodec.parse()` when a leaf value read from disk belongs to a different state than expected.

## Root cause

`LongListDisk` has a race condition between readers (`lookupInChunk`, unsynchronized) and chunk lifecycle operations (`closeChunk` → `createChunk`). Because chunks in `LongListDisk` are identified by file offsets, recycling an offset via `freeChunks` allows a concurrent reader to complete a file read against an offset that now holds data for a different index range. The reader returns a stale/wrong disk location, which causes the downstream codec to parse bytes from the wrong state entry.

`LongListOffHeap` is immune because its lookups are atomic memory reads on direct `ByteBuffer`s behind an `AtomicReferenceArray` — a CAS-nulled slot is immediately visible to all readers.

## Fix

Introduce a `StampedLock` in `LongListDisk` to coordinate readers with structural changes:

- **`get()`** uses `tryOptimisticRead()` + `validate()`. The common case (no concurrent chunk recycling) costs a single volatile read — no CAS, no contention. If validation fails, it retries under a real read lock (still concurrent with other readers).
- **`closeChunk()`** acquires the write lock *after* zeroing the file region but *before* adding the offset to `freeChunks`. This invalidates all outstanding optimistic stamps, forcing any in-flight reader holding a stale offset to retry. The write-lock critical section contains only the `freeChunks.add()` call.

## Performance impact

| Scenario | Cost |
|---|---|
| Read, no concurrent shrink | ~1 volatile read (optimistic stamp + validate) |
| Read, concurrent shrink | Retry with read lock; readers don't block each other |
| closeChunk | Write lock held for `freeChunks.add()` only (nanoseconds) |

## Testing

- Existing `LongListDisk` unit tests pass (read/write, valid range updates, chunk reuse)
- Reproduces and verifies fix under the original load test that triggered the `State ID num mismatch` error
- Added concurrent stress test: parallel readers + `updateValidRange` shrinking on a `LongListDisk` instance, asserting no stale reads

**Related issue(s)**:

Fixes #24347 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/LongListDiskConcurrentChunkRecyclingTest.java [hunk 1]
```diff
@@ -0,0 +1,502 @@
...
+            try {
+                barrier.await();
+            } catch (Exception e) {
+                return;
+            }
+            long minV = 0;
+            long maxW = initialCount - 1;
+            for (int iter = 0; iter < 400 && !stop.get() && maxW + tinyChunk < tinyCapacity; iter++) {
+                minV += tinyChunk;
+                list.updateValidRange(minV, tinyCapacity - 1);
```
Comment (thenswan) [inline platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/LongListDiskConcurrentChunkRecyclingTest.java]: 1. range is only shrinking
2. confusing var names in this test

Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/LongListDiskConcurrentChunkRecyclingTest.java]: Yes, fair points. I reworked the test.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java [hunk 2]
```diff
@@ -64,6 +66,24 @@ public class LongListDisk extends AbstractLongList<Long> {
      */
     private final Deque<Long> freeChunks = new ConcurrentLinkedDeque<>();
 
+    /**
+     * Protects readers from observing a chunk file-offset that has been
+     * recycled by a concurrent {@link #closeChunk} / {@link #createChunk}
+     * cycle.
+     *
+     * <ul>
+     *   <li><b>Read lock</b> – held by {@link #get} while it resolves a
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: The read lock must be used in both get() and put() / putIfEqual().

Another option is to document that put() / putIfEqual() may not be called in parallel with updateValidRange() - there may already be a statement like this in the docs, I don't know. In this case, a short note here should be added why the lock is not used in puts

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java [hunk 3]
```diff
@@ -395,17 +448,51 @@ public void close() {
...
         } catch (IOException e) {
             throw new UncheckedIOException(e);
         }
-        freeChunks.add(chunk);
+
+        // Recycle the offset under the write lock.
+        // This waits for all in-flight readers to finish, ensuring
+        // no reader is still using this offset when it becomes
+        // available for reuse by createChunk().
+        chunkRecycleLock.writeLock().lock();
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: This should work, but wouldn't it be better to take the lock on the whole updateValidRange() operation, which may include multiple createChunk() / closeChunk() calls?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: Fixed.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java (hunk 3 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: Fair enough. I updated it

**Review by artemananiev — APPROVED** [review]
