### PR TITLE
fix: 24402: fix DataFileCollectionBench

### LINKED ISSUE #24402: Fix DataFileCollectionBench
`DataFileCollectionBench` fails with an error:
```
java.io.IOException: Got a data location from index for a file that doesn't exist. dataLocation={31,15} fileIndex=31 validKeyRange=(0,1000000)
currentIndexedFileList=[10, 21, 32]
	at com.swirlds.merkledb.files.DataFileCollection.readerForDataLocation(DataFileCollection.java:441)
	at com.swirlds.merkledb.files.DataFileCollection.readDataItem(DataFileCollection.java:478)
	at com.swirlds.benchmark.DataFileCollectionBench$1.read(DataFileCollectionBench.java:44)
	at com.swirlds.benchmark.DataFileCollectionBench.compaction(DataFileCollectionBench.java:84)
```

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
Fixed `DataFileCollectionBench`.

**Related issue(s)**:
Fixes #24402

### CODE REVIEW

File: platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/DataFileCollectionBench.java [hunk 1]
```diff
@@ -66,6 +67,7 @@ BenchmarkRecord read(long dataLocation) throws IOException {
                 index.put(id, store.storeDataItem(record::serialize, record.getSizeInBytes()));
                 if (verify) map[(int) id] = record;
             }
+            store.updateValidKeyRange(0, maxKey);
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/DataFileCollectionBench.java]: Minor: it's a bit confusing why a call above does `-1` and this one doesn't. There may (or may not) be an off-by one error. Otherwise, comments above both the calls could help explain the reason for the math (or lack thereof.)

Comment (thenswan) [reply platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/DataFileCollectionBench.java]: I eliminated confusion here. Across tests, key ranges for `DataFileCollection` are set in different ways and work in test scenarios.

Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/DataFileCollectionBench.java]: Thank you!
