### PR TITLE
Change the log level from Error to warn.

### LINKED ISSUE #955: File 0.0.150 needs to be created for migration tests.
**Summary of the defect**
During Migration tests, we see the following error logs:
`Node 0 has exception:- Error reading ‘0.0.150’ @ data/diskFs/0.0.3/File0.0.150!`

**How to reproduce (if possible)**
Run any migration test.

**Service logs (if applicable)**
HGCAA log:

2021-01-13 18:51:46.657 INFO  225  ServicesState - Init called on Services node 0 WITH Merkle saved state
2021-01-13 18:51:46.666 **ERROR 132  MerkleDiskFs - Error reading '0.0.150' @ data/diskFs/0.0.3/File0.0.150!
java.io.FileNotFoundException: File 'data/diskFs/0.0.3/File0.0.150' does not exist**
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:265) ~[commons-io-2.1.jar:2.1]
	at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1490) ~[commons-io-2.1.jar:2.1]
	at com.hedera.services.state.merkle.MerkleDiskFs.lambda$static$1(MerkleDiskFs.java:71) ~[HederaNode.jar:?]
	at com.hedera.services.state.merkle.MerkleDiskFs.contentsOf(MerkleDiskFs.java:130) [HederaNode.jar:?]
	at com.hedera.services.state.merkle.MerkleDiskFs.diskContentHash(MerkleDiskFs.java:125) [HederaNode.jar:?]
	at com.hedera.services.state.merkle.MerkleDiskFs.checkHashesAgainstDiskContents(MerkleDiskFs.java:113) [HederaNode.jar:?]
	at com.hedera.services.ServicesState.init(ServicesState.java:235) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:461) [swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:701) [swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:944) [swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:345) [swirlds-platform-core-0.7.5.jar:?]
2021-01-13 18:51:46.673 INFO  357  ServicesMain - [SwirldState Hashes]
  Overall           :: 04e7e606985726d5d4e93a9239032511ec74b40dfd78b54e1232581813876980438118260ba8e2890db73be750c3df7b
  Accounts          :: 4d63c6c481a04cdbe08cd1052e6b50e7bbaaa45acfd8d0abb2063793bea8e03c2cdd0c084487cafd870f29ea21db586c
  Storage           :: bc0c5d8543df17b1159aea8f8e208c2791599fdda29c2bbadfcc1a0dae777bb3f4b64062e3ec57036a487fbf9a08dd3a
  Topics            :: 8b1e9b1c50f83dc9df6b60708ef968206c66cc1d058785809e580bc2e7dd576c892c97df0756f6c7f812b3ba4660daae
  Tokens            :: 5223ee674932bc77d5987e5224feb2799bfee2a489dd52e817bb15e5e16a9946333243c7f950ea2040a77e34c1bc45b9
  TokenAssociations :: 51b5b3905e468e1493b12de0171ed892b65ee61c82490009a31da1d6c721816696d6ae7a488964e354bf2fac021fe417
  DiskFs            :: 884cd15c0bb8ccd0d05ba328aea3ea7a3f61f2b191c01cc50c0544a04a65fe92efeb067e1df4eb268bdbbc83b7d4ec04
  ScheduledTxs      :: ee4be3e3cb061f4d903c1a5db46bfaafaeb66d217ca95bca04ba625e0ef1b8afa5a5491c5a6f5859bcf1333dadfaf191
  NetworkContext    :: a4f6e87a3f1cd4ec82fefc3cfa534f2e28906d54a136606a8f15990345c3a7d1d2d303e3b7a55670b69a0546b6d4065a
  AddressBook       :: a37b6c89723ad86cc9fa291a9817b4a21be3186e402b1abf0bc6f1702158418d8d8890d42e171a1f95c042f97f6addc5

**Environment:**
- Hedera Services Version: 0.10.0 to current master

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #955

**Summary of the change**:
Changed the log level from Error to warn and only print out the stack trace when debug is enabled. I checked all the current callers of this method. As of now, this change shouldn't cause any issue.

This method is at low level. When anything happens, it's difficult for this method to decide whether the situation should be treated as error or not.  Its callers shall have better context to decide what it should be.  So an alternative solution is to re-throw this exception and let its called to handle it.

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java [hunk 1]
```diff
@@ -129,7 +129,12 @@ public void checkHashesAgainstDiskContents() {
 		try {
 			return bytesHelper.allBytesFrom(pathToContentsOf(fid));
 		} catch (IOException e) {
-			log.error("Error reading '{}' @ {}!", asLiteralString(fid), pathToContentsOf(fid), e);
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java:132]: @JeffreyDallas Can we think of a case where this `IOException` _would_ mean a serious error?

I wonder if we could just add a node-local property, say `files.skipDiskFsHashCheck`, and override it to `true` when running a migration test?

**Review by tinker-michaelj — APPROVED** [review]
Seems like a good solution for now!

**Review by JeffreyDallas — APPROVED** [review]

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java (hunk 1 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java:132]: Opened #1005 to track a long term solution.
