### PR TITLE
Fix UnsupportedQueriesRegression HapiSuite

### LINKED ISSUE #8155: Fix UnsupportedQueries test suite
### Problem

Fix UnsupportedQueriesRegression (part of Crypto hapi e2e test suite)

- [x] getClaimNotSupported()
- [x] getStakersNotSupported()
- [x] getFastRecordNotSupported()
- [x] getBySolidityIdNotSupported()
- [x] getTokenNftInfosNotSupported()
- [x] getAccountNftInfosNotSupported()

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
Fix UnsupportedQueriesRegression e2e test suite (part of Crypto hapi e2e test suite)

**Related issue(s)**:

Fixes #8155 
Relies on https://github.com/hashgraph/hedera-protobufs/pull/303

Sequence to merge this change across the two repositories:
-Merge this PR which sets hapiProtoBranchOrTag = "7680-Get-Fast-Record" // temporary branch
-Merge https://github.com/hashgraph/hedera-protobufs/pull/303 to merge changes in 7680-Get-Fast-Record into add-pbj-types-for-state
-Merge PR #8538 to reset the hapiProtoBranchOrTag back to add-pbj-types-for-state

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java [hunk 1]
```diff
@@ -144,9 +145,9 @@ public void handleQuery(@NonNull final Bytes requestBuffer, @NonNull final Buffe
         final var function = functionOf(query);
 
         final var handler = dispatcher.getHandler(query);
-        final var queryHeader = handler.extractHeader(query);
+        var queryHeader = handler.extractHeader(query);
         if (queryHeader == null) {
-            throw new StatusRuntimeException(Status.INVALID_ARGUMENT);
+            queryHeader = QueryHeader.DEFAULT;
```
Comment (rbair23) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java:150]: I might suggest:

```
    final var queryHeader = requireNonNullElse(handler.extractHeader(query), QueryHeader.DEFAULT);
```

Personally, I like using final where possible. It just feels "tighter" -- fewer loose ends.

**Review by rbair23 — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java:150]: Thanks for the suggestion, that looks cleaner. I see that you already approved. If I end up making changes for other reasons then I will incorporate this suggestion.

**Review by jeromy-cannon — APPROVED** [review]

**Review by qnswirlds — APPROVED** [review]

**Review by david-bakin-sl — APPROVED** [review]
LGTM
