### PR TITLE
Change the account balances export timeline.

### LINKED ISSUE #1142: Export account balances every exportPeriodSecs since the epoch (in consensus time)
**Summary of the defect**
The account balances file should be exported each time the signed state timestamp enters a new "period", where the timeline is broken into periods of length `balances.exportPeriodSecs` beginning with the epoch.

Also:

- [ ] Remove the timestamp for client saved .pb file

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #1142 

**Summary of the change**:

1. changed the account balances export timeline;
2. Also wiped out the timestamp field for client account balances .pb file.

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java [hunk 1]
```diff
@@ -94,7 +94,8 @@
 	private String lastUsedExportDir = UNKNOWN_EXPORT_DIR;
 	private BalancesSummary summary;
 
-	Instant periodEnd = NEVER;
+	Instant periodEnd = Instant.now();
+	private int exportPeriod = -1;
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java:98]: Should use a meaningful default value that could really be used in the calculations below.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java [hunk 2]
```diff
@@ -626,17 +626,14 @@ private String expectedExportDir() {
...
 	@Test
 	public void exportsWhenPeriodSecsHaveElapsed() {
+		now = subject.periodEnd;
+		anEternityLater = now.plusSeconds(dynamicProperties.balancesExportPeriodSecs() * 2);
 		assertFalse(subject.isTimeToExport(now));
-		assertEquals(now.plusSeconds(dynamicProperties.balancesExportPeriodSecs()), subject.periodEnd);
-		assertFalse(subject.isTimeToExport(shortlyAfter));
-		assertEquals(now.plusSeconds(dynamicProperties.balancesExportPeriodSecs()), subject.periodEnd);
 		assertTrue(subject.isTimeToExport(anEternityLater));
-		assertEquals(anEternityLater.plusSeconds(dynamicProperties.balancesExportPeriodSecs()), subject.periodEnd);
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:639]: We should keep the test with `assertFalse(subject.isTimeToExport(shortlyAfter));`, also we should keep the check on whether `periodEnd` got changed or not.

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Please see inline comments.

File: hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java (hunk 1 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java:98]: Yeah, make sense. Will change to default export value.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java (hunk 2 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:639]: Yeah, I will put back similar test cases, though may not be exactly same.

File: hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java [hunk 3]
```diff
@@ -77,6 +77,7 @@
 
 	private static final String PROTO_FILE_EXTENSION = ".pb";
 	private static final String CSV_FILE_EXTENSION = ".csv";
+	private static final int DEFAULT_EXPORT_PERIOD = 600; // seconds
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java:80]: Note that all global/dynamic properties **must** have a default value from the JAR's _src/main/resources/bootstrap.properties_. So we never have to use inline default constants in the code. 👍

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
LGTM! Just had one comment that we don't want to hard-code any default property values in the code (it is a system invariant that **all** properties have a default value in _src/main/resource/bootstrap.properties_).

File: hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java]: We can even make this `private final int exportPeriod` since it must be set in the constructor.

Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java]: Yeah. Changed.

File: hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java (hunk 3 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java:80]: Removed this line. It's good to know all properties must have a default value. Thx.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java (hunk 2 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java]: I changed the test scenarios to cover those changes.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java [hunk 4]
```diff
@@ -626,17 +622,39 @@ private String expectedExportDir() {
...
-		assertEquals(now.plusSeconds(dynamicProperties.balancesExportPeriodSecs()), subject.periodEnd);
+		// test the export won't happen inside interval
+		subject = new SignedStateBalancesExporter(properties, signer, dynamicProperties);
+		Instant startTime = Instant.parse("2021-03-11T10:01:32.0Z");
+		assertFalse(subject.isTimeToExport(startTime));
+		assertEquals(startTime, subject.periodBegin);
+		assertFalse(subject.isTimeToExport(startTime.plusSeconds(1)));
+		assertEquals(startTime.plusSeconds(1), subject.periodBegin);
+		assertFalse(subject.isTimeToExport(startTime.plusSeconds(11)));
+		assertEquals(startTime.plusSeconds(11), subject.periodBegin);
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:637]: This portion of the test is redundantly covered by the rest of the test. Plus it is using magic numbers, not the `dynamicProperties.balancesExportPeriodSecs()` that can clear show whether a new timestamp will trigger a balance export or not.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java [hunk 5]
```diff
@@ -626,17 +622,39 @@ private String expectedExportDir() {
...
+
+		Instant nextPeriod  = startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() + 1);
+
+		assertTrue(subject.isTimeToExport(nextPeriod));
+		assertEquals(startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() + 1), subject.periodBegin );
+
+		anEternityLater = startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() * 2 + 1);
 		assertTrue(subject.isTimeToExport(anEternityLater));
-		assertEquals(anEternityLater.plusSeconds(dynamicProperties.balancesExportPeriodSecs()), subject.periodEnd);
+		assertEquals(startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() * 2 + 1), subject.periodBegin);
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:657]: Replace `startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() * 2 + 1` by `anEternityLater`

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java [hunk 6]
```diff
@@ -626,17 +622,39 @@ private String expectedExportDir() {
...
+		subject = new SignedStateBalancesExporter(properties, signer, dynamicProperties);
+		startTime = Instant.parse("2021-03-11T10:59:59.0Z");
+		assertFalse(subject.isTimeToExport(startTime));
+		assertTrue(subject.isTimeToExport(startTime.plusSeconds(1)));
+		assertEquals(startTime.plusSeconds(1), subject.periodBegin);
+
+		shortlyAfter = startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() / 2);
 		assertFalse(subject.isTimeToExport(shortlyAfter));
-		assertEquals(now.plusSeconds(dynamicProperties.balancesExportPeriodSecs()), subject.periodEnd);
+		assertEquals(startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() / 2), subject.periodBegin);
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:648]: Replace `startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() / 2` by `shortlyAfter`

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java [hunk 7]
```diff
@@ -626,17 +622,39 @@ private String expectedExportDir() {
...
+
+		Instant nextPeriod  = startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() + 1);
+
+		assertTrue(subject.isTimeToExport(nextPeriod));
+		assertEquals(startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() + 1), subject.periodBegin );
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:653]: Replace `startTime.plusSeconds(dynamicProperties.balancesExportPeriodSecs() + 1` by `nextPeriod`

**Review by qnswirlds — CHANGES_REQUESTED** [review]

File: hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java [hunk 8]
```diff
@@ -136,12 +137,14 @@ public void exportBalancesFrom(ServicesState signedState, Instant when) {
 					when, summary.getTotalFloat(), expectedFloat)); }
 		log.info("Took {}ms to summarize signed state balances", watch.getTime(TimeUnit.MILLISECONDS));
 
-		if (exportCsv) {
-			toCsvFile(when);
-		}
+		// .pb account balances file is our focus, process it first to let its timestamp to stay close to
+		// epoch epxort period boundary
```
[the remark this answers is not in the document]
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java:141]: Good catch! Will fix it now. Thx!

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java (hunk 4 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:637]: Yeah. This portion is redundant. Removed.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java (hunk 5 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:657]: Done.

File: hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java (hunk 7 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java:653]: Done

**Review by qnswirlds — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
