### PR TITLE
fix: Avoid NPE in TipsetEventCreator in case we cannot create selfless event

### LINKED ISSUE #24142: NPE in TipsetEventCreator
```
 
2026-03-07 01:27:46.712 699986   ERROR EXCEPTION        <platformForkJoinThread-4> TipsetEventCreator: failed to locate eligible ignored node to use as a parent


2026-03-07 01:27:46.713 699987   ERROR EXCEPTION        <platformForkJoinThread-4> DefaultUncaughtExceptionHandler: Uncaught exception in EventCreationManager
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "element" is null
	at org.hiero.consensus.event.creator.impl.tipset.TipsetEventCreator.contains(TipsetEventCreator.java:353)
	at org.hiero.consensus.event.creator.impl.tipset.TipsetEventCreator.createEventCombinedAlgorithm(TipsetEventCreator.java:322)
	at org.hiero.consensus.event.creator.impl.tipset.TipsetEventCreator.maybeCreateUnsignedEvent(TipsetEventCreator.java:254)
	at org.hiero.consensus.event.creator.impl.tipset.TipsetEventCreator.maybeCreateEvent(TipsetEventCreator.java:217)
	at org.hiero.consensus.event.creator.impl.DefaultEventCreationManager.maybeCreateEvent(DefaultEventCreationManager.java:142)
	at com.swirlds.component.framework.component.ComponentWiring.lambda$bind$9(ComponentWiring.java:675)
	at com.swirlds.component.framework.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:96)
	at com.swirlds.component.framework.schedulers.internal.SequentialTask.onExecute(SequentialTask.java:77)
	at org.hiero.base.concurrent.AbstractTask.exec(AbstractTask.java:68)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

### PR DESCRIPTION
**Pull request by abies**
**Description**:
Due to change related to multiple other parents (MOP), null reference might have escaped from very rarely executed branch of code. This change makes sure it is not resulting in NPE, but rather skips event generation, as in pre-0.70 version.

**Related issue(s)**:

Fixes #24142

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java [hunk 1]
```diff
@@ -322,6 +322,9 @@ private UnsignedEvent createEventCombinedAlgorithm() {
         if (beNiceChance > 0 && random.nextDouble() < beNiceChance) {
             // replace one of the best parents with the one chosen to reduce selfishness
             final PlatformEvent selflessParent = selectParentToReduceSelfishness();
+            if (selflessParent == null) {
```
Comment (mxtartaglia-sl) [inline platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java:325]: I wonder if this cases doensn't mean:
"I've tried to be nice and reduce the selfishness a bit, but the node that is being ignored doesn't have an event to choose from, and so, I can't be nice even if I try."

If so, I think we should just continue creating an event in the outer part of the if as if the condition that entered this path was false.

Comment (abies) [reply platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java:325]: This is returning old behaviour of the code from 0.69. Any more complex modifications to the algorithm are risky, should be a different PR and we don't want to backport them to prod/late test version (and this PR is designed for that).

Actual fix and investigation of underlying problem (because that null return should NEVER happen) will be covered in https://github.com/hiero-ledger/hiero-consensus-node/issues/24143
