### PR TITLE
fix: use exact math for all summed balances

### LINKED ISSUE #12667: (mod) Use exact math when summing amounts
### Description

There are several places where `long` values are summed without `Math.addExact()`.

### Steps to reproduce

Submit a `CryptoTransfer` with e.g. only credits `(+Long.MAX_VALUE, +Long.MAX_VALUE, +2)` 

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
  - Fixes #12667 
  - Use `BigInteger` for net-zero adjustment calculations in `CryptoTransfer` pure checks.
  - Use exact math for all custom fee summing.
  - During record finalization,
      1. Use exact math for summing net balance adjustments.
      2. Add an extra safety check in record finalization for any balance that exceeds total hbar supply.

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java [hunk 1]
```diff
@@ -198,8 +203,21 @@ public static void adjustHbarFees(final AssessmentResult result, final AccountID
...
+    public static long addExactOrThrow(final long a, final long b) {
+        return addExactOrThrowReason(a, b, INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE);
+    }
+
+    public static long addExactOrThrowReason(
+            final long a, final long b, @NonNull final ResponseCodeEnum failureReason) {
+        try {
+            return Math.addExact(a, b);
+        } catch (final ArithmeticException ignore) {
+            throw new HandleException(INSUFFICIENT_SENDER_ACCOUNT_BALANCE_FOR_CUSTOM_FEE);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java:220]: Should we be using `failureReason` here ?

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Have just one comment. Thanks @tinker-michaelj 🙌

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/AdjustmentUtils.java]: Ah good catch Neeha, fixed.

**Review by Neeharika-Sompalli — APPROVED** [review]
