### PR TITLE
05761 pces span heuristic

### LINKED ISSUE #5761: Improve heuristic for sizing preconsensus event stream files
The current heuristic for sizing preconsensus event files is functional. But after integrating the file writer and watching it operate, I found that the heuristic results in some less-than-desirable properties.

I propose the following changes to the heuristic:

- create two modes of operation:
  - a mode where we quickly change the generation span as we attempt to find the ballpark span size we want
  - a mode where we slowly tweak generation span and converge on a more exact span
- atomic file renames after closing
  - allows us to overestimate generational span, and then fix it when finished (assuming we don't crash)
  - we don't want to overestimate span by too much, file overlap after a crash shouldn't result in a performance problem

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #5761

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java [hunk 1]
```diff
@@ -63,8 +63,9 @@ public class PreconsensusEventMetrics {
     private static final RunningAverageMetric.Config PRECONSENSUS_EVENT_AVERAGE_UN_UTILIZED_FILE_SPAN_CONFIG =
             new RunningAverageMetric.Config(CATEGORY, "preconsensusEventAverageUnutilizedFileSpan")
                     .withUnit("generations")
-                    .withDescription("The average unutilized generational span of preconsensus event files. "
-                            + "Only reflects files written since the last restart. Smaller is better.");
+                    .withDescription(
+                            "The average unutilized generational span of preconsensus event files prior "
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java:67]: This amendment "prior to span compaction" should also be added to the metric config above, `PRECONSENSUS_EVENT_AVERAGE_FILE_SPAN_CONFIG`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java [hunk 2]
```diff
@@ -331,12 +346,15 @@ private void closeFile() {
      * Calculate the generation span for a new file that is about to be created.
      */
     private long computeNewFileSpan(final long minimumFileGeneration, final long nextGenerationToWrite) {
-        if (averageGenerationalSpanUtilization.isEmpty()) {
-            return bootstrapGenerationalSpan;
-        }
 
-        final long desiredSpan =
-                (long) (averageGenerationalSpanUtilization.getAverage() * generationalSpanOverlapFactor);
+        final long basisSpan = (bootstrapMode || averageGenerationalSpanUtilization.isEmpty())
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java:350]: Is it conceivable that `bootstrapMode` could be false, *and* `averageGenerationalSpanUtilization` could be empty?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java:67]: Not actually necessary. The metric above reflects the actual generational span in the file, this metric shows the different between the actual span and the span specified by the fields in the file name. After span compaction is complete, the span specified by file name will match the actual span of events in the file.

The reason why it's still important to report this metric is that if we crash prior to finishing a file we will never get the chance to do span compaction. This is not the end of the world, but it may cause a large overlap between files, which is undesirable for performance reasons (it could cause us to take longer to replay the files).

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java:350]: Yes, I uncovered this case when testing. It will be empty exactly once, the first time it is called after we exit bootstrap mode.

**Comment by cody-littley** [comment]
@alittley I accidentally pressed the button to merge `develop` in github, then also merged it locally, so I had to use a force push. Sorry. 🙃

**Review by alittley — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 3]
```diff
@@ -427,8 +427,15 @@ private long getNextSequenceNumber() {
      */
     public void finishedWritingFile(@NonNull final PreConsensusEventMutableFile file) {
 
+        final long previousFileHighestGeneration;
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:430]: Generally I would recommend a unit test or 2 for this new logic, but since we're bumping into release timelines I'll let you decide whether or not you want to write them

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 3 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:430]: added a new test

**Review by alittley — APPROVED** [review]
