### PR TITLE
fix: negative Id for StakedNodeId in token service. less than -1

### LINKED ISSUE #13961: negative Id for StakedNodeId in token service
This is a user error, where they passed negative Id for StakedNodeId . It should have returned INVALID_STAKING_ID. But, because we construct new Node() without checking if the value is negative, we threw an IllegalArgumentException .
We should fix it [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java#L135)

```
2024-06-20 19:15:37.855 ERROR 660  HandleWorkflow - Possibly CATASTROPHIC failure while handling a user transaction
java.lang.IllegalArgumentException: id must be non-negative
	at com.swirlds.common.platform.NodeId.<init>(NodeId.java:69) ~[swirlds-common-0.50.0.jar:?]
	at com.hedera.node.app.info.NetworkInfoImpl.nodeInfo(NetworkInfoImpl.java:92) ~[?:?]
	at com.hedera.node.app.service.token.impl.validators.StakingValidator.validateStakedId(StakingValidator.java:130) ~[app-service-token-impl-0.50.0.jar:?]
	at com.hedera.node.app.service.token.impl.validators.StakingValidator.validateStakedIdForUpdate(StakingValidator.java:108) ~[app-service-token-impl-0.50.0.jar:?]
	at com.hedera.node.app.service.token.impl.handlers.CryptoUpdateHandler.validateFields(CryptoUpdateHandler.java:309) ~[app-service-token-impl-0.50.0.jar:?]
	at com.hedera.node.app.service.token.impl.handlers.CryptoUpdateHandler.validateSemantics(CryptoUpdateHandler.java:244) ~[app-service-token-impl-0.50.0.jar:?]
	at com.hedera.node.app.service.token.impl.handlers.CryptoUpdateHandler.handle(CryptoUpdateHandler.java:162) ~[app-service-token-impl-0.50.0.jar:?]
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchHandle(TransactionDispatcher.java:146) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleUserTransaction(HandleWorkflow.java:600) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handlePlatformTransaction(HandleWorkflow.java:322) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleRound(HandleWorkflow.java:288) ~[?:?]
	at com.hedera.node.app.Hedera.onHandleConsensusRound(Hedera.java:954) ~[?:?]
	at com.hedera.node.app.state.HederaLifecyclesImpl.onHandleConsensusRound(HederaLifecyclesImpl.java:110) ~[?:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.handleConsensusRound(MerkleHederaState.java:328) ~[?:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:60) ~[swirlds-platform-core-0.50.0.jar:?]
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:122) ~[swirlds-platform-core-0.50.0.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.handleConsensusRound(ConsensusRoundHandler.java:212) ~[swirlds-platform-core-0.50.0.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:111) ~[swirlds-common-0.50.0.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.50.0.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:191) ~[swirlds-common-0.50.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]```

### PR DESCRIPTION
**Pull request by povolev15**
fix bug issue that happened in testnet when negative less than -1 stakednodeid happened it fires incorrect exception

**Related issue(s)**:

Fixes #13961

### CODE REVIEW

**Review by iwsimon — APPROVED** [review]
LGTM

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java [hunk 1]
```diff
@@ -132,7 +132,9 @@ private void validateStakedId(
         if (stakedIdKind.equals("STAKED_ACCOUNT_ID")) {
             validateTrue(accountStore.getAccountById(requireNonNull(stakedAccountIdInOp)) != null, INVALID_STAKING_ID);
         } else if (stakedIdKind.equals("STAKED_NODE_ID")) {
-            validateTrue(networkInfo.nodeInfo(requireNonNull(stakedNodeIdInOp)) != null, INVALID_STAKING_ID);
+            requireNonNull(stakedNodeIdInOp);
+            validateTrue(stakedNodeIdInOp >= -1L, INVALID_STAKING_ID);
```
Comment (david-bakin-sl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java:136]: It is _not too late_ to give `-1` a **proper name**, which should have been done much earlier.  E.g., `public static final long RESET_STAKING_SENTINAL_ID = 1L;` and then provide `private boolean isValidStakedNodeId(final long stakedNodeId) { return stakedNodeId >= 0 }` and `private boolean isAcceptableStakedNodeId(final long stakedNodeId) { return isValidStakedNodeId(stakedNodeId) || stakedNodeId == RESET_STAKING_SENTINAL_ID; }`.  Or something similar.  So that the you don't have to rely on the comments to understand the code, when it's possible to make it so the code is understandable.  I'd also go for a `private final long RESET_STAKING_ACCOUNT_ID = 0L;` for the same reason.

(Names could be improved, but that's the idea.)

**Review by david-bakin-sl — APPROVED** [review]
LGTM but it would be really sweet to provide names for `-1L` and `0L` as the comment indicates.

**Review by kimbor — APPROVED** [review]
lgtm!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java (hunk 1 above)
Comment (povolev15) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java:136]: Thanks, David, we will fix it in the future because I think it is used in multiple places. I fixed it because I was paged on testnet about it
