### PR TITLE
fixed recordBuilder hash issue

### LINKED ISSUE #7700: Fix transaction hash calc in modularized `RecordService`
### Description

All EET's that run a `getTxnRecord` operation are failing to assert the retrieved record has the expected transaction hash.

### Steps to reproduce

Ran modrun, `UtilPrngSuite.usdFeeAsExpected(), got the FAILED status with log:
HapiSpecOperation - 'usdFeeAsExpected' - HapiGetTxnRecord{sigs=1, node=0.0.3, txn=prng} failed - org.opentest4j.AssertionFailedError: Bad transaction hash! ==> array contents differ at index [0], expected: <53> but was: <82>

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

**Related issue(s)**:

Fixes #7700 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by povolev15 — APPROVED** [review]
LGTM

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 1]
```diff
@@ -160,10 +162,19 @@ private void handlePlatformTransaction(
 
             preHandleResult = getCurrentPreHandleResult(state, platformEvent, platformTxn, configuration);
             final var transactionInfo = preHandleResult.txInfo();
+            final var transaction = transactionInfo.transaction();
             final var txBody = transactionInfo.txBody();
+            final Bytes transactionBytes;
+
+            if (transaction.signedTransactionBytes().length() > 0) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:169]: Might be worth checking for null here, in case this transaction doesn't have the new signed bytes form.
```suggestion
            if (transaction.signedTransactionBytes() != null && transaction.signedTransactionBytes().length() > 0) {
```

Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:169]: transaction is a PBJ record, the default value of signedTransactionBytes is Bytes.EMPTY. It will not be null unless someone set it to null in the Builder. I was thinking about we should also check both transactionInfo and transaction to see if they are null, then throw HandleException or something. I didn't it add yet and like to see reviewers' comments first. Thanks.

**Review by jsync-swirlds — APPROVED** [review]
LGTM.

**Review by kimbor — APPROVED** [review]
lgtm!

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Review by netopyr — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
