### PR TITLE
EET : Aggregate the accountAmounts in the token transfer list

### LINKED ISSUE #2311: EET testClient does not aggregate token transfers properly.
### Description

When we perform an operation like this : 

```
cryptoTransfer(
    moving(10, token).between(TOKEN_TREASURY, thirdUser),
    moving(20, token).between(TOKEN_TREASURY, firstUser)
)
```

EET produces the following transfer list:
```
tokenTransfers=0.0.1022([0.0.1018 -> -10, 0.0.1021 <- +10, 0.0.1018 -> -20, 0.0.1019 <- +20])([])}
```

This results in `ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS` response from the nodes.

### Steps to reproduce

Perform a test that does a crypto transfer similar to 
```
cryptoTransfer(
    moving(10, token).between(TOKEN_TREASURY, thirdUser),
    moving(20, token).between(TOKEN_TREASURY, firstUser)
)
```

### Additional context

_No response_

### Hedera network

other

### Version

v0.19.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by anighanta**
Signed-off-by: anighanta <anirudh.ghanta@hedera.com>

**Description**:

**Related issue(s)**:

Fixes #2311

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java [hunk 1]
```diff
@@ -395,6 +401,36 @@ protected HapiCryptoTransfer self() {
 				.collect(toList());
 	}
 
+	private Map<TokenID, List<AccountAmount>> AggregateOnTokenIds(HapiApiSpec spec) {
```
Comment (Neeharika-Sompalli) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java:404]: AggregateOnTokenIds -> aggregateOnTokenIds , method name convention

**Review by qnswirlds — COMMENTED** [review]
Do we have the same complaint for hbar transfers?
