### PR TITLE
Validate all TransactionBody's have an oneof set

### LINKED ISSUE #4658: 🔥 All `TransactionBody`'s have a `oneof` set.
In all the transaction records, validate the `TransactionBody` is set. 

It will be easy to parse the transaction using `functionOf(txBody);` method and see if the transactionBody is set.

Probably something like this. I have something implemented in t[his branch](https://github.com/hashgraph/hedera-services/compare/04658-D-txn-body-validation), but it is stale now.
```
public class TransactionBodyClassifier {
    private final Set<HederaFunctionality> transactionType = new HashSet<>();

    public HederaFunctionality incorporate(final RecordStreamItem item) {
        var txnType = NONE;
        try {
            txnType = functionOf(CommonUtils.extractTransactionBody(item.getTransaction()));
            transactionType.add(txnType);
        } catch (UnknownHederaFunctionality | InvalidProtocolBufferException e) {
            transactionType.add(txnType);
        }
        return txnType;
    }

    public boolean isInvalid() {
        return transactionType.contains(NONE);
    }
}
```

Testing:

Added this validator at the end of CI and validate no records are invalid.

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

**Related issue(s)**:

Fixes #4658 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+ */
+public class TransactionBodyValidator implements RecordStreamValidator {
+    private final Map<HederaFunctionality, Long> expectedTxnBodies = new EnumMap<>(HederaFunctionality.class);
+    private final TransactionBodyClassifier transactionBodyClassifier = new TransactionBodyClassifier();
+
+    @Override
+    @SuppressWarnings("java:S106")
+    public void validateRecordsAndSidecars(final List<RecordWithSidecars> recordsWithSidecars) {
+        validateTransactionBody(recordsWithSidecars);
+        System.out.println("Expected transaction body functions: " + expectedTxnBodies);
```
Comment (kimbor) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:40]: You should not have a System.out.println. Either replace with a logger, or if it's not critical information delete altogether.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+ * set, by comparing checking if there are any NONE functionality transactions at the end of the CI test run:
+ *
+ * <p>It uses the {@link TransactionBodyValidation} suite to perform the queries.
+ */
+public class TransactionBodyValidator implements RecordStreamValidator {
+    private final Map<HederaFunctionality, Long> expectedTxnBodies = new EnumMap<>(HederaFunctionality.class);
+    private final TransactionBodyClassifier transactionBodyClassifier = new TransactionBodyClassifier();
+
+    @Override
+    @SuppressWarnings("java:S106")
```
Comment (kimbor) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:37]: If you remove the System.out below, can also remove this @SuppressWarnings

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+
+    private void validateTransactionBody(final List<RecordWithSidecars> recordsWithSidecars) {
+        for (final var recordWithSidecars : recordsWithSidecars) {
+            final var items = recordWithSidecars.recordFile().getRecordStreamItemsList();
+            for (final var item : items) {
+                final var txnType = transactionBodyClassifier.incorporate(item);
+                if (expectedTxnBodies.containsKey(txnType)) {
+                    expectedTxnBodies.put(txnType, expectedTxnBodies.get(txnType) + 1);
+                } else {
+                    expectedTxnBodies.put(txnType, 1L);
```
Comment (kimbor) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:51]: Did you use 1L because it's HederaFunctionality.NONE? I dislike magic numbers. You should use a constant or at least add a comment to explain.

**Review by kimbor — CHANGES_REQUESTED** [review]

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.hedera.node.app.hapi.utils.exception;
+
+public class UnknownHederaFunctionality extends Exception {
```
[the remark this answers is not in the document]
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java:19]: If you search where is this used, you can find it. I checked InvalidTxBodyException and no javadoc there.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 5]
```diff
@@ -88,4 +135,143 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
     static void setSha384HashTag(final String sha384HashTag) {
         CommonUtils.sha384HashTag = sha384HashTag;
     }
+
+    public static HederaFunctionality functionOf(final TransactionBody txn) throws UnknownHederaFunctionality {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:139]: I like this. But, I believe this function exists in `MiscUtils`. You can delete there and move it into this class as you did.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.hedera.node.app.hapi.utils.exception;
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java:18]: Same with this. We can move this to hapi-utils. It currently exists `hedera-app`.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 5 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:139]: I updated the change you asked. Please re-check. Thanks.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java (hunk 6 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java:18]: I updated the change you asked. Please re-check. Thanks.

File: hedera-node/hedera-schedule-service-impl/build.gradle.kts [hunk 7]
```diff
@@ -31,6 +31,8 @@ configurations.all {
 }
 
 dependencies {
+  implementation(project(mapOf("path" to ":hedera-node:hapi-utils")))
+  implementation(project(mapOf("path" to ":hedera-node:hapi-utils")))
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-schedule-service-impl/build.gradle.kts:35]: Added twice. And also you can just do 
```
implementation(project(":hedera-node:hapi-utils"))

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+ * <p>It uses the {@link TransactionBodyValidation} suite to perform the queries.
+ */
+public class TransactionBodyValidator implements RecordStreamValidator {
+    private static final Logger log = LogManager.getLogger(TransactionBodyValidator.class);
+
+    private final Map<HederaFunctionality, Long> expectedTxnBodies = new EnumMap<>(HederaFunctionality.class);
+    private final TransactionBodyClassifier transactionBodyClassifier = new TransactionBodyClassifier();
+
+    @Override
+    public void validateRecordsAndSidecars(final List<RecordWithSidecars> recordsWithSidecars) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:41]: We should add this validator to `AllIntegrationTests.recordStreamValidation()` . Just like `BalanceReconciliationValidator`

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+/**
+ * This validator checks all the transactions submitted have {@link com.hederahashgraph.api.proto.java.TransactionBody}
+ * set, by comparing checking if there are any NONE functionality transactions at the end of the CI test run:
+ *
+ * <p>It uses the {@link TransactionBodyValidation} suite to perform the queries.
+ */
+public class TransactionBodyValidator implements RecordStreamValidator {
+    private static final Logger log = LogManager.getLogger(TransactionBodyValidator.class);
+
+    private final Map<HederaFunctionality, Long> expectedTxnBodies = new EnumMap<>(HederaFunctionality.class);
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:37]: Why do we need `expectedTxnBodies` ? I am not sure  if its useful to count `number of transactions` totally submitted.
imo, it will be helpful to log the record if it is invalid.

File: hedera-node/hedera-schedule-service-impl/build.gradle.kts (hunk 7 above)
Comment (iwsimon) [reply hedera-node/hedera-schedule-service-impl/build.gradle.kts]: This was auto added by IntelliJ. Thanks for catching it. Fixed.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java (hunk 8 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:41]: added.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java (hunk 9 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java]: changed it to log the record transactionId if it's invalid.

**Review by Neeharika-Sompalli — DISMISSED** [review]
Makes sense to me ! Good work @iwsimon  !

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 10]
```diff
@@ -88,4 +135,143 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
...
+        if (txn.hasContractCall()) {
```
Comment (netopyr) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:140]: This should be replaced with a switch statement IMO. Can be done in a follow-up PR.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (netopyr) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java:19]: I am not sure, I can follow. The class and constructor need javadocs.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 5 above)
Comment (netopyr) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:139]: Please add javadocs.

`@NonNull` missing for parameter and return type.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java
Comment (netopyr) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:1]: I find the code here surprisingly complex given that we are just looking for transactions for which we could not determine the functionality.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java:23]: added javadoc

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 5 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java]: added @NonNull and javadoc. Thanks.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 10 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:149]: Each if statement has different .hasXXX calls, I would like to see how you use switch statement IMO. Any code example?

Comment (netopyr) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:149]: Right, you cannot use these methods. But you can do a switch based on `TransactionBody.data().kind()`. You can find an example in `TransactionDispatcher`.

Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java]: I replaced if with switch. Thank you @netopyr for the good suggestion!

**Review by kimbor — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+    public void validateRecordsAndSidecars(final List<RecordWithSidecars> recordsWithSidecars) {
+        validateTransactionBody(recordsWithSidecars);
+        log.info("Expected transaction body functions: {}", expectedTxnBodies);
+    }
+
+    private void validateTransactionBody(final List<RecordWithSidecars> recordsWithSidecars) {
+        for (final var recordWithSidecars : recordsWithSidecars) {
+            final var items = recordWithSidecars.recordFile().getRecordStreamItemsList();
+            for (final var item : items) {
+                final var txnType = transactionBodyClassifier.incorporate(item);
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:50]: I think we can fail immediately with an `IllegalStateException` as soon as we see a `NONE`; the `expectedTxnBodies` I think is a bit confusing.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 12]
```diff
@@ -88,4 +137,65 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
...
+            case TOKENWIPE -> TokenAccountWipe;
+            case TOKENASSOCIATE -> TokenAssociateToAccount;
+            case TOKENDISSOCIATE -> TokenDissociateFromAccount;
+            case TOKEN_FEE_SCHEDULE_UPDATE -> TokenFeeScheduleUpdate;
+            case TOKEN_PAUSE -> TokenPause;
+            case TOKEN_UNPAUSE -> TokenUnpause;
+            case SCHEDULECREATE -> ScheduleCreate;
+            case SCHEDULEDELETE -> ScheduleDelete;
+            case SCHEDULESIGN -> ScheduleSign;
+            case NODE_STAKE_UPDATE -> NodeStakeUpdate;
```
Comment (tinker-michaelj) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:196]: ⚠️ This changes behavior compared to `MiscUtils.functionOf()`, which throws on a `NODE_STAKE_UPDATE`.

We should port unit tests from `MiscUtilsTest` and make sure no behavior changes, since this is changing production code.

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
Overall looks great!

Since we are changing production code in moving `functionOf()` to `CommonUtils`, we need to make sure its behavior doesn't change for a `NODE_STAKE_UPDATE`; and also ensure 95%+ code coverage.

For your `TransactionBodyValidator`, we _do_ need a variant that recognizes `NODE_STAKE_UPDATE`. So maybe we also need a `CommonUtils.functionOrStakeUpdateOf()` method to use in the validator?

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 12 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java]: removed NODE_STAKE_UPDATE from here.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 13]
```diff
@@ -88,4 +138,82 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
...
+
+    /**
+     * check TransactionBody and return the NodeStakeUpdate HederaFunctionality
+     *
+     * @param txn the {@code TransactionBody}
+     * @return one of HederaFunctionality
+     * @throws UnknownHederaFunctionality if it's not a NodeStakeUpdate HederaFunctionality
+     */
+    @NonNull
+    public static HederaFunctionality functionOrStakeUpdateOf(@NonNull final TransactionBody txn)
```
[the remark this answers is not in the document]
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:210]: This change was from @tinker-michaelj 's comments and has to be treated differently. This is not a valid type of transaction for a user to submit via HAPI, and is added for the node software to use to export stake info to mirror nodes in the record stream. This could be applied to all other record stream. So it's here.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 14]
```diff
@@ -88,4 +138,85 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
...
+
+    /**
+     * check TransactionBody and return the HederaFunctionality
+     *
+     * @param txn the {@code TransactionBody}
+     * @return one of HederaFunctionality
+     * @throws UnknownHederaFunctionality if all the check fails
+     */
+    @NonNull
+    public static HederaFunctionality functionOf(@NonNull final TransactionBody txn) throws UnknownHederaFunctionality {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:150]: I would suggest using the same method as the deleted one from `MiscUtils`

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 15]
```diff
@@ -88,4 +138,85 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
...
+     * check TransactionBody and return the NodeStakeUpdate HederaFunctionality,
+     * which was added for the node software to use to export stake info to mirror nodes in the record stream.
+     * It is not a valid type of transaction for a user to submit via HAPI.
+     *
+     * @param txn the {@code TransactionBody}
+     * @return one of HederaFunctionality
+     * @throws UnknownHederaFunctionality if it's not a NodeStakeUpdate HederaFunctionality
+     */
+    @NonNull
+    public static HederaFunctionality functionNodeStakeUpdateOf(@NonNull final TransactionBody txn)
```
Comment (Neeharika-Sompalli) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:213]: Since this is used only in `TransactionBodyValidator`, we should make this a private method in that class.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java [hunk 16]
```diff
@@ -0,0 +1,60 @@
...
+
+public class TransactionBodyClassifier {
+    private final Set<HederaFunctionality> transactionType = new HashSet<>();
+
+    public void incorporate(final RecordStreamItem item) throws InvalidProtocolBufferException {
+        var txnType = NONE;
+        TransactionBody txnBody = CommonUtils.extractTransactionBody(item.getTransaction());
+
+        try {
+            txnType = functionNodeStakeUpdateOf(txnBody);
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java:40]: nit: Since majority cases it will not be `NodeSTakeUpdate`, you could do `functionOf` first.
```
 HederaFunctionality txnType;
        TransactionBody txnBody = CommonUtils.extractTransactionBody(item.getTransaction());
        try {
            txnType = functionOf(txnBody);
        } catch (UnknownHederaFunctionality e) {
             // This is needed while validating record streams for NodeStakeUpdate transactions
            txnType = txnBody.getDataCase().equals(NODE_STAKE_UPDATE) ? NodeStakeUpdate : NONE;
        }
        transactionType.add(txnType);
```

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 15 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java]: Updated code.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java (hunk 16 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java]: Updated code.

**Review by Neeharika-Sompalli — COMMENTED** [review]
LGTM ! But need to make sure Integration and E2E tests pass.

**Review by Neeharika-Sompalli — APPROVED** [review]

File: hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java [hunk 17]
```diff
@@ -111,5 +208,112 @@ void detectsOverflowInVariousCases() {
...
     }
 
+    @Test
+    void throwsOnUnexpectedFunctionality() {
+        assertThrows(UnknownHederaFunctionality.class, () -> functionOf(TransactionBody.getDefaultInstance()));
+    }
+
+    @Test
+    void getsExpectedTxnFunctionality() {
+        final Map<HederaFunctionality, BodySetter<? extends GeneratedMessageV3, Builder>> setters = new HashMap<>() {
```
Comment (netopyr) [inline hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:218]: Have you considered writing a data-driven test (one that uses `@ParameterizedTest`) instead? Creating such a data structure and iterating over it looks unusual.

File: hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java [hunk 18]
```diff
@@ -111,5 +208,112 @@ void detectsOverflowInVariousCases() {
...
+                put(CryptoApproveAllowance, new BodySetter<>(CryptoApproveAllowanceTransactionBody.class));
+            }
+        };
+
+        setters.forEach((function, setter) -> {
+            final var txn = TransactionBody.newBuilder();
+            setter.setDefaultInstanceFor(txn);
+            try {
+                final var input = txn.build();
+                assertEquals(function, functionOf(input));
```
Comment (netopyr) [inline hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:271]: What happens if an `assertEquals` fails within a lambda expression? Is junit able to handle it and show a useful error message?

File: hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java [hunk 19]
```diff
@@ -111,5 +208,112 @@ void detectsOverflowInVariousCases() {
...
+            } catch (final UnknownHederaFunctionality uhf) {
+                throw new IllegalStateException(uhf);
+            }
+        });
+    }
+
     private static final ByteString NONSENSE = ByteString.copyFromUtf8("NONSENSE");
+
+    private static class BodySetter<T, B> {
```
Comment (netopyr) [inline hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:280]: This test looks more complicated than the functionality you are testing, which is almost always a bad sign. Is it really necessary to do all of this?

Comment (netopyr) [reply hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:280]: Ah, never mind. I just realized that you just moved the test from elsewhere. We should probably create an issue to redesign this test.

Comment (iwsimon) [reply hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:280]: Yes, I just moved these tests since I moved functionOf() call from MiscUtils to CommonUtils and changed it to switch expression.

File: hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java (hunk 18 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:271]: Tried a failed case, junit showed a useful error message.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 20]
```diff
@@ -88,4 +136,65 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
     static void setSha384HashTag(final String sha384HashTag) {
         CommonUtils.sha384HashTag = sha384HashTag;
     }
+
+    /**
+     * check TransactionBody and return the HederaFunctionality. This method was moved from MiscUtils.
```
Comment (hendrikebbers) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:141]: `This method was moved from MiscUtils` <- This is not really a needed information in JavaDoc.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java [hunk 21]
```diff
@@ -88,4 +136,65 @@ public static boolean productWouldOverflow(final long multiplier, final long mul
...
+     * NODE_STAKE_UPDATE is not checked in this method, since it is not a user transaction.
+     *
+     * @param txn the {@code TransactionBody}
+     * @return one of HederaFunctionality
+     * @throws UnknownHederaFunctionality if all the check fails
+     */
+    @NonNull
+    public static HederaFunctionality functionOf(@NonNull final TransactionBody txn) throws UnknownHederaFunctionality {
+        DataCase dataCase = txn.getDataCase();
```
[the remark this answers is not in the document]
Comment (hendrikebbers) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:150]: `CommonUtils` sounds too common for this use case. I assume a class that cares about Transactions makes more sense.

File: hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java [hunk 22]
```diff
@@ -111,5 +208,112 @@ void detectsOverflowInVariousCases() {
...
+        };
+
+        setters.forEach((function, setter) -> {
+            final var txn = TransactionBody.newBuilder();
+            setter.setDefaultInstanceFor(txn);
+            try {
+                final var input = txn.build();
+                assertEquals(function, functionOf(input));
+            } catch (final UnknownHederaFunctionality uhf) {
+                throw new IllegalStateException(uhf);
```
Comment (hendrikebbers) [inline hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java:273]: use fail(....) instead?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 23]
```diff
@@ -0,0 +1,55 @@
...
+ * set, by comparing checking if there are any NONE functionality transactions at the end of the CI test run:
+ *
+ * <p>It uses the {@link TransactionBodyValidation} suite to perform the queries.
+ */
+public class TransactionBodyValidator implements RecordStreamValidator {
+
+    private final TransactionBodyClassifier transactionBodyClassifier = new TransactionBodyClassifier();
+
+    @Override
+    public void validateRecordsAndSidecars(final List<RecordWithSidecars> recordsWithSidecars) {
```
Comment (hendrikebbers) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:35]: null annotations and null checks missing

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java [hunk 24]
```diff
@@ -0,0 +1,55 @@
...
+            final var items = recordWithSidecars.recordFile().getRecordStreamItemsList();
+            for (final var item : items) {
+                try {
+                    transactionBodyClassifier.incorporate(item);
+                    if (transactionBodyClassifier.isInvalid()) {
+                        throw new IllegalStateException(
+                                "Invalid TransactionBody type HederaFunctionality.NONE with record: " + item);
+                    }
+                } catch (InvalidProtocolBufferException e) {
+                    throw new IllegalStateException(e);
```
Comment (hendrikebbers) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:50]: please add a message

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java [hunk 25]
```diff
@@ -0,0 +1,57 @@
...
+import com.hederahashgraph.api.proto.java.HederaFunctionality;
+import com.hederahashgraph.api.proto.java.TransactionBody;
+import com.hederahashgraph.api.proto.java.TransactionBody.DataCase;
+import java.util.HashSet;
+import java.util.Set;
+
+public class TransactionBodyClassifier {
+    private final Set<HederaFunctionality> transactionType = new HashSet<>();
+
+    public void incorporate(final RecordStreamItem item) throws InvalidProtocolBufferException {
```
Comment (hendrikebbers) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java:37]: null annotations and null checks missing

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 21 above)
[the remark this answers is not in the document]
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:152]: Added nullcheck. Yes, CommonUtils is too common. Maybe we can refactory it later to somewhere else.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java (hunk 20 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java:142]: @Neeharika-Sompalli asked me to add this. The important one is next sentence: NODE_STAKE_UPDATE is not checked in this method, since it is not a user transaction.

File: hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java (hunk 22 above)
Comment (iwsimon) [reply hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java]: Replaced it with fail. Thanks.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java (hunk 23 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java]: added null check.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java (hunk 24 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:60]: Added log.error. However, we are double logging here as we log the exception in TestBase.assertValidatorsPass(). Hope it's not too much.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by nathanklick — APPROVED** [review]
Approved on behalf of release engineering with respect to `module-info.java` changes only, no other code has been reviewed. Please seek additional approvals as necessary.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java (hunk 24 above)
Comment (hendrikebbers) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java:60]: I mean that you should pass a message to the construction of the exception. 
```suggestion
                    throw new IllegalStateException("a message that describes the error",e);
```
