### PR TITLE
08237 Fixed validation of multiple rounds in VirtualMerkleLeafHasher

### LINKED ISSUE #8237: VMap: State file not found
This appeared in 2 tests:
http://35.247.76.217:8095/swirlds-automation/develop/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/
http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230828-053537-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

```
---- VirtualMerkleLeafValidator FAILED validation ----
<<ERROR>>
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/node0000/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/0/123/4016/vmapHashes.json
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/node0001/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/1/123/4016/vmapHashes.json
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/node0002/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/2/123/4016/vmapHashes.json
```

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This fix resets MerkleDb static state to prevent usage of incorrect metadata during the validation of the state files. 
Here is the explanation of why it's happening. `VirtualMerkleLeafHasher#main` loads rounds to validate. To do so it creates a virtual map which, in it's turn, creates a _default instance_ of MerkleDB (see `com.swirlds.virtualmap.VirtualMap#loadFromFile`) if it doesn't exist. To check if it exists or not, it checks if the path for a default instance is set or not. If the path is `null`, it creates a new instance. 

Also, `VirtualMap#loadFromFile` loads `virtualMapState` from the disk. This state, among other things, contains `firstLeafPath` and `lastLeafPath`. These parameters are defining a valid range of the keys we can use to get leaf values from the map. 

It all works perfectly fine if `VirtualMerkleLeafHasher` needs to validate a single round. The issue comes into play whenever it tries to validate more than one round. To validate the next round it creates another virtual map, and another call to  `VirtualMap#loadFromFile` updates `virtualMapState` and, therefore, `firstLeafPath` and `lastLeafPath`. However, it doesn't create another instance of `MerkleDb` because it was previously created. And this previously created instance has different valid `firstLeafPath` and `lastLeafPath`. 

**Related issue(s)**:

Fixes #8237

### CODE REVIEW

**Review by artemananiev — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java [hunk 1]
```diff
@@ -323,16 +325,6 @@ public AddressBook updateWeight(@NonNull AddressBook configAddressBook, @NonNull
         return configAddressBook;
     }
 
-    private void resetDefaultMerkleDbPathIfNeeded() {
-        // This is a workaround to support multiple nodes running in a single process for testing
```
Comment (OlegMazurov) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java:327]: I think this comment is worth saving. Maybe move it to where resetDefaultInstancePath() is called in the constructor.

**Review by OlegMazurov — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java (hunk 1 above)
Comment (imalygin) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java:327]: I moved this comment to javadoc of `MerkleDb#resetDefaultInstancePath`, so the information is not lost.

**Review by OlegMazurov — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

**Review by poulok — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
