### PR TITLE
fix: Use reserved cons times for post-upgrade system tx dispatches

### LINKED ISSUE #20327: `doPostUpgradeSetup()` should use system-reserved consensus timestamps
When we dispatch post-upgrade system transactions [here](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java#L485), the resulting `SystemContext` [here](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java#L341) is using the round timestamp as its first dispatch time.

But if the first round post-upgrade has a user transaction, this will cause a duplicate.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #20327 by adding `UseReservedConsensusTimes` and `TriggerStakePeriodSideEffects` enums to system tx context factory and configuring them appropriately.

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java [hunk 1]
```diff
@@ -619,13 +626,33 @@ public Instant restartSystemChangesTimeAt(@NonNull final Instant firstEventTime)
                                 : 0);
     }
 
+    /**
+     * Whether a context for system transactions should use reserved prior consensus times, or pick up from
+     * the time given to the transaction context factory.
+     */
+    private enum UseReservedConsensusTimes {
```
Comment (derektriley) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java:633]: Do you see these enums being expanded in the future? Why not just use a boolean for each?

**Review by derektriley — APPROVED** [review]
Minor question, LGTM.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java:633]: This improves readability at the _call site_; so instead of seeing just `true`, we see `UseReservedConsensusTimes.YES`.
