### PR TITLE
test: Add checks for socket exceptions

### LINKED ISSUE #21514: Drop connections
When shutting down a node, isolating a node or partitioning multiple nodes, it should be configurable if the connection is dropped or traffic blocked. By default, we want to drop connections (which should result in `SOCKET_EXCEPTION`).

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

This PR adds checks for socket exceptions when nodes are disconnected or shut down.

It also moves `NetworkPartitionTest` temporarily into the `testIntegration` module to allow access to the logs if the flaky test `testCreateAndRemovePartition` fails again.

**Related issue(s)**:

Fixes #21514

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java [hunk 1]
```diff
@@ -62,62 +65,88 @@ void testIsolateAndRejoinSingleNode(@NonNull final TestEnvironment env) {
...
-                    network::allNodesAreActive,
-                    Duration.ofSeconds(120L),
-                    "Not all nodes became ACTIVE after rejoining");
+            for (int i = 0; i < 3; i++) {
+
+                // Capture logs from all nodes
+                final List<SingleNodeLogResult> logResults = Stream.of(node0, node1, node2, node3)
+                        .map(Node::newLogResult)
+                        .toList();
+                logResults.forEach(SingleNodeLogResult::clear);
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java]: I think this would be simpler if the variable stored the multiple node results:

```
final MultipleNodeLogResults logResults = network.newLogResults();
logResults.clear();
```

And later, you can iterate through each individual one use `logResults.results()`

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java [hunk 2]
```diff
@@ -62,62 +65,88 @@ void testIsolateAndRejoinSingleNode(@NonNull final TestEnvironment env) {
...
+                // Verify network knows about the isolation partition
+                assertThat(network.getNetworkPartitionContaining(node0)).isEqualTo(isolationPartition);
+                assertThat(network.networkPartitions()).hasSize(2); // isolation + remaining nodes
+
+                // Verify the remaining nodes are in a complementary partition
+                final Partition remainingPartition = network.getNetworkPartitionContaining(node1);
+                assertThat(remainingPartition).isNotNull().isNotEqualTo(isolationPartition);
+                assertThat(remainingPartition.nodes()).containsExactlyInAnyOrder(node1, node2, node3);
+
+                // Wait for nodes to become inactive due to network partition
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java]:
```suggestion
                // Wait for the isolated node to go into CHECKING due to the network partition
```

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java [hunk 3]
```diff
@@ -90,6 +98,21 @@ void testKillAndRestartSingleNode(@NonNull final TestEnvironment env) {
                 assertThat(node2.isActive()).isTrue();
                 assertThat(node3.isActive()).isTrue();
 
+                // check there are socket exceptions in all logs
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java]: Comment is incorrect, since it only checks the logs of the nodes that remained active

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java [hunk 4]
```diff
@@ -74,6 +77,11 @@ void testKillAndRestartSingleNode(@NonNull final TestEnvironment env) {
 
             for (int i = 0; i < 3; i++) {
 
+                // Capture logs from the nodes that will remain active
+                final List<SingleNodeLogResult> logResults =
+                        Stream.of(node1, node2, node3).map(Node::newLogResult).toList();
+                logResults.forEach(SingleNodeLogResult::clear);
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java]: nit: this could also be accomplished with `network.newLogResults().suppressingNode(node0)`

File: platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/zzz/NetworkPartitionTest.java [hunk 5]
```diff
@@ -1,22 +1,29 @@
 // SPDX-License-Identifier: Apache-2.0
-package org.hiero.otter.fixtures;
+package org.hiero.otter.zzz;
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/zzz/NetworkPartitionTest.java:2]: what is this? 😆

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java (hunk 1 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java]: Oh, I forgot that this is possible. 😆

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java (hunk 2 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NetworkIsolationTest.java]: fixed

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java (hunk 4 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java]: yeah, yeah, forest... trees... 😄 
fixed

File: platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java (hunk 3 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/test/java/org/hiero/otter/fixtures/NodeLifecycleTest.java]: fixed

File: platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/zzz/NetworkPartitionTest.java (hunk 5 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/zzz/NetworkPartitionTest.java:2]: An attempt to ensure this test runs last which will hopefully preserve the logs.

**Review by poulok — APPROVED** [review]
