### PR TITLE
fix: fixed nextNodeId is decremented when the last node is removed

### LINKED ISSUE #15161: nextNodeId is decremented when the last node is removed.
Jeffery was testing node delete transaction with solo.
He started a network with 4 nodes
address, 0, 0, node1, 500, network-node1-0.network-node1.node-delete.svc.cluster.local, 50111, network-node1-svc.node-delete.svc.cluster.local, 50111, 0.0.3
address, 1, 1, node2, 500, network-node2-0.network-node2.node-delete.svc.cluster.local, 50111, network-node2-svc.node-delete.svc.cluster.local, 50111, 0.0.4
address, 2, 2, node3, 500, network-node3-0.network-node3.node-delete.svc.cluster.local, 50111, network-node3-svc.node-delete.svc.cluster.local, 50111, 0.0.5
address, 3, 3, node4, 500, network-node4-0.network-node4.node-delete.svc.cluster.local, 50111, network-node4-svc.node-delete.svc.cluster.local, 50111, 0.0.6
nextNodeId, 4
After sending a node delete transaction to delele the last node in addressbook, hedera app generated the following new config.txt
address, 0, 0, node1, 125, network-node1-0.network-node1.node-delete.svc.cluster.local, 50111, network-node1-svc.node-delete.svc.cluster.local, 50111, 0.0.3
address, 1, 1, node2, 125, network-node2-0.network-node2.node-delete.svc.cluster.local, 50111, network-node2-svc.node-delete.svc.cluster.local, 50111, 0.0.4
address, 2, 2, node3, 125, network-node3-0.network-node3.node-delete.svc.cluster.local, 50111, network-node3-svc.node-delete.svc.cluster.local, 50111, 0.0.5
nextNodeId, 3
But when restarting hedera with the new config.txt, I got the following error
java.lang.IllegalStateException: The new address book's nextNodeId 3 must be greater than or equal to the previous address book's nextNodeId 4

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

 Fixed the issue and added more tests.

**Related issue(s)**:

Fixes #15161

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM @iwsimon . We can also add the same upgrade test with last node removed as well and see if it passes.

**Comment by iwsimon** [comment]
> LGTM @iwsimon . We can also add the same upgrade test with last node removed as well and see if it passes.

Yes, I added it here: com.hedera.node.app.service.networkadmin.impl.test.handlers.ReadableFreezeUpgradeActionsTest#preparesForUpgradeWithDAB2

File: hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java [hunk 1]
```diff
@@ -52,11 +52,14 @@ public class AddressBookHelper {
      */
     public static long getNextNodeID(@NonNull final ReadableNodeStore nodeStore) {
         requireNonNull(nodeStore);
-        final long maxNodeId = StreamSupport.stream(
-                        Spliterators.spliterator(nodeStore.keys(), nodeStore.sizeOfState(), DISTINCT), false)
-                .mapToLong(EntityNumber::number)
-                .max()
-                .orElse(-1L);
+        long maxNodeId = -1L;
+        if (nodeStore.keys() != null) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:56]: When will this be null ?

**Review by Neeharika-Sompalli — COMMENTED** [review]
LGTM except a null check that seems not required.

File: hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:56]: It's good to add null check here because Spliterators.spliterator() check for requireNonNull(iterator). If it's a mock object such as in FreezeHandlerTest#happyPathFreezeUpgradeOrTelemetryUpgrade, we get nullpointerexception.

Comment (netopyr) [reply hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:56]: We do not need to fix this in this PR, but I think this is not good practice. `ReadableNodeStore.keys()` should be annotated with `NonNull`, and tests need to be adjusted to behave like the real code.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:56]: Agreed, we should adjust test in later PR.  It might be confusing in the future when we add null checks, when not required.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @iwsimon

File: hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:56]: I will update the test and remove null check in the next PR.

**Comment by iwsimon** [comment]
> LGTM! Thanks @iwsimon . Seems there are compile issues

Merged from develop fixed the compile issue.
