### PR TITLE
fix(21894): Set consistent handlers in deterministic model, do not swallow exceptions when using deterministic task schedulers

### LINKED ISSUE #21894: Deterministic schedulers don't use the set `UncaughtExceptionHandler`;  deterministic wiring model does not set the handlers consistently
Two problems detected 
1) When using deterministic schedulers, in case of setting an uncaughtExceptionHandler in the model, it doesn't get invoked, leading to swallowing exceptions. This scheduler is only used in Test.

2) The Deterministic model (exclusively used in tests, otter included) is setting inconsistent uncaughtExceptionHandlers for concurrent task schedulers (returning a deterministic scheduler) and for sequential task schedulers (using direct schedulers), leaving to a situation where it depends on the type of the scheduler if a test will fail with an exception being rethrown or not.

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
This pr fixes two problems detected:

* When using deterministic schedulers, if an uncaughtExceptionHandler is set in the model, it doesn't get invoked, leading to exceptions being swallowed. This scheduler is only used in Test.

* The Deterministic model (exclusively used in tests, otter included) is setting inconsistent uncaughtExceptionHandlers for concurrent task schedulers (returning a deterministic scheduler) and for sequential task schedulers (using direct schedulers), leaving to a situation where it depends on the type of the scheduler if a test will fail with an exception being rethrown or not.

**Related issue(s)**:

Fixes #21894

### CODE REVIEW

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/builders/internal/AbstractTaskSchedulerBuilder.java [hunk 1]
```diff
@@ -264,11 +264,17 @@ public AbstractTaskSchedulerBuilder<OUT> withDataCounter(@NonNull ToLongFunction
...
+        return uncaughtExceptionHandlerOr(ExceptionHandlers.defaultExceptionHandler(name));
+    }
+
+    /**
+     * Returns either the set uncaughtExceptionHandler or the handler sent as parameter.
+     * @param or the uncaught exception handler to return in case none was set
+     * @return the uncaught exception handler
+     */
+    @NonNull
+    protected UncaughtExceptionHandler uncaughtExceptionHandlerOr(@NonNull UncaughtExceptionHandler or) {
```
Comment (netopyr) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/builders/internal/AbstractTaskSchedulerBuilder.java]: I find this method and its name misleading. The method returns either the uncaughtExceptionHandler that was set on this builder or a provided default. That's unexpected behavior for a builder.

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/deterministic/DeterministicTaskScheduler.java [hunk 2]
```diff
@@ -25,37 +25,33 @@ public class DeterministicTaskScheduler<OUT> extends TaskScheduler<OUT> {
...
+     *                                 throw.
+     * @param insertionIsBlocking      when data is inserted into this task scheduler, will it block until capacity is
+     *                                 available?
+     * @param submitWork               a method where all work should be submitted
      */
     protected DeterministicTaskScheduler(
             @NonNull final TraceableWiringModel model,
             @NonNull final String name,
             @NonNull final TaskSchedulerType type,
+            final UncaughtExceptionHandler uncaughtExceptionHandler,
```
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/deterministic/DeterministicTaskScheduler.java]: nit: nullity

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/deterministic/DeterministicTaskScheduler.java [hunk 3]
```diff
@@ -122,9 +112,16 @@ protected boolean offer(@NonNull final Consumer<Object> handler, @NonNull final
     @Override
     protected void inject(@NonNull final Consumer<Object> handler, @NonNull final Object data) {
         onRamp.forceOnRamp();
-        submitWork.accept(() -> {
+        submitWork.accept(() -> doWork(handler, data));
+    }
+
+    private void doWork(final @NonNull Consumer<Object> handler, final @NonNull Object data) {
```
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/internal/deterministic/DeterministicTaskScheduler.java]: nit: we usually put the nullity annotation before `final`

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/builders/internal/AbstractTaskSchedulerBuilder.java (hunk 1 above)
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/schedulers/builders/internal/AbstractTaskSchedulerBuilder.java]: nit: `final`

**Review by poulok — APPROVED** [review]
