### PR TITLE
fix: close last sidecar file

### LINKED ISSUE #13435: `TraceabilitySuite` is flaky in CI
### Description

We are irregularly but frequently seeing failures like,
```
org.opentest4j.AssertionFailedError: There are some sidecars that have not been yet externalized in the sidecar files after all specs: Pending sidecars not yet seen: 
****** PENDING #1******
*** Pending sidecar***
ethereumLazyCreateExportsExpectedSidecars: <consensus_timestamp {
  seconds: 1716257029
  nanos: 675075078
}
actions {
  contract_actions {
    call_type: CALL
    calling_account {
      accountNum: 5189
    }
```

### Steps to reproduce

Run this suite in CI.

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #13435

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/BroadcastingRecordStreamListener.java [hunk 1]
```diff
@@ -72,11 +77,12 @@ private void retryExposingVia(
...
             try {
                 exposure.accept(f);
+                log.info("Provided validators with access to {} file {}", fileType, f.getAbsolutePath());
                 return;
             } catch (UncheckedIOException e) {
-                if (retryCount < 8) {
+                if (retryCount < NUM_RETRIES) {
                     try {
-                        Thread.sleep(500);
+                        MILLISECONDS.sleep(RETRY_BACKOFF_MS);
```
Comment (iwsimon) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/BroadcastingRecordStreamListener.java:85]: Wondering if any benefit using TimeUnit instead of Thread here?

Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/BroadcastingRecordStreamListener.java:85]: No real benefit, just a bit more readable imo.

**Review by iwsimon — DISMISSED** [review]
LGTM. Thanks @tinker-michaelj

**Review by jeromy-cannon — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
Makes sense to me. Thanks @tinker-michaelj

**Review by jeromy-cannon — APPROVED** [review]
