### PR TITLE
fix: Ui metrics name

### LINKED ISSUE #11316: bug: Metrics consumed by the ui where not changed
Getting following error in the ui
```
2024-02-01 11:03:21.954 476      ERROR EXCEPTION        <AWT-EventQueue-0> Log4jSetup: exception on thread AWT-EventQueue-0
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "com.swirlds.metrics.api.Metrics.getValue(String, String)" is null
	at com.swirlds.demo.hashgraph.HashgraphDemoMain$Picture.paintComponent(HashgraphDemoMain.java:240) ~[?:?]
```

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
Fixes #11316

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]

File: platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java [hunk 1]
```diff
@@ -237,9 +237,9 @@ public void paintComponent(final Graphics g) {
             final double createCons = (double) metrics.getValue(PLATFORM_CATEGORY, "secC2C");
             final double recCons = (double) metrics.getValue(PLATFORM_CATEGORY, "secR2C");
 
-            print(g, "%5.0f trans/sec", (double) metrics.getValue(PLATFORM_CATEGORY, "trans/sec"));
-            print(g, "%5.0f events/sec", (double) metrics.getValue(PLATFORM_CATEGORY, "events/sec"));
-            print(g, "%4.0f%% duplicate events", (double) metrics.getValue(PLATFORM_CATEGORY, "dupEv%"));
+            print(g, "%5.0f trans_per_sec", (double) metrics.getValue(PLATFORM_CATEGORY, "trans_per_sec"));
```
Comment (edward-swirldslabs) [inline platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java:240]: I wonder if making metric names constants in some sort of `EventMetricsConstants` class would be useful at some point.  This comment isn't meant to block this PR, just observing that a common constant would make future metric name changes occur everywhere at once.

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java (hunk 1 above)
Comment (mxtartaglia-sl) [reply platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java:240]: yes, I agree. But we would still need to find a place to put those constants compatible with the modularization efforts going on.
