### PR TITLE
chore: Introduce fixed random seed

### LINKED ISSUE #19190: Allow to set a seed
Provide the possibility to set a fixed seed easily.

This is not as straightforward as one might expect. We want to initialize the environment before we pass control to the user, but to do that, we already need the seed. One possibility would be to set it in an annotation.

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

This PR introduces a new annotation `@TurtleSpecs` that allows defining Turtle-specific configurations. It adds the parameter `randomSeed` to specify a fixed random seed.

**Related issue(s)**:

Fixes #19190

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleSpecs.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+@Target({ElementType.TYPE, ElementType.METHOD})
+@Retention(RetentionPolicy.RUNTIME)
+public @interface TurtleSpecs {
+
+    /**
+     * Fixed seed for the PRNG of the test. If set to {@code 0} (the default), a random seed will be generated.
+     *
+     * @return the random seed
+     */
+    long randomSeed() default 0L;
```
Comment (timo0) [inline platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleSpecs.java:21]: I would vote for `-1`

File: platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/junit/OtterTestExtension.java [hunk 2]
```diff
@@ -150,7 +152,11 @@ public boolean supportsTestTemplate(@NonNull final ExtensionContext context) {
      * @return a new {@link TurtleTestEnvironment} instance
      */
     private TestEnvironment createTurtleTestEnvironment(@NonNull final ExtensionContext extensionContext) {
-        final TurtleTestEnvironment turtleTestEnvironment = new TurtleTestEnvironment();
+        final Optional<TurtleSpecs> turtleSpecs =
+                AnnotationSupport.findAnnotation(extensionContext.getElement(), TurtleSpecs.class);
+        final long randomSeed = turtleSpecs.map(TurtleSpecs::randomSeed).orElse(0L);
```
Comment (timo0) [inline platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/junit/OtterTestExtension.java:157]: I would vote for `-1`

**Review by timo0 — APPROVED** [review]
looks good for me! I would vote for a different default value but fine not changing :)

File: platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleSpecs.java (hunk 1 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleSpecs.java:21]: Why `-1`? It is often used as a default when the valid range is only positive numbers. However, this is not the case here.

Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/turtle/TurtleSpecs.java:21]: As discussed, there are no strong reasons one way or the other. I will therefore keep the current implementation. We can change it later if we discover good reasons.
