### PR TITLE
fix: Sidecars/trace data for `REVERTED_SUCCESS` inside batch

### LINKED ISSUE #22516: Revert sidecar/trace data with "write" semantics in failed `AtomicBatch`
[Here](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/BaseTranslator.java#L657) there is a hidden assumption that successful EVM tx executions in a batch will not have a later operation fail. C.f. a temporary workaround,
```
                            if (value == null) {
                                Bytes valueFromState;
                                if (executingHookId == null
                                        || contractId.contractNumOrThrow() != HTS_HOOKS_CONTRACT_NUM) {
                                    valueFromState = writtenSlots.get(slotKey);
                                } else {
                                    valueFromState = writtenLambdaSlots.get(
                                            new LambdaSlotKey(executingHookId, minimalKey(slotKey.key())));
                                }
                                if (valueFromState == null) {
                                    // (FUTURE) - uncomment throw below once we have determined the right way to
                                    // unblock BlockItem -> TransactionSidecarRecord translation for the scenario in
                                    // ContractGetInfoSuite#userPaysTheGasUsed()
                                    //                                    throw new IllegalStateException("No written
                                    // value found for write to " + slotKey
                                    //                                            + " in " + remainingStateChanges);
                                    valueFromState = Bytes.fromHex("02");
                                }
                                value = HookUtils.minimalRepresentationOf(valueFromState);
                            }
```

The fix actually applies to both record stream sidecars and block stream trace data:
 - When an `AtomicBatch` fails, revert or revise any data with "write" semantics.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #22516

### CODE REVIEW

**Review by mhess-swl — APPROVED** [review]
Looks good, thanks @tinker-michaelj!

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java [hunk 1]
```diff
@@ -612,6 +614,35 @@ public Output build(final boolean topLevel, @Nullable final List<StateChange> gr
             if (slotUsages != null) {
                 final boolean traceExplicitWrites = logicallyIdentical == null;
                 if (traceExplicitWrites) {
+                    // When writes are traced explicitly in ContractSlotUsage#writtenSlotKeys, we index the reads
+                    // to their corresponding writes; so in the case of a reverted transaction, we need to swap
```
Comment (lukelee-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java:618]: > we need to swap the indexes back to the original keys before output

I'm unsure as to when this happens.  Perhaps in a future pr, the comment can be modified to clarify

**Review by lukelee-sl — APPROVED** [review]
LGTM.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/BlockStreamBuilder.java:618]: Ah yes will do.
