### PR TITLE
fix: rejected execution in wiring framework

### LINKED ISSUE #11290: Catch Rejected Execution Exceptions
In the wiring framework, we should not explode if the fork join pool throws a `RejectedExecutionException` from `ForkJoinPool.managedBlock()`.

### PR DESCRIPTION
**Pull request by cody-littley**
closes #11290

### CODE REVIEW

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java [hunk 1]
```diff
@@ -72,38 +73,43 @@ public BackpressureObjectCounter(
      */
     @Override
     public void onRamp() {
-        final long currentCount = count.get();
-        if (currentCount < capacity) {
-            final boolean success = count.compareAndSet(currentCount, currentCount + 1);
-            if (success) {
-                return;
+        while (true) {
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:76]: This is basically a spin until the condition is met and loop indefinitely until it is?  Does this burn 1 cpu while waiting?

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java (hunk 1 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:76]: nevermind, I think I misread where the scope ends.   The brain read the closing brace, but it's in a red zone, not a green zone.

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:76]: It will burn a CPU either until the condition is met (i.e. there is capacity in the queue) or the fork join pool has sufficient resources to offload the blocked thread. This is intended as a last resort as opposed to just crashing when the exception is thrown. In practice, we shouldn't see this unless there is something hogging the fork join pool resources.

File: platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java [hunk 2]
```diff
@@ -108,7 +108,7 @@ void orderOfOperationsTest(final String typeString) {
         assertEventuallyEquals(
                 value,
                 wireValue::get,
-                Duration.ofSeconds(1),
+                Duration.ofSeconds(10),
```
Comment (cody-littley) [inline platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java:111]: Note to reviewers:github test runner has been super flaky of late. Tests that used to work just fine are now having bizzare timing issues. I suspect the computer running tests is overloaded.

Increasing the timeouts here will allow more leniency when the host runner is under extreme load, but will add no additional time to the test if the runner is running at normal speed.

Comment (edward-swirldslabs) [reply platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java:111]: The timing issues are in no way related to this code change?

**Review by edward-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java:111]: I can't rule that out. However, I'm unable to reproduce the failures locally. Also, I've seen lots of time sensistive tests get flaky recently.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java [hunk 3]
```diff
@@ -72,38 +73,43 @@ public BackpressureObjectCounter(
...
+                // The managedBlock() pattern allows us to block while yielding the physical CPU core to other
+                // tasks.
+                ForkJoinPool.managedBlock(onRampBlocker);
+                return;
+            } catch (final InterruptedException ex) {
+                // This should be impossible.
+                Thread.currentThread().interrupt();
+                throw new IllegalStateException("Interrupted while blocking on an onRamp() for " + name);
+            } catch (final RejectedExecutionException ex) {
+                // We've exhausted our supply of background threads, we have no choice but to busy wait.
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:111]: Should we sleep a bit?

**Review by alittley — DISMISSED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java (hunk 3 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:111]: Possibly. @OlegMazurov what would you recommend that we do inside this loop?

File: platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/test/java/com/swirlds/common/wiring/schedulers/SequentialTaskSchedulerTests.java:111]: Additional information I just found out recently (repeating it here for others, we discussed this privately on slack). There was a recent CI pipeline change that causes our tests to all run in parallel. These tests spin up lots of threads, and I'm thinking they are interfering with each other and fighting over CPU resources. IMO, increasing timeouts for stability is better than using the tag that forces the tests to run serially.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java (hunk 3 above)
Comment (OlegMazurov) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:111]: Add `Thread.onSpinWait()`. Instantiating and throwing the exception is expensive enough to pass for a delay between unsuccessful attempts. Will be clearly visible in profiles (we'll reassess if and when that happens).
The real issue is that we use back-pressure inside a ForkJoinPool.

Comment (cody-littley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/counters/BackpressureObjectCounter.java:111]: done

**Review by alittley — APPROVED** [review]
