### PR TITLE
Reduce fee for perf test

### LINKED ISSUE #1143: Reduce fee for performance test
When a performance test starts, it usually creates a payer account with recharging option so when this account runs out of balance, it is recharged by the test default payer. Sometimes, due to high TPS, the transaction to recharge fails and therefore prevents the test from continuing and passing. An option to consider is to reduce the fee charged when running a performance test.

### PR DESCRIPTION
**Pull request by qnswirlds**
**Related issue(s)**:
Closes #1143

**Summary of the change**:
- Refactor `UtilVerbs.makeFree()` to allow fee reduction for a specific `HederaFunctionality`
- Make use of the `max` field in FeeComponents so all of the logics in fee calculations will still be exercised and tested
https://github.com/hashgraph/hedera-protobufs-java/blob/a43782805b6d98855e72b2c6dc202f9d3f430715/src/main/proto/BasicTypes.proto#L293-L295
- Reduce fee for `CryptoTransferLoadTest`, `SubmitMessageLoadTest` and `TokenTransfersLoadProvider`
- Add a `reduceTransferFee()` test in `MiscCryptoSuite`

Performance tests that passed with reduced fee

Crypto 10k-46m
- https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614793907225900

Crypto 10k-181m
- https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614806749232400
`2021-03-03 21:23:07.913 INFO   188  HapiGetAccountBalance - 'RunCryptoTransfers' - balance for 'sender': 99999890913892 tinyBars (999998ħ)` (remaining balance after test, down from 1m hbars, so less than 2 hbars was used for this 3-hr test)

HCS 10k-61m
- https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614813854236400

HTS 10k-63m
- https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614820090238900
- https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1614833963243100

**External impacts**:
None.

**Applicable documentation**
None.

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java [hunk 1]
```diff
@@ -414,35 +415,52 @@ public static HapiSpecOperation ensureDissociated(String account, List<String> t
...
+
+	public static HapiSpecOperation reduceFeeFor(HederaFunctionality function,
+			long tinyBarMaxNodeFee, long tinyBarMaxNetworkFee, long tinyBarMaxServiceFee) {
 		return withOpContext((spec, opLog) -> {
+			if (!spec.setup().defaultNode().equals(asAccount("0.0.3"))) {
+				opLog.info("Sleeping to wait for fee reduction...");
+				Thread.sleep(20000);
+				return;
+			}
+			Thread.sleep(10000);
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java:429]: What's the purpose to wait 10s here?

File: test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java [hunk 2]
```diff
@@ -56,7 +57,8 @@ public static void main(String... args) {
 	private List<HapiApiSpec> positiveTests() {
 		return Arrays.asList(
 //				transferChangesBalance()
-				getsGenesisBalance()
+//				getsGenesisBalance()
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java:60]: Do you intend to comment out this test?

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java (hunk 1 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java:429]: At first, I added only the sleep on line 426 for other clients to wait for the fee schedules update. Then as described in the following commit https://github.com/hashgraph/hedera-services/pull/1144/commits/d4a0d63ee802eb1656701c9596428705c1797f04, because `HapiApiSpec.tryReinitializingFees()` runs before any other ops, so on other clients, `HapiApiSpec.tryReinitializingFees()` will run before the sleep on line 426 kicks in. The client targeting node 0.0.3 has to wait so not to disturb (fail) the `HapiApiSpec.tryReinitializingFees()` on other clients. I'll add comment to explain in the test code too.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java [hunk 3]
```diff
@@ -113,6 +115,7 @@ protected HapiApiSpec runCryptoTransfers() {
 						fileUpdate(APP_PROPERTIES)
 								.payingWith(GENESIS)
 								.overridingProps(Map.of("hapi.throttling.buckets.fastOpBucket.capacity", "1300000.0")),
+						reduceFeeFor(CryptoTransfer, 2L, 3L, 3L),
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java:118]: Can the fees be reduced to even lower, or to all `0`s? For longer run and higher TPS, I am afraid the small fees may still adds up to deplete the payer balance before the perf test ends.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java (hunk 2 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java:60]: It seems to me that this suite serves as a playground for manual and convenient testing, for example, to get Genesis balance of a network, which we don't always want run that as a functionality test. That was why I picked this suite to add the `reduceTransferFee` test to show that the fee reduction works. Again, `reduceTransferFee` is not necessarily tested for functionality.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java (hunk 3 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java:118]: No, we wouldn't want that because we still want to see fees (all kinds including node, network and service fees) being charged. Besides, as I just added in the comment of the PR, a 3-hr test used less than 2 hbars!
`2021-03-03 21:23:07.913 INFO   188  HapiGetAccountBalance - 'RunCryptoTransfers' - balance for 'sender': 99999890913892 tinyBars (999998ħ)`

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java (hunk 1 above)
Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java:429]: I see. Yeah, I think a comment will make it clear. I was thinking the client for 0.0.3 to run first, but forgot other clients may run earlier than node 0.0.3's client.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java (hunk 2 above)
Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/MiscCryptoSuite.java:60]: Got it.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java (hunk 3 above)
Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java:118]: I thought for a dedicated 3-hr transfer load test with 10K or higher TPS, the fee will be much higher. But a quick calculation shows it will be less than 9 hbar for its theoretical max value.

**Review by ljianghedera — DISMISSED** [review]
LGTM.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java (hunk 3 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java:118]: Exactly, and since we are running 6N-6C, the payer account for each client will be deducted less than 2 hbars, as mentioned.

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM

**Review by tinker-michaelj — APPROVED** [review]
👍

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by ljianghedera — APPROVED** [review]
