### PR TITLE
Align expiry record `TransactionID` with HIP-449

### LINKED ISSUE #3984: NPE when running `ValidationScenarios`
```
2022-09-23 20:16:41.886 ERROR 174  TreasuryReturns - Unable to return all NFTs from account 0.0.2299120
java.lang.NullPointerException: Cannot invoke "com.hedera.services.state.merkle.MerkleUniqueToken.getNext()" because "burnedNft" is null
	at com.hedera.services.state.expiry.removal.TreasuryReturnHelper.burnOrReturnNft(TreasuryReturnHelper.java:81) ~[?:?]
	at com.hedera.services.state.expiry.removal.TreasuryReturns.tryNftReturns(TreasuryReturns.java:169) ~[?:?]
	at com.hedera.services.state.expiry.removal.TreasuryReturns.returnNftsFrom(TreasuryReturns.java:132) ~[?:?]
	at com.hedera.services.state.expiry.removal.AccountGC.expireBestEffort(AccountGC.java:72) ~[?:?]
	at com.hedera.services.state.expiry.removal.RemovalHelper.remove(RemovalHelper.java:75) ~[?:?]
	at com.hedera.services.state.expiry.removal.RemovalHelper.tryToRemoveContract(RemovalHelper.java:67) ~[?:?]
	at com.hedera.services.state.expiry.ExpiryProcess.process(ExpiryProcess.java:54) ~[?:?]
	at com.hedera.services.state.expiry.EntityAutoExpiry.executeInternal(EntityAutoExpiry.java:105) ~[?:?]
	at com.hedera.services.state.expiry.EntityAutoExpiry.execute(EntityAutoExpiry.java:73) ~[?:?]
	at com.hedera.services.state.logic.StandardProcessLogic.incorporateConsensusTxn(StandardProcessLogic.java:120) ~[?:?]
	at com.hedera.services.txns.ProcessLogic.lambda$incorporateConsensus$0(ProcessLogic.java:39) ~[?:?]
	at com.swirlds.common.system.Round.forEachEventTransaction(Round.java:80) ~[swirlds-common-0.30.0.jar:?]
	at com.hedera.services.txns.ProcessLogic.incorporateConsensus(ProcessLogic.java:38) ~[?:?]
	at com.hedera.services.ServicesState.handleConsensusRound(ServicesState.java:216) ~[?:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:180) ~[swirlds-platform-core-0.30.0.jar:?]
	at com.swirlds.platform.state.SwirldStateManagerDouble.handleConsensusRound(SwirldStateManagerDouble.java:154) ~[swirlds-platform-core-0.30.0.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:311) ~[swirlds-platform-core-0.30.0.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.waitForItem(QueueThreadImpl.java:249) ~[swirlds-common-0.30.0.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:229) ~[swirlds-common-0.30.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:573) ~[swirlds-common-0.30.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:204) ~[swirlds-common-0.30.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### LINKED ISSUE #3990: Expiry records need to use globally unique `TransactionID`s per HIP-449
### Description

[HIP-449](https://hips.hedera.com/hip/hip-449) superseded the [initial record spec from HIP-16](https://github.com/hashgraph/hedera-services/blob/master/docs/autorenew-feature.md#autorenewal-record).

According to HIP-449, expiry records should receive a `TransactionID` derived via the same approach as other child records.

But at present the `TransactionID`'s exported still follow the HIP-16 spec.

### Steps to reproduce

Generate expiry records using the `v0.30.2` tag.

### Additional context

_No response_

### Hedera network

other

### Version

v0.30.2

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issues**:
- Closes #3990 
- Closes #3984

**Description**:
- Fixes `ExpiryRecordHelper` to source `TransactionID`s from the `RecordsHistorian`'s top-level transaction. 
   * Adds two small methods `nextSystemTransactionIdIsUnknown()` and `computeNextSystemTransactionId()` to `RecordsHistorian` interface for this purpose.
- [Avoids NPE](https://github.com/hashgraph/hedera-services/blob/fix-expiry-record-id/hedera-node/src/main/java/com/hedera/services/state/expiry/removal/TreasuryReturns.java#L158) in case of a contract in state with inconsistent `numNftsOwned > 0`.

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/records/RecordsHistorian.java [hunk 1]
```diff
@@ -153,6 +154,21 @@ void trackPrecedingChildRecord(
      */
     Instant nextFollowingChildConsensusTime();
 
+    /**
+     * Returns whether there is a usable system transaction id available.
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/records/RecordsHistorian.java:158]: typo I think , do you mean `unavailable or null ` ?

File: hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java [hunk 2]
```diff
@@ -210,30 +210,24 @@ public Optional<TransactionBody.Builder> synthContractOpFromEth(final EthTxData
...
+        return TransactionBody.newBuilder().setContractDeleteInstance(op);
     }
 
     public TransactionBody.Builder synthAccountAutoRemove(final EntityNum accountNum) {
         final var grpcId = accountNum.toGrpcAccountId();
         final var op = CryptoDeleteTransactionBody.newBuilder().setDeleteAccountID(grpcId);
-        return TransactionBody.newBuilder()
-                .setTransactionID(TransactionID.newBuilder().setAccountID(grpcId))
-                .setCryptoDelete(op);
+        return TransactionBody.newBuilder().setCryptoDelete(op);
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java:221]: On line 220 , don't we need to set `.setPermanentRemoval(true)` ?

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! other than a question

File: hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java:221]: Cleared as account removal is not active and the field is not added to protobufs yet.
