### PR TITLE
fix: token associations modular dumper

### LINKED ISSUE #10918: Differential testing: Enhance token associations store dumper to handle modular representation
Token associations store dumper needs to handle the migration + dumping of the modular representation.

See the DumpContractStoresSubcommand for how this can be done.

See https://www.notion.so/swirldslabs/Signed-State-Store-Dumpers-57d4412fa4c84459a0ca699ce1446c98 for further information.

Depends on https://github.com/hashgraph/hedera-services/issues/10913

### PR DESCRIPTION
**Pull request by petreze**
**Description**:
This PR adds modu dumper for token associations

**Related issue(s)**:

Fixes #10918 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociation.java [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+        final var value = wrapper.getValue();
+        return new TokenAssociation(
+                accountIdFromMod(value.accountId()),
+                tokenIdFromMod(value.tokenId()),
+                value.balance(),
+                value.frozen(),
+                value.kycGranted(),
+                value.automaticAssociation(),
+                tokenIdFromMod(value.previousToken()),
+                tokenIdFromMod(value.previousToken()));
```
Comment (agadzhalov) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociation.java:65]: I assume  on L65 `tokenIdFromMod(value.previousToken()));` should be `tokenIdFromMod(value.nextToken()));`

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+    @NonNull
+    private static final List<Pair<String, BiConsumer<FieldBuilder, TokenAssociation>>> fieldFormatters = List.of(
+            Pair.of("owner", getFieldFormatter(TokenAssociation::accountId, ThingsToStrings::toStringOfEntityId)),
+            Pair.of("spender", getFieldFormatter(TokenAssociation::tokenId, ThingsToStrings::toStringOfEntityId)),
+            Pair.of("creationTime", getFieldFormatter(TokenAssociation::balance, Object::toString)),
+            Pair.of("metadata", getFieldFormatter(TokenAssociation::isFrozen, Object::toString)),
+            Pair.of("prev", getFieldFormatter(TokenAssociation::isKycGranted, Object::toString)),
+            Pair.of("next", getFieldFormatter(TokenAssociation::isAutomaticAssociation, Object::toString)),
+            Pair.of("next", getFieldFormatter(TokenAssociation::prev, ThingsToStrings::toStringOfEntityId)),
+            Pair.of("next", getFieldFormatter(TokenAssociation::next, ThingsToStrings::toStringOfEntityId))
```
Comment (agadzhalov) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:127]: Currently the header from mono is:
`account;token;balance;frozen;kycGranted;automaticAssociation;prev;next`

We have to update the titles as follows:

owner -> account
spender -> token
creationTime -> balance
metadata -> frozen
prev -> kycGranted
next -> automaticAssociation
next -> prev
next -> next

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+                    writer.getSize(), checkpoint.name());
+        }
+    }
+
+    @NonNull
+    private static <K extends VirtualKey, V extends VirtualValue>
+            Map<TokenAssociationId, TokenAssociation> gatherTokenRelations(
+                    @NonNull final VirtualMap<K, V> source,
+                    @NonNull final Function<K, TokenAssociationId> keyMapper,
+                    @NonNull final Function<V, TokenAssociation> valueMapper) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:80]: I like this approach to adapting the same iterator over the store to both mono+modular representations.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+                    .extractVirtualMapData(
+                            getStaticThreadManager(),
+                            p -> tokenAssociations.add(
+                                    Pair.of(keyMapper.apply(p.left()), valueMapper.apply(p.right()))),
+                            threadCount);
+        } catch (final InterruptedException ex) {
+            System.err.println("*** Traversal of token associations virtual map interrupted!");
+            Thread.currentThread().interrupt();
+        }
+        while (!tokenAssociations.isEmpty()) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:95]: Nothing wrong here but you could consider using `ConcurrentLinkedQueue.forEach`.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 5]
```diff
@@ -0,0 +1,150 @@
...
+            final var mapping = tokenAssociations.poll();
+            r.put(mapping.key(), mapping.value());
+        }
+        return r;
+    }
+
+    private static void reportOnUniques(
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:102]: Method name should be fixed.  (_not_ uniques here)

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 6]
```diff
@@ -0,0 +1,150 @@
...
+
+    static <T> void formatField(
+            @NonNull final FieldBuilder fb,
+            @NonNull final TokenAssociation unique,
+            @NonNull final Function<TokenAssociation, T> fun,
+            @NonNull final Function<T, String> formatter) {
+        fb.append(formatter.apply(fun.apply(unique)));
+    }
+
+    private static void formatUnique(@NonNull final Writer writer, @NonNull final TokenAssociation unique) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:145]: And again, method name.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 7]
```diff
@@ -0,0 +1,150 @@
...
+
+    @NonNull
+    static <T> BiConsumer<FieldBuilder, TokenAssociation> getFieldFormatter(
+            @NonNull final Function<TokenAssociation, T> fun, @NonNull final Function<T, String> formatter) {
+        return (fb, u) -> formatField(fb, u, fun, formatter);
+    }
+
+    static <T> void formatField(
+            @NonNull final FieldBuilder fb,
+            @NonNull final TokenAssociation unique,
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:139]: Here formal parameter name needs fixin'.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java (hunk 2 above)
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:127]: The field names "owner", "spender", etc are all wrong for associations.  This means the CSV header line will not be correctd.

**Review by david-bakin-sl — CHANGES_REQUESTED** [review]
Looks good except  1) for over-enthusiastic cut/paste that left some things named `unique`-ishly instead of `token_rel`-ishly and more important 2) please fix the field names for the CSV headers.  With that done I'll just approve it directly.

**Review by david-bakin-sl — APPROVED** [review]
LGTM!

**Review by vtronkov — DISMISSED** [review]

**Review by jeromy-cannon — APPROVED** [review]

**Review by agadzhalov — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java [hunk 8]
```diff
@@ -0,0 +1,149 @@
...
+        writer.writeln(formatHeader());
+        associations.entrySet().stream()
+                .sorted(Map.Entry.comparingByKey())
+                .forEach(e -> formatTokenAssociation(writer, e.getValue()));
+        writer.writeln("");
+    }
+
+    @NonNull
+    private static String formatHeader() {
+        return "accountId,tokenId,"
```
Comment (vtronkov) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:111]: Sorry for the late comment. Shouldn't we delete the `accountId,tokenId,` part? It seems that this will generate duplicate columns 🤔

Comment (petreze) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:111]: At first I was thinking about the same.. @david-bakin-sl thoughts on that?

The other option could be to remove `accountId` and `tokenId` from the `fieldFormatters` [here](https://github.com/hashgraph/hedera-services/blob/10918-token-associations-modular-dumper/hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java#L118-L119)

Comment (david-bakin-sl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/bbm/associations/TokenAssociationsDumpUtils.java:111]: Good catch.  I think just remove the `"accountId,tokenId,"+` here.

I knew it was going to be a problem asking you to write code with no way to test it.  But good code review counts, thanks Valentin!  (I should test it - but I can't run the rounds for technical reasons at this time.  I'll see if I can ask someone to test this - but the people who could do it are pretty busy right now on testing event rounds. 
 Even so don't hold up the approvals+merge for it.)

**Review by david-bakin-sl — APPROVED** [review]
LGTM!

**Review by vtronkov — APPROVED** [review]

**Review by agadzhalov — APPROVED** [review]
LGTM

**Review by jeromy-cannon — APPROVED** [review]

**Review by mhess-swl — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !
