### PR TITLE
fix: Remove HederaFileNumbers and HederaAccountNumbers

### LINKED ISSUE #8182: Remove HederaFileNumbers and HederaAccountNumbers

### PR DESCRIPTION
**Pull request by povolev15**
Remove HederaFileNumbers and HederaAccountNumbers, and using config instead

**Related issue(s)**:

Fixes #8182

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java [hunk 1]
```diff
@@ -90,13 +90,15 @@ public class EndOfStakingPeriodUpdaterTest {
     private WritableStakingInfoStore stakingInfoStore;
     private WritableNetworkStakingRewardsStore stakingRewardsStore;
 
+    public static final ConfigProvider DEFAULT_CONFIG_PROVIDER = HederaTestConfigBuilder.createConfigProvider();
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/EndOfStakingPeriodUpdaterTest.java:93]: Nit: 
```suggestion
    private static final ConfigProvider DEFAULT_CONFIG_PROVIDER = HederaTestConfigBuilder.createConfigProvider();
```
Can do in a future PR tho

**Review by mhess-swl — APPROVED** [review]

**Review by kimbor — APPROVED** [review]
lgtm!

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @povolev15 !
