### PR TITLE
Split `Scope` into `ExtWorldScope`, `ExtFrameScope`; complete `TransactionComponent`

### LINKED ISSUE #6487: Finish wiring `ContractService` with `HandleContextScope` impl
### Problem

A modularized `ContractService` will depend on several facilities in both `@HandleScope` and `@Singleton` scopes. This issue gives a stream-of-consciousness summary of these facilities, with brief descriptions of why they are needed.

`Name`s and descriptions are stylized, pointed at needed functionality but not necessarily its final form.

```[tasklist]
### Management helpers to enforce entity-agnostic policies
- [ ] `KeyManagement` for validating keys, detecting immutability sentinels, etc.
- [ ] `ExpirationManagement` for validating and performing auto-renew account changes and expiration changes.
- [ ] `AttributeManagement` for validating and updating memos and aliases.
```

```[tasklist]
### Network event callbacks
- [ ] `PropertiesChangeListener` to re-number the trailing 256 block hashes (if possible) after an update to file `0.0.121`, based on an authoritative `(blockNumber, blockHash)` pair provided via the [`contracts.knownBlockHash` property](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties#L76).
```

```[tasklist]
### Metric/clock facilities
- [ ] `MetricsManager` to register the `gasPerConsSec` running average with Platform metrics.
- [ ] `SystemClockListener` to register a listener for updating this metric each consensus second.
```

```[tasklist]
### Throttling facilities
- [ ] Pre-handle `ThrottleAccumulator` to report expected usage of both `gas` and `CryptoCreate` via `EthereumTransaction` lazy create.
- [ ] Post-handle `ThrottleFinalizer` to drain unused gas.
```

```[tasklist]
### Fee facilities
- [ ] `FeeCalculator` for computing cost of `gas` and synthetic `TransactionBody`'s dispatched from system contracts.
- [ ] `FeeCharging` for charging prorated storage fees at the end of the transaction, with the option to either itemize the fees in a separate child record or collapse them to the parent record.
```

```[tasklist]
### States facilities
- [ ] Includes a "journaled" `States` implementation with transactional checkpoints so deep EVM stacks do not trigger deep JVM call stacks when reading from EVM (or Hedera) state.
```

```[tasklist]
### Dispatching facility
- [ ] Accepts a "`SimpleKeySignatureVerification` strategy" that has access to: (1) The type of key being verified---account, admin, treasury, auto-renew account, mint, freeze, etc.; and (2) the option to delegate verification back to the top-level `SignatureMap` for a cryptographic key; and (3) the option to modify the `TransactionBody` being dispatched based on a verification result.
- [ ] Acts relative to a given `States` parameter, since transactional boundaries in the EVM stack and world state can change independently of dispatching child transactions.
- [ ] Produces records that appear in the record stream iff the provided States object commits the journal entries added at this transactional checkpoint.
- [ ] Supports dispatching transactions without creating a record, for internal EVM value transfers and alias mutations.
- [ ] Supports dispatching alias link/unlink operations that lack a corresponding HAPI `TransactionBody`.
- [ ] Supports dispatching transactions whose records are only externalized on success of the top-level Hedera transaction (for internal `CONTRACT_CREATION` calls that are later reverted).
```

```[tasklist]
### Record management facility
 - [ ] Ensures the hbar `TransferList` of the top-level record does not repeat custom fee adjustments (or storage rent payments!) that already appear in a following child record. (That is, recognizes the top-level record cannot just summarize the hbar balance changes present at the final `AccountStore.commit()`.)
 - [ ] Supports directly injecting items into the record stream without a corresponding dispatch (for the synthetic `ContractCreation` child record following an `EthereumTransaction` to the `0x0` address).
 - [ ] Provides access to the pending record file number for the current transaction, since this is required to implement `block.number`.
 - [ ] Signals whether the current transaction will begin a new record file (barring catastrophic failure during record streaming); and when the transaction does begin a new record file, provides access to the final running hash of the pending just-closed file, since this is required to implement `blockhash(block.number - 1)`.
 - [ ] Allows registering something like a `NewBlockListener` that is notified whenever a new block is created, to support answering `blockhash(block.number - n)`.
```

### Solution

Make the above facilities precise and implement them.

### Alternatives

_No response_

### LINKED ISSUE #7565: Add test scaffold for contract-file-token integration tests
### Problem

There are many interactions between the modularized `ContractService` and `TokenService` we'd like to test.

Unit tests can exercise particular interactions, but this is not satisfying.

End-to-end tests, however, add so many moving parts that it becomes a challenge to configure the desired inputs; and reason about the expected outputs.

### Solution

Create a simple test scaffold under `:hedera-app:itest` that can build a `HandleContext` from a `FakeHederaState` with well-known entities.

Then call the `ContractService` handlers with such `HandleContext`, and verify the changes to the `FakeHederaState` are as expected.

The expectations of this suite should be derived from the `mono-service` execution of the following spec:
```
      private HapiSpec reportErc721Operations() {
        final AtomicReference<Address> eddsaPartyAddress = new AtomicReference<>();
        final AtomicReference<Address> ecdsaCounterpartyAddress = new AtomicReference<>();
        final AtomicReference<Address> ecdsaOperatorAddress = new AtomicReference<>();
        final AtomicReference<Address> ecdsaTreasuryAddress = new AtomicReference<>();
        final var erc721 = "ERC721Full";
        final var ecdsaTreasury = "ecdsaTreasury";
        final var eddsaParty = "eddsaParty";
        final var ecdsaCounterparty = "ecdsaCounterparty";
        final var ecdsaOperator = "ecdsaOperator";
        final var aEcKey = "aEcKey";
        final var bEcKey = "bEcKey";
        final var cEcKey = "cEcKey";
        final var aEdKey = "aEdKey";

        return onlyDefaultHapiSpec("ReportErc721Operations")
                .given(
                        newKeyNamed(aEcKey).shape(SigControl.SECP256K1_ON),
                        newKeyNamed(bEcKey).shape(SigControl.SECP256K1_ON),
                        newKeyNamed(cEcKey).shape(SigControl.SECP256K1_ON),
                        newKeyNamed(aEdKey).shape(SigControl.ED25519_ON),
                        cryptoCreate(ecdsaTreasury)
                                .balance(ONE_HUNDRED_HBARS)
                                .key(aEcKey)
                                .advertisingCreation()
                                .withMatchingEvmAddress()
                                .exposingEvmAddressTo(address -> {
                                    ecdsaTreasuryAddress.set(address);
                                    System.out.println("  ➡️  " + address);
                                }),
                        getAccountInfo(ecdsaTreasury).logged(),
                        cryptoCreate(ecdsaCounterparty)
                                .key(bEcKey)
                                .advertisingCreation()
                                .withMatchingEvmAddress()
                                .exposingEvmAddressTo(address -> {
                                    ecdsaCounterpartyAddress.set(address);
                                    System.out.println("  ➡️  " + address);
                                }),
                        cryptoCreate(ecdsaOperator)
                                .key(cEcKey)
                                .advertisingCreation()
                                .withMatchingEvmAddress()
                                .exposingEvmAddressTo(address -> {
                                    ecdsaOperatorAddress.set(address);
                                    System.out.println("  ➡️  " + address);
                                }),
                        cryptoCreate(eddsaParty)
                                .key(aEdKey)
                                .advertisingCreation()
                                .exposingCreatedIdTo(id -> {
                                    eddsaPartyAddress.set(idAsHeadlongAddress(id));
                                    System.out.println("  ➡️  " + asHexedSolidityAddress(id));
                                }),
                        uploadInitCode(erc721),
                        // Mints NFT's with serial numbers 2, 3, 5, 8, 13
                        contractCreate(erc721)
                                .advertisingCreation()
                                .gas(GAS_TO_OFFER)
                                .payingWith(ecdsaTreasury))
                .when(
                        // Approve the eddsaParty to transfer the NFT's with serial number 2 and 3
                        sourcing(() -> contractCall(erc721, "approve", eddsaPartyAddress.get(), BigInteger.valueOf(2))
                                .payingWith(ecdsaTreasury)),
                        sourcing(() -> contractCall(erc721, "approve", eddsaPartyAddress.get(), BigInteger.valueOf(3))
                                .payingWith(ecdsaTreasury)),
                        // Approve the ecdsaOperator to transfer all NFT's
                        sourcing(() -> contractCall(erc721, "setApprovalForAll", ecdsaOperatorAddress.get(), true)
                                .payingWith(ecdsaTreasury)
                                .via("operatorApproval")),
                        // Transfer NFT with serial number 13 from ecdsaTreasury to ecdsaCounterparty via operator
                        // approval
                        sourcing(() -> contractCall(
                                        erc721,
                                        "safeTransferFrom",
                                        ecdsaTreasuryAddress.get(),
                                        ecdsaCounterpartyAddress.get(),
                                        BigInteger.valueOf(13))
                                .payingWith(ecdsaOperator)),
                        // Transfer NFT with serial number 3 from ecdsaTreasury to ecdsaCounterparty via specific
                        // approval
                        sourcing(() -> contractCall(
                                        erc721,
                                        "safeTransferFrom",
                                        ecdsaTreasuryAddress.get(),
                                        ecdsaCounterpartyAddress.get(),
                                        BigInteger.valueOf(3))
                                .payingWith(eddsaParty)),
                        // Directly transfer NFT with serial number 8 from ecdsaTreasury to eddsaPartyAddress
                        sourcing(() -> contractCall(
                                        erc721,
                                        "safeTransferFrom",
                                        ecdsaTreasuryAddress.get(),
                                        eddsaPartyAddress.get(),
                                        BigInteger.valueOf(8))
                                .payingWith(ecdsaTreasury)),
                        // Finally, transfer NFT with serial number 3 from ecdsaCounterparty to eddsaPartyAddress
                        sourcing(() -> contractCall(
                                        erc721,
                                        "safeTransferFrom",
                                        ecdsaCounterpartyAddress.get(),
                                        eddsaPartyAddress.get(),
                                        BigInteger.valueOf(3))
                                .payingWith(ecdsaCounterparty)))
                .then(getContractBytecode(erc721).exposingBytecodeTo(bytes -> {
                    try {
                        Files.write(Paths.get("Erc721Full.bin"), bytes);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }));
    }
```
where we have updated `TransitionRunner` [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/TransitionRunner.java#L126) to display storage as follows,
```
                if (function == ContractCall) {
                    final var app = AppsManager.APPS.get(new NodeId(0));
                    final var accounts = app.backingAccounts();
                    final var orderedIds = new TreeSet<>(HederaLedger.ACCOUNT_ID_COMPARATOR);
                    orderedIds.addAll(accounts.idSet());
                    orderedIds.forEach(id -> {
                        final var account = accounts.getRef(id);
                        if (account.isSmartContract()) {
                            final var storage = app.workingState().contractStorage();
                            final var firstKey = account.getFirstContractStorageKey();
                            System.out.println("Contract storage for 0.0." + id.getAccountNum() + ":");
                            System.out.println(IterableStorageUtils.joinedStorageMappings(firstKey, storage));
                        }
                    });
                }
```

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #6487 
 - Closes #7565

### CODE REVIEW

**Review by mhess-swl — APPROVED** [review]

**Review by lukelee-sl — APPROVED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java [hunk 1]
```diff
@@ -149,8 +153,18 @@ private HederaEvmTransactionResult safeCommit(
...
 
-    private record InvolvedParties(
-            @NonNull HederaEvmAccount sender, @Nullable HederaEvmAccount relayer, @NonNull Address receiverAddress) {}
+    private HederaEvmTransactionResult commitResourceExhaustion(
+            @NonNull final HederaEvmTransaction transaction,
+            @NonNull final HederaWorldUpdater updater,
+            @NonNull final HederaEvmContext context,
+            @NonNull final ResponseCodeEnum reason,
+            @NonNull final Configuration config) {
+        // Note these calls cannot fail, or processTransaction() above would have aborted right away
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:162]: (Example of a good comment needed because it is not true that "good code documents itself" (always). This is good code but there are semantics that are inexpressible in most programming languages.)

File: hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java [hunk 2]
```diff
@@ -40,6 +40,8 @@ public record ContractsConfig(
         // "TokenAssociateToAccount,TokenDissociateFromAccount,TokenFreezeAccount,TokenUnfreezeAccount,TokenGrantKycToAccount,TokenRevokeKycFromAccount,TokenAccountWipe,TokenBurn,TokenDelete,TokenMint,TokenUnpause,TokenPause,TokenCreate,TokenUpdate,ContractCall,CryptoTransfer") Set<HederaFunctionality> allowSystemUseOfHapiSigs,
         @ConfigProperty(defaultValue = "0") @NetworkProperty long maxNumWithHapiSigsAccess,
         // @ConfigProperty(defaultValue = "") Set<Address> withSpecialHapiSigsAccess,
+        @ConfigProperty(value = "nonces.externalization.enabled", defaultValue = "true") @NetworkProperty
```
Comment (david-bakin-sl) [inline hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java:43]: (Impossible to tell if my previous comment got disappeared when this file got updated:)

(I need to understand the new config system better, because: Why do many of these properties not have a `value` (i.e., external name)?)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/CallOutcome.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import static com.hedera.hapi.node.base.ResponseCodeEnum.SUCCESS;
+import static java.util.Objects.requireNonNull;
+
+import com.hedera.hapi.node.base.ContractID;
+import com.hedera.hapi.node.base.ResponseCodeEnum;
+import com.hedera.hapi.node.contract.ContractFunctionResult;
+import edu.umd.cs.findbugs.annotations.NonNull;
+import edu.umd.cs.findbugs.annotations.Nullable;
+
+public record CallOutcome(@Nullable ContractFunctionResult result, @NonNull ResponseCodeEnum status) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/CallOutcome.java:28]: Nice record

**Review by david-bakin-sl — COMMENTED** [review]
Submitted pending comments now as you're actively updating this.  Got 36/123 will continue later.

File: build-logic/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts [hunk 4]
```diff
@@ -187,6 +187,19 @@ testing {
                 }
             }
         }
+
+        // Add the X-test task for executing "cross-service" tests
+        register<JvmTestSuite>("xtest") {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply build-logic/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts:192]: True, Gradle plugins ime are usually quite opinionated and do a bunch of auto-configuration. Convenient, but it does lend an air of mystery to the build artifacts...

File: hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/numbers/FakeHederaNumbers.java [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+        return 60;
+    }
+
+    @Override
+    public boolean isSuperuser(long num) {
+        return (num == 2) || (num == 50);
+    }
+
+    @Override
+    public long stakingRewardAccount() {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/numbers/FakeHederaNumbers.java:71]: Any `0.0.X` with `X <= 750` can be updated using the network admin accounts, **even if `0.0.X`'s key doesn't sign the `CryptoUpdate` transaction**. Higher-numbered accounts can only be updated if their key signs.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java [hunk 6]
```diff
@@ -17,27 +17,29 @@
...
     }
 
     @Override
     public void registerSchemas(@NonNull final SchemaRegistry registry) {
         registry.register(new ContractSchema());
     }
 
-    public HederaEvmTransactionProcessor transactionProcessor() {
-        return transactionProcessor;
+    public ContractHandlers handlers() {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java:42]: There's definitely a learning curve...I have a modest 182-card deck of [Anki flashcards](https://apps.ankiweb.net/) just for Dagger2 concepts. 😳 

But yes, afaik, unless we switch the `HederaInjectionComponent`'s scope to a custom, non-`@Singleton`  annotation, we won't be able to use the natural Dagger2 idiom of,
```
@Component(
        modules = {LegacyMonoInjectionModule.class, ...}
        dependencies = {ContractServiceComponent.class})
public interface HederaInjectionComponent {
```
...which is definitely the preferred way to make the `ContractServiceComponent`'s provision methods part of the app's binding graph.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java [hunk 7]
```diff
@@ -69,6 +70,9 @@ public TransactionProcessor(
         this.contractCreation = requireNonNull(contractCreation);
     }
 
+    private record InvolvedParties(
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java:73]: Here `sender` **is** `tx.origin`; but it's called `sender` everywhere in `mono-service` so I thought people might expect that. Added comments as suggested.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/QueryModule.java [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+    @Provides
+    @QueryScope
+    static Configuration provideConfiguration(@NonNull final QueryContext context) {
+        return requireNonNull(context).configuration();
+    }
+
+    @Provides
+    @QueryScope
+    static Instant provideConsensusTime() {
+        return Instant.now();
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/QueryModule.java:47]: Switched this `Instant` to be bound in the `QueryComponent.Factory.create()` method.

File: hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java:43]: I think we only need to specify `value` if the property's name can't be constructed by dot-joining the config class's `@ConfigData` annotation value with the Java field name of the property.

So for example, given:
```
@ConfigData("contracts")
...
@ConfigProperty(defaultValue = "0") @NetworkProperty long maxNumWithHapiSigsAccess,
```
this automatically implies a property of,
```
contracts.maxNumWithHapiSigsAccess=0
```

But this nonce externalization property doesn't follow this pattern.

File: hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/numbers/FakeHederaNumbers.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/numbers/FakeHederaNumbers.java:71]: hmmm, ok, and I guess there's a particularly small and well-known set of admin accounts

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+     */
+    void removeSlot(@NonNull SlotKey key);
+
+    /**
+     * Puts the given {@link SlotValue} for the given {@link SlotKey}.
+     *
+     * @param key the {@link SlotKey} to put the {@link SlotValue} for
+     * @param value the {@link SlotValue} to put
+     */
+    void putSlot(@NonNull SlotKey key, @NonNull SlotValue value);
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java:60]: If you put zeros does this turn into a `removeSlot` or should you not do that?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java [hunk 10]
```diff
@@ -0,0 +1,93 @@
...
+ * An intermediary that manages access to the slot and bytecode key/value states.
+ */
+public interface ContractStateStore {
+    /**
+     * Returns the {@link Bytecode} for the given contract number.
+     *
+     * @param contractNumber the contract number to get the {@link Bytecode} for
+     * @return the {@link Bytecode} for the given contract number
+     */
+    Bytecode getBytecode(@NonNull EntityNumber contractNumber);
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java:37]: I notice `SlotKey` (a BESU function) takes the contract as a `long`, IOW the EVM address.  Here we're using a Hedera `EntityNumber`.  Will callers have to go to any trouble here, that is, will they have the evm address and have to translate it themselves?  If so, maybe a default method could be here to do the translation.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java [hunk 11]
```diff
@@ -0,0 +1,93 @@
...
+     */
+    @Nullable
+    SlotValue getOriginalSlotValue(@NonNull SlotKey key);
+
+    /**
+     * Returns the number of slots.
+     *
+     * @return the number of slots
+     */
+    long getNumSlots();
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java:92]: Current number of slots taking into account added but especially _deleted_, right?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java [hunk 12]
```diff
@@ -87,72 +87,90 @@ public class DispatchingEvmFrameState implements EvmFrameState {
     private static final String TOKEN_CALL_REDIRECT_CONTRACT_BINARY =
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java:87]: It would make me happy to see a comment saying where this magical string came from.  Even better, if the solidity source were checked in somewhere (is it?).

Separately, I wonder if it occurred to anyone that the replacement placeholder need not actually be `fefe...` or any other hex characters, or even the _correct length_ but something that would stand out.  Like `$$TOKEN_ADDRESS$$` or whatever it is.  In fact `%s` would stand out and turn this into a formatting string.  Oh well.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java [hunk 13]
```diff
@@ -87,72 +87,90 @@ public class DispatchingEvmFrameState implements EvmFrameState {
...
+        // Ensure we don't change any prev/next keys until the base commit
         final var slotValue = new SlotValue(
                 tuweniToPbjBytes(requireNonNull(value)),
                 oldSlotValue == null ? com.hedera.pbj.runtime.io.buffer.Bytes.EMPTY : oldSlotValue.previousKey(),
                 oldSlotValue == null ? com.hedera.pbj.runtime.io.buffer.Bytes.EMPTY : oldSlotValue.nextKey());
-        storage.put(slotKey, slotValue);
+        // We don't call remove() here when the new value is zero, again because we
+        // want to preserve the prev/next key information until the base commit; only
+        // then will we remove the zeroed out slot from the K/V state
+        contractStateStore.putSlot(slotKey, slotValue);
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java:112]: Ah.  This answers that question then about `removeSlot`|`putSlot` above: `putSlot` puts zeros.  But makes the question of `getNumSlots` more interesting.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java [hunk 14]
```diff
@@ -87,72 +87,90 @@ public class DispatchingEvmFrameState implements EvmFrameState {
...
+    /**
+     * {@inheritDoc}
+     */
     @Override
     public @NonNull List<StorageAccesses> getStorageChanges() {
         final Map<Long, List<StorageAccess>> modifications = new TreeMap<>();
-        storage.modifiedKeys().forEach(slotKey -> modifications
+        contractStateStore.getModifiedSlotKeys().forEach(slotKey -> modifications
                 .computeIfAbsent(slotKey.contractNumber(), k -> new ArrayList<>())
                 .add(StorageAccess.newWrite(
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java:141]: The two transforms pbj<->besu(tuweni) could be pulled out into a matched set of methods.

**Review by david-bakin-sl — COMMENTED** [review]
Making progress.  80 of 124.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceModule.java [hunk 15]
```diff
@@ -58,16 +61,19 @@ public interface ServiceModule {
 
     @Binds
     @IntoMap
+    @Singleton
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceModule.java:64]: In this case we do need the `@Singleton` annotation, because this binding is part of a "multibound collection"; that is, a
```
Map<HederaEvmVersion, TransactionProcessor> processors
```

The object that's created by Dagger when you request a multibound set or map will have the scope of the component that you request it from.

Since we're "requesting" this `Map<HederaEvmVersion, TransactionProcessor>` [here](https://github.com/hashgraph/hedera-services/blob/06487-scope-impl/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/ContextTransactionProcessor.java#L66), inside a `@TransactionScope` component, without the `@Singleton` annotation here, each of its three `TransactionProcessor`'s would be re-created for every transaction and new `TransactionComponent`.

(Arguably we should avoid re-creating this `Map` on every transaction by injecting it into e.g. `ContractCreateHandler` and then adding a `@BindsInstance` parameter to the `TransactionComponent.Factory.create()` method...but this seems like premature optimization. 😁)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/RootProxyWorldUpdater.java [hunk 16]
```diff
@@ -64,21 +72,53 @@ public BaseProxyWorldUpdater(
...
+        storageSizeValidator.assertValid(sizeEffects.finalSlotsUsed(), hederaOperations, sizeEffects.sizeChanges());
         // Charge rent for each increase in storage size
         chargeRentFor(sizeEffects);
         // "Rewrite" the pending storage changes to preserve per-contract linked lists
-        storageManager.rewrite(scope, changes, sizeEffects.sizeChanges(), scopedStorage());
+        storageManager.rewrite(hederaOperations, changes, sizeEffects.sizeChanges(), hederaOperations.getStore());
 
+        // We now have an apparently valid change set, and want to capture some summary
+        // information for the Hedera record
+        createdContractIds = hederaOperations.createdContractIds();
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/RootProxyWorldUpdater.java:91]: These two methods on `HederaOperations` aren't actually annotated to return `@NonNull` (which comes up below).

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ScopedEvmFrameStateFactory.java [hunk 17]
```diff
@@ -0,0 +1,46 @@
...
+
+    @Inject
+    public ScopedEvmFrameStateFactory(
+            @NonNull final HederaOperations hederaOperations, @NonNull final HederaNativeOperations extFrameScope) {
+        this.hederaOperations = Objects.requireNonNull(hederaOperations);
+        this.extFrameScope = Objects.requireNonNull(extFrameScope);
+    }
+
+    @Override
+    public EvmFrameState get() {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ScopedEvmFrameStateFactory.java:43]: return value annotation?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableContractStateStore.java [hunk 18]
```diff
@@ -0,0 +1,107 @@
...
+        requireNonNull(states);
+        this.storage = states.get(ContractSchema.STORAGE_KEY);
+        this.bytecode = states.get(ContractSchema.BYTECODE_KEY);
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    @Override
+    public Bytecode getBytecode(@NonNull final EntityNumber contractNumber) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableContractStateStore.java:48]: (I don't want to be the `@Nullable` guy - that's not really my code review schtick.  I've got other things to do - complain about naming, make irrelevant comments, compare Java to C++, etc. So I won't mention them anymore.)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java [hunk 19]
```diff
@@ -66,6 +67,20 @@ public static List<ContractLoginfo> pbjLogsFrom(@NonNull final List<Log> logs) {
         return pbjLogs;
     }
 
+    /**
+     * Wraps the first 32 bytes of the given SHA-384 {@link com.swirlds.common.crypto.Hash hash} in a Besu {@link Hash}.
+     *
+     * @param sha384Hash the SHA-384 hash
+     * @return the first 32 bytes as a Besu {@link Hash}
+     */
+    public static org.hyperledger.besu.datatypes.Hash ethHashFrom(
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java:76]: (Java's inability to let you define type aliases is sad.  The other time you really want it is for naming a container of some complicated type.)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java (hunk 11 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java:92]: True, although we never call `remove()` on the underlying key-value store for contract storage until the root updater's `commit()`.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java [hunk 20]
```diff
@@ -66,6 +67,20 @@ public static List<ContractLoginfo> pbjLogsFrom(@NonNull final List<Log> logs) {
...
+            @NonNull final com.hedera.pbj.runtime.io.buffer.Bytes sha384Hash) {
+        requireNonNull(sha384Hash);
+        final byte[] prefixBytes = new byte[32];
+        sha384Hash.getBytes(0, prefixBytes, 0, prefixBytes.length);
+        return org.hyperledger.besu.datatypes.Hash.wrap(Bytes32.wrap(prefixBytes));
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/ConversionUtils.java:81]: I don't _think_ there's any byte copying going on in here - just wrapping in other classes.  The copy takes place on the line above.  (And I'm not sure why even _that_ copy is needed.)

**Review by david-bakin-sl — COMMENTED** [review]
87/124 and chugging along ....

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceModule.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceModule.java:65]: I have to think about this, and seriously start playing with Dagger.  It sure is convenient - I totally get that - but at the same time there's a bit of "action at a distance" going on that's kind of spooky, because invisible.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java [hunk 21]
```diff
@@ -146,6 +170,32 @@ public static HederaEvmTransactionResult resourceExhaustionFrom(
                 null);
     }
 
+    private ContractFunctionResult asSuccessResultForCommitted(@NonNull final RootProxyWorldUpdater updater) {
+        final var createdIds = updater.getCreatedContractIds();
+        return ContractFunctionResult.newBuilder()
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java:175]: No, just vanilla builders.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java (hunk 9 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java:66]: Added comment here as well, seems you answered this below tho.

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/TransactionProcessorTest.java [hunk 22]
```diff
@@ -16,13 +16,43 @@
 
 package com.hedera.node.app.service.contract.impl.test.exec;
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/TransactionProcessorTest.java:17]: Code coverage shows missed L223 in `TransactionProcessor.computeInvolvedParties` ([equivalent link](https://github.com/hashgraph/hedera-services/blob/0f10af45473ac79c98b609fc180dae8c659daa70/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionProcessor.java#L203)) which looks like it might be interesting to cover.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java (hunk 10 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ContractStateStore.java:37]: Hmm I'm not quite sure. It might be hard to know until the `HandleContext` API is nailed down and we've sorted out exactly which of these interfaces even need to exist. 🤔

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaNativeOperationsTest.java [hunk 23]
```diff
@@ -0,0 +1,94 @@
...
+
+    private HandleHederaNativeOperations subject;
+
+    @BeforeEach
+    void setUp() {
+        subject = new HandleHederaNativeOperations(context);
+    }
+
+    @Test
+    void getAccountNotImplemented() {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaNativeOperationsTest.java:44]: Great idea! As each method gets implemented something in this test _fails_ and then you're reminded to write the darn test (if you haven't already). I will remember this.

**Review by david-bakin-sl — COMMENTED** [review]
102/123 you're handling comments faster than I can write them ...

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java (hunk 21 above)
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java:175]: Given the number of fields I wonder if it's worth doing (in general)? (I don't think I've seen it anywhere else, just asking. There's a lot of fields, easy to miss one.)

**Review by david-bakin-sl — APPROVED** [review]
You know what? I'm pooped.  20 tests to go.  But I checked the unit test coverage and it's terrific as usual (just a few aren't 100% - I commented on one).  So: Excellent PR, LGTM!

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java (hunk 12 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java:87]: Luke showed me that this redirect contract comes from [HIP-719](https://hips.hedera.com/hip/hip-719) - perhaps a comment pointing there, please?

Comment (Nana-EC) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/DispatchingEvmFrameState.java:87]: Well it actually precedes HIP 719 (probably HIP 376 in 0.26) but HIP 719 is the first place it's laid out properly.
It essentially fuels the ability to treat an HTS token like an ERC token.
So in contract you can omit the tokenAddress as a parameter because you call the contract that "lives" at the token address.
That redirect contract binary picks it up and essentially sets the address as the 1st param in whatever call is being made
e.g. `<htsTokenAddres>.allowance(owner, spender)` =(redirect)=> `IHederaTokenService.allowance(htsTokenAddress, owner, spender)`

**Review by david-bakin-sl — APPROVED** [review]
LGTM

**Review by david-bakin-sl — APPROVED** [review]
Reiterating LGTM.  (Feel free to close conversations if you need to before merge.)

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by jeromy-cannon — APPROVED** [review]

**Review by netopyr — APPROVED** [review]
LGTM in regards to `hedera-base`

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java [hunk 24]
```diff
@@ -185,7 +185,7 @@ public Hedera(@NonNull final ConstructableRegistry constructableRegistry) {
         // FUTURE: Use the service loader framework to load these services!
         this.servicesRegistry = new ServicesRegistryImpl(Set.of(
                 new ConsensusServiceImpl(),
-                new ContractServiceImpl(),
+                CONTRACT_SERVICE,
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java:188]: I needed a way to decouple the `ContractServiceComponent`'s binding graph from the `HederaInjectionComponent` and this was just the most convenient.

Agreed, we should discuss replacing the use of `@Singleton` on `HederaInjectionComponent` with a custom annotation so we can use the service components as Dagger2 "component dependencies".

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java [hunk 25]
```diff
@@ -101,10 +105,10 @@ public ReadableStoreFactory(@NonNull final HederaState state) {
      * Create a new store given the store's interface. This gives read-only access to the store.
      *
      * @param storeInterface The store interface to find and create a store for
-     * @param <C> Interface class for a Store
+     * @param <C>            Interface class for a Store
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java:121]: Afaict spotless does insert this spacing. 🤔
