### PR TITLE
Error handling for penalty payments

### LINKED ISSUE #8686: Many tests fail with UNKNOWN status
Many tests fail with UNKNOWN status. The main issue is that we do not handle failed penalty charges correctly.

### PR DESCRIPTION
**Pull request by netopyr**
This change introduces proper error handling while we charge penalties in the `HandleWorkflow`.

Closes #8686

### CODE REVIEW

**Review by vtronkov — APPROVED** [review]

**Review by georgi-l95 — APPROVED** [review]
LGTM

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 1]
```diff
@@ -348,12 +352,22 @@ private void handleUserTransaction(
...
+                try {
+                    final var penaltyPayerID =
+                            validationResult.status() == NODE_DUE_DILIGENCE_FAILURE ? creator.accountId() : payer;
+                    final var penaltyFee = new Fees(fees.nodeFee(), fees.networkFee(), 0L);
+                    feeAccumulator.charge(penaltyPayerID, penaltyFee);
+                } catch (HandleException ex) {
+                    final var identifier = validationResult.status == NODE_DUE_DILIGENCE_FAILURE
+                            ? "node " + creator.nodeId()
+                            : "account " + payer;
+                    logger.error(
```
Comment (povolev15) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:365]: why do we log it and not throw

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 2]
```diff
@@ -381,7 +395,15 @@ private void handleUserTransaction(
             logger.error("An unexpected exception was thrown during handle", e);
             rollback(ResponseCodeEnum.FAIL_INVALID, stack, recordListBuilder);
             if (payer != null && fees != null) {
-                feeAccumulator.charge(payer, fees);
+                try {
+                    feeAccumulator.charge(payer, fees);
+                } catch (HandleException chargeException) {
+                    logger.error(
+                            "Unable to charge account {} a penalty after an unexpected exception {}. Cause of the failed charge:",
+                            payer,
```
Comment (povolev15) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:403]: same here

**Review by povolev15 — APPROVED** [review]
other than the 2 comments LGTM

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 2 above)
Comment (povolev15) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:403]: What does stop us from logging and throwing it?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:365]: The `TransactionReceipt` would contain the status `FAIL_INVALID` instead of the more specific error code that is available here. What would we gain if we threw an `Exception` here?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 2 above)
Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:403]: As written above, an `Exception` would skip creating and storing the `TransactionReceipt`, i.e., a user would not be able to see that the transaction failed.

**Review by rbair23 — APPROVED** [review]
