### PR TITLE
chore: only override Netty defaults on non-`DEV` profile; other fixes

### LINKED ISSUE #10637: Diagnose and enable/fix remaining disabled `HapiSpec`s
### Problem

We need to relocate/fix/enable the below `HapiSpec`s as `@HapiTest`s:

## crypto (2)

_NftTransferSuite_
 - [x] `transferNfts()`

_TxnReceiptRegression_
 - [x] `receiptUnavailableAfterCacheTtl()`
## smart_contract (10)

_TraceabilitySuite_
 - [x] `ethereumLazyCreateExportsExpectedSidecars()`
 - [x] `traceabilityE2EScenario16()`
 - [x] `traceabilityE2EScenario19()`
 - [x] `hollowAccountCreate2MergeExportsExpectedSidecars()`
 - [x] `traceabilityE2EScenario14()`
 - [x] `traceabilityE2EScenario15()`
 - [x] `traceabilityE2EScenario20()`
 - [x] `traceabilityE2EScenario13()`
 - [x] `assertSidecars()`

_SigningReqsSuite_
 - [x] `autoRenewAccountCanUseLegacySigActivationIfConfigured()`
## time_consuming (12)

_SteadyStateThrottlingCheck_
 - [x] `checkBalanceQps()`
 - [x] `checkTps()`
 - [x] `checkCustomNetworkTps()`

_StakingSuite_
 - [x] `getInfoQueriesReturnsPendingRewards()`
 - [x] `zeroRewardEarnedWithZeroWholeHbarsStillSetsSASOLARP()`
 - [x] `evenOneTinybarChangeInIndirectStakingAccountTriggersStakeeRewardSituation()`
 - [x] `rewardPaymentsNotRepeatedInSamePeriod()`
 - [x] `rewardsWorkAsExpected()`
 - [x] `endOfStakingPeriodRecTest()`
 - [x] `secondOrderRewardSituationsWork()`
 - [x] `losingEvenAZeroBalanceStakerTriggersStakeeRewardSituation()`
 - [x] `rewardsWorkAsExpectedWithReceiverSigRequired()`
## misc (56)

_ScheduleSignSpecs_
 - [x] `suiteCleanup()`
 - [x] `signFailsDueToDeletedExpiration()`
 - [x] `sharedKeyWorksAsExpected()`
 - [x] `overlappingKeysTreatedAsExpected()`
 - [x] `triggersUponAdditionalNeededSig()`
 - [x] `reductionInSigningReqsAllowsTxnToGoThroughWithRandomKey()`
 - [x] `retestsActivationOnSignWithEmptySigMap()`
 - [x] `triggersUponFinishingPayerSig()`
 - [x] `receiverSigRequiredNotConfusedByOrder()`
 - [x] `suiteSetup()`
 - [x] `addingSignaturesToExecutedTxFails()`

_ScheduleCreateSpecs_
 - [x] `doesntTriggerUntilPayerSigns()`

_UtilScalePricingCheck_
 - [x] `nftPriceScalesWithUtilization()`

_ScheduleRecordSpecs_
 - [x] `canScheduleChunkedMessages()`
 - [x] `canonicalScheduleOpsHaveExpectedUsdFees()`
 - [x] `noFeesChargedIfTriggeredPayerIsInsolvent()`
 - [x] `noFeesChargedIfTriggeredPayerIsUnwilling()`

_ScheduleDeleteSpecs_
 - [x] `deletingExecutedIsPointless()`

_DuplicateManagementTest_
 - [x] `usesUnclassifiableIfNoClassifiableAvailable()`
 - [x] `hasExpectedDuplicates()`
 - [x] #10650

_CostOfEverythingSuite_
 - [x] `miscContractCreatesAndCalls()`
 - [x] `canonicalScheduleOpsHaveExpectedUsdFees()`

_RecordCreationSuite_
 - [x] `submittingNodeChargedNetworkFeeForLackOfDueDiligence()`

_ScheduleExecutionSpecStateful_
 - [x] `suiteCleanup()`
 - [x] `executionWithTokenTransferListSizeExceedFails()`
 - [x] `scheduledUniqueMintFailsWithNftsDisabled()`
 - [x] `scheduledBurnWithInvalidTokenThrowsUnresolvableSigners()`
 - [x] `scheduledUniqueBurnFailsWithNftsDisabled()`
 - [x] `executionWithTransferListWrongSizedFails()`

_ScheduleExecutionSpecs_
 - [x] `executionWithInvalidAccountAmountsFails()`
 - [x] `scheduledBurnFailsWithInvalidTxBody()`
 - [x] `executionWithCustomPayerButNoFundsFails()`
 - [x] `scheduledXferFailingWithRepeatedTokenIdPaysServiceFeeButNoImpact()`
 - [x] `scheduledPermissionedFileUpdateWorksAsExpected()`
 - [x] `congestionPricingAffectsImmediateScheduleExecution()`
 - [x] `executionWithCustomPayerWorks()`
 - [x] `scheduledFreezeWithUnauthorizedPayerFails()`
 - [x] `scheduledMintFailsWithInvalidTxBody()`
 - [x] `scheduledXferFailingWithEmptyTokenTransferAccountAmountsPaysServiceFeeButNoImpact()`
 - [x] `scheduledSubmitThatWouldFailWithTopicDeletedCannotBeSigned()`
 - [x] `executionWithDefaultPayerButAccountDeletedFails()`
 - [x] `executionWithDefaultPayerButNoFundsFails()`
 - [x] `suiteCleanup()`
 - [x] `executionWithCustomPayerButAccountDeletedFails()`
 - [x] `executionWithCustomPayerAndAdminKeyWorks()`
 - [x] `scheduledPermissionedFileUpdateUnauthorizedPayerFails()`
 - [x] `executionWithDefaultPayerWorks()`
 - [x] `scheduledFreezeWorksAsExpected()`
 - [x] `executionWithCustomPayerWhoSignsAtCreationAsPayerWorks()`
 - [x] `suiteSetup()`
 - [x] `scheduledXferFailingWithNonNetZeroTokenTransferPaysServiceFeeButNoImpact()`
 - [x] `scheduledSystemDeleteWorksAsExpected()`
 - [x] `scheduledMintFailsWithInvalidAmount()`
 - [x] `scheduledBurnForUniqueFailsWithInvalidAmount()`

_LeakyContractTestsSuite_
 - [x] `etx026AccountWithoutAliasCanMakeEthTxnsDueToAutomaticAliasCreation()`

### Solution

Do this.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #10637
 - As per mod-service, only override Netty server defaults if active profile is not `DEV`.
    * This lets us enable `SteadyStateThrottleCheck` and get stable success with a max allowed deviation of 7% from nominal TPS over the 3-minute test period.
 - Avoids a possible unhandled exception in `SynchronizedThrottleAccumulator` in which thread scheduling effects could make `Instant.now()` appear to go backward in time.
 - Restores an accidentally removed call to `shutdownChannels()` in `HapiApiClients`.
 - Makes `NONDETERMINISTIC_NONCE` a default `SnapshotMatchMode` when running in a Linux environment (mostly accurate approximation for "when running in CI").
 - Adds `NONDETERMINISTIC_TRANSACTION_FEES` to `ExtCodeCopyOperationSuite.verifiesExistence()`.
 - Stabilizes `NftTransferSuite` by submitting fewer concurrent operations (maybe not needed with `DEV` profile change above, but the test doesn't offer any more functional test coverage either way).

### CODE REVIEW

**Review by iwsimon — APPROVED** [review]
LGTM

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/SteadyStateThrottlingCheck.java [hunk 1]
```diff
@@ -231,7 +225,7 @@ final HapiSpec checkCustomNetworkTps(
                 }));
     }
 
-    @HapiTest
+    @BddMethodIsNotATest
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/SteadyStateThrottlingCheck.java:228]: This still doesnt work ?

**Review by povolev15 — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! tyvm @tinker-michaelj 🎉

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/SteadyStateThrottlingCheck.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/SteadyStateThrottlingCheck.java:228]: This method is a factory for `HapiSpec`'s, but not itself a directly runnable `HapiSpec`.
