### PR TITLE
chore: Fix otter state initialization

### LINKED ISSUE #22240: ISS during Otter test replay
Recent addition to Otter framework (https://github.com/hiero-ledger/hiero-consensus-node/pull/22177) uncovered an issue. In some cases the `LargeStateTests#largeRestartTest` results in ISS. We need to figure out why exactly it's happening.

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

This PR fixes the state initialization code in the otter framework.

**Related issue(s)**:

Fixes #22240

### CODE REVIEW

File: platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/platform/ConsensusNodeManager.java [hunk 1]
```diff
@@ -132,7 +132,7 @@ public ConsensusNodeManager(
         // Set active the roster
         final ReadablePlatformStateStore store =
                 new ReadablePlatformStateStore(state.getReadableStates(PlatformStateService.NAME));
-        RosterUtils.setActiveRoster(state, activeRoster, store.getRound() + 1);
+        RosterUtils.setActiveRoster(state, activeRoster, store.getRound());
```
Comment (poulok) [inline platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/platform/ConsensusNodeManager.java]: This change is incorrect. The `+ 1` is necessary. I am confused how the `StartFromStateTest` is passing with this change. It makes me think there is another bug somewhere.

Comment (netopyr) [reply platform-sdk/consensus-otter-docker-app/src/testFixtures/java/org/hiero/consensus/otter/docker/app/platform/ConsensusNodeManager.java]: Reverted the changes and created a ticket to investigate this: https://github.com/hiero-ledger/hiero-consensus-node/issues/22318
