### PR TITLE
fix: Fix bug increasing network size from a single node network

### LINKED ISSUE #22262: Allow growing a single node network to a multiple node network
It is currently not possible to run a single node network, then add nodes later with an upgrade. The event validator does a special check for single node networks that allows the other parent to be the same as the self parent. We create such events because of a consensus quirk with single node networks. The reason the network cannot be grown to more than 1 node is because this check does not evaluate the correct roster when determining if the event was created with a size 1 roster.

The best solution is to create single network events properly - with no other parent - and add the other parent in the Consensus Engine right before adding it to the consensus algorithm. When the consensus algorithm is enhanced to not need this extra step, it can be removed. Meanwhile, the events will be created and validated properly.

### PR DESCRIPTION
**Pull request by poulok**
**Related issue(s)**:
Fixes #22262

### CODE REVIEW

File: platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java [hunk 1]
```diff
@@ -271,11 +271,8 @@ private PlatformEvent signEvent(final UnsignedEvent event) {
      */
     @NonNull
     private UnsignedEvent createEventForSizeOneNetwork() {
-        // There is a quirk in size 1 networks where we can only
-        // reach consensus if the self parent is also the other parent.
-        // Unexpected, but harmless. So just use the same event
-        // as both parents until that issue is resolved.
-        return buildAndProcessEvent(lastSelfEvent);
+        // In a network of size one, we create events without other parents.
+        return buildAndProcessEvent(null);
```
Comment (netopyr) [inline platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java]: Nit: Do we really want to keep the method `createEventForSizeOneNetwork`?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java [hunk 2]
```diff
@@ -97,14 +107,44 @@ public EventImpl linkEvent(@NonNull final PlatformEvent event) {
...
+                    .toList();
+        } else {
+            // There is a quirk in size 1 networks where we can only
+            // reach consensus if the self-parent is also the other parent.
+            // Unexpected, but harmless. So just use the same event
+            // as the other parent until that issue is resolved.
+            return Stream.of(event.getSelfParent(), event.getSelfParent())
+                    .map(ed -> getParentToLink(event, ed))
+                    .filter(Objects::nonNull)
+                    .toList();
```
Comment (netopyr) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java]: Nit: I think a more traditional approach without `Stream` would be easier to understand.

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/linking/ConsensusLinkerTests.java [hunk 3]
```diff
@@ -51,8 +55,8 @@ class ConsensusLinkerTests {
 
     private FakeTime time;
 
-    private final NodeId cr0 = NodeId.of(0);
-    private final NodeId cr1 = NodeId.of(1);
+    private NodeId cr0 = NodeId.of(0);
+    private NodeId cr1 = NodeId.of(1);
```
Comment (netopyr) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/linking/ConsensusLinkerTests.java]: Nit: Are these defaults ever used? If not, I would remove them.

File: platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/addressbook/RosterHistoryBuilder.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+import java.util.List;
+import java.util.Map;
+import org.hiero.consensus.model.hashgraph.ConsensusConstants;
+import org.hiero.consensus.roster.RosterHistory;
+import org.hiero.consensus.roster.RosterUtils;
+
+/**
+ * A builder for {@link RosterHistory} for use in tests.
+ */
+public class RosterHistoryBuilder {
```
Comment (netopyr) [inline platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/addressbook/RosterHistoryBuilder.java]: Nit: Does it make sense to move this to production code? For instance `GuiEventStorage` could use it.

**Review by netopyr — APPROVED** [review]
LGTM - thanks @poulok

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java [hunk 5]
```diff
@@ -62,9 +72,12 @@ public class ConsensusLinker {
      * Constructor
      *
      * @param logsAndMetrics logs and collects metrics in case of linking issues
+     * @param rosterHistory the roster history
      */
-    public ConsensusLinker(@NonNull final LinkerLogsAndMetrics logsAndMetrics) {
-        this.logsAndMetrics = logsAndMetrics;
+    public ConsensusLinker(
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java]: I don't like the idea of the linker needing a roster history just for this exception. I would rather go with something outside the linker that just sets the other parent to be the same as the self parent

File: platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java (hunk 1 above)
Comment (poulok) [reply platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/tipset/TipsetEventCreator.java]: Removed. I initially wanted to keep it, but I'm fine removing it too.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java (hunk 2 above)
Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java]: This is already in main, I only moved it. But the move is reverted now.

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/linking/ConsensusLinkerTests.java (hunk 3 above)
Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/linking/ConsensusLinkerTests.java]: Yes they are used. This file has been reverted.

File: platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/addressbook/RosterHistoryBuilder.java (hunk 4 above)
Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/addressbook/RosterHistoryBuilder.java]: No longer needed so I deleted this class

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java (hunk 5 above)
Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/linking/ConsensusLinker.java]: Changed approach to fixing the consensus quirk

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java [hunk 6]
```diff
@@ -1198,6 +1202,24 @@ private long round(@Nullable final EventImpl x) {
...
+     * @return true if the creator of this event has a supermajority of weight in the roster
+     */
+    private boolean hasSuperMajority(@Nullable final EventImpl x) {
+        if (x == null) {
+            return false;
+        }
+        if (!rosterIndicesMap.containsKey(x.getCreatorId().id())) {
+            return false;
+        }
+        final int memberIndex = rosterIndicesMap.get(x.getCreatorId().id());
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java]: nit: these are 2 lookups, if we just do a `get()` and check for null then its a single lookup

Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java]: good call, fixed

**Review by lpetrovic05 — APPROVED** [review]

File: platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/WeightGenerators.java [hunk 7]
```diff
@@ -112,7 +112,7 @@ public static List<Long> randomNodeWeights(final long weightSeed, final int numb
         long remainingWeight = totalWeight - firstNodeWeight;
         weights.add(firstNodeWeight);
         for (int i = 1; i < numberOfNodes - 1; i++) {
-            final long weight = r.nextLong(remainingWeight);
+            final long weight = r.nextLong(Math.min(remainingWeight, halfTotalWeight));
```
Comment (netopyr) [inline platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/WeightGenerators.java:115]: Unrelated to this change, I just realize that the weight will not be evenly distributed. Is this what we want?

**Review by netopyr — APPROVED** [review]
LGTM - thanks @poulok

File: platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/WeightGenerators.java (hunk 7 above)
Comment (poulok) [reply platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/WeightGenerators.java:115]: this is intended
