### PR TITLE
fix: Wrap hashed keys from mapping-entry `HookStore`s in `minimalKey()`

### LINKED ISSUE #24729: StateOperator: `EntityIdUniqueness` validation fails on PreviewNet
Currently, we have consistent state validation failure on PreviewNet for EVM hook storage slot count. 

Here is an [example](https://github.com/hashgraph/hedera-state-validator/actions/runs/23915743377/job/69749430620#step:20:25)

```
EntityIdUniqueness.validateIdCounts,validateIdCounts() - FAILED, time taken - 0 sec
org.opentest4j.AssertionFailedError: EVM hook storage slot count is unexpected ==> expected: <5> but was: <3>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:664)
	at com.hedera.statevalidation.validator.state.service.EntityIdUniqueness.validateIdCounts(EntityIdUniqueness.java:232)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

It may be an artifact of the PreviewNet but it's still worth investigation.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
👉 Closes #24729 

ℹ️ **Context**
 -  `HookStore` has a [variant](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hapi/hedera-protobuf-java-api/src/main/proto/services/hook_types.proto#L125) for setting an EVM storage slot by giving (1) a Solidity `mapping` key, and (2) the slot of the `mapping` itself.
 - The formula for translating from `mapping` key and slot to a raw EVM slot 256-bit key is: `keccak256(abi.encodePacked(mapping_slot, key))`
 - Now, for storage changes originating [in the EVM via `HookEvmFrameState`](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/hooks/HookEvmFrameState.java), or "normal"`HookStore`s, it is guaranteed that `WritableEvmHookStore.applyStorageMutations()` will get the "minimal representation" of each 256-bit key, stripped of leading zeros.
 - ⚠️ But [here](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableEvmHookStore.java#L90) we were not wrapping the `slotKeyOfMappingEntry(p, entry)` call in `minimalKey()` to strip any leading zeros.
 - This led to inconsistencies in counting total # of hook slots when a `HookStore` using mapping entries hashed to a 256-bit key with leading zeros, because the final key put in state _is_ [ultimately the minimal key](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableEvmHookStore.java#L311), no matter what.
     * In particular, at the time we check "does this key already exist" for a hashed key that **still has leading zeros**, the answer looks like "no"...but it's actually "yes".

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableEvmHookStore.java [hunk 1]
```diff
@@ -273,9 +277,9 @@ private Bytes removeSlot(@NonNull final HookId hookId, @NonNull Bytes firstKey,
             firstKey = key.equals(firstKey) ? nextKey : firstKey;
```
Comment (petreze) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableEvmHookStore.java]: Is it intentional here to still use the original `key` instead of `minimalKey`?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableEvmHookStoreTests.java [hunk 2]
```diff
@@ -118,6 +120,7 @@ public class RepeatableEvmHookStoreTests {
             EvmHookMappingEntry.newBuilder().preimage(ZERO).value(A).build();
     private static final EvmHookMappingEntry F_E_ENTRY =
             EvmHookMappingEntry.newBuilder().key(F).value(E).build();
+    private static final Logger log = LogManager.getLogger(RepeatableEvmHookStoreTests.class);
```
Comment (petreze) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableEvmHookStoreTests.java]: nit: unused

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableEvmHookStore.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/WritableEvmHookStore.java]: Ah indeed, fixed!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableEvmHookStoreTests.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/integration/RepeatableEvmHookStoreTests.java]: Removed!

**Review by stoyanov-st — APPROVED** [review]
LGTM
