### PR TITLE
fix: reset event creator as part of reconnect cleanup

### LINKED ISSUE #11038: TipsetEventCreator: selfishness score is X but advancement score is zero
This issue appeared in a [JRS test](http://35.247.76.217:8095/swirlds-automation/develop/10N/MultiSBReconnect/20240118-060030-GCP-Daily-MultiSBReconnect-3R-10N/FCM-MultiSBReconnect-3R-1k-20m/node0001/swirlds.log). 

Stack trace:
```
2024-01-18 06:13:16.893 557      ERROR EXCEPTION        <ForkJoinPool.commonPool-worker-20> TipsetEventCreator: selfishness score is 9 but advancement score is zero for EventDescriptor[creator=0,generation=4795,birthRound=-9223372036854775808,hash=982451ccbd0f].
Minimum generation non-ancient: NonAncientEventWindow[latestConsensusRound=360,minRoundNonAncient=335,minGenNonAncient=4795]
Latest self event: EventDescriptor[creator=1,generation=1399,birthRound=-9223372036854775808,hash=8ae3c8c21079]
Total weight: 50000000000
Maximum possible advancement weight: 45000000000
Self weight: 5000000000
Previous advancement weight: TipsetAdvancementWeight[advancementWeight=5000000000, zeroWeightAdvancementCount=0]
Latest self event tipset: (0:667, 1:1399, 2:682, 3:1394, 4:1395, 5:1395, 6:1394, 7:1393, 8:1393, 9:1394)
Snapshot: (0:667, 1:1398, 2:682, 3:1394, 4:1395, 5:1395, 6:1394, 7:1393, 8:1393, 9:1391)
Snapshot history: 
  - (0:667, 1:1007, 2:682, 3:1005, 4:996, 5:1002, 6:1002, 7:1000, 8:1006, 9:1003)
  - (0:667, 1:1047, 2:682, 3:1043, 4:1042, 5:1040, 6:1042, 7:1041, 8:1046, 9:1042)
  - (0:667, 1:1050, 2:682, 3:1047, 4:1045, 5:1045, 6:1044, 7:1048, 8:1046, 9:1044)
  - (0:667, 1:1061, 2:682, 3:1051, 4:1055, 5:1054, 6:1054, 7:1055, 8:1060, 9:1057)
  - (0:667, 1:1211, 2:682, 3:1207, 4:1205, 5:1209, 6:1205, 7:1206, 8:1204, 9:1210)
  - (0:667, 1:1228, 2:682, 3:1220, 4:1223, 5:1221, 6:1222, 7:1227, 8:1225, 9:1222)
  - (0:667, 1:1231, 2:682, 3:1225, 4:1228, 5:1225, 6:1225, 7:1227, 8:1228, 9:1223)
  - (0:667, 1:1242, 2:682, 3:1236, 4:1235, 5:1233, 6:1241, 7:1236, 8:1240, 9:1238)
  - (0:667, 1:1396, 2:682, 3:1390, 4:1390, 5:1395, 6:1391, 7:1392, 8:1387, 9:1389)
  - (0:667, 1:1398, 2:682, 3:1394, 4:1395, 5:1395, 6:1394, 7:1393, 8:1393, 9:1391)
Childless events:
  - EventDescriptor[creator=9,generation=4821,birthRound=-9223372036854775808,hash=c2ef9d5f1257] (0:-1, 1:-1, 2:-1, 3:4818, 4:4814, 5:4816, 6:4817, 7:4815, 8:4817, 9:4821)
  - EventDescriptor[creator=4,generation=4821,birthRound=-9223372036854775808,hash=c98f847f367a] (0:-1, 1:-1, 2:-1, 3:4814, 4:4821, 5:4817, 6:4819, 7:4820, 8:4818, 9:4816)
  - EventDescriptor[creator=5,generation=4821,birthRound=-9223372036854775808,hash=754f27ecd10c] (0:-1, 1:-1, 2:-1, 3:4815, 4:4816, 5:4821, 6:4819, 7:4815, 8:4812, 9:4816)
  - EventDescriptor[creator=3,generation=4822,birthRound=-9223372036854775808,hash=b3b236663303] (0:-1, 1:-1, 2:-1, 3:4822, 4:4816, 5:4817, 6:4820, 7:4815, 8:4821, 9:4816)
  - EventDescriptor[creator=0,generation=4795,birthRound=-9223372036854775808,hash=982451ccbd0f] (0:4795, 1:-1, 2:-1, 3:-1, 4:-1, 5:-1, 6:-1, 7:-1, 8:-1, 9:-1)
  - EventDescriptor[creator=6,generation=4822,birthRound=-9223372036854775808,hash=ef6db0a10ba6] (0:-1, 1:-1, 2:-1, 3:4817, 4:4816, 5:4817, 6:4822, 7:4818, 8:4814, 9:4816)
  - EventDescriptor[creator=7,generation=4822,birthRound=-9223372036854775808,hash=7a748f8ecd79] (0:-1, 1:-1, 2:-1, 3:4818, 4:4816, 5:4816, 6:4819, 7:4822, 8:4814, 9:4819)

2024-01-18 06:13:16.894 558      ERROR EXCEPTION        <ForkJoinPool.commonPool-worker-20> TipsetEventCreator: failed to locate eligible ignored node to use as a parent
```

### PR DESCRIPTION
**Pull request by cody-littley**
closes #11038

### CODE REVIEW

**Review by edward-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventCreationManagerWiring.java [hunk 1]
```diff
@@ -38,8 +40,10 @@ public class EventCreationManagerWiring {
 
     private final BindableInputWire<GossipEvent, GossipEvent> eventInput;
     private final BindableInputWire<NonAncientEventWindow, GossipEvent> nonAncientEventWindowInput;
+    private final BindableInputWire<ClearTrigger, GossipEvent> clearInput;
     private final Bindable<Instant, GossipEvent> heartbeatBindable;
     private final OutputWire<GossipEvent> newEventOutput;
+    private EventCreationManager eventCreationManager;
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventCreationManagerWiring.java:46]: why do you need this variable?

**Review by lpetrovic05 — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventCreationManagerWiring.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/EventCreationManagerWiring.java:46]: Unused, removed.

**Review by edward-swirldslabs — APPROVED** [review]

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/EventCreator.java [hunk 2]
```diff
@@ -24,7 +25,7 @@
 /**
  * An object that creates new events.
  */
-public interface EventCreator {
+public interface EventCreator extends Clearable {
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/EventCreator.java:28]: I've removed this interface from all classes where it was added in this PR.

**Review by alittley — APPROVED** [review]
