### PR TITLE
JMH staking benchmark + `pendingRewards` edge case fix

### LINKED ISSUE #3481: Characterize perf overhead of native staking via JMH
### Problem

We need fairly granular benchmarks that capture the `handleTransaction` throughput of simple `CryptoTransfer`s, we can compare with and without staking overhead.

### Solution

- [ ] Add a JMH benchmark that captures the throughput of a simulated simple `CryptoTransfer`.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #3481
 - Adds `StakingActivityBench` to measure throughput of simple `CryptoUpdate` and `CryptoTransfer` txns through a ledger with `StakingAccountsCommitInterceptor`.
 - Simultaneously tests `pendingRewards` management by [comparing the network context summary with aggregated reward estimates](https://github.com/hashgraph/hedera-services/blob/03481-jmh-staking-benchmark/hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java#L156) at the end of each simulated staking period.
 - Updates _hedera-node/build.grade.kts_ to support Dagger2 annotation processor for `jmh` source set.
 - Fixes edge-case bug in `pendingRewards` management when a `CryptoUpdate` "changes" an account's `STAKING_ID` or `DECLINE_REWARD` property to the same value it currently has.
     * In this case, `stakePeriodStart` could be reset to the current period **without pending rewards being unclaimed via `StakeInfoManager.unclaimRewardsForStakeStart()`**.
     * The fix is to ensure `stakePeriodStart` is updated to the current period [only when stake metadata has truly changed](https://github.com/hashgraph/hedera-services/blob/03481-jmh-staking-benchmark/hedera-node/src/main/java/com/hedera/services/ledger/accounts/staking/StakingUtils.java#L120).
 - Excludes JMH sources from Sonar report (this appears to be why `master` is showing 84% instead of 96%).

A typical result on my laptop is,
```
Result "com.hedera.services.ledger.StakingActivityBench.stakingActivities":
  204269.923 ops/s
```

### CODE REVIEW

File: hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityModule.java [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+    @Singleton
+    EntityCreator bindEntityCreator(MockEntityCreator entityCreator);
+
+    @Binds
+    @Singleton
+    RecordsHistorian bindRecordsHistorian(MockRecordsHistorian recordsHistorian);
+
+    @Binds
+    @Singleton
+    TransactionContext TransactionContext(MockTransactionContext transactionContext);
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityModule.java:73]: nit : naming for function `transactionContext`

File: hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java [hunk 2]
```diff
@@ -0,0 +1,307 @@
...
+        // Also the stakee in the case of a staking election to account
+        final var countpartyId = advanceToNextId();
+        // Also the stakee in the case of a staking election to node
+        advanceI();
+        final var nodeI = Math.floorMod(i, numNodes);
+
+        rewardCalculator.reset();
+        sideEffects.reset();
+        ledger.begin();
+        // First we credit fees
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java:252]: QQ: Are these needed here or just wanted their time included in benchmark ?

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM other than a Question and nit

File: hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityModule.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityModule.java:73]: Ah typo, will fix!

File: hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java:252]: They're necessary to get the interceptor and `TransactionalLedger` to work (otherwise for example, every `commit()`, the `0.0.800` account will be debited for *all rewards paid in the benchmark*---not just the current transaction).
