### PR TITLE
Distinguish auto-approvals in synthetic `CryptoTransfer` transfer lists

### LINKED ISSUE #6262: spender allowance does not decrease as allowance is spent
### Description

I initially created hashgraph/hedera-mirror-node-explorer/issues/567 , however, @ericleponner indicated that this is an issue at the service layer.

I assumed it was simply the mirror node returning a stale allowance(i.e. the allowance that was initially approved), but it seems it's not being updated at the service layer.

I'd also recommend interpreting `type(int64).max` as an infinite allowance(i.e. does not need to be decreased as spender spends) which is similar to ERC20 tokens where an allowance of `type(uint256).max` is interpreted as [an infinite approval/allowance](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f959d7e4e6ee0b022b41e5b644c79369869d8411/contracts/token/ERC20/ERC20.sol#L129).

### Steps to reproduce

I'm not sure how to get both fungible and nonfungible token allowances using the SDK, I tried searching for a way to do so in the docs to no avail.

If there is a way then on _mainnet_ simply get the allowance for spender _0.0.2178425_ for token _0.0.2178426_ approved by account _0.0.1055570_, if the allowance is still 100 WHBAR then this confirms the issue.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.36.4

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #6262 
 - Updates `TransferPrecompile` to produce a synthetic `CryptoTransferTransactionBody` with `is_approval = true` for each asset change that was automatically switched to use an approval/allowance.
 - Includes EET to verify this behavior using a new `RecordStreamAssertion` implementation.

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/IdScreenedAssertion.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+     * @param txnId the {@code TransactionID} of the record stream item
+     * @return whether if the item should be included in the assertion
+     */
+    protected boolean filter(@NonNull final TransactionID txnId) {
+        return true;
+    }
+
+    private boolean nonNonceFieldsMatch(@NonNull final TransactionID a, @NonNull final TransactionID b) {
+        return a.getTransactionValidStart().equals(b.getTransactionValidStart())
+                && a.getAccountID().equals(b.getAccountID());
```
Comment (Nana-EC) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/IdScreenedAssertion.java:69]: Missing check for scheduled
```suggestion
                && a.getAccountID().equals(b.getAccountID())
                && a.isScheduled().equals(b.isScheduled());
```

**Review by Nana-EC — COMMENTED** [review]
Looking good.
2 suggestions - 1 for readability of tests and the other a missing TransactionID field check

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java [hunk 2]
```diff
@@ -678,4 +688,138 @@ private AccountAmount aaWith(final AccountID account, final long amount, final b
...
+     * synthetic {@code CryptoTransfer} op to reflect the switch.
+     *
+     * @param opBuilder the builder for the in-progress synthetic {@code CryptoTransfer} op
+     * @param switchedChange the token {@code BalanceChange} switched to approval-based authorization
+     */
+    private static void updateSynthOpForAutoApprovalOfToken(
+            final CryptoTransferTransactionBody.Builder opBuilder, final BalanceChange switchedChange) {
+        for (int i = 0, n = opBuilder.getTokenTransfersCount(); i < n; i++) {
+            final var tokenTransfers = opBuilder.getTokenTransfers(i);
+            if (tokenTransfers.getToken().equals(switchedChange.tokenId())) {
```
Comment (lukelee-sl) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:755]: When there is a transfer of a token from sender to receiver, do we not sometimes create two BalanceChange objects - one with the positive and one with the negative amount?

Comment (tinker-michaelj) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:755]: True, but we will only ever "switch" the `BalanceChange` with the negative amount. Or maybe I am missing the point? 😁

File: hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SynthApprovalRecordsTest.java [hunk 3]
```diff
@@ -0,0 +1,231 @@
...
+import com.hederahashgraph.api.proto.java.TransferList;
+import org.junit.jupiter.api.Test;
+
+class SynthApprovalRecordsTest {
+    @Test
+    void canUpdateHbarAutoApprovals() {
+        final var amount = 10;
+        final var debited = IdUtils.asModelId("0.0.3");
+        final var payer = IdUtils.asModelId("0.0.5");
+        final var hbarAdjust = BalanceChange.changingHbar(
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SynthApprovalRecordsTest.java]: Done!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/IdScreenedAssertion.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/IdScreenedAssertion.java]: Good point, renamed this class to reflect it's only meant to screen by "base" `TransactionID` fields: `accountID` and `transactionValidStart`.

Subclasses can choose to be pickier about `nonce` or `scheduled` fields.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java (hunk 2 above)
Comment (lukelee-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:755]: Ah, ok you're right.  I keep forgetting about that if statement.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java [hunk 4]
```diff
@@ -678,4 +688,138 @@ private AccountAmount aaWith(final AccountID account, final long amount, final b
...
+     * @param opBuilder the builder for the in-progress synthetic {@code CryptoTransfer} op
+     * @param switchedChange the hbar {@code BalanceChange} switched to approval-based authorization
+     */
+    private static void updateSynthOpForAutoApprovalOfHbar(
+            @NonNull final CryptoTransferTransactionBody.Builder opBuilder,
+            @NonNull final BalanceChange switchedChange) {
+        final var transfersBuilder = opBuilder.getTransfersBuilder();
+        for (int i = 0, n = transfersBuilder.getAccountAmountsCount(); i < n; i++) {
+            final var hbarAdjust = transfersBuilder.getAccountAmountsBuilder(i);
+            if (hbarAdjust.getAccountID().equals(switchedChange.accountId())) {
```
Comment (Nana-EC) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:732]: @tinker-michaelj should we have a check for debit inside this functions to be clear it's only for debits?
For FT amount also
Not sure how to capture debit for NFTs though.

**Review by Nana-EC — APPROVED** [review]
LGTM
One suggestion for adding a debit check if useful

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java [hunk 5]
```diff
@@ -678,4 +688,138 @@ private AccountAmount aaWith(final AccountID account, final long amount, final b
...
+     *
+     * <p><b>Important:</b> this method acts via side effects, mutating the given {@code opBuilder} in-place.
+     *
+     * @param opBuilder the builder for the in-progress synthetic {@code CryptoTransfer} op
+     * @param switchedChange the {@code BalanceChange} switched to approval-based authorization
+     */
+    @VisibleForTesting
+    static void updateSynthOpForAutoApprovalOf(
+            @NonNull final CryptoTransferTransactionBody.Builder opBuilder,
+            @NonNull final BalanceChange switchedChange) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:705]: We should probably mention this switched change is only for debit in a comment ?

Comment (Nana-EC) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:705]: Or better yet check in the code that it's a debit

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java [hunk 6]
```diff
@@ -678,4 +688,138 @@ private AccountAmount aaWith(final AccountID account, final long amount, final b
...
+            final var hbarAdjust = transfersBuilder.getAccountAmountsBuilder(i);
+            if (hbarAdjust.getAccountID().equals(switchedChange.accountId())) {
+                hbarAdjust.setIsApproval(true);
+                return;
+            }
+        }
+        // This doesn't make sense, as it implies the TransferPrecompile has switched a non-custom-fee hbar
+        // adjustment to approval-based authorization, but the synthetic CryptoTransfer op doesn't have a
+        // matching adjustment in its transfer list
+        log.warn(CHANGE_SWITCHED_TO_APPROVAL_WITHOUT_MATCHING_ADJUSTMENT_IN, switchedChange, opBuilder);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:740]: Are we doing this to see in case we missed any transfers that are missed, but should not be missed ? :)

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM !

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java (hunk 5 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:705]: I think it will not reach to this function if its not debit 😃

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:734]: Added debit check for hbar and fungible `BalanceChange`'s.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java:746]: True...tbh `ERROR` makes more sense as a log level; it would be catastrophic if we had a non-custom-fee `BalanceChange` that didn't appear in the `TransactionBody`!

Changing all these `log.warn()`'s to `log.error()`'s.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Thanks @tinker-michaelj
