### PR TITLE
08103 Changed the way ClosedByInterruptException handled in DataFileCollection

### LINKED ISSUE #8103: DataFileCollection: Failed to copy data item 34
The following failure was observed in a nightly run of `VMerkleDual-NDReconnect-500-60m`

http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230818-053611-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/node0003/

```
2023-08-18 06:16:48.118 8885     ERROR EXCEPTION        <<merkledb: Merging #0>> DataFileCollection: Failed to copy data item 34 / 22008224
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[?:?]
	at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:168) ~[?:?]
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:820) ~[?:?]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:800) ~[?:?]
	at com.swirlds.merkledb.utilities.MerkleDbFileUtils.completelyRead(MerkleDbFileUtils.java:91) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileReader.read(DataFileReader.java:377) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileReader.readDataItemBytes(DataFileReader.java:201) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.lambda$compactFiles$2(DataFileCollection.java:447) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.collections.AbstractLongList.forEach(AbstractLongList.java:635) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.MemoryIndexDiskKeyValueStore$1.forEach(MemoryIndexDiskKeyValueStore.java:208) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.compactFiles(DataFileCollection.java:426) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.MemoryIndexDiskKeyValueStore.merge(MemoryIndexDiskKeyValueStore.java:212) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.doMerge(MerkleDbDataSource.java:1382) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### PR DESCRIPTION
**Pull request by imalygin**
This PR changs the way `ClosedByInterruptException` handled in `DataFileCollection`. It's no longer resulted in a message of `ERROR` level.

To capture log entries for further verification I added `MockAppender` to `swirlds-common-test` module. 

**Related issue(s)**:

Fixes #8103 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java [hunk 1]
```diff
@@ -447,6 +448,14 @@ public synchronized List<Path> compactFiles(
                             serializationVersion, reader.readDataItemBytes(fileOffset));
                     // update the index
                     index.putIfEqual(path, dataLocation, newLocation);
+                } catch (final ClosedByInterruptException e) {
+                    logger.info(
+                            EXCEPTION.getMarker(),
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java:453]: It should be `MERKLE_DB.getMarker()`, otherwise it will still be treated as an error (regardless of logger level) by JRS.

File: platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java [hunk 2]
```diff
@@ -713,6 +702,108 @@ void mergeWorksAfterOpen(final FilesTestType testType) throws Exception {
...
+                fail("Exception should not be thrown");
+            }
+            reset(spy);
+        });
+        thread.start();
+        try {
+            assertEventuallyTrue(
+                    () -> {
+                        try {
+                            Thread.sleep(100);
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java:784]: This Thread.sleep() is probably redundant because of assertEventuallyTrue()

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java [hunk 3]
```diff
@@ -447,6 +448,14 @@ public synchronized List<Path> compactFiles(
...
+                            "Failed to copy data item {} / {} due to thread interruption",
+                            fileIndex,
+                            fileOffset,
+                            e);
+                    throw e;
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java:458]: Should not be rethrown.

Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java:458]: That was my initial thinking but then I realized that we re-throw here to end `forEach` cycle.

File: platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java]: Agreed. I removed it

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java]: Fixed

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+ */
+public class MockAppender extends AbstractAppender {
+    private final List<String> messages = new CopyOnWriteArrayList<>();
+
+    public MockAppender(String name) {
+        super("MockAppender-" + name, null, null, true, null);
+    }
+
+    @Override
+    public void append(LogEvent event) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java:45]:
```suggestion
    public void append(@NonNull final LogEvent event) {
```

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+
+    public int size() {
+        return messages.size();
+    }
+
+    public void clear() {
+        messages.clear();
+    }
+
+    public String get(int index) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java:63]: Not sure if this method can return null or not, please add `@NonNull` or `@Nullable` (whichever is appropriate)

```suggestion
    public String get(final int index) {
```

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+ *         logger.addAppender(mockAppender);
+ *  } </pre>
+ *  Then call {@code mockAppender.get(<index>)} to get the log message.
+ *  After the test, call {@code mockAppender.stop()} to clean up.
+ *
+ */
+public class MockAppender extends AbstractAppender {
+    private final List<String> messages = new CopyOnWriteArrayList<>();
+
+    public MockAppender(String name) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java:40]:
```suggestion
    public MockAppender(@NonNull final String name) {
```

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+        if (isStarted()) {
+            messages.add(String.format(
+                    "%s - %s - %s",
+                    event.getMarker().getName(),
+                    event.getLevel(),
+                    event.getMessage().getFormattedMessage()));
+        }
+    }
+
+    public int size() {
```
Comment (cody-littley) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java:55]: please add short javadocs for public methods

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java [hunk 8]
```diff
@@ -37,12 +38,15 @@
 public class MockAppender extends AbstractAppender {
     private final List<String> messages = new CopyOnWriteArrayList<>();
 
-    public MockAppender(String name) {
+    public MockAppender(@NonNull String name) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java:41]:
```suggestion
    public MockAppender(@NonNull final String name) {
```

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java [hunk 9]
```diff
@@ -37,12 +38,15 @@
...
         super("MockAppender-" + name, null, null, true, null);
     }
 
+    /**
+     * {@inheritDoc}
+     */
     @Override
-    public void append(LogEvent event) {
+    public void append(@NonNull LogEvent event) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/logging/MockAppender.java:49]:
```suggestion
    public void append(@NonNull final LogEvent event) {
```

**Review by cody-littley — DISMISSED** [review]

**Review by artemananiev — APPROVED** [review]

**Review by cody-littley — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]

**Review by JeffreyDallas — APPROVED** [review]
