### PR TITLE
Fix INSUFFICIENT_PAYER_BALANCE error in nightly tests

### LINKED ISSUE #1054: Fix INSUFFICIENT_PAYER_BALANCE error in nightly tests
**Summary of the defect**
Most of the nightly regression tests are failing with `INSUFFICIENT_PAYER_BALANCE` error on Feb 3rd. 
Failing Crypto-Restart test link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1612420086307000

Possible Resolution:
This might be solved by using `long initialBalance = 5_000_000_000_000L;` in `CryptoCreateForSuiteRunner` and use different initialBalance for performance tests in LoadTest `public static OptionalLong initialBalance = OptionalLong.of(900_000_000_000L);`

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #1054 

Passed Migration test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612482469189000

Yesterday's failed test : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1612418938306500

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java [hunk 1]
```diff
@@ -45,8 +45,8 @@
 	public static OptionalInt threadNumber = OptionalInt.empty();
 	public static OptionalInt hcsSubmitMessage = OptionalInt.empty();
 	public static OptionalInt hcsSubmitMessageSizeVar = OptionalInt.empty();
-	/** initial balance of payer account used for paying for performance test transactions */
-	public static OptionalLong initialBalance = OptionalLong.of(90_000_000_000_000L);
+	/** initial balance of account used as sender for performance test transactions */
+	protected static OptionalLong initialBalance = OptionalLong.of(ONE_HBAR * 9000);
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:49]: We wanted 1 mil hbars (`ONE_HBAR * 1_000_000L`) to avoid recharging during load tests. And we still want a public scope to be used in `CryptoCreateForSuiteRunner`

File: test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java [hunk 2]
```diff
@@ -49,6 +49,9 @@
 	private String nodes;
 	private String defaultNode;
 
+	//Use more initialBalance for this account as it is used as payer for the performance tests
+	private static OptionalLong initialBalance = OptionalLong.of(ONE_HBAR * 50000);
+
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java:54]: This was not what we discussed. We want
```
CryptoCreateForSuiteRunner.initialBalance = 5 * LoadTest.initialBalance; // or 10 *
```
If these two balances don't link together, changing one might break the other in performance tests. It's harder to maintain them that way.

**Review by qnswirlds — CHANGES_REQUESTED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java [hunk 3]
```diff
@@ -50,7 +51,7 @@
 	private String defaultNode;
 
 	//Use more initialBalance for this account as it is used as payer for the performance tests
-	private static OptionalLong initialBalance = OptionalLong.of(ONE_HBAR * 50000);
+	private static double initialBalance = 5.0 * (LoadTest.initialBalance.getAsLong());
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java:54]: We should just use `long` and avoid the type cast later. All balances/fee are integers in tinybars, no floating-points

**Review by qnswirlds — APPROVED** [review]

**Comment by Neeharika-Sompalli** [comment]
After the fix `INSUFFICIENT_PAYER_BALANCE` error is resolved. https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1612540763198200

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java [hunk 4]
```diff
@@ -45,8 +45,8 @@
 	public static OptionalInt threadNumber = OptionalInt.empty();
 	public static OptionalInt hcsSubmitMessage = OptionalInt.empty();
 	public static OptionalInt hcsSubmitMessageSizeVar = OptionalInt.empty();
-	/** initial balance of payer account used for paying for performance test transactions */
-	public static OptionalLong initialBalance = OptionalLong.of(90_000_000_000_000L);
+	/** initial balance of account used as sender for performance test transactions */
+	public static OptionalLong initialBalance = OptionalLong.of(ONE_HBAR * 1_000_000L);
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:49]: This only increases the initial balances by 10,000 hbar. Will this be enough if we move to full 4-hr run?

Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:49]: @ljianghedera On the 3 hour weekly tests, 90K hbars were sufficient for the test run. Now we are providing 1M hbars. It should be sufficient right?

Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:49]: Actually it was 900K hbars for 3-hr run. I didn't expect it to run into the insufficient payer balance error for 3 hr run. So if we increase 100K hbars for another 1-hr, we may still run into this problem again. Since we are only in test, I suggest we increase the initial balances to 5M+ hbars to avoid this problem once and for all.

Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:49]: Since the payer is not the sender. 1M should be sufficient.

**Review by ljianghedera — DISMISSED** [review]
LGTM.

**Review by ljianghedera — APPROVED** [review]
LGTM
