### PR TITLE
test: six new hapi tests for token claim airdrop

### LINKED ISSUE #14703: TokenClaimAirdrop transaction containing duplicate entries should fail

### PR DESCRIPTION
**Pull request by povolev15**
Implemented 3 tests:
-TokenClaimAirdrop transaction containing duplicate entries should fail
-TokenClaimAirdrop transaction with more than 10 pending airdrops entries should fail
-TokenClaimAirdrop transaction with no pending airdrops entries should fail
-[Single Token]
Given existing pending airdrop in state when valid TokenClaimAirdrop transaction containing 1 entry for the same pending airdrop is performed then the TokenClaimAirdrop should succeed
-[Single Token]
Receiver (a normal account) signs a pending TokenClaimAirdrop transaction for FT A 
-[Single Token]
Receiver (a normal account) signs a pending TokenClaimAirdrop transaction for 1 NFT A with serial number 1
-[Single Token]
Receiver signs a TokenClaimAirdrop with not enough HBAR, then gets enough HBAR and claims the same airdrop again.
**Related issue(s)**:

Fixes #14703 
#14701 
#14700 
#14813 
#14814
#14815 
#14816

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 1]
```diff
@@ -44,15 +45,21 @@
...
 import static com.hederahashgraph.api.proto.java.ResponseCodeEnum.INVALID_TRANSACTION_BODY;
+import static com.hederahashgraph.api.proto.java.ResponseCodeEnum.MAX_PENDING_AIRDROP_ID_EXCEEDED;
+import static com.hederahashgraph.api.proto.java.ResponseCodeEnum.PENDING_NFT_AIRDROP_ALREADY_EXISTS;
 import static com.hederahashgraph.api.proto.java.TokenType.FUNGIBLE_COMMON;
 
+import com.google.protobuf.ByteString;
 import com.hedera.services.bdd.junit.HapiTest;
 import com.hedera.services.bdd.junit.HapiTestLifecycle;
 import com.hedera.services.bdd.junit.support.TestLifecycle;
+import com.hederahashgraph.api.proto.java.TokenType;
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:60]: wrong import

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 2]
```diff
@@ -117,6 +138,162 @@ final Stream<DynamicTest> claimFungibleTokenAirdrop() {
...
+                        .initialSupply(1000L),
+                newKeyNamed(NFT_SUPPLY_KEY),
+                tokenCreate(NON_FUNGIBLE_TOKEN)
+                        .name(NON_FUNGIBLE_TOKEN)
+                        .treasury(OWNER)
+                        .tokenType(TokenType.NON_FUNGIBLE_UNIQUE)
+                        .initialSupply(0L)
+                        .supplyKey(NFT_SUPPLY_KEY),
+                mintToken(NON_FUNGIBLE_TOKEN, List.of(ByteString.copyFromUtf8("a"), ByteString.copyFromUtf8("b"))),
+                tokenClaimAirdrop().hasPrecheck(EMPTY_PENDING_AIRDROP_ID_LIST));
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:164]: Do you need all the accounts and tokens created to do claim with empty body, this should be a pureCheck so you can simpify this test to tokenClaimAirdrop().hasPrecheck(EMPTY_PENDING_AIRDROP_ID_LIST)

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 3]
```diff
@@ -117,6 +138,162 @@ final Stream<DynamicTest> claimFungibleTokenAirdrop() {
...
+                        .treasury(OWNER)
+                        .tokenType(FUNGIBLE_COMMON)
+                        .initialSupply(1000L),
+                tokenCreate(FUNGIBLE_TOKEN_10)
+                        .treasury(OWNER)
+                        .tokenType(FUNGIBLE_COMMON)
+                        .initialSupply(1000L),
+                tokenCreate(FUNGIBLE_TOKEN_11)
+                        .treasury(OWNER)
+                        .tokenType(FUNGIBLE_COMMON)
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:255]: you can create a helper method that creates a token and/or moves a token to reduce code duplication

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 4]
```diff
@@ -65,6 +74,20 @@
 @DisplayName("Claim token airdrop")
 public class TokenClaimAirdropTest extends TokenAirdropBase {
     private static final String RECEIVER = "receiver";
+    private static final String OWNER_2 = "owner2";
+    private static final String FUNGIBLE_TOKEN = "fungibleToken";
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:78]: Why not name this `FUNGIBLE_TOKEN_1` to match the rest?

**Review by david-bakin-sl — APPROVED** [review]
LGTM

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 5]
```diff
@@ -117,6 +140,98 @@ final Stream<DynamicTest> claimFungibleTokenAirdrop() {
...
+                tokenClaimAirdrop(
+                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN),
+                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN),
+                                pendingAirdrop(OWNER_2, RECEIVER, FUNGIBLE_TOKEN_2),
+                                pendingNFTAirdrop(OWNER, RECEIVER, NON_FUNGIBLE_TOKEN, 1))
+                        .payingWith(RECEIVER)
+                        .feeUsd(0.001)
+                        .via("claimTxn")
+                        .hasPrecheck(PENDING_NFT_AIRDROP_ALREADY_EXISTS));
+    }
```
Comment (JivkoKelchev) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:187]: There is no need to send airdrops in this case.
Here, when you send claim transaction, it should fail in the `pureChecks` with PENDING_AIRDROP_ID_REPEATED, so no state checks.

This way the test will be way simpler and easy to read
```suggestion
    @HapiTest
    @DisplayName("token claim with duplicate entires should fail")
    final Stream<DynamicTest> duplicateClaimAirdrop() {
        return hapiTest(
                cryptoCreate(RECEIVER).balance(ONE_HUNDRED_HBARS),
                tokenClaimAirdrop(
                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN),
                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN))
                        .payingWith(RECEIVER)
                        .feeUsd(0.001)
                        .hasPrecheck(PENDING_AIRDROP_ID_REPEATED));
    }
```

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 6]
```diff
@@ -117,6 +140,98 @@ final Stream<DynamicTest> claimFungibleTokenAirdrop() {
...
+    @DisplayName("token claim with duplicate entires should fail")
+    final Stream<DynamicTest> duplicateClaimAirdrop() {
+        return hapiTest(
+                cryptoCreate(OWNER).balance(ONE_HUNDRED_HBARS).maxAutomaticTokenAssociations(0),
+                cryptoCreate(OWNER_2).balance(ONE_HUNDRED_HBARS).maxAutomaticTokenAssociations(0),
+                cryptoCreate(RECEIVER).balance(ONE_HUNDRED_HBARS),
+                tokenCreate(FUNGIBLE_TOKEN)
+                        .treasury(OWNER)
+                        .tokenType(FUNGIBLE_COMMON)
+                        .initialSupply(1000L),
```
Comment (JivkoKelchev) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:159]: OWNER and FUNGIBLE_TOKEN are already created in `beforeAll()`. You can use them directly.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 7]
```diff
@@ -117,6 +140,98 @@ final Stream<DynamicTest> claimFungibleTokenAirdrop() {
...
+                        .payingWith(OWNER),
+                tokenClaimAirdrop(
+                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN),
+                                pendingAirdrop(OWNER, RECEIVER, FUNGIBLE_TOKEN),
+                                pendingAirdrop(OWNER_2, RECEIVER, FUNGIBLE_TOKEN_2),
+                                pendingNFTAirdrop(OWNER, RECEIVER, NON_FUNGIBLE_TOKEN, 1))
+                        .payingWith(RECEIVER)
+                        .feeUsd(0.001)
+                        .via("claimTxn")
+                        .hasPrecheck(PENDING_NFT_AIRDROP_ALREADY_EXISTS));
```
Comment (JivkoKelchev) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:186]: `PENDING_NFT_AIRDROP_ALREADY_EXISTS` was wrong status.
It was replaced with `PENDING_AIRDROP_ID_REPEATED`. 
You may need to rebase or merge the target branch.

**Review by JivkoKelchev — CHANGES_REQUESTED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 8]
```diff
@@ -118,6 +142,98 @@ final Stream<DynamicTest> claimFungibleTokenAirdrop() {
...
     }
 
+    @HapiTest
+    @DisplayName("token claim with no pending airdrop should fail")
+    final Stream<DynamicTest> tokenClaimWithNoPendingAirdrop() {
+        return hapiTest(tokenClaimAirdrop().hasPrecheck(EMPTY_PENDING_AIRDROP_ID_LIST));
+    }
+
+    @HapiTest
+    @DisplayName("token claim with duplicate entires should fail")
```
Comment (kimbor) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:152]:
```suggestion
    @DisplayName("token claim with duplicate entries should fail")
```

**Review by ibankov — APPROVED** [review]
LGTM

**Review by JivkoKelchev — APPROVED** [review]
LGTM, thanks @povolev15
