### PR TITLE
fix: added validation for node account availability in yahcli

### LINKED ISSUE #21974: Yachli experiences NPE when passing the wrong node account ID
In this example the correct --node-account was 3 but we passed in 0 and that caused and NPE. this transaction was for file upload to 150 to perform an upgrade.

```
submit@transaction-submission-1:~/yahcli$ docker run --interactive --tty --volume $(pwd):/launch gcr.io/hedera-registry/yahcli:0.68 \
  --fixed-fee 100000000 \
  --node-account 0 \
  --network integration \
  --payer 54 \
  sysfiles upload software-zip \
    --bytes-per-append 5140 \
    --appends-per-burst 512
Unable to find image 'gcr.io/hedera-registry/yahcli:0.68' locally
0.68: Pulling from hedera-registry/yahcli
4b3ffd8ccb52: Pull complete
65b4a32fbe43: Pull complete
71abb39f78a1: Pull complete
b32aac563dea: Pull complete
2326993b9fe6: Pull complete
25e57e0743a9: Pull complete
ad3d6acb17ab: Pull complete
a36ef9ec579f: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:a02b3ad3d30d12ef9732e28208ea41d295219744624e6009b1e82d4775366b30
Status: Downloaded newer image for gcr.io/hedera-registry/yahcli:0.68
Log level is WARN
Targeting integration, paying with 0.0.54
2025-11-03 17:50:21.449 <hc> INFO   45   MapPropertySource - Initializing a MapPropertySource from {default.payer.pemKeyResource=, fees.fixedOffer=100000000, fees.useFixedOffer=true, nodes=34.74.191.8:0.0.3#0,35.245.150.69:0.0.4#1,34.70.193.123:0.0.5#2,34.94.114.236:0.0.6#3, default.payer.pemKeyLoc=./integration/keys/account54.pem, default.node=0, default.payer=0.0.54}
2025-11-03 17:50:22.059 <hc> INFO   75   ConfigProviderBase - Properties file data/config/genesis.properties does not exist and won't be used as configuration source
2025-11-03 17:50:22.060 <hc> INFO   75   ConfigProviderBase - Properties file data/config/application.properties does not exist and won't be used as configuration source
2025-11-03 17:50:22.473 <hc> INFO   976  HapiSpec - 'UploadSystemFile-150' -  test suite started !
2025-11-03 17:50:22.480 <hc> INFO   1015 HapiSpec - 'UploadSystemFile-150' finished initial execution of CustomSpecAssert
.i. Beginning upload for 0.0.150 (36119 appends required)
.i. Submitting initial update for file 0.0.150,
2025-11-03 17:50:22.659 <hc> ERROR  50   CustomSpecAssert - Operation 'HapiFileUpdate{sigs=1, payer=DEFAULT_PAYER, fileName=0.0.150}' :: HapiClients has no matching stub!
2025-11-03 17:50:22.661 <hc> WARN   221  HapiSpecOperation - 'UploadSystemFile-150' - CustomSpecAssert failed - java.lang.NullPointerException: HapiClients has no matching stub!!
java.lang.IllegalStateException: java.lang.NullPointerException: HapiClients has no matching stub!
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:51)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.executeHederaOps(CustomSpecAssert.java:31)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:25)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:56)
	at com.hedera.services.bdd.spec.utilops.UtilVerbs.lambda$updateSpecialFile$60(UtilVerbs.java:1798)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.submitOp(CustomSpecAssert.java:72)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:207)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:48)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.executeHederaOps(CustomSpecAssert.java:31)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:25)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:56)
	at com.hedera.services.bdd.spec.utilops.SourcedOp.submitOp(SourcedOp.java:19)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:207)
	at com.hedera.services.bdd.spec.HapiSpec.exec(HapiSpec.java:1006)
	at com.hedera.services.bdd.spec.HapiSpec.run(HapiSpec.java:803)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hedera.services.bdd.suites.HapiSuite.runSequentialSpecs(HapiSuite.java:275)
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:233)
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteSync(HapiSuite.java:205)
	at com.hedera.services.yahcli.commands.files.SysFileUploadCommand.call(SysFileUploadCommand.java:106)
	at com.hedera.services.yahcli.commands.files.SysFileUploadCommand.call(SysFileUploadCommand.java:14)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.hedera.services.yahcli.Yahcli.main(Yahcli.java:118)
Caused by: java.lang.NullPointerException: HapiClients has no matching stub!
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at com.hedera.services.bdd.spec.infrastructure.HapiClients.nextStubsFromPool(HapiClients.java:390)
	at com.hedera.services.bdd.spec.infrastructure.HapiClients.getFileSvcStub(HapiClients.java:212)
	at com.hedera.services.bdd.junit.hedera.utils.GrpcUtils.submit(GrpcUtils.java:133)
	at com.hedera.services.bdd.junit.hedera.AbstractGrpcNetwork.submit(AbstractGrpcNetwork.java:70)
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:229)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:207)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:48)
	... 29 more
2025-11-03 17:50:22.667 <hc> ERROR  50   CustomSpecAssert - Operation 'CustomSpecAssert' :: java.lang.NullPointerException: HapiClients has no matching stub!
2025-11-03 17:50:22.667 <hc> WARN   221  HapiSpecOperation - 'UploadSystemFile-150' - SourcedOp failed - java.lang.IllegalStateException: java.lang.NullPointerException: HapiClients has no matching stub!!
java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.NullPointerException: HapiClients has no matching stub!
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:51)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.executeHederaOps(CustomSpecAssert.java:31)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:25)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:56)
	at com.hedera.services.bdd.spec.utilops.SourcedOp.submitOp(SourcedOp.java:19)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:207)
	at com.hedera.services.bdd.spec.HapiSpec.exec(HapiSpec.java:1006)
	at com.hedera.services.bdd.spec.HapiSpec.run(HapiSpec.java:803)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hedera.services.bdd.suites.HapiSuite.runSequentialSpecs(HapiSuite.java:275)
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:233)
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteSync(HapiSuite.java:205)
	at com.hedera.services.yahcli.commands.files.SysFileUploadCommand.call(SysFileUploadCommand.java:106)
	at com.hedera.services.yahcli.commands.files.SysFileUploadCommand.call(SysFileUploadCommand.java:14)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.hedera.services.yahcli.Yahcli.main(Yahcli.java:118)
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException: HapiClients has no matching stub!
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:51)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.executeHederaOps(CustomSpecAssert.java:31)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:25)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:56)
	at com.hedera.services.bdd.spec.utilops.UtilVerbs.lambda$updateSpecialFile$60(UtilVerbs.java:1798)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.submitOp(CustomSpecAssert.java:72)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:207)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:48)
	... 22 more
Caused by: java.lang.NullPointerException: HapiClients has no matching stub!
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at com.hedera.services.bdd.spec.infrastructure.HapiClients.nextStubsFromPool(HapiClients.java:390)
	at com.hedera.services.bdd.spec.infrastructure.HapiClients.getFileSvcStub(HapiClients.java:212)
	at com.hedera.services.bdd.junit.hedera.utils.GrpcUtils.submit(GrpcUtils.java:133)
	at com.hedera.services.bdd.junit.hedera.AbstractGrpcNetwork.submit(AbstractGrpcNetwork.java:70)
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:229)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:207)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:48)
	... 29 more
2025-11-03 17:50:22.982 <hc> INFO   1064 HapiSpec - 'UploadSystemFile-150' - final status: FAILED!
.!. FAILED Uploading requested system files
```

### PR DESCRIPTION
**Pull request by AlexKehayov**
**Description**:
- Adds validation for node account availability in ConfigManager
- Adds `nodeAccount` param and `stderrCb` callback to receive stderr content in YahcliCallOperation
- Adds `sysfileUploadWithInvalidNodeAccountFailsGracefully()` test to cover the introduced changes

**Related issue(s)**:

Fixes #21974

### CODE REVIEW

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java [hunk 1]
```diff
@@ -31,8 +33,13 @@ public class YahcliCallOperation extends AbstractYahcliOperation<YahcliCallOpera
     @Nullable
     private Consumer<String> outputCb;
 
+    @Nullable
+    private Consumer<String> stderrCb;
+
```
Comment (ibankov) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java:40]: Do you need this cb? I think you can use the `outputCb`?

Comment (AlexKehayov) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java:40]: Unfortunately, the ParameterException is logged in stderr, the original version validated logs only from stdout. I couldn't test my change otherwise. The current approach may be useful for future negative tests. When not explicitly called in a specific test, it does not alter the original behavior.

Comment (mhess-swl) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java:40]: A standard error capture is something that 1. makes total sense for a cli application and 2). I've wanted to add since starting to write yahcli tests, but haven't gotten around to doing. Thanks for adding it @AlexKehayov!!

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/SysFileUploadInvalidNodeAccountTest.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+     * <p>
+     * This test verifies that validation in ConfigManager.assertDefaultNodeAccountIsKnown()
+     * properly rejects invalid node accounts with a clear error message instead of allowing
+     * them to cause a NullPointerException later in the execution.
+     */
+    @HapiTest
+    final Stream<DynamicTest> sysfileUploadWithInvalidNodeAccountFailsGracefully() {
+        final var stderrRef = new AtomicReference<>("");
+        return hapiTest(
+                withOpContext((spec, opLog) -> {
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/SysFileUploadInvalidNodeAccountTest.java]: You can use `doingContextual(...)` instead of `withOpContext(...)` if you're not going to use `opLog`

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/SysFileUploadInvalidNodeAccountTest.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+                    final var stderr = stderrRef.get();
+
+                    final var hasValidationError = stderr != null
+                            && !stderr.isEmpty()
+                            && (stderr.contains("Node account '0' does not exist in network")
+                                    && stderr.contains("Available node accounts:"));
+
+                    assertTrue(
+                            hasValidationError,
+                            "Expected validation error message about node account not existing in stderr.");
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/regression/SysFileUploadInvalidNodeAccountTest.java]:
```suggestion
                    assertTrue(
                            stderr.contains("Node account '0' does not exist in network")
                                    && stderr.contains("Available node accounts:"),
                            "Expected validation error message about node account not existing in stderr, but got " + stdErr);
```

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java [hunk 4]
```diff
@@ -392,8 +392,33 @@ public void assertNoMissingDefaults() {
...
+            try {
+                final var accountNum = Long.parseLong(normalizedNodeAccount);
+                final var nodeExists = targetNet.getNodes().stream().anyMatch(node -> node.getAccount() == accountNum);
+                if (!nodeExists) {
+                    final var availableAccounts = targetNet.getNodes().stream()
+                            .map(NodeConfig::getAccount)
+                            .map(String::valueOf)
+                            .collect(Collectors.joining(", "));
+                    fail(String.format(
+                            "Node account '%s' does not exist in network '%s'. " + "Available node accounts: %s",
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java]: Nit:
```suggestion
                            "Node account '%s' does not exist in network '%s'. Available node accounts: %s",
```

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java [hunk 5]
```diff
@@ -392,8 +392,33 @@ public void assertNoMissingDefaults() {
 
     private void assertDefaultNodeAccountIsKnown() {
         final var normalizedNodeAccount = normalizePossibleIdLiteral(this, yahcli.getNodeAccount());
-        defaultNodeAccount =
+        final var nodeAccountToUse =
                 Optional.ofNullable(normalizedNodeAccount).orElse(String.valueOf(targetNet.getDefaultNodeAccount()));
+
+        // Validate that the node account exists in the network configuration
+        if (normalizedNodeAccount != null) {
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java:399]: Changing the exception thrown by this behavior is a breaking change. Have we talked to devops to make sure they don't depend on it in some way?

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java [hunk 6]
```diff
@@ -104,34 +136,101 @@ public Optional<Throwable> execFor(@NonNull final HapiSpec spec) {
...
+                    // Create a PrintWriter that writes to both file and original System.err
+                    try (PrintWriter errorPrintWriter = new PrintWriter(
+                            new Writer() {
+                                @Override
+                                public void write(char[] cbuf, int off, int len) {
+                                    final var str = new String(cbuf, off, len);
+                                    fileWriter.print(str);
+                                    originalErr.print(str);
+                                    originalErr.flush(); // Immediate flush to console
+                                }
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: 6+ layers of braces makes it pretty hard to tell if all this code is correct or not

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java (hunk 5 above)
Comment (ibankov) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java:399]: Previously we were throwing NPE, I don't think they depend on that.

Comment (AlexKehayov) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java:399]: @mhess-swl Should I request review from someone specifically?

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java (hunk 6 above)
Comment (AlexKehayov) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: I adjusted the code to show errors in the console and save them to a file at the same time. The snippet is a bit bulkier, but it's more convenient for development to see the error output live in my opinion.

```
if (stderrCb != null) {
                errPath = Files.createTempFile(TxnUtils.randomUppercase(8), ".err");
                try (final var fileWriter = new PrintWriter(Files.newBufferedWriter(errPath), true)) {
                    // Create a PrintWriter that writes to both file and original System.err
                    try (PrintWriter errorPrintWriter = new PrintWriter(
                            new Writer() {
                                @Override
                                public void write(char[] cbuf, int off, int len) {
                                    final var str = new String(cbuf, off, len);
                                    fileWriter.print(str);
                                    originalErr.print(str);
                                    originalErr.flush(); // Immediate flush to console
                                }

                                @Override
                                public void flush() {
                                    fileWriter.flush();
                                    originalErr.flush();
                                }

                                @Override
                                public void close() {
                                    fileWriter.close();
                                }
                            },
                            true)) {
                        commandLine.setErr(errorPrintWriter);
                        executeCommand(commandLine, finalizedArgs);
                    }
                }
            }
```

**Comment by AlexKehayov** [comment]
@mhess-swl @ibankov Thank you for the reviews, all suggestions are applied.

File: hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java (hunk 5 above)
Comment (mhess-swl) [reply hedera-node/yahcli/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java:399]: > Previously we were throwing NPE, I don't think they depend on that.

@ibankov I doubt it too, but our new [backwards compatibility doc](https://github.com/hiero-ledger/governance/pull/347) calls out making breaking changes, so we should get in the habit of checking. 

@AlexKehayov no, just ask in devops

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java (hunk 6 above)
Comment (mhess-swl) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: I'm not disagreeing with the changes, just the organization of the code. E.g.:

* The custom `Writer` implementation could be refactored into its own class
* The file writer and error print writer could be refactored into a separate method:
```
if (stderrCb != null) {
    executeErrorWrappedCmd(commandLine, finalizedArgs, ... etc);
} else {
    executeCommand(commandLine, finalizedArgs, ...etc);
}
```
* Condense the writers into a single `try` block:
```
// Create a PrintWriter that writes to both file and original System.err
try (final var fileWriter = new PrintWriter(Files.newBufferedWriter(errPath), true); 
    PrintWriter errorPrintWriter = new PrintWriter(...)) {
    // ... 
}
```

There are lots of ways to reduce the number of braces and indents required; currently it's just really hard to read which braces go with which code.

Comment (AlexKehayov) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: @mhess-swl The requested changes are applied.

Comment (mhess-swl) [reply hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java]: Beautiful, thank you!!

File: hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java [hunk 7]
```diff
@@ -148,4 +233,37 @@ private boolean argsInclude(String s) {
         }
         return false;
     }
+
+    /**
+     * A Writer that captures stderr output to a file while simultaneously writing to the original System.err,
+     * allowing stderr to be captured for inspection while still being visible in the console.
+     */
+    private static class StderrCaptureWriter extends Writer {
```
Comment (mhess-swl) [inline hedera-node/yahcli/src/test/java/com/hedera/services/yahcli/test/bdd/YahcliCallOperation.java:241]: So much nicer, thank you!

**Comment by petreze** [comment]
[A mirror PR](https://github.com/hiero-ledger/hiero-consensus-node/pull/22096) is created
