### PR TITLE
Fix ContractHTSSuite tests

### LINKED ISSUE #9656: Fix ContractHTSSuite tests

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
Fix ContractHTSSuite tests.

**Related issue(s)**:
Fixes #9656

### CODE REVIEW

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
The `TokenService` and `ScheduleService` both dispatch txns so the `HandleContext` should not always set a `ContractCallResult`.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java [hunk 1]
```diff
@@ -607,6 +609,10 @@ private void dispatchSyntheticTxn(
             dispatcher.dispatchPureChecks(txBody);
         } catch (PreCheckException e) {
             childRecordBuilder.status(e.responseCode());
+            var output = ReturnTypes.encodedRc(e.responseCode());
```
Comment (lukelee-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java:612]: It seems to me like we are making an assumption here that all PreCheckExceptions result from a contract call. I'm not sure if this is true and perhaps this can lead to unexpected outcomes.

**Comment by thenswan** [comment]
@lukelee-sl @tinker-michaelj updated the PR with another option.

**Review by tinker-michaelj — APPROVED** [review]
Ah very nice, LGTM!

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by JeffreyDallas — APPROVED** [review]

**Review by jeromy-cannon — APPROVED** [review]
