### PR TITLE
fix: use the marker EXCEPTION for error level messages

### LINKED ISSUE #10488: Always log errors with the exception marker
In the platform test validators, error level log messages don't always fail the test, depending on which log marker is used. In order to be safe, we should use `EXCEPTION.getMarker()` for ALL platform level error messages that we want to fail a test. If we don't want a log message to fail a test, we should either configure the validator to ignore the log based on some other factor, or we should downgrade the log message to a warning or info level log.

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #10488

### CODE REVIEW

**Review by edward-swirldslabs — COMMENTED** [review]
How do we know this doesn't break any validators that were expecting the marker types that were replaced?

**Comment by cody-littley** [comment]
@edward-swirldslabs 

> How do we know this doesn't break any validators that were expecting the marker types that were replaced?

Well, I will know if it breaks the abbreviated panel. I intend to monitor test results after this merges, and follow up with any fixes as needed.

File: platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java [hunk 1]
```diff
@@ -761,7 +762,7 @@ private boolean creatingOnExistingEntities(
                         expectedValue.getEntityType());
             } else {
                 logger.error(
-                        PERFORM_ON_CREATE_DELETE,
```
Comment (anthony-swirldslabs) [inline platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java:764]: It seems that this marker is used here because this condition is acceptable under certain conditions, as documented at:

https://github.com/hashgraph/hedera-services/blob/4db779426c45f1d84eae528a147351a53d4915f3/platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java#L94-L99

I'm wondering if your change would break those cases or not. In an ideal world, the code would probably branch to detect those conditions and emit a warning instead of an error, I guess.

**Review by alittley — APPROVED** [review]

File: platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java:764]: @cody-littley : In an above comment, I see you're going to try and fix any potential failures after the change is deployed, which is fine.

In that case, if we don't want anyone to use non-standard markers, such as the one quoted above, why don't we delete them from the code-base to discourage their usage?

**Review by artemananiev — APPROVED** [review]

**Review by nathanklick — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]

File: platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedFCMFamilyImpl.java:764]: I responded to this in the `#logging` slack channel. Let's discuss there.
