### PR TITLE
Fix javadoc warnings in test-clients module and remove unused legacy code

### LINKED ISSUE #1572: Fix all javadoc errors and warnings in test-clients module

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #1572 

**Summary of the change**:
1. Removed unused legacy code
2. Fixed all javadoc warnings in `test-clients/` module

No warnings are shown [here](https://circleci.com/api/v1.1/project/github/hashgraph/hedera-services/72910/output/103/0?file=true&allocation-id=60d9f594e56ba4530bc44636-0-build%2F2547F6A5) in the javadoc generation for `test-clients` and `hedera-node` module :
**Applicable documentation**
- [x] Javadoc

### CODE REVIEW

**Review by anighanta — APPROVED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java [hunk 1]
```diff
@@ -605,8 +605,11 @@ public static HapiSpecOperation contractListWithPropertiesInheritedFrom(
 	}
 
 	/**
-	 * Validates that fee charged for a transaction is within +/- 0.0001$ of
-	 * expected fee (taken from pricing calculator)
+	 *  Validates that fee charged for a transaction is within +/- 0.0001$ of
+	 * 	expected fee (taken from pricing calculator)
+	 * @param txn transaction
+	 * @param expectedUsd expected fee
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java:611]: expected fee in USD

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoRenewEntitiesForReconnect.java [hunk 2]
```diff
@@ -110,7 +110,7 @@ protected Logger getResultsLogger() {
 	 * Since reconnect is not supported when node starts from genesis, run some transactions before running correctness
 	 * tests so that a state is saved before reconnect.
 	 *
-	 * @return
+	 * @return HapiApiSpec needed to be run
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoRenewEntitiesForReconnect.java:113]: HapiApiSpec to do some CryptoTransfer's before reconnect

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Please spend some more time on the wordings to increase readability. javadoc is indeed a doc. We should not make changes just to get away from having warnings. 
Also, there are a few javadoc warnings in the `hedera-node` module. Maybe they got introduced via some merges recently. Please help fix them too.
After we have fixed all of those javadoc warnings, we will fail the workflow when having any new javadoc warning.
Thanks!

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java]: fixed. Thanks @qnswirlds

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoRenewEntitiesForReconnect.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoRenewEntitiesForReconnect.java]: fixed. Thanks @qnswirlds

**Comment by Neeharika-Sompalli** [comment]
Fixed javadocs in `hedera-node` module as well. Results are [here](https://circleci.com/api/v1.1/project/github/hashgraph/hedera-services/72910/output/103/0?file=true&allocation-id=60d9f594e56ba4530bc44636-0-build%2F2547F6A5)

**Review by qnswirlds — APPROVED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java [hunk 3]
```diff
@@ -503,7 +503,9 @@ public static HapiSpecOperation updateLargeFile(
 			boolean signOnlyWithPayer,
 			OptionalLong tinyBarsToOffer
 	) {
-		return updateLargeFile(payer, fileName, byteString, signOnlyWithPayer, tinyBarsToOffer, op -> {}, op -> {});
+		return updateLargeFile(payer, fileName, byteString, signOnlyWithPayer, tinyBarsToOffer, op -> {
+		}, op -> {
+		});
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java:508]: nit: Not sure if this code snippet is formatted by Intellij or not. It would be better to have it like if possible:
```
return updateLargeFile(payer, fileName, byteString, signOnlyWithPayer, tinyBarsToOffer, 
                 op -> {}, op -> {});
```

File: test-clients/src/main/java/com/hedera/services/legacy/core/CustomProperties.java [hunk 4]
```diff
@@ -32,94 +32,107 @@
...
-    return rv;
-  }
+	/**
+	 * Retrieves the int value of the property matching the given name.
+	 *
+	 * @param name
+	 * 		the key of the property to be retrieved
+	 * @param defaultValue
+	 * 		default value to be returned if the named property does not exist or
+	 * 		the value retrieved is not a parsable integer which results in {@link NumberFormatException}
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/legacy/core/CustomProperties.java:105]: nit: line 105 is better to move after line 102.

File: test-clients/src/main/java/com/hedera/services/legacy/core/CustomProperties.java [hunk 5]
```diff
@@ -32,94 +32,107 @@
...
-    return rv;
-  }
+	/**
+	 * Retrieves the long value of the property matching the given name.
+	 *
+	 * @param name
+	 * 		the key of the property to be retrieved
+	 * @param defaultValue
+	 * 		default value to be returned if the named property does not exist or
+	 * 		the value retrieved is not a parsable long which results in {@link NumberFormatException}
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/legacy/core/CustomProperties.java:126]: Same here.

File: test-clients/src/main/java/com/hedera/services/legacy/file/FileServiceIT.java [hunk 6]
```diff
@@ -9,9 +9,9 @@
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
- * 
+ *
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/legacy/file/FileServiceIT.java:12]: for this and other legacy test clients, do we still need them? I thought they are already migrated to EET based clients already.

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java (hunk 3 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java:508]: I think it's the IntelliJ on Neeha's computer

File: test-clients/src/main/java/com/hedera/services/legacy/file/FileServiceIT.java (hunk 6 above)
Comment (qnswirlds) [reply test-clients/src/main/java/com/hedera/services/legacy/file/FileServiceIT.java:12]: May need another discussion and can be done in a separate PR if we decide to remove them

**Review by ljianghedera — DISMISSED** [review]
Overall LGTM.

File: test-clients/src/main/java/com/hedera/services/legacy/file/FileServiceIT.java (hunk 6 above)
Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/legacy/file/FileServiceIT.java:12]: Yeah, agree.

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java (hunk 3 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java]: @ljianghedera  @qnswirlds  Yes, my IntelliJ formatted the line. Fixed it. Thank you!

**Review by ljianghedera — APPROVED** [review]
LGTM!

**Review by qnswirlds — APPROVED** [review]
