### PR TITLE
Fix TxnRecordRegression

### LINKED ISSUE #8943: Fix TxnRecordRegression

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
Fix one of `TxnRecordRegression` tests.

**Related issue(s)**:

Fixes #8943 

**Notes for reviewer**:
Added @HapiTest annotation to `recordNotFoundIfNotInPayerState()` test, had to change the expected return to `INVALID_TRANSACTION_ID` as that is the implemented logic.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java [hunk 1]
```diff
@@ -101,13 +102,14 @@ private HapiSpec returnsInvalidForUnspecifiedTxnId() {
...
 
+    @HapiTest
     private HapiSpec recordNotFoundIfNotInPayerState() {
         return defaultHapiSpec("RecordNotFoundIfNotInPayerState")
                 .given(
                         cryptoCreate("misc").via("success"),
                         usableTxnIdNamed("rightAccountWrongId").payerId("misc"))
                 .when()
-                .then(getTxnRecord("rightAccountWrongId").hasCostAnswerPrecheck(RECORD_NOT_FOUND));
+                .then(getTxnRecord("rightAccountWrongId").hasCostAnswerPrecheck(INVALID_TRANSACTION_ID));
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java:112]: We should not be changing the response we are returning and comply with mono-service

Comment (rbair23) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java:112]: Correct, we need the test to stay the same, and for the modular node behavior to match mono service.

Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java]: Understood. Changes are applied.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM!
