### PR TITLE
Reduce duplication in Smart Contract Service

### LINKED ISSUE #74: Replace ScImpl with a standard ContractsController
Logically, the `SmartContractServiceImpl` class has the basic responsibility of forwarding gRPC messages to appropriate internal components. This needs to be isolated in a `ContractsController` analogous to the [`FileController`](https://github.com/swirlds/services-hedera/blob/dev/hedera-node/src/main/java/com/hedera/services/grpc/controllers/FileController.java).

### LINKED ISSUE #76: Refactor ScImpl#getTxRecordByContractID as an AnswerService in terms of HederaContracts
Given an injected instance of `HederaContracts`, the query-answering logic for a valid `ANSWER_ONLY` version of `ContractGetRecords` should amount to:

1. Extract the target contract from the query.
2. Obtain a `HederaAccount` via `contracts.get(id)`, catching any exception.
3. Provide a response from the `HederaAccount#records`/exception.

### LINKED ISSUE #77: Refactor ScImpl#contractGetInfo as an AnswerService in terms of HederaContracts
Given an injected instance of `HederaContracts`, the query-answering logic for a valid `ANSWER_ONLY` version of `ContractGetInfo` should amount to:

1. Extract the target contract from the query.
2. Recover a `HederaAccount` from `contracts.get(id)`, catching any exception.
3. Provide a response from the `HederaAccount`/exception.

### LINKED ISSUE #78: Refactor ScImpl#contractGetBytecode as an AnswerService in terms of HederaContracts
Given an injected instance of `HederaContracts`, the query-answering logic for a valid `ANSWER_ONLY` version of `ContractGetBytecode` should amount to:

1. Extract the target contract from the query.
2. Invoke `contracts.getBytecode(id)`, catching any exception.
3. Provide a response from the recoverd bytes/exception.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Closes #74, closes #76, closes #77, closes #78 
- Addresses #79, #81, #82, #83, #84 but does not close them.
- Addresses #104 (completes migration of all global/dynamic properties) but does not close it.

**Summary of the change**:
- Replace legacy `SmartContractServiceImpl` with a `ContractsController` that delegates queries to `AnswerService` implementations, and uses the standard submission flow for transactions. 
- Adapt each `SmartContractRequestHandler` method as a `TransitionLogic`; refactor all prechecks as `TransitionLogic.syntaxCheck` implementations, hence removing duplication between legacy handlers and `TransactionValidationUtils`/`AwareProcessLogic` components.
- Also adapt the `FreezeHandler` as a `TransitionLogic` to eliminate legacy record mapping from `AwareProcessLogic`.
- Refactor all contract-related global/dynamic properties.

**External impacts**:
- The required node payment for a `ContractCallLocal` query can be slightly higher now, since the prior code computed gas and non-gas fees separately (hence rounding down twice in two separate `tinycent -> tinybar` conversions); the refactored code only rounds down once.

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java [hunk 1]
```diff
@@ -128,6 +133,54 @@ public FeeObject estimateFee(SignedTxnAccessor accessor, JKey payerKey, StateVie
...
+				var payer = accessor.getPayer();
+				var cryptoTransferOp = accessor.getTxn().getCryptoTransfer();
+				var adjustments = cryptoTransferOp.getTransfers().getAccountAmountsList();
+				long cryptoTransferNet = 0L;
+				for (AccountAmount adjustment : adjustments) {
+					if (payer.equals(adjustment.getAccountID())) {
+						cryptoTransferNet += adjustment.getAmount();
+					}
+				}
+				return cryptoTransferNet;
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java:164]: Should this be ```return -cryptoTransferNet;```?

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+					.setNodedata(nonGasUsage.getNodedata().toBuilder().setGas(op.getGas()))
+					.build();
+			return ans;
+		} catch (Exception e) {
+			log.warn("Usage estimation unexpectedly failed for {}!", query, e);
+			throw new IllegalArgumentException(e);
+		}
+	}
+
+	ContractCallLocalResponse dummyResponse(ContractID target) {
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java:113]: This method is only used in this class, should it  be `private` ?

File: hedera-node/src/main/java/com/hedera/services/grpc/controllers/ContractController.java [hunk 3]
```diff
@@ -20,18 +20,108 @@
  * ‍
  */
 
-public class ContractController {
+import com.hedera.services.queries.answering.QueryResponseHelper;
+import com.hedera.services.queries.contract.ContractAnswers;
+import com.hedera.services.queries.crypto.CryptoAnswers;
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/grpc/controllers/ContractController.java:25]: This import statement is not needed.

File: hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+	}
+
+	@Override
+	public Function<TransactionBody, ResponseCodeEnum> syntaxCheck() {
+		return SYNTAX_CHECK;
+	}
+
+	public ResponseCodeEnum validate(TransactionBody freezeTxn) {
+		var op = freezeTxn.getFreeze();
+		if (!isValidTime(op.getStartHour(), op.getStartMin()) || !isValidTime(op.getEndHour(), op.getEndMin())) {
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java:89]: Is it possible for client to send freeze request with end time earlier than start time?

**Review by ljianghedera — APPROVED** [review]
LGTM overall.

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java:164]: For a `CryptoTransfer`, we can directly compute the affect on the payer (for example, if it sends `1_000 tinybar`, then `cryptoTransferNet=-1000`, or if it receives `500 tinybar`, then `cryptoTransferNet=+500`).

For the other operation types, we need to multiply a quantity by -1 to get the `cryptoTransferNet`, since in these cases there is some amount (`gas`, an `initialBalance`, or a `sent` amount) that will be **deducted from the payer**.

Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java:164]: Yeah. I realized that all amount in transfer list from this payer is negative. Thanks for the clarification.

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java:113]: I left the access level `package-private` because I wanted to call this method directly in tests.

Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java:113]: I noticed the unit test case you are calling this methods directly and I thought this method might be general util method used by other classes in this package as well.

File: hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java:89]: It seems we just rely on `Platform.setFreezeTime` to throw an exception if we pass the platform invalid parameters.

File: hedera-node/src/main/java/com/hedera/services/grpc/controllers/ContractController.java (hunk 3 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/grpc/controllers/ContractController.java:25]: Ah good catch, I'll remove those in a future PR so you don't need to re-approve 😁  (or if Quan requests changes, will remove the imports when addressing those).

File: hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java (hunk 4 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/txns/network/FreezeTransitionLogic.java:89]: So the platform will take care of the logic error, no need to repeat the logic here.  Makes sense.

**Comment by ljianghedera** [comment]
@tinker-michaelj thanks for addressing these minot issues. I think it's good to merge into master.

**Review by qnswirlds — DISMISSED** [review]
The changes look good to me in general. The test coverage increased significantly due to the refactoring, so great work! As pointed out by Codecov, there are some new lines that are not covered by tests, but those could definitely improved in a future PR. We still have all the smart contract integration tests from test-clients that were passing to give us confidence for this merge.

**Review by qnswirlds — APPROVED** [review]
Re-approve for the resolved merge conflicts and fix for `MerkleAccountTokens` deserialization.
