### PR TITLE
Privileges check

### LINKED ISSUE #6131: Design Facility for privileged transaction checks for modular services
There are a number of cases where we check for "privileged" accounts.  For security this "Privilege Check" should be called from a single point in Workflow rather than in multiple places or services.

1. This can all be handled in signature verification, or a single component called from signature verification.
   1. Documentation of the rules and requirements for this process is [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/privileged-transactions.md)
   1. The privileged account ID, for this purpose, is the account ID set in the transaction ID (sometimes called the payer account ID)
      - A privileged account is one of the following account IDs
         1. accounts.treasury
         1. accounts.systemAdmin
         1. accounts.addressBookAdmin
         1. accounts.feSchedulesAdmin
         1. accounts.exchangeRatesAdmin
         1. accounts.freezeAdmin
   1. If the transaction is a FileUpdate or FileAppend
      - If the target is a system file
         Check the privileged account key and file ID against the table, authorize only if the table indicates permitted, otherwise fail with UNAUTHORIZED.
      - The key associated with the target entity is not required to sign the transaction
         This means system files never need the entity key to sign the transaction, as entity signature is waived for accounts authorized to submit those transactions
   1. If the transaction is a "Privileged Transaction" as listed in the documented table
      - The privileged account ID must be permitted to submit the transaction as shown in the documented table, otherwise fail with UNAUTHORIZED
   1. If the transaction is a CryptoUpdate
      - If the target account is accounts.treasury
         1. If the privileged account ID is *not* accounts.treasury, fail with UNAUTHORIZED
      - If the target is any account strictly greater than accounts.treasury and less than or equal to ledger.numReservedSystemEntities
         1. If the privileged account ID is accounts.treasury or accounts.systemAdmin
            - The target account does not need to sign the transaction

- In all cases, the "is the correct account privileged" check is managed by workflow (or a component shared by the workflows) and need not reference any service handlers.
- At only one point is detailed information about the transaction needed, in most cases we only need what account is in the transaction ID, and the type of transaction.
- The one exception is whether a file to be modified is a "System File".
- Whether a file is a "System File" requires checking what file is referenced by a transaction (which is not complex) and checking that against configuration (not state).
- This information therefore can (and for security probably should) be determined by a specific component associated with hedera-app, not the FileService.
- If we wish to be pedantic about service implementations "owning" the transaction content, we can still require that FileService return the file(s) to be affected in the PreHandleResult (this is possibly required for signature verification regardless) and use that to determine if any is a "System File".

### PR DESCRIPTION
**Pull request by netopyr**
- Implementation of privileges check
- Ported test from mono-code
- Integrated into handle workflow

Closes #6131

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java [hunk 1]
```diff
@@ -0,0 +1,217 @@
...
+                    txBody.fileDeleteOrThrow().fileIDOrThrow().fileNum());
+            case CRYPTO_DELETE -> checkEntityDelete(
+                    txBody.cryptoDeleteOrThrow().deleteAccountIDOrThrow().accountNumOrThrow());
+            case CONTRACT_DELETE -> checkEntityDelete(
+                    txBody.contractDeleteInstanceOrThrow().contractIDOrThrow().contractNumOrThrow());
+
+            default -> SystemPrivilege.UNNECESSARY;
+        };
+    }
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java:104]: Will be good to have javadocs on all these methods, not a blocker for the PR.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+        final var configuration = configProvider.getConfiguration();
+        this.accountsConfig = configuration.getConfigData(AccountsConfig.class);
+        this.filesConfig = configuration.getConfigData(FilesConfig.class);
+        this.numReservedSystemEntities =
+                configuration.getConfigData(LedgerConfig.class).numReservedSystemEntities();
+    }
+
+    /**
+     * Checks whether an account is exempt from paying fees.
```
Comment (kimbor) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java:63]: This description is incorrect. The method checks whether an account is authorized to perform this action.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java (hunk 1 above)
Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/PrivilegesVerifier.java:104]: Good idea, will add it.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 3]
```diff
@@ -396,19 +404,33 @@ private ValidationResult validate(
...
             return new ValidationResult(PRE_HANDLE_FAILURE, e.responseCode());
         }
 
-        // Check the status and solvency of the payer
-        try {
-            final var payer = solvencyPreCheck.getPayerAccount(storeFactory, preHandleResult.payer());
-            solvencyPreCheck.checkSolvency(preHandleResult.txInfo(), payer, fees.totalWithoutServiceFee());
-        } catch (final PreCheckException e) {
-            return new ValidationResult(NODE_DUE_DILIGENCE_FAILURE, e.responseCode());
+        // Check if the payer has the required permissions
```
Comment (kimbor) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:422]: The difference between 'has the required permissions' and 'has the required privileges' is not very clear. Maybe add a link to https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/docs/privileged-transactions.md in the javadoc.

File: hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java [hunk 4]
```diff
@@ -0,0 +1,678 @@
...
+    @SuppressWarnings("DataFlowIssue")
+    @Test
+    void testConstructorWithIllegalParameters() {
+        assertThatThrownBy(() -> new PrivilegesVerifier(null)).isInstanceOf(NullPointerException.class);
+    }
+
+    @Test
+    void treasuryCanUpdateAllNonAccountEntities() {
+        // expect:
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 101));
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java:123]: These would be much clearer if the numbers were constants named for the "file" being tested (e.g. `ADDRESS_BOOK_NUM` or `THROTTLES_NUM`).

File: hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java [hunk 5]
```diff
@@ -0,0 +1,678 @@
...
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 102));
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 111));
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 112));
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 121));
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 122));
+        assertTrue(subject.canPerformNonCryptoUpdate(2, 123));
+        for (var num = 150; num <= 159; num++) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java:130]: This would be easier to comprehend if we used something line `MIN_UPGRADE_FILE` and `MAX_UPGRADE_FILE` as constants for the numbers.  Even better would be to read those values from the config so we don't have to change this code if/when the config defaults change.

File: hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java [hunk 6]
```diff
@@ -0,0 +1,678 @@
...
+import org.junit.jupiter.api.Test;
+
+// This test may look a little weird without context. The original test in mono is very extensive. To ensure that
+// we don't break anything, I copied the test from mono and hacked it a little to run it with the new code.
+// (It was a good thing. I discovered two bugs...) :)
+class PrivilegesVerifierTest {
+
+    private Wrapper subject;
+
+    private static class Wrapper {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/test/java/com/hedera/node/app/authorization/PrivilegesVerifierTest.java:67]: What do we gain using a wrapper here rather than directly calling methods for the class we intend to test?  It seems like unnecessary additional complexity (and opportunity to unintentionally skew results).
