### PR TITLE
fix: Add additional verification strategy for schedule delete facade calls

### LINKED ISSUE #22446: Investigate the behaviour of scheduleDelete facade call
It was reported that facade calling the scheduleDelete transaction is failing with either INVALID_SIGNATURE or UNAUTHORIZED. 

Transaction for reference: https://hashscan.io/testnet/transactionsById/0.0.7314364-1764755546-221926699

- Try reproducing the behaviour
- Investigate the impact and cause
- Estimate the outcome / Provide fix if plausible 
- Document the findings

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:

Added additional verification strategy covering the case when schedule was created with admin key different than contract id. Now we are able to delete the schedule from facade calls. 

**Related issue(s)**:

Fixes #22446 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/deleteschedule/DeleteScheduleTranslator.java [hunk 1]
```diff
@@ -129,4 +143,27 @@ public static long gasRequirement(
             @NonNull final AccountID payerId) {
         return systemContractGasCalculator.gasRequirement(body, DispatchType.SCHEDULE_DELETE, payerId);
     }
+
+    private static boolean isRedirectWithNonContractAdminKey(@NonNull HssCallAttempt attempt) {
```
Comment (gkozyryatskyy) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/deleteschedule/DeleteScheduleTranslator.java:147]: add javadoc and unit test for this function?

**Review by gkozyryatskyy — APPROVED** [review]
LGTM!

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/deleteschedule/DeleteScheduleTranslator.java [hunk 2]
```diff
@@ -66,11 +69,22 @@ public Optional<SystemContractMethod> identifyMethod(@NonNull final HssCallAttem
...
     @Override
     public Call callFrom(@NonNull final HssCallAttempt attempt) {
-        return new DispatchForResponseCodeHssCall(
-                attempt,
-                transactionBodyFor(scheduleIdFor(attempt)),
-                DeleteScheduleTranslator::gasRequirement,
-                attempt.keySetFor());
+        if (isRedirectWithNonContractAdminKey(attempt)) {
+            // Use a custom verification strategy that checks the admin key of the redirected schedule
+            // if the call is via the proxy and the schedule admin key is not a contract key
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/deleteschedule/DeleteScheduleTranslator.java:74]: Perhaps a note to indicate the use case - i.e when a schedule transaction has been created via HAPI with an admin key?

Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hss/deleteschedule/DeleteScheduleTranslator.java:74]: my note is trying to state that 😀  or at least I hoped it will. 
You think I should rephrase it?
