### PR TITLE
fix: create sidecar metadata before writing `RecordStreamFile` footer

### LINKED ISSUE #12090: (mod) Record files omit `SidecarMetadata`
### Description

I ran transactions that produced sidecar files.

But the `RecordStreamFile#sidecars()` metadata list was always empty.

### Steps to reproduce

As above.

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #12090 
 - Populate the `BlockRecordWriterV6#sidecarMetadata` field _before_ writing the corresponding `RecordStreamFile` "footer".
 - Bump HAPI proto version for record stream to `0.48.0`.

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java [hunk 1]
```diff
@@ -273,15 +273,14 @@ public void close(@NonNull final HashObject endRunningHash) {
...
 
+            closeSidecarFileWriter();
             writeFooter(endRunningHash);
 
             outputStream.close();
             bufferedOutputStream.close();
             if (gzipOutputStream != null) gzipOutputStream.close();
             fileOutputStream.close();
 
-            closeSidecarFileWriter();
```
Comment (steven-sheehy) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java:283]: There should be some test that verifies this. Both at the unit level and at the hapi spec level to verify e2e.

Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v6/BlockRecordWriterV6.java:283]: Created https://github.com/hashgraph/hedera-services/issues/12098 and will find a volunteer for it. 😇

**Review by steven-sheehy — APPROVED** [review]

**Review by mhess-swl — APPROVED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by nathanklick — APPROVED** [review]
