### PR TITLE
fix: add background traffic to `DabEnabledUpgradeTest`

### LINKED ISSUE #15220: Upgrade HAPI tests should use background traffic
### Description

`@HapiTest`'s run with an artificial 1 minute staking period; and the long sleeps in `DabEnabledUpgradeTest` can lead to a period passing without a single transaction.

Because this is an impossible condition in production with 24 hour staking periods, pending reward management does not take into account skipped periods and this leads to errors in the test logs.

### Steps to reproduce

Run `DabEnabledUpgradeTest` with `@Order(MAX_VALUE - 2)` so `LogValidationTest` comes next.

### Additional context

_No response_

### Hedera network

_No response_

### Version

multiple

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #15220

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! tyvm @tinker-michaelj

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java [hunk 1]
```diff
@@ -88,7 +87,7 @@
  * the config version is still zero.
  */
 @Tag(UPGRADE)
-@Order(MAX_VALUE)
+@Order(Integer.MAX_VALUE - 2)
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java:90]: This strange expression `Integer.MAX_VALUE - 2` appears in no other `@Order` so isn't obvious.  Why not leave a comment here explaining what it says in the underlying issue?  And is it `- 2` instead of `- 1` so that it preceeds `StreamValidationTest` in addition to `LogValidationTest`?

**Review by david-bakin-sl — APPROVED** [review]
LGTM with one suggestion for adding a comment to the code.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/system/DabEnabledUpgradeTest.java:90]: Ah yes I should add this detail @david-bakin-sl , will do in next PR. 🙏
