### PR TITLE
fix: 24569 Added new `LongList` implementation - `LongListSegment`

### LINKED ISSUE #24569: MemorySegment based implementation of LongList
`LongList` interface in MerkleDb has several implementations, including Java heap and off-heap lists. Off-heap implementation relies on `sun.misc.Unsafe` to close its index chunks, which are Java direct byte buffers.

With JDK 25 support, a new implementation can be provided, based on MemorySegments. It would combine native buffer benefits (as off-heap) and well defined API to manage buffer lifecycle (as on-heap).

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

Adds a new `LongList` implementation backed by `java.lang.foreign.MemorySegment` (JDK 22+), replacing `sun.misc.Unsafe` usage in `LongListOffHeap` with a supported API.

### What

`LongListSegment extends AbstractLongList<SegmentChunk> implements OffHeapUser`

- Per-chunk `Arena.ofShared()` for deterministic deallocation and concurrent access
- `VarHandle` on `ValueLayout.JAVA_LONG` for volatile reads/writes/CAS
- Catch-and-return on `IllegalStateException` for the reader-vs-closeChunk race (no locking on the hot path)
- Detached buffer copy in `writeLongsData` to decouple snapshot writes from arena lifecycle

### Why

`LongListOffHeap` relies on `sun.misc.Unsafe` (via `MemoryUtils`) for off-heap access and cleanup. `Unsafe` is unsupported and scheduled for removal. The FFM API provides equivalent semantics with a well-defined lifecycle model.

### Testing

- `LongListSegmentTest` — extends `AbstractLongListTest`, inherits all existing tests
- Full cross-compatibility matrix: segment ↔ heap ↔ off-heap ↔ disk (read/write)
- Added to `LongListValidRangeTest` and `LongListAdHocTest` providers
- Segment-specific memory cleanup verification via `getOffHeapConsumption()`

**Related issue(s)**:

Fixes #24569 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java [hunk 1]
```diff
@@ -200,15 +200,26 @@ void testClose() {
         }
         // Check all memory is freed after DB is closed, but skip for LongListDisk
         // as LongListDisk use file-based operations (FileChannel#write in LongListDisk#closeChunk)
-        // that don't immediately free memory due to OS-level caching
-        if (!(longList instanceof LongListDisk)) {
+        // that don't immediately free memory due to OS-level caching.
+        // Also skip for LongListSegment — FFM arena allocations are not tracked by the
+        // direct memory BufferPoolMXBean; they are verified separately below.
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java:205]: If for off-heap indexes we switch from "direct" memory to just "native" memory we need to reconsider how we configure `java`: we don't need to allocate a large amount of `-XX:MaxDirectMemorySize` any more and we may lose control over how much native memory we use causing unexpected oom-kills in various controlled environments.

Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java:205]: Yes, that is correct. We indeed need to stop reserving large amount of `-XX:MaxDirectMemorySize` because it will not be used as much anymore. Instead, we'll need to rely on what OS mechanism such as cgroup memory limits. 

We may need to monitory the memory consumption with `-XX:NativeMemoryTracking=summary` flag and `jcmd`. 

But ultimately, the best way to control it is on the application level - we know exactly the number of chunks and we know exactly the chunk size. Therefore, we can control the overall memory consumption.

Comment (OlegMazurov) [reply platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java:205]: At the very least this PR should include new values for `-XX:MaxDirectMemorySize` for every use in the repository.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java [hunk 2]
```diff
@@ -269,13 +269,13 @@ public HalfDiskHashMap(
             if (Files.exists(indexFile) && !forceIndexRebuilding) {
                 bucketIndexToBucketLocation = preferDiskBasedIndex
                         ? new LongListDisk(indexFile, bucketIndexCapacity, configuration)
-                        : new LongListOffHeap(indexFile, bucketIndexCapacity, configuration);
+                        : new LongListSegment(indexFile, bucketIndexCapacity, configuration);
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java:272]: Today we have only one config in MerkleDbConfig, whether to use disk indices or not. Do you think it would be better to change that config to a enum, so indices can be created on heap, off heap, on disk, or using memory segments?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java [hunk 3]
```diff
@@ -447,7 +447,7 @@ public void snapshot(final Path snapshotDirectory) throws IOException {
      */
     @Override
     public long getOffHeapConsumption() {
-        if (bucketIndexToBucketLocation instanceof LongListOffHeap offheapIndex) {
+        if (bucketIndexToBucketLocation instanceof LongListSegment offheapIndex) {
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java]: Should it be "instance of LongListOffHeap OR instance of LongListSegment"? Even better, the `getOffHeapConsumption()` method can be promoted to the `LongList` interface.

**Review by anthony-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java:205]: Would it be okay, if I do it in a separate PR?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java:272]: I don't think we really need it. Functionally `LongListSegment` is a drop-in replacement for `LongListOffHeap`. Once we confirm that `LongListSegment` works fine (or may be even better!), there will be no use for `LongListOffHeap`

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 4]
```diff
@@ -0,0 +1,391 @@
...
+     * {@link AbstractLongList#get(long, long)} returns when the chunk slot is already
+     * {@code null}.
+     */
+    @Override
+    protected long lookupInChunk(@NonNull final SegmentChunk chunk, final long subIndex) {
+        try {
+            return (long) LONG_HANDLE.getVolatile(chunk.segment(), subIndex * Long.BYTES);
+        } catch (final IllegalStateException e) {
+            // Arena was closed concurrently — chunk is outside the valid range
+            return IMPERMISSIBLE_VALUE;
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java:186]: Is it really possible?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java (hunk 3 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java]: > Even better, the getOffHeapConsumption() method can be promoted to the LongList interface.

Yes. Sounds good, I'll do it.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 5]
```diff
@@ -0,0 +1,391 @@
...
+     * removed from {@code chunkList} — the index is outside the valid range, and
+     * {@code AbstractLongList#putImpl} assertions (when enabled) would have caught
+     * the out-of-range access before reaching this point.
+     */
+    @Override
+    protected void putToChunk(@NonNull final SegmentChunk chunk, final int subIndex, final long value) {
+        try {
+            LONG_HANDLE.setVolatile(chunk.segment(), (long) subIndex * Long.BYTES, value);
+        } catch (final IllegalStateException e) {
+            // Arena was closed concurrently — chunk is outside the valid range, drop the write
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Is this really possible? If not, an exception should be thrown here rather just silently ignoring the issue

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 6]
```diff
@@ -0,0 +1,391 @@
...
+     * may still return stale values while adjacent entries already return zero. This is
+     * acceptable because {@code partialChunkCleanup} is called from
+     * {@link LongList#updateValidRange}, which has already moved the valid-range
+     * boundaries; any stale value a reader sees is for an index that is no longer valid,
+     * and the reader's own valid-range check will discard it. This is consistent with
+     * the behavior of {@link LongListOffHeap}, which uses non-volatile
+     * {@code MemoryUtils.setMemory} for the same operation.
+     *
+     * <p>If the chunk's arena has been closed concurrently (e.g. by {@link #close()}
+     * racing with an in-flight {@link LongList#updateValidRange}), the cleanup is
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java:245]: Is this race possible?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 7]
```diff
@@ -0,0 +1,391 @@
...
+    @Override
+    protected SegmentChunk readChunkData(
+            @NonNull final FileChannel fileChannel, final int chunkIndex, final int startIndex, final int endIndex)
+            throws IOException {
+        final SegmentChunk chunk = createChunk();
+        // Get a ByteBuffer view of the segment — backed by the same native memory, no copy
+        final ByteBuffer buf = chunk.segment().asByteBuffer().order(ByteOrder.nativeOrder());
+        readDataIntoBuffer(fileChannel, chunkIndex, startIndex, endIndex, buf);
+        // Reset position/limit — segment access is always by absolute offset
+        buf.clear();
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Is this really needed? MemorySegment is stateless, it doesn't have any "position" or "limit"

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 8]
```diff
@@ -0,0 +1,391 @@
...
+     * segment's backing memory is exposed as a {@link ByteBuffer} view for
+     * {@link FileChannel} compatibility, avoiding an extra copy.
+     */
+    @Override
+    protected SegmentChunk readChunkData(
+            @NonNull final FileChannel fileChannel, final int chunkIndex, final int startIndex, final int endIndex)
+            throws IOException {
+        final SegmentChunk chunk = createChunk();
+        // Get a ByteBuffer view of the segment — backed by the same native memory, no copy
+        final ByteBuffer buf = chunk.segment().asByteBuffer().order(ByteOrder.nativeOrder());
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Would it work, if a saved index file is moved from a little-endian machine to a big-endian one and loaded there?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 4 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java:186]: Yes, it is. 

Read path (get on the LongList):
A query thread loads a leaf record:
→ MerkleDbDataSource.loadLeafRecord(path)
→ pathToDiskLocationLeafNodes.get(path) to find the disk location
→ AbstractLongList.get(index, defaultValue)
→ chunkList.get(chunkIndex) — captures a SegmentChunk reference

Write path (updateValidRange on the LongList):
The flush thread processes dirty leaves:
→ MerkleDbDataSource.saveRecords(firstLeafPath, lastLeafPath, ...)
→ writeLeavesToPathToKeyValue(firstLeafPath, lastLeafPath, ...)
→ keyValueStore.updateValidKeyRange(firstLeafPath, lastLeafPath)
→ pathToDiskLocationLeafNodes.updateValidRange(firstLeafPath, lastLeafPath)
→ shrinkLeftSideIfNeeded(newMinValidIndex)
→ chunkList.compareAndSet(i, chunk, null) + closeChunk(chunk)

When the flush advances `firstLeafPath` (shrinking from the left), it removes chunks for paths that are no longer valid. A query thread would only look up a path if the virtual map still contains it. And the virtual pipeline ensures that by the time `saveRecords` is called, the current mutable copy already has the updated path range — old paths have been removed from the map.

But here's the thing: the query thread might have started its lookup before the flush, using a path that was valid at the start of the request. By the time it reaches `chunkList.get(chunkIndex)`, the flush has already advanced the boundary and closed the chunk. The read thread holds a reference to a dead `SegmentChunk`.

This same race exists today with `LongListOffHeap`. The same window exists between `chunkList.get` and `lookupInChunk`. With `LongListOffHeap`, the `Unsafe` read silently returns whatever bytes happen to be at the freed memory address. The caller gets back `IMPERMISSIBLE_VALUE` or a stale value, treats it as a cache miss, and recovers.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 9]
```diff
@@ -0,0 +1,391 @@
...
+        final int totalNumOfChunks = calculateNumberOfChunks(size());
+        final long currentMinValidIndex = minValidIndex.get();
+        final int firstChunkWithDataIndex = toIntExact(currentMinValidIndex / longsPerChunk);
+
+        // A confined arena for the temporary write buffer. Confined is sufficient because
+        // writeLongsData is a single-threaded operation (snapshot/flush), and it is cheaper
+        // than a shared arena. The buffer is decoupled from any chunk arena, so
+        // FileChannel.write never touches chunk-scoped memory directly.
+        try (final Arena writeArena = Arena.ofConfined()) {
+            final MemorySegment writeBufSegment = writeArena.allocate(memoryChunkSize, Long.BYTES);
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Why is this temp memory segment needed? Can the original segments be written directly (converting them to byte buffers, if needed)? If a temp buffer is really needed, can it be a byte buffer rather than a memory segment?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 7 above)
Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: The MemorySegment doesn't have a position or limit. But the buffer has. And ofBuffer() creates a segment from the buffer's position to its current limit. I've spent some time today fighting this issue in PBJ. Ended up doing duplicate().clear() to solve the problem.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 5 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: In this case your suspicion is correct - it's not possible, and the exception should be propagated.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 6 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java:245]: Yes, it is possible in the  context of compaction.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 8 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Likely, it would be broken. However, realistically it won't be problem. All the platforms we support - Mac, Linux, and Windows - are little-endian.

File: platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java:205]: Here is a follow-up ticket for the memory settings update https://github.com/hiero-ledger/hiero-consensus-node/issues/24743

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 8 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: I'm going to update it to LITTLE_ENDIAN to prevent the confusion.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 9 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: It was required based on the same assumption that I had in `put` method - it was guarding against possible race condition. But later I figured out that its not possible in our current workflows. I updated `put` method and I should update this as well.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java (hunk 3 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java]: Fixed

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 8 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: I replaced all the usages of `nativeOrder` with LITTLE_ENDIAN for the sake of consistency

**Review by thenswan — APPROVED** [review]

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 4 above)
Comment (artemananiev) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java:186]: OK, makes sense. Thanks

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 10]
```diff
@@ -0,0 +1,389 @@
...
+     * {@code null}.
+     */
+    @Override
+    protected long lookupInChunk(@NonNull final SegmentChunk chunk, final long subIndex) {
+        try {
+            return (long) LONG_HANDLE.getVolatile(chunk.segment(), subIndex * Long.BYTES);
+        } catch (final IllegalStateException e) {
+            // Arena was closed concurrently — chunk is outside the valid range
+            return IMPERMISSIBLE_VALUE;
+        } catch (final IndexOutOfBoundsException e) {
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: OK, IllegalStateException above is a legit case. What about this IOOBE? How / when is it possible?

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java [hunk 11]
```diff
@@ -0,0 +1,389 @@
...
+     * {@link AbstractLongList#putIfEqual(long, long, long)} that returns {@code false}
+     * when the chunk slot is already {@code null} — the chunk no longer participates
+     * in the valid range.
+     */
+    @Override
+    protected boolean putIfEqual(
+            @NonNull final SegmentChunk chunk, final int subIndex, final long oldValue, final long newValue) {
+        try {
+            return LONG_HANDLE.compareAndSet(chunk.segment(), (long) subIndex * Long.BYTES, oldValue, newValue);
+        } catch (final IllegalStateException e) {
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: My understanding is `putIfEqual()` lifecycle should be identical to `putToChunk()`, that is the exception should not be caught here, but propagated

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 7 above)
Comment (artemananiev) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: The buffer is thrown away in the end of this method, it doesn't make sense to clear its position / limit

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 10 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Yes, it's redundant. It's a debug code taken from `LongListOffHeap` which would help with identifying issues related to `Unsafe` class.

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 7 above)
Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: You mean it doesn't make sense to preserve/restore its position/limit? If there's not any other code that uses the buffer and relies on its position/limit, then indeed you can call clear() directly on its instance w/o duplicating it.

(In PBJ, I couldn't do that in the utility class because the latter is unaware of how the buffer is used outside of it.)

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 11 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: ok, fair enough. Fixed

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java (hunk 7 above)
Comment (imalygin) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListSegment.java]: Fixed
