### PR TITLE
fix: tokenClaimAirdrop throws NPE on null sender or receiver

### LINKED ISSUE #17095: NPE on tokenClaimAirdrop with AirdropId with null sender or receiver
### Description

When submitting a tokenClaimAirdrop transaction, if one of the PendingAirdropIds in the list has an empty senderId or receiverId then the transaction fails catastrophically.

### Steps to reproduce

Send a valid tokenAirdrop
Attempt a tokenClaimAirdop, but have an empty senderId or receiverId in the transaction

### Additional context

```
2024-12-17 20:51:10.957 ERROR 149  PreHandleWorkflowImpl - Possibly CATASTROPHIC failure while running the pre-handle workflow
java.lang.NullPointerException: Field receiverId is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
	at com.hedera.hapi.node.base.PendingAirdropId.receiverIdOrThrow(PendingAirdropId.java:192) ~[hapi-0.57.2.jar:?]
	at com.hedera.node.app.service.token.impl.handlers.TokenClaimAirdropHandler.preHandle(TokenClaimAirdropHandler.java:100) ~[app-service-token-impl-0.57.2.jar:?]
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchPreHandle(TransactionDispatcher.java:90) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.expandAndVerifySignatures(PreHandleWorkflowImpl.java:296) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.preHandleTransaction(PreHandleWorkflowImpl.java:239) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.prehandle.PreHandleWorkflow.preHandleTransaction(PreHandleWorkflow.java:64) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.lambda$preHandle$0(PreHandleWorkflowImpl.java:144) ~[HederaNode.jar:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:?]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
	at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.preHandle(PreHandleWorkflowImpl.java:141) ~[HederaNode.jar:?]
	at com.hedera.node.app.Hedera.onPreHandle(Hedera.java:842) ~[HederaNode.jar:?]
	at com.hedera.node.app.state.MerkleStateLifecyclesImpl.onPreHandle(MerkleStateLifecyclesImpl.java:94) ~[HederaNode.jar:?]
	at com.swirlds.platform.state.PlatformMerkleStateRoot.preHandle(PlatformMerkleStateRoot.java:166) ~[swirlds-platform-core-0.57.2.jar:?]
	at com.swirlds.platform.eventhandling.DefaultTransactionPrehandler.prehandleApplicationTransactions(DefaultTransactionPrehandler.java:88) ~[swirlds-platform-core-0.57.2.jar:?]
	at com.swirlds.common.wiring.component.ComponentWiring.lambda$bind$8(ComponentWiring.java:730) ~[swirlds-common-0.57.2.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bindConsumer$0(BindableInputWire.java:92) ~[swirlds-common-0.57.2.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.ConcurrentTask.exec(ConcurrentTask.java:66) [swirlds-common-0.57.2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

### Hedera network

testnet

### Version

0.57.2

### Operating system

None

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
When submitting a tokenClaimAirdrop transaction, if one of the PendingAirdropIds in the list has an empty `senderId` or `receiverId` then the transaction fails catastrophically. This PR fixes the problem and adds unit tests and hapi tests to verify the fix.

**Related issue(s)**:
Fixes #17095
Sister PR to develop: #17097

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java [hunk 1]
```diff
@@ -141,7 +142,12 @@ public class BodyIdClearingStrategy extends IdClearingStrategy<TxnModification>
             entry(
                     "proto.EthereumTransactionBody.call_data",
                     ExpectedResponse.atConsensus(INVALID_ETHEREUM_TRANSACTION)),
-            entry("proto.TokenUpdateNftsTransactionBody.token", ExpectedResponse.atIngest(INVALID_TOKEN_ID)));
+            entry("proto.TokenUpdateNftsTransactionBody.token", ExpectedResponse.atIngest(INVALID_TOKEN_ID)),
+            entry("proto.PendingAirdropId.receiver_id", ExpectedResponse.atIngest(INVALID_PENDING_AIRDROP_ID)),
+            entry(
+                    "proto.PendingAirdropId.fungible_token_type",
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java:148]: No precheck for this property was added, is that intentional?

**Review by lukelee-sl — APPROVED** [review]
LGTM.  Thanks for catching this.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java:148]: Yes, intentional. The field is not nullable in the protobuf so it shouldn't make it to ingest. If it does somehow get through, it will still be rejected during handle.
BTW @mhess-swl compliments on how thoroughly you review PRs.

Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/BodyIdClearingStrategy.java:148]: Ok great.
Thank you! :)

**Review by mhess-swl — APPROVED** [review]
