### PR TITLE
Use instantaneous capacity checks for gauges and `TraceabilityExportTask`

### LINKED ISSUE #6706: Gauge metric `consThroughputLimitsPercentUsed` does not display useful values
### Description

`ServicesStateManager` uses a dedicated thread to [update metric values](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ServicesStatsManager.java#L108) at regular intervals.

For throttle utilization gauges, this means calling the [`DeterministicThrottle.percentUsed(now)`](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java#L115) method on each throttle with a metric. The `percentUsed(Instant)` method will simulate draining capacity until the given time, and then returning what percent of bucket capacity is still used.

⚠️  Note that `now` is wall clock time in the `ServicesStateManager` thread. This is at least _reasonable_ for frontend throttles, whose `lastDecisionTime` is also a recent wall clock time. But for the consensus throttles, whose `lastDecisionTime` is a consensus time (which tends to lag clock time by a few seconds), this means `percentUsed(now)` will mostly return `0.0%`.

### Steps to reproduce

Observe the value of this stat while running some transactions against local node.

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #6706 
 - When setting a gauge metric for throttle utilization, instead of calling `percentUsed(Instant)` (which simulates leaking capacity until the given time), just sets the metric to utilization at the last decision time for the throttle.
 - 😢 Note the regrettable duplication in the `Gas*` variants; will not be fixed here.
 - Also switches the `freeToUsedRatio(Instant)` method to be an instantaneous measurement to fix an annoying problem that can surface in `TraceabilityExportTask`.

### CODE REVIEW

**Review by nickpoorman — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java [hunk 1]
```diff
@@ -105,18 +104,17 @@ private void registerTypeWith(
...
     private void update(
-            final Instant now,
             final List<DeterministicThrottle> activeThrottles,
             final GasLimitDeterministicThrottle gasThrottle,
             final Map<String, DoubleGauge> namedMetrics) {
         activeThrottles.forEach(throttle -> {
             final var name = throttle.name();
             if (namedMetrics.containsKey(name)) {
-                namedMetrics.get(name).set(throttle.percentUsed(now));
+                namedMetrics.get(name).set(throttle.instantaneousPercentUsed());
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java:113]: Shouldn't this change just be done for `handleThrottling.allActiveThrottles(), handleThrottling.gasLimitThrottle()` ?

Comment (tinker-michaelj) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java:113]: After thinking about it, I couldn't see any reason to treat frontend throttles differently. 🤔

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java:113]: I see . Makes sense
