### PR TITLE
Fix ValidateDuplicateTransactionAfterReconnect to set ledger.keepRecordsInState as true 

### LINKED ISSUE #936: Fix ValidateDuplicateTransactionAfterReconnect to have ledger.keepRecordsInState as true
**Summary**
Instead of setting `ledger.keepRecordsInState` as true for all the tests in regression, set the value to true for `ValidateDuplicateTransactionAfterReconnect` as it is needed for the test `TransactionHistory-Reconnect-1-12m.json`

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #936 

Related regression PR : https://github.com/swirlds/swirlds-platform-regression/pull/765
**Summary of the change**:
Instead of setting `ledger.keepRecordsInState` as true for all the tests in regression, set the value to true for `ValidateDuplicateTransactionAfterReconnect` as it is needed for the test `TransactionHistory-Reconnect-1-12m.json`

Passed Reconnect test : 
`TransactionHistory-Reconnect-1-12m` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609954937441200
Passed other reconnect tests : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609953504440500

### CODE REVIEW

**Review by cesaragv — APPROVED** [review]

**Review by ljianghedera — APPROVED** [review]
LGTM

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java [hunk 1]
```diff
@@ -62,7 +63,10 @@ private HapiApiSpec validateDuplicateTransactionAfterReconnect() {
 						sleepFor(Duration.ofSeconds(25).toMillis()),
 						getAccountBalance(GENESIS)
 								.setNode("0.0.6")
-								.unavailableNode()
+								.unavailableNode(),
+						fileUpdate(APP_PROPERTIES)
+								.payingWith(ADDRESS_BOOK_CONTROL)
+								.overridingProps(Map.of("ledger.keepRecordsInState", "true"))
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java:69]: Isn't `ledger.keepRecordsInState` in `bootstrap.properties` instead of `application.properties`? I wonder if this property is dynamically updated via a fileUpdate of `application.properties`. @tinker-michaelj, could you please confirm?

Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java:69]: @qnswirlds When discussed with @tinker-michaelj, though `ledger.keepRecordsInState` shows its set in `bootstrap.properties` in `hgcaa.log` , the default value is taken from Global/Dynamic properties , so we can override in `application.properties`.

**Review by qnswirlds — APPROVED** [review]
