### PR TITLE
Fix tests in unique token management spec

### LINKED ISSUE #9460: Fix remaining tests for UniqueTokenManagementSpecs
UniqueTokenManagementSpecs
- [ ] mintUniqueTokenReceiptCheck
- [ ] uniqueWipeFailsWhenInvokedOnFungibleToken
- [x] populatingMetadataForFungibleDoesNotWork
- [x] commonWipeFailsWhenInvokedOnUniqueToken
- [x] serialNumbersOnlyOnFungibleBurnFails

passing on branch `9446-add-pureChecks`

### PR DESCRIPTION
**Pull request by mhess-swl**
Closes #9460

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java [hunk 1]
```diff
@@ -772,7 +772,8 @@ private HapiSpec uniqueWipeFailsWhenInvokedOnFungibleToken() { // invokes unique
                                 .hasKnownStatus(INVALID_WIPING_AMOUNT)
                                 .via("wipeTx"),
                         wipeTokenAccount(A_TOKEN, ACCOUNT, List.of())
-                                .hasKnownStatus(OK)
+                                .hasPrecheck(OK)
+                                .hasKnownStatus(SUCCESS)
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java:776]: `hasKnownStatus(OK)` makes no sense because it is not a final status, merely a precheck status. Mono service, oddly enough, passes either way, so we'll go with the test that makes sense.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java [hunk 2]
```diff
@@ -185,7 +185,11 @@ protected Map<TokenID, List<NftTransfer>> nftChangesFrom(
             // will be explicitly set as 0.0.0
             final var builder = NftTransfer.newBuilder();
             if (modifiedNft != null) {
-                builder.receiverAccountID(modifiedNft.ownerId());
+                if (modifiedNft.hasOwnerId()) {
+                    builder.receiverAccountID(modifiedNft.ownerId());
+                } else {
+                    builder.receiverAccountID(token.treasuryAccountId());
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java:191]: I saw this change in one other PR also from Limechain 🤔  I believe we need to set sender to 0.0.0 if persistedNft is null on line 182

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java:776]: We don't need `.hasPrecheck(OK)` , since we are asserting `.hasKnownStatus(SUCCESS)`

Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java]: Done

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java (hunk 2 above)
Comment (mhess-swl) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java:193]: Done

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java [hunk 3]
```diff
@@ -813,28 +815,31 @@ private HapiSpec mintUniqueTokenReceiptCheck() {
...
                                         1,
                                         tokenTransferList.getNftTransfersList().size());
-                                tokenTransferList.getNftTransfersList().stream().forEach(nftTransfers -> {
+                                tokenTransferList.getNftTransfersList().forEach(nftTransfers -> {
                                     Assertions.assertEquals(
-                                            AccountID.getDefaultInstance(), nftTransfers.getSenderAccountID());
+                                            AccountID.newBuilder()
+                                                    .setAccountNum(0)
+                                                    .build(),
+                                            nftTransfers.getSenderAccountID());
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java:834]: Both mono and mod code fail when this assertion checks for `AccountID.getDefaultInstance()`, and both pass when we change to account 0.0.0. Not sure how this is passing in CI checks on mono service 😬

Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java:834]: 👍

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by jsync-swirlds — APPROVED** [review]

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by kimbor — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java (hunk 3 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java:834]: > Not sure how this is passing in CI checks on mono service 😬

Easy---it's not running in CI! 😝
