### PR TITLE
9839 Prevented possible NPE caused by a race condition

### LINKED ISSUE #9839: `DataFileCollectionTest#merge` fails non-deterministially
### Description

On some rare occasions `DataFileCollectionTest#merge` may fail due to a race condition between reading and compacting threads. 

Specifically, reading thread enters method `DataFileCollection#readDataItemBytes`, gets an instance of `DataFileReader` using method `DataFileCollection#readerForDataLocation` (this method checks if the underlying file channel is open) and then compacting thread closes this reader. The subsequent attempts to use this reader result in the following exception: 
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.channels.FileChannel.read(java.nio.ByteBuffer, long)" because "fileChannel" is null	
at com.swirlds.merkledb.utilities.MerkleDbFileUtils.completelyRead(MerkleDbFileUtils.java:91)	
at com.swirlds.merkledb.files.DataFileReader.read(DataFileReader.java:383)	
at com.swirlds.merkledb.files.DataFileReader.readDataItemBytes(DataFileReader.java:194)	
at com.swirlds.merkledb.files.DataFileCollection.readDataItem(DataFileCollection.java:491)	
at com.swirlds.merkledb.files.DataFileCollection.retryReadUsingIndex(DataFileCollection.java:513)	
at com.swirlds.merkledb.files.DataFileCollection.readDataItemUsingIndex(DataFileCollection.java:598)	
at com.swirlds.merkledb.files.DataFileCollectionTest.lambda$merge$10(DataFileCollectionTest.java:403)	
```

To prevent that, we need to have a null check in `DataFileReader#read`. Also, callers of this method should be aware that the method can return null. `DataFileCollection#retryReadUsingIndex` in its turns is already capable of handling nulls - it will retry on it, and that will help. 

### Steps to reproduce

1. Run DataFileCollectionTest
2. Hope for the best

### Additional context

_No response_

### Hedera network

other

### Version

v0.45

### Operating system

None

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This change prevents possible NPE described in #9839 Instead, the method returns null and other methods pass that null to the point where it's retried on (see `DataFileCollection#retryReadUsingIndex`)

**Related issue(s)**:

Fixes #9839 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java [hunk 1]
```diff
@@ -376,6 +379,11 @@ private ByteBuffer read(final long byteOffsetInFile, final int bytesToRead) thro
         for (int retries = 3; retries > 0; retries--) {
             final int fcIndex = leaseFileChannel();
             final FileChannel fileChannel = fileChannels.get(fcIndex);
+            if (fileChannel == null) {
```
Comment (jsync-swirlds) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java:382]: Do we need to check if the file channel is actually open here (e.g. ` || !filChannel.isOpen()`)?

**Review by jsync-swirlds — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java:382]: I don't think we need this condition. If this code even encounters a closed channel, it processes the exception here:
```
            } catch (final ClosedChannelException e) {
                // This exception may be thrown, if the channel was closed, because a different
                // thread reading from the channel was interrupted. Re-create the file channel
                // and retry
                reopenFileChannel(fcIndex, fileChannel);
            } 
```
