### PR TITLE
fix(23397): Fix BlockingResourceProvider blocks if no consumer is waiting

### LINKED ISSUE #23397: flake in ReconnectControllerTest.testMultiplePeersReportBeforeThreshold()
```
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>	
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)	
•••
at com.swirlds.platform.reconnect.ReconnectControllerTest.testMultiplePeersReportBeforeThreshold(ReconnectControllerTest.java:451)	
•••
Output View rawDownload raw
Random seed: -2803851248005077945L	
Random seed: 7889956098744681602L
```

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
Fix a specific scenario in the BlockingResourceProvider where if no consumer is waiting, a provider would block indefinitely. 
Also fixes another scenario where forced the consumer to retry the wait on the resource to release the provider in case of receiving an interruption.
Improves BlockingResourceProvider documentation.
Fixes ReconnectControllerTest flakiness and possible testing a different scenario than intended.

**Related issue(s)**:

Fixes #23397

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/base-concurrent/src/main/java/org/hiero/base/concurrent/BlockingResourceProvider.java [hunk 1]
```diff
@@ -106,12 +126,18 @@ public LockedResource<T> waitForResource() throws InterruptedException {
                 resourceProvided.await();
             }
             return resource;
+        } catch (final InterruptedException e) {
+            // Makes sure that, in case the consumer was interrupted we close the resource to allow
+            // the provider to gracefully continue its operations
+            // The provided resource will no longer be available
+            resource.close();
```
Comment (lpetrovic05) [inline platform-sdk/base-concurrent/src/main/java/org/hiero/base/concurrent/BlockingResourceProvider.java:140]: this seems to have changed from yesterdays discussion

Comment (mxtartaglia-sl) [reply platform-sdk/base-concurrent/src/main/java/org/hiero/base/concurrent/BlockingResourceProvider.java:140]: Analyzed a little further.
BlockingResourceProvider maintains a boolean state indicating if its waiting for a resource or not. If that boolean is true, it allows providers to request permits, it will deny permits otherwise. That boolean can be queried but can it is only queried on test code. In an error situation as the one we analyzed yesterday, the boolean flag will be false (the BlockingResourceProvider is not waiting for a resource yet), if the consumer calls waitForResource, that method will set the flag back to true, but since the resource was provided before the exception, it will almost immediately set it back to false, but that opens the door to another possible situation where just for one moment a provider could receive a permit. 
My reasoning is the next:  Just to avoid this situation, if the error happens in this class, closing the resource and not forcing the retry is our safest option, if it happens somewhere else, then it is the responsibility of the consumer.

Comment (lpetrovic05) [reply platform-sdk/base-concurrent/src/main/java/org/hiero/base/concurrent/BlockingResourceProvider.java:140]: ok
