### PR TITLE
fix: support all 10 upgrade files from 150-159

### LINKED ISSUE #10335: update FileService to support all upgrade files from 150-159
The current Modular File Service code only handles file 150 as an "Upgrade" file.
We must support files 150-159 (or whichever range is read from the filesConfig.softwareUpdateRange configuration).

The File Service handlers and upgrade store must be updated to read and support the configured range of file ID values for the "Upgrade" file(s).

### PR DESCRIPTION
**Pull request by povolev15**
Fix to support all 10 upgrade files from 150-159

**Related issue(s)**:

Fixes #10335

### CODE REVIEW

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeFileStore.java [hunk 1]
```diff
@@ -50,24 +52,32 @@ public class WritableUpgradeFileStore extends ReadableUpgradeFileStoreImpl {
      */
     public WritableUpgradeFileStore(@NonNull final WritableStates states) {
         super(states);
-        writableUpgradeState = requireNonNull(states.getQueue(getStateKey()));
+        this.states = requireNonNull(states);
         writableUpgradeFileState = requireNonNull(states.get(BLOBS_KEY));
     }
 
-    public void add(@NonNull final File file) {
+    public void add(@NonNull final File file, @NonNull final FileID fileID) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeFileStore.java:59]: The fileID parameter is no longer needed or used in this method.

**Review by jsync-swirlds — COMMENTED** [review]
Just a couple small items.

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeFileStore.java (hunk 1 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeFileStore.java:59]: removed thanks

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/FileGenesisSchema.java [hunk 2]
```diff
@@ -78,18 +80,38 @@ public class FileGenesisSchema extends Schema {
...
-        return Set.of(
-                StateDefinition.onDisk(BLOBS_KEY, FileID.PROTOBUF, File.PROTOBUF, MAX_FILES_HINT),
-                StateDefinition.queue(UPGRADE_DATA_KEY, ProtoBytes.PROTOBUF));
+        Set<StateDefinition> definitions = new LinkedHashSet<>();
+        definitions.add(StateDefinition.onDisk(BLOBS_KEY, FileID.PROTOBUF, File.PROTOBUF, MAX_FILES_HINT));
+
+        final var filesConfig = configProvider.getConfiguration().getConfigData(FilesConfig.class);
+        final var hederaConfig = configProvider.getConfiguration().getConfigData(HederaConfig.class);
+        final var fileNums = filesConfig.softwareUpdateRange();
+        final var firstUpdateNum = fileNums.left();
```
[the remark this answers is not in the document]
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/FileGenesisSchema.java:101]: I changed it. thanks

**Review by jsync-swirlds — DISMISSED** [review]

**Review by jsync-swirlds — DISMISSED** [review]

File: hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java [hunk 3]
```diff
@@ -81,6 +81,8 @@ class FreezeHandlerTest {
     @Mock(strictness = LENIENT)
     private Account account;
 
+    private final FileID fileUpgradeFileId = FileID.newBuilder().fileNum(150L).build();
+
```
Comment (kimbor) [inline hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java:85]: It would be good to have a test for other file Ids too, both valid and invalid range

Comment (povolev15) [reply hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java:85]: sure I will add some tests

**Review by cody-littley — DISMISSED** [review]
I'm not a code owner of any files in the latest diff. Approving because github isn't smart enough to remove me from the list of required reviewers.

**Review by jsync-swirlds — APPROVED** [review]

**Review by jeromy-cannon — DISMISSED** [review]

File: hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java [hunk 4]
```diff
@@ -287,6 +291,35 @@ void rejectOnInvalidFile() throws IOException {
         }
     }
 
+    @Test
+    void rejectInvalidFileId() throws IOException {
+        // these freeze types require a valid update file to have been set via FileService
+        FreezeType[] freezeTypes = {PREPARE_UPGRADE, TELEMETRY_UPGRADE};
+
+        //        // set up the file store to return a fake upgrade file
```
Comment (kimbor) [inline hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java:299]: Remove this commented out code

**Review by kimbor — APPROVED** [review]
One small nit. I approved.

File: hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java (hunk 3 above)
Comment (kimbor) [reply hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java:89]: Looks good

File: hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java (hunk 4 above)
Comment (povolev15) [reply hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java:299]: I will fix it in the next PR.

**Review by kimbor — APPROVED** [review]

**Review by jsync-swirlds — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
Nice work @povolev15 , tyvm! 

We would get some nice readability benefits if `LongPair` had a `boolean contains(long)` method. 🤔

**Review by edward-swirldslabs — APPROVED** [review]

**Review by jeromy-cannon — APPROVED** [review]
