### PR TITLE
Fix Schedule Service to compile and pass unit tests with PBJ

### LINKED ISSUE #5623: PBJ updates round 2 hedera-schedule-service

### PR DESCRIPTION
**Pull request by jsync-swirlds**
**Description**:

 * Small changes for correct serialization in the MonoSchedulingStateAdapterCodec.
 * Added missing imports and fixed method name change in ScheduleServiceImpl.
 * Updated test base class to make compatible with intensified non-null requirements.
 * Updated several tests to set mocking up better; the intensified non-null requirements require more mocks to return values.
 * Adjusted serialization/deserialization testing to work with PBJ DataIO classes.
 * Suppressed some unnecessary warnings in test classes
 * Removed, for now, two tests for not-in-whitelist transactions.
    * Those didn't actually test what was claimed, and what was tested, missing keys, throws NPE now, rather than failing.
    * Added `@todo` comments to create proper tests for non-whitelisted transactions

**Related issue(s)**:

Fixes #5623

### CODE REVIEW

**Review by povolev15 — APPROVED** [review]
LGTM

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/serdes/MonoSchedulingStateAdapterCodec.java [hunk 1]
```diff
@@ -17,33 +17,32 @@
...
     @Override
     public MerkleScheduledTransactionsState parse(final @NonNull ReadableSequentialData input) throws IOException {
-        if (input instanceof SerializableDataInputStream in) {
-            final var context = new MerkleScheduledTransactionsState();
-            context.deserialize(in, MerkleScheduledTransactionsState.CURRENT_VERSION);
-            return context;
-        } else {
-            throw new IllegalArgumentException("Expected a SerializableDataInputStream");
-        }
+        return new MerkleScheduledTransactionsState(input.readLong());
```
Comment (mhess-swl) [inline hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/serdes/MonoSchedulingStateAdapterCodec.java:30]: This read and the write below look pretty different than what was originally here. That's fine as long as we didn't miss anything

File: hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java [hunk 2]
```diff
@@ -83,37 +79,39 @@ void scheduleDeleteHappyPath() throws DecoderException {
     }
 
     @Test
-    // when schedule id to delete is not found, fail with INVALID_SCHEDULE_ID
+        // when schedule id to delete is not found, fail with INVALID_SCHEDULE_ID
```
Comment (mhess-swl) [inline hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java:82]: Whitespace? A couple instances of this. Definitely not a big deal, just wondered if it's intentional

File: hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java [hunk 3]
```diff
@@ -40,40 +40,36 @@
 import org.apache.commons.codec.DecoderException;
 import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
+import org.mockito.BDDMockito;
 import org.mockito.Mock;
+import org.mockito.Mockito;
+import org.mockito.exceptions.misusing.UnnecessaryStubbingException;
```
Comment (mhess-swl) [inline hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java:46]: I didn't see this class used anywhere. Necessary to import?

File: hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java (hunk 2 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java:82]: Spotless likes to add extra indentation to line comments.

File: hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java (hunk 3 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java:46]: Thanks; this is leftover from fixing Mokito's overly sensitive stubbing analysis.
Removed.

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/serdes/MonoSchedulingStateAdapterCodec.java (hunk 1 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/serdes/MonoSchedulingStateAdapterCodec.java:30]: The MerkleScheduledTransactionsState does the same in its serialize.  It's not perfect, but would require rewriting the original object in MonoService to make the serialization take PBJ DataIO to fix more cleanly.  As functionality is moved out of MonoService, this should definitely be revisited.

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleSignHandlerTest.java [hunk 4]
```diff
@@ -104,12 +104,11 @@ void scheduleSignFailsIfScheduleMissing() {
     @Test
     void scheduleSignVanillaWithOptionalPayerSet() {
         final var txn = scheduleSignTransaction();
-        givenSetupForScheduleSign(txn);
+        scheduledTxn = givenSetupForScheduleSign(txn);
```
[the remark this answers is not in the document]
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleSignHandlerTest.java:107]: It's used in some of the sub methods (it's a class attribute).  I tried removing it, and things broke.  Before, it was inconsistent whether the return value was used, and hidden that setting up the givens modified scheduledTxn; these changes at least make it consistent and visible (which helped me figure out why the unit tests were doing very odd things at times).
