### PR TITLE
Fix fee calculation for TokenWipe and TokenBurn

### LINKED ISSUE #8760: Tests failing with `feeData` null error
### Problem

When trying to execute tests which include `TokenBurn` or `TokenWipe` operations, they all fail with `feeData` null exception

### Solution

Fix errors by adding logic for fee calculation to check for tokenType

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by georgi-l95**
**Description**:
This PR adds logic to the fee calculation for TokenWipe and TokenBurn to check for token type, which will be then used for  selection from the feeDataMap

**Related issue(s)**:

Fixes #8760 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java [hunk 1]
```diff
@@ -194,9 +194,15 @@ public void handle(@NonNull final HandleContext context) throws HandleException
     @Override
     public Fees calculateFees(@NonNull final FeeContext feeContext) {
         final var op = feeContext.body();
+        final var readableTokenStore = feeContext.readableStore(ReadableTokenStore.class);
+        final var tokenType =
+                readableTokenStore.get(op.tokenWipeOrThrow().tokenOrThrow()).tokenType();
         final var meta = TOKEN_OPS_USAGE_UTILS.tokenWipeUsageFrom(fromPbj(op));
         return feeContext
-                .feeCalculator(SubType.DEFAULT)
+                .feeCalculator(
```
Comment (netopyr) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java:202]: Do we have to take into account if the token has custom fees and eventually use `TOKEN_FUNGIBLE_COMMON_WITH_CUSTOM_FEES` and `TOKEN_NON_FUNGIBLE_UNIQUE_WITH_CUSTOM_FEES`?

Comment (georgi-l95) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java:202]: In the feeDataMap for both `TOKEN_BURN` and `TOKEN_ACCOUNT_WIPE` only subTypes available are `TOKEN_FUNGIBLE_COMMON` and `TOKEN_NON_FUNGIBLE_UNIQUE`. So judging by this I'd say we don't need to worry about custom fees. But won't hurt for someone else to confirm, just to be sure.

**Review by netopyr — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — COMMENTED** [review]
Approving post merge. Thanks @georgi-l95
