### PR TITLE
Fix previewnet bugs

### LINKED ISSUE #1783: PREVIEWNET Regression: Can Accidentally Burn Tokens by sending from treasury to previously disassociated contract address.
### Description

Tried to transfer a token to a contract that was no longer associated, expected the transfer to fail, it returned success, however the tokens were removed from the treasury and not added to the contract's account balance.

### Steps to reproduce

Create a Treasury Account
Create a Token
Create a Contract
Associate Token with Contract
Disassociate Token from Contract
Attempt to Send Tokens from Treasury to Contract (This call should fail but does not)
Get token Balances for Contract and Treasury
The treasury has deducted the amount of transfer, but it is not credited to the contract account, affectively burned.

### Additional context

Test Log:

```
 Dissociate Tokens: Can Dissociate token from Contract Consent
  No source available
   Duration: 28.3 sec

  Standard Output: 
    STARTING SETUP: Test Account Instance
    7/9/2021 11:35:44 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830544", "nanos": 9255000 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ed25519": "7OH1xdi4zG4mYp7X4e71lUaT6bwEWu1ZwT9MFBp/LkQ=" }, "initialBalance": "17", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "sh7jGt&9h$lLkFwe" } }
    7/9/2021 11:35:44 AM  └─ SIG → { "sigPair": [ { "ed25519": "bBTDq4rhxN+lqFMkuGnLPdKDWBam6ZHFcIR/aDMQ13jqouclIRtBuf7v5vaanfKmR/fVVSBwbE+AG/yA26HbAQ==" } ] }
    7/9/2021 11:35:44 AM  RX:(00)  { }
    7/9/2021 11:35:44 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830544", "nanos": 9255000 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:44 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:45 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:45 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:46 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "11360" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:35:46 AM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625830544", "nanos": 9255000 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:46 AM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/9/2021 11:35:46 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830546", "nanos": 346805800 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/9/2021 11:35:46 AM  ├─ SIG → { "sigPair": [ { "ed25519": "umVQ7i7edR7+6qHSMiiPC4kALSq84pKk0BlK4uUhXeLtfbMVWyCvnw4KewvEUGcSi1GzGDWFvuNvGl8zxYm3BQ==" } ] }
    7/9/2021 11:35:46 AM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnEKEwoMCJLpoIcGEKisr6UBEgMYjxUSAhgDGID4gq0WIgIIeDI3VGVzdCBBY2NvdW50IEluc3RhbmNlOiBDcmVhdGluZyBUZXN0IEFjY291bnQgb24gTmV0d29ya3ITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQLplUO4u3nUe/uqh0jIojwuJAC0qvOKSpNAZSuLlIV3i7X2zFVsgr58OCnsLxFBnEotRsxg1hb7jbxpfM8WJtwU=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625830544", "nanos": 9255000 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:46 AM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "11360" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "NydBlJ8nXg8X7/jpSTmjQKOi7M/gyd0tG1BDBxjfoxZTyExk8/v7GNLRw6HWGR/W", "consensusTimestamp": { "seconds": "1625830545", "nanos": 479771000 }, "transactionID": { "transactionValidStart": { "seconds": "1625830544", "nanos": 9255000 }, "accountID": { "accountNum": "2703" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "41962034", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2035403" }, { "accountID": { "accountNum": "98" }, "amount": "39926631" }, { "accountID": { "accountNum": "2703" }, "amount": "-41962051" }, { "accountID": { "accountNum": "11360" }, "amount": "17" } ] } } } }
    SETUP COMPLETED: Test Account Instance
    STARTING SETUP: Creating Greeting Contract Instance
    7/9/2021 11:35:46 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830546", "nanos": 400472500 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Greeting Contract Create: Uploading Contract File MfguhWZvK7", "fileCreate": { "expirationTime": { "seconds": "1633720546", "nanos": 394823500 }, "keys": { "keys": [ { "ed25519": "QhhXFLXXQqICyi9r5ufjbXQooO4XG4Ggw7XLsBbz2uE=" } ] }, "contents": "MHg2MDgwNjA0MDUyMzQ4MDE1NjEwMDEwNTc2MDAwODBmZDViNTAzMzYwMDA4MDYxMDEwMDBhODE1NDgxNzNmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmMDIxOTE2OTA4MzczZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZjE2MDIxNzkwNTU1MDYxMDFiZTgwNjEwMDYwNjAwMDM5NjAwMGYzZmU2MDgwNjA0MDUyMzQ4MDE1NjEwMDEwNTc2MDAwODBmZDViNTA2MDA0MzYxMDYxMDA1MzU3NjAwMDM1N2MwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwOTAwNDgwNjM0MWMwZTFiNTE0NjEwMDU4NTc4MDYzY2ZhZTMyMTcxNDYxMDA2MjU3NWI2MDAwODBmZDViNjEwMDYwNjEwMGU1NTY1YjAwNWI2MTAwNmE2MTAxNTU1NjViNjA0MDUxODA4MDYwMjAwMTgyODEwMzgyNTI4MzgxODE1MTgxNTI2MDIwMDE5MTUwODA1MTkwNjAyMDAxOTA4MDgzODM2MDAwNWI4MzgxMTAxNTYxMDBhYTU3ODA4MjAxNTE4MTg0MDE1MjYwMjA4MTAxOTA1MDYxMDA4ZjU2NWI1MDUwNTA1MDkwNTA5MDgxMDE5MDYwMWYxNjgwMTU2MTAwZDc1NzgwODIwMzgwNTE2MDAxODM2MDIwMDM2MTAxMDAwYTAzMTkxNjgxNTI2MDIwMDE5MTUwNWI1MDkyNTA1MDUwNjA0MDUxODA5MTAzOTBmMzViNjAwMDgwOTA1NDkwNjEwMTAwMGE5MDA0NzNmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmMTY3M2ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmYxNjMzNzNmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmMTYxNDE1NjEwMTUzNTczMzczZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZjE2ZmY1YjU2NWI2MDYwNjA0MDgwNTE5MDgxMDE2MDQwNTI4MDYwMGQ4MTUyNjAyMDAxN2Y0ODY1NmM2YzZmMmMyMDc3NmY3MjZjNjQyMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwODE1MjUwOTA1MDkwNTZmZWExNjU2MjdhN2E3MjMwNTgyMDc3ZmJlYzQ5ZjY0ZWRhMjNjYjUyNjI3NTA4OGY2NWMxZmM3ZThkMDAyYjQ2ODFlMDk4ZjE4MjkyNzkxY2Q5NGIwMDI5" } }
    7/9/2021 11:35:46 AM  └─ SIG → { "sigPair": [ { "ed25519": "T862XKSMjZZvvvaSvw0asqx71IxwPHIkvzHGUidYkvXhN11SG51XVFXoTOYAcLR11b5+lQqRHdA7QfGIvsuGBA==" } ] }
    7/9/2021 11:35:46 AM  RX:(00)  { }
    7/9/2021 11:35:46 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830546", "nanos": 400472500 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:46 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:46 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:47 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:47 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:48 AM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "fileID": { "fileNum": "11361" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:35:48 AM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625830546", "nanos": 400472500 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:48 AM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/9/2021 11:35:48 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830548", "nanos": 649076400 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Greeting Contract Create: Uploading Contract File MfguhWZvK7", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/9/2021 11:35:48 AM  ├─ SIG → { "sigPair": [ { "ed25519": "8uptpbIegIASR0CaIvkQWvA5ZgF5oV33U9XnPnE+ZP3jKmyZBbBt1XD+pjMiV0R8K/vwEVgVcsoblvGYU8O9Cg==" } ] }
    7/9/2021 11:35:48 AM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnYKEwoMCJTpoIcGELC9wLUCEgMYjxUSAhgDGID4gq0WIgIIeDI8R3JlZXRpbmcgQ29udHJhY3QgQ3JlYXRlOiBVcGxvYWRpbmcgQ29udHJhY3QgRmlsZSBNZmd1aFdadks3chMKEQoHCgMYjxUQDwoGCgIYAxAQEkQKQhpA8uptpbIegIASR0CaIvkQWvA5ZgF5oV33U9XnPnE+ZP3jKmyZBbBt1XD+pjMiV0R8K/vwEVgVcsoblvGYU8O9Cg==" } }, "transactionID": { "transactionValidStart": { "seconds": "1625830546", "nanos": 400472500 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:48 AM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "fileID": { "fileNum": "11361" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "aTXYuPs2eJ65mgT4Q8widtU/VwdcY9l+2VHMydeQedFZdDENBbLN25VDYxXonPqV", "consensusTimestamp": { "seconds": "1625830547", "nanos": 435014000 }, "transactionID": { "transactionValidStart": { "seconds": "1625830546", "nanos": 400472500 }, "accountID": { "accountNum": "2703" } }, "memo": "Greeting Contract Create: Uploading Contract File MfguhWZvK7", "transactionFee": "42749663", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2172877" }, { "accountID": { "accountNum": "98" }, "amount": "40576786" }, { "accountID": { "accountNum": "2703" }, "amount": "-42749663" } ] } } } }
    7/9/2021 11:35:48 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830548", "nanos": 703372500 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Greeting Contract Create: Instantiating Contract Instance MfguhWZvK7", "contractCreateInstance": { "fileID": { "fileNum": "11361" }, "adminKey": { "ed25519": "xbm8FLgYEyyqROsHT+2Hze/nBYtzGA8O2ZGYsPKsQDU=" }, "gas": "2000", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "Greeting Contract iAOk%HD2Aq" } }
    7/9/2021 11:35:48 AM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "M4iU2B1KlVPIDlpAGlUDblz8VG7yPt3Wb9MYiFL93BbmXHTBKx/RbKfGd3HVzPC4tTWNzC0DGMV7MVuGpw9QAQ==" }, { "pubKeyPrefix": "xQ==", "ed25519": "8EAsWye4lK3U4ZLoT74xSC4SZxRM02AMq5K03D0wUW1iEkPVyZjpdcaCZIyaBPdMJRZ4XxCsjrVT4qTlv9vFDQ==" } ] }
    7/9/2021 11:35:48 AM  RX:(00)  { }
    7/9/2021 11:35:48 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830548", "nanos": 703372500 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:48 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:49 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:49 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:50 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "contractID": { "contractNum": "11362" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:35:50 AM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625830548", "nanos": 703372500 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:50 AM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/9/2021 11:35:50 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830550", "nanos": 129482000 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Greeting Contract Create: Instantiating Contract Instance MfguhWZvK7", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/9/2021 11:35:50 AM  ├─ SIG → { "sigPair": [ { "ed25519": "rvWV7SYNh/lvpG36d83KqCF4c+lSPicqGRVi3Pr6n4SDzbbuJ1oTlbVVcvaeDeW+ocP1aBrb19w8B0VNQR0VCg==" } ] }
    7/9/2021 11:35:50 AM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "Cn0KEgoLCJbpoIcGEJD63j0SAxiPFRICGAMYgPiCrRYiAgh4MkRHcmVldGluZyBDb250cmFjdCBDcmVhdGU6IEluc3RhbnRpYXRpbmcgQ29udHJhY3QgSW5zdGFuY2UgTWZndWhXWnZLN3ITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQK71le0mDYf5b6Rt+nfNyqgheHPpUj4nKhkVYtz6+p+Eg8227idaE5W1VXL2ng3lvqHD9Wga29fcPAdFTUEdFQo=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625830548", "nanos": 703372500 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:50 AM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "contractID": { "contractNum": "11362" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "DjnggFRklrvfKQSJFLqjJr0pSWt5Hbf2ebWRdsnP+6UO22ydlK7oFwLETHbyymtI", "consensusTimestamp": { "seconds": "1625830549", "nanos": 605434000 }, "transactionID": { "transactionValidStart": { "seconds": "1625830548", "nanos": 703372500 }, "accountID": { "accountNum": "2703" } }, "memo": "Greeting Contract Create: Instantiating Contract Instance MfguhWZvK7", "transactionFee": "664677319", "contractCreateResult": { "contractID": { "contractNum": "11362" }, "gasUsed": "279" }, "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "21370814" }, { "accountID": { "accountNum": "98" }, "amount": "643306505" }, { "accountID": { "accountNum": "2703" }, "amount": "-664677319" } ] } } } }
    SETUP COMPLETED: Greeting Contract Instance Created
    STARTING SETUP: Test Token Instance
    STARTING SETUP: Test Account Instance
    7/9/2021 11:35:50 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830550", "nanos": 168000800 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ed25519": "aMMKt+R/pWNdZwDdQAFPxPXwMWxRkv8wFNtSJk75mxU=" }, "initialBalance": "10", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "C69-VFL3&o62ALWILYQ" } }
    7/9/2021 11:35:50 AM  └─ SIG → { "sigPair": [ { "ed25519": "6nWfsdujlcSdFuLCdZu+MdMVfunnMXQcP6RIeDBlJIsbumECEAda57RpmRISIDDaqEm59A9sQEb2pxcbXrZ8CQ==" } ] }
    7/9/2021 11:35:50 AM  RX:(00)  { }
    7/9/2021 11:35:50 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830550", "nanos": 168000800 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:50 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:50 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:50 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:51 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "11363" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:35:51 AM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625830550", "nanos": 168000800 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:51 AM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/9/2021 11:35:51 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830551", "nanos": 632264900 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/9/2021 11:35:51 AM  ├─ SIG → { "sigPair": [ { "ed25519": "vopp/EE30sqpmk8IsVE9rjVeEUokKj11nio0us1v+lJHXNPnrTej3CrvYU9B8q96KiAr6ducHvpVL2oOA/DhDA==" } ] }
    7/9/2021 11:35:51 AM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnEKEwoMCJfpoIcGEMSxvq0CEgMYjxUSAhgDGID4gq0WIgIIeDI3VGVzdCBBY2NvdW50IEluc3RhbmNlOiBDcmVhdGluZyBUZXN0IEFjY291bnQgb24gTmV0d29ya3ITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQL6KafxBN9LKqZpPCLFRPa41XhFKJCo9dZ4qNLrNb/pSR1zT5603o9wq72FPQfKveiogK+nbnB76VS9qDgPw4Qw=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625830550", "nanos": 168000800 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:51 AM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "11363" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "Yi1TDW9ATEEDgM2dGkEHqiQexe7MzSEV9i2ypqJ4H6TuFoIVJfYpBoZGsWD867Nq", "consensusTimestamp": { "seconds": "1625830551", "nanos": 72087000 }, "transactionID": { "transactionValidStart": { "seconds": "1625830550", "nanos": 168000800 }, "accountID": { "accountNum": "2703" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "42034625", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2037200" }, { "accountID": { "accountNum": "98" }, "amount": "39997425" }, { "accountID": { "accountNum": "2703" }, "amount": "-42034635" }, { "accountID": { "accountNum": "11363" }, "amount": "10" } ] } } } }
    SETUP COMPLETED: Test Account Instance
    STARTING SETUP: Test Account Instance
    7/9/2021 11:35:51 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830551", "nanos": 659881300 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ed25519": "MCXe6EkT2WET3MMff49YV3h3oIyDqrDQ2gEAwBPSLrA=" }, "initialBalance": "11", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "v#BdH0FGpC1a5ehh272X" } }
    7/9/2021 11:35:51 AM  └─ SIG → { "sigPair": [ { "ed25519": "XNtFxoqRezfAZSvBri7m6a/fTZFVkBVY8kG/eFsrKDboBkaYkFAVMu+PNJzRf79mT3b0Xi6i5g/Y7UQW5w+kAA==" } ] }
    7/9/2021 11:35:51 AM  RX:(00)  { }
    7/9/2021 11:35:51 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830551", "nanos": 659881300 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:51 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:51 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:52 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:53 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "11364" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:35:53 AM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625830551", "nanos": 659881300 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:53 AM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/9/2021 11:35:53 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830553", "nanos": 71898800 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/9/2021 11:35:53 AM  ├─ SIG → { "sigPair": [ { "ed25519": "ysKrV/4g+/U4y9psiiYudqvRsvWqZvfWklFyUCM0alvz3mkRiLWxzpPQAlwEeeuCruB9D5tfMGfpapWnVNnODw==" } ] }
    7/9/2021 11:35:53 AM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnAKEgoLCJnpoIcGELCtpCISAxiPFRICGAMYgPiCrRYiAgh4MjdUZXN0IEFjY291bnQgSW5zdGFuY2U6IENyZWF0aW5nIFRlc3QgQWNjb3VudCBvbiBOZXR3b3JrchMKEQoHCgMYjxUQDwoGCgIYAxAQEkQKQhpAysKrV/4g+/U4y9psiiYudqvRsvWqZvfWklFyUCM0alvz3mkRiLWxzpPQAlwEeeuCruB9D5tfMGfpapWnVNnODw==" } }, "transactionID": { "transactionValidStart": { "seconds": "1625830551", "nanos": 659881300 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:53 AM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "11364" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "M3tqdxMrT7CTztKvCUDLp4fo2jDm8FnIRQp3wgkVBj3lWdlzXl6uwhdp5ye1JB2x", "consensusTimestamp": { "seconds": "1625830552", "nanos": 527878000 }, "transactionID": { "transactionValidStart": { "seconds": "1625830551", "nanos": 659881300 }, "accountID": { "accountNum": "2703" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "42058818", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2037800" }, { "accountID": { "accountNum": "98" }, "amount": "40021018" }, { "accountID": { "accountNum": "2703" }, "amount": "-42058829" }, { "accountID": { "accountNum": "11364" }, "amount": "11" } ] } } } }
    SETUP COMPLETED: Test Account Instance
    7/9/2021 11:35:53 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830553", "nanos": 106092200 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestToken Setup: QHQLGNYKAXWXVWHHZCFY", "tokenCreation": { "name": "PT%GWDrviu3f%&Y88hOXFwWlEcNy6sbjg5wcB&GDIcq%RWe-Gr", "symbol": "QHQLGNYKAXWXVWHHZCFY", "decimals": 2, "initialSupply": "190000000", "treasury": { "accountNum": "11363" }, "adminKey": { "ed25519": "qEtlyihM09OeSjf8FuFCdrPRHJBnS7UTOC/uJM6pAVg=" }, "freezeKey": { "ed25519": "Eq2aiuFyqHAT6FbkvYhs7NRdUn9wZMnI8O9TE95okQ0=" }, "wipeKey": { "ed25519": "2bMN0MG+r9OuVZMAAnMWkQXuW30B7odMfHm3KsbDRDc=" }, "supplyKey": { "ed25519": "WgqQj+AevFE8+UCj9m9CZSeS9QpJUVo61W1/27isjSc=" }, "expiry": { "seconds": "1636056352" }, "autoRenewAccount": { "accountNum": "11364" }, "autoRenewPeriod": { "seconds": "7776000" }, "memo": "Test Token: %aKOvFbU0#UsPAF8BoLf", "supplyType": "FINITE", "maxSupply": "489875687", "feeScheduleKey": { "ed25519": "AibSid60WGRDUUrTnMMTXkNJSJTd5Ggi8bjX1L5Zw/Q=" } } }
    7/9/2021 11:35:53 AM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "VvOgkTS+2tTAx0qvFvKsKun1jLLTdpKJgjOOYbPI8kPFi4JkAUQq+Tfw+y/UvgzqpfUBCKXTxf3t8nUtu/kqBA==" }, { "pubKeyPrefix": "qA==", "ed25519": "exuR2jEdQcZc5EWrTuM4R9jJpR+3TQAkw88Mv61AXPD19GzZY2b15NAwM3yll/t33+IyLJ40vFwtWOEXJLBhDQ==" }, { "pubKeyPrefix": "MA==", "ed25519": "MRls71VQEyZwfuKFWpUft5u3Bjql4mjVoAQ7rwijunArL9Cfbvnzil3HoumZY8Ycgu4H03ZoeCazpRhtJnKhBw==" }, { "pubKeyPrefix": "aA==", "ed25519": "SJjpdfoj5B6inSrIlhWHqPqrgJ7yXx11IpLjSUVDbdV4jir6S5Fg07pa7tl0fzqHksY7dsnRUzZcbT3VXD4gBA==" } ] }
    7/9/2021 11:35:53 AM  RX:(00)  { }
    7/9/2021 11:35:53 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830553", "nanos": 106092200 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:53 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:53 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:53 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:54 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "tokenID": { "tokenNum": "11365" } } } }
    7/9/2021 11:35:54 AM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625830553", "nanos": 106092200 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:54 AM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/9/2021 11:35:54 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830554", "nanos": 487169500 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestToken Setup: QHQLGNYKAXWXVWHHZCFY", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/9/2021 11:35:54 AM  ├─ SIG → { "sigPair": [ { "ed25519": "i9kDMergAjaxUme1wZyJTvJEi8yN9EN8n2gCTMgHSNHZh5WKh8IWeQ5R/E720v2V8V16h2zWQY3VcTAXMSVwDg==" } ] }
    7/9/2021 11:35:54 AM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "Cl8KEwoMCJrpoIcGENy7pugBEgMYjxUSAhgDGID4gq0WIgIIeDIlVGVzdFRva2VuIFNldHVwOiBRSFFMR05ZS0FYV1hWV0hIWkNGWXITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQIvZAzHq4AI2sVJntcGciU7yRIvMjfRDfJ9oAkzIB0jR2YeViofCFnkOUfxO9tL9lfFdeods1kGN1XEwFzElcA4=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625830553", "nanos": 106092200 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:54 AM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "tokenID": { "tokenNum": "11365" } }, "transactionHash": "pJdD/BLCqhFxjng9ZKWinqhrEmp3fkQRnrAflxe5ixvqVQRZ0POuzbho1ko/YpiH", "consensusTimestamp": { "seconds": "1625830554", "nanos": 54247000 }, "transactionID": { "transactionValidStart": { "seconds": "1625830553", "nanos": 106092200 }, "accountID": { "accountNum": "2703" } }, "memo": "TestToken Setup: QHQLGNYKAXWXVWHHZCFY", "transactionFee": "873462307", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "16597177" }, { "accountID": { "accountNum": "98" }, "amount": "856865130" }, { "accountID": { "accountNum": "2703" }, "amount": "-873462307" } ] }, "tokenTransferLists": [ { "token": { "tokenNum": "11365" }, "transfers": [ { "accountID": { "accountNum": "11363" }, "amount": "190000000" } ] } ] } } }
    SETUP COMPLETED: Test Token Instance
    7/9/2021 11:35:54 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830554", "nanos": 521204800 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "tokenAssociate": { "account": { "accountNum": "11362" }, "tokens": [ { "tokenNum": "11365" } ] } }
    7/9/2021 11:35:54 AM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "Fdl17ldkJ+Nd8BzXizJKbAyknUfJMV5xFUvZ3gdGj+tHCSubBTzQaggSsvHFepzkT1XcTFCYA5jehmsCOG1bAg==" }, { "pubKeyPrefix": "xQ==", "ed25519": "kiSggMs8WxtYv3W68AYpDp6nu5f3yyXpP0yQ63Bh+1HN6BbPHEZ8LUXnQc1QaRbZQ2/pq7sewYZ14JJOaBxCBg==" } ] }
    7/9/2021 11:35:54 AM  RX:(00)  { }
    7/9/2021 11:35:54 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830554", "nanos": 521204800 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:54 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:54 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:55 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:55 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:56 AM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    
    CALLING: GetContractInfoAsync(0.0.11362)
    
    7/9/2021 11:35:56 AM  QX ASK → { "contractGetInfo": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "contractID": { "contractNum": "11362" } } }
    7/9/2021 11:35:56 AM  RX:(00)  { "contractGetInfo": { "header": { "responseType": "COST_ANSWER", "cost": "10" } } }
    7/9/2021 11:35:56 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830556", "nanos": 745231200 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-10" }, { "accountID": { "accountNum": "3" }, "amount": "10" } ] } } }
    7/9/2021 11:35:56 AM  ├─ SIG → { "sigPair": [ { "ed25519": "9We6T76/ynaivxXcmc5RZKLOwjm1C1SoLaiENOiLVykXH0XrS+SyFPiVQJyZyiRlGKLadwFlOULQrvF123/JDg==" } ] }
    7/9/2021 11:35:56 AM  └─ QRY → { "contractGetInfo": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCJzpoIcGEOCmreMCEgMYjxUSAhgDGID4gq0WIgIIeHITChEKBwoDGI8VEBMKBgoCGAMQFBJECkIaQPVnuk++v8p2or8V3JnOUWSizsI5tQtUqC2ohDToi1cpFx9F60vkshT4lUCcmcokZRii2ncBZTlC0K7xddt/yQ4=" } }, "contractID": { "contractNum": "11362" } } }
    7/9/2021 11:35:56 AM  RX:(00)  { "contractGetInfo": { "header": { "cost": "10" }, "contractInfo": { "contractID": { "contractNum": "11362" }, "accountID": { "accountNum": "11362" }, "contractAccountID": "0000000000000000000000000000000000002c62", "adminKey": { "ed25519": "xbm8FLgYEyyqROsHT+2Hze/nBYtzGA8O2ZGYsPKsQDU=" }, "expirationTime": { "seconds": "1633720548" }, "autoRenewPeriod": { "seconds": "7890000" }, "storage": "510", "memo": "Greeting Contract iAOk%HD2Aq", "tokenRelationships": [ { "tokenId": { "tokenNum": "11365" }, "symbol": "QHQLGNYKAXWXVWHHZCFY", "freezeStatus": "Unfrozen", "decimals": 2 } ] } } }
    
    VERIFIED: Token 0.0.11365 is associated with Contract 0.0.11362
    
    CALLING: DissociateTokenAsync(0.0.11365, 0.0.11362, privateKey)
    
    7/9/2021 11:35:56 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830556", "nanos": 810926600 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "tokenDissociate": { "account": { "accountNum": "11362" }, "tokens": [ { "tokenNum": "11365" } ] } }
    7/9/2021 11:35:56 AM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "zFQSxrYt4i1hDH/qST1GMRh+rMmTB1HWJhSKhZUlxM21dBLsXa+ST7m+k3qFQcbIuBnaBDtK2CBGY0uLVNPPAw==" }, { "pubKeyPrefix": "xQ==", "ed25519": "+dBIUCCOezcenJ/QWKP9tbOBHJX2ZsQcZ3eDxGpKqNOWiMg1vyOdkb1JGvlPFnUueZy36MN1XGqsKnX8LaddDw==" } ] }
    7/9/2021 11:35:56 AM  RX:(00)  { }
    7/9/2021 11:35:56 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830556", "nanos": 810926600 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:56 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:57 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:57 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:58 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:35:58 AM  QX ASK → { "contractGetInfo": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "contractID": { "contractNum": "11362" } } }
    7/9/2021 11:35:58 AM  RX:(00)  { "contractGetInfo": { "header": { "responseType": "COST_ANSWER", "cost": "10" } } }
    7/9/2021 11:35:58 AM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625830558", "nanos": 194456300 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-10" }, { "accountID": { "accountNum": "3" }, "amount": "10" } ] } } }
    7/9/2021 11:35:58 AM  ├─ SIG → { "sigPair": [ { "ed25519": "qZfglTaIx5yMpOiMdiGKfdU6iNzFuAlrt86+QlqGNtpcyx+bEnFstyeTD30S0wFX++6n1EHS7mFz409H4aqTBw==" } ] }
    7/9/2021 11:35:58 AM  └─ QRY → { "contractGetInfo": { "header": { "payment": { "signedTransactionBytes": "CjcKEgoLCJ7poIcGEOzV3FwSAxiPFRICGAMYgPiCrRYiAgh4chMKEQoHCgMYjxUQEwoGCgIYAxAUEkQKQhpAqZfglTaIx5yMpOiMdiGKfdU6iNzFuAlrt86+QlqGNtpcyx+bEnFstyeTD30S0wFX++6n1EHS7mFz409H4aqTBw==" } }, "contractID": { "contractNum": "11362" } } }
    7/9/2021 11:35:58 AM  RX:(00)  { "contractGetInfo": { "header": { "cost": "10" }, "contractInfo": { "contractID": { "contractNum": "11362" }, "accountID": { "accountNum": "11362" }, "contractAccountID": "0000000000000000000000000000000000002c62", "adminKey": { "ed25519": "xbm8FLgYEyyqROsHT+2Hze/nBYtzGA8O2ZGYsPKsQDU=" }, "expirationTime": { "seconds": "1633720548" }, "autoRenewPeriod": { "seconds": "7890000" }, "storage": "510", "memo": "Greeting Contract iAOk%HD2Aq" } } }
    
    VERIFIED: Token 0.0.11365 is NOT associated with Contract 0.0.11362
    
    
    CALLING: TransferTokensAsync(0.0.11365, 0.0.11363, 0.0.11362, 126666666, privateKey)
    
    7/9/2021 11:35:58 AM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625830558", "nanos": 223963300 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "tokenTransfers": [ { "token": { "tokenNum": "11365" }, "transfers": [ { "accountID": { "accountNum": "11363" }, "amount": "-126666666" }, { "accountID": { "accountNum": "11362" }, "amount": "126666666" } ] } ] } }
    7/9/2021 11:35:58 AM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "HvGhpGmc/+rVrnnUvJr93reShDtpfDQC4Kmdj1sAKnsDtCuYhulh1AfKYgKMUqTLxv5VMRqxudusihF9SsQaCg==" }, { "pubKeyPrefix": "aA==", "ed25519": "TK+A1ysEeW+8rd8yQWSDURh1N7XRrOpioKMVzt13S4QHN3eHNSCHUTujQt9mYqpDdYaGWUC8TyRHXAwJhPwMBA==" } ] }
    7/9/2021 11:35:58 AM  RX:(00)  { }
    7/9/2021 11:35:58 AM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625830558", "nanos": 223963300 }, "accountID": { "accountNum": "2703" } } } }
    7/9/2021 11:35:58 AM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:58 AM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:58 AM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:35:59 AM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/9/2021 11:36:00 AM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/9/2021 11:36:00 AM  QX ASK → { "cryptogetAccountBalance": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "contractID": { "contractNum": "11362" } } }
    7/9/2021 11:36:00 AM  RX:(00)  { "cryptogetAccountBalance": { "header": { }, "accountID": { "accountNum": "11362" } } }
    
    VERIFIED: Contract 0.0.11362 has Token 0.0.11365 balance of 0
    
    7/9/2021 11:36:00 AM  QX ASK → { "cryptogetAccountBalance": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "accountID": { "accountNum": "11363" } } }
    7/9/2021 11:36:00 AM  RX:(00)  { "cryptogetAccountBalance": { "header": { }, "accountID": { "accountNum": "11363" }, "balance": "10", "tokenBalances": [ { "tokenId": { "tokenNum": "11365" }, "balance": "63333334", "decimals": 2 } ] } }
    
    VERIFIED: Treasury 0.0.11363 has Token 0.0.11365 balance of 63333334 which is less than the original of 190000000 by the amount of the transfer value.
    
[teardown omitted]
```

.NET SDK integration test:

```c#
        [Fact(DisplayName = "Dissociate Tokens: Can Dissociate token from Contract Consent")]
        public async Task CanDissociateTokenFromContract()
        {
            await using var fxAccount = await TestAccount.CreateAsync(_network);
            await using var fxContract = await GreetingContract.CreateAsync(_network);
            await using var fxToken = await TestToken.CreateAsync(_network, fx => fx.Params.GrantKycEndorsement = null);
            var xferAmount = 2 * fxToken.Params.Circulation / 3;

            var _contractId = $"0.0.{fxContract.ContractRecord.Contract.AccountNum}";
            var _tokenId = $"0.0.{fxToken.Record.Token.AccountNum}";
            var _treasuryId = $"0.0.{fxToken.TreasuryAccount.Record.Address.AccountNum}";

            var receipt = await fxContract.Client.AssociateTokenAsync(fxToken.Record.Token, fxContract.ContractRecord.Contract, fxContract.PrivateKey);
            Assert.Equal(ResponseCode.Success, receipt.Status);

            _network.Output.WriteLine($"\nCALLING: GetContractInfoAsync({_contractId})\n");
            var info = await fxAccount.Client.GetContractInfoAsync(fxContract.ContractRecord.Contract);
            Assert.NotNull(info);

            var association = info.Tokens.FirstOrDefault(t => t.Token == fxToken.Record.Token);
            Assert.NotNull(association);
            Assert.Equal(fxToken.Record.Token, association.Token);
            Assert.Equal(fxToken.Params.Symbol, association.Symbol);
            Assert.Equal(0UL, association.Balance);
            Assert.Equal(fxToken.Params.Decimals, association.Decimals);
            Assert.Equal(TokenKycStatus.NotApplicable, association.KycStatus);
            Assert.Equal(TokenTradableStatus.Tradable, association.TradableStatus);
            _network.Output.WriteLine($"\nVERIFIED: Token {_tokenId} is associated with Contract {_contractId}\n");

            _network.Output.WriteLine($"CALLING: DissociateTokenAsync({_tokenId}, {_contractId}, privateKey)\n");
            receipt = await fxContract.Client.DissociateTokenAsync(fxToken.Record.Token, fxContract.ContractRecord.Contract, fxContract.PrivateKey);
            Assert.Equal(ResponseCode.Success, receipt.Status);

            info = await fxAccount.Client.GetContractInfoAsync(fxContract.ContractRecord.Contract);
            Assert.NotNull(info);
            Assert.Null(info.Tokens.FirstOrDefault(t => t.Token == fxToken.Record.Token));
            _network.Output.WriteLine($"\nVERIFIED: Token {_tokenId} is NOT associated with Contract {_contractId}\n");

            // NETWORK BUG: This is what should happen
            //var tex = await Assert.ThrowsAsync<TransactionException>(async () =>
            //{
            //    await fxToken.Client.TransferTokensAsync(fxToken.Record.Token, fxToken.TreasuryAccount.Record.Address, fxContract.ContractRecord.Contract, (long)xferAmount, fxToken.TreasuryAccount.PrivateKey);
            //});
            //Assert.Equal(ResponseCode.TokenNotAssociatedToAccount, tex.Status);
            //Assert.StartsWith("Unable to execute transfers, status: TokenNotAssociatedToAccount", tex.Message);

            //Assert.Equal(0UL, await fxToken.Client.GetContractTokenBalanceAsync(fxContract, fxToken));

            // NETWORK BUG: Should not be able to do this, it should fail
            _network.Output.WriteLine($"\nCALLING: TransferTokensAsync({_tokenId}, {_treasuryId}, {_contractId}, {xferAmount}, privateKey)\n");
            await fxToken.Client.TransferTokensAsync(fxToken.Record.Token, fxToken.TreasuryAccount.Record.Address, fxContract.ContractRecord.Contract, (long)xferAmount, fxToken.TreasuryAccount.PrivateKey);
            Assert.Equal(ResponseCode.Success, receipt.Status);
            // But appears to have failed behind the scenes anyway
            Assert.Equal(0UL, await fxToken.Client.GetContractTokenBalanceAsync(fxContract, fxToken));
            _network.Output.WriteLine($"\nVERIFIED: Contract {_contractId} has Token {_tokenId} balance of 0\n");
            Assert.Equal(fxToken.Params.Circulation - xferAmount, await fxToken.Client.GetAccountTokenBalanceAsync(fxToken.TreasuryAccount, fxToken));
            _network.Output.WriteLine($"\nVERIFIED: Treasury {_treasuryId} has Token {_tokenId} balance of {fxToken.Params.Circulation - xferAmount} which is less than the original of {fxToken.Params.Circulation} by the amount of the transfer value.\n");
        }
```

### Hedera network

previewnet

### Version

v0.16.0-alpha1 (presumably deployed on previewnet)

### Operating system

Windows

### LINKED ISSUE #1785: PREVIEW Network: Burning NFT not owned by Treasury corrupts cryptogetAccountBalance returned actual account owning NFT
### Description

When burning an NFT that is not owned by the treasury, the NFT is indeed removed from the network, however the balance adjustment for the burned NFT is applied to the treasury account and not the account that presently owned the NFT with the specified serial number.

As a secondary symptom: `tokenGetAccountNftInfos` is corrupted when the network enters this state.

### Steps to reproduce

- Create a Regular Account
- Create a Treasury Account
- Create an NFT 
- Associate Regular Account
- Transfer NFT SN no. 1 from Treasury to Regular Account
- Burn NFT with SN 1
- Check Balances of Both Accounts: They are off.
- Retrieve the list of all NFTs of the type, the owning accounts are correct as expected (the Regular Account is missing SN 1)

Also `tokenGetAccountNftInfos` is corrupted when system enters this invalid state.

### Additional context

Integration Test Log:

```
 Burn Assets: Can Burn Single Asset The Treasury Does Not Own
  No source available
   Duration: 19.5 sec

  Standard Output: 
    STARTING SETUP: Test Account Instance
    7/10/2021 10:56:03 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957763", "nanos": 93864400 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ed25519": "h8xW7OAHm9WJNmXR9PmBbTtelUrqVtXhfkRC/Efkdl0=" }, "initialBalance": "14", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "eYr5Q-f%JUtssD3" } }
    7/10/2021 10:56:03 PM  └─ SIG → { "sigPair": [ { "ed25519": "EuPvWU0Zl0bfY3vQOk1yRi2OeXBgaaXQ0fwjtU+19BMDVELCBmwlMMKB4U65e9D9tAUgncIGFomS17JCdcxDCg==" } ] }
    7/10/2021 10:56:03 PM  RX:(00)  { }
    7/10/2021 10:56:03 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957763", "nanos": 93864400 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:03 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:04 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:04 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "12733" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/10/2021 10:56:04 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625957763", "nanos": 93864400 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:04 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/10/2021 10:56:04 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625957764", "nanos": 685234100 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/10/2021 10:56:04 PM  ├─ SIG → { "sigPair": [ { "ed25519": "rXOXk5sdwj8X7gAh1j33XL7ejz3rtyF0xrySU7FaycIOhkndrGI6Ijg5tg6o7jgtTDQLE+1Oznkms/TLsQUlBQ==" } ] }
    7/10/2021 10:56:04 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnEKEwoMCITLqIcGELSv38YCEgMYjxUSAhgDGID4gq0WIgIIeDI3VGVzdCBBY2NvdW50IEluc3RhbmNlOiBDcmVhdGluZyBUZXN0IEFjY291bnQgb24gTmV0d29ya3ITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQK1zl5ObHcI/F+4AIdY991y+3o8967chdMa8klOxWsnCDoZJ3axiOiI4ObYOqO44LUw0CxPtTs55JrP0y7EFJQU=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625957763", "nanos": 93864400 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:04 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "12733" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "ykkQKlsS3RmgsbRwRpYjR7cypGNIFfKIliflQ5mbZMtu0Pm7oghVy4fuFkFgM24F", "consensusTimestamp": { "seconds": "1625957763", "nanos": 901753000 }, "transactionID": { "transactionValidStart": { "seconds": "1625957763", "nanos": 93864400 }, "accountID": { "accountNum": "2703" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "41937835", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2034803" }, { "accountID": { "accountNum": "98" }, "amount": "39903032" }, { "accountID": { "accountNum": "2703" }, "amount": "-41937849" }, { "accountID": { "accountNum": "12733" }, "amount": "14" } ] } } } }
    SETUP COMPLETED: Test Account Instance
    STARTING SETUP: Test Asset Instance
    STARTING SETUP: Test Account Instance
    7/10/2021 10:56:04 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957764", "nanos": 732497200 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ed25519": "zSHQXKCWsARV/s1X2HNrSMuc4gUlI2zId2UiHKl53Ak=" }, "initialBalance": "17", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "Jn@$l9iGVI" } }
    7/10/2021 10:56:04 PM  └─ SIG → { "sigPair": [ { "ed25519": "bmqdnlP1Kyl58hWEeU5iz7mDMpDQHUy/wk4fHHieqgfsq3GyEIoYCdXmnhK0ySF9HrjjY/7BdR9eLr62IzEyAA==" } ] }
    7/10/2021 10:56:04 PM  RX:(00)  { }
    7/10/2021 10:56:04 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957764", "nanos": 732497200 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:04 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:05 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:05 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:06 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "12734" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/10/2021 10:56:06 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625957764", "nanos": 732497200 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:06 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/10/2021 10:56:06 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625957766", "nanos": 103753500 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/10/2021 10:56:06 PM  ├─ SIG → { "sigPair": [ { "ed25519": "YBZL2v7iI80lsaUjIQrVEmAuusRlmaiDst1M+nFRtQBTmJdMqYSO6wfqviJDHYQxVpBahja5NkaHivrEOVRMDA==" } ] }
    7/10/2021 10:56:06 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnAKEgoLCIbLqIcGEJzOvDESAxiPFRICGAMYgPiCrRYiAgh4MjdUZXN0IEFjY291bnQgSW5zdGFuY2U6IENyZWF0aW5nIFRlc3QgQWNjb3VudCBvbiBOZXR3b3JrchMKEQoHCgMYjxUQDwoGCgIYAxAQEkQKQhpAYBZL2v7iI80lsaUjIQrVEmAuusRlmaiDst1M+nFRtQBTmJdMqYSO6wfqviJDHYQxVpBahja5NkaHivrEOVRMDA==" } }, "transactionID": { "transactionValidStart": { "seconds": "1625957764", "nanos": 732497200 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:06 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "12734" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "wh9sRj+tb8bh+kjpV9MeYtNP4JVG/+rENxwXJ1Wl7VicexKev3q5ABjqV6NpbvbH", "consensusTimestamp": { "seconds": "1625957765", "nanos": 114050000 }, "transactionID": { "transactionValidStart": { "seconds": "1625957764", "nanos": 732497200 }, "accountID": { "accountNum": "2703" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "41816852", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2031807" }, { "accountID": { "accountNum": "98" }, "amount": "39785045" }, { "accountID": { "accountNum": "2703" }, "amount": "-41816869" }, { "accountID": { "accountNum": "12734" }, "amount": "17" } ] } } } }
    SETUP COMPLETED: Test Account Instance
    STARTING SETUP: Test Account Instance
    7/10/2021 10:56:06 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957766", "nanos": 129526800 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoCreateAccount": { "key": { "ed25519": "8AvcaeH7Ih5nEAikmMNTL9WdfEtRG+nKoex0eQk/CQo=" }, "initialBalance": "10", "autoRenewPeriod": { "seconds": "7890000" }, "memo": "!y26PEnEEd6mj0DGbaf" } }
    7/10/2021 10:56:06 PM  └─ SIG → { "sigPair": [ { "ed25519": "5MO9DC8HL3eWAu1217CBhD9HyzfbZbVQ5P8i09Xb5HkvjOm/OJWvoA2e3vAl8usrgBIVDCunmV5IM957N1vgAw==" } ] }
    7/10/2021 10:56:06 PM  RX:(00)  { }
    7/10/2021 10:56:06 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957766", "nanos": 129526800 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:06 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:06 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:06 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:07 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:08 PM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "12735" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/10/2021 10:56:08 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625957766", "nanos": 129526800 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:08 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/10/2021 10:56:08 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625957768", "nanos": 361053100 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance: Creating Test Account on Network", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/10/2021 10:56:08 PM  ├─ SIG → { "sigPair": [ { "ed25519": "fjBGuXlj0K6gl708ZRs5RhaupeSi3pwLeXQSyCY2GfxM5Qbq9IocNvP2zROKzTo+5gLKGBYbFWQp+bF0+ercDQ==" } ] }
    7/10/2021 10:56:08 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CnEKEwoMCIjLqIcGEKz3lKwBEgMYjxUSAhgDGID4gq0WIgIIeDI3VGVzdCBBY2NvdW50IEluc3RhbmNlOiBDcmVhdGluZyBUZXN0IEFjY291bnQgb24gTmV0d29ya3ITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQH4wRrl5Y9CuoJe9PGUbOUYWrqXkot6cC3l0EsgmNhn8TOUG6vSKHDbz9s0Tis06PuYCyhgWGxVkKfmxdPnq3A0=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625957766", "nanos": 129526800 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:08 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "accountID": { "accountNum": "12735" }, "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } }, "transactionHash": "XnVg5zGtLbp9rO5B+kei0jKWQZG6Xs2e2n+/Vgkq1qxcjjhpBCKZk8JI9gYcuV5c", "consensusTimestamp": { "seconds": "1625957766", "nanos": 760465000 }, "transactionID": { "transactionValidStart": { "seconds": "1625957766", "nanos": 129526800 }, "accountID": { "accountNum": "2703" } }, "memo": "Test Account Instance: Creating Test Account on Network", "transactionFee": "42034625", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "2037200" }, { "accountID": { "accountNum": "98" }, "amount": "39997425" }, { "accountID": { "accountNum": "2703" }, "amount": "-42034635" }, { "accountID": { "accountNum": "12735" }, "amount": "10" } ] } } } }
    SETUP COMPLETED: Test Account Instance
    7/10/2021 10:56:08 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957768", "nanos": 395470800 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestAsset Setup: FPOSXPIRDBAAYXLRRSPP", "tokenCreation": { "name": "QUa8ih50WKpW7QV&835yBr@yzdf25cw&vJtxY*YzR50&6jxSeI", "symbol": "FPOSXPIRDBAAYXLRRSPP", "treasury": { "accountNum": "12734" }, "adminKey": { "ed25519": "bN6dQhlX7ngeqD/uPLuqjNeRnBStQvgIVLUuG3h6phk=" }, "freezeKey": { "ed25519": "DrLoF6D5MbolbF2lusdPMRRbxs4xvMogTA2wfQmeLCU=" }, "wipeKey": { "ed25519": "OR5y/GnVaGq5gapUDJZEsBkS6InlDOaGzy8BfrbxLZ4=" }, "supplyKey": { "ed25519": "EjUAMfNE5ZfbaT/pPuxclgT4mtPE2rp4zCcJZuVnGsU=" }, "expiry": { "seconds": "1635257954" }, "autoRenewAccount": { "accountNum": "12735" }, "autoRenewPeriod": { "seconds": "7776000" }, "memo": "Test Asset: $fGhO9D9QyNYwMGa$OCb", "tokenType": "NON_FUNGIBLE_UNIQUE", "supplyType": "FINITE", "maxSupply": "16000", "feeScheduleKey": { "ed25519": "iMvynR+MaEyC/AHx4NfycOg2SLD1C76+g7F/Q7JcTDw=" } } }
    7/10/2021 10:56:08 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "B6rsesyi9A1pHuUaarkvK6daqdLZHP2l6PgFr2ZjdUFOMNxs4NSqZMlsZlZ2ybW1wWGnUwd5Xh0BbwA9cKvoDg==" }, { "pubKeyPrefix": "bA==", "ed25519": "WsHRAp6W1YeFTOJLEEbGeG6zSAiqLVFkwXSIE+3z+Md7mEBeHmwp/fQHQuH6TWkK+NQvDoRRFrLMRJ4IEb28Dw==" }, { "pubKeyPrefix": "8A==", "ed25519": "J+1hDVFbb99bOMiGezfTk8aorxikbAB/t9cbd18wjbmyj23GRC0xTIvCDNGWQyDBrE/oY+uThk3ucfKvvgBOBQ==" }, { "pubKeyPrefix": "zQ==", "ed25519": "HrEbTH4w1cbG7AQLyD61tweNDKMG7p4U+MOXRLlxv1mYp15wXR3VW9w9MjVYRVSJRxxcrv4szSwTMlf+bXStDg==" } ] }
    7/10/2021 10:56:08 PM  RX:(00)  { }
    7/10/2021 10:56:08 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957768", "nanos": 395470800 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:08 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:08 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:09 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:09 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:10 PM  RX:(04)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "tokenID": { "tokenNum": "12736" } } } }
    7/10/2021 10:56:10 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625957768", "nanos": 395470800 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:10 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/10/2021 10:56:10 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625957770", "nanos": 638509500 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestAsset Setup: FPOSXPIRDBAAYXLRRSPP", "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/10/2021 10:56:10 PM  ├─ SIG → { "sigPair": [ { "ed25519": "Xog6RXxOn1JmXHUfNjAIptwE7nhideCt8RkmY84i0pKEdvUbucqllrYqw22e5SAe9tvLgnLH6Q04b+HsfBXfDQ==" } ] }
    7/10/2021 10:56:10 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "Cl8KEwoMCIrLqIcGELzDu7ACEgMYjxUSAhgDGID4gq0WIgIIeDIlVGVzdEFzc2V0IFNldHVwOiBGUE9TWFBJUkRCQUFZWExSUlNQUHITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQF6IOkV8Tp9SZlx1HzYwCKbcBO54YnXgrfEZJmPOItKShHb1G7nKpZa2KsNtnuUgHvbby4Jyx+kNOG/h7HwV3w0=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625957768", "nanos": 395470800 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:10 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "tokenID": { "tokenNum": "12736" } }, "transactionHash": "Ex06cTsb/HTCL28YUMaRHuusqtySqoZFIC2rdVAggLs+Z4NqBVpU0/soDOdyjz9/", "consensusTimestamp": { "seconds": "1625957768", "nanos": 906930000 }, "transactionID": { "transactionValidStart": { "seconds": "1625957768", "nanos": 395470800 }, "accountID": { "accountNum": "2703" } }, "memo": "TestAsset Setup: FPOSXPIRDBAAYXLRRSPP", "transactionFee": "873462216", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "16597177" }, { "accountID": { "accountNum": "98" }, "amount": "856865039" }, { "accountID": { "accountNum": "2703" }, "amount": "-873462216" } ] } } } }
    7/10/2021 10:56:10 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957770", "nanos": 667363300 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "tokenAssociate": { "account": { "accountNum": "12733" }, "tokens": [ { "tokenNum": "12736" } ] } }
    7/10/2021 10:56:10 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "TfnDngPzMWtfUJRcauwtobYWDTJh0NUJlvdDa0eTfCTSM8pnSTtOlkaBVNU30FyuZO40bPm3vyKYp2JTQyrmBg==" }, { "pubKeyPrefix": "hw==", "ed25519": "z7mdlvcy7ze0YidoyWyyVP0LwGJTVrqkRbnxvExPhVwB0lbztnpIsNjggYKYLXpVR92/BIEwj9VwUK8jsU7sAw==" } ] }
    7/10/2021 10:56:10 PM  RX:(00)  { }
    7/10/2021 10:56:10 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957770", "nanos": 667363300 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:10 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:10 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:11 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:12 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/10/2021 10:56:12 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957772", "nanos": 37851100 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "tokenMint": { "token": { "tokenNum": "12736" }, "metadata": [ "VflvUY/qlu7o+5VoYcoLRQXRMYALKBl8tMvQC+ZZFCP2JlUV9iunI3jF+q1GkuKy", "qYkA4ejhxKKfyqyCdbe5IKtgRrIEWOH/HGZg/ZOwd3HZEYbG06Pkm4urQPeYH4Zk", "39OS4UQNVOjw6qgTiiWDdS+vQ5GEiLhOl5TsDPkjYg+kcR6+eRWMIqgd+DvG/26C", "yvv0HtHzS75wKmDknB/Vn2f89SnhIGFTUaqmn2kJdkxdMwLajL75s+hS9swUIBTI", "tYuS+jrq3uiZ75LvsfRs07buxHsMI7Lrb/pWPPIVkfkBMf+FmDcxFZWG6fZN9emc", "Gjb92G7i2xh0yVY25F8eyiPQpacStjlUhDBqS/CC+yy0QLflVZLM+5HOucQy/4nq", "7R9LWyucGYnr8LHz/rNVHT1JBX/HLkx3kjAxHbIEmIz+KNloRBqHGOE/5WsRvpyT", "XTBDWWk+t1g6+4Xw4ubGeYBmqH0zZ9NK4BwwVuYvLb6CvQKT8W1GUxVBvfTj3qJ+", "FWgMPp3RlQgjcilBSp+RaV9QFb9obalyPo+hsI6pdc2VwF6Ekp0afK2U2sk7Cdbu", "f5EB+aPEONlqRV1KtcNJWBXeIoSUiU4izuFKRYYSa146LjIX8mQj6m1hbv4p+329" ] } }
    7/10/2021 10:56:12 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "w2wA03SXhxEtT40yTP2ZAKZRSQB6k7FELWoUHRQiuWhIpzms7vM94XfbstDJ+vTq1MogXR6PrdxBtKVtxTHOCg==" }, { "pubKeyPrefix": "Eg==", "ed25519": "sRgvMrZbqAZnXXPs+R0ccn+3d2pZztNLI8lqtWbfRhWSJoDHPXB5TjuaKeqRj8gv00J+Lq1/o71f8IEzoDEdCA==" } ] }
    7/10/2021 10:56:12 PM  RX:(00)  { }
    7/10/2021 10:56:12 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957772", "nanos": 37851100 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:12 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:12 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:12 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:13 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "serialNumbers": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ] } } }
    7/10/2021 10:56:13 PM  QX ASK → { "transactionGetRecord": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "transactionID": { "transactionValidStart": { "seconds": "1625957772", "nanos": 37851100 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:13 PM  RX:(00)  { "transactionGetRecord": { "header": { "responseType": "COST_ANSWER", "cost": "8" } } }
    7/10/2021 10:56:13 PM  QX PYMT  { "transactionID": { "transactionValidStart": { "seconds": "1625957773", "nanos": 438581000 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "transfers": { "accountAmounts": [ { "accountID": { "accountNum": "2703" }, "amount": "-8" }, { "accountID": { "accountNum": "3" }, "amount": "8" } ] } } }
    7/10/2021 10:56:13 PM  ├─ SIG → { "sigPair": [ { "ed25519": "eZS2d0wtJ7uegMuY7jCPDVKwlvQhKNKwY5MO4e8VWQxBaPXvQYYLBtIL0YTFVX+Wdj+TKaWKriN4LvE0F4/4BQ==" } ] }
    7/10/2021 10:56:13 PM  └─ QRY → { "transactionGetRecord": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCI3LqIcGEIjukNEBEgMYjxUSAhgDGID4gq0WIgIIeHITChEKBwoDGI8VEA8KBgoCGAMQEBJECkIaQHmUtndMLSe7noDLmO4wjw1SsJb0ISjSsGOTDuHvFVkMQWj170GGCwbSC9GExVV/lnY/kymliq4jeC7xNBeP+AU=" } }, "transactionID": { "transactionValidStart": { "seconds": "1625957772", "nanos": 37851100 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:13 PM  RX:(00)  { "transactionGetRecord": { "header": { }, "transactionRecord": { "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "serialNumbers": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" ] }, "transactionHash": "SZJEZJZnUVyeQW2Vv0wLcuBGFXYFpREeb8znL7B9yq7gZ5ojpDS7I2IzgSsRa4sT", "consensusTimestamp": { "seconds": "1625957772", "nanos": 628031000 }, "transactionID": { "transactionValidStart": { "seconds": "1625957772", "nanos": 37851100 }, "accountID": { "accountNum": "2703" } }, "transactionFee": "1509935", "transferList": { "accountAmounts": [ { "accountID": { "accountNum": "3" }, "amount": "37010" }, { "accountID": { "accountNum": "98" }, "amount": "1472925" }, { "accountID": { "accountNum": "2703" }, "amount": "-1509935" } ] }, "tokenTransferLists": [ { "token": { "tokenNum": "12736" }, "nftTransfers": [ { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "1" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "2" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "3" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "4" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "5" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "6" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "7" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "8" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "9" }, { "senderAccountID": { }, "receiverAccountID": { "accountNum": "12734" }, "serialNumber": "10" } ] } ] } } }
    SETUP COMPLETED: Test Asset Instance
    7/10/2021 10:56:13 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957773", "nanos": 474576600 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "cryptoTransfer": { "tokenTransfers": [ { "token": { "tokenNum": "12736" }, "nftTransfers": [ { "senderAccountID": { "accountNum": "12734" }, "receiverAccountID": { "accountNum": "12733" }, "serialNumber": "1" }, { "senderAccountID": { "accountNum": "12734" }, "receiverAccountID": { "accountNum": "12733" }, "serialNumber": "2" }, { "senderAccountID": { "accountNum": "12734" }, "receiverAccountID": { "accountNum": "12733" }, "serialNumber": "3" }, { "senderAccountID": { "accountNum": "12734" }, "receiverAccountID": { "accountNum": "12733" }, "serialNumber": "4" }, { "senderAccountID": { "accountNum": "12734" }, "receiverAccountID": { "accountNum": "12733" }, "serialNumber": "5" }, { "senderAccountID": { "accountNum": "12734" }, "receiverAccountID": { "accountNum": "12733" }, "serialNumber": "6" } ] } ] } }
    7/10/2021 10:56:13 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "BV/ZlcHhnyswRCJ+cN8CVGAGgPXLcxc9d2fcaib2yLQGJGT+CAPnswTOaQPRTA1APo8M142T2PMpulwqdMo3CQ==" }, { "pubKeyPrefix": "zQ==", "ed25519": "hwvElIVRIqVvhcDlGFtS7WkSUAH86rXjNlZeuDUCtELh2RS2vE4Lio6KembgF0JHeD5LGQ/8FbtTRibSxJU8Aw==" } ] }
    7/10/2021 10:56:13 PM  RX:(00)  { }
    7/10/2021 10:56:13 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957773", "nanos": 474576600 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:13 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:13 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:14 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:14 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    7/10/2021 10:56:14 PM  QX ASK → { "cryptogetAccountBalance": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "accountID": { "accountNum": "12733" } } }
    7/10/2021 10:56:15 PM  RX:(00)  { "cryptogetAccountBalance": { "header": { }, "accountID": { "accountNum": "12733" }, "balance": "14", "tokenBalances": [ { "tokenId": { "tokenNum": "12736" }, "balance": "6" } ] } }
    7/10/2021 10:56:15 PM  QX ASK → { "cryptogetAccountBalance": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "accountID": { "accountNum": "12734" } } }
    7/10/2021 10:56:15 PM  RX:(00)  { "cryptogetAccountBalance": { "header": { }, "accountID": { "accountNum": "12734" }, "balance": "17", "tokenBalances": [ { "tokenId": { "tokenNum": "12736" }, "balance": "4" } ] } }
    7/10/2021 10:56:15 PM  TX     → { "tokenGetInfo": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "token": { "tokenNum": "12736" } } }
    7/10/2021 10:56:15 PM  RX:(00)  { "tokenGetInfo": { "header": { "responseType": "COST_ANSWER", "cost": "10" } } }
    7/10/2021 10:56:15 PM  TX     → { "tokenGetInfo": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCI/LqIcGENyPgrkBEgMYjxUSAhgDGID4gq0WIgIIeHITChEKBwoDGI8VEBMKBgoCGAMQFBJECkIaQKPHi8gKjgvNnOXSUI/lJDf3U7RkLdxH6ucYj/RXsaaFaLhkgLAMBbHSYL/ZaCOr0WpELxyOP+C/0NLBMIeLlgU=" } }, "token": { "tokenNum": "12736" } } }
    7/10/2021 10:56:15 PM  RX:(00)  { "tokenGetInfo": { "header": { "cost": "10" }, "tokenInfo": { "tokenId": { "tokenNum": "12736" }, "name": "QUa8ih50WKpW7QV&835yBr@yzdf25cw&vJtxY*YzR50&6jxSeI", "symbol": "FPOSXPIRDBAAYXLRRSPP", "totalSupply": "10", "treasury": { "accountNum": "12734" }, "adminKey": { "ed25519": "bN6dQhlX7ngeqD/uPLuqjNeRnBStQvgIVLUuG3h6phk=" }, "freezeKey": { "ed25519": "DrLoF6D5MbolbF2lusdPMRRbxs4xvMogTA2wfQmeLCU=" }, "wipeKey": { "ed25519": "OR5y/GnVaGq5gapUDJZEsBkS6InlDOaGzy8BfrbxLZ4=" }, "supplyKey": { "ed25519": "EjUAMfNE5ZfbaT/pPuxclgT4mtPE2rp4zCcJZuVnGsU=" }, "defaultFreezeStatus": "Unfrozen", "autoRenewAccount": { "accountNum": "12735" }, "autoRenewPeriod": { "seconds": "7776000" }, "expiry": { "seconds": "1633733768" }, "memo": "Test Asset: $fGhO9D9QyNYwMGa$OCb", "tokenType": "NON_FUNGIBLE_UNIQUE", "supplyType": "FINITE", "maxSupply": "16000", "feeScheduleKey": { "ed25519": "iMvynR+MaEyC/AHx4NfycOg2SLD1C76+g7F/Q7JcTDw=" } } } }
    7/10/2021 10:56:15 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957775", "nanos": 461927700 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "tokenBurn": { "token": { "tokenNum": "12736" }, "serialNumbers": [ "1" ] } }
    7/10/2021 10:56:15 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "6qPy71uJOtIHJHUf2b3HEVqSmPlCutx+fOfsrpJ85x55/eBBY4kW/AilHwpOgOieaVUdNr5GCfuvlkBsM7InBw==" }, { "pubKeyPrefix": "Eg==", "ed25519": "12le7e2LyNUfjgyzlejMRYyK7bmRn9uhL16u5JbIJwtaaiHxwt4tXF1WbNvX+o2Ctv3xM6xCoSVIQirXSCTUCg==" } ] }
    7/10/2021 10:56:15 PM  RX:(00)  { }
    7/10/2021 10:56:15 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957775", "nanos": 461927700 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:15 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:15 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:16 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:16 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } }, "newTotalSupply": "9" } } }
    7/10/2021 10:56:16 PM  QX ASK → { "cryptogetAccountBalance": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "accountID": { "accountNum": "12733" } } }
    7/10/2021 10:56:16 PM  RX:(00)  { "cryptogetAccountBalance": { "header": { }, "accountID": { "accountNum": "12733" }, "balance": "14", "tokenBalances": [ { "tokenId": { "tokenNum": "12736" }, "balance": "6" } ] } }
    7/10/2021 10:56:16 PM  QX ASK → { "cryptogetAccountBalance": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "accountID": { "accountNum": "12734" } } }
    7/10/2021 10:56:16 PM  RX:(00)  { "cryptogetAccountBalance": { "header": { }, "accountID": { "accountNum": "12734" }, "balance": "17", "tokenBalances": [ { "tokenId": { "tokenNum": "12736" }, "balance": "3" } ] } }
    7/10/2021 10:56:16 PM  TX     → { "tokenGetInfo": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "token": { "tokenNum": "12736" } } }
    7/10/2021 10:56:16 PM  RX:(00)  { "tokenGetInfo": { "header": { "responseType": "COST_ANSWER", "cost": "10" } } }
    7/10/2021 10:56:16 PM  TX     → { "tokenGetInfo": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCJDLqIcGEMy4964DEgMYjxUSAhgDGID4gq0WIgIIeHITChEKBwoDGI8VEBMKBgoCGAMQFBJECkIaQLpnb+Y4dZIGW4lmrY26kgygmSO8RXJV3goXE4mRkOsDNid1rEh3Z6OWbnZsuHxnOoD/XMH3iwUByCwaTvm/Kwo=" } }, "token": { "tokenNum": "12736" } } }
    7/10/2021 10:56:16 PM  RX:(00)  { "tokenGetInfo": { "header": { "cost": "10" }, "tokenInfo": { "tokenId": { "tokenNum": "12736" }, "name": "QUa8ih50WKpW7QV&835yBr@yzdf25cw&vJtxY*YzR50&6jxSeI", "symbol": "FPOSXPIRDBAAYXLRRSPP", "totalSupply": "9", "treasury": { "accountNum": "12734" }, "adminKey": { "ed25519": "bN6dQhlX7ngeqD/uPLuqjNeRnBStQvgIVLUuG3h6phk=" }, "freezeKey": { "ed25519": "DrLoF6D5MbolbF2lusdPMRRbxs4xvMogTA2wfQmeLCU=" }, "wipeKey": { "ed25519": "OR5y/GnVaGq5gapUDJZEsBkS6InlDOaGzy8BfrbxLZ4=" }, "supplyKey": { "ed25519": "EjUAMfNE5ZfbaT/pPuxclgT4mtPE2rp4zCcJZuVnGsU=" }, "defaultFreezeStatus": "Unfrozen", "autoRenewAccount": { "accountNum": "12735" }, "autoRenewPeriod": { "seconds": "7776000" }, "expiry": { "seconds": "1633733768" }, "memo": "Test Asset: $fGhO9D9QyNYwMGa$OCb", "tokenType": "NON_FUNGIBLE_UNIQUE", "supplyType": "FINITE", "maxSupply": "16000", "feeScheduleKey": { "ed25519": "iMvynR+MaEyC/AHx4NfycOg2SLD1C76+g7F/Q7JcTDw=" } } } }
    7/10/2021 10:56:16 PM  TX     → { "tokenGetNftInfos": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "tokenID": { "tokenNum": "12736" }, "end": "9" } }
    7/10/2021 10:56:16 PM  RX:(00)  { "tokenGetNftInfos": { "header": { "responseType": "COST_ANSWER", "cost": "24" } } }
    7/10/2021 10:56:16 PM  TX     → { "tokenGetNftInfos": { "header": { "payment": { "signedTransactionBytes": "CjgKEwoMCJDLqIcGELiBuMgDEgMYjxUSAhgDGID4gq0WIgIIeHITChEKBwoDGI8VEC8KBgoCGAMQMBJECkIaQAyoW8JJC7/iHENbXuxLBzQDPuhP4YPyZCm3RRPnnet9rcfimACiBMsYk5Mz6CaPwV5FaGXYrALQm32FkiCmYww=" } }, "tokenID": { "tokenNum": "12736" }, "end": "9" } }
    7/10/2021 10:56:16 PM  RX:(00)  { "tokenGetNftInfos": { "header": { "cost": "24" }, "nfts": [ { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "10" }, "accountID": { "accountNum": "12734" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "f5EB+aPEONlqRV1KtcNJWBXeIoSUiU4izuFKRYYSa146LjIX8mQj6m1hbv4p+329" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "2" }, "accountID": { "accountNum": "12733" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "qYkA4ejhxKKfyqyCdbe5IKtgRrIEWOH/HGZg/ZOwd3HZEYbG06Pkm4urQPeYH4Zk" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "3" }, "accountID": { "accountNum": "12733" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "39OS4UQNVOjw6qgTiiWDdS+vQ5GEiLhOl5TsDPkjYg+kcR6+eRWMIqgd+DvG/26C" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "4" }, "accountID": { "accountNum": "12733" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "yvv0HtHzS75wKmDknB/Vn2f89SnhIGFTUaqmn2kJdkxdMwLajL75s+hS9swUIBTI" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "5" }, "accountID": { "accountNum": "12733" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "tYuS+jrq3uiZ75LvsfRs07buxHsMI7Lrb/pWPPIVkfkBMf+FmDcxFZWG6fZN9emc" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "6" }, "accountID": { "accountNum": "12733" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "Gjb92G7i2xh0yVY25F8eyiPQpacStjlUhDBqS/CC+yy0QLflVZLM+5HOucQy/4nq" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "7" }, "accountID": { "accountNum": "12734" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "7R9LWyucGYnr8LHz/rNVHT1JBX/HLkx3kjAxHbIEmIz+KNloRBqHGOE/5WsRvpyT" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "8" }, "accountID": { "accountNum": "12734" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "XTBDWWk+t1g6+4Xw4ubGeYBmqH0zZ9NK4BwwVuYvLb6CvQKT8W1GUxVBvfTj3qJ+" }, { "nftID": { "tokenID": { "tokenNum": "12736" }, "serialNumber": "9" }, "accountID": { "accountNum": "12734" }, "creationTime": { "seconds": "1625957772", "nanos": 628031000 }, "metadata": "FWgMPp3RlQgjcilBSp+RaV9QFb9obalyPo+hsI6pdc2VwF6Ekp0afK2U2sk7Cdbu" } ] } }
    7/10/2021 10:56:16 PM  TX     → { "tokenGetAccountNftInfos": { "header": { "payment": { }, "responseType": "COST_ANSWER" }, "accountID": { "accountNum": "12733" }, "end": "1" } }
    7/10/2021 10:56:17 PM  RX:(00)  { "tokenGetAccountNftInfos": { "header": { "nodeTransactionPrecheckCode": "FAIL_INVALID", "responseType": "COST_ANSWER" } } }
    STARTING TEARDOWN: Test Asset Instance
    7/10/2021 10:56:17 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957777", "nanos": 96138900 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "TestAssetInstance Teardown: Attempting to delete Asset from Network (may already be deleted)", "tokenDeletion": { "token": { "tokenNum": "12736" } } }
    7/10/2021 10:56:17 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "6rqltoeWzKzGlr6PQBMFPuDbfGGSLMPU9fyYB/n4uAnPm1Wjh8MMEMYsDFJ6xXJawHHDTZw9YoX2zZhpUU6hDA==" }, { "pubKeyPrefix": "bA==", "ed25519": "D/0exu431aUCJol+uKNOlxT+Qq+ggEkpbSXcJlWz9rOWzw5GCb1HcvOMOXMP/qZsnHdBqE9uHZncJ7NqmS5RAg==" } ] }
    7/10/2021 10:56:17 PM  RX:(00)  { }
    7/10/2021 10:56:17 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957777", "nanos": 96138900 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:17 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:17 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:17 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:18 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    STARTING TEARDOWN: Test Account Instance
    7/10/2021 10:56:18 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957778", "nanos": 483227400 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance Teardown: Attempting to delete Account from Network (if exists)", "cryptoDelete": { "transferAccountID": { "accountNum": "2703" }, "deleteAccountID": { "accountNum": "12734" } } }
    7/10/2021 10:56:18 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "k1ogcQ2fyHc/88cBeNSFC//RMZL3Pesohd3/oNekXLV7al2sFUvDSs6ybiaCFKronYaaK2rIYL1p8RUc4cVWDg==" }, { "pubKeyPrefix": "zQ==", "ed25519": "c/Ri7vBAR+WySkD9VYPa3G6KB/wT15yZaAxokI+knqSI703o8XjU40QfHcribY9pt+TJtmTCXONluBWyRC8OCw==" } ] }
    7/10/2021 10:56:18 PM  RX:(00)  { }
    7/10/2021 10:56:18 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957778", "nanos": 483227400 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:18 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:18 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:19 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:19 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    TEARDOWN COMPLETED: Test Account Instance
    STARTING TEARDOWN: Test Account Instance
    7/10/2021 10:56:19 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957779", "nanos": 842016700 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance Teardown: Attempting to delete Account from Network (if exists)", "cryptoDelete": { "transferAccountID": { "accountNum": "2703" }, "deleteAccountID": { "accountNum": "12735" } } }
    7/10/2021 10:56:19 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "sCrHU1CEhbIadFLCWGLMASDbYY8pzyKrw+xY7iXhJ3BaRLrkBUM3QQ1u5iZDGcWhciMV5IH28Byyt3UY29HTBQ==" }, { "pubKeyPrefix": "8A==", "ed25519": "ndeLwXcSRs5pZReLkkEXvBkzA+fp01p1Y0HX0X///0FSVDxargqmbdY6Y+xqr6uJiKKTH/p9YJMjUTnYz6FWDA==" } ] }
    7/10/2021 10:56:19 PM  RX:(00)  { }
    7/10/2021 10:56:19 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957779", "nanos": 842016700 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:19 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:20 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:20 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:21 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    TEARDOWN COMPLETED: Test Account Instance
    TEARDOWN COMPLETED Test Asset Instance
    STARTING TEARDOWN: Test Account Instance
    7/10/2021 10:56:21 PM  TX BODY  { "transactionID": { "transactionValidStart": { "seconds": "1625957781", "nanos": 208938200 }, "accountID": { "accountNum": "2703" } }, "nodeAccountID": { "accountNum": "3" }, "transactionFee": "6000000000", "transactionValidDuration": { "seconds": "120" }, "memo": "Test Account Instance Teardown: Attempting to delete Account from Network (if exists)", "cryptoDelete": { "transferAccountID": { "accountNum": "2703" }, "deleteAccountID": { "accountNum": "12733" } } }
    7/10/2021 10:56:21 PM  └─ SIG → { "sigPair": [ { "pubKeyPrefix": "Qg==", "ed25519": "BrYpK9rka0/V+4lB1JbWcofjD5lM98ZjLT6f/0sUjZhirAYwAN7DtoUDYpJ83NAol2qgnTaXqfRFcX5MoJCYBQ==" }, { "pubKeyPrefix": "hw==", "ed25519": "pYKPMlwJ9C8cU+dsWonttJXfOgNODxrvc7pEuqwPjJC4li60mg7MeE3ouXKnEt+PzlO7Tt8y2P9tJEdx7YqzAg==" } ] }
    7/10/2021 10:56:21 PM  RX:(00)  { }
    7/10/2021 10:56:21 PM  TX     → { "transactionGetReceipt": { "transactionID": { "transactionValidStart": { "seconds": "1625957781", "nanos": 208938200 }, "accountID": { "accountNum": "2703" } } } }
    7/10/2021 10:56:21 PM  RX:(00)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:21 PM  RX:(01)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:21 PM  RX:(02)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "UNKNOWN" } } }
    7/10/2021 10:56:22 PM  RX:(03)  { "transactionGetReceipt": { "header": { }, "receipt": { "status": "SUCCESS", "exchangeRate": { "currentRate": { "hbarEquiv": 1, "centEquiv": 12, "expirationTime": { "seconds": "4102444800" } }, "nextRate": { "hbarEquiv": 1, "centEquiv": 15, "expirationTime": { "seconds": "4102444800" } } } } } }
    TEARDOWN COMPLETED: Test Account Instance
```

.NET Integration Test Source Code:

```C#
        [Fact(DisplayName = "Burn Assets: Can Burn Single Asset The Treasury Does Not Own")]
        public async Task CanBurnSingleAssetTheTreasuryDoesNotOwn()
        {
            await using var fxAccount = await TestAccount.CreateAsync(_network);
            await using var fxAsset = await TestAsset.CreateAsync(_network, fx => fx.Params.GrantKycEndorsement = null, fxAccount);

            var amountToTransfer = 2 * fxAsset.Metadata.Length / 3;
            var expectedTreasury = fxAsset.Metadata.Length - amountToTransfer;
            var serialNumbersTransfered = Enumerable.Range(1, amountToTransfer).Select(i => (long)i);

            var transferParams = new TransferParams
            {
                AssetTransfers = serialNumbersTransfered.Select(sn => new AssetTransfer(new Asset(fxAsset.Record.Token, sn), fxAsset.TreasuryAccount, fxAccount)),
                Signatory = fxAsset.TreasuryAccount
            };

            await fxAsset.Client.TransferAsync(transferParams);

            Assert.Equal((ulong)amountToTransfer, await fxAccount.Client.GetAccountTokenBalanceAsync(fxAccount, fxAsset));
            Assert.Equal((ulong)expectedTreasury, await fxAsset.Client.GetAccountTokenBalanceAsync(fxAsset.TreasuryAccount, fxAsset));
            Assert.Equal((ulong)fxAsset.Metadata.Length, (await fxAsset.Client.GetTokenInfoAsync(fxAsset)).Circulation);

            var reciept = await fxAsset.Client.BurnAssetAsync(new Asset(fxAsset.Record.Token, 1), fxAsset.SupplyPrivateKey);
            Assert.Equal(ResponseCode.Success, reciept.Status);
            Assert.Equal((ulong)fxAsset.Metadata.Length - 1, reciept.Circulation);

            // TODO: NETWORK BUG: Token balances are corrupted.  Treasury is deducted when account balance should be instead.
            Assert.Equal((ulong)amountToTransfer, await fxAccount.Client.GetAccountTokenBalanceAsync(fxAccount, fxAsset));
            Assert.Equal((ulong)expectedTreasury - 1, await fxAsset.Client.GetAccountTokenBalanceAsync(fxAsset.TreasuryAccount, fxAsset));
            Assert.Equal((ulong)fxAsset.Metadata.Length - 1, (await fxAsset.Client.GetTokenInfoAsync(fxAsset)).Circulation);

            // HOWEVER when getting the list of tokens, the accounting is correct
            var allAssets = await fxAccount.Client.GetAssetInfoAsync(fxAsset.Record.Token, 0, fxAsset.Metadata.Length - 1);
            Assert.Equal(fxAsset.Metadata.Length - 1, allAssets.Count);
            var treasuryCount = 0;
            var accountCount = 0;
            foreach(var asset in allAssets)
            {
                // Confirm Serial Numbers and Metadata Match
                Assert.True(fxAsset.Metadata[asset.Asset.SerialNum - 1].ToArray().SequenceEqual(asset.Metadata.ToArray()));
                if (asset.Owner == fxAccount.Record.Address)
                {
                    accountCount++;
                    Assert.True(asset.Asset.SerialNum <= amountToTransfer);
                }
                else
                {
                    treasuryCount++;
                    Assert.True(asset.Asset.SerialNum > amountToTransfer);
                }
            }
            Assert.Equal(amountToTransfer - 1, accountCount);
            Assert.Equal(expectedTreasury, treasuryCount);

            // and we should not find this, we explicitly destroyed serial number 1 above.
            Assert.Null(allAssets.FirstOrDefault(a => a.Asset.SerialNum == 1));

            // and this call gets corrupted
            var pex = await Assert.ThrowsAsync<PrecheckException>(async () =>
            {
                await fxAccount.Client.GetAccountAssetInfoAsync(fxAccount.Record.Address, 0, 1);
            });
            Assert.Equal(ResponseCode.FailInvalid, pex.Status);
        }
```

### Hedera network

previewnet

### Version

v0.16.0-alpha1 (presumably deployed on previewnet)

### Operating system

Windows

### LINKED ISSUE #1786: PREVIEWNET Should reject use of non-fungible unique in tokenTransferLists
### Description

A `CryptoTransfer` specifying a non-fungible unique token in the `tokenTransferLists` _should_ be rejected with `TOKEN_TRANSFERS_LIST_ONLY_USABLE_WITH_FUNGIBLE_COMMON`.

Instead the "owned NFTs" fields of the accounts involved are treated as if they were fungible common token balances.

### Steps to reproduce

E.g. EET [here](https://github.com/hashgraph/hedera-services/blob/01783-M-RestoreDissocCheck/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java#L118).

### Additional context

_No response_

### Hedera network

previewnet

### Version

v0.16.0-alpha.1

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issues**
 - Closes #1783
 - Closes #1785 
 - Closes #1786 

**Note to reviewer**
- The `TransactionRecordService` change is just javadoc and minor stylistic changes.

**Summary of changes**:
- _(1783)_ Refactor `Account.dissociateWith()` to use a `Dissociation` process object to manage the `TokenRelationship` models affected by a dissociation.
    * Update `TypedTokenStore.persist(TokenRelationship)` to remove a dissociated relationship from the Merkle state when observing a new `TokenRelationship.isDestroyed()` flag is set. (Set by `Dissociation.updateModelRelsSubjectTo()` method.)
    * Resolve to `ACCOUNT_STILL_OWNS_NFTS` when dissociating a relationship between a unique token and an account that still holds NFTs (even if the token is expired).
- _(1785)_ Enforce the requirement that burned NFTs be held by the treasury by updating `TokenBurnTransitionLogic` to load the `UniqueToken`s to be burned, and then asserting ownership in `Token.burn()`.
- _(1786)_ Resolve to `TOKEN_TRANSFERS_LIST_ONLY_USABLE_WITH_FUNGIBLE_COMMON` in `HederaTokenStore` when sanity-checking a non-ownership change involving a `NON_FUNGIBLE_UNIQUE` token.
- Fix mismatch in `MerkleUniqueTokenId` serde.
- Fix use of default payer in HIP-18 `TokenTransactSpecs` w/ custom HTS fees.
- Allow `GetAccountNftInfos` to be used with a contract account.
- Remove auxiliary `Set<NftId>` from `BackingNfts` to reduce per-NFT memory footprint.
- Remove deprecated `CopyOnWriteIds.removeAll(Set<TokenID>)` and `MerkleAccountTokens.dissociateAll()` methods.
- Remove refactored, now unused `TokenStore.wipe()` method.
- Add various EETs for related issues.

### CODE REVIEW

File: hedera-node/src/test/java/com/hedera/services/txns/token/TokenDissociateTransitionLogicTest.java [hunk 1]
```diff
@@ -1,207 +1,146 @@
 package com.hedera.services.txns.token;
 
-/*-
```
Comment (Daniel-K-Ivanov) [inline hedera-node/src/test/java/com/hedera/services/txns/token/TokenDissociateTransitionLogicTest.java:3]: nit: I think that the license was removed by mistake

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java [hunk 2]
```diff
@@ -99,11 +106,166 @@ public static void main(String... args) {
...
+				).when(
+						mintToken(B_TOKEN, List.of(ByteString.copyFromUtf8("dark"))),
+						tokenAssociate(theAccount, List.of(A_TOKEN, B_TOKEN))
+				).then(
+						cryptoTransfer(
+								movingUnique(1, A_TOKEN).between(TOKEN_TREASURY, theAccount)
+						).hasKnownStatus(INVALID_NFT_ID),
+						cryptoTransfer(
+								moving(1, B_TOKEN).between(TOKEN_TREASURY, theAccount)
+						).hasKnownStatus(TOKEN_TRANSFERS_LIST_ONLY_USABLE_WITH_FUNGIBLE_COMMON)
```
Comment (Daniel-K-Ivanov) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java:145]: I think that `TOKEN_TRANSFERS_LIST_ONLY_USABLE_WITH_FUNGIBLE_COMMON ` might not be the best response code in this situation since technically speaking `Token Transfer List` is used with non-fungible uniques. NftTransfers are placed inside the `token-transfer-list`:

```
message TokenTransferList {
    TokenID token = 1; // The ID of the token
    repeated AccountAmount transfers = 2; // Applicable to tokens of type FUNGIBLE_COMMON. Multiple list of AccountAmounts, each of which has an account and amount
    repeated NftTransfer nftTransfers = 3; // Applicable to tokens of type NON_FUNGIBLE_UNIQUE. Multiple list of NftTransfers, each of which has a sender and receiver account, including the serial number of the NFT
}
```
 Maybe a better response code would be `INVALID_TOKEN_ID`

**Review by Daniel-K-Ivanov — DISMISSED** [review]
LGTM! Added 2 nits and one comment related to the suitability of the `TOKEN_TRANSFERS_LIST_ONLY_USABLE_WITH_FUNGIBLE_COMMON ` response code

**Review by ljianghedera — APPROVED** [review]
LGTM

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java (hunk 2 above)
Comment (tinker-michaelj) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java:145]: Ah good point! Refined to `ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON`.

File: hedera-node/src/test/java/com/hedera/services/txns/token/TokenDissociateTransitionLogicTest.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/src/test/java/com/hedera/services/txns/token/TokenDissociateTransitionLogicTest.java]: Restored.

File: hedera-node/src/main/java/com/hedera/services/store/TypedTokenStore.java [hunk 3]
```diff
@@ -385,9 +395,13 @@ private void initModelFields(UniqueToken uniqueToken, MerkleUniqueToken immutabl
...
-		final var accountId = newRel.getAccount().getId();
-		backingTokenRels.addToExistingRels(Pair.of(
+		backingTokenRels.addToExistingRels(legacyReprOf(newRel));
+	}
+
+	static Pair<AccountID, TokenID> legacyReprOf(TokenRelationship rel) {
+		final var tokenId = rel.getToken().getId();
+		final var accountId = rel.getAccount().getId();
+		return Pair.of(
 				AccountID.newBuilder()
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/store/TypedTokenStore.java]: Done!

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java [hunk 4]
```diff
@@ -111,6 +122,157 @@ public static void main(String... args) {
...
+								.tokenType(TokenType.NON_FUNGIBLE_UNIQUE)
+								.initialSupply(0L)
+								.treasury(TOKEN_TREASURY)
+				).when(
+						mintToken(B_TOKEN, List.of(ByteString.copyFromUtf8("dark"))),
+						tokenAssociate(theAccount, List.of(A_TOKEN, B_TOKEN))
+				).then(
+						cryptoTransfer(
+								movingUnique(1, A_TOKEN).between(TOKEN_TREASURY, theAccount)
+						).hasKnownStatus(INVALID_NFT_ID),
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java:149]: Should we also add `NFT_TRANSFERS_ONLY_ALLOWED_FOR_NON_FUNGIBLE_UNIQUE`?

**Review by qnswirlds — DISMISSED** [review]
