### PR TITLE
[ETX-006] Invalid data in ethereum body fails and charges relayer

### LINKED ISSUE #3213: Invalid data in ethereum body fails and charges relayer
- Unit test for the above.
- Probably want a large vector with creative ways to fail.  This includes only parsing.
- we can assert it fails without the charging

### PR DESCRIPTION
**Pull request by georgiyazovaliiski**
**Description**:
Failing parsing cases for ethereum transaction data.

**Related issue(s)**:

Fixes #3213

### CODE REVIEW

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java [hunk 1]
```diff
@@ -176,18 +180,66 @@ void whiteBoxDecodingErrors() {
...
+		// legacy TX with too few RLP entries
+		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeAsList(size_1)));
 		// type 2 TX with too many RLP entries
 		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 2 }, size_13)));
+		// type 2 TX with too few RLP entries
+		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 2 }, size_1)));
 		// Unsupported Transaciton Type
 		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 127 }, size_13)));
+		// Trimmed End Bytes
+		assertThrows(IllegalArgumentException.class, () ->
```
Comment (mustafauzunn) [inline hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:197]: There we will have sonar code smell: Only one method invocation is expected when testing runtime exceptions

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java [hunk 2]
```diff
@@ -176,18 +180,66 @@ void whiteBoxDecodingErrors() {
...
+	@Test
+	void parsingErrors() {
+		final var wrongData = Hex.encode(ByteString.copyFromUtf8("wrong").toByteArray());
+
+		// invalid nonce
+		var normalData = normalRlpData();
+		normalData[1] = wrongData;
+		final var invalidNonceData = Arrays.asList(normalData);
+
+		assertThrows(IllegalArgumentException.class, () ->
```
Comment (mustafauzunn) [inline hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:223]: There we will have sonar code smell: Only one method invocation is expected when testing runtime exceptions

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java [hunk 3]
```diff
@@ -176,18 +180,66 @@ void whiteBoxDecodingErrors() {
...
+				EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 2 },	invalidNonceData)));
+
+		// invalid gasLimit
+		normalData = normalRlpData();
+		normalData[4] = wrongData;
+		final var invalidGasLimitData = Arrays.asList(normalData);
+
+		assertThrows(IllegalArgumentException.class, () ->
```
Comment (mustafauzunn) [inline hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:231]: There we will have sonar code smell: Only one method invocation is expected when testing runtime exceptions

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java [hunk 4]
```diff
@@ -176,18 +180,66 @@ void whiteBoxDecodingErrors() {
...
+				EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 2 },	invalidGasLimitData)));
+
+		// invalid recId
+		normalData = normalRlpData();
+		normalData[9] = wrongData;
+		final var invalidRecIdData = Arrays.asList(normalData);
+
+		assertThrows(IllegalArgumentException.class, () ->
```
Comment (mustafauzunn) [inline hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:239]: There we will have sonar code smell: Only one method invocation is expected when testing runtime exceptions

**Review by mustafauzunn — CHANGES_REQUESTED** [review]

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java (hunk 1 above)
Comment (shemnon) [reply hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:197]: Sonar was right, the coding of the test was not correct.  We shouldn't re-encode the already encoded RLP.

This exposes a bug, we should be returning null not throwing exceptions.

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java [hunk 5]
```diff
@@ -176,18 +180,66 @@ void whiteBoxDecodingErrors() {
...
+		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeAsList(size_1)));
 		// type 2 TX with too many RLP entries
 		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 2 }, size_13)));
+		// type 2 TX with too few RLP entries
+		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 2 }, size_1)));
 		// Unsupported Transaciton Type
 		assertNull(EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(new byte[] { 127 }, size_13)));
+		// Trimmed End Bytes
+		assertThrows(IllegalArgumentException.class, () ->
+				EthTxData.populateEthTxData(RLPEncoder.encodeSequentially(Hex.decode(RAW_TX_TYPE_0_TRIMMED_LAST_BYTES))));
```
Comment (shemnon) [inline hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:198]:
```suggestion
		assertNull(EthTxData.populateEthTxData(Hex.decode(RAW_TX_TYPE_0_TRIMMED_LAST_BYTES)));
```

This should be coupled with a change to EthTxData.populateEthTxData to wrap the whole body in a 
```java
    try {
      // whole contents of populateEthTxData
    } catch(IllegalArgumentException iae) {
      return null;
    }
```
This is because headlong throws IllegalArgumentExceptions on a parsing error, and we want to return null indicating there was no valid RLP data.

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java (hunk 2 above)
Comment (shemnon) [reply hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:223]: Again, populateEthTxData should throw no exceptions, this should be assertNull

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java (hunk 3 above)
Comment (shemnon) [reply hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:231]: This should be null

File: hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java (hunk 4 above)
Comment (shemnon) [reply hedera-node/src/test/java/com/hedera/services/txns/ethereum/EthTxDataTest.java:239]: this should be null

**Review by shemnon — CHANGES_REQUESTED** [review]
I'd say these tests found a bug.  :)

**Review by shemnon — APPROVED** [review]
Merge if you like my changes.
