### PR TITLE
Remove impure Repository references in contract queries

### LINKED ISSUE #471: Race condition caused by ContractCallLocal bug
**Summary of the defect**
The `ContractCallLocal` answer incorrectly uses the persistent `ServicesRepositoryRoot` to look up the ["sender nonce"](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/legacy/handler/SmartContractRequestHandler.java#L578). This opens the door to a race condition with the `handleTransaction` thread. 

**How to reproduce (if possible)**
In progress.

**Service logs**
A believed possible symptom is,
```
java.lang.IllegalArgumentException: tried to modify an immutable FCQueue
        at com.swirlds.fcqueue.FCQueue.add(FCQueue.java:254) ~[swirlds-fcqueue-0.7.2.jar:?]
        at com.swirlds.fcqueue.FCQueue.offer(FCQueue.java:427) ~[swirlds-fcqueue-0.7.2.jar:?]
        at com.hedera.services.ledger.HederaLedger.addReturningEarliestExpiry(HederaLedger.java:271) ~[?:?]
        at com.hedera.services.ledger.HederaLedger.addPayerRecord(HederaLedger.java:266) ~[?:?]
        at com.hedera.services.state.expiry.ExpiringCreations.createExpiringRecord(ExpiringCreations.java:111) ~[?:?]
        at com.hedera.services.state.expiry.ExpiringCreations.createExpiringPayerRecord(ExpiringCreations.java:64) ~[?:?]
        at com.hedera.services.records.FeeChargingRecordsHistorian.addNewRecords(FeeChargingRecordsHistorian.java:122) ~[?:?]
        at com.hedera.services.ledger.HederaLedger.commit(HederaLedger.java:121) ~[?:?]
        at com.hedera.services.legacy.services.state.AwareProcessLogic.processInLedgerTxn(AwareProcessLogic.java:149) ~[?:?]
        at com.hedera.services.legacy.services.state.AwareProcessLogic.incorporateConsensusTxn(AwareProcessLogic.java:108) ~[?:?]
        at com.hedera.services.ServicesState.handleTransaction(ServicesState.java:177) ~[?:?]
        at com.swirlds.platform.EventFlow.handleTransaction(EventFlow.java:758) ~[swirlds-platform-core-0.7.2.jar:?]
        at com.swirlds.platform.EventFlow.takeHandlePut(EventFlow.java:1231) ~[swirlds-platform-core-0.7.2.jar:?]
        at com.swirlds.platform.EventFlow.doCons(EventFlow.java:821) ~[swirlds-platform-core-0.7.2.jar:?]
        at com.swirlds.platform.StoppableThread$StoppableRunnable.run(StoppableThread.java:132) [swirlds-platform-core-0.7.2.jar:?]
```
Which will cause an ISS isolated to the node which succumbs to the race condition.

### LINKED ISSUE #475: Merge Swirlds SDK Release 0.7.3
Merge Swirlds SDK Release 0.7.3

https://github.com/swirlds/swirlds-internal-sdk/blob/master/Swirlds%20SDK%20-%20version%200.7.3.zip

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Closes #471 
- Closes #475

**Summary of the change**:
Remove all impure usage of the mutable `ServicesRepositoryRoot` in smart contract queries.
- Delete the [obsolete](https://github.com/hashgraph/hedera-services/pull/478/files#diff-98e68de2c727cd6819590f97951000f0L469) [calls](https://github.com/hashgraph/hedera-services/pull/478/files#diff-98e68de2c727cd6819590f97951000f0L588) to `ServicesRepositoryRoot#getNonce` which always return `BigInteger.ZERO`.
- Refactor the `ContractGetByteCode` query as an [`AnswerService` implementation](https://github.com/hashgraph/hedera-services/pull/478/files#diff-489b465f5370d6bfb85a39f846546d78R480).

Other improvements:
- [Fail fast](https://github.com/hashgraph/hedera-services/pull/478/files#diff-f7f12fa164aa28b945b16a3faeaa5854R106) and capture the error in logs if `MerkleAccount#copy` is called on an immutable instance.
- Refactor the transactional processing + error handling in legacy `AwareProcessLogic` into a dedicated [`ServicesTxnManager`](https://github.com/hashgraph/hedera-services/pull/478/files#diff-10dffbc67fab6906b17a67c3a0a87571R48), ensuring exceptions are not propagated to the Platform.
- Add [query stress tests](https://github.com/hashgraph/hedera-services/pull/478/files#diff-1d37e48f9ceff6d8030570cd36286a61R840) to the end of regression runs.
- Various improvements to forensics "tests" for analysis of e.g. record streams.

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/GetBytecodeResourceUsage.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
+package com.hedera.services.fees.calculation.contract.queries;
+
+import com.hedera.services.context.primitives.StateView;
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/GetBytecodeResourceUsage.java:3]: copyright missing

File: hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/GetBytecodeResourceUsage.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import com.hedera.services.fees.calculation.QueryResourceUsageEstimator;
+import com.hedera.services.fees.calculation.crypto.queries.GetTxnRecordResourceUsage;
+import com.hederahashgraph.api.proto.java.FeeData;
+import com.hederahashgraph.api.proto.java.Query;
+import com.hederahashgraph.api.proto.java.ResponseType;
+import com.hederahashgraph.fee.SmartContractFeeBuilder;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/fees/calculation/contract/queries/GetBytecodeResourceUsage.java:11]: Missing license header

File: hedera-node/src/test/java/com/hedera/test/forensics/AccountsReader.java [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+import com.hedera.services.state.submerkle.SolidityFnResult;
+import com.swirlds.common.constructable.ClassConstructorPair;
+import com.swirlds.common.constructable.ConstructableRegistry;
+import com.swirlds.common.merkle.io.MerkleDataInputStream;
+import com.swirlds.common.merkle.utility.MerkleLong;
+import com.swirlds.fcmap.FCMap;
+import com.swirlds.fcmap.internal.FCMInternalNode;
+import com.swirlds.fcmap.internal.FCMLeaf;
+import com.swirlds.fcmap.internal.FCMTree;
+import com.swirlds.fcqueue.FCQueue;
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/test/forensics/AccountsReader.java:20]: Missing license header
