### PR TITLE
Fixed issue with prefetch task submission (#2427)

### LINKED ISSUE #2427: Prefetch queue not draining
### Description

After enabling logging, noticed that the prefetch queue is not draining properly. The bug does not impact the caching of the EVM bytecode but it basically makes the prefetch stage useless.

### Steps to reproduce

Found issue by adding logging inside the prefetch Runnable lambda. Enabled global logging by editing the log4j.xml top-level logging setting. Noticed that enqueuing of the Runnable is happening but the execution of the Runnable is not being triggered.

### Additional context

_No response_

### Hedera network

other

### Version

v0.20

### Operating system

macOS

### PR DESCRIPTION
**Pull request by superboo**
**Description**:
Fix use of ExecutorService when scheduling pre-fetch EVM bytecode task.

**Related issue(s)**:
Fixes #2427

**Notes for reviewer**:
This PR is a duplicate of a previous one that was targeted for smart-contracts/virtual-map. That PR ran into merge conflicts with the base layer and was abandoned. This PR is targeted to vm-plus-020-test.3.

The sonar errors are caused by files with duplication rates > 1% in the `com.hedera.services.state.virtual` package (in the base layer). Michael has suggested to ignore them as those files are reworked in the hts-contracts branch.

In unit tests, kept one use of Thread.sleep() to add latency during task performing. This delay helps when trying to reproduce scenario when queue fills up. Without the delay, the performing of the tasks can be too quick and the queue empties before the check.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/src/test/java/com/hedera/services/txns/prefetch/PrefetchProcessorTest.java [hunk 1]
```diff
@@ -140,68 +155,62 @@ ExecutorService createExecutorService(int threadPoolSize, BlockingQueue<Runnable
...
+        for (int i = 0; i < 20; i++) {
+            processor.submit(accessor);
+        }
 
-        assertTrue(processor.offer(accessor));
-        assertFalse(processor.offer(accessor));
-        assertThat(
-                logCaptor.warnLogs(),
-                contains(Matchers.startsWith("Pre-fetch queue is FULL")));
+        System.out.println(rejected.size());
```
Comment (anighanta) [inline hedera-node/src/test/java/com/hedera/services/txns/prefetch/PrefetchProcessorTest.java:190]: nit : print statement could be removed

**Review by anighanta — APPROVED** [review]

File: hedera-node/src/test/java/com/hedera/services/txns/prefetch/PrefetchProcessorTest.java (hunk 1 above)
Comment (superboo) [reply hedera-node/src/test/java/com/hedera/services/txns/prefetch/PrefetchProcessorTest.java]: removed

**Review by OlegMazurov — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM
