### PR TITLE
test: fix ConsistencyTestingTool system transactions filtering

### LINKED ISSUE #17588: JTR failure for `Consistency-Hard-Restart-10m` possible not correct detecting of system transactions
This [JTR run](http://35.247.76.217:8095/swirlds-automation/main/4N/Restart/20250128-053555-GCP-Daily-Restart-4N/Consistency-Hard-Restart-10m/) failed in `ConsistencyTestingTool`.

First analysis looks like the filtering of system transactions is not working.

See `ConsistencyTestingToolRound#fromRound` this looks like it's needing an update.

### PR DESCRIPTION
**Pull request by mustafauzunn**
**Description**:

Fix ConsistencyTestingTool system transactions filtering

**Related issue(s)**:

Fixes #17588 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolRound.java [hunk 1]
```diff
@@ -63,6 +64,9 @@ public static ConsistencyTestingToolRound fromRound(final @NonNull Round round,
             if (transaction.isSystem()) {
                 return;
             }
+            if (isSystemTransaction(transaction)) {
+                return;
+            }
```
Comment (IvanKavaldzhiev) [inline platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolRound.java:69]:
```suggestion
            if (transaction.isSystem() || isSystemTransaction(transaction)) {
                return;
            }
```

**Review by lpetrovic05 — APPROVED** [review]

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM
