### PR TITLE
make ledeger Id a byteString of just hex bytes rather than a bytes from a stirng representation of hex

### LINKED ISSUE #2841: Ledger ID should return 00, 01, 02 for networks
### Description

- For testnet, the ledger ID returns `30783031` when it should return `01`
- `30783031`is the UTF-8 encoding of the Unicode string "0x01" instead of the big-endian representation of the number whose hex encoding is 0x01

Related HIPs: [33](https://hips.hedera.com/hip/hip-33), [198](https://hips.hedera.com/hip/hip-198)

0x00  Hedera mainnet
0x01  Hedera stable testnet
0x02  Hedera preview net

### Steps to reproduce

Get the ledger ID from an info response. 

### Additional context

_No response_

### Hedera network

testnet

### Version

0.22.3

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by anighanta**
**Description**:

**Related issue(s)**:

Fixes #2841 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/config/NetworkInfo.java [hunk 1]
```diff
@@ -47,8 +48,22 @@ public ByteString ledgerId() {
...
 			 *   0x03 -> other dev or preprod networks
 			 */
-			ledgerId = ByteString.copyFromUtf8(properties.getStringProperty("ledger.id"));
+			ledgerId = rationalize(properties.getStringProperty("ledger.id"));
 		}
 		return ledgerId;
 	}
+
+	private ByteString rationalize(String ledgerProperty) {
+		if (!ledgerProperty.startsWith("0x")) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/config/NetworkInfo.java:57]: Can't we just wrap a call to `com.swirlds.common.CommonUtils.unhex(ledgerProperty)` in a `try-catch (IllegalArgumentException)` and get the same result?

File: test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java [hunk 2]
```diff
@@ -132,7 +132,7 @@ protected void assertExpectationsGiven(HapiApiSpec spec) throws Throwable {
 		var actualTokenRels = actualInfo.getTokenRelationshipsList();
 		assertExpectedRels(contract, relationships, actualTokenRels, spec);
 		assertNoUnexpectedRels(contract, absentRelationships, actualTokenRels, spec);
-		Assertions.assertEquals(ByteString.copyFromUtf8(expectedLedgerId), actualInfo.getLedgerId());
+		Assertions.assertEquals(rationalize(expectedLedgerId), actualInfo.getLedgerId());
```
Comment (tinker-michaelj) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java:135]: It's probably better to have these `ledgerId` assertions in the `*GetInfo` queries be off by default; otherwise, every time we want to run a query against a non-dev network, it will fail. 😂

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
Semantic changes LGTM! But we'd probably prefer to re-use the `CommonUtils` library for the hex decoding.

File: hedera-node/src/main/java/com/hedera/services/config/NetworkInfo.java (hunk 1 above)
Comment (anighanta) [reply hedera-node/src/main/java/com/hedera/services/config/NetworkInfo.java:57]: Makes sense. But `unhex()` still needs the **`0x`**  to be missing from the string when it parses the big-endian representation.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
