### PR TITLE
06788 Better handling of failed async hashing

### LINKED ISSUE #6788: Better exception handling in `MerkleUtils#rehashTree`
### Problem

Currently the exception is handled this way in `MerkleUtils#rehashTree`:

```
  final Future<Hash> future = MerkleCryptoFactory.getInstance().digestTreeAsync(root);
            try {
                return future.get();
            } catch (InterruptedException | ExecutionException e) {
                Thread.currentThread().interrupt();
            }
```

So, if any exception happens during the hashing, the stacktrace is lost. 

### Solution

This exception must not be swallowed. It should do two things:
- Log the exception it caught
-  Rethrow the  `ExecutionException` wrapped in some unchecked exception

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

Currently the exception is handled this way in MerkleUtils#rehashTree:
```
  final Future<Hash> future = MerkleCryptoFactory.getInstance().digestTreeAsync(root);
            try {
                return future.get();
            } catch (InterruptedException | ExecutionException e) {
                Thread.currentThread().interrupt();
            }
```
So, if any exception happens during the hashing, the stacktrace is lost.

This exception must not be swallowed. It should do two things:

Log the exception it caught
Rethrow the ExecutionException wrapped in some unchecked exception

**Related issue(s)**:

Fixes #6788

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by artemananiev — DISMISSED** [review]

**Review by OlegMazurov — APPROVED** [review]

**Review by artemananiev — DISMISSED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleUtils.java [hunk 1]
```diff
@@ -58,8 +65,12 @@ public static Hash rehashTree(final MerkleNode root) {
             final Future<Hash> future = MerkleCryptoFactory.getInstance().digestTreeAsync(root);
             try {
                 return future.get();
-            } catch (InterruptedException | ExecutionException e) {
+            } catch (InterruptedException e) {
+                logger.error(EXCEPTION.getMarker(), "Interrupted while waiting for tree hashing to complete", e);
                 Thread.currentThread().interrupt();
+            } catch (ExecutionException e) {
+                logger.error(EXCEPTION.getMarker(), "Async tree hashing failed", e);
+                throw new MerkleSynchronizationException(e);
```
Comment (cody-littley) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleUtils.java:73]: This exception type is intended for use by the reconnect algorithm (which is sometimes called "synchronization").

Comment (imalygin) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleUtils.java]: Fair enough. I added an exception that is specific to this failure.

**Review by artemananiev — APPROVED** [review]

**Review by OlegMazurov — APPROVED** [review]

**Review by cody-littley — APPROVED** [review]
