### PR TITLE
fix: 11496 Rewrote `testFlushBackpressure`.

### LINKED ISSUE #11496: Rewrite `VirtualPipelineTests#flushThrottle`
### Description

Current implementation of `VirtualPipelineTests#flushThrottle` is way too sensitive to the environment load and, therefore, unstable. 
It has to be re-written to eliminate dependency on `Thread.sleep`. 

### Steps to reproduce

Run `VirtualPipelineTests#flushThrottle`

### Additional context

_No response_

### Hedera network

other

### Version

v0.47

### Operating system

None

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

Rewrote `testFlushBackpressure`. Added  `testFamilySizeBackpressure`.

**Related issue(s)**:

Fixes #11496 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java [hunk 1]
```diff
@@ -812,57 +812,68 @@ void mergeReleaseRace() throws InterruptedException {
...
+        if (duration == null) {
+            // no backpressure applied
+            return;
+        }
 
-        final Instant end = Instant.now();
-        final Duration duration = Duration.between(start, end);
-
-        final int ms = (int) duration.toMillis();
+        assertEquals(expectedTimeMs, duration.toMillis());
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java:827]: Minor: previously there was a small range of values allowed and now we're expecting a precise match here. I think this may introduce a degree of flakiness, now or in the future when the tests run on a different hardware. I'd still allow a range here. The comment applies to a test below as well.

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java:827]: No, it can't introduce any flakiness because these numbers are strictly deterministic. This was the whole point of the refactoring.

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java:827]: Sounds good.
