### PR TITLE
fix: Reconnect process should wait until the gossip is fully paused before clearing the system state

### LINKED ISSUE #22363: Broken Intake counter in reported in OrphanBuffer
```
2025-11-28 16:51:59.908 4499     INFO  RECONNECT        <<platform-core: reconnectController>> ReconnectController: A state was obtained from a peer
2025-11-28 16:51:59.911 4500     INFO  RECONNECT        <<platform-core: reconnectController>> ReconnectController: The state obtained from a peer was validated
2025-11-28 16:52:01.488 4506     INFO  STATE_TO_DISK    <<platform-core: reconnectController>> DefaultSavedStateController: Signed state from round 535765 created, will eventually be written to disk, for reason: RECONNECT
2025-11-28 16:52:01.489 4507     INFO  PLATFORM_STATUS  <platformForkJoinThread-4> StatusStateMachine: Platform spent 6.6 m in BEHIND. Now in RECONNECT_COMPLETE {"oldStatus":"BEHIND","newStatus":"RECONNECT_COMPLETE"} [com.swirlds.logging.legacy.payload.PlatformStatusPayload]
2025-11-28 16:52:01.489 4509     INFO  STARTUP          <platformForkJoinThread-3> Shadowgraph: Shadowgraph starting from expiration threshold 535738
2025-11-28 16:52:01.493 4512     INFO  STATE_TO_DISK    <<scheduler StateSnapshotManager>> SignedStateFileWriter: Started writing round 535765 state to disk. Reason: RECONNECT, directory: /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.hedera.services.ServicesMain/27/123/535765
2025-11-28 16:52:01.495 4513     INFO  RECONNECT        <<platform-core: reconnectController>> ReconnectController: Reconnect almost done resuming gossip
2025-11-28 16:52:01.496 4514     INFO  STARTUP          <platformForkJoinThread-6> PcesFileManager: Due to recent operations on this node, the local preconsensus event stream will have a discontinuity. The last file with the old origin round is 2025-11-28T16+45+26.415161339Z_seq31200_minr534738_maxr534762_orgn534765.pces. All future files will have an origin round of 535765.
2025-11-28 16:52:01.503 4515     INFO  STATE_TO_DISK    <<scheduler StateSnapshotManager>> MerkleTreeSnapshotWriter: Creating a snapshot on demand in /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/swirlds-tmp/12 for round 535765
2025-11-28 16:52:01.556 4520     ERROR EXCEPTION        <platformForkJoinThread-8> DefaultUncaughtExceptionHandler: Uncaught exception in OrphanBuffer
java.lang.IllegalStateException: Event processed from peer, but no events from that peer were in the intake pipeline. This shouldn't be possible.
	at com.swirlds.platform.gossip.DefaultIntakeEventCounter.lambda$static$0(DefaultIntakeEventCounter.java:29)
	at java.base/java.util.concurrent.atomic.AtomicInteger.getAndUpdate(AtomicInteger.java:259)
	at com.swirlds.platform.gossip.DefaultIntakeEventCounter.eventExitedIntakePipeline(DefaultIntakeEventCounter.java:81)
	at com.swirlds.platform.event.orphan.DefaultOrphanBuffer.eventIsNotAnOrphan(DefaultOrphanBuffer.java:213)
	at com.swirlds.platform.event.orphan.DefaultOrphanBuffer.missingParentBecameAncient(DefaultOrphanBuffer.java:161)
	at com.swirlds.platform.event.orphan.DefaultOrphanBuffer.lambda$setEventWindow$2(DefaultOrphanBuffer.java:138)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at com.swirlds.platform.event.orphan.DefaultOrphanBuffer.setEventWindow(DefaultOrphanBuffer.java:137)
	at com.swirlds.component.framework.component.ComponentWiring.lambda$bind$7(ComponentWiring.java:634)
	at com.swirlds.component.framework.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:96)
	at com.swirlds.component.framework.schedulers.internal.SequentialTask.onExecute(SequentialTask.java:77)
	at org.hiero.base.concurrent.AbstractTask.exec(AbstractTask.java:68)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2025-11-28 16:52:02.683 4521     INFO  STARTUP          <<scheduler ConsensusEngine>> ConsensusImpl: Found init judge (CR:26 H:b908e25fb292 BR:535763), num remaining: 22
2025-11-28 16:52:02.683 4522     INFO  STARTUP          <<scheduler ConsensusEngine>> ConsensusImpl: Found init judge (CR:7 H:080d1c662c74 BR:535763), num remaining: 21
2025-11-28 16:52:02.683 4523     INFO  STARTUP          <<scheduler ConsensusEngine>> ConsensusImpl: Found init judge (CR:19 H:1f236150197c BR:535763), num remaining: 20
2025-11-28 16:52:02.683 4524     INFO  STARTUP          <<scheduler ConsensusEngine>> ConsensusImpl: Found init judge (CR:12 H:94a453ad8ca4 BR:535763), num remaining: 19
```

### PR DESCRIPTION
**Pull request by abies**
**Description**:
Reconnect needs to wait for all sync processes to fully pause before clearing the state and requesting further processing. Currently, it doesn't, which can lead to race condition, where some long running sync is still pushing events against already cleared orphan buffers/consensus/etc

**Related issue(s)**:

Fixes #22363 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java [hunk 1]
```diff
@@ -46,6 +47,7 @@ public class FallenBehindMonitor {
 
     private final double fallenBehindThreshold;
     private boolean isBehind;
+    private boolean pausedNotification;
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java]: nit: I don't think it's required, but making this variable `volatile` will be a clear indicator to readers that it is used by multiple threads.

Comment (poulok) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java]: A better name for a `boolean` variable would be `pausedNotificationReceived`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java [hunk 2]
```diff
@@ -203,4 +205,36 @@ public FallenBehindStatus check(
         }
         return status;
     }
+
+    /**
+     * Inform thread listening on {@link #awaitGossipPaused()} that gossip was already fully paused. Supports notifying
+     * only a single thread, but can be executed before, after or concurrently with the await call.
+     */
+    public void notifySyncProtocolPaused() {
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java:219]: I would like to see a unit test for the interaction of these two methods.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java (hunk 1 above)
Comment (abies) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java]: Volatile would be bit misleading, as they are protected by locks and don't require implicit barriers. I'll add `@GuardedBy` annotation to show the multithreaded behaviour.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java (hunk 2 above)
Comment (abies) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/FallenBehindMonitor.java:219]: Added unit test for that. For some reason I haven't found the test class for FallenBehindMonitor before.

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/FallenBehindMonitorTest.java [hunk 3]
```diff
@@ -522,4 +522,44 @@ void testReportedSizeAccuracy() {
...
+    void testGossipPausedNotificationReverseOrder() throws InterruptedException {
+        final CountDownLatch allCompleted = new CountDownLatch(1);
+
+        monitor.notifySyncProtocolPaused();
+
+        new Thread(() -> {
+                    try {
+                        monitor.awaitGossipPaused();
+                        allCompleted.countDown();
+                    } catch (InterruptedException e) {
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/FallenBehindMonitorTest.java:557]: nit: `final`

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/FallenBehindMonitorTest.java [hunk 4]
```diff
@@ -522,4 +522,44 @@ void testReportedSizeAccuracy() {
...
+    void testGossipPausedNotificationNormalOrder() throws InterruptedException {
+        final CountDownLatch allStarted = new CountDownLatch(1);
+        final CountDownLatch allCompleted = new CountDownLatch(1);
+
+        new Thread(() -> {
+                    try {
+                        allStarted.countDown();
+                        monitor.awaitGossipPaused();
+                        allCompleted.countDown();
+                    } catch (InterruptedException e) {
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/FallenBehindMonitorTest.java:536]: nit: `final`
