### PR TITLE
chore: Fix connections

### LINKED ISSUE #22441: Modifications of individual connections is broken
The methods that modify the state of individual connections do not call `updateConnections()`.

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

This PR fixes two bugs in individual connections and adds integration tests which ensure we actually disconnect and connect nodes.

**Related issue(s)**:

Fixes #22441

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java [hunk 1]
```diff
@@ -0,0 +1,426 @@
...
+                assertThat(conn0to1.isConnected()).isFalse();
+                assertThat(conn0to2.isConnected()).isFalse();
+                assertThat(conn0to3.isConnected()).isFalse();
+                assertThat(conn1to0.isConnected()).isFalse();
+                assertThat(conn2to0.isConnected()).isFalse();
+                assertThat(conn3to0.isConnected()).isFalse();
+
+                // Wait for node0 to detect the disconnection and enter CHECKING status
+                timeManager.waitForCondition(
+                        () -> node0.platformStatus() == CHECKING,
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java]: nit: you can use `node0.isChecking()` here

File: platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java [hunk 2]
```diff
@@ -0,0 +1,426 @@
...
+                        Duration.ofSeconds(120L),
+                        "Node0 did not enter CHECKING status after disconnecting all connections (cycle " + cycle
+                                + ")");
+
+                // Verify other nodes remain ACTIVE (they can still communicate with each other)
+                timeManager.waitFor(Duration.ofSeconds(5));
+                assertThat(node1.platformStatus())
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java:133]: nit: you could use `assertTrue(node1.isActive())` here

File: platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java (hunk 1 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java]: Fixed

File: platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java (hunk 2 above)
Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/testIntegration/java/org/hiero/otter/fixtures/test/ConnectionTest.java:133]: I prefer AssertJ as it provides better error messages. 😄
