### PR TITLE
fix: fixed diff test issue 11522

### LINKED ISSUE #11522: Replay events from round 162309838 and validate record files for differential testing - 5 min
Replay events from round 162309838 and validate record files for differential testing - 5 min

Found 4 diffs below:

---- CryptoTransfer DIFFERED (TRANSACTION_RECORD_MISMATCH) ----
Mismatched field counts  (expected but not find [tokenTransferLists]) between expected receipt {

---- TokenDissociateFromAccount DIFFERED (TRANSACTION_RECORD_MISMATCH) ----
Mismatched values, expected 'SUCCESS', got 'TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES' - Matching field 'status' Matching field 'receipt'  ==> expected: <SUCCESS> but was: <TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES>

--- TokenMint DIFFERED (TRANSACTION_RECORD_MISMATCH) ----
Transaction fees '25478444' and '24734311' varied by more than 1 tinybar - Matching field 'transactionFee'  ==> expected: <true> but was: <false>

DIFFERED (TRANSACTION_RECORD_MISMATCH) ----
Mismatched field counts  (expected but not find [signer_nonce]) between expected errorMessage: "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b556e69737761705632526f757465723a20494e53554646494349454e545f4f55545055545f414d4f554e54000000000000000000000000000000000000000000"
gasUsed: 1600000
gas: 2000000
functionParameters: "\030\313\257\345\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000#+\225\375\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\250X~\340F\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\240\000\000\000\000\000\000\000\000\000\000\000\000\\Ch\367(\3344\216\361\2649hC\3741\001\207\a\202\316\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\215\241\226\'B\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\370\232\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\026;Z"
sender_id {
  accountNum: 3865438
}
signer_nonce {
  value: 731
}
 and errorMessage: "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b556e69737761705632526f757465723a20494e53554646494349454e545f4f55545055545f414d4f554e54000000000000000000000000000000000000000000"
gasUsed: 1600000
gas: 2000000
functionParameters: "\030\313\257\345\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000#+\225\375\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\250X~\340F\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\240\000\000\000\000\000\000\000\000\000\000\000\000\\Ch\367(\3344\216\361\2649hC\3741\001\207\a\202\316\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\215\241\226\'B\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\370\232\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\026;Z"
sender_id {
  accountNum: 3865438
}
Matching field 'contractCallResult'

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**: fixed CustomFractionalFeeAssessor.filteredByExemptions() to return correct value.

**Related issue(s)**:

Fixes #11522 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java [hunk 1]
```diff
@@ -112,10 +112,10 @@ public class MerkleHederaState extends PartialNaryMerkleInternal implements Merk
      */
     private static final long DO_NOT_USE_IN_REAL_LIFE_CLASS_ID = 0x0000deadbeef0000L;
 
-    private static final long CLASS_ID = 0x2de3ead3caf06392L;
+    //    private static final long CLASS_ID = 0x2de3ead3caf06392L;
     // Uncomment the following class ID to run a mono -> modular state migration
     // NOTE: also change class ID of ServicesState
-    //    private static final long CLASS_ID = 0x8e300b0dfdafbb1aL;
+    private static final long CLASS_ID = 0x8e300b0dfdafbb1aL;
```
Comment (povolev15) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java:118]: I don't think taht file need to be commited

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java [hunk 2]
```diff
@@ -115,10 +115,10 @@ public class ServicesState extends PartialNaryMerkleInternal
         implements MerkleInternal, SwirldState, StateChildrenProvider {
     private static final Logger log = LogManager.getLogger(ServicesState.class);
 
-    private static final long RUNTIME_CONSTRUCTABLE_ID = 0x8e300b0dfdafbb1aL;
+    //    private static final long RUNTIME_CONSTRUCTABLE_ID = 0x8e300b0dfdafbb1aL;
     // Uncomment the following class ID to run a mono -> modular state migration
     // NOTE: also change class ID of MerkleHederaState
-    //    private static final long RUNTIME_CONSTRUCTABLE_ID = 0x8e300b0dfdafbb1bL;
+    private static final long RUNTIME_CONSTRUCTABLE_ID = 0x8e300b0dfdafbb1bL;
```
Comment (povolev15) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java:121]: same

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java:118]: This won't matter.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java (hunk 2 above)
Comment (iwsimon) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java:121]: same

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java:118]: Why won't it matter? Seems like this will create duplicate class ids.

Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java]: Reverted to original class_id.

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Review by povolev15 — APPROVED** [review]
