### PR TITLE
fix: Implement new PCES writer flush

### LINKED ISSUE #10887: `MixedOps-NI-3NReconnect-2k-30m` JRS failure
- [data](http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20240110-063758-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-NI-3NReconnect-2k-30m/)

- All nodes simply move to `CHECKING`, and nothing happens

### LINKED ISSUE #10930: Fix PcesWriter flushing bug
### Problem

- In the PCES migration, I fumbled how keystone events are flushed.
- This can lead to a deadlock, where transaction handling is waiting on a keystone event to become durable, but the event writer doesn't have any reason to flush the event

### Scope

- This bug exists only in `develop`, having been merged on 1/8/24 https://github.com/hashgraph/hedera-services/pull/10795

### Solution

- The `LinkedEventIntake` should have a secondary output wire, to get the sequence number of the keystone event for each round.
- Data will be pushed onto the secondary wire prior to trying to add rounds to handle to the consensus round handler
    - this prevents a full queue on the consensus round handler from preventing the latest keystone event sequence number from being pushed out
- That keystone event sequence number output will be wired into a `PcesWriter` `flushEvent` input wire, so that the keystone event of each and every round receives a flush request, and cannot hang the system

### Related

- this bug is the root of https://github.com/hashgraph/hedera-services/issues/10887
- https://github.com/hashgraph/hedera-services/issues/10927

### PR DESCRIPTION
**Pull request by alittley**
- closes #10930 
- closes #10887 
- [diagram](https://mermaid.ink/svg/Zmxvd2NoYXJ0IExSCnYwKCgiQCIpKQpzdWJncmFwaCB2MVsiQ29uc2Vuc3VzIFBpcGVsaW5lIl0Kc3ViZ3JhcGggdjJbIkxpbmtlZCBFdmVudCBJbnRha2UiXQp2M3t7ImdldE5vbkFuY2llbnRFdmVudFdpbmRvdyJ9fQp2NFsibGlua2VkRXZlbnRJbnRha2U8YnIgLz7imIUiXQp2NXt7ImxpbmtlZEV2ZW50SW50YWtlU3BsaXR0ZXIifX0KZW5kCnY2WyJpbk9yZGVyTGlua2VyPGJyIC8+ypgiXQplbmQKc3ViZ3JhcGggdjdbIkludGFrZSBQaXBlbGluZSJdCnN1YmdyYXBoIHY4WyJFdmVudCBWYWxpZGF0aW9uIl0KdjlbImV2ZW50RGVkdXBsaWNhdG9yPGJyIC8+ypgiXQp2MTBbImV2ZW50U2lnbmF0dXJlVmFsaWRhdG9yPGJyIC8+ypgiXQp2MTFbImludGVybmFsRXZlbnRWYWxpZGF0b3I8YnIgLz7igKAiXQplbmQKc3ViZ3JhcGggdjEyWyJPcnBoYW4gQnVmZmVyIl0KdjEzWyJvcnBoYW5CdWZmZXI8YnIgLz7KmCJdCnYxNHt7Im9ycGhhbkJ1ZmZlclNwbGl0dGVyIn19CmVuZAp2MTVbLyJldmVudEhhc2hlciIvXQplbmQKc3ViZ3JhcGggdjE2WyJQcmVjb25zZW5zdXMgRXZlbnQgU3RyZWFtIl0KdjE3Wy8iZXZlbnREdXJhYmlsaXR5TmV4dXMiL10KdjE4Wy8icGNlc1NlcXVlbmNlciIvXQp2MTlbInBjZXNXcml0ZXI8YnIgLz5AypgiXQplbmQKc3ViZ3JhcGggdjIwWyJTdGF0ZSBGaWxlIE1hbmFnZW1lbnQiXQp2MjF7eyJleHRyYWN0T2xkZXN0TWluaW11bUdlbmVyYXRpb25PbkRpc2sifX0KdjIyWyJzaWduZWRTdGF0ZUZpbGVNYW5hZ2VyIl0KdjIze3sidG9TdGF0ZVdyaXR0ZW5Ub0Rpc2tBY3Rpb24ifX0KZW5kCnN1YmdyYXBoIHYyNFsiU3RhdGUgU2lnbmF0dXJlIENvbGxlY3Rpb24iXQp2MjVbInN0YXRlU2lnbmF0dXJlQ29sbGVjdG9yIl0KdjI2e3sic3RhdGVTaWduYXR1cmVUcmFuc2FjdGlvbnNGaWx0ZXIifX0KdjI3e3sic3lzdGVtVHJhbnNhY3Rpb25zRmlsdGVyIn19CnYyOHt7InN5c3RlbVRyYW5zYWN0aW9uc1NwbGl0dGVyIn19CmVuZAp2MjlbWyJhcHBsaWNhdGlvblRyYW5zYWN0aW9uUHJlaGFuZGxlciJdXQp2MzBbImV2ZW50Q3JlYXRpb25NYW5hZ2VyPGJyIC8+ypjimaEiXQp2MzFbImhlYXJ0YmVhdCJdCnYzMlsvInBjZXNSZXBsYXllciIvXQp2MzNbInN0YXRlU2lnbmVyIl0KdjM0KCgiypgiKSkKdjM1KCgi4oCgIikpCnYzNigoIuKYhSIpKQp2MzcoKCLimaEiKSkKdjI5IC0uICJmdXR1cmVzIiAuLW8gdjM2CnYzMCAtLiAibm9uLXZhbGlkYXRlZCBldmVudHMiIC4tPiB2MzUKdjkgLS0gImV2ZW50cyB3aXRoIHVudmFsaWRhdGVkIHNpZ25hdHVyZXMiIC0tPiB2MTAKdjE1IC0tICJub24tdmFsaWRhdGVkIGV2ZW50cyIgLS0+IHYxMQp2MTAgLS0gInVub3JkZXJlZCBldmVudHMiIC0tPiB2MTMKdjIxIC0tICJtaW5pbXVtIGlkZW50aWZpZXIgdG8gc3RvcmUiIC0tPiB2MTkKdjMgLS4gIm5vbi1hbmNpZW50IGV2ZW50IHdpbmRvdyIgLi0+IHYzNAp2MzEgLS0gImhlYXJ0YmVhdCIgLS0+IHYzNwp2NiAtLSAibGlua2VkIGV2ZW50cyIgLS0+IHY0CnYxMSAtLSAibm9uLWRlZHVwbGljYXRlZCBldmVudHMiIC0tPiB2OQp2NCAtLSAicm91bmQgbGlzdHMiIC0tPiB2NQp2NCAtLSAiZmx1c2ggcmVxdWVzdCIgLS0+IHYxOQp2NSAtLSAicm91bmRzIiAtLT4gdjMKdjEzIC0tICJldmVudCBsaXN0cyIgLS0+IHYxNAp2MTQgLS0gInByZWNvbnNlbnN1cyBldmVudHMiIC0tPiB2MjkKdjE0IC0tICJwb3NzaWJsZSBwYXJlbnRzIiAtLT4gdjMwCnYxNCAtLSAiZXZlbnRzIHRvIHNlcXVlbmNlIiAtLT4gdjE4CnYxNCAtLSAicHJlY29uc2Vuc3VzIGV2ZW50cyIgLS0+IHYyNwp2MzIgLS0gImRvbmUgc3RyZWFtaW5nIHBjZXMiIC0tPiB2MAp2MzIgLS0gImV2ZW50cyB0byBoYXNoIiAtLT4gdjE1CnYxOCAtLSAidW5saW5rZWQgZXZlbnRzIiAtLT4gdjYKdjE4IC0tICJldmVudHMgdG8gd3JpdGUiIC0tPiB2MTkKdjE5IC0tICJsYXRlc3QgZHVyYWJsZSBzZXF1ZW5jZSBudW1iZXIiIC0tPiB2MTcKdjIyIC0tICJzdGF0ZSBzYXZpbmcgcmVzdWx0IiAtLT4gdjIxCnYyMiAtLSAic3RhdGUgc2F2aW5nIHJlc3VsdCIgLS0+IHYyMwp2MjYgLS0gInN0YXRlIHNpZ25hdHVyZSB0cmFuc2FjdGlvbnMiIC0tPiB2MjUKdjI3IC0tICJzeXN0ZW0gdHJhbnNhY3Rpb24gbGlzdHMiIC0tPiB2MjgKdjI4IC0tICJzeXN0ZW0gdHJhbnNhY3Rpb25zIiAtLT4gdjI2CmNsYXNzRGVmIHMwIGZpbGw6I2Y4OCxzdHJva2U6IzAwMCxzdHJva2Utd2lkdGg6MnB4CmNsYXNzIHYwLHYzNCx2MzUsdjM2LHYzNyBzMApjbGFzc0RlZiBzMSBmaWxsOiM5Q0Ysc3Ryb2tlOiMwMDAsc3Ryb2tlLXdpZHRoOjJweApjbGFzcyB2MSx2MTYsdjIwLHYyNCx2NyBzMQpjbGFzc0RlZiBzMiBmaWxsOiNCRUYsc3Ryb2tlOiMwMDAsc3Ryb2tlLXdpZHRoOjJweApjbGFzcyB2MTIsdjIsdjggczIKY2xhc3NEZWYgczMgZmlsbDojY2NjLHN0cm9rZTojMDAwLHN0cm9rZS13aWR0aDoycHgKY2xhc3MgdjE0LHYxNSx2MTcsdjE4LHYyMSx2MjMsdjI2LHYyNyx2MjgsdjMsdjMyLHY1IHMzCmNsYXNzRGVmIHM0IGZpbGw6I2ZmOSxzdHJva2U6IzAwMCxzdHJva2Utd2lkdGg6MnB4CmNsYXNzIHYxMCx2MTEsdjEzLHYxOSx2MjIsdjI1LHYyOSx2MzAsdjMxLHYzMyx2NCx2Nix2OSBzNAo=?bgColor=e8e8e8)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java [hunk 1]
```diff
@@ -176,6 +188,32 @@ public void beginStreamingNewEvents(final @NonNull DoneStreamingPcesTrigger igno
...
+                flushRequired = true;
+            }
+        }
+
+        if (flushRequired) {
+            if (currentMutableFile == null) {
+                logger.error(EXCEPTION.getMarker(), "Flush required, but no file is open. This should never happen");
+            }
+
+            closeFile();
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java:211]: We don't need to close the file when we flush, just call the flush method on the stream object. As is, this will cause us to write one PCES file per round, which is not desirable.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java [hunk 2]
```diff
@@ -221,56 +265,46 @@ public Long registerDiscontinuity(final long newOriginRound) {
...
+     * @return the sequence number of the last event durably written to the stream, or null if this method call didn't
+     * result in any additional events being durably written to the stream
      */
-    private static void validateSequenceNumber(@NonNull final GossipEvent event) {
-        if (event.getStreamSequenceNumber() == GossipEvent.NO_STREAM_SEQUENCE_NUMBER
-                || event.getStreamSequenceNumber() == GossipEvent.STALE_EVENT_STREAM_SEQUENCE_NUMBER) {
-            throw new IllegalStateException("Event must have a valid stream sequence number");
-        }
+    @Nullable
+    public Long submitFlushRequest(final long sequenceNumber) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java:289]: What is this return value used for?

Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java:289]: If submission of the flush request immediately results in an event becoming durable, this return value will pass that along to the durability nexus

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java (hunk 1 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PcesWriter.java]: Fixed

**Review by cody-littley — DISMISSED** [review]

**Review by cody-littley — APPROVED** [review]
