### PR TITLE
fix: Support zero-weight nodes in sync lag calculation

### LINKED ISSUE #22292: `SyncLagCalculator` does not support some weight distributions
The `SyncLagCalculator.getSyncRoundLag()` method does not work properly for networks in which a single node has all the network weight (i.e. all other nodes have zero weight). The results of the method call is `NaN` which causes the `SyncLagRule.isEventCreationPermitted()` to always evaluate to `false`, preventing the node from creating events.

### PR DESCRIPTION
**Pull request by abies**
**Description**:

Sync lag calculation had special support for single-node networks, where the roster had only a single entry. Unfortunately, it was failing in case there were multiple nodes, but only one of them had a non-zero weight. This PR fixes this special case.

**Related issue(s)**:

Fixes #22292 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java [hunk 1]
```diff
@@ -108,4 +112,53 @@ public void missingNodesAssumedToBeZero() {
...
+        assertEquals(0, slc.getSyncRoundLag());
+    }
+
+    @ParameterizedTest
+    @ValueSource(ints = {1, 2, 3, 4, 5, 6, 7, 8, 9})
+    public void singleNodeNetworkUselessNode(final int zeroWeightNodeCount) {
+
+        rosterBuilder.withSize(zeroWeightNodeCount + 1);
+        rosterBuilder.withWeightGenerator((seed, numberOfNodes) -> {
+            final Long[] weights = new Long[numberOfNodes];
```
Comment (poulok) [inline platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java]: Why not add this to the weight generators available to other tests? It could be useful other places as well.

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java [hunk 2]
```diff
@@ -108,4 +112,53 @@ public void missingNodesAssumedToBeZero() {
...
+            weights[0] = Math.max(100, seed);
+            for (int i = 1; i < numberOfNodes; i++) {
+                weights[i] = 0L;
+            }
+            return Arrays.asList(weights);
+        });
+        final var roster = rosterBuilder.build();
```
Comment (poulok) [inline platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:133]: Have I mentioned how much I dislike the use of `var`? 😁

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java [hunk 3]
```diff
@@ -108,4 +112,53 @@ public void missingNodesAssumedToBeZero() {
...
+        final var selfNodeId = NodeId.of(roster.rosterEntries()
```
Comment (poulok) [inline platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:134]: Don't you want to test the sync lag calculator for the weighted node? That way the weight of all other nodes will always be zero.

File: platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculator.java [hunk 4]
```diff
@@ -87,7 +87,7 @@ public void reportSyncLag(final NodeId nodeId, final long diff) {
     public double getSyncRoundLag() {
         final var lagArray = consensusLag.values().toArray(WeightAndLag[]::new);
         double medianLag;
-        if (lagArray.length > 0) {
+        if (totalWeight > 0) {
```
Comment (poulok) [inline platform-sdk/consensus-event-creator-impl/src/main/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculator.java]: This is not really total weight. It is the weight of all other nodes in the network.

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java (hunk 3 above)
Comment (abies) [reply platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:134]: The weighted node is tested inside `singleNodeNetworkRealNode`. This test is for the zero weight nodes.

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java (hunk 1 above)
Comment (abies) [reply platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java]: Added.

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java (hunk 2 above)
Comment (abies) [reply platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:133]: It is just easier in unit tests

Comment (poulok) [reply platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:133]: Yes, but it is harder for reviewers to read, and reviewers almost never pay as much attention to unit tests as they do production code. We should make unit tests as easy to understand and read as possible.

But anyways, I will get off my soapbox now.

File: platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java [hunk 5]
```diff
@@ -108,4 +112,39 @@ public void missingNodesAssumedToBeZero() {
 
         assertEquals(0, slc.getSyncRoundLag());
     }
+
+    @ParameterizedTest
+    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9})
+    public void singleNodeNetworkRealNode(final int zeroWeightNodeCount) {
```
Comment (poulok) [inline platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:118]: nit: This test name, and the one below, are misleading. They are mostly not single node networks, but multi-node networks where only a single node has any weight. Those are different things.

This does not need to be fixed in this PR, but it would be nice to update at some point.

Comment (abies) [reply platform-sdk/consensus-event-creator-impl/src/test/java/org/hiero/consensus/event/creator/impl/rules/SyncLagCalculatorTests.java:118]: Ok, will update it next time we touch the sync lag (which might be soon, due to all the other activity around event creation).
