### PR TITLE
01810: Support custom fixed fees token to be created/updated

### LINKED ISSUE #1810: Support custom fixed fees that use the token to be created
On token creation, there isn't yet a token ID to refer to in the custom fixed fee.

### PR DESCRIPTION
**Pull request by qnswirlds**
**Related issue(s)**:

Close #1810

**Notes for reviewer**:
- Used sentinel tokenId with tokenNum == 0
- Added CustomFeeBuilder to simplify test codes and remove lots of duplications
- Simplify TokenFeeScheduleUpdateTransitionLogic and its unit tests

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java [hunk 1]
```diff
@@ -148,15 +148,17 @@ private ResponseCodeEnum autoEnableFeeCollectors(
...
-				final var collector = fee.getFeeCollectorAccountId();
-				if (!customCollectorsEnabled.contains(collector)) {
-					status = autoEnableAccountForNewToken(collector, created, op);
-					if (status != OK) {
-						return status;
-					}
-					customCollectorsEnabled.add(collector);
+			boolean collectorEnablementNeeded = fee.hasFractionalFee();
+			if (fee.hasFixedFee() && fee.getFixedFee().hasDenominatingTokenId()) {
+				collectorEnablementNeeded |= (0 == fee.getFixedFee().getDenominatingTokenId().getTokenNum());
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java:153]: Nice 😁

**Review by tinker-michaelj — APPROVED** [review]
LGTM!!

File: hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java (hunk 1 above)
Comment (qnswirlds) [reply hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java:153]: Thanks! :D
