### PR TITLE
fix: Fix flaky `StopWatchTest`

### LINKED ISSUE #23456: Test Flake: StopWatchTest
https://scans.gradle.com/s/m4wa6dwr3tnca/tests/task/:swirlds-common:test/details/com.swirlds.common.utility.StopWatchTest/multipleRuns()?expanded-stacktrace=WyIwIl0&top-execution=1

### PR DESCRIPTION
**Pull request by poulok**
Fixes #23456

### CODE REVIEW

File: platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/StopWatchTest.java [hunk 1]
```diff
@@ -78,23 +81,27 @@ void reset() throws InterruptedException {
 
         stopWatch.start();
         assertTrue(stopWatch.isRunning());
-        Thread.sleep(50);
+        fakeTime.tick(Duration.ofMillis(60)); // Simulate 50ms passing
```
Comment (timo0) [inline platform-sdk/swirlds-common/src/test/java/com/swirlds/common/utility/StopWatchTest.java]:
```suggestion
        fakeTime.tick(Duration.ofMillis(60)); // Simulate 60ms passing
```
