### PR TITLE
feat: 22703 fix failed invalid

### LINKED ISSUE #22703: EIP-7702: Investigate FAILED_INVALID
Executing tests that attempt to send authorization lists are returning a FAILED_INVALID.  Investigate the cause.

### PR DESCRIPTION
**Pull request by lukelee-sl**
**Description**:
- Fix were several parsing related issues that was causing the FAILED_INVALID.
- Handle potential `IllegalArgumentException` exceptions possible when parsing via `EthTxData` and convert to `HandleExceptions` to get rid of the possible future `FailedInvalid`
- Remove `IndependentChildDispatch` options.  Replace dispatches for code delegations to use regular `stepDispatch`
- Create a child `ProxyWorldUpdater` to handle state changes and record stream production for code delegations which is separate from the normal EVM transaction changes.

**Related issue(s)**:

Fixes #22703

### CODE REVIEW

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/CodeDelegation.java [hunk 1]
```diff
@@ -44,7 +43,7 @@ public long getChainId() {
     public byte[] calculateSignableMessage() {
         // Use Long.toBytes for canonical RLP encoding (nonce=0 -> empty byte array, not 8 zeros)
         // Use RLPEncoder.list() to wrap in a proper RLP list (not sequence which just concatenates)
-        final var nonceBytes = Longs.toByteArray(nonce);
+        final var nonceBytes = Bytes.minimalBytes(nonce).toArray();
```
Comment (lukasz-hashgraph) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/CodeDelegation.java:47]: Is that different from: `final var rlpEncoded = RLPEncoder.list(chainId, address, nonce)`? Also the comment above needs to be updated.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java [hunk 2]
```diff
@@ -466,29 +466,22 @@ public List<CodeDelegation> extractCodeDelegations() throws IllegalArgumentExcep
...
                 }
-
                 codeDelegations.add(new CodeDelegation(
-                        rlpInnerList.get(0).data(), // chainId)
-                        rlpInnerList.get(1).data(), // address
-                        asLong(rlpInnerList.get(2)), // nonce
-                        asByte(rlpInnerList.get(3)), // yParity
-                        rlpInnerList.get(4).data(), // r
-                        rlpInnerList.get(5).data() // s
+                        rlpItem.asRLPList().elements().get(0).data(), // chainId)
```
Comment (lukasz-hashgraph) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java]: Looks like calling `elements()` is decoding the list every time. Perhaps better to call it once and store the result in a variable?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java [hunk 3]
```diff
@@ -86,10 +93,6 @@ private void setAccountCodeToDelegationIndicator(
             return;
         }
 
-        if (codeDelegation.getR().compareTo(HALF_CURVE_ORDER) > 0) {
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java:89]: why are we removing this check?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java [hunk 4]
```diff
@@ -139,9 +142,8 @@ private void setAccountCodeToDelegationIndicator(
                 return;
             }
 
-            if (!((ProxyWorldUpdater) worldUpdater)
-                    .setAccountCodeDelegationIndicator(
-                            ((HederaEvmAccount) authority).hederaId(), delegatedContractAddress)) {
+            if (!proxyWorldUpdater.setAccountCodeDelegationIndicator(
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java]: There were some unresolved comments left on https://github.com/hiero-ledger/hiero-consensus-node/pull/22429 - one of them was to rename `setAccountCodeToDelegationIndicator` (we're no longer setting the code). Perhaps this PR is a good opportunity to address that?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java [hunk 5]
```diff
@@ -166,12 +166,12 @@ public void setNonce(final long contractNumber, final long nonce) {
     private static DispatchOptions<CryptoCreateStreamBuilder> dispatchOptionsOf(
             final boolean hasDelegationAddress, @NonNull final AccountID payerId, @NonNull final TransactionBody body) {
         if (hasDelegationAddress) {
-            return independentChildDispatch(payerId, body, CryptoCreateStreamBuilder.class);
+            return stepDispatch(
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java:169]: The doc on `stepDispatch` says:

> Returns options for a dispatch that is a step in the parent dispatch's business logic, but only appropriate to externalize if the parent succeeds.

I don't think that matches our goal of externalizing the changes even if the main transaction reverts at the time of EVM execution. Am I missing something?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java (hunk 3 above)
Comment (lukelee-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java:89]: the signature from Luis's test (produced by hardhat) failed with this check and the check does not exist in Besu?  It seems that limiting to the upper half only applies to the S value.  I did not research this more.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java (hunk 5 above)
Comment (lukelee-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java:169]: We are creating a new and separate `SavepointStack`  to save the state changes/records for all code delegations and then committing at the end of processing.  Because this `SavepointStack` is distinct from the one created for normal evm transaction processing, using this method of dispatch should be fine.  Also, child record creation is distinct from state changes.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java (hunk 4 above)
Comment (lukelee-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java]: I think I got all three naming changes mentioned in the other pr.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/CodeDelegation.java (hunk 1 above)
Comment (lukelee-sl) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/CodeDelegation.java:47]: Yes, I was getting the wrong address because the leading zeros were not truncated.  I compared the results from the client to validate this.  

Updated the comments.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java (hunk 3 above)
Comment (lukasz-hashgraph) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java:89]: Ah, right. It's just the `s` value that's restricted, as per [EIP-2](https://eips.ethereum.org/EIPS/eip-2).

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java (hunk 4 above)
Comment (lukasz-hashgraph) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/delegation/CodeDelegationProcessor.java]: Thank you 👍

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java (hunk 5 above)
Comment (lukasz-hashgraph) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java:169]: Gotcha, thx 👍
