### PR TITLE
06968 Integrate PlatformStatusStateMachine

### LINKED ISSUE #5161: Node on Reconnect should skip becoming ACTIVE if it is BEHIND
The current sequence of status changes when a node disconnects and reconnects is as follows:
1.  DISCONNECTED
2. ACTIVE
3. BEHIND
4. ACTIVE

Even though 2 to 3 is fast, sometimes a test-clients probes the status of the node right in the middle of the status transition and thinks that the node is ready to receive requests (transactions/queries). And then when it sends the requests, the node is unavailable due to falling behind.

The suggested sequence of status changes is as follows:
1.  DISCONNECTED
2. BEHIND
3. ACTIVE (after a successful synchronization with other nodes)

or
1.  DISCONNECTED
2. ACTIVE (when the node is still up-to-date and no synchronization is needed)

Some notes from @lbaird:
- It should sync with nodes that (together with itself) have a supermajority of stake, before it sets status to active.
- That should happen for both reconnect and restart. In both cases, we want to make sure we know all the latest events before we start creating new events.
- To be clear, it shouldn’t even create new events until after syncing with the more-than-two-thirds-stake nodes (including itself).

### LINKED ISSUE #5350: Node becomes ACTIVE when state loading fails
From Tanner:
> When we hit the state load bug in v0.33.0, the network still came ACTIVE after the state load error. The network returns UNKNOWN transaction responses, and never appears to save state. Is it possible to not have the network come ACTIVE at all?

The exception in question:
```
java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "this.networkCtx" is null
	at com.hedera.services.context.MutableStateChildren.networkCtx(MutableStateChildren.java:170) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.StakePeriodManager.estimatedFirstNonRewardableStakePeriod(StakePeriodManager.java:107) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.StakePeriodManager.isEstimatedRewardable(StakePeriodManager.java:113) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.RewardCalculator.estimatePendingRewards(RewardCalculator.java:92) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.StakeStartupHelper.lambda$recomputeQuantities$3(StakeStartupHelper.java:192) ~[?:?]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at com.hedera.services.state.migration.AccountStorageAdapter.forEach(AccountStorageAdapter.java:146) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.StakeStartupHelper.recomputeQuantities(StakeStartupHelper.java:187) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.StakeStartupHelper.lambda$doUpgradeHousekeeping$0(StakeStartupHelper.java:140) ~[?:?]
	at com.hedera.services.utils.MiscUtils.withLoggedDuration(MiscUtils.java:875) ~[?:?]
	at com.hedera.services.ledger.accounts.staking.StakeStartupHelper.doUpgradeHousekeeping(StakeStartupHelper.java:138) ~[?:?]
	at com.hedera.services.ServicesState.internalInit(ServicesState.java:327) ~[?:?]
	at com.hedera.services.ServicesState.deserializedInit(ServicesState.java:248) ~[?:?]
	at com.hedera.services.ServicesState.init(ServicesState.java:196) ~[?:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedState(SwirldsPlatform.java:803) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:778) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.SwirldsPlatform.<init>(SwirldsPlatform.java:631) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:507) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:639) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.Browser.<init>(Browser.java:252) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:401) ~[swirlds-platform-core-0.33.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:659) ~[swirlds-platform-core-0.33.0.jar:?]
```

### LINKED ISSUE #5405: Disallow Transaction from Freeze Complete status to Active status
The platform should not be allowed to transition from a `FREEZE_COMPLETE` status to an `ACTIVE` status.

### LINKED ISSUE #6968: Integrate PlatformStatus state machine
Integrate the `PlatformStatus` state machine created in #6297 into the platform, so that the status state machine is traversed based on platform happenings

No action will be taken or decided on based on any state except for the current behavior which rejects transactions if we are not in the `ACTIVE` status

### PR DESCRIPTION
**Pull request by alittley**
- Closes #6968 
- Closes #5405 
- Closes #5161 
- Closes #5350

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java [hunk 1]
```diff
@@ -343,10 +350,15 @@ public class SwirldsPlatform implements Platform, Startable {
...
+        platformStatusStateMachine = components.add(buildPlatformStatusStateMachine(time));
+
         this.metrics = platformContext.getMetrics();
 
         metrics.getOrCreate(StatConstructor.createEnumStat(
-                "PlatformStatus", Metrics.PLATFORM_CATEGORY, PlatformStatus.values(), currentPlatformStatus::get));
+                "PlatformStatus",
+                Metrics.PLATFORM_CATEGORY,
+                PlatformStatus.values(),
+                platformStatusStateMachine::getCurrentStatus));
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:361]: Can this be encapsulated within the state machine class?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java [hunk 2]
```diff
@@ -1101,43 +1138,6 @@ private void configureStartupEventFreeze() {
...
-                setPlatformStatus(PlatformStatus.BEHIND);
-            } else if (freezeManager.isFreezeStarted()) {
-                setPlatformStatus(PlatformStatus.FREEZING);
-            } else if (freezeManager.isFreezeComplete()) {
-                setPlatformStatus(PlatformStatus.FREEZE_COMPLETE);
-            } else {
-                setPlatformStatus(PlatformStatus.ACTIVE);
-            }
-        }
-    }
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:1123]: good riddance

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java [hunk 3]
```diff
@@ -134,7 +133,7 @@ public AppCommunicationComponent wireAppCommunicationComponent(final Notificatio
             @NonNull final HaltRequestedConsumer haltRequestedConsumer,
             @NonNull final AppCommunicationComponent appCommunicationComponent,
             @NonNull final PreconsensusEventWriter preconsensusEventWriter,
-            @NonNull final Supplier<PlatformStatus> getPlatformStatus) {
+            @NonNull final PlatformStatusStateMachine platformStatusStateMachine) {
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java:136]: I wonder if it might simplify dependencies if we created a simple functional interface like this:

```
interface CurrentPlatformStatus {
    PlatformStatus getCurrentStatus();
}
```

We can have the interface `PlatformStatusStateMachine` extend this interface. Then, for classes like this that just need the ability to poll the current status have a much simpler API to interact with.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java [hunk 4]
```diff
@@ -46,8 +46,12 @@ public class FallenBehindManagerImpl implements FallenBehindManager, EventCreati
      * fallen behind. This Set is made from a ConcurrentHashMap, so it needs no synchronization
      */
     private final Set<NodeId> notYetReportFallenBehind;
-    /** Called on any fallen behind status change */
-    private final Runnable notifyPlatform;
+
+    /**
+     * A runnable which announces to the platform that this node has fallen behind
+     */
+    private final Runnable announceFallenBehind;
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java:53]: I wonder if it would be better to pass in a `PlatformStatusStateMachaine`, and just let this class send the appropriate action.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java (hunk 1 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:361]: Unfortunately, doing so creates a circular dependency. I'm assuming the `common` module isn't intended to ever include something from `core`?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java (hunk 3 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java:136]: Done

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java (hunk 4 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java]: Done

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java [hunk 5]
```diff
@@ -171,7 +171,7 @@ static SwirldStateManager swirldStateManager(
             @NonNull final PostConsensusSystemTransactionManager postConsensusSystemTransactionManager,
             @NonNull final Metrics metrics,
             @NonNull final PlatformStatusStateMachine platformStatusStateMachine,
-            @NonNull final SettingsProvider settings,
+            @NonNull final TransactionConfig transactionConfig,
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java:174]: Instead of passing this in as a parameter, could we get it from the context? No need to extract it in this helper method (which I will probably delete soon, it doesn't really serve a purpose), you can get it inside the `SwirldStateManagerImpl`.

Come to think of it, you could also do the same with metrics as well.

For these big objects with a millions parameters, I think it is worth a little extra logic in the constructor if it reduces the number of parameters.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java [hunk 6]
```diff
@@ -35,11 +35,7 @@
 import com.swirlds.logging.payloads.InsufficientSignaturesPayload;
 import com.swirlds.platform.components.common.output.FatalErrorConsumer;
 import com.swirlds.platform.components.common.query.PrioritySystemTransactionSubmitter;
-import com.swirlds.platform.components.state.output.IssConsumer;
-import com.swirlds.platform.components.state.output.NewLatestCompleteStateConsumer;
-import com.swirlds.platform.components.state.output.StateHasEnoughSignaturesConsumer;
-import com.swirlds.platform.components.state.output.StateLacksSignaturesConsumer;
-import com.swirlds.platform.components.state.output.StateToDiskAttemptConsumer;
+import com.swirlds.platform.components.state.output.*;
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java:38]: We explicitly avoid importing using wildcards. It makes for verbose lists of imports, but the fear is that overuse of wildcards will lead to everything importing everything else.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java [hunk 7]
```diff
@@ -55,16 +51,7 @@
...
-import com.swirlds.platform.state.signed.SignedState;
-import com.swirlds.platform.state.signed.SignedStateFileManager;
-import com.swirlds.platform.state.signed.SignedStateGarbageCollector;
-import com.swirlds.platform.state.signed.SignedStateHasher;
-import com.swirlds.platform.state.signed.SignedStateInfo;
-import com.swirlds.platform.state.signed.SignedStateManager;
-import com.swirlds.platform.state.signed.SignedStateMetrics;
-import com.swirlds.platform.state.signed.SignedStateSentinel;
-import com.swirlds.platform.state.signed.SourceOfSignedState;
+import com.swirlds.platform.state.signed.*;
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java:54]: don't use wildcard

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:361]: Hmm... let's not try and solve this in this PR. Your changes didn't cause this problem.

As I slowly make additional changes to clean up `SwirldsPlatform.java`, I will probably just replace this "enum stat" with a basic lambda. Not something you need to do for this PR though.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java (hunk 6 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java:38]: Reformatting did this automatically... does yours not?

File: platform-sdk/docs/core/platform-status.md [hunk 8]
```diff
@@ -1,70 +0,0 @@
-# Platform Status
-
-The platform status is represented as an enum value from `PlatformStatus.java`. It is updated via
```
Comment (poulok) [inline platform-sdk/docs/core/platform-status.md:3]: Was deleting this file intentional?

Comment (poulok) [reply platform-sdk/docs/core/platform-status.md:3]: I expected this to be updated to explain the new paradigm

Comment (alittley) [reply platform-sdk/docs/core/platform-status.md:3]: @poulok This deletion was intentional.

I started describing the new paradigm in text form, and found the result unhelpful. It was just a less digestible version of the state machine diagram, which already includes all relevant information regarding what events cause which transitions.

It also doesn't seem helpful to include documentation describing the characteristics of each platform status, as that documentation already exists in the `PlatformStatus` enum itself.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java [hunk 9]
```diff
@@ -16,166 +16,28 @@
...
-                throw new IllegalArgumentException(
-                        "Unknown action type: " + action.getClass().getName());
-            }
-        } catch (final IllegalPlatformStatusException e) {
-            logger.error(EXCEPTION.getMarker(), e.getMessage(), e);
-            return null;
-        }
-    }
-
+public interface PlatformStatusStateMachine extends PlatformStatusGetter, Startable, Stoppable {
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java:27]: It doesn't make sense to me to have the interface extend `Startable` and `Stoppable` when they only apply to one of the two implementations. I'm not sure this interface should even exist. There is one class that contains the queue thread: `AsyncPlatformStatusStateMachine`. I think it should instantiate the `SyncPlatformStatusStateMachine` class inside its own constructor and use it as a helper class that is strictly internal to itself, in which case the interface is not needed.

In my view, the `AsyncPlatformStatusStateMachine` is the "task component" interface that the outside world interacts with. That task module instantiates classes it needs to do it's job, one of which is `SyncPlatformStatusStateMachine`. Looking at it this way, I think it is more clear to call these class something like `PlatformStatusComponent` and `PlatformStatusStateMachine`.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/AsyncPlatformStatusStateMachine.java [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+
+        this.time = Objects.requireNonNull(time);
+        this.stateMachine = Objects.requireNonNull(stateMachine);
+        Objects.requireNonNull(threadManager);
+
+        this.handleThread = new QueueThreadConfiguration<PlatformStatusAction>(threadManager)
+                .setComponent("platform-status")
+                .setThreadName("platform-status-state-machine")
+                .setHandler(this::processStatusAction)
+                .setIdleCallback(this::triggerTimeElapsed)
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/AsyncPlatformStatusStateMachine.java:71]: The default waitForWork time is 10 milliseconds. Is that how often we want to trigger the time elapsed status? Maybe that should be configurable and set to a higher number.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java [hunk 11]
```diff
@@ -0,0 +1,203 @@
...
+
+    /**
+     * The object containing the state machine logic for the current status
+     */
+    private PlatformStatusLogic currentStatusLogic;
+
+    /**
+     * The current platform status, to be accessed in a thread safe manner
+     */
+    private final AtomicReference<PlatformStatus> currentStatus;
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java:75]: If we want to follow the component concepts @lpetrovic05 is laying out, this should be in a separate nexus component. We can leave that for later if you prefer - it will be an easy enough change given the current organization. It would replace the `PlatformStatusGetter` functional interface.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java [hunk 12]
```diff
@@ -0,0 +1,203 @@
...
+    /**
+     * Constructor
+     *
+     * @param time               a source of time
+     * @param config             the platform status config
+     * @param notificationEngine the notification engine
+     */
+    public SyncPlatformStatusStateMachine(
+            @NonNull final Time time,
+            @NonNull PlatformStatusConfig config,
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java:91]:
```suggestion
            @NonNull final PlatformStatusConfig config,
```

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java [hunk 13]
```diff
@@ -0,0 +1,203 @@
...
+        final String newStatusName = newLogic.getStatus().name();
+
+        final String statusChangeMessage = "Platform spent %s time in %s. Now in %s"
+                .formatted(Duration.between(currentStatusStartTime, time.now()), previousStatusName, newStatusName);
+
+        logger.info(
+                PLATFORM_STATUS.getMarker(),
+                () -> new PlatformStatusPayload(statusChangeMessage, previousStatusName, newStatusName).toString());
+
+        notificationEngine.dispatch(
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java:170]: I would move this to the very last thing done in this method. It is synchronous, it could delay updating the actual status and the start time.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java [hunk 14]
```diff
@@ -1025,6 +1039,23 @@ private PreconsensusEventWriter buildPreconsensusEventWriter(
...
 
+    /**
+     * Build the platform status state machine
+     *
+     * @param time a source of time
+     * @return the platform status state machine
+     */
+    @NonNull
+    private PlatformStatusStateMachine buildPlatformStatusStateMachine(@NonNull final Time time) {
+        final PlatformStatusConfig platformStatusConfig =
```
[the remark this answers is not in the document]
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:1050]: Method no longer exists with most changes in the next commit

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/AsyncPlatformStatusStateMachine.java (hunk 10 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/AsyncPlatformStatusStateMachine.java:71]: 10 milliseconds seems reasonable enough to me, but I'm not opposed to raising it. Do you think `100 millis` would be better?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java (hunk 5 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java]: Fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java (hunk 6 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java]: Fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java (hunk 7 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java]: Fixed

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java (hunk 9 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java]: I agree. Reworked

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java]: Done

Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java]: Done

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java (hunk 13 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/SyncPlatformStatusStateMachine.java]: Done

**Review by cody-littley — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java (hunk 9 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java]: Instead of `PlatformStatusComponent`, how about the name `PlatformStatusManager`? Even if this class is using Lazar's new component architecture, "component" seems linguistically awkward to me in this context.

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java (hunk 9 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java]: I also prefer `PlatformStatusManager`

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java [hunk 15]
```diff
@@ -0,0 +1,127 @@
...
+     */
+    @Override
+    public void stop() {
+        handleThread.stop();
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    public void processStatusAction(@NonNull final PlatformStatusAction action) {
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java:105]: This method is being called directly by other parts of the system. The queue is being bypassed.

The method that calls into the state machine should be private and only referenced by the code creating the queue thread.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java [hunk 16]
```diff
@@ -0,0 +1,127 @@
...
+public class PlatformStatusComponent implements PlatformStatusGetter, Startable, Stoppable {
+    /**
+     * A source of time
+     */
+    private final Time time;
+
+    /**
+     * The thread to handle incoming {@link PlatformStatusAction}s
+     */
+    private final QueueThread<PlatformStatusAction> handleThread;
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java:47]: In other classes, queue threads are usually referred to as a `queue` or a `queueThread`, not a `thread`. The interface it exposes is that of a queue and not a thread.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java [hunk 17]
```diff
@@ -0,0 +1,127 @@
...
+
+        this.time = Objects.requireNonNull(time);
+        Objects.requireNonNull(threadManager);
+        Objects.requireNonNull(notificationEngine);
+
+        final PlatformStatusConfig config =
+                platformContext.getConfiguration().getConfigData(PlatformStatusConfig.class);
+        this.stateMachine = new PlatformStatusStateMachine(time, config, notificationEngine);
+
+        this.handleThread = new QueueThreadConfiguration<PlatformStatusAction>(threadManager)
```
Comment (poulok) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java:76]: The maximum size of this queue should come from a configuration value.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java [hunk 18]
```diff
@@ -97,6 +99,11 @@ public class SignedStateFileManager implements Startable {
      */
     private final Time time;
 
+    /**
+     * Manages platform status
+     */
+    private final PlatformStatusComponent platformStatusComponent;
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java:105]: Instead of having the entire `PlatformStatusComponent` being passed around everywhere, maybe it's better to pass around a functional interface for submitting `PlatformStatusAction`. None of these classes should know about or be able to invoke the `start()` and `stop()` methods.

File: platform-sdk/docs/core/platform-status.md (hunk 8 above)
Comment (poulok) [reply platform-sdk/docs/core/platform-status.md:3]: I think there is still benefit to a textual supplement to the diagram. For example, why do we need a CHECKING state? Why is it necessary for the reconnect state to be saved to disk prior to moving to the CHECKING state? What is the purpose of the OBSERVING state? The "what" is explained well in the code, but not the why. Those questions are the more difficult to answer, so having a document with more context in it is useful.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java [hunk 19]
```diff
@@ -324,6 +347,7 @@ public void consensusRound(final ConsensusRound consensusRound) {
         if (!addedFirstRoundInFreeze && isRoundInFreezePeriod(consensusRound)) {
             addedFirstRoundInFreeze = true;
             enterFreezePeriod.run();
+            platformStatusComponent.processStatusAction(new FreezePeriodEnteredAction(consensusRound.getRoundNum()));
```
Comment (poulok) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java:350]: Updating the platform status to FREEZING used to be synchronous because `enterFreezePeriod.run()` called into `FreezeManager.freezeStarted()`, which updated the platform status directly. This changes it to be asynchronous, so the event creation logic for the tipset algorithm needs to key off of the freeze manager instead of the status.

@cody-littley

**Review by edward-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java [hunk 20]
```diff
@@ -0,0 +1,127 @@
...
+import com.swirlds.common.threading.manager.ThreadManager;
+import edu.umd.cs.findbugs.annotations.NonNull;
+import java.util.Objects;
+
+/**
+ * An asynchronous component which manages platform status.
+ * <p>
+ * This object wraps a {@link PlatformStatusStateMachine}, which contains the actual state machine logic.
+ */
+public class PlatformStatusComponent implements PlatformStatusGetter, Startable, Stoppable {
```
Comment (hendrikebbers) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java:38]: From my point of view `PlatformStatus*` should be part of `platform-core` instead of `swirlds-common`

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java (hunk 9 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusStateMachine.java]: Renamed

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/AsyncPlatformStatusStateMachine.java (hunk 10 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/AsyncPlatformStatusStateMachine.java]: I added a config field, with default `100ms`

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java (hunk 15 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java]: Oops, fixed. I made `processStatusAction` private, and added a new method `registerStatusAction`, which is what other parts of the system call

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java (hunk 16 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java]: Fixed

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java (hunk 17 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java]: fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java (hunk 18 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java]: Agreed, done

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java (hunk 20 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusComponent.java]: I don't have strong feelings either way, but I'd prefer to do this in a different PR if we decide to go this route, to avoid increasing scope

File: hedera-node/config.txt [hunk 21]
```diff
@@ -23,7 +23,7 @@ app,		HederaNode.jar
 # app, 		PlatformTestingDemo.jar, FCM1KFreeze.json
 # ** END REMOVE FROM SDK RELEASES **
 
- address,  A, Alice,    1, 127.0.0.1, 50204, 127.0.0.1, 50204, 0.0.3
+ address,  0, A, Alice,    1, 127.0.0.1, 50204, 127.0.0.1, 50204, 0.0.3
```
Comment (poulok) [inline hedera-node/config.txt]: hmmm...this may have been from a merge with develop. All the addresses should have node ids now

File: hedera-node/docs/design/services/smart-contract-service/accounts-blocklisting.md [hunk 22]
```diff
@@ -0,0 +1,78 @@
+# Accounts Blocklisting
```
Comment (poulok) [inline hedera-node/docs/design/services/smart-contract-service/accounts-blocklisting.md]: Strange. Why is this showing as a difference with `develop`?

**Review by lpetrovic05 — DISMISSED** [review]

**Comment by alittley** [comment]
I've drafted this PR to indicate that it is currently blocked. There will likely be merges that invalidate reviews at several points moving forward, so reviewers may feel free to wait until blockers are removed to re-review

**Review by edward-swirldslabs — APPROVED** [review]

**Review by edward-swirldslabs — DISMISSED** [review]

**Review by qnswirlds — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java [hunk 23]
```diff
@@ -0,0 +1,140 @@
...
+
+        final PlatformStatusConfig config =
+                platformContext.getConfiguration().getConfigData(PlatformStatusConfig.class);
+        this.stateMachine = new PlatformStatusStateMachine(time, config, notificationEngine);
+
+        this.queue = new QueueThreadConfiguration<PlatformStatusAction>(threadManager)
+                .setComponent("platform-status")
+                .setThreadName("platform-status-state-machine")
+                .setHandler(this::processStatusAction)
+                .setIdleCallback(this::triggerTimeElapsed)
```
Comment (cody-littley) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java:80]: Would it make sense to also add `setBatchHandledCallback(this::triggerTimeElapsed)`? My concern is that if we get work in the queue more frequently than once in 100ms, we may never get around to calling the idle callback.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java [hunk 24]
```diff
@@ -0,0 +1,140 @@
...
+        Objects.requireNonNull(threadManager);
+        Objects.requireNonNull(notificationEngine);
+
+        final PlatformStatusConfig config =
+                platformContext.getConfiguration().getConfigData(PlatformStatusConfig.class);
+        this.stateMachine = new PlatformStatusStateMachine(time, config, notificationEngine);
+
+        this.queue = new QueueThreadConfiguration<PlatformStatusAction>(threadManager)
+                .setComponent("platform-status")
+                .setThreadName("platform-status-state-machine")
```
Comment (cody-littley) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java:78]: Optional suggestion.
```suggestion
                .setComponent("platform")
                .setThreadName(status-state-machine")
```

This will cause the thread name to be `<platform: status-state-machine>`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java [hunk 25]
```diff
@@ -1046,9 +1051,13 @@ private void replayPreconsensusEvents() {
...
                     stateManagementComponent,
-                    currentPlatformStatus::get,
-                    this::setPlatformStatus,
+                    platformStatusManager,
                     initialMinimumGenerationNonAncient);
+        } else {
+            // if preconsensus events aren't being replayed, advance through that part of the state machine anyway
+            platformStatusManager.submitStatusAction(new StartedReplayingEventsAction());
+            platformStatusManager.submitStatusAction(
+                    new DoneReplayingEventsAction(Time.getCurrent().now()));
```
Comment (cody-littley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:1060]: If you pull the status action stuff out of `PreconsensusEventReplayWorkflow.replayPreconsensusEvents()`, then you can delete this else block and rearrange the code like this:

```
        platformStatusManager.submitStatusAction(new StartedReplayingEventsAction());
        if (enableReplay) {
            PreconsensusEventReplayWorkflow.replayPreconsensusEvents(
                    platformContext,
                    threadManager,
                    Time.getCurrent(),
                    preconsensusEventFileManager,
                    preconsensusEventWriter,
                    eventTaskDispatcher,
                    intakeQueue,
                    consensusRoundHandler,
                    stateHashSignQueue,
                    stateManagementComponent,
                    currentPlatformStatus::get,
                    this::setPlatformStatus,
                    platformStatusManager,
                    initialMinimumGenerationNonAncient);
        }
        platformStatusManager.submitStatusAction(
                    new DoneReplayingEventsAction(Time.getCurrent().now()));
```

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:1060]: A thought, feel free to take it or leave it depending if you think it is more or less elegant.

What if we hid the action objects from the public API, e.g. `new DoneReplayingEventsAction(Time.getCurrent().now())`. Instead, there would be a method for each action type, e.g. `platformStatusManager.doneReplayingEvents() // time is captured internally`.  We'd still use the action objects internally on the queue, but the use of the status manager becomes simpler.

If you end up doing this, the interface `StatusActionSubmitter` would end up having these methods on it, and `PlatformStatusStateMachine` would implement those methods.

If you like this idea but think it's too big a change at this point in the PR's lifespan, feel free to instead do it as a follow up task.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java (hunk 23 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java:80]: Hmm... in practice, the only action which occurs with any kind of frequency is `SelfEventReachedConsensus`, and if we're getting a lot of those, then the `TimeElapsedAction` isn't necessary anyway.

It's possible that we might add additional actions in the future though... I think I'll go ahead and do your suggestion, so there isn't a nasty surprise someday

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java (hunk 25 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java]: I like the idea of hiding the actions - I created an issue for this work [here](https://github.com/hashgraph/hedera-services/issues/7618)

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java (hunk 23 above)
Comment (alittley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/status/PlatformStatusManager.java:80]: Done

**Review by cody-littley — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]
