### PR TITLE
Fix test CryptoCreateSuite.syntaxChecksAreAsExpected

### LINKED ISSUE #9515: CryptoCreateSuite hapi test
- [x] createAnAccountEmptyThresholdKey
- [x] createAnAccountEmptyKeyList
- [x]                 createAnAccountEmptyNestedKey
- [x]                 createAnAccountInvalidKeyList
- [x]                 createAnAccountInvalidNestedKeyList
- [x]                 createAnAccountInvalidThresholdKey
- [x]                 createAnAccountInvalidNestedThresholdKey
- [x]                 createAnAccountThresholdKeyWithInvalidThreshold
- [x]                 createAnAccountInvalidED25519
- [x]                 syntaxChecksAreAsExpected
- [x]                 usdFeeAsExpected
- [x]                 createAnAccountWithStakingFields
- [x]                 createAnAccountWithECDSAAlias
- [x]                 createAnAccountWithED25519Alias
- [x]                 createAnAccountWithECKeyAndNoAlias
- [x]                 createAnAccountWithEDKeyAndNoAlias
- [x]                 createAnAccountWithED25519KeyAndED25519Alias
- [x]                 createAnAccountWithECKeyAndECKeyAlias
- [x]                 createAnAccountWithEVMAddressAliasFromSameKey
- [x]                 createAnAccountWithEVMAddressAliasFromDifferentKey
- [x]                 createAnAccountWithECDSAKeyAliasDifferentThanAdminKeyShouldFail
- [x]                 createAnAccountWithEDKeyAliasDifferentThanAdminKeyShouldFail
- [x]                 cannotCreateAnAccountWithLongZeroKeyButCanUseEvmAddress

### PR DESCRIPTION
**Pull request by kimbor**
Fix test CryptoCreateSuite.syntaxChecksAreAsExpected
Update to comments in NetworkUncheckedSubmitHandler

**Related issue(s)**:
Fixes #9515

### CODE REVIEW

**Review by Neeharika-Sompalli — COMMENTED** [review]
I see one HAPI test failing, Is it flaky ?

**Comment by kimbor** [comment]
> I see one HAPI test failing, Is it flaky ?

Not flaky, but it's also failing in develop.

**Comment by Neeharika-Sompalli** [comment]
> > I see one HAPI test failing, Is it flaky ?
> 
> Not flaky, but it's also failing in develop.

Ah I did not see that fail on my PR 🤔 . If its failing on develop also how was this enabled?

**Comment by kimbor** [comment]
> > > I see one HAPI test failing, Is it flaky ?
> > 
> > 
> > Not flaky, but it's also failing in develop.
> 
> Ah I did not see that fail on my PR 🤔 . If its failing on develop also how was this enabled?

It looks like it was fixed in your PR #9535 that just merged. I grabbed latest develop and now it passes locally for me. I merged develop here and tests are re-running, I think they will pass this time.

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java [hunk 1]
```diff
@@ -34,8 +34,11 @@
 /**
  * This class contains all workflow-related functionality regarding {@link HederaFunctionality#UNCHECKED_SUBMIT}.
  * <p>
- * This transaction type has been deprecated. Because protobufs promise backwards compatibility,
- * we cannot remove it. However, it should not be used.
+ * Unchecked submit is a mechanism to bypass ingest checks. This is a dangerous operation and will be removed
+ * in the future.
+ * Transactions that are wrapped in an unchecked submit call are unwrapped during ingest and then submitted directly.
+ * Therefore, unchecked submit is not a transaction type that is actually submitted to the network and there is no
+ * reason to implement a handler for it. This class exists for completeness but will never actually be called.
```
Comment (mhess-swl) [inline hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java:41]:
```suggestion
 * reason to implement a handler for it. This class exists for completeness but should never actually be called.
```
My suggestion is subjective at best. I typically like to account for the myriad branches of possibility I haven't considered 😅

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java [hunk 2]
```diff
@@ -100,7 +120,9 @@ public ExpiryMeta resolveCreationAttempt(
     @NonNull
     @Override
     public ExpiryMeta resolveUpdateAttempt(
-            @NonNull final ExpiryMeta currentMeta, @NonNull final ExpiryMeta updateMeta) {
+            @NonNull final ExpiryMeta currentMeta,
+            @NonNull final ExpiryMeta updateMeta,
+            final boolean isForTokenUpdate) {
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:125]: The other method of differentiating with the functionality enum seems easier to read and reason about, as opposed to the boolean added here. Any reason not to use functionality instead?

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java [hunk 3]
```diff
@@ -31,16 +32,18 @@ public interface ExpiryValidator {
...
      *
      * @return the expiry metadata that will result from the creation
      * @throws HandleException if the metadata is invalid
      */
     @NonNull
     ExpiryMeta resolveCreationAttempt(
-            boolean entityCanSelfFundRenewal, @NonNull ExpiryMeta creationMetadata, final boolean isForTopicCreation);
+            boolean entityCanSelfFundRenewal,
+            @NonNull ExpiryMeta creationMetadata,
+            final HederaFunctionality functionality);
```
Comment (mhess-swl) [inline hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java:46]: Nit:
```suggestion
            @NonNull final ExpiryMeta creationMetadata,
            @NonNull final HederaFunctionality functionality);
```

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java [hunk 4]
```diff
@@ -74,15 +77,32 @@ public ExpiryMeta resolveCreationAttempt(
...
             // Even if the effective expiry is valid, we still also require any explicit auto-renew period to be valid
             if (creationMeta.hasAutoRenewPeriod()) {
                 context.attributeValidator().validateAutoRenewPeriod(creationMeta.autoRenewPeriod());
             }
+        } else if (functionality == HederaFunctionality.TOKEN_CREATE) {
+            // In mono-service, INVALID_RENEWAL_PERIOD is thrown for token creation and update
+            // if the autoRenewPeriod is not in range.
+            // It would be more correct to throw AUTO_RENEW_DURATION_NOT_IN_RANGE like the other services do,
+            // but this would break differential testing. So for now, we replicate the mono-service behaviour.
+            try {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:94]: Instead of duplicating this block, can't we extract it to a method?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java (hunk 2 above)
Comment (kimbor) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:125]: We really only care whether the functionality enum is TOKEN_UPDATE or anything else. There are places in the smart contract code where it is known that some kind of smart contract functionality is in use but we don't specifically know which kind. In that case, it is clearer to simply pass 'false' (for not a TOKEN_UPDATE) versus either modifying a bunch of code to pass the exact smart contract functionality even though it doesn't ultimately matter, or passing a smart contract enum which is technically incorrect.

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java]: Fixed

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java (hunk 3 above)
Comment (kimbor) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java]: Fixed

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java (hunk 4 above)
Comment (kimbor) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:92]: Fixed

**Review by mhess-swl — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
