### PR TITLE
Move where EmergencyReconnectStartedAction is submitted

### LINKED ISSUE #7887: EmergencyReconnectStartedAction still isn't behaving correctly
The place where `EmergencyReconnectStartedAction`s are being created causes the following exception to be spammed:

```
2023-08-06 05:44:20.706 115      ERROR EXCEPTION        <<platform: status-state-machine>> PlatformStatusStateMachine: Received unexpected status action `EmergencyReconnectStartedAction` with current status of `BEHIND`
com.swirlds.common.system.status.IllegalPlatformStatusException: Received unexpected status action `EmergencyReconnectStartedAction` with current status of `BEHIND`
	at com.swirlds.common.system.status.logic.BehindStatusLogic.processEmergencyReconnectStartedAction(BehindStatusLogic.java:97) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at com.swirlds.common.system.status.PlatformStatusStateMachine.getNewLogic(PlatformStatusStateMachine.java:126) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at com.swirlds.common.system.status.PlatformStatusStateMachine.processStatusAction(PlatformStatusStateMachine.java:163) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at com.swirlds.common.system.status.PlatformStatusManager.processStatusAction(PlatformStatusManager.java:121) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:254) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:615) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:216) ~[swirlds-common-0.41.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Instead of submitting the status action in `EmergencyReconnectProtocol::shouldInitiate`, the call should be made in `EmergencyReconnectLearner::execute`, where the emergency reconnect is *actually* starting

Additionally, `EmergencyReconnectProtocol` shouldn't cause an exception if submitted while in the `BEHIND` status, since it's possible that an emergency reconnect may have to be attempted multiple times

### PR DESCRIPTION
**Pull request by alittley**
- Closes #7887

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]

**Review by timo0 — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectLearner.java [hunk 1]
```diff
@@ -36,29 +40,38 @@ public class EmergencyReconnectLearner {
...
+    private final StatusActionSubmitter statusActionSubmitter;
+
+    /**
+     * @param emergencyRecoveryFile the emergency recovery file used for this reconnect
+     * @param reconnectController   controls reconnecting as a learner
+     * @param statusActionSubmitter used to submit status actions
      */
     public EmergencyReconnectLearner(
-            final EmergencyRecoveryFile emergencyRecoveryFile, final ReconnectController reconnectController) {
+            final EmergencyRecoveryFile emergencyRecoveryFile,
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectLearner.java:53]: `@NonNull` or `@Nullable` markings on the other arguments.

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectLearner.java (hunk 1 above)
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectLearner.java]: added

**Review by edward-swirldslabs — APPROVED** [review]

**Review by cody-littley — APPROVED** [review]
