### PR TITLE
9944 Fix record cache handling to remediate "RECORD_NOT_FOUND" responses.

### LINKED ISSUE #9944: Fix record cache handling to remediate "RECORD_NOT_FOUND" responses
Most ScheduleRecordSpec tests return RECORD_NOT_FOUND because the dispatch of the triggered transactions is producing child records rather than the expected top level records.  Likewise some of the values in the triggered transaction are not matching Mono Service expectations.
We need to make necessary changes so those records can be found via the get transaction info query.

### PR DESCRIPTION
**Pull request by jsync-swirlds**
* Fixed an arithmetic bug in HandleWorkflow where we added instead of subtracting an offset
 * Adjusted RecordCacheImpl to treat scheduled transactions as top-level istead of children of the sign or create.
 * Adjusted RecordListBuilter to only create a synthetic transactionID if none is provided.
    * Includes modifying AbstractGrantApprovalCall to _not_ send an unnecessary transactionID.
 * Modified the DeduplicationCacheImpl to consider the `scheduled` flag when finding duplicate transaction ID values

Note: There remains a bug in consensus timestamp for child transactions.  That will be fixed in a separate PR as it also enables quite a few HapiTest methods, which makes that PR larger and more complex to review.

Fixes #9944

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java [hunk 1]
```diff
@@ -376,25 +377,26 @@ public Result build() {
...
         int nextNonce = count + 1; // Initialize to be 1 more than the number of preceding items
         count = childRecordBuilders == null ? 0 : childRecordBuilders.size();
         for (int i = 0; i < count; i++) {
-            final var recordBuilder = childRecordBuilders.get(i);
-            records.add(recordBuilder
-                    .transactionID(idBuilder.nonce(nextNonce++).build())
-                    .syncBodyIdFromRecordId()
-                    .build());
+            final SingleTransactionRecordBuilderImpl recordBuilder = childRecordBuilders.get(i);
+            // Only create a new transaction ID for child records is one is not provided
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/RecordListBuilder.java:392]: Not a blocker
```suggestion
            // Only create a new transaction ID for child records if one is not provided
```

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 2]
```diff
@@ -257,7 +257,7 @@ private void handlePlatformTransaction(
             @NonNull final ConsensusTransaction platformTxn) {
         // Get the consensus timestamp. FUTURE We want this to exactly match the consensus timestamp from the hashgraph,
         // but for compatibility with the current implementation, we adjust it as follows.
-        final Instant consensusNow = platformTxn.getConsensusTimestamp().minusNanos(1000 + 3L);
+        final Instant consensusNow = platformTxn.getConsensusTimestamp().minusNanos(1000 - 3L);
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:260]: Are we sure this is correct? This puts the transaction time OUTSIDE of the consTime +/- 1000 nanos range. Why would we want that?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java [hunk 3]
```diff
@@ -39,11 +39,14 @@
 public final class DeduplicationCacheImpl implements DeduplicationCache {
     /**
      * The {@link TransactionID}s that this node has already submitted to the platform, sorted by transaction start
-     * time, such that earlier start times come first. We guard this data structure within a synchronized block.
+     * time, such that earlier start times come first. An ID with scheduled set is different from the same ID
+     * without scheduled set (and, in fact, an ID with scheduled set will always match the ID of the ScheduleCreate
+     * transaction that created the schedule, except scheduled is set).
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java:44]: Just a thought
```suggestion
     * time, such that earlier start times come first. 
     *
     * <p>Note that an ID with scheduled set is different from the same ID
     * without scheduled set (and, in fact, an ID with scheduled set will always match the ID of the ScheduleCreate
     * transaction that created the schedule, except scheduled is set).
```

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java [hunk 4]
```diff
@@ -239,8 +238,9 @@ private void addToInMemoryCache(
         history.nodeIds().add(nodeId);
 
         // Either we add this tx to the main records list if it is a user/preceding transaction, or to the child
-        // transactions list of its parent
-        final var listToAddTo = isChildTx ? history.childRecords() : history.records();
+        // transactions list of its parent.  Note that scheduled transactions are always child transactions, but
+        // never produce child *records*, the scheduled transaction record is treated as a user transaction record.
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java:242]: ...therefore?
```suggestion
        // never produce child *records*, and therefore the scheduled transaction record is treated as a user transaction record.
```

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 2 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:260]: Actually, this fixes to put the time back in.
Subtraction (1000 + 3) means subtract 1003, which is outside.  This fixes the code to subtract 997, as originally intended.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java (hunk 4 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java:242]: it is more correct to say `instead` in this case.  Cause and effect are inverse from what therefore implies.
I'll make the corresponding change.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 2 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:260]: Ahhh I didn't see the double negative, got it 👍

Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:260]: It's confusing, which is probably why it was incorrect in the first place.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java (hunk 4 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java]: That's fine, I wasn't sure what the connecting phrase should be. Just that it wasn't there and my brain short-circuited

**Review by mhess-swl — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
