### PR TITLE
fix: Adjust Code Delegation revert flow with Ethereum Type 4 transactions

### LINKED ISSUE #23659: [EIP-7702][BUG] Reverting origin transaction rollbacks code delegation updates
Negative scenarios of code delegation related tests via type 4 ethereum transactions do not comply with the HIP-1340 definition and rollback any delegation related updates.

- Investigate the behaviour
- Implement solution
- Add additional HAPI tests to verify the reversion flows are covered

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
Adding adjustments to the negative scenario of setting code delegation via type 4 transaction and the origin transaction fails. 
Also fix up the failure record if insufficient funds for lazy create from authorisation list. 

Also providing HAPI tests covering the fixed flows

**Related issue(s)**:

Fixes #23659 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java [hunk 1]
```diff
@@ -179,6 +179,42 @@ public static <T extends StreamBuilder> DispatchOptions<T> independentDispatch(
                 UNIVERSAL_NOOP_FEE_CHARGING);
     }
 
+    /**
+     * Returns options for a dispatch that is independent of the parent dispatch yet executed with parent.
+     * Use cases related to EIP-7702 code delegation,
+     * <ul>
+     *     <li>Creating a hollow account from a public key set in authorization list field of type 4 Ethereum transactions.</li>
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java:186]: that flow no longer creates a _hollow_ account, so let's update this comment

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java [hunk 2]
```diff
@@ -179,6 +179,42 @@ public static <T extends StreamBuilder> DispatchOptions<T> independentDispatch(
...
+     * @param streamBuilderType the type of stream builder to use for the dispatch
+     * @return the options for the setup dispatch
+     * @param <T> the type of stream builder to use for the dispatch
+     */
+    public static <T extends StreamBuilder> DispatchOptions<T> independentStepDispatch(
+            @NonNull final AccountID payerId,
+            @NonNull final TransactionBody body,
+            @NonNull final Class<T> streamBuilderType) {
+        return new DispatchOptions<>(
+                Commit.WITH_PARENT,
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/DispatchOptions.java:203]: Looking at the doc of `WITH_PARENT` doesn't seem to match what we want to achieve:
```
        /**
         * Wait to commit the dispatched transaction's effects with its parent; hence, only commit these effects
         * if the parent dispatch does not roll back.
         */
```

is that comment obsolete?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java [hunk 3]
```diff
@@ -156,6 +157,9 @@ private void tryHandle(
             }
             handleSystemUpdates(dispatch);
         } catch (HandleException e) {
+            // For EIP-7702 eth type 4 transactions we need to commit the code delegation related actions before rolling
+            // back
+            commitPossibleDelegationActions(dispatch, functionality);
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java:162]: I have mixed feelings about having this here 😅 It looks fine, I guess, but feels a bit off abstraction-wise.
I can't think of any better alternative though, so 👍

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java [hunk 4]
```diff
@@ -351,4 +355,19 @@ private boolean failsSignatureVerification(@NonNull final Dispatch dispatch) {
         }
         return false;
     }
+
+    private void commitPossibleDelegationActions(
+            @NonNull final Dispatch dispatch, @NonNull final HederaFunctionality functionality) {
+        if (hasAuthorizationList(dispatch, functionality)) {
+            dispatch.stack().commitFullStack();
```
Comment (lukasz-hashgraph) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/DispatchProcessor.java:362]: Are we sure there will never be any other items on the stack here aside from delegation processing outcomes?

**Comment by stoyanov-st** [comment]
Merging as is. Comments will be addressed in a future PR.
