### PR TITLE
address comments from pr #9519

### LINKED ISSUE #9517: Slot values should never be null
### Description

Replace all slot values and keys to use Bytes.EMPTY to indicate empty values

### Steps to reproduce

See above

### Additional context

_No response_

### Hedera network

other

### Version

v0.43

### Operating system

None

### PR DESCRIPTION
**Pull request by lukelee-sl**
**Description**:
There were a couple of code review comments from pr #9519 that need to be addressed

**Related issue(s)**:

Fixes #9517

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/StorageAccess.java [hunk 1]
```diff
@@ -30,7 +30,7 @@
  *
  * @param key the key of the access
  * @param value the value read or overwritten
- * @param writtenValue if not Bytes.EMPTY, the overwriting value
+ * @param writtenValue if not null, the overwriting value
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/StorageAccess.java:33]: undoing this change from the previous pr as the `writtenValue` _can_ be null if the `StorageAccess` was for a read.

**Review by david-bakin-sl — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM

**Review by kimbor — APPROVED** [review]
