### PR TITLE
fix: improve hashing with PBJ 0.12.2

### LINKED ISSUE #21808: Improve hashing with PBJ 0.12.2
Improve hashing with `WritableMessageDigest` from PBJ 0.12.2

### PR DESCRIPTION
**Pull request by OlegMazurov**
**Description**:
* upgrade PBG to 0.12.2
* simplify hashing with WritableMessageDigest
* remove lambdas from performance critical code (`VirtualLeafBytes.writeToForHashing()`)

**Related issue(s)**:

Fixes #21808

**Notes for reviewer**:
CryptoBench before:
```
2025-10-23 07:56:23.494 Total transactions: 600000000, time: 11516 sec, TPS: 52100
```
after:
```
2025-10-23 07:48:13.308 Total transactions: 600000000, time: 11012 sec, TPS: 54484
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java [hunk 1]
```diff
@@ -240,15 +231,15 @@ protected boolean onExecute() {
         }
 
         static Hash hash(final Hash left, final Hash right) {
-            final MessageDigest md = MESSAGE_DIGEST_THREAD_LOCAL.get();
-            md.reset();
+            final WritableMessageDigest wmd = MESSAGE_DIGEST_THREAD_LOCAL.get();
+            wmd.reset();
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java:235]: Minor q: `MessageDigest.digest()` resets the MD object per its javadoc. What is the reason for calling `reset()` explicitly?

Comment (OlegMazurov) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java:235]: The only reason I can come up with is a defense against a previous failed attempt to use the thread local (leftover bytes that were not digested due to some exception, f.e.). Currently, it's overly paranoid as all uses of the thread local are in this class and any exception would be a bigger problem to worry about. In the future, however, we are thinking about having a different implementation for thread locals where `MessageDigest` would be available for free in any thread in the task processing thread pool. There will be no control over who uses `MessageDigest` and it will be safer to ensure a clean state before use.

Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java:235]: Makes sense. Thanks for clarifying.

**Review by rbarker-dev — APPROVED** [review]
