### PR TITLE
fix: publisher logging errors

### LINKED ISSUE #21961: Quiescence mode: unexpected ERROR "DefaultPlatformPublisher: No preconsensus event consumer is registered"
Branch: 21683-integrate-quiescence-controller

all nodes on HashSphere throws ERROR:
https://perf.analytics.eng.hashgraph.io/ephemeral/test_runs/21683-integrate-quiescence-controller_AdHoc6_44/report/podlog_solo-sdpt-n6/network-node1_logs/swirlds.log

`2025-10-31 02:06:42.012 33       ERROR EXCEPTION        <platformForkJoinThread-5> DefaultPlatformPublisher: No preconsensus event consumer is registered`

@tinker-michaelj

### PR DESCRIPTION
**Pull request by lpetrovic05**
closes #21961

The publisher was logging errors if some consumers were null. But looking at the publisher, I saw no reason for it to exist....

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java [hunk 1]
```diff
@@ -242,12 +243,8 @@ public void consensusSnapshotOverride(@NonNull final ConsensusSnapshot consensus
                 .consensusEngineWiring()
                 .getInputWire(ConsensusEngine::outOfBandSnapshotUpdate)
                 .inject(consensusSnapshot);
-
-        if (components.platformPublisherWiring().getSchedulerType() != TaskSchedulerType.NO_OP) {
-            components
```
Comment (mxtartaglia-sl) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java:247]: we definitely don't need the getSchedulerType method anymore

Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformCoordinator.java:247]: removed
