### PR TITLE
Property ledger.keepRecordsInState is set to true by default.

### LINKED ISSUE #898: Daily-Comp-NetError-4N-1C fails with bad account records exception
The test is failing on both AWS and GCP
```
---- HAPIClientValidator FAILED validation ----
<<ERROR>>
java.lang.Exception: Bad account records! :: Bad list size! expected:<0> but was:<1>
```

### PR DESCRIPTION
**Pull request by anighanta**
set the property ledger.keepRecordsInState before the tests as it is being set to true at startUp on every regression run.

Signed-off-by: Anirudh Ghanta <anirudh.ghanta@hedera.com>

**Related issue(s)**:
Closes #898 

**Summary of the change**:
Set ledger.keepRecordsInState=false before the test `accountsGetPayerRecordsIfSoConfigured`.

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java [hunk 1]
```diff
@@ -60,6 +60,9 @@ private HapiApiSpec accountsGetPayerRecordsIfSoConfigured() {
 				.given(
 						cryptoCreate("payer")
 				).when(
+						fileUpdate(APP_PROPERTIES)
```
Comment (Neeharika-Sompalli) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/records/RecordCreationSuite.java:63]: Please add a passing test result with this change to the PR description

**Review by qnswirlds — COMMENTED** [review]
Changes look good. Waiting for a link to a successful run to approve.

**Comment by anighanta** [comment]
Node 0 - RecordCreation                  PASSED 
in https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609445428398600
and https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609434495389900

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM. Please create a separate issue for the failing token tests. I believe these errors did not occur when running on circleCI.

**Review by qnswirlds — APPROVED** [review]

**Comment by anighanta** [comment]
> LGTM. Please create a separate issue for the failing token tests. I believe these errors did not occur when running on circleCI.

The cause might be because of my local. I didn't see this error on Hedera-regression channel for test Misc-Basic-1-11m.json
