### PR TITLE
Fix TxnReceiptRegression suite

### LINKED ISSUE #8917: FIx TxnReceiptRegression

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:
Fixed some of `TxnReceiptRegression` tests.

**Related issue(s)**:

Fixes #8917 
**Notes for reviewer**:
Added `@HapiTest` annotation to `returnsInvalidForUnspecifiedTxnId()`, `receiptAvailableWithinCacheTtl()` and `receiptNotFoundOnUnknownTransactionID()`. I had to extend the if condition in `validate` in the `NetworkTransactionGetReceiptHandler` in order to throw the correct exceptions and change the expected return of `receiptNotFoundOnUnknownTransactionID ()` to `INVALID_TRANSACTION_ID` as that is the implemented logic.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java [hunk 1]
```diff
@@ -113,13 +115,14 @@ private HapiSpec receiptUnavailableIfRejectedInPrecheck() {
...
+    @HapiTest
     private HapiSpec receiptNotFoundOnUnknownTransactionID() {
         return defaultHapiSpec("receiptNotFoundOnUnknownTransactionID")
                 .given()
                 .when()
                 .then(withOpContext((spec, ctxLog) -> {
-                    HapiGetReceipt op =
-                            getReceipt(spec.txns().defaultTransactionID()).hasAnswerOnlyPrecheck(RECEIPT_NOT_FOUND);
+                    final HapiGetReceipt op = getReceipt(spec.txns().defaultTransactionID())
+                            .hasAnswerOnlyPrecheck(INVALID_TRANSACTION_ID);
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java:125]: We should not be changing the response and comply with mono-service

Comment (rbair23) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java:125]: That is correct, the test logic should not change. We need to align the behavior in the modular code to match the mono service behavior, and the tests are the guard to ensure we do it correctly.

Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java]: Understood. Changes are applied.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !
