### PR TITLE
Fix the critical code smell issues.

### LINKED ISSUE #1493: Fix Critical SonarCloud CodeSmells
**Summary**
Fix Critical CodeSmells except "Cognitive Complexity" in SonarCloud

Parent issue : #1491 

NOTE: While creating the branch to address the issue, start branch name with `branch` so that sonar cloud compares the issues on master are resolved.

First clean up those fake issues, like the following:

- [ ] commented out line in license header to be removed;
- [ ] The class with *Test.java needs to have @Test scenarios;

### PR DESCRIPTION
**Pull request by ljianghedera**
**Description**:
This PR fixed all critical code smell issues as of now.

**Related issue(s)**:

Fixes #1493 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java [hunk 1]
```diff
@@ -97,33 +99,61 @@ ResponseCodeEnum validateTokenTransferSizes(
...
-				if (transferCounts == 0) {
-					return EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS;
-				}
-				count += transferCounts;
-				if (count > maxListLen) {
-					return TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED;
+
+				try {
+					count = checkTokenTransferNum(scopedTransfers, count, maxListLen);
+				} catch (InvalidTransactionException e) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java:129]: Here also imo if we can avoid using exceptions here also, we should. Not only does throwing an exception create an object, but it captures the stack trace, which can be surprisingly expensive. (See [this blog](https://shipilev.net/blog/2014/exceptional-performance/) for a long discussion about the performance impact of exceptions.)

File: hedera-node/src/main/java/com/hedera/services/legacy/evm/SolidityExecutor.java [hunk 2]
```diff
@@ -241,58 +241,69 @@ private void call() {
...
-			}
+			precompileContractIsNull(targetAddress);
 		}
 		if (!localCall) {
 			transfer(trackingRepository, solidityTxn.getSender(), targetAddress, toBI(solidityTxn.getValue()));
 			touchedAccounts.add(targetAddress);
 		}
 	}
 
+	private void precompileContractIsNull(final byte[] targetAddress) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/legacy/evm/SolidityExecutor.java:256]: Maybe,

```suggestion
	private void executeContractAt(final byte[] targetAddress) {
```

File: hedera-node/src/main/java/com/hedera/services/legacy/evm/SolidityExecutor.java [hunk 3]
```diff
@@ -241,58 +241,69 @@ private void call() {
...
+					contractCreateAdaptor,
+					fundingAddress,
+					rbh,
+					sbh,
+					dynamicProperties.defaultContractLifetime(),
+					dynamicProperties.cacheRecordsTtl()).withCommonConfig(commonConfig);
+		}
+	}
+
+	private boolean precompiledContractNotNull(final byte[] targetAddress) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/legacy/evm/SolidityExecutor.java:282]: Maybe,

```suggestion
      /* Returns true if an error occurs during execution of the precompiled contract */
	private boolean executePrecompiledContractAt(final byte[] targetAddress) {
```

File: hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java [hunk 4]
```diff
@@ -446,20 +446,24 @@ private boolean hasNondeprecatedAdminKey(ContractUpdateTransactionBody op) {
 			} else {
 				List<JKey> required = new ArrayList<>();
 				if (waclShouldSign) {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java:448]: These changes to `HederaSigningOrder` will conflict with refactoring I'm doing for https://github.com/hashgraph/hedera-services/issues/1890; I'm replacing the,
```
	final Predicate<TransactionBody> updateAccountSigns;
	final BiPredicate<TransactionBody, HederaFunctionality> targetWaclSigns;
```
fields with a dedicated `SignatureWaivers` class. I'd suggest reverting the changes to this file, if you don't mind. 🙏

File: hedera-node/src/main/java/com/hedera/services/sigs/order/SigningOrderException.java [hunk 5]
```diff
@@ -28,13 +28,13 @@
  * @see HederaSigningOrder
  */
 public class SigningOrderException extends Exception {
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/sigs/order/SigningOrderException.java:30]: This class can be deleted, actually. 😁

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java [hunk 6]
```diff
@@ -218,36 +218,48 @@ public void deserialize(SerializableDataInputStream in, int version) throws IOEx
 		midnightRates = in.readSerializable(true, ratesSupplier);
 
 		if (version >= RELEASE_0130_VERSION) {
-			int numUsageSnapshots = in.readInt();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java:221]: If we're cleaning up this method, it might be a good time to remove always-true migration conditions (e.g. `version >= RELEASE_0130_VERSION` is always true now).

File: hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java [hunk 7]
```diff
@@ -358,27 +358,18 @@ public ExpirableTxnRecord copy() {
 
 	public static ExpirableTxnRecord fromGprc(TransactionRecord record) {
 		List<EntityId> tokens = NO_TOKENS;
-		List<CurrencyAdjustments> tokenAdjustments = null;
-		List<NftAdjustments> nftTokenAdjustments = null;
+		List<CurrencyAdjustments> tokenAdjustments = new ArrayList<>();
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java:361]: These lists are purposely initialized as `null` instead of a new `ArrayList` because in many cases we can avoid creating these objects.

File: hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java [hunk 8]
```diff
@@ -21,6 +21,7 @@
  */
 
 import com.hedera.services.context.TransactionContext;
+import com.hedera.services.exceptions.InvalidTransactionException;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java:24]: In the next week or so LimeChain will open a PR that completely refactors this class; I think we should revert these changes also to avoid needless merge conflicts.

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
Thanks for attacking these @ljianghedera!  🙏 

Almost all of the changes for smells other than "cognitive complexity" I think are great. (Except as I wrote in comments below, I would revert the changes to `HederaSigningOrder` and `TokenUpdateTransitionLogic`, because both those classes have more targeted refactoring in progress.)

For the "cognitive complexity" smells, I also like the changes to classes that already had 100% unit test coverage. But I would vote to ignore these smells on legacy classes that have little or no code coverage. (I guess `SolidityExecutor` and `SmartContractRequestHander` in particular.)

Would be interested to see what others think.

**Review by qnswirlds — COMMENTED** [review]
Overall LGTM.

File: hedera-node/src/main/java/com/hedera/services/exceptions/TooManyCustomFeesException.java [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ * ‍
+ */
+
+import com.hederahashgraph.api.proto.java.TransferList;
+
+import static com.hedera.services.utils.MiscUtils.readableTransferList;
+
+public class TooManyCustomFeesException extends IllegalArgumentException {
```
[the remark this answers is not in the document]
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/exceptions/TooManyCustomFeesException.java:27]: Make sense as performance is a big concern in our case. 

Removed this exception class and changed to the suggested implementation.

File: hedera-node/src/main/java/com/hedera/services/exceptions/TooManyCustomFeesException.java [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+	public static String messageFor(final int actual, final int maxAllowed) {
+		return String.format("Max allowed custom fee size is '%d', actual custom fee number is now '%d'", maxAllowed, actual);
```
[the remark this answers is not in the document]
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/exceptions/TooManyCustomFeesException.java:29]: This class is removed.

File: hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java [hunk 11]
```diff
@@ -78,20 +104,12 @@ public ResponseCodeEnum assess(
 					htsFeeAssessor.assess(payer, fee, balanceChangeManager, accumulator);
 				}
 				if (balanceChangeManager.numChangesSoFar() > maxBalanceChanges) {
-					return CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS;
+					throw new TooManyCustomFeesException(balanceChangeManager.numChangesSoFar(), maxBalanceChanges);
```
[the remark this answers is not in the document]
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java:107]: Use the suggested approach to get rid of exception throwing.

File: hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java (hunk 1 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java:129]: Yeah, changed the implementation to avoid throwing exception.

File: hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java [hunk 12]
```diff
@@ -113,6 +113,9 @@
 			.build();
 	private static final AccountID AN_ACCOUNT = AccountID.newBuilder().setAccountNum(1_234L).build();
 
+	private static final String AN_TOKEN_NAME = "012345678912";
+	private static final String AN_TOKEN_SYMBOL = "ABCD";
```
[the remark this answers is not in the document]
Comment (ljianghedera) [reply hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java:117]: Fixed.

File: hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java (hunk 4 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java:448]: Not at all. Reverted all changes to file.

File: hedera-node/src/main/java/com/hedera/services/sigs/order/SigningOrderException.java (hunk 5 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/sigs/order/SigningOrderException.java:30]: Deleted this exception.

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java (hunk 6 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java:221]: Good idea! Removed the check of `version >= RELEASE_0130_VERSION`.

File: hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java (hunk 8 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java:24]: Absolutely. Done the reverting.

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleOptionalBlob.java [hunk 13]
```diff
@@ -106,6 +106,7 @@ public void setHash(Hash hash) {
 	 */
 	@Override
 	public void invalidateHash() {
+		// Do nothing because this is no-op intentionally.
```
[the remark this answers is not in the document]
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleOptionalBlob.java:109]: Actually this does make SonarCloud happier based on my experiment. If the body is empty (no code, no comment), SonarCloud complains code smell. If some comment is put there, SonarCloud will be quiet.

**Comment by ljianghedera** [comment]
> Thanks for attacking these @ljianghedera! 🙏
> 
> Almost all of the changes for smells other than "cognitive complexity" I think are great. (Except as I wrote in comments below, I would revert the changes to `HederaSigningOrder` and `TokenUpdateTransitionLogic`, because both those classes have more targeted refactoring in progress.)
> 
> For the "cognitive complexity" smells, I also mostly like the changes to classes with 100% unit test coverage. But my vote would be to ignore these smells on legacy classes that have little or no code coverage. (`SolidityExecutor` and `SmartContractRequestHander` in particular.)
> 
> Would be interested to see what others think.
So you mean we better not touch these legacy classes at all? Yeah, I can feel that.  I had quite a struggle on how to handle the legacy code when reviewing these classes. The dilemma is if leave the legacy code alone and use SonarCloud's suppression mechanism to ignore these code smells in master branch, they may showing up in developer's branches occasionally and cause confusions; If we touch the these classes which don't have any test coverage, then codecov will not be happy at all, and I don't think it's wise to spend lots of effort to provide test coverage to these soon to be gone code at all.  

After some struggle, I guess one solution is to fix the code smells (a small effort) but ignore the code coverage (a big effort). To do so, the first time to merge back to master, we need to force the codecov. After that, as long as we don't touch the legacy code, the legacy code coverage issue won't be triggered any more.

Not sure if this is a good solution though.

File: hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java (hunk 7 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java:361]: Yeah, changed the implementation to keep these lists to still be initialized as `null`.

File: hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java [hunk 14]
```diff
@@ -78,20 +108,12 @@ public ResponseCodeEnum assess(
 					htsFeeAssessor.assess(payer, fee, balanceChangeManager, accumulator);
 				}
 				if (balanceChangeManager.numChangesSoFar() > maxBalanceChanges) {
-					return CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS;
+					return FixedFeeProcessingResult.ASSESSMENT_FAILED_WITH_TOO_MANY_ADJUSTMENTS_REQUIRED;
 				}
 			} else {
-				hasFractionalFees = true;
+				return FixedFeeProcessingResult.FRACTIONAL_FEE_ASSESSMENT_PENDING;
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java:114]: Oops, here we only want to "remember to return" `FRACTIONAL_FEE_ASSESSMENT_PENDING`.

 If we `return` right away, we will skip any other fixed fees in the `fees` list! 😲

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java:221]: Since we are now on release `0.16.0`, all the checks in this method will always be true; but not urgent to change in this PR.

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
Overall looks good!! But as noted, the `FixedFeeAssessor` must always iterate over _all_ the `fees` before returning its result.

File: hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java (hunk 14 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java:114]: Right, right, that's silly!

Fixed and also added test cases to cover this scenario.

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java (hunk 6 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java:221]: I think I can clean up `0.14.0` as well, but should we still keep `0.15.0` check? I mean, we may still need to restore from `0.15.0` state file, right?

**Review by tinker-michaelj — APPROVED** [review]
LGTM!!
