### PR TITLE
fix return File instead of optional when call getFileLeaf

### LINKED ISSUE #8198: `ReadableFileStore.getFileLeaf()` need to not return Optional
`ReadableFileStore.getFileLeaf()` returns an `Optional` but we prefer to return the object directly and `null` if not found, because `null` is not a valid value in the state.

### PR DESCRIPTION
**Pull request by povolev15**
fix return null instead of optional when call getFileLeaf

**Related issue(s)**:

Fixes #8198

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java [hunk 1]
```diff
@@ -283,12 +283,13 @@ private Bytes initcodeFor(@NonNull final ContractCreateTransactionBody body) {
             return body.initcode();
         } else {
             final var maybeInitcode = fileStore.getFileLeaf(body.fileIDOrElse(FileID.DEFAULT));
-            validateTrue(maybeInitcode.isPresent(), INVALID_FILE_ID);
-            final var initcode = maybeInitcode.get();
-            validateFalse(initcode.deleted(), FILE_DELETED);
-            validateTrue(initcode.contents().length() > 0, CONTRACT_FILE_EMPTY);
+            if (maybeInitcode == null) {
+                throw new HandleException(INVALID_FILE_ID);
+            }
```
Comment (jsync-swirlds) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java:288]: For consistency, this could be:
```java
            validateFalse(maybeInitcode == null, INVALID_FILE_ID);
```

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java [hunk 2]
```diff
@@ -283,12 +283,13 @@ private Bytes initcodeFor(@NonNull final ContractCreateTransactionBody body) {
             return body.initcode();
         } else {
             final var maybeInitcode = fileStore.getFileLeaf(body.fileIDOrElse(FileID.DEFAULT));
```
Comment (jsync-swirlds) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java:285]: This might read better if renamed `maybeInitCode ==> initCode`

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java (hunk 1 above)
Comment (povolev15) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java:288]: done thanks

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java [hunk 3]
```diff
@@ -57,10 +56,13 @@ public ReadableFileStoreImpl(@NonNull final ReadableStates states) {
      */
     public @Nullable FileMetadata getFileMetadata(@Nullable final FileID id) {
         final var file = getFileLeaf(id);
-        return file.map(FileStore::fileMetaFrom).orElse(null);
+        if (file == null) {
+            return null;
+        }
+        return file == null ? null : FileStore.fileMetaFrom(file);
```
[the remark this answers is not in the document]
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java:62]: done thanks

**Review by jsync-swirlds — APPROVED** [review]

**Review by rbair23 — APPROVED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java [hunk 4]
```diff
@@ -282,13 +282,12 @@ private Bytes initcodeFor(@NonNull final ContractCreateTransactionBody body) {
         if (body.hasInitcode()) {
             return body.initcode();
         } else {
-            final var maybeInitcode = fileStore.getFileLeaf(body.fileIDOrElse(FileID.DEFAULT));
-            validateTrue(maybeInitcode.isPresent(), INVALID_FILE_ID);
-            final var initcode = maybeInitcode.get();
-            validateFalse(initcode.deleted(), FILE_DELETED);
-            validateTrue(initcode.contents().length() > 0, CONTRACT_FILE_EMPTY);
+            final var initCode = fileStore.getFileLeaf(body.fileIDOrElse(FileID.DEFAULT));
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java:285]: A nit but I believe that the original `initcode` is correct.

**Review by lukelee-sl — APPROVED** [review]
LGTM

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java [hunk 5]
```diff
@@ -57,10 +56,10 @@ public ReadableFileStoreImpl(@NonNull final ReadableStates states) {
      */
     public @Nullable FileMetadata getFileMetadata(@Nullable final FileID id) {
         final var file = getFileLeaf(id);
-        return file.map(FileStore::fileMetaFrom).orElse(null);
+        return file == null ? null : FileStore.fileMetaFrom(file);
     }
 
-    public @Nullable Optional<File> getFileLeaf(@Nullable FileID id) {
-        return Optional.ofNullable(fileState.get(id));
+    public @Nullable File getFileLeaf(@Nullable FileID id) {
```
Comment (netopyr) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java:62]: Nit: Not part of this PR, but does it make sense to allow a `@Nullable` `id`?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java (hunk 4 above)
Comment (povolev15) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java:285]: I didn't change any of the code I just changed the readableFileStoreImpl and that's why I had to change in all these places

**Review by netopyr — APPROVED** [review]
LGTM

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java (hunk 5 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java:62]: We will do it. That's what I discuss also with @jsync-swirlds

Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java:62]: and I think you mean @NonNull

Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java:62]: Already noted for a follow-up.

Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java:62]: https://github.com/hashgraph/hedera-services/issues/8198 issue created

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java (hunk 4 above)
Comment (povolev15) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java:285]: will be fixed as part of that issue
https://github.com/hashgraph/hedera-services/issues/8207

**Review by iwsimon — APPROVED** [review]

**Review by AlfredoG87 — APPROVED** [review]
LGTM
