### PR TITLE
7046 Fixed NPE which caused infinite wait on a future object. 

### LINKED ISSUE #7046: MerkleDB Unit Tests Hang
Several times in the last week, I have observed the platform unit test suite get stuck and run for many hours. When I observe this, I cancel the test suite. Always, the workflow seem to be in the middle of the JasperDB tests.

Example: https://github.com/hashgraph/hedera-services/actions/runs/5224279727/jobs/9432293344?pr=7022

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

- Fixed NPE which caused infinite wait on a future object. 
- Added cancellation of a future in case of an error.  
- Re-enabled the tests that were previously disabled

**Related issue(s)**:

Fixes #7046 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java [hunk 1]
```diff
@@ -309,11 +309,15 @@ public StandardFuture<Void> parallelTraverse(Executor executor, Consumer<T> acti
...
-                    result.complete(null);
+                try {
+                    for (int i = 0; i < size; ++i) {
+                        action.accept(array[i]);
+                    }
+                    if (count.decrementAndGet() == 0) {
+                        result.complete(null);
+                    }
+                } catch (Exception e) {
+                    result.cancelWithError(true, e);
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java:320]: It appears the first parameter is superfluous as no callback was provided for the `StandardFuture`.

**Review by OlegMazurov — APPROVED** [review]

**Review by deepak-swirlds — DISMISSED** [review]

**Review by OlegMazurov — APPROVED** [review]
