### PR TITLE
fix: consensus writes marker before exception

### LINKED ISSUE #11633: 2024-02-20 - TaskSchedulerBuilder: Uncaught Exception in scheduler linkedEventIntake
http://35.247.76.217:8095/swirlds-automation/release/0.47/4N_2C/CentOS7_Update/20240217-110814-GCP-Daily-Update-CentOS7-4N-2C/Crypto-Update-Jar-1.5k-25m/

I've pasted swirlds.log up until the exception starts occurring at the bottom. 

```
---- ErrorValidator FAILED validation ----
(Node 0) Marker EXCEPTION appeared 135155 times.
(Node 0) Exception java.lang.IllegalStateException appeared 135152 times.
(Node 1) Marker EXCEPTION appeared 135159 times.
(Node 1) Exception java.lang.IllegalStateException appeared 135156 times.
(Node 2) Marker EXCEPTION appeared 135159 times.
(Node 2) Exception java.lang.IllegalStateException appeared 135156 times.
(Node 3) Marker EXCEPTION appeared 135157 times.
(Node 3) Exception java.lang.IllegalStateException appeared 135154 times.
```

All nodes failed to come up on this run, logs filled with the following exception.  

```
2024-02-17 11:23:46.103 80       ERROR EXCEPTION        <<scheduler linkedEventIntake>> TaskSchedulerBuilder: Uncaught exception in scheduler linkedEventIntake
java.lang.IllegalStateException: Cannot provide the minimum generation until all judges are found
	at com.swirlds.platform.consensus.RoundElections.getMinGeneration(RoundElections.java:115) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.consensus.RoundElections.creatMinGenInfo(RoundElections.java:124) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.consensus.ConsensusRounds.currentElectionDecided(ConsensusRounds.java:132) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.roundDecided(ConsensusImpl.java:639) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.calculateAndVote(ConsensusImpl.java:370) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.recalculateAndVote(ConsensusImpl.java:322) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.addEvent(ConsensusImpl.java:280) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.components.LinkedEventIntake.addEvent(LinkedEventIntake.java:127) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$0(BindableInputWire.java:74) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:193) ~[swirlds-common-0.80.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
[node-0-swirlds.log](https://github.com/hashgraph/hedera-services/files/14351052/node-0-swirlds.log)

### PR DESCRIPTION
**Pull request by edward-swirldslabs**
**Description**:
This PR moves the checking of judges and writing of marker files before the exception thrown in the issue.   The whole marker file writing endeavor was necessitated by this issue.  This completes the story arc on the platform side.  The next time this exception occurs we will have written a marker file and then it is up to JRS to respond to the presence of the marker file. 

Fixes #11633

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java [hunk 1]
```diff
@@ -651,6 +651,9 @@ private List<EventImpl> getStronglySeenInPreviousRound(final EventImpl event) {
         final List<EventImpl> judges = roundElections.findAllJudges();
         final long decidedRoundNumber = rounds.getElectionRoundNumber();
 
+        // Check for no judges or super majority conditions.
+        checkJudges(judges, decidedRoundNumber);
```
Comment (kfa-aguda) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java:655]: looks good to me.
As an aside, i think this method can be better named - `writeMarkerFile` is probably more appropriate.

**Review by kfa-aguda — APPROVED** [review]

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java (hunk 1 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ConsensusImpl.java:655]: I disagree, the writing of the marker files doesn't happen in all cases, only when the judges fail their checks.  I think check judges is the right name.
