### PR TITLE
fix: 23631 Update bytes for hash of a Merkle leaf

### LINKED ISSUE #23631: Update bytes to hash of a merkle leaf
As proposed in #20371, current implementation of `VirtualLeafBytes#writeToForHashing` includes a wrapper for the state item: 

```
message MerkleLeaf {
	oneof {
                Timestamp block_consensus_timestamp = 1;
		BlockItem block_item = 2;
		StateItem state_item = 3;
```

Upon further consideration we decided to exclude `MerkleLeaf` wrapper from the hashing.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR updates how exactly we has Merkle leaf of the state. 

**Related issue(s)**:

Fixes #23631 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java [hunk 1]
```diff
@@ -250,19 +250,10 @@ public void writeToForHashing(final WritableSequentialData out) {
...
-        final int keyLen = Math.toIntExact(kb.length());
-        int innerLen = ProtoWriterTools.sizeOfDelimited(FIELD_LEAFRECORD_KEY, keyLen);
-
         final Bytes vb = valueBytes();
-        if (vb != null) {
-            final int valueLen = Math.toIntExact(vb.length());
-            innerLen += ProtoWriterTools.sizeOfDelimited(FIELD_LEAFRECORD_VALUE, valueLen);
-        }
 
-        ProtoWriterTools.writeTag(out, FIELD_MERKLELEAF_STATEITEM);
```
Comment (thenswan) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java:262]: I think `FIELD_MERKLELEAF_STATEITEM` can be removed if not used anymore

Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java:262]: Done

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/Rehash.java [hunk 2]
```diff
@@ -58,8 +59,11 @@ void reHash(DeserializedSignedState deserializedSignedState) throws Exception {
      * @param deserializedSignedState The deserialized signed state, propagated by the DeserializedSignedStateResolver.
      * @param hashInfo                The hash info object, propagated by the HashInfoResolver.
      */
+    @Disabled("expected to fail in 0.72 due to different leaf bytes to hash "
+            + "(see https://github.com/hiero-ledger/hiero-consensus-node/issues/23631)."
+            + "Should be re-enabled in 0.73")
```
Comment (artemananiev) [inline hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/Rehash.java:64]: Please, file a ticket for this follow-up change and target it to 0.73

File: platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/StateItem.java [hunk 3]
```diff
@@ -50,7 +50,7 @@ public record StateItem(@NonNull Bytes key, @NonNull Bytes value) {
     public static final class StateItemCodec implements Codec<StateItem> {
 
         static final FieldDefinition FIELD_KEY = new FieldDefinition("keyBytes", FieldType.BYTES, false, 2);
-        static final FieldDefinition FIELD_VALUE = new FieldDefinition("keyBytes", FieldType.BYTES, false, 3);
+        static final FieldDefinition FIELD_VALUE = new FieldDefinition("valueBytes", FieldType.BYTES, false, 3);
```
Comment (artemananiev) [inline platform-sdk/swirlds-state-impl/src/main/java/com/swirlds/state/merkle/StateItem.java:53]: Nice catch!

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java]: This comment is outdated, there is no `getSizeInBytesForHashing()` any longer. On one hand, I don't think it makes sense to re-introduce that method just to reference it from this JavaDoc. On the other hand, removing JavaDoc for the current method altogether doesn't look right, either

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+ * <p>This listener collects hashed leaf records and internal node hashes produced by the {@link VirtualHasher}
+ * and flushes them to the underlying {@link VirtualDataSource}.
+ *
+ * <p>To avoid keeping all hashes in memory during a full rehash (which could involve billions of leaves),
+ * this listener flushes data in batches once a threshold ({@code DEFAULT_FLUSH_INTERVAL}) is reached.
+ * It also ensures a final flush is performed when hashing is completed.
+ */
+public class FullLeafRehashHashListener implements VirtualHashListener {
+
+    private static final int DEFAULT_FLUSH_INTERVAL = 500000;
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java]: I know this class isn't related to reconnects, but it probably makes sense to use `VirtualMapConfig.reconnectFlushInterval` here

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+
+    private static final Logger logger = LogManager.getLogger(FullLeafRehashHashListener.class);
+
+    private final VirtualDataSource dataSource;
+    private final long firstLeafPath;
+    private final long lastLeafPath;
+    private List<VirtualLeafBytes> leaves;
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java]: No need to collect / flush leaves

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java [hunk 6]
```diff
@@ -455,6 +472,160 @@ void postInit() {
...
+        final long lastLeafPath = dataSource.getLastLeafPath();
+
+        final ConcurrentBlockingIterator<VirtualLeafBytes> rehashIterator =
+                new ConcurrentBlockingIterator<>(MAX_REHASHING_BUFFER_SIZE);
+        final CompletableFuture<Hash> fullRehashFuture = new CompletableFuture<>();
+        final CompletableFuture<Void> leafFeedFuture = new CompletableFuture<>();
+        if (firstLeafPath < 0 || lastLeafPath < 0) {
+            logger.info(
+                    STARTUP.getMarker(),
+                    "VirtualMap is empty, skipping full rehash. First path: {}, last path: {}",
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java]: No need to log paths here, the VM is empty

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java [hunk 7]
```diff
@@ -455,6 +472,160 @@ void postInit() {
...
+     * only updates hashes for dirty leaves that are already in the in-memory cache,
+     * whereas this method always rehashes every leaf from persistent storage. Because
+     * the number of leaves is very large, this method is deliberately designed to never
+     * load all leaves into memory at once (unlike {@code computeHash()}, which can
+     * safely ignore memory consumption since the cache is already resident).
+     */
+    public void fullLeafRehashIfNecessary() {
+        requireNonNull(records, "Records must be initialized before rehashing");
+
+        // getting a range that is relevant for the data source
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java:496]: Assuming full rehash should only be done at VM initialization, it makes sense to check that VM's and data source's leaf path ranges are identical

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java [hunk 8]
```diff
@@ -455,6 +472,160 @@ void postInit() {
...
+                    rehashIterator.close();
+                    final var message = "Full rehash failed";
+                    logger.error(EXCEPTION.getMarker(), message, exception);
+                    fullRehashFuture.completeExceptionally(new MerkleSynchronizationException(message, exception));
+                })
+                .build()
+                .start();
+
+        // This background thread will be responsible for feeding the iterator with data.
+        new ThreadConfiguration(getStaticThreadManager())
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java]: Does it have to be in a separate thread? Feeding leaves can be done right in the current thread

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java [hunk 9]
```diff
@@ -455,6 +472,160 @@ void postInit() {
...
+        logger.info(STARTUP.getMarker(), "Doing full rehash for the path range: {} - {}", firstLeafPath, lastLeafPath);
+        final FullLeafRehashHashListener hashListener =
+                new FullLeafRehashHashListener(firstLeafPath, lastLeafPath, dataSource, statistics);
+
+        // This background thread will be responsible for hashing the tree and sending the
+        // data to the hash listener to flush.
+        new ThreadConfiguration(getStaticThreadManager())
+                .setComponent("virtualmap")
+                .setThreadName("leafRehasher")
+                .setRunnable(() -> fullRehashFuture.complete(hasher.hash(
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java]: I'm not sure if it can be simplified to something like this:

```java
fullRehashFuture.completeAsync(() -> hasher.hash(...));
```

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/Rehash.java (hunk 2 above)
Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/Rehash.java:64]: Done https://github.com/hiero-ledger/hiero-consensus-node/issues/23654

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java (hunk 8 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java]: Yes, it can be done in the current thread. Fixed.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java (hunk 9 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java]: I refactored this part as well.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java (hunk 7 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java:496]: added asserts

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java (hunk 6 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java]: Fixed the message

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java (hunk 5 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java]: Agreed. I removed leaves collection

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java (hunk 4 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/FullLeafRehashHashListener.java]: Agreed

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualLeafBytes.java]: I replaced the outdated comment with proper javadoc

**Review by mxtartaglia-sl — APPROVED** [review]
