### PR TITLE
Fix `duplicateKeysAndSerialsInSameTxnDoesntThrow` test

### LINKED ISSUE #9057: CryptoApproveAllowanceSuite.approveForAllSpenderCanDelegateOnNFT() failed
### Description

CryptoApproveAllowanceSuite.approveForAllSpenderCanDelegateOnNFT() failed with message:
Expected DELEGATING_SPENDER_CANNOT_GRANT_APPROVE_FOR_ALL, was INVALID_SIGNATURE!

### Steps to reproduce

Run the test.

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### LINKED ISSUE #9058: CryptoApproveAllowanceSuite.duplicateKeysAndSerialsInSameTxnDoesntThrow() failed
### Description

CryptoApproveAllowanceSuite.duplicateKeysAndSerialsInSameTxnDoesntThrow() failed with error:
Wrong precheck status! Expected OK, actual INSUFFICIENT_TX_FEE

### Steps to reproduce

run test

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #9058 
Fixes #9057 

Fixes `duplicateKeysAndSerialsInSameTxnDoesntThrow` and `approveForAllSpenderCanDelegateOnNFT` test

### CODE REVIEW

**Review by iwsimon — DISMISSED** [review]
LGTM

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java [hunk 1]
```diff
@@ -443,11 +443,15 @@ private HapiSpec approveForAllSpenderCanDelegateOnNFT() {
...
+                        // NOTE: This test in mono-service was failing in pre-check before signing requirements
+                        // (the signing requirements are wrong too).
+                        // In new code since we moved these checks to handle, it failed at signature verification.
+                        // To make it fail with same status code, we need to sign with owner.
                         cryptoApproveAllowance()
                                 .payingWith(DEFAULT_PAYER)
                                 .addDelegatedNftAllowance(
                                         OWNER, NON_FUNGIBLE_TOKEN, newSpender, delegatingSpender, true, List.of())
-                                .signedBy(DEFAULT_PAYER, delegatingSpender)
+                                .signedBy(DEFAULT_PAYER, OWNER)
```
Comment (iwsimon) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java:454]: With this change, will it pass in mono code test too?

Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java:454]: Yes Iris, it will pass, because in mono-service the precheck still fails

**Review by iwsimon — APPROVED** [review]
LGTM
