### PR TITLE
Additional reconnect scenarios

### LINKED ISSUE #1270: Additional Reconnect test scenarios
### Note:

- `StartingStateX`: 6 Node State that has 1M crypto accounts, 1M topics, 1K Tokens, 1M token associations, 100 Scheduled transactions. [Link](https://console.cloud.google.com/storage/browser/services-regression-jrs-files/StartFromSavedState/LocalState-1M-Size/6Node_State_With_All_Entities/123/52786?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&project=hedera-regression&prefix=&forceOnObjectsSortingFiltering=false) to the state
- `StartingStateX-15N`: 15 Node State that has 610K Topics, 1715 Files, 615K Accounts, 2330 Tokens, 950K token associations, 100 Scheduled transactions. [Link](https://console.cloud.google.com/storage/browser/services-regression-jrs-files/StartFromSavedState/LocalState-1M-Size/15Node_State_With_All_Entities/3656?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&project=hedera-regression&supportedpurview=project&prefix=&forceOnObjectsSortingFiltering=false) to the state
- Client submits a steady state `1.5K TPS` of  mixed operations during the test.

**Reconnect types:** 
- `Multi Part Reconnect test` : Disconnects one node, but node tries multiple attempts to successfully complete reconnect
- `Multi Node Reconnect test` : Disconnects more than one node at once
- `Interrupted Reconnect` : One node is disconnected from network and during reconnect, it is interrupted

    All the above scenarios can be done using NI or ND reconnect
1. `NI Reconnect` : Network Interrupt Reconnect, in which node is disconnected from network
2. `ND Reconnect` : Node Death Reconnect , in which java process on the node is killed 

- `SB reconnect` : Synthetic Bottleneck reconnect , in which a delay is added to handleTransaction, so that one nodes becomes very slow in handling transactions and falls behind other nodes in the network

###  **6 Node Network** 

- [x] Modify existing reconnect tests that are being tested on 4 node network to 6 node network
- [x] Modify `MixedOps-NDReconnect-1.5k-12m.json`  test to run traffic continuously during the test
- [x] **Multi Part Reconnect test ** : 
1.  Starts all nodes from the `StartingStateX`
2. Disconnect one node from the network for a 20 minutes
3. Let the node reconnect successfully
- [x] **Profile Multi Part Reconnect test **  
Measure time for successful reconnect starting from various state sizes to be loaded. Time to be measured is between the following logs . Profiling data is available at [LINK](https://github.com/hashgraph/hedera-services/issues/1270#issuecomment-822758753)
```
SyncCaller: Starting reconnect in role of the receiver. 
Finished reconnect in the role of the receiver.
```

### **15 Node Network - Single Region**
- [x] **Multi node reconnect test **
1.  Start all nodes from `StartingStateX-15N`
2. Disconnect two nodes from network for a short time
3. Let both the nodes reconnect successfully
- [x] **Multi node reconnect test with multiple reconnect attempts ** 
1.  starts all nodes from `StartingStateX-15N` 
2. Disconnect two nodes from the network for 20 minutes
3. Let both the nodes reconnect successfully 
- [x] **Interrupted Reconnect tests** by disconnecting  one node and multi node
1.  starts all nodes from `StartingStateX-15N` 
2. Disconnect two nodes from the network for 10 minutes
3. Let both the nodes reconnect. While reconnecting interrupt the reconnect and let them reconnect successfully after interrupts 

### **15 Node Network - Multi Region**

- [x] 15 Node NI Reconnect test and 15 Node ND Reconnect multi region-multi node tests by adding netem delays from mainnet
1.  Start all nodes from `StartingStateX-15N`
2. Disconnect two nodes from network for a short time in NI reconnect. Kill the Java process on one node for a short time in ND reconnect
3. Let both the nodes reconnect successfully
- [x] Profile multiregion tests with 15 node network

- [x] Modify existing multi-region tests to disconnect more than 2 nodes
- [x] Clean up validator errors in client

### LINKED ISSUE #1324: Reconnect test for Schedule Transactions
**Summary**
Create the following two scenarios to test Schedule Transactions during reconect.
1. Create a few Scheduled transactions while node is down and after reconnect try to create same scheduled transaction. We expect a response that says schedule transaction exists on reconnected node
2.  Create a few Scheduled transactions while node is down with an expiry of 1 minute, so that they will be expired by the time node gets the state.

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
- Closes #1270  
- Closes #1324  
- Related to https://github.com/swirlds/swirlds-platform-regression/pull/1003

**Summary of the change**:
1. Existing reconnect tests are converted to 6 nodes network, so `ValidateDuplicateTransactionAfterReconnect.java`, `UpdateAllProtectedFilesDuringReconnect.java `, `MixedValidationsAfterReconnect.java` are updated  to use node 0.0.8 as reconnected node 
2. Adds test suites for creating schedules and tokens before reconnect
2. Make `initialBalance` a configurable parameter for LoadTests using `CI_PROPERTIES_MAP`
3. Adds automated workflows for the added reconnect tests. 

Passed tests added:
`GCP-Daily-Comp-Reconnect-6N-1C` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619475638037000
`GCP-Daily-Comp-3NReconnect-15N-1C` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619475438036500
`GCP-Daily-Global-Reconnect-15N-1C` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619471275034800
`ScheduleExpiry-NIReconnect-1-12m` : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1619576004046500

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java [hunk 1]
```diff
@@ -117,7 +117,7 @@ protected HapiApiSpec runCryptoTransfers() {
 								.overridingProps(Map.of("hapi.throttling.buckets.fastOpBucket.capacity", "1300000.0")),
 						reduceFeeFor(CryptoTransfer, 2L, 3L, 3L),
 						cryptoCreate("sender")
-								.balance(initialBalance.getAsLong())
+								.balance((balance) -> settings.getInitialBalance())
```
Comment (anighanta) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java:120]: Any specific reason why a lambda here rather than just a function call?

Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java]: Fixed. Thanks @anighanta !

Comment (anighanta) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java]: I didn't mean to change it. We actually check the function first. Just wondering why

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/SubmitMessagesForReconnect.java [hunk 2]
```diff
@@ -38,7 +38,14 @@
 import static com.hedera.services.bdd.spec.utilops.UtilVerbs.withOpContext;
 import static com.hederahashgraph.api.proto.java.ResponseCodeEnum.BUSY;
 import static com.hederahashgraph.api.proto.java.ResponseCodeEnum.DUPLICATE_TRANSACTION;
+import static com.hederahashgraph.api.proto.java.ResponseCodeEnum.INSUFFICIENT_PAYER_BALANCE;
```
Comment (anighanta) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/SubmitMessagesForReconnect.java:41]: Unused imports

**Review by anighanta — DISMISSED** [review]
LGTM other than some minor changes requested.

**Comment by anighanta** [comment]
There are other reconnect tests. Not sure if we are using them in JRS. But as we moved onto 6 node networks, they might also be updated to point to node 0.0.8. Test like, `ValidateAppPropertiesStateAfterReconnect` , `ValidateExchangeRateStateAfterReconnect`, `ValidateFeeScheduleStateAfterReconnect`, `ValidateApiPermissionStateAfterReconnect`, `UpdateApiPermissionsDuringReconnect`

**Comment by Neeharika-Sompalli** [comment]
> There are other reconnect tests. Not sure if we are using them in JRS. But as we moved onto 6 node networks, they might also be updated to point to node 0.0.8. Test like, `ValidateAppPropertiesStateAfterReconnect` , `ValidateExchangeRateStateAfterReconnect`, `ValidateFeeScheduleStateAfterReconnect`, `ValidateApiPermissionStateAfterReconnect`, `UpdateApiPermissionsDuringReconnect`

They are currently not being used in JRS and they can still be run with the network size 4 if needed until they are added to JRS.  So, I did not modify them.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/SubmitMessagesForReconnect.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/SubmitMessagesForReconnect.java]: Fixed. Thanks

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/CryptoTransferLoadTest.java]: Reverted to lambda as `balanceFn` sets the values in `HapiCryptoCreate.opBodyDef`

**Review by anighanta — DISMISSED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java [hunk 3]
```diff
@@ -46,7 +47,7 @@
 	public static OptionalInt hcsSubmitMessage = OptionalInt.empty();
 	public static OptionalInt hcsSubmitMessageSizeVar = OptionalInt.empty();
 	/** initial balance of account used as sender for performance test transactions */
-	public static OptionalLong initialBalance = OptionalLong.of(ONE_MILLION_HBARS);
+	public static OptionalLong initialBalance = OptionalLong.of(DEFAULT_INITIAL_BALANCE);
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:50]: You added a new constant, does the CI property initialBalance not work?

File: .circleci/config.yml [hunk 4]
```diff
@@ -1308,6 +1308,25 @@ executors:
     working_directory: /repo
 
 workflows:
+  GCP-Personal-Dev:
+    jobs:
+      - build-platform-and-services:
+          filters:
+            branches:
+              only:
+                - developers-branch-to-run-tests
```
Comment (ljianghedera) [inline .circleci/config.yml:1317]: Shall this be changed to `master` for merging to master?

File: .circleci/config.yml [hunk 5]
```diff
@@ -1308,6 +1308,25 @@ executors:
...
+      - jrs-regression:
+          context: Slack
+          result_path: results/Personal
+          config_type: "personal"
+          workflow-name: "GCP-Personal-DevName"
```
Comment (ljianghedera) [inline .circleci/config.yml:1322]: This lines may also need to changes when merging to master,

File: .circleci/config.yml (hunk 4 above)
Comment (Neeharika-Sompalli) [reply .circleci/config.yml:1317]: This should not be run for each commit on master. It is a workflow for developers to easily automate their runs using their personal config. Without this workflow, we need to modify the Daily or Weekly nightly jsons to run tests.

File: .circleci/config.yml (hunk 5 above)
Comment (Neeharika-Sompalli) [reply .circleci/config.yml:1322]: As mentioned above, this will not be run on master. It is workflow for helping devs to run their personal JSON when needed

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java (hunk 3 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:50]: `DEFAULT_INITIAL_BALANCE` will be more clear and aligns with other DEFAULT static variables in the class. This value can be used in any other class. `DEFAULT_INITIAL_BALANCE` is assigned to `ONE_MILLION_HBARS` in `PerfTestLoadSettings`

File: .circleci/config.yml (hunk 4 above)
Comment (ljianghedera) [reply .circleci/config.yml:1317]: The intention is legit, but the implementation is not CircleCi way to do so. IMO, if developers want to run their workflows, either complete new one, or one of existing daily or weekly workflow, they should create a branch on both `hedera-services` repo and `regression` repo. And all the branches won't get interfered with `master` branch at all. Adding these workflows may confuse our understanding of CircleCi workflow, and also make the config.yml more complicated.

File: test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java (hunk 3 above)
Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/LoadTest.java:50]: OK, make sense.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateSchedulesBeforeReconnect.java [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+	private static final AtomicInteger scheduleNumber = new AtomicInteger(0);
+
+	@Override
+	protected List<HapiApiSpec> getSpecsInSuite() {
+		return List.of(
+				runCreateSchedules()
+		);
+	}
+
+	private synchronized HapiSpecOperation generateScheduleCreateOperation() {
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateSchedulesBeforeReconnect.java:67]: nit: I am not sure if `synchronized` is necessary here. For all the operations in this function, they don't change any shared states. The only object need protection is scheduleNumber, which is already defined as AtomicInteger, hence no need to worry this object.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateTokensBeforeReconnect.java [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+	private static final AtomicInteger tokenNumber = new AtomicInteger(0);
+
+	@Override
+	protected List<HapiApiSpec> getSpecsInSuite() {
+		return List.of(
+				runCreateTopics()
+		);
+	}
+
+	private synchronized HapiSpecOperation generateTopicCreateOperation() {
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateTokensBeforeReconnect.java:66]: Same here.

File: .circleci/config.yml (hunk 5 above)
Comment (Neeharika-Sompalli) [reply .circleci/config.yml]: Removed the workflow @ljianghedera

File: .circleci/config.yml (hunk 4 above)
Comment (Neeharika-Sompalli) [reply .circleci/config.yml]: @ljianghedera I see. Sure I removed the workflow.

**Review by ljianghedera — APPROVED** [review]
Overall looks good except some minor comments.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateSchedulesBeforeReconnect.java (hunk 6 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateSchedulesBeforeReconnect.java:74]: Good catch ! I will validate existing reconnect tests with multiple clients and remove `synchronized` in the PR that will be open for #1326
