### PR TITLE
Fix handledSubmitMessageSize and recordStreamQueueSize stats

### LINKED ISSUE #733: avgHdlSubMsgSize stat is not updated after the stat refactoring
**Summary of the defect**
There was a copy-paste issue on lines 61 and 66
https://github.com/hashgraph/hedera-services/blob/d275a47e518b31a30c0689f27acc28d0e4f44479/hedera-node/src/main/java/com/hedera/services/stats/MiscRunningAvgs.java#L57-L66
Also the following function is not hooked up to update the avgHdlSubMsgSize stat when handling submit message transactions
https://github.com/hashgraph/hedera-services/blob/d275a47e518b31a30c0689f27acc28d0e4f44479/hedera-node/src/main/java/com/hedera/services/stats/MiscRunningAvgs.java#L81-L83

**How to reproduce (if possible)**
Run any EET with submit message transactions, the avgHdlSubMsgSize stat is not updated in the csv file(s).

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Closes #733

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/stats/HapiOpCounters.java [hunk 1]
```diff
@@ -128,6 +139,10 @@ private void safeIncrement(
 	) {
 		if (!IGNORED_FUNCTIONS.contains(function)) {
 			counters.get(function).getAndIncrement();
+			if (function == ConsensusSubmitMessage) {
+				int txnBytes = txnCtx.accessor().getTxn().getSerializedSize();
+				runningAvgs.recordHandledSubmitMessageSize(txnBytes);
+			}
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/stats/HapiOpCounters.java:145]: Will putting the hook here also update the stat on receiving and submitting the `SubmitMessage` transactions to the network?

**Review by qnswirlds — APPROVED** [review]
LGTM!
