### PR TITLE
fix: update request size calculation to include 2 bytes per item

### LINKED ISSUE #21923: PublishStreamRequest size calculation incorrect
In the consensus node, we attempt to adhere to a max `PublishStreamRequest`. To do this we calculate the size of each block item that would make up the request, plus some padding for any additional overhead. However, the static overhead of 100 bytes we were using is incorrect. Each block item in the request has an additional overhead of 2 bytes. Because this wasn't accounted for, we exceed the max size. Thus, we should update the calculation to include the additional 2 bytes per item when we estimate the size.

### PR DESCRIPTION
**Pull request by timfn-hg**
**Description**:
This updates the size estimation calculation for pending requests we intend to send to a block node to include an extra 2 bytes of overhead per block item.

Also included are some logging enhancements to aid in debugging sending requests to the block node.

**Related issue(s)**:

Fixes #21923 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by alex-kuzmin-hg — APPROVED** [review]
Approved, but I also will add results of SDLT as ultimate evidence of correctness.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java [hunk 1]
```diff
@@ -652,34 +653,34 @@ public void endTheStreamWith(final PublishStreamRequest.EndStream.Code code) {
...
-                    PublishStreamRequest#protobufSize does the size calculation lazily and thus calling this can incur
-                    a performance penality. Therefore, we only want to log the byte size at trace level.
-                     */
-                    logger.trace(
-                            "{} Sending request to block node (type={}, bytes={})",
-                            this,
-                            request.request().kind(),
-                            request.protobufSize());
-                }
+                logger.debug(
```
Comment (derektriley) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java]: Should we log something different if blockNumber and requestNumber are -1? It may cause confusion.

Comment (timfn-hg) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java]: The only cases in which they will be -1 are for ad hoc end stream calls where the block and request number don't really make sense. I could add a log like: "{} Sending ad hoc request to block node ...." in such a case?

**Review by jsync-swirlds — COMMENTED** [review]
Looks good to me.

**Review by AlfredoG87 — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java (hunk 1 above)
Comment (derektriley) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java]: Yeah let's do that, it will lead to less confusion for someone new looking at the logs at debug level.

Comment (timfn-hg) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java]: Done

**Comment by timfn-hg** [comment]
XTS passing: https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/18953850909 except for an Otter test that is not related and the consensus team is aware of.

**Comment by alex-kuzmin-hg** [comment]
0 errors, all working OK: https://perf.analytics.eng.hashgraph.io/ephemeral/test_runs/timfn/21923-fix-request-size-calculation_AdHoc7_272/report/longevity/podlog_solo-sdlt-n7/
with this branch ref= 1fc9c3d62e0140546265d985c37e9aab44a18050

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java [hunk 2]
```diff
@@ -653,34 +654,46 @@ public void endTheStreamWith(final PublishStreamRequest.EndStream.Code code) {
      * @return true if the request was sent, else false
      */
     public boolean sendRequest(@NonNull final PublishStreamRequest request) {
+        return sendRequest(-1, -1, request);
+    }
+
+    private boolean sendRequest(
+            final long blockNumber, final int requestNumber, @NonNull final PublishStreamRequest request) {
```
Comment (petreze) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java:661]: Would it make sense to introduce a boolean which will differentiate the ad hoc requests in logs. In this way, we can also utilize the block number for `END_OF_BLOCK` as well

Comment (timfn-hg) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java:661]: This is addressed in this PR: https://github.com/hiero-ledger/hiero-consensus-node/pull/21903
```
[0002/localhost:8080/ACTIVE] Sending request (block=10, requestNumber=2) to block node (type=BLOCK_ITEMS, bytes=9156)
[0002/localhost:8080/ACTIVE] Sending request (block=10, requestNumber=3) to block node (type=END_OF_BLOCK, bytes=4)
```

There is some formatting differences, but those will be reconciled once this PR is merged into it.

Comment (petreze) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/blocks/impl/streaming/BlockNodeConnection.java:661]: Ah I see, great!
