### PR TITLE
Make tipset algorithm work with single node network.

### LINKED ISSUE #7607: Tipset algorithm does not work for size 1 network
Reported by Michael, but easily reproducible locally. No events reach consensus using the tipset algorithm in a size one network.

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #7607

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/StaticValidators.java [hunk 1]
```diff
@@ -63,33 +60,34 @@ public static boolean isValidTimeCreated(final EventImpl event) {
...
      */
-    public static boolean isParentDataValid(final BaseEvent event) {
-        final BaseEventHashedData hashedData = event.getHashedData();
-        final Hash spHash = hashedData.getSelfParentHash();
-        final Hash opHash = hashedData.getOtherParentHash();
-        final boolean hasSpHash = spHash != null;
-        final boolean hasOpHash = opHash != null;
-        final boolean hasSpGen = hashedData.getSelfParentGen() >= GraphGenerations.FIRST_GENERATION;
-        final boolean hasOpGen = hashedData.getOtherParentGen() >= GraphGenerations.FIRST_GENERATION;
+    public static GossipEventValidator isParentDataValid(final int networkSize) {
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/StaticValidators.java:68]: would you be opposed to renaming the method to `getParentDataValidator` or similar? The `is` verbiage implies returning a boolean

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/StaticValidators.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/validation/StaticValidators.java:68]: renamed to `buildParentValidator`

**Review by alittley — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]
