### PR TITLE
ci(workflow-fix): upload failure artifacts on flaky otter tests

### LINKED ISSUE #24907: Upload failure artifacts on flaky otter tests
Upload failure artifacts on flaky otter tests

### PR DESCRIPTION
**Pull request by andrewb1269**
**Description**:

Update the flaky otter tests to publish the failed artifacts.

**Related Issue(s)**:

Fixes #24907

**Testing**:

✅ Successful test [here](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/24249903755).

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerTestEnvironment.java [hunk 1]
```diff
@@ -74,7 +73,14 @@ public ContainerTestEnvironment(
 
         try {
             if (Files.exists(rootOutputDirectory)) {
-                FileUtils.deleteDirectory(rootOutputDirectory);
+                int runIndex = 1;
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerTestEnvironment.java]: nit: it would be nice to put this in a utility method so it does not have to be repeated, but not required.

Comment (andrewb1269) [reply platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/container/ContainerTestEnvironment.java]: Updated to a separate utility function called `prepareOutputDirectory`

**Review by poulok — APPROVED** [review]
