### PR TITLE
fix: use floating point numbers for calculating percentage in #checkSignatures(SignedState)

### LINKED ISSUE #16879: Unexpected exception: "DefaultStateSnapshotManager: State written to disk for round NNN did not have enough signatures.", supplied with wrong percentage example
### Description

current "develop" (hash f8e912a3fff6e9b1366400a4a009318165936c36 ) reproduces old bug https://github.com/hashgraph/hedera-services/issues/11422

I'm creating new one because the Reopening action is not enabled.

I see it on HashSphere:

```
2024-11-26 22:00:17.855 1995     ERROR EXCEPTION        <<scheduler StateSnapshotManager>> DefaultStateSnapshotManager: State written to disk for round 958 did not have enough signatures.
This log adds debug information for #11422.
Pre-check weight: 1500/3500 (0.000000%)  Post-check weight: 1500/3500 (0.000000%)
Pre-check threshold: false   Post-check threshold: false {} [com.swirlds.logging.legacy.payload.InsufficientSignaturesPayload]
```

that has 2 sides of a problem, 
1) according to evaluation of https://github.com/hashgraph/hedera-services/issues/11422  it should not be thrown,as we have sufficient signatures
2) its percentage output is wrong

### Steps to reproduce

To run NFT transfer test on low-profile node, e.g. xsmall GoogleCloud

### Additional context

_No response_

### Hedera network

other

### Version

v0.56

### Operating system

Linux

### PR DESCRIPTION
**Pull request by timfn-hg**
**Description**:
This fixes a bug where the output in an error message that calculated the weight as a percentage was using integers instead of floating point numbers. This caused the percent to always be 0%.

**Related issue(s)**:

Fixes #16879 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java [hunk 1]
```diff
@@ -210,6 +210,10 @@ private void checkSignatures(@NonNull final SignedState reservedState) {
 
         // don't log an error if this is a freeze state. they are expected to lack signatures
         if (reservedState.isFreezeState()) {
+            final double signingWeightPercent = ((double) reservedState.getSigningWeight())
+                    / reservedState.getAddressBook().getTotalWeight()
+                    * 100;
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java:215]: Minor nits for all the computations in this fix:
1. Might use `100.`. I'm sure javac will auto-expand the integer to double at compile time, but having all values as `double` makes the intent clearer to human readers.
2. Might group the expressions as `((double) x / y) * 100.`. Again, the current expression w/o any parentheses makes sense given the operators precedence in Java, but the `(/)*` grouping is easier to understand for a human w/o having to remember or double-check the operators precedence.

**Review by anthony-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java (hunk 1 above)
Comment (timfn-hg) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java:215]: Just to make sure I am following you... this is what you are proposing:
```
final double signingWeightPercent = (((double) reservedState.getSigningWeight())
        / ((double) reservedState.getAddressBook().getTotalWeight()))
        * 100.0;
// and...
final double signingWeight1Percent = (((double) signingWeight1) / ((double) totalWeight1)) * 100.0;
```

Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java:215]: Overall, yes, that looks super clear. I'd even be okay with a slightly simpler version of literally `( (double) x / y) * 100.0` w/o extra parentheses around `(double) x` and w/o converting the `y` to `double`. But I still like your version where everything explicitly made a `double` and there's no doubts about the order of operations at all. +1!

Comment (timfn-hg) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/DefaultStateSnapshotManager.java]: Done!

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]
