### PR TITLE
fix(21838): fix the testIntake wiring between consensus and the orphann buffer

### LINKED ISSUE #21838: failure in `ConsensusEngineContractTest#staleEventsTest` with seed `-3833760021351545904L`
Test failure in `ConsensusEngineContractTest#staleEventsTest` with seed `-3833760021351545904L` verified in main. [failure](https://scans.gradle.com/s/55wjelthqk7js/tests/task/:swirlds-platform-core:test/details/com.swirlds.platform.consensus.ConsensusEngineContractTest/staleEventsTest()?expanded-stacktrace=WyIwIl0&top-execution=1).

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
The issue being fixed here is the following:  In a direct scheduler pipeline, when the orphan buffer releases an event to the consensus component, the consensus component may output an `EventWindow` that feeds back to the same orphan buffer, which might then release a second batch of events. Because it's a DIRECT scheduler (synchronous, single-threaded),  the new list starts processing immediately, interrupting the previous list iteration.
This means a child event from the new list can be processed before its parent from the original list, breaking topological order.
This pr fixes the test intake by making it use Sequential schedulers and the deterministic wiring mode. It also adds support in the wiring model to perform all work waiting in the queue, instead of relying on given tics to advance work.

Fixes #21838

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/consensus/TestIntake.java [hunk 1]
```diff
@@ -122,6 +127,46 @@ public TestIntake(@NonNull final PlatformContext platformContext, @NonNull final
...
+     * It is done using binding a custom lambda that is solving an edge case that is particularly important when using direct task schedulers:
+     * In a direct scheduler pipeline, when the orphan buffer releases an event to the consensus component, the consensus component may output an `EventWindow` that feeds back to the same orphan buffer, which might then release a second batch of events. Because it's a DIRECT scheduler (synchronous, single-threaded),  the new list starts processing immediately, interrupting the previous list iteration.
+     * This means a child event from the new list can be processed before its parent from the original list, breaking topological order.
+     *
+     *  This method solves this issue using a queue of events and a flag indicating that there is a current integration in progress.
+     *  Only one iteration at the time will feed elements to consensus, allowing us to maintain the topological order.
+     * @param orphanBufferWiring the orphan buffer wiring
+     * @param consensusEngineWiring the consensus engine wiring
+     */
+    private static void wireOrphanBufferAndConsensusEngine(
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/consensus/TestIntake.java]: - I think we should use deterministic wiring for all components, not just these two
- Maybe I am misunderstanding something, but I don't think this needs to be so complicated and custom, take a look at how its done in the `TurtleNode`

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/DeterministicWiringModel.java [hunk 2]
```diff
@@ -174,4 +174,19 @@ public void stop() {
...
+    /**
+     * Check if there is any pending work in the current or next cycle.
+     *
+     * @return true if there is pending work, false otherwise
+     */
+    public boolean hasPendingWork() {
+        return !currentCycleWork.isEmpty() || !nextCycleWork.isEmpty();
+    }
+
+    public void doAllWork() {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/DeterministicWiringModel.java:190]: javadoc

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java [hunk 3]
```diff
@@ -65,53 +66,49 @@ public WiringModelBuilder withDefaultPool(@NonNull final ForkJoinPool defaultPoo
...
-     * Set if the health monitor should be enabled. Default is true.
+     * disables the health monitor.
      *
-     * @param healthMonitorEnabled whether to enable the health monitor
      * @return this
      */
     @NonNull
-    public WiringModelBuilder withHealthMonitorEnabled(final boolean healthMonitorEnabled) {
-        this.healthMonitorEnabled = healthMonitorEnabled;
+    public WiringModelBuilder disabledHealthMonitor() {
```
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java]: nit: should be `disableHealthMonitor()`

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java [hunk 4]
```diff
@@ -65,53 +66,49 @@ public WiringModelBuilder withDefaultPool(@NonNull final ForkJoinPool defaultPoo
...
-     * Set if hard backpressure should be enabled. Default is false.
+     * Sets hard backpressure to enabled. Default is false.
      *
-     * @param hardBackpressureEnabled whether to enable hard backpressure
      * @return this
      */
     @NonNull
-    public WiringModelBuilder withHardBackpressureEnabled(final boolean hardBackpressureEnabled) {
-        this.hardBackpressureEnabled = hardBackpressureEnabled;
+    public WiringModelBuilder enabledHardBackpressure() {
```
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java]: nit: should be `enableHardBackpressure()`

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java [hunk 5]
```diff
@@ -65,53 +66,49 @@ public WiringModelBuilder withDefaultPool(@NonNull final ForkJoinPool defaultPoo
...
      * called, the JVM will not automatically exit due to lack of non-daemon threads until {@link WiringModel#stop()} is
      * called.
      *
-     * @param jvmAnchorEnabled whether to enable the JVM anchor
      * @return this
      */
     @NonNull
-    public WiringModelBuilder withJvmAnchorEnabled(final boolean jvmAnchorEnabled) {
-        this.jvmAnchorEnabled = jvmAnchorEnabled;
+    public WiringModelBuilder jvmAnchorEnabled() {
```
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java]: nit: should be `enabledJvmAnchor`

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java [hunk 6]
```diff
@@ -191,6 +188,23 @@ public WiringModelBuilder withUncaughtExceptionHandler(
         return this;
     }
 
+    /**
+     * Applies the configuration contained in the {@link WiringConfig} instance.
+     *
+     * @return this
+     */
+    @NonNull
+    public WiringModelBuilder withComponentConfig(@NonNull final WiringConfig wiringConfig) {
```
Comment (poulok) [inline platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java]: If some methods are changing to be worded more directly, and not in the "with" pattern, all should be changed. And if you are going to change all of them, probably better to do it in a separate PR

**Review by lpetrovic05 — DISMISSED** [review]

File: platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java (hunk 6 above)
Comment (mxtartaglia-sl) [reply platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java]: I agree that a different pr is better. My plan was not to change all of them; using "with" for the ones that receive a parameter seems right IMO. I was only going to change the ones that no longer needed a parameter, since they set a flag. Given that deterministic is used here, I just made the change.
Is it okay to just leave it here and rename enabled to 'enable' and disabled to 'disable'?

Comment (poulok) [reply platform-sdk/swirlds-component-framework/src/main/java/com/swirlds/component/framework/model/WiringModelBuilder.java]: yes that's fine with me
