### PR TITLE
09394 fix failing tests in create2 operation suite

### LINKED ISSUE #9394: Fix any failing tests left in Create2OperationSuite

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

This PR enables most of the tests that are left in `Create2OperationSuit`. It resolves problems that are related to missing or incorrect child records.

There are three significant modifications:
- Update contract create child record, to match record fields in mono.
- Add `ContractCreateRecordBuilder` when hollow account is merged.
- Add a way to revert child records on frame message revert.

**Related issue(s)**:

Fixes #9394
This modification also overlaps with #9431 

**Notes for reviewer**:

The first thing I tried was to build `ContractCreateTransactionBody` instead of `CryptoCreateTransactionBody`, and dispatch a child transaction. But this way I had problems with initCode and charging the parent contract instead of the payer, even if the payer was set correctly in the context of the child transaction.
So I decided to stick with `CryptoCreateTransaction` and add the missing fields in the recordBuilder.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by netopyr — APPROVED** [review]
LGTM in regards to `hedera-app`

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java [hunk 1]
```diff
@@ -298,4 +318,18 @@ private void dispatchAndMarkCreation(
 
         tokenServiceApi.markAsContract(accountId, autoRenewAccountId);
     }
+
+    public void externalizeHollowAccountMerge(@NonNull ContractID contractId, @Nullable Bytes evmAddress) {
+        var recordBuilder = context.addRemovableChildRecordBuilder(ContractCreateRecordBuilder.class);
+        recordBuilder
+                .contractID(contractId)
+                // add dummy transaction, because SingleTransactionRecord require NonNull on build
+                .transaction(Transaction.newBuilder()
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java:327]: I think this will need to be a synthetic `ContractUpdate`; but that will be much easier to test once [this PR](https://github.com/hashgraph/hedera-services/pull/9513) is merged.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, very nice work @JivkoKelchev 🙏
