### PR TITLE
fix: ThreadLocal issue in LongListDisk when multiple lists are used

### LINKED ISSUE #16860: ThreadLocal issue in LongListDisk when multiple lists are used
`LongListDisk` has a ThreadLocal for temporary byte buffers, which are used to read or write index chunks from / to the temp file. This local is initialized lazily:

```java
    private ByteBuffer initOrGetTransferBuffer() {
        ByteBuffer buffer = TRANSFER_BUFFER_THREAD_LOCAL.get();
        if (buffer == null) {
            buffer = ByteBuffer.allocate(memoryChunkSize).order(ByteOrder.nativeOrder());
            TRANSFER_BUFFER_THREAD_LOCAL.set(buffer);
        } else {
            // clean up the buffer
            buffer.clear();
        }
        return buffer;
    }
```

When a new buffer is created, its size is `memoryChunkSize`. This size is read from a config and it's the same for all long lists in production. However, in tests, chunk sizes may be different across long lists, which may result in test failures.

Here is what may happen:

* Test 1: creates a long list with memoryChunkSize = 1000. The thread local field is initialized with a buffer of this size
* Test 2: on the same thread creates a long list with memoryChunkSize = 100
* When the long list in test 2 is closed, it gets the buffer, fills it with zeroes and writes to the file:

```java
    protected void closeChunk(@NonNull final Long chunk) {
        final ByteBuffer transferBuffer = initOrGetTransferBuffer();
        fillBufferWithZeroes(transferBuffer);
        try {
            currentFileChannel.write(transferBuffer, chunk);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        freeChunks.add(chunk);
    }
```

* `fillBufferWithZeroes()` resets buffer's limit to its capacity, that is, to 1000. When such a buffer is written to the file, 1000 bytes are written, but only 100 should be

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
This PR fixes ThreadLocal issue in `LongListDisk` when multiple lists are used. See #16860 for more details.

**Related issue(s)**:
Fixes #16860

### CODE REVIEW

**Review by imalygin — DISMISSED** [review]

File: platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java [hunk 1]
```diff
@@ -194,7 +194,7 @@ private static void fillBufferWithZeroes(ByteBuffer transferBuffer) {
 
     private ByteBuffer initOrGetTransferBuffer() {
         ByteBuffer buffer = TRANSFER_BUFFER_THREAD_LOCAL.get();
-        if (buffer == null) {
+        if (buffer == null || buffer.capacity() != memoryChunkSize) {
```
Comment (artemananiev) [inline platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java:197]: It can be done even better. `buffer.capacity()` doesn't have to be equal to `memoryChunkSize`, it has to be greater or equal. When it's greater, we need to make sure buffer limit is never reset, e.g. `buffer.clear()` is not called like it is today in `LongListDisk.fillBufferWithZeroes()`.

So the proposal is:
* Change the condition above to be greater or equal rather than equal
* Set buffer limit to memoryChunkSize in the end of `initOrGetTransferBuffer()`
* Inspect all calls to `buffer.clear()` and replace them with `setPosition(0)` + `setLimit(memoryChunkSize)`

Comment (thenswan) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: https://github.com/hashgraph/hedera-services/pull/16962/commits/9bda90b0ab51806f2342aafdcf08f283b2b41b61

Comment (thenswan) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: Actually, I merged `develop`, and it already contains the fix as you describe it, which came from https://github.com/hashgraph/hedera-services/pull/16962, so this PR will contain only a test.

Comment (thenswan) [reply platform-sdk/swirlds-merkledb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java]: @artemananiev actually, I merged `develop`, and it already contains the fix as you describe it, which came from https://github.com/hashgraph/hedera-services/pull/16962, so this PR will contain only a test.

**Review by artemananiev — APPROVED** [review]
