### PR TITLE
fix: 16322 Extracted platform-related functionality from `MerkleStateRoot` into `PlatformMerkleStateRoot`.

### LINKED ISSUE #16322: Refactor `MerkleStateRoot` - extract lifecycle-related code to a separate class
Currently `MerkleStateRoot` has two responsibilities: 
- it's an entry point to get access to the state (represented by `com.swirlds.state.State` interface)
- it's a bridge between the platform and the app (represented by 
`com.swirlds.platform.system.SwirldState`)

These two functionalities can and should be in the separate classes. In fact, it's a pre-requisite for #16223 Without this separation it will not be possible to define clear boundaries between `swirlds-state-impl` module and the rest of the platform.

So, the final goal of this ticket is to move the implementations of `com.swirlds.platform.system.SwirldState` methods to a separate class.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR splits `MerkleStateRoot` into two classes `MerkleStateRoot` and `PlatformMerkleStateRoot`.

Here is how the class diagram looks like:
image

All functionality related to the interaction between the platform and the app has been migrated to `PlatformMerkleStateRoot`. This class also implements the `MerkleRoot` interface, which will eventually be removed (https://github.com/hashgraph/hedera-services/issues/16436).

`MerkleStateRoot` is now focused solely on state interactions. It implements the `com.swirlds.state.State` interface, which serves as a gateway to the state content, and the `com.swirlds.common.merkle.MerkleInternal` interface, indicating that this is a Merkle tree implementation.

Also, `MerkleStateRoot` is now an abstract class because, to determine the current round, we need to extract it from the consensus snapshot, which resides in the platform context. As the name suggests, the platform context belongs to the `swirlds-platform-core` module. Therefore, I had to defer that logic to the concrete implementation.

`TestMerkleStateRoot` is used to test purposes and its implementation of `getCurrentRound()` always return 0. 

**Related issue(s)**:

Fixes #16322 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileReader.java [hunk 1]
```diff
@@ -103,7 +104,7 @@ public static List<SavedStateInfo> getSavedStateFiles(
         final SignedState newSignedState = new SignedState(
                 configuration,
                 CryptoStatic::verifySignature,
-                normalizedData.state(),
+                (MerkleRoot) normalizedData.state(),
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileReader.java:107]: why is this being cast? does the signed state need to change?

Comment (imalygin) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/snapshot/SignedStateFileReader.java:107]: This is a temporary fix. We have a ticket for a final solution about `MerkleRoot` interface - https://github.com/hashgraph/hedera-services/issues/16436. In this case we need `MerkleRoot` instance and `PlatformMerkleStateRoot` _is_ an instance of `MerkleRoot`, so I don't anticipate any issues here.

**Review by lpetrovic05 — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]

**Review by artemananiev — DISMISSED** [review]

**Review by lpetrovic05 — APPROVED** [review]

**Review by rbarkerSL — APPROVED** [review]
Approval applies to
- hedera-node/hedera-app/src/main/java/module-info.java
- hedera-node/test-clients/src/main/java/module-info.java
- platform-sdk/swirlds-platform-core/build.gradle.kts
- platform-sdk/swirlds-platform-core/src/main/java/module-info.java
- platform-sdk/swirlds-state-impl/src/main/java/module-info.java

**Review by lpetrovic05 — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ReadableStoreFactory.java [hunk 2]
```diff
@@ -136,7 +136,7 @@ private static Map<Class<?>, StoreEntry> createFactoryMap() {
      */
     public ReadableStoreFactory(@NonNull final State state) {
         this.state = requireNonNull(state, "The supplied argument 'state' cannot be null!");
-        if (state instanceof MerkleStateRoot merkleStateRoot) {
+        if (state instanceof PlatformMerkleStateRoot merkleStateRoot) {
             this.versionFactory = merkleStateRoot.getVersionFactory();
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ReadableStoreFactory.java:140]: Why was `getVersionFactory()` removed from `MerkleStateRoot`?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java [hunk 3]
```diff
@@ -231,7 +232,7 @@ public StateChangesValidator(
                         metrics),
                 DiskStartupNetworks::new,
                 NodeId.of(0L));
-        this.state = (MerkleStateRoot) hedera.newMerkleStateRoot();
+        this.state = (PlatformMerkleStateRoot) hedera.newMerkleStateRoot();
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java:235]: I'm confused why there are so many changes to the `MerkleStateRoot` interface. Doing so requires changes like we see here, where we go from an interface to something _more_ specific, despite this not being a platform test of any kind. What is the advantage of these changes?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ReadableStoreFactory.java (hunk 2 above)
Comment (imalygin) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ReadableStoreFactory.java:140]: Because this functionality is needed by the platform only. It doesn't have to be a part of the state.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java (hunk 3 above)
Comment (imalygin) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/StateChangesValidator.java:235]: The fundamental problem with the current `MerkleStateRoot` implementation is that it plays two roles:
- a gateway between the app and the platform
- Merkle-tree-based implementation of the State API

This PR partially addresses that - it separates platform-related code from the state implementation. Note that there is a follow-up ticket to refactor `swirlds-platform-core` further and get rid of `PlatformMerkleStateRoot`
https://github.com/hashgraph/hedera-services/issues/16568. 

Once this PR is merged and this , Block Node will be able to use `swirlds-state-api` and `swirlds-state-impl` to work with the state, and there will be no need to depend on `swirlds-platform-core`. This PR is a part of a broader effort - https://github.com/hashgraph/hedera-services/issues/15574 - which has it as the end goal.

**Review by mhess-swl — APPROVED** [review]
Looks good for services ✅

**Review by thenswan — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]
