### PR TITLE
fix: block stream translators - resolve flaky receipt mismatches

### LINKED ISSUE #20489: Test flake: `StreamValidationTest`
A run of `hapiTestMisc` on the `20160-separate-feb-metrics branch` produced the following [error](https://scans.gradle.com/s/aeujeqvmipu52):

```
    2025-07-30 20:42:25.517 <hc> ERROR  158  StreamValidationOp - Block stream validation error	
    org.opentest4j.AssertionFailedError: 1 differences found between generated and translated records	
    	
    ---- ConsensusCreateTopic DIFFERED (TRANSACTION_RECORD_MISMATCH) ----	
    Mismatched field counts  (expected from generated but did not find in translated [topicID]) between expected status: SUCCESS	
    exchangeRate {
```

We haven't been able to reproduce it, nor understand why there seems to be a state change that wasn't published. Reexamination of the hapi translator code suggests there are no errors in the translator code, but instead stems from not having a state change containing the topic ID to begin with. 

Trying to recreate it locally is probably our best bet.

### PR DESCRIPTION
**Pull request by AlexKehayov**
**Description**:
Fixes flaky TransactionRecordParityValidator failures where block stream validation reports mismatches between generated and translated records.

Root cause:
BaseTranslator.nextCreatedNum() returns entity numbers in ascending sorted order. When multiple entities of the same type are created in a single transactional unit (e.g., an auto-created account 1946 and a contract 1970), the translator for the contract pops 1946 instead of 1970, producing a wrong contractNum in the receipt. Similarly, TopicCreateTranslator could get the wrong topic number and fail to match any state change, leaving topicID missing from the receipt.

Fix:
- Added BaseTranslator.consumeCreatedNum(type, num) which removes a specific entity number from the list instead of blindly taking the first sorted entry.
- ContractCreateTranslator now consumes the authoritative contractNum from the EVM result, and falls back to the EVM result's contract ID when no matching state change is found — replacing the previous hollow-account fallback that crashed with "Field contractID/adminKey is null" for normal contract creations.
- TopicCreateTranslator finds the actual topic from state changes first, then consumes that specific number.
- Added regression tests proving the root cause and the fix.

Fixes #20489

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/ContractCreateTranslator.java [hunk 1]
```diff
@@ -128,18 +128,10 @@ public SingleTransactionRecord translate(
                                 .contractIdOrThrow()
                                 .contractNumOrThrow();
                         if (baseTranslator.entityCreatedThisUnit(contractNum)) {
-                            long createdNum = baseTranslator.nextCreatedNum(ACCOUNT);
-                            if (contractNum != createdNum) {
```
Comment (petreze) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/ContractCreateTranslator.java:132]: Don't we need to keep all of these validations in the new `consumeCreatedNum()` method?

Comment (AlexKehayov) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/ContractCreateTranslator.java:132]: consumeCreatedNum removes the correct number directly. If the number isn't found, it logs an error and returns false. The `> 1000` branch was actually the root cause of the bug and the `<= 1000` branch was a workaround that the new approach handles.

Comment (petreze) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/translators/impl/ContractCreateTranslator.java:132]: Makes sense 👍
