### PR TITLE
Only clear memo in `TokenUpdateLogic` if client code can signal unset vs empty

### LINKED ISSUE #6268: 0.38 `TokenUpdate` no longer supports clearing `memo` field
### Description

On previewnet, a `TokenUpdateTransactionBody` whose `memo` is set to an empty `string` no longer erases the token's memo.

h/t bugbytes

### Steps to reproduce

Submit a `TokenUpdate` w/ empty `memo` targeting a token with a non-empty `memo`.

The token's `memo` will be unchanged.

### Additional context

_No response_

### Hedera network

previewnet

### Version

0.38.0

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #6268 
 - Adds a `boolean mergeUnsetMemoFromExisting` flag to `TokenUpdateLogic.updateToken()` so that when client code cannot properly signal the difference between an _unset_ `memo` field and an _empty_ `memo` field, we don't unconditionally clear the token's existing memo.
 - This is relevant when the client code is an `updateToken()` system contract, whose current ABI does not let it distinguish between a contract (1) leaving the `memo` field unset and (2) explicitly setting `memo = ""` to erase the memo.

### CODE REVIEW

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogic.java [hunk 1]
```diff
@@ -73,11 +75,37 @@ public TokenUpdateLogic(
...
+     * @param now the current consensus time
+     * @param mergeUnsetMemoFromExisting whether to preserve the token's memo if the transaction memo is unset
+     */
+    public void updateToken(TokenUpdateTransactionBody op, long now, boolean mergeUnsetMemoFromExisting) {
         final var tokenID = tokenValidityCheck(op);
         if (op.hasExpiry()) {
             validateTrueOrRevert(validator.isValidExpiry(op.getExpiry()), INVALID_EXPIRATION_TIME);
         }
         MerkleToken token = tokenStore.get(tokenID);
+        final var isOpMemoUnset = !op.hasMemo() || op.getMemo().getValue().length() == 0;
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogic.java:104]: Why do we need this condition `op.getMemo().getValue().length() == 0` . Shouldn't `!op.hasMemo()` be enough ?

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !
