### PR TITLE
Fix zip file security vulnerability issues.

### LINKED ISSUE #1434: 1428 child-issue: Clean up SonarCloud security issues
Related to #1428

Resolve 2 security vulnerabilities in SonarCloud https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false&types=VULNERABILITY

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #1434

**Summary of the change**:

1. Added the checks to prevent zip file security vulnerabilities;

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Changes LGTM. But I think
1. We should make this class `final`
2. We should add a test for the `unzip` function

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java [hunk 1]
```diff
@@ -68,14 +68,17 @@ public static void unzip(byte[] bytes, String dstDirectory) throws IOException {
 		ZipEntry entry = zipIn.getNextEntry();
 		while (entry != null) {
 			String filePath = dstDirectory + File.separator + entry.getName();
+			File fileOrDir = new File(filePath);
```
Comment (rbair23) [inline hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:71]: I prefer to use final variables where possible since it aids in reading code. With non-final vars, I don't know if they get modified later in the code or not. If they're final, then I know they don't get changed anywhere else.

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java [hunk 2]
```diff
@@ -68,14 +68,17 @@ public static void unzip(byte[] bytes, String dstDirectory) throws IOException {
...
+			filePath = fileOrDir.getCanonicalPath();
+			if(!filePath.startsWith(destDir.getCanonicalPath() + File.separator)) {
+				throw new IllegalArgumentException("Zip file entry " + filePath + " has potential security risk");
```
Comment (rbair23) [inline hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:74]: Let's modify the comment so it doesn't say "security risk", but just says something like "the supplied path was invalid. Only specify a filePath with a full canonical path name" or something similar (you can come up with a better text).

Let's also make sure to write the tests including the negative tests to make sure this code works as expected and throws when needed.

**Review by rbair23 — CHANGES_REQUESTED** [review]

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java (hunk 1 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java]: Yes, changed as suggested.

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java (hunk 2 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java]: Re-worded the description and added test cases.

**Review by abhishek-hedera — APPROVED** [review]

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java [hunk 3]
```diff
@@ -58,24 +58,28 @@ private static void extractSingleFile(ZipInputStream inputStream, String filePat
...
+			final File fileOrDir = new File(filePath);
+			filePath = fileOrDir.getCanonicalPath();
+			if(!filePath.startsWith(destDir.getCanonicalPath() + File.separator)) {
+				throw new IllegalArgumentException("Zip file entry has invalid path " + filePath +
+						". Only specify a filePath with correct canonical path name.");
+			}
 			if (!entry.isDirectory()) {
-				File newFile = new File(filePath);
 				log.info("create file {}", filePath);
 				extractSingleFile(zipIn, filePath);
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:79]: need test

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java [hunk 4]
```diff
@@ -58,24 +58,28 @@ private static void extractSingleFile(ZipInputStream inputStream, String filePat
...
 			} else {
-				File dir = new File(filePath);
-				log.info("create sub dir " + dir);
-				dir.mkdir();
+				log.info("create sub dir " + fileOrDir);
+				fileOrDir.mkdir();
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:82]: need test

File: hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+		});
+	}
+
+	@Test
+	public void unzipSuccessfully() throws Exception {
+		final String zipFile = "src/test/resources/testfiles/updateFeature/update.zip";
+		final byte[] data = Files.readAllBytes(Paths.get(zipFile));
+		final String dstDir = "./temp";
+
+		UnzipUtility.unzip(data, dstDir);
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java:49]: Should wrap it up with `assertDoesNotThrow`

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java [hunk 6]
```diff
@@ -31,7 +31,7 @@
 import java.util.zip.ZipEntry;
 import java.util.zip.ZipInputStream;
 
-public class UnzipUtility {
+public final class UnzipUtility {
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:35]: SonarCloud also complains about a code smell of an implicit public constructor. We could add a private constructor to hide this implicit public one and just do a throw there
This is for your reference
https://androidhiro.com/source/android/example/java-private-constructor-checker/1955

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Please see inline comments

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java (hunk 3 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:79]: The test cases to cover these lines are in MerkleAccountPropertyTest

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java (hunk 4 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:82]: Same here.

File: hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java (hunk 5 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java:49]: Done

File: hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java (hunk 6 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/utils/UnzipUtility.java:35]: Added the default private constructor. None of the approaches mentioned in the reference works. I don't think we  want to introduce the package proposed in this article to have `PrivateConstructorChecker` for the test coverage. 

I will dig to see if there is other way to do it.

File: hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+	@Test
+	public void privateConstructorShallThrowException() {
+		Constructor<?> ctor;
+		try {
+			ctor = UnzipUtility.class.getDeclaredConstructor();
+			ctor.setAccessible(true);
+
+			ctor.newInstance();
+		} catch (Exception e) {
+			IllegalStateException cause = (IllegalStateException) e.getCause();
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java:46]: nit: here you should catch the specific `IllegalStateException` instead of a generic `Exception`, so you can avoid the unnecessary cast.

**Review by qnswirlds — APPROVED** [review]
LGTM now

File: hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java (hunk 7 above)
Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java:46]: If doing so, catching `IllegalStateException` alone won't work, we need to also catch all other exception types that can be thrown by `getDeclaredConstructor` and `newInstance`. Essentially it's something like this:

```
		try {
			ctor = UnzipUtility.class.getDeclaredConstructor();
			ctor.setAccessible(true);

			ctor.newInstance();
		} catch (IllegalStateException | NoSuchMethodException | InstantiationException | InvocationTargetException | IllegalAccessException e) {
			IllegalStateException cause = (IllegalStateException) e.getCause();
			assertEquals("UnzipUtility is an utility class. Shouldn't create any instance!", cause.getMessage());
		}

```
A cast is still required. So for a test case, I guess it's probably a little overkill.

Comment (qnswirlds) [reply hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java:46]: hmm, in that case the `cast` is not quite right, because what if you really received other type of `Exception`? Then the correct solution should be catching `IllegalStateException` for the assertion then catch other generic `Exception` just to ignore for the passing of the test.

Comment (ljianghedera) [reply hedera-node/src/test/java/com/hedera/services/utils/UnzipUtilityTest.java]: Yeah, should be something like above updated.

**Review by qnswirlds — APPROVED** [review]

**Review by abhishek-hedera — APPROVED** [review]
LGTM
