### PR TITLE
fix: revert recycle-bin store location

### LINKED ISSUE #13334: Revert recycle bin location change
The change of the recycle bin location produced an error while executing related migration code

From @dalvizu 
```
sudo docker logs swirlds-node
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> BEGIN USER IDENT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
uid=2000(hedera) gid=2000(hedera) groups=2000(hedera)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< END USER IDENT   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Exception in thread "main" java.io.UncheckedIOException: java.nio.file.AtomicMoveNotSupportedException: data/saved/swirlds-recycle-bin -> data/recycle-bin: Invalid cross-device link
	at com.swirlds.common.io.utility.FileUtils.rethrowIO(FileUtils.java:73)
	at com.swirlds.common.io.filesystem.internal.FileSystemManagerImpl.<init>(FileSystemManagerImpl.java:108)
	at com.swirlds.common.io.filesystem.internal.FileSystemManagerFactoryImpl.createFileSystemManager(FileSystemManagerFactoryImpl.java:58)
	at com.swirlds.common.context.DefaultPlatformContext.<init>(DefaultPlatformContext.java:59)
	at com.swirlds.platform.builder.PlatformBuilder.buildPlatformContext(PlatformBuilder.java:374)
	at com.hedera.node.app.ServicesMain.main(ServicesMain.java:161)
Caused by: java.nio.file.AtomicMoveNotSupportedException: data/saved/swirlds-recycle-bin -> data/recycle-bin: Invalid cross-device link
	at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:871)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
	at java.base/java.nio.file.Files.move(Files.java:1430)
	at com.swirlds.common.io.filesystem.internal.FileSystemManagerImpl.lambda$new$4(FileSystemManagerImpl.java:108)
	at com.swirlds.common.io.utility.FileUtils.rethrowIO(FileUtils.java:71)
	... 5 more
```

```
[12:41](https://swirldslabs.slack.com/archives/C06R5C8271B/p1715787664905159)
the swirlds-node container, oddly, is still running. That is the entireity of it’s docker log, and there is no swirlds.log
danalvizu@staging-sm-1:~$ sudo docker ps
CONTAINER ID   IMAGE                                              COMMAND                  CREATED        STATUS                  PORTS     NAMES
ca5a73adebff   local/main-network-node:0.50.0-alpha.1             "/opt/hgcapp/service…"   15 hours ago   Up 15 hours                       swirlds-node
```

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
This Pr revers the storage location of the recycle bin back to `saved/swirlds-recycle-bin/nodeId`

**Related issue(s)**:

Fixes #13334 

**Notes for reviewer**:
A recent refactor of the context unified how the PlatformContext is created for commands when no NodeId is needed.
Given the necessity of introducing the nodeId in the factory is limited to cases where we have that information,  I had to create a NoOpRecycleBin that doesn't requiere the nodeId to function.
This introduction brought the opportunity to modify the signature of the factory to support both cases, and thus simplify the factory building patterns

### CODE REVIEW

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java [hunk 1]
```diff
@@ -53,28 +54,37 @@ public interface PlatformContext {
...
         final Metrics metrics = new NoOpMetrics();
         final Cryptography cryptography = CryptographyHolder.get();
-        return create(configuration, metrics, cryptography);
+        // This new method is used by commands that have no access to nodeId,
+        // we temporary assigning node 0 until we remove recycle bin from the fsManager,
+        // then we can set a dummy impl of the recycle bin
+        final FileSystemManager fileSystemManager =
+                FileSystemManagerFactory.getInstance().createFileSystemManager(configuration, metrics);
+
+        return create(configuration, metrics, cryptography, fileSystemManager);
```
Comment (cody-littley) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java:63]: Assuming node is going to make local testing tricky (currently `pcli browse` platforms share the same file system). It is reasonable for the platform context to be aware of the node ID, this should be an argument to whatever builds the platform context.

I started work on a platform context builder (in draft mode because there is ongoing design discussion around the platform context), and in that PR the node ID was required to build a platform context. https://github.com/hashgraph/hedera-services/pull/13152

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/NoOpRecycleBin.java [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+package com.swirlds.common.io.utility;
+
+import edu.umd.cs.findbugs.annotations.NonNull;
+import java.io.IOException;
+import java.nio.file.Path;
+
+/**
+ * A no-op {@link RecycleBin} implementation.
+ *
+ */
```
Comment (cody-littley) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/NoOpRecycleBin.java:26]:
```suggestion
/**
 * A no-op {@link RecycleBin} implementation.
 */
```

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java (hunk 1 above)
Comment (mxtartaglia-sl) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/context/PlatformContext.java]: As spoken, fixed the comment and moved it to javadoc.
It is a method only used by commands not aware of the concept of nodeId.

**Review by cody-littley — APPROVED** [review]
