### PR TITLE
fix: Fuzzy match AtomicCryptoTransferSuite

### LINKED ISSUE #10976: Enable fuzzy record matching for AtomicCryptoTransferHTSSuite

### PR DESCRIPTION
**Pull request by MrValioBg**
**Description**:
Fuzzy match AtomicCryptoTransferSuite.

The disabled tests were initially failing in mono, but passing in modularized codebase.

After adding the CRYPTO_TRANSFER_V2 in the isClassicCall method, the tests failing in mono also started to fail in modularized code.

There is a new open issue to revisit those tests - #11103

**Related issue(s)**:

Fixes #10976 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by mhess-swl — COMMENTED** [review]
Looks good from the services side 👍

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java [hunk 1]
```diff
@@ -97,12 +97,19 @@ public TransactionBody decodeCryptoTransfer(
...
-                .transfers(convertingMaybeApprovedAdjustments(((Tuple) call.get(0)).get(0), addressIdConverter)));
+        final var transferList = convertingMaybeApprovedAdjustments(((Tuple) call.get(0)).get(0), addressIdConverter);
+
+        final var cryptoTransfersBody = tokenTransfers(convertTokenTransfers(
+                call.get(1),
+                this::convertingMaybeApprovedAdjustments,
+                this::convertingMaybeApprovedOwnershipChanges,
+                addressIdConverter));
+
+        if (transferList.accountAmounts() != null
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java:108]: ⚠️ Shouldn't it be impossible for this to be `null`? 

Even if _currently_ there's no risk of hiding a bug by working around an incorrect `null` here, adding such checks makes it easier for bugs to hide in the future.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java [hunk 2]
```diff
@@ -133,7 +137,8 @@ public List<HapiSpec> getSpecsInSuite() {
         });
     }
 
-    @HapiTest
+    // This test is failing against mono-service.
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java:140]: In the PR description, you wrote,

> After adding the CRYPTO_TRANSFER_V2 in the isClassicCall method, the tests failing in mono also started to fail in modularized code.

Does that mean this test now fails as a `@HapiTest` too?

Comment (MrValioBg) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java:140]: Yes, exactly

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java (hunk 1 above)
Comment (MrValioBg) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java]: Yes, you are right, since in the Builder accountAmounts() method in TransferList, we use List.of() for the input.

I fixed it, great catch!

**Review by mhess-swl — APPROVED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java]: Awesome, thanks @MrValioBg !

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java:140]: Ah got it 💯

**Review by tinker-michaelj — APPROVED** [review]
LGTM, thanks @MrValioBg !
