### PR TITLE
Fix Hedera so it can start again

### LINKED ISSUE #6803: `Hedera` unable to start
I found a couple bugs while trying to start the Hedera class:

- At genesis, the wrong version is passed in to migration (should be null)
- Genesis state is not constructed properly (failed to commit admin states)
- "genesisUsage" was not set on dagger

### PR DESCRIPTION
**Pull request by rbair23**
Closes #6803 

I also removed the dual-grpc server setup, so we can start performing test runs exclusively on the new code paths (we're past the point of wanting to run both at the same time)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java [hunk 1]
```diff
@@ -326,8 +326,9 @@ private void onStateInitialized(
      * Called by this class when we detect it is time to do migration.
      */
     private void onMigrate(
-            @NonNull final MerkleHederaState state, @NonNull final SerializableSemVers deserializedVersion) {
-        final var previousVersion = PbjConverter.toPbj(deserializedVersion.getServices());
+            @NonNull final MerkleHederaState state, @Nullable final SerializableSemVers deserializedVersion) {
+        final var previousVersion =
+                deserializedVersion == null ? null : PbjConverter.toPbj(deserializedVersion.getServices());
```
Comment (rbair23) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java:331]: Previously I made the mistake of not allowing the deserialized version to be null. But it is null during genesis.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java [hunk 2]
```diff
@@ -450,10 +451,7 @@ private void validateLedgerState() {
      */
     @Override
     public void run() {
-        // Start the gRPC servers.
-        logger.info("Starting mono gRPC server");
-        daggerApp.grpcStarter().startIfAppropriate();
-
+        // Start the gRPC server.
```
Comment (rbair23) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java:454]: We're going all-in on the new workflows. No more mixed mode for the grpc servers.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java [hunk 3]
```diff
@@ -596,6 +594,7 @@ private void createSpecialGenesisChildren(
         // Prepopulate the FreezeService state with default values for genesis
         final var adminStates = state.createWritableStates(FreezeService.NAME);
         adminStates.getSingleton(FreezeServiceImpl.UPGRADE_FILES_KEY).put(new MerkleSpecialFiles());
+        ((MerkleWritableStates) adminStates).commit();
```
Comment (rbair23) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java:597]: We have to commit the default fields added to the admin state

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java [hunk 4]
```diff
@@ -730,6 +729,7 @@ private void initializeDagger(@NonNull final MerkleHederaState state, @NonNull f
                     .maxSignedTxnSize(MAX_SIGNED_TXN_SIZE)
                     .crypto(CryptographyHolder.get())
                     .selfId(nodeSelfAccount)
+                    .genesisUsage(trigger == InitTrigger.GENESIS)
```
Comment (rbair23) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java:732]: And we have to set the genesis trigger

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java (hunk 1 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java:331]: Might be worth putting the null check in the toPbj method, so the method is null-safe (rather than null-failing)...
