### PR TITLE
Fix TokenAssociationSpecs tests

### LINKED ISSUE #8558: Resolve `TokenAssociationSpecs` errors
### Problem

We have the following tests suite `TokenAssociationSpecs` that has problems when it's running against modularization codebase.

### Solution

Resolve issues with the test suite. When ready add @hapitest annotations to the passing tests.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
**Description**:
- Updates the `freezeStatus` and `kycStatus` returned for the associated tokens in `getAccountInfo`. It can now return all possible status values.
- Enables the `treasuryAssociationIsAutomatic` test.
- The last disabled test from the suite depends on `TokenDissociateFromAccountHandler -> tokenIsExpired` which is not implemented yet.

**Related issue(s)**:

Fixes #8558 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by Ivo-Yankov** [comment]
> This PR changes the test. This should only be necessary in rare cases and it is not clear, if this is the case here. Can you please explain why you changed the test?
> 
> On of the integration tests is failing.

The change was not actually necessary and I reverted it.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java [hunk 1]
```diff
@@ -279,8 +279,9 @@ private List<TokenRelation> createTokenRelsToAccount(
             }
 
             // Create the new token relation
-            final var isFrozen = token.hasFreezeKey() && token.accountsFrozenByDefault();
-            final var kycGranted = !token.hasKycKey();
+            boolean isTreasuryAccount = token.treasuryAccountId().equals(account.accountId());
```
Comment (netopyr) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:282]: Nit: I prefer `Objects.equals()` because it allows either parameter to be `null`.

**Review by netopyr — APPROVED** [review]
LGTM

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java (hunk 1 above)
Comment (Ivo-Yankov) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java]: Changed it to use `Objects.equals()`

**Review by netopyr — APPROVED** [review]
LGTM

**Review by netopyr — APPROVED** [review]
LGTM
