### PR TITLE
06790 Do leaf rehash during VirtualMap deserialization

### LINKED ISSUE #6790: VirtualRootNode has to be rehashed on deserialization
### Problem

After #5825 0.38 -> 0.39 upgrade requires re-hashing of all `VirtualMap` leaves. Currently it happens in `ServicesState#internalInit`. However, it turned out that in some cases we may need `VirtualRootNode` hashed even before the `VirtualMap` is constructed. 

Otherwise, rehashing on load fails with the following exception:

```
Loading state from /Users/codylittley/Downloads/./49311271/SignedState.swh
Hashing state
java.lang.RuntimeException: problem encountered while hashing state
	at com.swirlds.platform.state.editor.StateEditor.<init>(StateEditor.java:81)
	at com.swirlds.platform.cli.StateEditorCommand.call(StateEditorCommand.java:72)
	at com.swirlds.platform.cli.StateEditorCommand.call(StateEditorCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.swirlds.cli.PlatformCli.main(PlatformCli.java:218)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.common.merkle.hash.FutureMerkleHash.rethrowException(FutureMerkleHash.java:83)
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:93)
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:30)
	at com.swirlds.platform.state.editor.StateEditor.<init>(StateEditor.java:79)
	... 11 more
Caused by: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hashSubTree(VirtualHasher.java:701)
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:417)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.computeHash(VirtualRootNode.java:1248)
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.hashCopy(VirtualPipeline.java:359)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.getHash(VirtualRootNode.java:1200)
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.hashSubtree(MerkleHashBuilder.java:206)
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.lambda$createHashingRunnable$1(MerkleHashBuilder.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Failed to find a hash for 2202619, which is a sibling of 2202620
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.lambda$hashSubTree$2(VirtualHasher.java:660)
	... 3 more
```

### Solution

Add `VirtualRootNode#fullLeafRehash` call  to `VirtualRootNode#deserialize`. 

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

After https://github.com/hashgraph/hedera-services/pull/5825 0.38 -> 0.39 upgrade requires re-hashing of all VirtualMap leaves. Currently it happens in ServicesState#internalInit. However, it turned out that in some cases we may need VirtualRootNode hashed even before the VirtualMap is constructed.

Otherwise, rehashing on load fails with the following exception:
```
Loading state from /Users/codylittley/Downloads/./49311271/SignedState.swh
Hashing state
java.lang.RuntimeException: problem encountered while hashing state
	at com.swirlds.platform.state.editor.StateEditor.<init>(StateEditor.java:81)
	at com.swirlds.platform.cli.StateEditorCommand.call(StateEditorCommand.java:72)
	at com.swirlds.platform.cli.StateEditorCommand.call(StateEditorCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.swirlds.cli.PlatformCli.main(PlatformCli.java:218)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.common.merkle.hash.FutureMerkleHash.rethrowException(FutureMerkleHash.java:83)
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:93)
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:30)
	at com.swirlds.platform.state.editor.StateEditor.<init>(StateEditor.java:79)
	... 11 more
Caused by: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hashSubTree(VirtualHasher.java:701)
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:417)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.computeHash(VirtualRootNode.java:1248)
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.hashCopy(VirtualPipeline.java:359)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.getHash(VirtualRootNode.java:1200)
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.hashSubtree(MerkleHashBuilder.java:206)
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.lambda$createHashingRunnable$1(MerkleHashBuilder.java:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Failed to find a hash for 2202619, which is a sibling of 2202620
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.lambda$hashSubTree$2(VirtualHasher.java:660)
	... 3 more
```

**Related issue(s)**:

Fixes #6790, #6692

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java [hunk 1]
```diff
@@ -225,10 +226,13 @@ VirtualRootNode<K, V> getRoot() {
 
     /**
      * Does a full rehash of the persisted leaves of the map.
-     * Delegates the call to {@link VirtualRootNode#fullLeafRehash()} which does the actual work.
+     * Delegates the call to {@link VirtualRootNode#fullLeafRehashIfNecessary()} which does the actual work.
+     *
+     * This method is going to be removed after 0.39.0 release because it shouldn't be called explicitly.
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java:231]: Was this method ever used by any promoted HS version? If not, it can be just dropped without deprecating it first

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java [hunk 2]
```diff
@@ -165,9 +165,9 @@ public static class ClassVersion {
 
     /**
      * The number of seconds to wait for the full leaf rehash process to finish
-     * (see {@link VirtualRootNode#fullLeafRehash()}) before we fail with an exception.
+     * (see {@link VirtualRootNode#fullLeafRehashIfNecessary()}) before we fail with an exception.
      */
-    private static final int MAX_FULL_REHASHING_TIMEOUT = 21600; // 6 hours
+    private static final int MAX_FULL_REHASHING_TIMEOUT = 3600; // 1 hour
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:170]: Why is it no longer needed to be 6h?

Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:170]: When I added this code, I didn't know that we have 5 minutes SLA for the upgrade. I left 1 hour as a theoretical limit for the testing purposes.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java:231]: Okay, I'll take my chances then. If someone grabs this platform build before me, they will have compilation errors. But I'll do my best to be first.

**Review by cody-littley — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]
