### PR TITLE
test: Additional airdrop negative tests

### LINKED ISSUE #14912: (CLAIM_47) TokenClaimAirdrop transaction with no pending airdrops entries should fail

### LINKED ISSUE #14913: (CLAIM_48) Attempt to claim an airdrop that was claimed by the same account

### LINKED ISSUE #14914: (CLAIM_49) Attempt to claim an airdrop that was claimed by a different account

### LINKED ISSUE #14915: (CLAIM_50) Attempt to claim an airdrop by the sender account (when the receiver account is different)

### LINKED ISSUE #14916: (CLAIM_51) TokenClaimAirdrop transaction containing pending airdrops entries which do not exist in state should fail

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

Add claim airdrop test cases from the test plan:
CLAIM_47
CLAIM_48
CLAIM_49
CLAIM_50
CLAIM_51

**Related issue(s)**:

Fixes #14912
Fixes #14913
Fixes #14914
Fixes #14915
Fixes #14916

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 1]
```diff
@@ -112,17 +114,20 @@ public class TokenClaimAirdropTest extends TokenAirdropBase {
...
+                "tokens.airdrops.cancel.enabled", "false"));
         // create some entities with disabled airdrops
         lifecycle.doAdhoc(setUpEntitiesPreHIP904());
         // enable airdrops
         lifecycle.doAdhoc(
                 overriding("entities.unlimitedAutoAssociationsEnabled", "true"),
                 overriding("tokens.airdrops.enabled", "true"),
-                overriding("tokens.airdrops.claim.enabled", "true"));
+                overriding("tokens.airdrops.claim.enabled", "true"),
+                overriding("tokens.airdrops.cancel.enabled", "true"));
```
Comment (iwsimon) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:130]: Above overrideInClass() call is all the default TokesConfig values. EntitiesConfig also has unlimitedAutoAssociationsEnabled default to true. I think we only need lifecycle.overrideInClass() for "tokens.airdrops.enabled", "true", "tokens.airdrops.claim.enabled", "true","tokens.airdrops.cancel.enabled", "true" here. 
               @tinker-michaelj is the above correct?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java [hunk 2]
```diff
@@ -765,6 +791,43 @@ final Stream<DynamicTest> hollowNoHbarFail() {
...
+        // CLAIM_50
+        return hapiTest(flattened(
+                setUpTokensAndAllReceivers(),
+                cryptoCreate(receiver),
+                cryptoCreate(randomAccount),
+                tokenAirdrop(moving(1, FUNGIBLE_TOKEN).between(OWNER, receiver)).payingWith(OWNER),
+                tokenClaimAirdrop(pendingAirdrop(OWNER, receiver, FUNGIBLE_TOKEN))
+                        .payingWith(randomAccount)
+                        .signedBy(randomAccount)
+                        .hasKnownStatus(INVALID_SIGNATURE)));
```
Comment (iwsimon) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:828]: randomAccount is not the sender.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java (hunk 1 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:130]: Here, we override airdrop related properties twice. 
1 - we disabled everything using `overrideInClass`.
This way we can create entities like if they are created pre hip904 in `setUpEntitiesPreHIP904`
For example, a hollow account with 0 auto-associations.
2 - After that we enable again everything related to the airdrops, and then start tests.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java (hunk 2 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:826]: Fixed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:130]: We only need  ```
lifecycle.overrideInClass(Map.of(
                "entities.unlimitedAutoAssociationsEnabled", "false"))
``` instead of 
                l```
ifecycle.overrideInClass(Map.of(
                "entities.unlimitedAutoAssociationsEnabled", "false",
                "tokens.airdrops.enabled", "false",
                "tokens.airdrops.claim.enabled", "false")); 
```since the other two are the default config value.

**Review by Neeharika-Sompalli — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java (hunk 1 above)
Comment (JivkoKelchev) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:130]: But when we release the airdrops, the default values will be changed to "true". 
Also, in different environments, we can have different values. 
I don't think we should be relying on default values here.

Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip904/TokenClaimAirdropTest.java:130]: I see. Thanks.

**Review by iwsimon — APPROVED** [review]
LGTM, thanks @JivkoKelchev
