### PR TITLE
fix: prevent hollow account fuzzing test to fail due to stale account registry entries

### LINKED ISSUE #25015: [Flaky Test] com.hedera.services.bdd.suites.regression.HollowAccountCompletionFuzzing#hollowAccountCompletionFuzzing
## Flaky Test Detected

| Field | Value |
|---|---|
| Module | `test-clients` |
| Class | `com.hedera.services.bdd.suites.regression.HollowAccountCompletionFuzzing` |
| Method | `hollowAccountCompletionFuzzing` |
| First detected | 2026-04-15 |
| Workflow | [Node: PR Checks #48256](https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/24469069332) |

### Failure Detail (first occurrence)
```
com.hedera.services.bdd.spec.infrastructure.RegistryNotFound: Missing AccountID 'Fuzz#36#'!
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.HapiSpecRegistry.get(HapiSpecRegistry.java:755)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.HapiSpecRegistry.getAccountID(HapiSpecRegistry.java:549)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.providers.ops.hollow.RandomOperationSignedBy.keyFromAccount(RandomOperationSignedBy.java:49)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.providers.ops.hollow.RandomOperationSignedBy.randomHollowAccountKey(RandomOperationSignedBy.java:44)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.providers.ops.hollow.RandomOperationSignedBy.get(RandomOperationSignedBy.java:40)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.providers.ops.hollow.RandomContractCreateSignedBy.get(RandomContractCreateSignedBy.java:13)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.infrastructure.providers.ops.BiasedDelegatingProvider.get(BiasedDelegatingProvider.java:94)
	at com.hedera.node.test.clients@0.74.0-SNAPSHOT/com.hedera.services.bdd.spec.utilops.ProviderRun.lambda$submitOp$0(ProviderRun.java:187)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:710)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:635)
	at... (truncated)
```

### PR DESCRIPTION
**Pull request by Evdokia-Georgieva**
**Description**:
Root cause:
The fuzz test tracks hollow accounts in two separate places: a data map that stores the actual AccountID, read by getAccountID() and a present set that tracks which of the names read by getQualifying() actually exist. These are supposed to stay in sync, but when cryptoDelete().purging() deletes an account, it removes the entry from the data map but the name is still present even though the AccountID is already gone. On the next operation, randomHollowAccountKey() calls getQualifying() and gets the name ("Fuzz#36#" in the case of the failure recorded in the issue) from the stale present set, then immediately calls registry.getAccountID("Fuzz#36#"), which fails with RegistryNotFound because the entry was already removed. 
Fix: 
A check is added in RandomOperationSignedBy.randomHollowAccountKey() to verify registry.hasAccountId() before proceeding. Since hasAccountId() and getAccountID() read from the same data map, if hasAccountId() returns true, then getAccountID() will always succeed and this way the stale present entries will be skipped.

**Related issue(s)**: 
Fixes #25015

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomOperationSignedBy.java [hunk 1]
```diff
@@ -41,7 +41,10 @@ public Optional<HapiSpecOperation> get() {
     }
 
     private Optional<String> randomHollowAccountKey() {
-        return accounts.getQualifying().filter(a -> a.endsWith(ACCOUNT_SUFFIX)).map(this::keyFromAccount);
+        return accounts.getQualifying()
+                .filter(a -> a.endsWith(ACCOUNT_SUFFIX))
+                .filter(a -> registry.hasAccountId(a))
```
Comment (ibankov) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomOperationSignedBy.java:46]: you can add the same guard to `RandomHollowAccountDeletion` as well

Comment (Evdokia-Georgieva) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomOperationSignedBy.java:46]: Done, check out the latest commit :)

**Review by Grigorov-Georgi — APPROVED** [review]

**Review by AlexKehayov — APPROVED** [review]
LGTM

**Review by JivkoKelchev — APPROVED** [review]
LGTM, ty @Evdokia-Georgieva
