### PR TITLE
fix fileservice util to support correctly immutible files

### LINKED ISSUE #7646: FileServiceUtils fails to include keys from files in state to required signing keys and enforces keys on the update transaction
It was found while addressing #7638 that `FileServiceUtils` enforces every file update to include keys. But this is not a proper requirement. Instead, if keys are included, they should be required for signing. But in addition, keys on the file in state should also be included, but do not appear to be. This affects only the modular code (not released) and not production code.
 
```
        if (listKeys == null || !listKeys.hasKeys() || listKeys.keys().isEmpty()) {
            // @todo('protobuf change needed') change to immutable file response code
            if (areKeysRequired) {
                throw new PreCheckException(UNAUTHORIZED);
            }
        }
```

### PR DESCRIPTION
**Pull request by povolev15**
**Related issue(s)**:

Fixes #7646

### CODE REVIEW

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java [hunk 1]
```diff
@@ -107,6 +111,10 @@ public void handle(@NonNull final HandleContext handleContext) throws HandleExce
         }
         final var file = optionalFile.get();
 
+        // First validate this file is mutable; and the pending mutations are allowed
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java:114]: When privileged checks are done, we'll have to check that here and skip at least the mutability check for privileged "payer" accounts

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java [hunk 2]
```diff
@@ -63,14 +63,17 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
...
-        validateAndAddRequiredKeys(fileMeta.keys(), context, true);
+        var file = fileStore.getFileLeaf(transactionBody.fileID());
+        validateAndAddRequiredKeys(file.orElse(null), null, context);
     }
 
     @Override
     public void handle(@NonNull final HandleContext handleContext) throws HandleException {
         requireNonNull(handleContext);
+        // First validate this file is mutable; and the pending mutations are allowed
+        // TODO: add or condition for privilege accounts from context
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java:76]: Might revise this comment:
```suggestion
        // TODO: check here that the "payer" is a privileged account.
        //       a privileged account is always required for this transaction.
```

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java [hunk 3]
```diff
@@ -62,14 +62,17 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
...
-        validateAndAddRequiredKeys(fileMeta.keys(), context, true);
+        var file = fileStore.getFileLeaf(transactionBody.fileID());
+        validateAndAddRequiredKeys(file.orElse(null), null, context);
     }
 
     @Override
     public void handle(@NonNull final HandleContext handleContext) throws HandleException {
         requireNonNull(handleContext);
+        // First validate this file is mutable; and the pending mutations are allowed
+        // TODO: add or condition for privilege accounts from context
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java:75]:
```suggestion
        // TODO: check here that the "payer" is a privileged account.
        //       a privileged account is always required for this transaction.
```

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java (hunk 2 above)
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java:76]: Might want to revise the comment:
```suggestion
        // TODO: check here that the "payer" is a privileged account.
        //       a privileged account is always required for this transaction.
```

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java [hunk 4]
```diff
@@ -189,4 +190,33 @@ public static void validateAndAddRequiredKeys(
...
+     * @param file that will be checked for verification keys
+     * @param transactionKeyList transaction keys that add to context for verification.
+     * @param context the handle context for the transaction.
+     * @throws HandleException throws exception if {@link ResponseCodeEnum#UNAUTHORIZED}
+     */
+    public static void validateSignatures(
+            @Nullable File file, @Nullable KeyList transactionKeyList, @NonNull HandleContext context)
+            throws HandleException {
+
+        if (transactionKeyList != null && transactionKeyList.hasKeys()) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java:205]: Question for the experts:
When a file transaction has a KeyList (create or update allow these), do we require that all of those keys have signed?  I can see a case for _possibly_ not doing so:
> `idi` needs to create a file
> The file is to be owned/controlled by four others [`bob`, `alice`, `raj`, `tosi`]
> in the create transaction, `idi` sets the key list to contain keys for [`bob`, `alice`, `raj`, `tosi`]

The question is, do we require that `idi` create a scheduled transaction in this case, so all four of the others can sign the file create (assuming they cannot all sign the initial transaction), or can `idi` just create the file, and it is only modifications thereafter that require all four keys from `bob`, `alice`, `raj`, and `tosi`?

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java [hunk 5]
```diff
@@ -287,6 +296,17 @@ void handleThrowsIfAttributeValidatorFails() {
         assertTrue(fileStore.get(FileID.newBuilder().fileNum(1234L).build()).isEmpty());
     }
 
+    @Test
+    void handleThrowsIfKeysSignatureFailed() {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java:300]: Might be good to have one of these for each of the handlers...

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java:1]: Do we have a test that verifies the handler throws if the file is immutable (has no key list, or empty key list)?  If not, it would be good to add that for all three of append, delete, and update...

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java (hunk 1 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java:114]: added todo here

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java (hunk 3 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java]: done thanks

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java (hunk 2 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java]: done thanks

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java (hunk 5 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java:300]: done thank you

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java:1]: sure I will add it.

**Review by iwsimon — APPROVED** [review]
LGTM

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java:1]: done

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java [hunk 6]
```diff
@@ -98,26 +114,28 @@ void fileIdNotFound() throws PreCheckException {
...
+        context.registerStore(ReadableFileStore.class, mockStore);
 
         // when:
         assertThrowsPreCheck(() -> subject.preHandle(context), INVALID_FILE_ID);
     }
 
     @Test
-    @DisplayName("File without keys returns error")
-    @Disabled("Revisit after fix for https://github.com/hashgraph/hedera-services/issues/7646")
-    void noFileKeys() throws PreCheckException {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java:110]: Shouldn't this still be present, to test the immutable case?

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java [hunk 7]
```diff
@@ -148,6 +154,27 @@ void appliesNewKeys() {
         assertEquals(expectedKey, newFile.keys());
     }
 
+    @Test
+    @DisplayName("Fails handle if keys doesn't exist on file to be updated")
+    void keysDoesntExist() {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java:159]: Might be worth renaming to "failForImmutableFile"

Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java:159]: Might be worth renaming to "failForImmutableFile"

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java [hunk 8]
```diff
@@ -198,6 +212,40 @@ void appliesUpgradeFileNewContent() {
         assertEquals(bytesNewContentExpected, file);
     }
 
+    @Test
+    @DisplayName("Fails handle if keys doesn't exist on file to be appended")
+    void keysDoesntExist() {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java:217]: Might be good to rename this to "failsForImmutableFile" to make clearer that we're testing how the code handles immutable files, not verifying that keys do not exist.

Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java]: done

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java (hunk 7 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java:197]: done thanks

Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java:197]: done thanks

**Review by tinker-michaelj — COMMENTED** [review]
I think I'm missing something...I don't understand why the `FileHandler`'s are directly validating signatures here. :thinking:

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java:204]: If a `FileCreate` specifies a `KeyList{a, b, c, d}` then yes, all four keys would have to sign the `FileCreate`.

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java (hunk 6 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java:110]: on pre-handle it doesn't throw.
The one you are referring to that I deleted it is also for prehandle ``` void noFileKeys() throws PreCheckException```

Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java:110]: Ahh.  Should add the immutability check as a separate test, then.

**Comment by jsync-swirlds** [comment]
> I think I'm missing something...I don't understand why the `FileHandler`'s are directly validating signatures here. 🤔

My understanding:
The signatures are validated in Workflow, but that just generates the validation results.
Payer is fully verified in workflow, but the services still need to read the results and react appropriately for any other keys that do not have valid signatures.

**Comment by netopyr** [comment]
> > I think I'm missing something...I don't understand why the `FileHandler`'s are directly validating signatures here. 🤔
> 
> My understanding: The signatures are validated in Workflow, but that just generates the validation results. Payer is fully verified in workflow, but the services still need to read the results and react appropriately for any other keys that do not have valid signatures.

This is not fully correct. Optional keys are treated like that, the verification is started but not taken into account. Required keys, on the other hand, are checked. If the verification of a required key fails, `handle` will not be called.

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java (hunk 6 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java:110]: ok sure will be done. I will commit soon

**Review by jsync-swirlds — DISMISSED** [review]

**Review by iwsimon — DISMISSED** [review]

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java [hunk 9]
```diff
@@ -72,9 +74,10 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
 
         final var transactionBody = context.body().fileAppendOrThrow();
         final var fileStore = context.createStore(ReadableFileStore.class);
-        final var fileMeta = preValidate(transactionBody.fileID(), fileStore, context, false);
+        preValidate(transactionBody.fileID(), fileStore, context, false);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java:77]: Shouldn't these checks be done in handle ? In all handlers. It is possible configuration or state changed from prehandle to handle

Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java:77]: that's why it checked in both

**Review by nathanklick — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by jsync-swirlds — APPROVED** [review]
