### PR TITLE
Resolve SonarCloud Minor Bugs

### LINKED ISSUE #1433: 1428 child-issue: Clean up SonarCloud stability Bugs - Minor
**Summary of the defect**
Related to #1428 

Resolve 99 minor bugs in SonarCloud https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false&severities=MINOR&types=BUG

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #1433 

**Summary of the change**:
1. Resolved SonarCloud Minor Bugs
2. Added `calculateRBS` and `calculateBPT` in `FeeBuilder` base class as the lines of code are repeated in multiple places.

Status on the branch shows all the 99 Minor Bugs are resolved in this SonarCloud [link](https://sonarcloud.io/project/issues?branch=branch-1433-M-cleanup-sonarcloud-minor-bugs&id=com.hedera.hashgraph%3Ahedera-services&resolved=false&types=BUG)
image

### CODE REVIEW

**Review by qnswirlds — COMMENTED** [review]
Instead of adding the cast from `int` to `long`, I think it's better to change the return type of some functions from `int` to `long`.  The same to some input, changing them from `int` to `long` will avoid most of the unnecessary casts.

**Comment by rbair23** [comment]
> Instead of adding the cast from `int` to `long`, I think it's better to change the return type of some functions from `int` to `long`. The same to some input, changing them from `int` to `long` will avoid most of the unnecessary casts.

I'm still working through the PR, but I like the thought. Maybe some of the variables (not just params / return values) could be `long` instead of `int`?

File: hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public FeeData get() {
 		xferBytes += (hbarXfers + tokenXfers) * usageProperties.accountAmountBytes();
 		usageEstimator.addBpt(xferBytes);
 		if (hbarXfers > 0) {
-			addRecordRb(hbarXfers * usageProperties.accountAmountBytes());
+			addRecordRb((long) hbarXfers * usageProperties.accountAmountBytes());
```
Comment (abhishek-hedera) [inline hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java:68]: Doesn't require a cast to long as it's already a long.

File: hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java [hunk 2]
```diff
@@ -261,21 +261,21 @@ public FeeData getContractCallLocalFeeMatrices(int funcParamSize,
...
+      }
     }
-    
-    bpr = BASIC_QUERY_RES_HEADER + getStateProofSize(responseType);    
-   
-    sbpr = BASIC_ENTITY_ID_SIZE + errorMessageSize +  LONG_SIZE  +  contractFuncResultSize;
+
+    bpr =  BASIC_QUERY_RES_HEADER + getStateProofSize(responseType);
+
+    sbpr =  BASIC_ENTITY_ID_SIZE + errorMessageSize +  LONG_SIZE  +  contractFuncResultSize;
```
Comment (abhishek-hedera) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java:278]: Both lines have an extra space after the assignment operation.

File: hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java [hunk 3]
```diff
@@ -461,7 +461,7 @@ public FeeData getContractByteCodeQueryFeeMatrices(int byteCodeSize, ResponseTyp
      * Transaction processing) ResponseType - INT_SIZE ContractID - BASIC_ENTITY_ID_SIZE
      */
 
-    bpt = BASIC_QUERY_HEADER + BASIC_ENTITY_ID_SIZE;
+    bpt =  calculateBPT();
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java]: Fixed alignment in the file. Thanks !

File: hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java [hunk 4]
```diff
@@ -428,9 +428,9 @@ public FeeData getContractInfoQueryFeeMatrices(Key key, ResponseType responseTyp
         keySize = getAccountKeyStorageSize(key);
     }
 
-    bpr = BASIC_QUERY_RES_HEADER + getStateProofSize(responseType); 
+    bpr =  BASIC_QUERY_RES_HEADER + getStateProofSize(responseType);
 
-    sbpr = BASIC_CONTRACT_INFO_SIZE + keySize ;
+    sbpr =  BASIC_CONTRACT_INFO_SIZE + keySize ;
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java]: Fixed alignment in the file. Thanks !

File: hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java]: Fixed alignment in the file. Thanks !

File: hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java]: Fixed . Thanks !

File: hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java [hunk 5]
```diff
@@ -42,7 +42,7 @@
 
 public class ScheduleOpsUsage {
 	/* Scheduled transaction ids have the scheduled=true flag set */
-	private static final long SCHEDULED_TXN_ID_SIZE = BASIC_TX_ID_SIZE + BOOL_SIZE;
+	private static final long SCHEDULED_TXN_ID_SIZE = (long) BASIC_TX_ID_SIZE + BOOL_SIZE;
```
Comment (qnswirlds) [inline hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java:45]: I think we should change `BASIC_TX_ID_SIZE` and/or `BOOL_SIZE ` to `long` instead

File: hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java [hunk 6]
```diff
@@ -61,7 +61,7 @@ public FeeData scheduleCreateUsage(TransactionBody scheduleCreate, SigUsage sigU
 		var op = scheduleCreate.getScheduleCreate();
 
 		var scheduledTxn = op.getScheduledTransactionBody();
-		long msgBytesUsed = scheduledTxn.getSerializedSize() + op.getMemoBytes().size();
+		int msgBytesUsed = scheduledTxn.getSerializedSize() + op.getMemoBytes().size();
```
Comment (qnswirlds) [inline hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java:64]: `msgBytesUsed` must be `long` because on line 83, we will do `estimate.addBpt(msgBytesUsed);` which requires a `long`. Here a `cast` is unavoidable!

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/CommonUtils.java [hunk 7]
```diff
@@ -64,7 +64,7 @@ public static void napMillis(long timeInMillis) throws InterruptedException {
    * Sleep given seconds.
    */
   public static void nap(int timeInSec)  throws InterruptedException {
-    Thread.sleep(timeInSec * 1000);
+    Thread.sleep((long) timeInSec * 1000);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/CommonUtils.java:67]: No, do a `* 1000L`! Or as I remember we have those conversion constants to be reused.

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java [hunk 8]
```diff
@@ -238,9 +239,9 @@ public static void main(String[] args)  {
     byte[] encKey = null;
     try (FileInputStream  keyfis = new FileInputStream(args[0])) {
         encKey = new byte[keyfis.available()];
-        keyfis.read(encKey);
+        int bytesRead = keyfis.read(encKey);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java:242]: Adding `bytesRead` here will make it unused. As for the `read` function, it is always safer to check the `bytesRead` with the total number of bytes that we intended to read, which is `encKey.length`

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java [hunk 9]
```diff
@@ -251,17 +252,17 @@ public static void main(String[] args)  {
...
+      System.err.println("Caught exception when generating public key " + e);
       log.error("Caught Exception when generating public key", e);
     }
 
       /* input the signature bytes */
     byte[] sigToVerify = null;
     try(FileInputStream sigfis = new FileInputStream(args[1])) {
       sigToVerify = new byte[sigfis.available()];
-      sigfis.read(sigToVerify);
+      int bytesRead = sigfis.read(sigToVerify);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java:263]: same here

File: hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java [hunk 10]
```diff
@@ -632,16 +632,16 @@ public FeeData getCryptoAddLiveHashTxFeeMatrices(TransactionBody txBody, SigValu
     long sbpr = 0;
 
     // calculate BPT - Total Bytes in Transaction
-    int txBodySize = 0;
+    long txBodySize = 0;
     txBodySize = getCommonTransactionBodyBytes(txBody);
-    bpt = txBodySize + getCryptoAddLiveHashBodyBodyTxSize(txBody) + (BASIC_ENTITY_ID_SIZE)
+    bpt = (long) txBodySize + getCryptoAddLiveHashBodyBodyTxSize(txBody) + (BASIC_ENTITY_ID_SIZE)
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java:637]: Remove this cast since `txBodySize` was changed to `long`

File: hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java [hunk 11]
```diff
@@ -669,9 +669,9 @@ public FeeData getCryptoDeleteLiveHashTxFeeMatrices(TransactionBody txBody, SigV
     long sbpr = 0;
 
     // calculate BPT - Total Bytes in Transaction
-    int txBodySize = 0;
+    long txBodySize = 0;
     txBodySize = getCommonTransactionBodyBytes(txBody);
-    bpt = txBodySize + getCryptoDeleteLiveHashBodyBodyTxSize() + sigValObj.getSignatureSize();
+    bpt = (long) txBodySize + getCryptoDeleteLiveHashBodyBodyTxSize() + sigValObj.getSignatureSize();
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java:674]: same here, remove this cast

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java [hunk 12]
```diff
@@ -72,10 +72,10 @@
   /**
    * Fields included: nodeTransactionPrecheckCode, responseType, cost
    */
-  public static final int BASIC_QUERY_RES_HEADER = 2 * INT_SIZE + LONG_SIZE;
-  public static final int BASIC_QUERY_HEADER = 212;
+  public static final long BASIC_QUERY_RES_HEADER = 2L * INT_SIZE + LONG_SIZE;
+  public static final long BASIC_QUERY_HEADER = 212;
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java:76]: Use 212L

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java [hunk 13]
```diff
@@ -72,10 +72,10 @@
...
   public static final int BASIC_CONTRACT_CREATE_SIZE = BASIC_ENTITY_ID_SIZE + 6 * LONG_SIZE;
-  public static final int BASIC_CONTRACT_INFO_SIZE =
+  public static final long BASIC_CONTRACT_INFO_SIZE =
       2 * BASIC_ENTITY_ID_SIZE + SOLIDITY_ADDRESS + BASIC_TX_ID_SIZE;
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java:79]: Use 2L

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java [hunk 14]
```diff
@@ -162,11 +162,11 @@ public static FeeObject getFeeObject(FeeData feeData, FeeData feeMatrices, Excha
...
    */
-  public static int getCommonTransactionBodyBytes(TransactionBody txBody) throws InvalidTxBodyException {
+  public static long getCommonTransactionBodyBytes(TransactionBody txBody) throws InvalidTxBodyException {
     if (txBody == null) {
       throw new InvalidTxBodyException("Transaction Body not available for Fee Calculation");
     }
-    int memoSize = 0;
+    long memoSize = 0;
     if (txBody.getMemo() != null) {
       memoSize = txBody.getMemoBytes().size();
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java:171]: `txBody.getMemoBytes().size()` will return an `int` so it's better to keep `int memoSize = 0;` and do a cast when we return for `getCommonTransactionBodyBytes`

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java [hunk 15]
```diff
@@ -295,8 +295,8 @@ public static int getSignatureSize(Transaction transaction) {
    * @return tinyHbars
    */
   public static long getTinybarsFromTinyCents(ExchangeRate exchangeRate, long tinyCentsFee) {
-    BigInteger hbarMultiplier = BigInteger.valueOf(Long.valueOf(exchangeRate.getHbarEquiv()));
-    BigInteger centsDivisor = BigInteger.valueOf(Long.valueOf(exchangeRate.getCentEquiv()));
+    BigInteger hbarMultiplier = BigInteger.valueOf(exchangeRate.getHbarEquiv());
+    BigInteger centsDivisor = BigInteger.valueOf(exchangeRate.getCentEquiv());
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java:299]: I don't see any problem with the original code, because `getHbarEquiv` and `getCentEquiv` return an `int`. If sonar is complaining, that really is their problem! We can do this code differently by multiplying with `1L` or do a cast, but I don't see the point.

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java [hunk 16]
```diff
@@ -62,7 +62,7 @@ public FeeData getFileCreateTxFeeMatrices(TransactionBody txBody, SigValueObj si
     long sbpr = 0;
 
     // calculate BPT - Total Bytes in Transaction
-    int txBodySize = 0;
+    long txBodySize = 0;
     txBodySize = getCommonTransactionBodyBytes(txBody);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:66]: Combine those two lines into one `long txBodySize = getCommonTransactionBodyBytes(txBody);`

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java [hunk 17]
```diff
@@ -104,7 +104,7 @@ public FeeData getFileUpdateTxFeeMatrices(TransactionBody txBody, Timestamp expi
     long sbpr = 0;
 
     FileUpdateTransactionBody fileUpdateTxBody = txBody.getFileUpdate();
-    int txBodySize = 0;
+    long txBodySize = 0;
     txBodySize = getCommonTransactionBodyBytes(txBody);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:108]: Same here, combine those two

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java [hunk 18]
```diff
@@ -170,7 +170,7 @@ public FeeData getFileAppendTxFeeMatrices(TransactionBody txBody, Timestamp expi
     long sbpr = 0;
 
     FileAppendTransactionBody fileAppendTxBody = txBody.getFileAppend();
-    int txBodySize = 0;
+    long txBodySize = 0;
     txBodySize = getCommonTransactionBodyBytes(txBody);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:174]: and here

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java [hunk 19]
```diff
@@ -471,7 +471,7 @@ public FeeData getFileDeleteTxFeeMatrices(TransactionBody txBody, SigValueObj si
     long bpr = 0;
     long sbpr = 0;
 
-    int txBodySize = 0;
+    long txBodySize = 0;
     txBodySize = getCommonTransactionBodyBytes(txBody);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:475]: and here

File: hedera-node/src/main/java/com/hedera/services/legacy/handler/FreezeHandler.java [hunk 20]
```diff
@@ -182,7 +182,10 @@ private void updateFeatureWithFileContents(final byte[] fileBytes) {
 				deleteFileFromList(DELETE_FILE);
 
 				log.info("{} deleting file {}", LOG_PREFIX, DELETE_FILE);
-				deleteTxt.delete();
+				boolean isDeleted = deleteTxt.delete();
+				if (!isDeleted) {
+					log.warn("{} File could not be deleted", DELETE_FILE);
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/legacy/handler/FreezeHandler.java:187]: Need to add test to cover the `log.warn` that was added

File: hedera-node/src/main/java/com/hedera/services/records/EarliestRecordExpiry.java [hunk 21]
```diff
@@ -54,6 +54,11 @@ public int compareTo(EarliestRecordExpiry that) {
 		return Long.compare(this.earliestExpiry, that.earliestExpiry);
 	}
 
+	@Override
+	public int hashCode() {
+		return Objects.hash(earliestExpiry, id);
+	}
+
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/records/EarliestRecordExpiry.java:61]: Need to add test as suggested by Codecov

File: hedera-node/src/main/java/com/hedera/services/state/exports/AccountBalance.java [hunk 22]
```diff
@@ -74,6 +75,11 @@ public boolean equals(Object o) {
 				&& this.b64TokenBalances.equals(that.b64TokenBalances);
 	}
 
+	@Override
+	public int hashCode() {
+		return Objects.hash(num, shard, realm, balance, b64TokenBalances);
+	}
+
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/state/exports/AccountBalance.java:82]: Same here, need test

File: hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java [hunk 23]
```diff
@@ -116,18 +117,21 @@ public void migrateLegacyDiskFsFromV13LocFor(String fsBaseDir, String fsNodeScop
...
 				throw new UncheckedIOException(e);
 			}
 		}
 		var nowEmptyLegacyDir = fsBaseDir + File.separator + fsNodeScopedDir;
-		new File(nowEmptyLegacyDir).delete();
+		try {
+			Files.delete(Paths.get(nowEmptyLegacyDir));
+		} catch (IOException e) {
+			log.warn("Empty legacy directory for File 150 could not be deleted !");
+		}
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleDiskFs.java:134]: Same here, need test to cover the `log.warn`

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Please see inline comments

File: hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java (hunk 5 above)
Comment (Neeharika-Sompalli) [reply hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java:45]: Changing this to long affects changes in a lot of places as both are used in multiple places

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/CommonUtils.java (hunk 7 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/CommonUtils.java:67]: Fixed it ! Thanks !

File: hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java (hunk 10 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java:637]: Yes changes were in my local. Fixed it. Thanks!

File: hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java (hunk 11 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java:674]: Yes changes were in my local. Fixed it. Thanks!

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java (hunk 17 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:108]: Fixed. Thanks

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java (hunk 16 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:66]: Fixed. Thanks!

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java (hunk 14 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java:171]: Fixed. Thanks!

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java (hunk 13 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java:79]: Fixed. Thanks

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java (hunk 19 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java]: Fixed

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java (hunk 18 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java]: Fixed. Thanks

File: hedera-node/src/main/java/com/hedera/services/state/exports/AccountBalance.java (hunk 22 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/main/java/com/hedera/services/state/exports/AccountBalance.java:82]: Added

File: hedera-node/src/main/java/com/hedera/services/records/EarliestRecordExpiry.java (hunk 21 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/main/java/com/hedera/services/records/EarliestRecordExpiry.java:61]: Added test

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java (hunk 15 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java]: Yes , made the change as SonarCloud had complained about casting to `Long`. Reverted back the change.

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java (hunk 9 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java:266]: same here

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java (hunk 8 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java:242]: Added a warn when they mismatch.

File: hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java (hunk 6 above)
Comment (Neeharika-Sompalli) [reply hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java]: Fixed.

File: hapi-fees/src/main/java/com/hedera/services/usage/TxnUsage.java [hunk 24]
```diff
@@ -56,7 +56,7 @@ protected void addEntityBpt() {
 		usageEstimator.addBpt(BASIC_ENTITY_ID_SIZE);
 	}
 
-	protected void addNetworkRecordRb(long rb) {
+	protected void addNetworkRecordRb(int rb) {
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hapi-fees/src/main/java/com/hedera/services/usage/TxnUsage.java]: Yes its an unwanted change. Reverted it. Thanks !

File: hapi-fees/src/main/java/com/hedera/services/usage/SingletonEstimatorUtils.java [hunk 25]
```diff
@@ -45,7 +45,7 @@ public UsageEstimate baseEstimate(TransactionBody txn, SigUsage sigUsage) {
 		var base = FeeComponents.newBuilder()
 				.setBpr(INT_SIZE)
 				.setVpt(sigUsage.numSigs())
-				.setBpt(baseBodyBytes(txn) + sigUsage.sigsSize());
+				.setBpt((long) baseBodyBytes(txn) + sigUsage.sigsSize());
```
[the remark this answers is not in the document]
Comment (Neeharika-Sompalli) [reply hapi-fees/src/main/java/com/hedera/services/usage/SingletonEstimatorUtils.java]: Removed by returning long in `baseBodyBytes`

**Review by abhishek-hedera — APPROVED** [review]
LGTM other than the codecov tests.

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java [hunk 26]
```diff
@@ -238,9 +239,12 @@ public static void main(String[] args)  {
     byte[] encKey = null;
     try (FileInputStream  keyfis = new FileInputStream(args[0])) {
         encKey = new byte[keyfis.available()];
-        keyfis.read(encKey);
+        int bytesRead = keyfis.read(encKey);
+        if (bytesRead != encKey.length) {
+          log.warn("Total bytes read from key file doesn't match expected length");
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java:244]: Actually this code was repeated. We should extract it out to a helper function. And add a test for it.

File: hedera-node/src/test/java/com/hedera/services/records/EarliestEntryExpiryTest.java [hunk 27]
```diff
@@ -48,4 +48,15 @@ public void toStringWorks() {
...
+	@Test
+	public void hashCodeWorks() {
+		// given:
+		EarliestRecordExpiry ere = new EarliestRecordExpiry(5L, asAccount("0.0.5"));
+		EarliestRecordExpiry ere1 = new EarliestRecordExpiry(5L, asAccount("0.0.5"));
+
+		// expect:
+		assertTrue(ere.equals(ere1));
+		assertTrue(ere.hashCode() == ere1.hashCode());
+	}
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/records/EarliestEntryExpiryTest.java:61]: This test should do `assertEquals(expectedHash, ere.hashCode());` instead

File: hedera-node/src/test/java/com/hedera/services/state/exports/AccountBalanceTest.java [hunk 28]
```diff
@@ -51,4 +51,15 @@ public void beanWorks() {
...
+	@Test
+	public void hashCodeWorks() {
+		// given:
+		AccountBalance acc1 = new AccountBalance(5, 4, 3, 6);
+		AccountBalance acc2 = new AccountBalance(5, 4, 3, 6);
+
+		// expect:
+		assertTrue(acc1.equals(acc2));
+		assertTrue(acc1.hashCode() == acc2.hashCode());
+	}
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/state/exports/AccountBalanceTest.java:64]: Same here, rhis test should do `assertEquals(expectedHash, acc.hashCode());`

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java [hunk 29]
```diff
@@ -62,8 +62,7 @@ public FeeData getFileCreateTxFeeMatrices(TransactionBody txBody, SigValueObj si
     long sbpr = 0;
 
     // calculate BPT - Total Bytes in Transaction
-    int txBodySize = 0;
-    txBodySize = getCommonTransactionBodyBytes(txBody);
+    long txBodySize = getCommonTransactionBodyBytes(txBody);
```
Comment (ljianghedera) [inline hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java:65]: This can be a `final` value.

File: hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java [hunk 30]
```diff
@@ -55,7 +55,7 @@ public CryptoTransferUsage givenTokenMultiplier(int tokenMultiplier) {
 	public FeeData get() {
 		var op = this.op.getCryptoTransfer();
 
-		int hbarXfers = op.getTransfers().getAccountAmountsCount();
+		long hbarXfers = op.getTransfers().getAccountAmountsCount();
```
Comment (ljianghedera) [inline hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java:58]: This can be a `final` value.

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java (hunk 15 above)
Comment (qnswirlds) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java]: As discussed, I just wanted to point out that this implicit cast is done with courtesy for us. So if we do it explicitly to remove the dependency on this courtesy, there should not be any complaint! But I am ok to remove it.

File: hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java (hunk 26 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureVerifier.java]: As SignatureVerifier. main is legacy code, and not used anywhere. This is removed.

File: hedera-node/src/test/java/com/hedera/services/records/EarliestEntryExpiryTest.java (hunk 27 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/test/java/com/hedera/services/records/EarliestEntryExpiryTest.java]: Fixed. Thanks

File: hedera-node/src/test/java/com/hedera/services/state/exports/AccountBalanceTest.java (hunk 28 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/test/java/com/hedera/services/state/exports/AccountBalanceTest.java]: Fixed. Thanks

File: hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java (hunk 30 above)
Comment (Neeharika-Sompalli) [reply hapi-fees/src/main/java/com/hedera/services/usage/crypto/CryptoTransferUsage.java]: Fixed. Thanks !

File: hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java (hunk 29 above)
Comment (Neeharika-Sompalli) [reply hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java]: Fixed. Thanks !

**Review by qnswirlds — APPROVED** [review]
Great work!

**Review by abhishek-hedera — APPROVED** [review]
LGTM
