### PR TITLE
fix: EIP-155 support in isAuthorized/isAuthorizedRaw

### LINKED ISSUE #17273: fix: EIP-155 support in smart contract service for Hedera chain ids.
[EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) encodes the chain id along with the curve parity in the `v` component of an EVM EC signature.  If the value of the chain id, when doubled with 35 added to it, doesn't fit in a byte you need to have more bytes of the `v` component of your signatures. 

Currently smart contract facilities that verify EC signatures only allow for 1 byte of `v` (hard coding `65` as the length of an EC signature).  This is needed in `isAuthorizeRaw` and `signSchedule`.  Need to handle 2 byte `v`s so users can encode Hedera chain ids in the EC signature per EIP-155.

### PR DESCRIPTION
**Pull request by david-bakin-sl**
**Description**:

Need to support chain ids such that encoding them in the `v` part of the signature according to EIP-155 works for "large" chain ids, such as Hedera's own.

**Related issue(s)**:

Fixes #17273

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by lukelee-sl — APPROVED** [review]
LGTM. A couple of nits to fix at your discretion.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java [hunk 1]
```diff
@@ -91,13 +95,9 @@ public IsAuthorizedRawCall(
...
         requireNonNull(frame, "frame");
 
-        // First things first: What kind of signature are we dealing with, thus what kind of account+key we need
-        final var signatureType =
-                switch (signature.length) {
-                    case 65 -> SignatureType.EC;
-                    case 64 -> SignatureType.ED;
-                    default -> SignatureType.INVALID;
-                };
+        final var signatureType = signature.length > 64
```
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:98]: Good point. I'm not using `SignatureMapUtils.validChainId` here (or a variant of it that wouldn't actually _check_ the chain id).  Will fix.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java [hunk 2]
```diff
@@ -50,6 +50,10 @@
 /** HIP-632 method: `isAuthorizedRaw` */
 public class IsAuthorizedRawCall extends AbstractCall {
 
+    private static final BigInteger big27 = BigInteger.valueOf(27);
+    private static final BigInteger big28 = BigInteger.valueOf(28);
+    private static final BigInteger big35 = BigInteger.valueOf(35);
```
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:55]: Yes.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java [hunk 3]
```diff
@@ -242,22 +249,21 @@ public Optional<byte[]> formatEcrecoverInput(@NonNull final byte[] messageHash,
...
+        requireNonNull(signature);
+        if (signature.length <= 64) throw new IllegalArgumentException("Signature is too short");
 
-        // We're getting the recovery value from a signature where it is only given a byte.  So
-        // this isn't the EIP-155 recovery value where the chain id is encoded in it (it's too
-        // small for most chain ids).  But I'm not 100% sure of that ... so ...
+        final var v = new BigInteger(1, signature, 64, signature.length - 64);
 
-        // FUTURE: Determine if in fact input `v` _ever_ has a EIP-155 encoded chain id ...
+        if (BigInteger.ZERO.equals(v)) return Optional.of((byte) 27);
```
Comment (stoyanov-st) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:258]: I wonder if this could be solved with a Map. I'm not a fan of those multiple one-liner if statements.

**Review by stoyanov-st — COMMENTED** [review]
Looks good, left some suggestions

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java (hunk 3 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:258]: I think a map did help, TY for the suggestion.  I also agree with not being a fan of the style I used.  Unfortunately, Java's (new) guarded switches - which I tried and which looks even better! - don't work with our use of spotless' palantir plugin.

Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/has/isauthorizedraw/IsAuthorizedRawCall.java:258]: (It would look even better if Java permitted overloading of arithmetic operators so expressions involving `BigInteger` weren't so ugly - I mean `BigInteger.valueOf(35).compareTo(v) > 0` vs `35 > v`, huh? - but that's a fight long lost ...)

**Review by lukelee-sl — DISMISSED** [review]
LGTM

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by stoyanov-st — APPROVED** [review]
LGTM
Thanks @david-bakin-sl
