### PR TITLE
fix: fallen behind detection

### LINKED ISSUE #11471: ISS detector uncaught exception: round handled twice
- observed in [this JRS run](http://35.247.76.217:8095/alittley/11446-use-ordered-solder/4N/Abbrev/20240208-202853-GCP-PRCheck-Abbrev-4N/Consistency-NDReconnect-10m/swirlds-logs.html)
    - this is on a non-develop branch, but I don't think the changes there are the cause of this error

```
2024-02-08 21:01:17.602 371      ERROR EXCEPTION        <ForkJoinPool-2-worker-18> TaskSchedulerBuilder: Uncaught exception in scheduler issDetector
java.lang.IllegalArgumentException: previous round was 521, can't decrease round to 521
	at com.swirlds.platform.state.iss.IssDetector.roundCompleted(IssDetector.java:175) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.iss.IssDetector.overridingState(IssDetector.java:362) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:93) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialTask.exec(SequentialTask.java:92) [swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

### PR DESCRIPTION
**Pull request by cody-littley**
closes #11471 

The majority of this change was originally made in [this PR](https://github.com/hashgraph/hedera-services/pull/11149), which was reverted due to a bug in fallen behind detection. This PR reintroduces the reverted changes but with the fallen behind detection bug fixed.

Primary diff has to do with the `Shadowgraph.reserve()` method. Instead of returning a `ShadowgraphReservation` containing an event window, I now return a new object called a `ReservedEventWindow` that contains both an event window and a shadowgraph reservation. Shadowgraph reservations are reused, and that was causing the nested event window to incorrectly be reused long past when it should have been discarded. This new technique always causes us to use the most recent event window, even if the base reservation object is reused.

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/TheirTipsAndEventWindow.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    @NonNull
+    public static TheirTipsAndEventWindow create(
+            @NonNull final NonAncientEventWindow eventWindow, @NonNull final List<Hash> tips) {
+        Objects.requireNonNull(eventWindow);
+        Objects.requireNonNull(tips);
+        return new TheirTipsAndEventWindow(eventWindow, tips);
+    }
+
+    @NonNull
+    public NonAncientEventWindow getEventWindow() {
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/TheirTipsAndEventWindow.java:48]: javadocs

File: platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/source/AbstractEventSource.java [hunk 2]
```diff
@@ -228,10 +229,12 @@ public IndexedEvent generateEvent(
         // work for consensus, and we will have to upgrade our simulation framework prior to converting
         // consensus to use the birth round.
         final IndexedEvent latestSelfEvent = getLatestEvent(random);
-        final long birthRound = Math.max(
-                        otherParentEvent == null ? 0 : otherParentEvent.getGeneration(),
-                        latestSelfEvent == null ? 0 : latestSelfEvent.getGeneration())
+        final long generation = Math.max(
+                        otherParentEvent == null ? (FIRST_GENERATION - 1) : otherParentEvent.getGeneration(),
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/source/AbstractEventSource.java:233]: I think `GraphGenerations` as a source of constants is deprecated.  `EventConstants.FIRST_GENERATION` would be better.

File: platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/source/AbstractEventSource.java [hunk 3]
```diff
@@ -228,10 +229,12 @@ public IndexedEvent generateEvent(
...
+                        latestSelfEvent == null ? (FIRST_GENERATION - 1) : latestSelfEvent.getGeneration())
                 + 1;
+        // First generation is 0, but first birth round is 1.
+        final long birthRound = generation + 1;
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/source/AbstractEventSource.java:237]: Would it make more sense to use `ConsensusConstants.ROUND_FIRST`.   or just a plain `1`.

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowGraphTest.java [hunk 4]
```diff
@@ -134,40 +133,40 @@ private void initShadowgraph(final Random random, final int numEvents, final int
...
     void testFindAncestorsExcludesExpiredEvents() {
-        Random random = RandomUtils.getRandomPrintSeed();
+        final Random random = RandomUtils.getRandomPrintSeed();
         initShadowgraph(random, 100, 4);
 
-        long expireBelowGen = random.nextInt(10) + 1;
+        final long expireBelowGen = random.nextInt(10) + 1;
 
         final NonAncientEventWindow eventWindow = new NonAncientEventWindow(
                 0 /* ignored by shadowgraph */, 0 /* ignored by shadowgraph */, expireBelowGen, GENERATION_THRESHOLD);
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowGraphTest.java:164]: It looks like this unit test only checks generation based threshold.  The issue for making the the shadowgraph compatible with birthRound was closed as completed, but these unit tests were not converted over to testing.  

Created a new issue for the conversion of these unit tests here: https://github.com/hashgraph/hedera-services/issues/11560

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowgraphByBirthRoundTests.java [hunk 5]
```diff
@@ -143,43 +142,43 @@ private void initShadowGraph(final Random random, final int numEvents, final int
     @ParameterizedTest
     @MethodSource("graphSizes")
     void testFindAncestorsForMultipleEvents(final int numEvents, final int numNodes) {
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowgraphByBirthRoundTests.java:144]: Oh!  is this whole file a clone of `ShadowGraphTest.java` but using birthRound for ancient?

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtils.java [hunk 6]
```diff
@@ -41,19 +43,19 @@ public static void printTipSet(final String nodeName, final SyncNode node) {
...
         }
-        return maxGen;
+        return maxIndicator;
     }
 
-    public static long getMinGen(final Set<ShadowEvent> events) {
-        long minGen = Long.MAX_VALUE;
-        for (ShadowEvent event : events) {
-            minGen = Math.min(event.getEvent().getGeneration(), minGen);
+    public static long getMinIndicator(final Set<ShadowEvent> events, @NonNull final AncientMode ancientMode) {
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtils.java:54]: `@NonNull` on first parameter?

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtilsTest.java [hunk 7]
```diff
@@ -55,10 +55,10 @@ void testUnknownNonAncient() {
         knownSet.add(e3);
         knownSet.add(e1);
 
-        final GraphGenerations generations = new Generations(0, 1, 3);
+        final NonAncientEventWindow eventWindow = new NonAncientEventWindow(0, 1, 0, GENERATION_THRESHOLD);
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtilsTest.java:58]: Is birthround testing relevant here?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java [hunk 8]
```diff
@@ -403,20 +410,14 @@ public class SwirldsPlatform implements Platform {
 
             // When we perform the migration to using birth round bounding, we will need to read
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:411]: This comment was intentionally left behind. It's in reference to the `PcesFileReader.readFilesFromDisk()` method that did not get moved.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/TheirTipsAndEventWindow.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/TheirTipsAndEventWindow.java:48]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/ShadowgraphWiring.java [hunk 9]
```diff
@@ -58,6 +58,6 @@ public static ShadowgraphWiring create(@NonNull final TaskScheduler<Void> taskSc
     public void bind(@NonNull final Shadowgraph shadowgraph) {
         ((BindableInputWire<EventImpl, Void>) eventInput).bind(shadowgraph::addEvent);
         ((BindableInputWire<NonAncientEventWindow, Void>) nonExpiredEventWindowInput)
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/ShadowgraphWiring.java:60]: nit: the bound method changed to `updateEventWindow`, perhaps the member `nonExpiredEventWindowInput` should receive the same update

**Review by alittley — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/source/AbstractEventSource.java (hunk 3 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/testFixtures/java/com/swirlds/platform/test/fixtures/event/source/AbstractEventSource.java:237]: In this case the "+ 1" is my preference. Even though `ROUND_FIRST` is equal to 1, it's not implied by the current documentation that adding the first round to a generation makes it a legal birth round number.

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowGraphTest.java (hunk 4 above)
Comment (cody-littley) [reply platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowGraphTest.java:164]: Your next comment is correct. I cloned this test, and the clone uses birth rounds.

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowgraphByBirthRoundTests.java (hunk 5 above)
Comment (cody-littley) [reply platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/ShadowgraphByBirthRoundTests.java:144]: Yup!

This test already had a lot of parameterized tests, and it was going to be really complex to add an additional dimension to the parameter space.

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtils.java (hunk 6 above)
Comment (cody-littley) [reply platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtils.java:54]: added

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtilsTest.java (hunk 7 above)
Comment (cody-littley) [reply platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestUtilsTest.java:58]: I'm leaning towards "not necessary". This is a test framework test, and the framework in question is something I'd like to deprecate in the near future.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java [hunk 10]
```diff
@@ -846,7 +843,15 @@ private void loadStateIntoConsensus(@NonNull final SignedState signedState) {
         Objects.requireNonNull(signedState);
 
         consensusRef.get().loadFromSignedState(signedState);
-        shadowGraph.startWithExpiredThreshold(consensusRef.get().getMinGenerationNonAncient());
+
+        // FUTURE WORK: this needs to be updated for birth round compatibility.
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java:847]: We are passing in a minimum generation non-ancient. In order to do this with birth rounds, we will need to store the minimum birth round non-ancient in the state.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowgraphSynchronizer.java [hunk 11]
```diff
@@ -141,37 +124,53 @@ public class ShadowgraphSynchronizer {
...
+     * Constructs a new ShadowgraphSynchronizer.
+     *
+     * @param platformContext        the platform context
+     * @param shadowGraph            stores events to sync
+     * @param numberOfNodes          number of nodes in the network
+     * @param syncMetrics            metrics for sync
+     * @param receivedEventHandler   events that are received are passed here
+     * @param fallenBehindManager    tracks if we have fallen behind
+     * @param intakeEventCounter     used for tracking events in the intake pipeline per peer
+     * @param executor               for executing read/write tasks in parallel
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/ShadowgraphSynchronizer.java:142]: reformatted

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/SyncUtils.java [hunk 12]
```diff
@@ -478,22 +428,27 @@ private static boolean haveWeKnownAboutEventForALongTime(
...
-            final GraphGenerations theirGenerations) {
-        long minSearchGen =
-                Math.max(myGenerations.getMinRoundGeneration(), theirGenerations.getMinGenerationNonAncient());
-        return s -> s.getEvent().getGeneration() >= minSearchGen && !knownShadows.contains(s);
+            @NonNull final Collection<ShadowEvent> knownShadows,
+            @NonNull final NonAncientEventWindow myEventWindow,
+            @NonNull final NonAncientEventWindow theirEventWindow,
+            @NonNull final AncientMode ancientMode) {
+
+        final long minimumSearchThreshold =
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/SyncUtils.java:448]: Mostly, this is just a continuance of the previous logic... I don't think the `max()` is actually required. This should always be evaluating to the peer's ancient threshold. But since this is a simple check, I think it's safer to leave it in place for the time being.

I've added the following comment.

```
        // When searching for events, we don't want to send any events that are known to be ancient to the peer.
        // We should never be syncing with a peer if their ancient threshold is less than our expired threshold 
        // (if this is the case, then the peer is "behind"), so in practice the minimumSearchThreshold will always 
        // be the same as the peer's ancient threshold. However, in an abundance of caution, we use the maximum of 
        // the two thresholds to ensure that we don't ever attempt to traverse over events that are expired to us, 
        // since those events may be unlinked and could cause race conditions if accessed.
```

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/TheirTipsAndEventWindow.java [hunk 13]
```diff
@@ -0,0 +1,55 @@
...
+    private final NonAncientEventWindow eventWindow;
+    private final List<Hash> tips;
+
+    private TheirTipsAndEventWindow(@NonNull final NonAncientEventWindow eventWindow, @NonNull final List<Hash> tips) {
+        this.eventWindow = eventWindow;
+        this.tips = tips;
+    }
+
+    @NonNull
+    public static TheirTipsAndEventWindow create(
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/TheirTipsAndEventWindow.java:40]: converted to a record

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/ShadowgraphWiring.java (hunk 9 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/components/ShadowgraphWiring.java:60]: changed name to `eventWindowInput`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/Shadowgraph.java [hunk 14]
```diff
@@ -171,19 +173,28 @@ private void disconnectShadowEvents() {
...
-    public synchronized ShadowgraphReservation reserve() {
+    @NonNull
+    public synchronized ReservedEventWindow reserve() {
         if (reservationList.isEmpty()) {
-            return newReservation();
+            return new ReservedEventWindow(eventWindow, newReservation());
         }
         final ShadowgraphReservation lastReservation = reservationList.getLast();
-        if (lastReservation.getReservedIndicator() == expireBelow) {
+        if (lastReservation.getReservedThreshold() == eventWindow.getExpiredThreshold()) {
```
[the remark this answers is not in the document]
Comment (alittley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/Shadowgraph.java]: Very nice, instant grok

**Review by alittley — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]
