### PR TITLE
fix: Enable fuzzy matching for ApproveAllowanceSuite

### LINKED ISSUE #10769: Enable fuzzy record matching for ApproveAllowanceSuite (11 tests)

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
**Description**:

**Related issue(s)**:

Fixes #10769 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java [hunk 1]
```diff
@@ -115,6 +116,7 @@ final HapiSpec deletionValidatesAlreadyDeletedToken() {
     final HapiSpec deletionValidatesMissingAdminKey() {
         return defaultHapiSpec("DeletionValidatesMissingAdminKey")
                 .given(
+                        overriding("staking.fees.nodeRewardPercentage", "10"),
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java:119]: Unintended change?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java [hunk 2]
```diff
@@ -76,7 +77,10 @@ public PricedResult execute() {
                     : GrantApprovalTranslator.GRANT_APPROVAL_NFT.getOutputs().encodeElements((long)
                             status.protoOrdinal());
 
-            return gasOnly(FullResult.successResult(encodedOutput, gasRequirement), status, false);
+            return gasOnly(
+                    FullResult.successResult(encodedOutput, gasRequirement, (ContractCallRecordBuilder) recordBuilder),
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java:81]: Instead of this cast it seems nicer to update [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java#L63) to dispatch with a type of `ContractCallRecordBuilder.class`. 🤔

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java [hunk 3]
```diff
@@ -89,7 +90,10 @@ public PricedResult execute() {
                     : GrantApprovalTranslator.ERC_GRANT_APPROVAL_NFT
                             .getOutputs()
                             .encodeElements();
-            return gasOnly(successResult(encodedOutput, gasRequirement), status, false);
+            return gasOnly(
+                    successResult(encodedOutput, gasRequirement, (ContractCallRecordBuilder) recordBuilder),
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java:94]: Same idea, can we just dispatch using `ContractCallRecordBuilder.class` as type?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java [hunk 4]
```diff
@@ -98,7 +99,7 @@ public PricedResult execute() {
             }
             return reversionWith(status, gasRequirement);
         } else {
-            return completionWith(status, gasRequirement);
+            return completionWith(gasRequirement, (ContractCallRecordBuilder) recordBuilder);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java:102]: Same idea.

**Review by tinker-michaelj — CHANGES_REQUESTED** [review]
Looks great, this seems like exactly the right fix @Ivo-Yankov!

Does seem there are unintentional changes in `TokenDeleteSpecs`; and would be cleaner (and a step toward some refactoring we have to do eventually) to just dispatch for a `ContractCallRecordBuilder` instead of casting.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java (hunk 1 above)
Comment (georgi-l95) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java]: Yep, addressed.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java (hunk 2 above)
Comment (georgi-l95) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java]: Thanks.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java (hunk 3 above)
Comment (georgi-l95) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java]: Thanks. Addressed.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java (hunk 4 above)
Comment (georgi-l95) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java]: Thanks. Addressed.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractHtsCall.java [hunk 5]
```diff
@@ -82,6 +82,15 @@ protected PricedResult completionWith(
         return gasOnly(successResult(output, gasRequirement, recordBuilder), recordBuilder.status(), isViewCall);
     }
 
+    protected PricedResult completionWith(
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractHtsCall.java:85]: Is this method used anywhere?

Comment (Ivo-Yankov) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractHtsCall.java]: This was a left-over from before reverting some of the changes in this PR. It's removed now.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @Ivo-Yankov !

**Review by georgi-l95 — APPROVED** [review]
