### PR TITLE
Always set a PRNG synth body (without range choice)

### LINKED ISSUE #4288: Always set the `UtilPrngTransactionBody` in synthetic record for `UtilPrng` contract
### Description

If the `PrngSystemPrecompiledContract` fails for some reason (probably `INSUFFICIENT_GAS`), it should still set the op-specific transaction body in its synthetic transaction.

### Steps to reproduce

Call `PrngSystemPrecompiledContract` with insufficient gas.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.30.5

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
- Always sets a `UtilPrngTransactionBody` in the synthetic transaction for a `PrngSystemPrecompiledContract` call.

**Related issue(s)**:
- Fixes #4288

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java [hunk 1]
```diff
@@ -214,13 +214,8 @@ private void trackPrngOutput(
...
     @VisibleForTesting
-    TransactionBody.Builder body(final Bytes randomNum) {
-        final var txnBody = TransactionBody.newBuilder();
-        if (randomNum == null) {
-            return txnBody;
-        }
-        final var body = UtilPrngTransactionBody.newBuilder();
-        return txnBody.setUtilPrng(body.build());
+    TransactionBody.Builder synthBody() {
+        return TransactionBody.newBuilder().setUtilPrng(UtilPrngTransactionBody.newBuilder());
```
Comment (steven-sheehy) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java:218]: Test?

Comment (steven-sheehy) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java:218]: How does the random value get populated im the body?

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java:218]: The random value bytes are populated in the child record of contractCall to `getPseudorandomSeed`.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java:218]: yeah, precompiles doesn't support giving a range parameter, since users can easily generate a pseudorandom number in a specified range using the seed by (integer value of seed % range) in solidity.
We just provide 256-bit pseudorandom seed using the first 256-bits of running hash of n-3 transaction record.

**Review by steven-sheehy — APPROVED** [review]
LGTM
