### PR TITLE
fixed code to pass CryptoUpdateSuite test

### LINKED ISSUE #8329: Start testing CryptoUpdateSuite
- [x] updateStakingFieldsWorks
- [ ] usdFeeAsExpectedCryptoUpdate
- [x] updateFailsWithOverlyLongLifetime
- [x] sysAccountKeyUpdateBySpecialWontNeedNewKeyTxnSign
- [x] canUpdateMemo
- [x] updateWithUniqueSigs
- [x] updateWithOneEffectiveSig
- [x] updateWithOverlappingSigs
- [x] updateFailsWithContractKey
- [x] updateFailsWithInsufficientSigs
- [x] cannotSetThresholdNegative
- [x] updateFailsIfMissingSigs
- [x] updateWithEmptyKeyFails
- [ ] updateMaxAutoAssociationsWorks

### PR DESCRIPTION
**Pull request by iwsimon**
Fixed code to pass CryptoUpdateSuite test.
Added stakednode = -1 and stakedaccount = null handling in rewards calculation 
Added unit test for payerAccount=deleted in PreHandleWorkflowImplTest

**Description**:

**Related issue(s)**:

Fixes #8329 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java [hunk 1]
```diff
@@ -307,7 +307,8 @@ private StakingInfo getStakingInfo(
 
         final var stakedNode = account.stakedNodeId();
         final var stakedAccount = account.stakedAccountId();
-        if (stakedNode != null) {
+        if (stakedNode != null && stakedNode != -1) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java:310]: nit : we can add a static final variable "SENTINEL_NODE_ID = -1" and use everywhere instead for clarity

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java [hunk 2]
```diff
@@ -102,13 +103,14 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
         // the target account must sign the transaction
         // 3. If the payer for the transaction is 0.0.2 or system admin, then no signatures are needed for the update
         final var targetAccountKeyMustSign = !waivers.isTargetAccountSignatureWaived(txn, payer);
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:106]: Curious `calculateFees` method is not implemented in this handler. Could you please create issue for that

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java [hunk 3]
```diff
@@ -244,19 +244,21 @@ private void adjustNodeStakes(
...
-                // in mid of the day, it will not receive rewards for that day.
-                // So, it will be leaving some rewards from its current node unclaimed.
-                // We need to record that, so we don't include them in the pendingRewards
-                // calculation later
-                final var effectiveStakeRewardStart = rewardableStakeStartFor(
-                        stakingRewardStore.isStakingRewardsActivated(), originalAccount, consensusNow);
-                stakeInfoHelper.increaseUnclaimedStakeRewards(
-                        currentStakedNodeId, effectiveStakeRewardStart, stakingInfoStore);
+            // -1 is a special value to remove the account's staked node ID.
+            if (currentStakedNodeId != -1) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java:248]: same as above , will be nice to use static variable with clear name for -1

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java [hunk 4]
```diff
@@ -180,6 +182,7 @@ private HapiSpec updateStakingFieldsWorks() {
                                 .logged());
     }
 
+    // @HapiTest recheck after TransactionRecord.getTranscationFee() is implemented
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java:185]: I think if `calculateFees` is implemented, it will pass

**Review by Neeharika-Sompalli — APPROVED** [review]
All the comments can be addressed in a different PR. LGTM!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java]: Defined both in StakeInfoHelper and used them in the code change.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java (hunk 3 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java]: updated

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java (hunk 2 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:107]: Created issue #8445 for this.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java (hunk 4 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java:185]: I will recheck this after #8445 completed.

Comment (Neeharika-Sompalli) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java:185]: I created an issue to implement calculateFees in all handlers. I will try to open branch for all handlers
