### PR TITLE
fix: ERC approve and remove scenarios

### LINKED ISSUE #10188: `ERCPrecompileSuite.someErc721ApproveAndRemoveScenariosPass()`

### PR DESCRIPTION
**Pull request by mustafauzunn**
**Description**:

Fix ERC approve and remove scenarios

**Related issue(s)**:

Fixes #10188 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java [hunk 1]
```diff
@@ -60,32 +64,89 @@ protected AbstractGrantApprovalCall(
...
+        return TransactionBody.newBuilder().cryptoDeleteAllowance(body).build();
+    }
+
+    private TransactionBody buildCryptoApproveAllowance(CryptoApproveAllowanceTransactionBody body) {
+        return TransactionBody.newBuilder().cryptoApproveAllowance(body).build();
+    }
+
+    private AccountID getOwnerId() {
+        final var nft = enhancement.nativeOperations().getNft(token.tokenNum(), amount.longValue());
+        return nft != null && nft.hasOwnerId()
```
Comment (tinker-michaelj) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java:144]: If the NFT was missing, this would return its token's treasury as its owner `AccountID`.

At this point have we verified the NFT exists? In that case we could use `requireNonNull(nft)` here?

Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java]: Noted. Thanks!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java [hunk 2]
```diff
@@ -88,15 +89,24 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
...
         for (final var allowance : op.nftAllowancesOrElse(emptyList())) {
             if (allowance.hasOwner()) {
-                context.requireKeyOrThrow(allowance.ownerOrThrow(), INVALID_ALLOWANCE_OWNER_ID);
+                final var store = context.createStore(ReadableAccountStore.class);
+                final var ownerId = allowance.ownerOrThrow();
+                final var owner = store.getAccountById(ownerId);
+                final var approvedForAll = owner.approveForAllNftAllowancesOrElse(emptyList()).stream()
+                        .anyMatch(approveForAll -> approveForAll.tokenId().equals(allowance.tokenId())
+                                && approveForAll.spenderId().equals(context.payer()));
+                if (approvedForAll) {
```
[the remark this answers is not in the document]
Comment (stoyanov-st) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java:98]: Noted

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java [hunk 3]
```diff
@@ -88,15 +89,24 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
...
+                    context.requireKeyOrThrow(context.payerKey(), INVALID_DELEGATING_SPENDER);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java:99]: ⚠️ This isn't necessary, and would actually break this call for a sender contract with a cryptographic admin key. I.e. we only need,
```
if (!context.payer().equals(ownerId) && !approvedForAll) {
         context.requireKeyOrThrow(ownerId, INVALID_ALLOWANCE_OWNER_ID);
}
```

**Review by tinker-michaelj — DISMISSED** [review]
There is one `if` condition we need to remove because it would break an HTS `CryptoDeleteAllowance` edge case.

But overall with all checks passing, LGTM! tyvm @mustafauzunn

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java (hunk 3 above)
Comment (stoyanov-st) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java]: Done, thanks!

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @mustafauzunn !

**Review by stoyanov-st — APPROVED** [review]
LGTM
