### PR TITLE
(EET) Add `ScheduleTypePatching` for running against saved state w/ missing price types

### LINKED ISSUE #1881: HTS-Restart-Performance-Hotspot-10k-61m failed for INSUFFICIENT_TX_FEE
### Description

Seems like some recent fee calculation for token creation causes this issue.

This error happens to both `master` and `release/0.16` branch.

### Steps to reproduce

slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1627278214219400

https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210726-043803-GCP-Daily-HTS-Restart-Perf-6N-6C/HTS-Restart-Performance-Hotspot-10k-61m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

Slack summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1627282241017300

### Additional context

In client node0's hapi-client-combined.log:
```
{ accountNum: 2102543 } } nodeAccountID { accountNum: 3 } transactionFee: 66757881 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoCreateAccount { key { ed25519: "\240\t^\266\257\315\027\255\226\346\341\t\222\325\312s17\275\327S\263\237%+\332V\327 P\214x" } initialBalance: 1000000000 proxyAccountID { } sendRecordThreshold: 5000000000000000000 receiveRecordThreshold: 5000000000000000000 autoRenewPeriod { seconds: 7776000 } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "}\221ki*,\"\321\233\362\2245\005g\337\265C\"\364\372\377\231\226\2704l.\264\341\362\031\"=$lk\225z\232H\344\272\314[\226rD\221\331\367\207\037\255\224*\225B\305\241%_\216\261\006" } sigPair { pubKeyPrefix: "\240" ed25519: "\330l*W\252&\321\235\024\371\226\332f\237F}\230o\255\220\236b\337\344\314\227\324\313o<%\222Y\t\216\331\354]\034e\224\2541\221O\374\371\r;\266\214H\316\257+\0211\022\025\245q\210\r\b" }
2021-07-26 04:43:19.825 WARN   170  FeeCalculator - Unable to calculate fee for op TokenCreate, using max fee!
java.lang.NullPointerException: null
	at com.hederahashgraph.fee.FeeBuilder.getFeeObject(FeeBuilder.java:149) ~[SuiteRunner.jar:?]
	at com.hederahashgraph.fee.FeeBuilder.getFeeObject(FeeBuilder.java:169) ~[SuiteRunner.jar:?]
	at com.hederahashgraph.fee.FeeBuilder.getTotalFeeforRequest(FeeBuilder.java:138) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeeCalculator.forOp(FeeCalculator.java:168) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeeCalculator.forActivityBasedOp(FeeCalculator.java:127) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.transactions.token.HapiTokenCreate.feeFor(HapiTokenCreate.java:229) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.finalizedTxn(HapiSpecOperation.java:317) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.finalizedTxn(HapiSpecOperation.java:282) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:145) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:36) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:45) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.ProviderRun.submitOp(ProviderRun.java:109) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:319) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:227) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:178) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:128) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:121) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:602) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:603) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:579) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:579) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:547) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:468) [SuiteRunner.jar:?]
2021-07-26 04:43:19.834 INFO   148  HapiTxnOp - 'RunTokenTransfers' -  submitting HapiTokenCreate{node=0.0.3, token=token0} via body=transactionID { transactionValidStart { seconds: 1627274539 nanos: 305 } accountID { accountNum: 2102543 } } nodeAccountID { accountNum: 3 } transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" tokenCreation { name: "token0592236" symbol: "KDEHDNPL" initialSupply: 20000 treasury { accountNum: 2102547 } expiry { seconds: 1634274599 nanos: 817901000 } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "U\323\324\2511A\346\224\260`\217!\342\342X}\0036z\243\363W\237a4\337\307m\262\212\035\355R\327\356\351|Hj\001\277\215\206\303x\255C\243\024\253\301Z\274Y=C\320F\361zbjm\001" } sigPair { pubKeyPrefix: "\240" ed25519: "\223\006#P\227M=\004\226,\342r\244\266Br}\312\252\264\275~\234\352\374\211\372F\037\201N\276?N#M?\270\317\242v(\342f\231\034\356=v\243W%\357\fQ\202\236\004n\330\231\315\323\a" }
2021-07-26 04:43:19.850 INFO   208  HapiTxnOp - 'RunTokenTransfers' -  HapiTokenCreate{sigs=2, node=0.0.3, token=token0} Wrong actual precheck status INSUFFICIENT_TX_FEE, expecting OK
2021-07-26 04:43:19.852 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - HapiTokenCreate{sigs=2, node=0.0.3, token=token0} failed Wrong precheck status! Expected OK, actual INSUFFICIENT_TX_FEE!
2021-07-26 04:43:19.852 ERROR  38   CustomSpecAssert - Operation 'HapiTokenCreate{sigs=2, node=0.0.3, token=token0}' :: Wrong precheck status! Expected OK, actual INSUFFICIENT_TX_FEE
2021-07-26 04:43:19.852 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual INSUFFICIENT_TX_FEE failed {}!

``` 

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by tinker-michaelj**
✅  &nbsp;Run completed without `INSUFFICIENT_TX_FEE` or NPE's [here](https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1627446851436200). 

⚠️ &nbsp;But further investigation is needed into the `TokenTransfersLoadProvider`; it is not submitting nearly the expected TPS
  - The [ServicesStats0.csv](https://github.com/hashgraph/hedera-services/files/6890422/ServicesStats0.csv) for the above run shows ~32µ secTransH, so there is no reason that TPS should not be 10k.

**Related issue(s)**:
- Closes #1881

**Changes**:
- Add a [`ScheduleTypePatching` helper](https://github.com/hashgraph/hedera-services/blob/01881-M-FixEetTokenCreateFeeCalc/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/ScheduleTypePatching.java#L36) for use in the [`FeeAndRatesProvider.downloadFeeSchedule()` method](https://github.com/hashgraph/hedera-services/blob/01881-M-FixEetTokenCreateFeeCalc/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java#L151).
    * `ScheduleTypePatching` uses the [`RequiredPriceTypes` helper](https://github.com/hashgraph/hedera-services/blob/01881-M-FixEetTokenCreateFeeCalc/hapi-fees/src/main/java/com/hedera/services/pricing/RequiredPriceTypes.java#L43) extracted to _hapi-fees/_ to "patch" any missing `SubType` prices with the default prices.
    * `AwareFcfsUsagePrices` [also uses](https://github.com/hashgraph/hedera-services/blob/01881-M-FixEetTokenCreateFeeCalc/hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java#L193) the `RequiredPriceTypes` helper to avoid duplication.
- Update the _test-clients/src/main/resource/FeeSchedule.json_ to the 0.16.0 _feeSchedules.json_.
- Slightly extend the lifetime of a to-be-detached account in the `GracePeriodRestrictionsSuite` to stabilize CI.

### CODE REVIEW

**Review by anighanta — APPROVED** [review]
Awesome work. LGTM

File: hapi-fees/src/main/java/com/hedera/services/pricing/RequiredPriceTypes.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
+package com.hedera.services.pricing;
+
+/*-
+ * ‌
+ * Hedera Services Node
```
Comment (qnswirlds) [inline hapi-fees/src/main/java/com/hedera/services/pricing/RequiredPriceTypes.java:5]: should be `Hedera Services API Fees` for this file and all files in `hapi-fees`. I hope it is not generated from `mvn license:update-file-header` or we have to investigate and fix it.
