### PR TITLE
fix: Setup metrics for WritableKVStateStack

### LINKED ISSUE #12485: Fix utilization metrics
Utilization metrics do not show up in Grafana. This needs to be investigated and fixed.

### PR DESCRIPTION
**Pull request by netopyr**
This PR ensure metrics are also setup for `WritableKVStateStack`

Fixes #12485

### CODE REVIEW

**Review by Neeharika-Sompalli — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKvStateMetrics.java [hunk 1]
```diff
@@ -60,7 +60,7 @@ public OnDiskWritableKvStateMetrics(
                 .withFormat("%,d");
         metrics.getOrCreate(totalUtilizationConfig);
 
-        final double relativeFactor = 100.0 / maxCapacity;
+        final double relativeFactor = 100.0 / Math.max(1.0, maxCapacity); // in some tests, maxCapacity is 0
```
Comment (netopyr) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKvStateMetrics.java:63]: This is just a workaround for now. We need to fix the tests in the future.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKvStateMetrics.java:63]: Makes sense
