### PR TITLE
Don't allow the tipset algorithm to create ancient self events.

### LINKED ISSUE #8616: Event creator creates ancient events
During the new consensus testing, a reconnect state has no events. After the reconnect is done, the event creator creates an event with no parents, which makes it throw an exception because that event is ancient. 

http://35.247.76.217:8095/lpetrovic05/05287-consensus-changes-2/6N/Migration/20230913-091959-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/node0005/swirlds.log
```
2023-09-13 09:26:32.315 332      INFO  STATE_TO_DISK    <<platform-core: signed-state-file-manager 5>> SignedStateFileWriter: Finished writing state for round 3503 to disk. Reason: RECONNECT, directory: /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.swirlds.demo.migration.MigrationTestingToolMain/5/123/3503 {"round":3503,"freezeState":false,"reason":"RECONNECT","directory":"file:///opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.swirlds.demo.migration.MigrationTestingToolMain/5/123/3503/"} [com.swirlds.logging.payloads.StateSavedToDiskPayload]
2023-09-13 09:26:32.316 333      INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 3.2 s in RECONNECT_COMPLETE. Now in CHECKING {"oldStatus":"RECONNECT_COMPLETE","newStatus":"CHECKING"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2023-09-13 09:26:32.322 334      ERROR EXCEPTION        <<event-creator>> TipsetTracker: Rejecting ancient event from 5 with generation 0. Current minimum generation non-ancient is 14087
2023-09-13 09:26:32.325 335      ERROR EXCEPTION        <<event-creator>> AbstractThreadConfiguration: exception on thread <event-creator>
java.lang.IllegalArgumentException: event (creator: 5, generation: 0, hash: b2a5c4036a84) is not in the tipset tracker
	at com.swirlds.platform.event.tipset.TipsetWeightCalculator.addEventAndGetAdvancementWeight(TipsetWeightCalculator.java:185) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.tipset.TipsetEventCreatorImpl.buildAndProcessEvent(TipsetEventCreatorImpl.java:377) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.tipset.TipsetEventCreatorImpl.createEventByOptimizingAdvancementWeight(TipsetEventCreatorImpl.java:281) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.tipset.TipsetEventCreatorImpl.maybeCreateEvent(TipsetEventCreatorImpl.java:225) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.tipset.SyncTipsetEventCreationManager.maybeCreateEvent(SyncTipsetEventCreationManager.java:90) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.waitForItem(QueueThreadImpl.java:287) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:250) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #8616

### CODE REVIEW

**Review by edward-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java [hunk 1]
```diff
@@ -268,10 +273,11 @@ private GossipEvent createEventByOptimizingAdvancementWeight() {
...
-            // There exist no parents that can advance consensus, and this is not our first event.
-            // The only time it's ok to create an event with no other parent is when we are creating
-            // our first event.
+        if (bestOtherParent == null
+                && (minimumGenerationNonAncient > GENERATION_UNDEFINED + 1 || lastSelfEvent != null)) {
+            // If there are no available other parents, it is only legal to create a new event if we are
+            // creating a genesis event. In order to create a genesis event, we must have never created
+            // an event before and the current minimum generation non ancient must have never been advanced.
             return null;
         }
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java:282]: It might just be me, but I found the logic as written here difficult to grasp - what do you think about this alternative layout? Up to you if you'd like it to stay as-is, though

```
        if (bestOtherParent == null) {
            // If there are no available other parents, it is only legal to create a new event if we are
            // creating a genesis event. In order to create a genesis event, we must have never created
            // an event before and the current minimum generation non ancient must have never been advanced.
            if (minimumGenerationNonAncient > GENERATION_UNDEFINED + 1 || lastSelfEvent != null) {
                // event creation isn't legal
                return null;
            }
            
            // we are creating a genesis event, so we can use a null other parent
            return buildAndProcessEvent(null);
        } else {
            tipsetMetrics.getTipsetParentMetric(bestOtherParent.getCreator()).cycle();
            return buildAndProcessEvent(bestOtherParent);
        }
```

**Review by alittley — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java [hunk 2]
```diff
@@ -69,7 +69,11 @@ public class TipsetEventCreatorImpl implements TipsetEventCreator {
     private final ChildlessEventTracker childlessOtherEventTracker;
     private final TransactionSupplier transactionSupplier;
     private final SoftwareVersion softwareVersion;
-    /** The address book for the current network. */
+    private long minimumGenerationNonAncient = GENERATION_UNDEFINED + 1;
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java:72]: `GraphGenerations.FIRST_GENERATION`
I know, the constants should be in a single place, but we can fix it in the future

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java [hunk 3]
```diff
@@ -268,10 +273,11 @@ private GossipEvent createEventByOptimizingAdvancementWeight() {
             }
         }
 
-        if (lastSelfEvent != null && bestOtherParent == null) {
-            // There exist no parents that can advance consensus, and this is not our first event.
-            // The only time it's ok to create an event with no other parent is when we are creating
-            // our first event.
+        if (bestOtherParent == null
+                && (minimumGenerationNonAncient > GENERATION_UNDEFINED + 1 || lastSelfEvent != null)) {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java:277]: I think the logic should be: "don't create ancient events"
So even if we have parents, but they are ancient, we should not create an event

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java:277]: `childlessOtherEventTracker.getChildlessEvents()` will never return ancient events, so we are guaranteed that any parent we choose will have a generation that produces a non-ancient child.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java:72]: fixed

**Review by lpetrovic05 — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/tipset/TipsetEventCreatorImpl.java:282]: Refactored.

```
        if (bestOtherParent == null) {
            // If there are no available other parents, it is only legal to create a new event if we are
            // creating a genesis event. In order to create a genesis event, we must have never created
            // an event before and the current minimum generation non ancient must have never been advanced.
            if (minimumGenerationNonAncient > GENERATION_UNDEFINED + 1 || lastSelfEvent != null) {
                // event creation isn't legal
                return null;
            }

            // we are creating a genesis event, so we can use a null other parent
            return buildAndProcessEvent(null);
        }

        tipsetMetrics.getTipsetParentMetric(bestOtherParent.getCreator()).cycle();
        return buildAndProcessEvent(bestOtherParent);
```

**Review by lpetrovic05 — APPROVED** [review]
