### PR TITLE
08105 Make DataFileWriter gracefully handle interrupts.

### LINKED ISSUE #8105: Reconnect failure: "this.writingMmap" is null
The following failure was observed in one of the nightly 0.41 tests.

http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/Reconnect/20230818-094040-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

From node 3's logs (i.e. the learner).
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.MappedByteBuffer.position()" because "this.writingMmap" is null
	at com.swirlds.merkledb.files.DataFileWriter.computePaddingLength(DataFileWriter.java:319) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.files.DataFileWriter.finishWriting(DataFileWriter.java:291) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.finishCurrentCompactionFile(DataFileCollection.java:511) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.pauseCompaction(DataFileCollection.java:541) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.pauseMerging(HalfDiskHashMap.java:338) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.pauseMerging(MerkleDbDataSource.java:506) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.MerkleDb.importDataSource(MerkleDb.java:375) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.MerkleDb.copyDataSource(MerkleDb.java:357) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSourceBuilder.copy(MerkleDbDataSourceBuilder.java:125) ~[swirlds-jasperdb-0.41.0-alpha.4.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.setupWithOriginalNode(VirtualRootNode.java:1364) ~[swirlds-virtualmap-0.41.0-alpha.4.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.LearnerThread.handleCustomRootInitialLesson(LearnerThread.java:131) ~[swirlds-common-0.41.0-alpha.4.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.LearnerThread.extractNodeFromLesson(LearnerThread.java:155) ~[swirlds-common-0.41.0-alpha.4.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.LearnerThread.run(LearnerThread.java:258) ~[swirlds-common-0.41.0-alpha.4.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:126) ~[swirlds-common-0.41.0-alpha.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR fixes possible reconnect failure which may happen due to unfortunate timing of a compaction pause. 
Also, it simplifies `DataFileWriter` by removing lock file because it's not necessary. `Files.createFile(path);` provides guarantees of atomic disk operation. 
Also, this PR reproduces the failure scenario in `DataFileWriterTest`.

**Related issue(s)**:

Fixes #8105 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 1]
```diff
@@ -124,21 +116,15 @@ public DataFileWriter(
         this.dataItemSerializer = dataItemSerializer;
         this.creationInstant = creationTime;
         this.path = createDataFilePath(filePrefix, dataFileDir, index, creationInstant);
-        this.lockFilePath = getLockFilePath(path);
-        if (Files.exists(lockFilePath)) {
-            throw new IOException("Tried to start writing to data file [" + path + "] when lock file already existed");
-        }
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:130]: Since lock files are now removed, `DataFileCommon.getLockFilePath()` may be obsolete. Besides that, `DataFileCommon.isFullyWrittenDataFile()` needs to be adjusted to not check lock files any longer.

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 2]
```diff
@@ -149,9 +135,15 @@ public DataFileWriter(
      * @throws IOException if I/O error(s) occurred
      */
     private void moveMmapBuffer(final int currentMmapPos) throws IOException {
-        mmapPositionInFile += currentMmapPos;
-        closeMmapBuffer();
-        writingMmap = writingChannel.map(MapMode.READ_WRITE, mmapPositionInFile, MMAP_BUF_SIZE);
+        try (FileChannel channel = FileChannel.open(path, StandardOpenOption.READ, StandardOpenOption.WRITE)) {
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:138]: final

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 3]
```diff
@@ -149,9 +135,15 @@ public DataFileWriter(
...
+            MappedByteBuffer newMap =
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:139]: final

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:130]: Yes, that's right. I updated `DafaFileCommon` as you suggested.

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java]: Fixed

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 4]
```diff
@@ -149,9 +135,35 @@ public DataFileWriter(
...
+    /**
+     * This method addresses the fact that the mapped byte buffer doesn't have the same safeguards
+     * as the regular FileChannel. It's possible to create a mapped byte buffer even if there is not enough
+     * disk space to map it. This code is trying to identify this situation and throw an exception.
+     *
+     * @param newMap the mapped byte buffer to verify
+     */
+    private static void verifyMmapCorrectness(final MappedByteBuffer newMap) throws IOException {
+        // theoretically it's possible, we should check it
+        if(newMap == null) {
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:157]: space

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 5]
```diff
@@ -149,9 +135,35 @@ public DataFileWriter(
...
+            throw new IOException("Failed to map file channel to memory");
+        }
+        // The idea is to force this mapping to happen. By default, actual mapping happens lazily.
+        try {
+            newMap.put(MMAP_BUF_SIZE - 1, (byte) -1);
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:162]: A named byte constant with a less common value.

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 6]
```diff
@@ -149,9 +135,35 @@ public DataFileWriter(
...
+            if (newMap.get(MMAP_BUF_SIZE - 1) != -1) throw new IOException("Fatal error when creating mmap. Possibly,  out of disk memory.");
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:163]: Does spotless allow single-line "if" statements? Even if so, I'd put the "throw" statement into a { } block to make it easier to read.

Comment (artemananiev) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:163]: The line looks too long anyway. Also, double whitespace after "Possibly,"

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java (hunk 4 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java]: Fixed

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java (hunk 5 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java]: Fixed

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java (hunk 6 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java]: Fixed

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java [hunk 7]
```diff
@@ -52,12 +51,9 @@ public final class DataFileWriter<D> {
 
     /** Mapped buffer size */
     private static final int MMAP_BUF_SIZE = PAGE_SIZE * 1024 * 4;
+    /** A value to write to verify a newly created mapped buffer */
+    public static final int PROBE_VALUE = 42;
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java:55]: Remove.

**Review by OlegMazurov — APPROVED** [review]

**Comment by imalygin** [comment]
Here is a ticket to address the issue uncovered during the testing of this PR https://github.com/hashgraph/hedera-services/issues/8205

**Review by OlegMazurov — APPROVED** [review]
