### PR TITLE
fix: use concurrent hashmap instead of synchroniztion for recordcache

### LINKED ISSUE #10127: `ReadableKVStateBase.readCache` is not properly synchronized
### Description

The following exception is thrown by a node when under heavy load:
```
2023-11-27 20:33:31.143 ERROR 133  PreHandleWorkflowImpl - Unexpected error while pre handling a transaction!
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
        at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1994) ~[?:?]
        at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2110) ~[?:?]
        at java.base/java.util.HashMap.treeifyBin(HashMap.java:778) ~[?:?]
        at java.base/java.util.HashMap.putVal(HashMap.java:650) ~[?:?]
        at java.base/java.util.HashMap.put(HashMap.java:618) ~[?:?]
        at com.hedera.node.app.spi.state.ReadableKVStateBase.markRead(ReadableKVStateBase.java:124) ~[app-spi-0.45.0-SNAPSHOT.jar:?]
        at com.hedera.node.app.spi.state.ReadableKVStateBase.get(ReadableKVStateBase.java:70) ~[app-spi-0.45.0-SNAPSHOT.jar:?]
        at com.hedera.node.app.service.token.impl.ReadableAccountStoreImpl.getAccountLeaf(ReadableAccountStoreImpl.java:132) ~[app-service-token-impl-0.45.0-SNAPSHOT.jar:?]
        at com.hedera.node.app.service.token.impl.ReadableAccountStoreImpl.getAccountById(ReadableAccountStoreImpl.java:104) ~[app-service-token-impl-0.45.0-SNAPSHOT.jar:?]
        at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.preHandleTransaction(PreHandleWorkflowImpl.java:174) ~[HederaNode.jar:?]
        at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.lambda$preHandle$0(PreHandleWorkflowImpl.java:128) ~[HederaNode.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) [?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:?]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) [?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```
The reason is unsynchronized calls to `markRead() -> readCache.put()` from multiple threads.

### Steps to reproduce

The exception was observed when running the `NftTransferLoadTest` benchmark (during the token creation phase).

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

Linux

### PR DESCRIPTION
**Pull request by povolev15**
This PR fix the ReadableKVStateBase.readCache is not properly synchronized

**Related issue(s)**:

Fixes #10127

### CODE REVIEW

**Review by jsync-swirlds — APPROVED** [review]

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java [hunk 1]
```diff
@@ -131,6 +137,7 @@ protected final void markRead(@NonNull K key, @Nullable V value) {
      * @return Whether it has been read
      */
     protected final boolean hasBeenRead(@NonNull K key) {
-        return readCache.containsKey(key);
+        var keyExistence = readCache.get(key);
+        return keyExistence != null && keyExistence != marker;
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:141]: Why do we need to check `keyExistence != marker;` ?

Comment (povolev15) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:141]: Because we put a marker into the reacCache and we would like to return true just if it is not marker and keyExistance is not null.

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java [hunk 2]
```diff
@@ -121,7 +126,8 @@ public void reset() {
      * @param value The value
      */
     protected final void markRead(@NonNull K key, @Nullable V value) {
-        readCache.put(key, value);
+        if (value == null) readCache.put(key, (V) marker);
+        else readCache.put(key, value);
```
[the remark this answers is not in the document]
Comment (povolev15) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:130]: fixed

**Review by jsync-swirlds — APPROVED** [review]

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java (hunk 1 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:144]: There is an interaction with line 72, so if this is changed, then line 72 cannot call this method and must implement the marker check.

Comment (tinker-michaelj) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:144]: Agreed with @Neeharika-Sompalli , the implementation here needs to remain `readCache.containsKey(key)`.

Comment (netopyr) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:144]: You are right. Sorry, did not think this through.

Comment (povolev15) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java:144]: fixed it

**Review by jsync-swirlds — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Thanks @povolev15
