### PR TITLE
854 894 record stream v5

### LINKED ISSUE #854: Refactor RecordStream
**Design Doc**:
[Swirlds Chained Object File Stream Design doc](https://hederatest.sharepoint.com/:w:/r/sites/Engineering/_layouts/15/Doc.aspx?sourcedoc=%7BBE14CE50-8223-4F87-973E-4E8641246CAB%7D&file=Swirlds%20Chained%20Object%20File%20Stream.docx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=051e005b-e05e-44e3-adc4-812c3ba613ab)
[Stream File Format Doc](https://hederatest.sharepoint.com/:w:/r/sites/Engineering/_layouts/15/Doc.aspx?sourcedoc=%7BE24A2E92-797D-4E26-91B0-9FBB41C46BA0%7D&file=Record%20and%20Event%20Stream%20File%20Formats.docx&nav=eyJjIjoxNjU0MDM5OTUyfQ&action=default&mobileredirect=true&cid=cffc8899-9c3a-4c4a-b450-37bc53506873)

**Main goal**: 
once a node does a reconnect, it should be able to continue the running hash and save record stream files which would be same as the files on other nodes

**Solution**:
- [ ] use new object stream file format for record stream: 

**record stream .rcd file**:

Name | Type (Bytes) | Description | MD
-- | -- | -- | --
Record Stream File Format Version | int (4) | Record stream file format version,  Value: 5 | y
Hapi Proto Major Version | int (4) | Matches NetworkGetVersionInfo.hapiProtoVersion Major.Minor.Patch Major version: 0;  Minor version: 9; Patch version: 0 | y
Hapi Proto Minor Version | int (4)
Hapi Proto Patch Version | int (4)
Object stream version | int (4) | Value: 1  This defines the format of the remainder of the file. This version number is used when parsing a stream file with methods defined in swirlds-common package | y
Start Object Running Hash | byte[] | Running Hash of all RecordStreamObject before writing this file. See `Hash object` table below for details | y
1st RecordStreamObject | byte[] | Serialized RecordStreamObject bytes. See ` RecordStreamObject ` table below for details | n
2nd RecordStreamObject | byte[] | ... | n
... | ... | ... | n
End Object Running Hash | byte[] | Running Hash of all RecordStreamObject before closing this file. | y

**RecordStreamObject**

Name | Type (Bytes) | Description
-- | -- | --
Class ID | long (8) | Value: 0xe370929ba5429d8b
Class Version | int (4) | Value: 1
Length of TransactionRecord | int (4) | Byte size of the following TransactionRecord message
TransactionRecord | byte[] | Serialized TransactionRecord message bytes
Length of Transaction | int (4) | Byte size of the following Transaction message
Transaction | byte[] | Serialized Transaction message bytes

**.rcd_sig**: 

Name | Type (Bytes) | Description
-- | -- | --
Signature File Format Version | byte | Value: 5
Object Stream Signature Version | int (4) | Value: 1   This defines the format of the remainder of the signature file. This version number is used when parsing a signature file with methods defined in swirlds-common package
Entire .rcd Hash | byte[] | Hash of the entire corresponding *.rcd file
Signature on hash bytes of Entire.rcd Hash | byte[] | A signature object generated by signing the hash bytes of Entire Hash. See ` Signature ` table below for details
Metadata .rcd Hash | byte[] | Metadata Hash of the corresponding *.rcd file
Signature on hash bytes of Metadata .rcd Hash | byte[] | A signature object generated by signing the hash bytes of Metadata Hash

- [x] modify existing code for record stream to use new `LinkedObjectStream` classes implemented in https://github.com/swirlds/swirlds-platform/pull/2737

- [x] add a child to `ServicesState`: a `RecordsRunningHashLeaf` which contains a RunningHash `runningRecordsHash`, which is a hash of all consensus Transaction and TransactionRecord up to the consensusTime

- [x] at restart for migration, the initial value of the Hash in `RecordsRunningHashLeaf` should be the Hash loaded from the last .rcd_sig file in the record stream directory;

- [x] define a `RecordStreamObject` which contains a pair of Transaction and TransactionRecord, which implements `SerializableRunningHashable` and `Timestamped`.

- [x] define a `RecordStreamManager` class for calculating running hash  and record streaming, which contains: 
- a `multiStream`, whose nextStreams are: a `hashQueueThread`, and a `writeQueueThread` when record streaming is enabled;
- a `hashQueueThread` whose nextStream is a `hashCalculator`;
- a `hashCalculator` for calculating Hash. Its nextStream is a `runningHashCalculator`
- a `runningHashCalculator` for calculating runningHash each time a `RecordStreamObject` is passed to it
- a `writeQueueThread` whose nextStream is a `fileWriter`;
- a `TimestampStreamFileWriter<RecordStreamObject>` which receives `RecordStreamObject`, writes to file, and generates signature file;
- a `Hash initialHash`, which is initialized as empty Hash, and is set to be the `runningRecordsHash` loaded from `SwirldsState` at restart; if `SwirldsState` doesn't contain `runningRecordsHash`, it should be the Hash loaded from the last .rcd_sig file in the record stream directory;

- [x] add a `recordStreamManager` field into `ServicesContext`; 
`AwareProcessLogic.addForStreaming()` passes a `RecordStreamObject` to `recordStreamManager`,
and update the `RunningHash` instance in `RecordsRunningHashLeaf` in `ServicesState` to be the `RunningHash` instance of this new `RecordStreamObject`;
the `Hash` object in the `RunningHash` instance would be calculated and set by the runningHashCalculator in the RecordStreamManager

- [x] should switch mode for `TimestampStreamFileWriter` at restart/reconnect 
set `startWriteAtCompleteWindow` for `TimestampStreamFileWriter`
if `isReconnect`, `startWriteAtCompleteWindow` should be set to be true, start to write streams file when encountering the first consensus record which is in a different period with previous record;
if `isReconnect` is false, which means loading from signed state at restart, `startWriteAtCompleteWindow` should be set to be false, start to write record stream file for the first consensus record.
- [ ] modify RecordStreamValidator in regression to accommodate the changes in record stream files

**Testing** 
- [ ] unit test coverage
- [ ] run Restart tests and validate record stream files;
- [ ] run Reconnect tests and validate record stream files;

**Impact** : 

mirror node need to change the method to parse record stream and signature files.

### PR DESCRIPTION
**Pull request by QianSwirlds**
for review purpose

**Related issue(s)**:
Closes #854

**Summary of the change**:
implement record stream version 5

**External impacts**:
mirror node side need to make changes because of file format change.

**Applicable documentation**
[Swirlds Chained Object File Stream Design doc](https://hederatest.sharepoint.com/:w:/r/sites/Engineering/_layouts/15/Doc.aspx?sourcedoc=%7BBE14CE50-8223-4F87-973E-4E8641246CAB%7D&file=Swirlds%20Chained%20Object%20File%20Stream.docx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=051e005b-e05e-44e3-adc4-812c3ba613ab)
[Stream File Format Doc](https://hederatest.sharepoint.com/:w:/r/sites/Engineering/_layouts/15/Doc.aspx?sourcedoc=%7BE24A2E92-797D-4E26-91B0-9FBB41C46BA0%7D&file=Record%20and%20Event%20Stream%20File%20Formats.docx&nav=eyJjIjoxNjU0MDM5OTUyfQ&action=default&mobileredirect=true&cid=cffc8899-9c3a-4c4a-b450-37bc53506873)

passed regression tests:

Crypto-Restart-1.5k-10m (Dec 30)
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609356727374200

AllProtectedFilesUpdate-Reconnect-1-12m (Jan 4)
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609785250409800

Crypto-Restart-RecordStreamV5-1.5k-10m (Jan 5)
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609873082420500

The 3 tests passed on Jan 6
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609956292443200

`Crypto-Migration-Testnet-100-5m` is failing, which is also failing in `894-M-with-sdk-0.8.0-alpha.1 ` branch

### CODE REVIEW

**Review by qnswirlds — COMMENTED** [review]
Some files were missing license header. I added those. Also many new lines of code were not covered by tests. We will need to add more unit tests for them.

**Comment by QianSwirlds** [comment]
> Some files were missing license header. I added those. Also many new lines of code were not covered by tests. We will need to add more unit tests for them.

Thanks @qnswirlds ! I will add more unit tests for new lines today.

**Comment by QianSwirlds** [comment]
Hi @tinker-michaelj , I tried to add you as a reviewer, but it seems like your id cannot be added as reviewer..
would you please review this PR when you are available? Thank you!

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java [hunk 1]
```diff
@@ -156,6 +170,11 @@ public void initialize(MerkleInternal previous) {
 			log.info("Created disk file system after <=0.9.0 state restoration");
 			skipDiskFsHashCheck = true;
 		}
+		if (runningHashLeaf() == null) {
+			setChild(ChildIndices.RECORD_STREAM_RUNNING_HASH,
+					new RecordsRunningHashLeaf(new RunningHash()));
+			log.info("Created RecordsRunningHashLeaf after <=0.110.0 state restoration");
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/ServicesState.java:176]: nit : Should be`0.11.0` instead of `0.110.0`

Comment (QianSwirlds) [reply hedera-node/src/main/java/com/hedera/services/ServicesState.java]: modified. Thanks @Neeharika-Sompalli !

File: hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java [hunk 2]
```diff
@@ -1687,6 +1731,58 @@ public MerkleDiskFs diskFs() {
...
+	 * When recordsInitialHash is read, the RecordStreamManager might not be initialized yet,
+	 * because RecordStreamManager can only be initialized after system files are loaded so that enableRecordStream
+	 * setting is read.
+	 * Thus we save the initialHash in the context, and use it when initializing RecordStreamManager
+	 *
+	 * @param recordsInitialHash
+	 * 		initial running Hash of records
+	 */
+	public void setRecordsInitialHash(final Hash recordsInitialHash) {
+		if (recordsInitialHash != null) {
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java:1774]: If there are two hash values here, how to decide which one to keep?

File: hedera-node/src/main/java/com/hedera/services/stream/RecordStreamObject.java [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+	}
+
+	@Override
+	public boolean equals(Object obj) {
+		if (obj == null || obj.getClass() != getClass()) {
+			return false;
+		}
+		if (this == obj) {
+			return true;
+		}
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/stream/RecordStreamObject.java:150]: Not a big deal. It's probably more efficient to put the `==` at the beginning.

File: hedera-node/src/main/java/com/hedera/services/legacy/stream/RecordStream.java [hunk 4]
```diff
@@ -466,21 +472,28 @@ public static boolean isRecordSigFile(File file) {
...
-	private byte[] readPrevFileHash(String directory) {
-		File dir = new File(directory);
-		File[] files = dir.listFiles();
-		Optional<File> lastSigFileOptional = Arrays.stream(files).filter(file -> isRecordSigFile(file))
-				.max(Comparator.comparing(File::getName));
-		if (lastSigFileOptional.isPresent()) {
-			File lastSigFile = lastSigFileOptional.get();
-			return getFileHashFromSigFile(lastSigFile);
+	public static byte[] readPrevFileHash(String directory) {
+		if (directory != null) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/legacy/stream/RecordStream.java:482]: nit : Instead of multiple `if` conditions inside if , it will be better to return `return new byte[DigestType.SHA_384.digestLength()];` if `directory == null` initially.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM

File: hedera-node/src/main/java/com/hedera/services/legacy/stream/RecordStream.java (hunk 4 above)
Comment (QianSwirlds) [reply hedera-node/src/main/java/com/hedera/services/legacy/stream/RecordStream.java:482]: Thank you @Neeharika-Sompalli .
because if `directory == null`, or the directory doesn't contain any file, or there is not any .rcd_sig file in this directory, we will `return new byte[DigestType.SHA_384.digestLength()];`

File: hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java (hunk 2 above)
Comment (QianSwirlds) [reply hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java]: yes, agreed. Removed this null check. Thanks @ljianghedera

**Review by ljianghedera — APPROVED** [review]
LGTM

File: hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java [hunk 5]
```diff
@@ -1258,16 +1291,27 @@ public void updateFeature() {
...
+	 */
+	public void initRecordStreamManager() {
+		try {
+			recordStreamManager = new RecordStreamManager(
 					platform,
 					runningAvgs(),
-					nodeAccount(),
-					properties().getStringProperty("hedera.recordStream.logDir"),
-					properties());
+					PropertiesLoader.isEnableRecordStreaming(),
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java:1307]: Again, no need to change for this PR, but worth noting that `PropertiesLoader` will be removed shortly. Main three reasons are:

1. Methods that directly access `PropertiesLoader` instead of using an injected `PropertySource` are less testable.
2. `PropertiesLoader` puts the default properties in code (`ApplicationConstants`) instead of externalizing (_src/main/resources/bootstrap.properties_). 
3. In `dev` mode, there are race conditions triggered by a `FileUpdate` to `0.0.121` when multiples nodes are running in the same JVM and sharing a classloader-scoped singleton instead of a `ServicesContext`-scoped singleton.

File: hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java [hunk 6]
```diff
@@ -1258,16 +1291,27 @@ public void updateFeature() {
...
 	}
 
-	public RecordStream recordStream() {
-		if (recordStream == null) {
-			recordStream = new RecordStream(
+	public RecordStreamManager recordStreamManager() {
+		return recordStreamManager;
+	}
+
+	/**
```
Comment (tinker-michaelj) [inline hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java:1298]: Don't need to change for this PR, but if you want the ability to dynamically override record streaming (i.e. without a network restart), we would want to inject the `RecordStreamManager` with the `GlobalDynamicProperties` singleton.

**Review by tinker-michaelj — APPROVED** [review]
Awesome work @QianSwirlds!

There may be an opportunity to simplify creation of the `RecordStreamManager` by constructing it with a reference to `GlobalDynamicProperties` (instead of explicitly waiting for `0.0.121` to be initialized and then injecting its needed property values).

But this can certainly wait for a future PR. Very nice job.

File: hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java (hunk 5 above)
Comment (QianSwirlds) [reply hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java:1307]: got it, thank you very much for the detailed explanation! @tinker-michaelj

**Comment by QianSwirlds** [comment]
> Awesome work @QianSwirlds!
> 
> There may be an opportunity to simplify creation of the `RecordStreamManager` by constructing it with a reference to `GlobalDynamicProperties` (instead of explicitly waiting for `0.0.121` to be initialized and then injecting its needed property values).
> 
> But this can certainly wait for a future PR. Very nice job.

Thank you so much! @tinker-michaelj

**Comment by Neeharika-Sompalli** [comment]
Passed Tests : 
1. `Misc-Basic-1-21m.json` - https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1610733023038100
2. `Update`- on 0.8.1 sdk - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1610753145005000
3. `Performance` - 8K Crypto and 10K HCS  https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1610739469004600
4. `Platform Tests` - https://hedera-hashgraph.slack.com/archives/CJ1P4A2NS/p1610738553016600

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by qnswirlds — APPROVED** [review]
