### PR TITLE
fix: use Bytes instead of String for SCHEDULES_BY_EQUALITY_KEY

### LINKED ISSUE #11971: SCHEDULES_BY_EQUALITY_KEY should not be string key
### Description

The map in state for `SCHEDULES_BY_EQUALITY_KEY` should not by keyed by String. String just seems odd. Talking with Joseph it should be a hash, in which case it should be Bytes not String.

Also the migration code seems wrong as it is converting Long to String and storing that in there which will never work.
```
                schedulesByEquality.put(
                        ProtoString.newBuilder()
                                .value(String.valueOf(scheduleEqualityVirtualKey.getKeyAsLong()))
                                .build(),
                        ScheduleList.newBuilder().schedules(schedules).build());
```

### Steps to reproduce

Problem in code

### Additional context

_No response_

### Hedera network

other

### Version

0.0.48

### Operating system

None

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
Update the map in state for SCHEDULES_BY_EQUALITY_KEY to use Bytes instead of String for modularized code.

**Related issue(s)**:
Fixes #11971

### CODE REVIEW

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java [hunk 1]
```diff
@@ -59,13 +59,6 @@ private static void addToHash(final Hasher hasher, final Key keyToAdd) {
         hasher.putBytes(keyBytes);
     }
 
-    @SuppressWarnings("UnstableApiUsage")
```
Comment (povolev15) [inline hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java:62]: why do you delete it?

**Review by povolev15 — APPROVED** [review]
other than the comment LGTM

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleStoreUtility.java:62]: It wasn't being used anywhere. Since it uses AccountID, it doesn't really belong in schedule service anyway. My guess is that it was only there due to a copy-pasta mistake.

**Review by tinker-michaelj — APPROVED** [review]
LGTM, ty @kimbor !
