### PR TITLE
fix: 11328 Optimized `DataFileReaderPbj.leaseFileChannel` method 

### LINKED ISSUE #11328: DataFileReaderPbj has a performance bottleneck in case of multi-threaded reads
### Problem

I encountered this issue while working on improvements of the state validation tool (see https://github.com/hashgraph/hedera-services/issues/11202) It turned out that even with proper parallelization there is not much of a performance gain. 

I started investigation and figured out that multiple threads are waiting on a monitor in the same `FileChannelImpl` object despite multiple file channels were available for that reader and not properly used. 

### Solution

This issue caused by the implementation of `DataFileReaderPbj#leaseFileChannel` which may be working fine in case of relatively low (2-4) number of reading threads but it doesn't scale.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

Optimized `DataFileReaderPbj.leaseFileChannel` method  to make sure that it returns an index of the least used file channel at the moment

**Related issue(s)**:

Fixes #11328 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 1]
```diff
@@ -75,19 +78,21 @@
 // https://github.com/hashgraph/hedera-services/issues/8344
 public class DataFileReaderPbj<D> implements DataFileReader<D> {
 
+    private static final MerkleDbConfig CONFIG = ConfigurationHolder.getConfigData(MerkleDbConfig.class);
```
[the remark this answers is not in the document]
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:81]: It is reliable in a sense that this configuration holder is fully initialized by the moment we use it here. Yes, it's deprecated but I'm not sure if there is any alternative way of getting config object from the static context.

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 2]
```diff
@@ -100,6 +105,7 @@ public class DataFileReaderPbj<D> implements DataFileReader<D> {
     protected final AtomicInteger fileChannelsCount = new AtomicInteger(0);
     /** Number of file channels currently in use by all threads working with this data file reader */
     protected final AtomicInteger fileChannelsInUse = new AtomicInteger(0);
+    protected final AtomicIntegerArray fileChannelsLeases = new AtomicIntegerArray(MAX_FILE_CHANNELS);
```
[the remark this answers is not in the document]
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java]: Agreed. I renamed it

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 3]
```diff
@@ -336,17 +343,38 @@ protected int leaseFileChannel() throws IOException {
...
+            int lease = count - 1;
+            fileChannelsLeases.incrementAndGet(lease);
+            return lease;
+        }
+        // find a channel with the least number of leases
+        // it's an estimate, as the number of leases may change while we're iterating, but it's good enough
+        int minCount = Integer.MAX_VALUE;
+        int lease = 0;
+        for (int i = 0; i < count; i++) {
+            int currentLeaseCount = fileChannelsLeases.get(i);
```
[the remark this answers is not in the document]
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java]: Fixed

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 4]
```diff
@@ -336,17 +343,38 @@ protected int leaseFileChannel() throws IOException {
         // Although openNewFileChannel() is thread safe, it makes sense to check the count here.
         // Since the channels are never closed (other than when the data file reader is closed),
         // it's safe to check count against MAX_FILE_CHANNELS
-        if ((inUse / count > THREADS_PER_FILECHANNEL) && (count < MAX_FILE_CHANNELS)) {
+        if (((float) inUse / count > THREADS_PER_FILECHANNEL) && (count < MAX_FILE_CHANNELS)) {
             openNewFileChannel(count);
             count = fileChannelsCount.get();
+            int lease = count - 1;
```
[the remark this answers is not in the document]
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java]: Sure, renamed it to `newChannelLease` as you suggested and made it `final `

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (jsync-swirlds) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:81]: Could the two values you need be non-static without compromising performance?
Alternatively, perhaps we could check with the hashgraph-base team about why it is deprecated and the recommended alternative approach?

**Review by jsync-swirlds — DISMISSED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java [hunk 5]
```diff
@@ -107,7 +107,9 @@ public record MerkleDbConfig(
         @ConfigProperty(defaultValue = "-1") int numHalfDiskHashMapFlushThreads,
         @ConfigProperty(defaultValue = "262144") int reservedBufferLengthForLeafList,
         @ConfigProperty(defaultValue = "1048576") int leafRecordCacheSize,
-        @ConfigProperty(defaultValue = "true") boolean usePbj) {
+        @ConfigProperty(defaultValue = "true") boolean usePbj,
+        @Min(1) @ConfigProperty(defaultValue = "8") int maxFileChannelsPerFileReader,
+        @Min(1) @ConfigProperty(defaultValue = "8") int maxThreadsPerFileChannel) {
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java:112]: Minor: it looks like the hard-coded default values try to make assumptions about the hardware running this code. I'd suggest to consider deriving the default values from Runtime.availableProcessors() and similar so as to try and optimally use all the hardware available, and prevent overuse of the resources when the code is running on a low-end hardware, too. This may be done separately though.

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 6]
```diff
@@ -336,17 +343,38 @@ protected int leaseFileChannel() throws IOException {
...
+            fileChannelLeases.incrementAndGet(newChannelLease);
+            return newChannelLease;
+        }
+        // find a channel with the least number of leases
+        // it's an estimate, as the number of leases may change while we're iterating, but it's good enough
+        int minCount = Integer.MAX_VALUE;
+        int channelLease = 0;
+        for (int i = 0; i < count; i++) {
+            final int currentLeaseCount = fileChannelLeases.get(i);
+            if(currentLeaseCount == 0) {
```
Comment (anthony-swirldslabs) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:359]: Minor: space after `if` here and at line 363 below.

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java (hunk 5 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java:112]: In case of the state validator there was a clear goal - reduce or eliminate the bottleneck that prevents reading values as much as possible. In this particular case it's not clear how exactly any of these values should be derived from `Runtime.availableProcessors()`. It looks like it should be measured on a particular configuration and adjusted to it. There are too many performance variables to consider here to predict what values the parameters should have.

Comment (anthony-swirldslabs) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java:112]: Fair enough.

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by jsync-swirlds — DISMISSED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:81]: Okay, there is a way. There is an instance of a `Platform` class, which contains an instance of `PlatformContext` which, in its turn, contains `Configuration`. I can pass this instance in a `VirtualMap` constructor and then provide it to all the related objects. It's possible to do but it's going to be a major refactoring, and it involves not just this code but multiple other pieces that are using `ConfigurationHolder` in the platform-sdk codebase. I created this ticket https://github.com/hashgraph/hedera-services/issues/11336 for this work to be done separately.

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java [hunk 7]
```diff
@@ -107,7 +107,9 @@ public record MerkleDbConfig(
         @ConfigProperty(defaultValue = "-1") int numHalfDiskHashMapFlushThreads,
         @ConfigProperty(defaultValue = "262144") int reservedBufferLengthForLeafList,
         @ConfigProperty(defaultValue = "1048576") int leafRecordCacheSize,
-        @ConfigProperty(defaultValue = "true") boolean usePbj) {
+        @ConfigProperty(defaultValue = "true") boolean usePbj,
+        @Min(1) @ConfigProperty(defaultValue = "8") int maxFileChannelsPerFileReader,
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java:111]: JavaDoc, please

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 8]
```diff
@@ -101,6 +106,8 @@ public class DataFileReaderPbj<D> implements DataFileReader<D> {
     /** Number of file channels currently in use by all threads working with this data file reader */
     protected final AtomicInteger fileChannelsInUse = new AtomicInteger(0);
 
+    protected final AtomicIntegerArray fileChannelLeases = new AtomicIntegerArray(MAX_FILE_CHANNELS);
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:109]: JavaDoc, please

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 9]
```diff
@@ -336,17 +344,38 @@ protected int leaseFileChannel() throws IOException {
...
         // it's safe to check count against MAX_FILE_CHANNELS
-        if ((inUse / count > THREADS_PER_FILECHANNEL) && (count < MAX_FILE_CHANNELS)) {
+        if (((float) inUse / count > THREADS_PER_FILECHANNEL) && (count < MAX_FILE_CHANNELS)) {
             openNewFileChannel(count);
             count = fileChannelsCount.get();
+            final int newChannelLease = count - 1;
+            fileChannelLeases.incrementAndGet(newChannelLease);
+            return newChannelLease;
+        }
+        // find a channel with the least number of leases
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:354]: The remainder of this method (except the two last lines) can be wrapped into "else", so there is only one "return" statement and one "incrementAndGet()" call

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java (hunk 8 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:109]: Fixed

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java (hunk 9 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java]: Done

**Review by jsync-swirlds — APPROVED** [review]

**Review by anthony-swirldslabs — DISMISSED** [review]

**Review by anthony-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java (hunk 7 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java:115]: Done

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]
