### PR TITLE
fix: 11498 Fix MapTest.

### LINKED ISSUE #11496: Rewrite `VirtualPipelineTests#flushThrottle`
### Description

Current implementation of `VirtualPipelineTests#flushThrottle` is way too sensitive to the environment load and, therefore, unstable. 
It has to be re-written to eliminate dependency on `Thread.sleep`. 

### Steps to reproduce

Run `VirtualPipelineTests#flushThrottle`

### Additional context

_No response_

### Hedera network

other

### Version

v0.47

### Operating system

None

### LINKED ISSUE #11498: Fix `MapTest#insertRemoveAndModifyOneMillion`
A problem was found while investigating one of `MapTest` failures. It's a regression introduced by https://github.com/hashgraph/hedera-services/pull/11268. In that fix, virtual map flushes were changed to check for the old path values before updating key to path mappings. That was the core of the algorithm for improved node remover.

However, same code, `VirtualDataSource.saveRecords()`, is also used for regular flushes, not only to flush data during reconnects. Regular flushes are slightly different, they contain real changes to virtual maps, so at the data source level they must be applied unconditionally, regardless of the old path values.

One possible solution is to introduce a flag to `saveRecords()` that indicates whether this method is called from `VirtualPipeline` (regular flushes) or `AbstractHashListener` (reconnect flushes). Based on this flag, deleted leaves are processed unconditionally, or only if the old path value matches the path in a record to delete.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

**Related issue(s)**:

Fixes #11498 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jsync-swirlds — DISMISSED** [review]

**Review by jsync-swirlds — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java [hunk 1]
```diff
@@ -611,17 +645,8 @@ public VirtualLeafRecord<K, V> loadLeafRecord(final K key) throws IOException {
         VirtualLeafRecord<K, V> leafRecord = pathToKeyValue.get(path);
 
         // FUTURE WORK: once the reconnect key leak bug is fixed, this block should be removed
```
Comment (artemananiev) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java:647]: I assume the comment may be deleted, too

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java [hunk 2]
```diff
@@ -87,6 +87,33 @@ void saveRecords(
             final Stream<VirtualLeafRecord<K, V>> leafRecordsToDelete)
             throws IOException;
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java:89]: Does it make sense to change the existing `saveRecords()` method in `VirtualDataSource` to be a default method (calling the new method with "false" as the last arg)?

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java [hunk 3]
```diff
@@ -840,6 +841,7 @@ public Stream<VirtualLeafRecord<K, V>> deletedLeaves() {
                 final K key = element.key;
                 final Mutation<K, VirtualLeafRecord<K, V>> mutation = lookup(keyToDirtyLeafIndex.get(key));
                 if (mutation != null && mutation.isDeleted()) {
+                    element.value.setPath(Path.INVALID_PATH);
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java:844]: This is not needed with the new approach

File: platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java [hunk 4]
```diff
@@ -164,6 +164,22 @@ public void close() throws IOException {
...
+                Stream<VirtualHashRecord> pathHashRecordsToUpdate,
+                Stream<VirtualLeafRecord<TestKey, TestValue>> leafRecordsToAddOrUpdate,
+                Stream<VirtualLeafRecord<TestKey, TestValue>> leafRecordsToDelete,
+                boolean isReconnectContext)
+                throws IOException {
+            final var ir = pathHashRecordsToUpdate.toList();
+            this.internalRecords.add(ir);
+            final var lr = leafRecordsToAddOrUpdate.toList();
+            this.leafRecords.add(lr);
+            delegate.saveRecords(firstLeafPath, lastLeafPath, ir.stream(), lr.stream(), leafRecordsToDelete);
```
Comment (artemananiev) [inline platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java:180]: Should this test use the new method with "true" as the last arg?

Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java]: Yes. It should be. Fixed.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java (hunk 3 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java]: Removed.

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java (hunk 2 above)
Comment (imalygin) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java:89]: Yes, it's a good idea, thank you

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java]: Removed

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java [hunk 5]
```diff
@@ -247,13 +247,13 @@ public BreakableDataSource(final BrokenBuilder builder, final VirtualDataSource<
 
         @Override
         public void saveRecords(
-                final long firstLeafPath,
-                final long lastLeafPath,
-                final Stream<VirtualHashRecord> pathHashRecordsToUpdate,
-                final Stream<VirtualLeafRecord<TestKey, TestValue>> leafRecordsToAddOrUpdate,
-                final Stream<VirtualLeafRecord<TestKey, TestValue>> leafRecordsToDelete)
+                long firstLeafPath,
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java:250]: Is there a reason that you removed the `final`s on these parameters?

**Review by alittley — APPROVED** [review]
Approved WRT hashgraph owned file

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java [hunk 6]
```diff
@@ -1218,7 +1211,11 @@ private void writeLeavesToPathToKeyValue(
             // dirtyLeaves stream above
             if (isLongKeyMode) {
                 final long key = ((VirtualLongKey) leafRecord.getKey()).getKeyAsLong();
-                longKeyToPath.putIfEqual(key, path, INVALID_PATH);
+                if (isReconnect) {
+                    longKeyToPath.putIfEqual(key, path, INVALID_PATH);
+                } else {
+                    longKeyToPath.put(key, INVALID_PATH);
+                }
```
Comment (jsync-swirlds) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java:1218]: Just curious; it looks like this is the essential fix.
What behavior did we uncover that reconnect should only replace a known/matching path with Invalid; while in other cases we replace or add a path as Invalid, regardless of previous value?

**Review by jsync-swirlds — DISMISSED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java (hunk 6 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java:1218]: As `isReconnect` flag suggests, there are two possible contexts:
- Regular flush. There we know for sure that if a tree node got into `deletedLeaves` set, it is deleted for sure and, therefore, the index should be updated unconditionally
- Flush on reconnect. In this case things may get tricky if a path of the key in question changed. In this case we delete conditionally (only if there were no changes), because if the path changed, it's a valid new path and should not be deleted.

**Review by jsync-swirlds — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java (hunk 5 above)
Comment (imalygin) [reply platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java]: That's a refactoring artifact. Thank you for pointing it out.

**Review by jsync-swirlds — DISMISSED** [review]

**Review by jsync-swirlds — APPROVED** [review]

**Review by alittley — APPROVED** [review]

**Review by alittley — DISMISSED** [review]

**Review by alittley — DISMISSED** [review]

**Review by alittley — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]

**Review by jsync-swirlds — APPROVED** [review]
