### PR TITLE
chore: fix chaos bot

### LINKED ISSUE #22059: Chaos Bot: Configuration
Allow the user to configure the chaos bot and the existing experiments

### PR DESCRIPTION
**Pull request by netopyr**
**Description**:

Remove usage of Set as it has a non-deterministic iteration order and some minor fixes for bandwidth.

**Related issue(s)**:

Fixes #22059

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/network/BandwidthLimit.java [hunk 1]
```diff
@@ -83,7 +83,7 @@ public int toKilobytesPerSecond() {
      * @return the bandwidth in megabytes per second
      */
     public int toMegabytesPerSecond() {
-        return kilobytesPerSecond / 1024;
+        return (kilobytesPerSecond + 512) / 1024;
```
Comment (poulok) [inline platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/network/BandwidthLimit.java:86]: Why add 512 if we are just converting?

Comment (netopyr) [reply platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/network/BandwidthLimit.java:86]: To round it. Do you think we should always round off?

Comment (poulok) [reply platform-sdk/consensus-otter-tests/src/testFixtures/java/org/hiero/otter/fixtures/network/BandwidthLimit.java:86]: Ah ok. This was not obvious to me. I suggest `return Math.round(kilobytesPerSecond / 1024);`

This does not have to be changed now.
