### PR TITLE
fix: Add test with deleted sender account

### LINKED ISSUE #14578: (AIRDROP - 59) Given sender is a deleted account when it attempts to sign a tokenAirdropTransaction then the transaction should fail.

### PR DESCRIPTION
**Pull request by JivkoKelchev**
**Description**:

(AIRDROP - 59) Given sender is a deleted account when it attempts to sign a tokenAirdropTransaction then the transaction should fail.

**Related issue(s)**:

Fixes #14578

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java [hunk 1]
```diff
@@ -121,8 +121,10 @@ public void validateSemantics(
                         .filter(item -> item.amount() < 0)
                         .findFirst();
                 final var senderId = senderAccountAmount.orElseThrow().accountIDOrThrow();
-                final var senderAccount = accountStore.get(senderId);
-                validateTrue(senderAccount != null, INVALID_ACCOUNT_ID);
+
+                final var senderAccount =
```
Comment (david-bakin-sl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAirdropValidator.java:125]: This is no longer a `test:` but a `fix:` (PR title).  (Also:  Good thing the test was in the test plan!)
