### PR TITLE
Fix `TokenFeeScheduleUpdateSpecs` tests

### LINKED ISSUE #8788: Fix TokenFeeScheduleUpdateSpecs tests

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
Fix for `onlyValidCustomFeeScheduleCanBeUpdated` in `TokenFeeScheduleUpdateSpecs` tests.

**Related issue(s)**:
Fixes #8788 

**Notes for reviewer**:
This fix worked last week but started to fail after the recent updates. I spent some time debugging it, and it looks like the implementation of `calculateFees` in `TokenFeeScheduleUpdateHandler` is what caused this test to fail (because the fix worked with an older version of the `develop` branch.

I have created one additional issue to be addressed separately: #8864 

Also, please note that other HAPI Tests are failing because `onlyValidCustomFeeScheduleCanBeUpdated` in `TokenFeeScheduleUpdateSpecs` is overriding props `tokens.maxCustomFeesAllowed` and failing, thus not reverting it back.

**Checklist**
- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by netopyr** [comment]
Unit tests are failing

**Comment by mhess-swl** [comment]
Are there tests that need to be written or modified as a result of these code changes?

**Comment by thenswan** [comment]
@netopyr @mhess-swl updated unit test that previously was failing.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java [hunk 1]
```diff
@@ -245,4 +250,29 @@ private void validateRoyaltyFeeForCreation(
...
+        final var denominator = fractionalFee.fractionalAmount().denominator();
+        final var minimumUnitsToCollect = fractionalFee.minimumAmount();
+        final var nominalMax = fractionalFee.maximumAmount();
+        final var maximumUnitsToCollect = nominalMax == 0 ? Long.MAX_VALUE : nominalMax;
+
+        validateTrue(denominator != 0, FRACTION_DIVIDES_BY_ZERO);
+        validateTrue(numerator > 0 && denominator > 0, CUSTOM_FEE_MUST_BE_POSITIVE);
+        validateTrue(minimumUnitsToCollect >= 0 && maximumUnitsToCollect >= 0, CUSTOM_FEE_MUST_BE_POSITIVE);
+        validateTrue(maximumUnitsToCollect >= minimumUnitsToCollect, FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT);
+    }
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:277]: Is this code already tested somewhere? I don't see many changes in `CustomFeesValidatorTest`

Comment (thenswan) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:277]: @mhess-swl added unit tests.

Comment (mhess-swl) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:277]: They look great, thank you!!

**Review by mhess-swl — APPROVED** [review]

**Comment by thenswan** [comment]
`PbjConverter` fix was done because of [this line](https://github.com/LimeChain/hedera-services/blob/c82334a3048d10f994ed6b7b0bf5d39e4aaf69b2/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/submerkle/FcCustomFee.java#L215) and it should address #8864 as well. I am expecting checks to pass now.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java [hunk 2]
```diff
@@ -245,4 +250,29 @@ private void validateRoyaltyFeeForCreation(
...
+        final var numerator = fractionalFee.fractionalAmount().numerator();
+        final var denominator = fractionalFee.fractionalAmount().denominator();
+        final var minimumUnitsToCollect = fractionalFee.minimumAmount();
+        final var nominalMax = fractionalFee.maximumAmount();
+        final var maximumUnitsToCollect = nominalMax == 0 ? Long.MAX_VALUE : nominalMax;
+
+        validateTrue(denominator != 0, FRACTION_DIVIDES_BY_ZERO);
+        validateTrue(numerator > 0 && denominator > 0, CUSTOM_FEE_MUST_BE_POSITIVE);
+        validateTrue(minimumUnitsToCollect >= 0 && maximumUnitsToCollect >= 0, CUSTOM_FEE_MUST_BE_POSITIVE);
+        validateTrue(maximumUnitsToCollect >= minimumUnitsToCollect, FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:276]: I think there are some functions added for common logic in this PR https://github.com/hashgraph/hedera-services/pull/8672. We should probably re-use the same functions to avoid duplicating code. Can be done after the PR is merged also.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:276]: Also some logic is missing for Royalty Fee as specified in the above PR. Should fix those as well.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! But need to re-use logics from other PR specified in comment. Can be done after merging this PR

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java (hunk 2 above)
Comment (thenswan) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:276]: Yeah, I agree with you @Neeharika-Sompalli 
I think since #8672 was merged, I can update this branch by re-using logic from it

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:276]: Sounds good. Thanks @thenswan

Comment (thenswan) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java]: @Neeharika-Sompalli updated PR

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java [hunk 3]
```diff
@@ -282,4 +271,32 @@ private void validateRoyaltyFeeForCreation(
...
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java:300]: Most of this code is duplicated from `validateFractionalFeeForCreation`. Can we move this to a different function and re-use in `validateFractionalFeeForCreation`

**Review by Neeharika-Sompalli — COMMENTED** [review]
LGTM Overall. Have a small comment on not duplicating code from a function in `CustomFeeValidator`

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM ! Thanks @thenswan

**Review by rbair23 — APPROVED** [review]
