### PR TITLE
fix: only migrate non-empty aliases

### LINKED ISSUE #11841: (2/19 - 18:45:00) Mismatched field counts  (found but did not expect [contractCreateResult]) from round 162955286
### Description

Transaction in HashScan [here](https://hashscan.io/mainnet/transaction/1708368321.070583172).

A Ethereum transaction with the below body

```
transactionID {
  transactionValidStart {
    seconds: 1708368310
    nanos: 875846384
  }
  accountID {
    accountNum: 995584
  }
}
nodeAccountID {
  accountNum: 4
}
transactionFee: 1260000000
transactionValidDuration {
  seconds: 120
}
ethereumTransaction {
  ethereum_data: "\002\370Z\202\001\'\a\204w5\224\000\205\364\360\026\030\000\203\024SZ\200\200\200\300\001\240m\357^U\005{\362>Y\222\271d\'\314\023\n\325\342>2.v\262aQ\264\n\246\271\227\322&\240R\232\275\341\3528\262\244\215\201E\215:\205\224\253>\336[\nA\2017S-\367}\273\320@\331\373"
  call_data {
    fileNum: 4721328
  }
}
```
Got 
```
Mismatched field counts  (found but did not expect [contractCreateResult]) between expected receipt {
  status: WRONG_NONCE
```
### Steps to reproduce

Run 15 mins events from round 162955286

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### LINKED ISSUE #11880: (2/19 - 19:30:00) Entries at position 306868 had different transactions (signedTransactionBytes:
### Description

Transaction in HashScan [here](https://hashscan.io/mainnet/transactionsById/0.0.995584-1708371221-163209171).

Transaction body:
```
transactionID {
  transactionValidStart {
    seconds: 1708371221
    nanos: 163209171
  }
  accountID {
    accountNum: 995584
  }
  nonce: 1
}
tokenAssociate {
  account {
    accountNum: 4721631
  }
  tokens {
    tokenNum: 3706639
  }
}
```

Got
---- TokenAssociateToAccount ≠ ContractCreate DIFFERED (TRANSACTION_MISMATCH) ----
Entries at position 306868 had different transactions (signedTransactionBytes: "\n(\n\025\n\v\b\225\332\316\256\006\020\323\277\351M\022\004\030\200\342< \001\302\002\016\n\005\030\337\227\240\002\022\005\030\217\236\342\001"
 vs signedTransactionBytes: "\n:\n\025\n\v\b\225\332\316\256\006\020\323\277\351M\022\004\030\200\342< \001B!B\005\b\200\316\332\003j\024lazy-created accountz\002\030\000"
)

These streams differed 455 times

### Steps to reproduce

Run 15 mins events from round 162958416

### Additional context

_No response_

### Hedera network

other

### Version

11852-pay-rewards-in-triggered-txn

### Operating system

None

### LINKED ISSUE #12140: (2/19 - 18:15:00)No modular record found at 2024-02-19T20:12:48.808288002Z for transactionID
### Description

Transaction in HashScan [here](https://hashscan.io/mainnet/transactionsById/0.0.4714230-1708373549-187194081).

```
transBody : 
transactionID {
  transactionValidStart {
    seconds: 1708373549
    nanos: 187194081
  }
  accountID {
    accountNum: 4714230
  }
  nonce: 1
}
cryptoCreateAccount {
  key {
    keyList {
    }
  }
  autoRenewPeriod {
    seconds: 7776000
  }
  memo: "lazy-created account"
  alias: "\267>[\201\273\242\321\346\356)\006\366?\275\221{\210\035>\377"
}
```
Got:
---- CryptoCreate DIFFERED (SECOND_IS_MISSING) ----
No modular record found at 2024-02-19T20:12:48.808288002Z for transactionID : transactionValidStart {
  seconds: 1708373549
  nanos: 187194081
}
accountID {
  accountNum: 4714230
}
nonce: 1

### Steps to reproduce

Run 15 mins from round 162960502.

### Additional context

_No response_

### Hedera network

other

### Version

release/0.48

### Operating system

None

### LINKED ISSUE #12147: (2/19 - 17:00:00) Entries at position 283101 had different transactions (signedTransactionBytes:
### Description

Transaction in HashScan [here](https://hashscan.io/mainnet/transactionsById/0.0.995584-1708369401-385266903).

```
For body,
transactionID {
  transactionValidStart {
    seconds: 1708369401
    nanos: 385266903
  }
  accountID {
    accountNum: 995584
  }
  nonce: 1
}
tokenAssociate {
  account {
    accountNum: 4721473
  }
  tokens {
    tokenNum: 3706639
  }
}
```
Got:
---- TokenAssociateToAccount ≠ ContractCreate DIFFERED (TRANSACTION_MISMATCH) ----
Entries at position 283101 had different transactions (signedTransactionBytes: "\n)\n\026\n\f\b\371\313\316\256\006\020\327\351\332\267\001\022\004\030\200\342< \001\302\002\016\n\005\030\301\226\240\002\022\005\030\217\236\342\001"
 vs signedTransactionBytes: "\n;\n\026\n\f\b\371\313\316\256\006\020\327\351\332\267\001\022\004\030\200\342< \001B!B\005\b\200\316\332\003j\024lazy-created accountz\002\030\000"
)

### Steps to reproduce

Run 15 mins events from round 162956328.

### Additional context

_No response_

### Hedera network

other

### Version

release/0.48

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #11880
 - Closes #11841
 - Closes #12147 
 - Closes #12140 
 - During alias migration, fix bug that set a `(<Bytes.EMPTY>, 0.0.X)` mapping when migrating [an account with an invalid ECDSA key](https://hashscan.io/mainnet/account/0.0.1385722?ph=1&pt=1).
 - Don't set an explicit `0.0.0` auto-renew account id in a synthetic `ContractCreation` for `EthereumTransaction` with no `to` address.

ℹ️  Also, make temporary changes for _diff testing only_.

In mono-service:
 - Insert the synthetic `ContractCreate` record for an `EthereumTransaction` with no `to` address at the _beginning_ of following child records.
 - Reclaim any entity ids left allocated in a reverted `ContractCall`.
 - Set `PAYER_ACCOUNT_NOT_FOUND` instead of `ACCOUNT_ID_DOES_NOT_EXIST` for a missing payer account (this becomes possible when replaying events with the above patch that reclaims unused entity ids).
 

In mod-service:
 - Don't externalize a `contractCallResult` on `WRONG_NONCE`.
 - Pre-validate all account ids to match mono-service failure codes.

### CODE REVIEW

**Review by mhess-swl — APPROVED** [review]
LGTM!

**Review by iwsimon — DISMISSED** [review]
LGTM. Thanks @tinker-michaelj. Failed unit tests.

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by povolev15 — DISMISSED** [review]
LGTM. Thanks @tinker-michaelj

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by povolev15 — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsHistorian.java [hunk 1]
```diff
@@ -136,6 +136,21 @@ void trackFollowingChildRecord(
             ExpirableTxnRecord.Builder recordSoFar,
             List<TransactionSidecarRecord.Builder> sidecars);
 
+    /**
+     * Adds the given in-progress child record to the active transaction, where its synthetic
+     * consensus timestamp will come <i>after</i> that of the parent user transaction.
```
Comment (david-bakin-sl) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsHistorian.java:141]: Does this mean _immediately_ after, i.e., first?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java [hunk 2]
```diff
@@ -119,7 +119,14 @@ public static ContractCreateTransactionBody synthContractCreationFromParent(
...
 
-    private static boolean hasNonDegenerateAutoRenewAccountId(@NonNull final Account account) {
+    /**
+     * Returns whether the given account has an auto-renew account id that is not
+     * {@code 0.0.0}.
+     *
+     * @param account the account
+     * @return whether the given account has an auto-renew account id that is not
+     */
+    public static boolean hasNonDegenerateAutoRenewAccountId(@NonNull final Account account) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java:129]: In a different world this could go somewhere else where it might be more generally useful, e.g., in Account?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java [hunk 3]
```diff
@@ -81,6 +81,14 @@ public void doIn(@NonNull final TransferContext transferContext) {
                 try {
                     newAssociation = validateAndBuildAutoAssociation(
                             accountId, tokenId, token, accountStore, tokenRelStore, handleContext);
+                    // (FUTURE) Also remove this redundant validation after diff testing
```
Comment (david-bakin-sl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:84]: Is this temp diff testing change mentioned in the PR description?  Not sure why this "redundant validation" is needed here.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java [hunk 4]
```diff
@@ -225,7 +225,9 @@ public void handle(@NonNull final HandleContext context) throws HandleException
         final var transferContext =
                 new TransferContextImpl(context, enforceMonoServiceRestrictionsOnAutoCreationCustomFeePayments);
 
+        // (TEMPORARY) Remove this after diff testing
```
Comment (david-bakin-sl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:228]: Does this comment apply to both L229 and L230 now?  (Also should probably use FUTURE keyword to identify this later.)

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java [hunk 5]
```diff
@@ -343,9 +343,12 @@ public void migrate(@NonNull final MigrationContext ctx) {
                                         aliasesState
                                                 .get()
                                                 .put(new ProtoBytes(toAcct.alias()), toAcct.accountIdOrThrow());
-                                        if (toAcct.alias().toByteArray().length > 20) {
+                                        if (toAcct.alias().length() > 20) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java:346]: Someday let's get rid of all of these `== 20` and `> 20` magic number relational expressions and replace them with something that self-describes as checking whether it is an evm address or not.

**Review by david-bakin-sl — APPROVED** [review]
LGTM with just some nits to fix comments so that they'll make sense later when ripping stuff out.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsHistorian.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsHistorian.java:141]: None of the mono-service changes in this PR would be worth putting into production in any case; they are immaterial changes needed for diff testing on `release/0.48`.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java (hunk 3 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/AssociateTokenRecipientsStep.java:84]: For diff-testing only.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java (hunk 5 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/InitialModServiceTokenSchema.java:346]: True, we have a serviceable comment somewhere...

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/utils/SynthTxnUtils.java:129]: Hmm true.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java:228]: Both lines can be removed after diff testing.
