### PR TITLE
fix: BLOBBASEFEE opcode (Cancun) to return 1 Wei not 0 Wei

### LINKED ISSUE #16091: fix: BLOBBASEFEE opcode not behaving as specified in HIP-866
Returns 0, not 1.  [HIP-866](https://hips.hedera.com/hip/hip-866) for reference.

### PR DESCRIPTION
**Pull request by david-bakin-sl**
**Description**:

Hedera Cancun customizations force `BLOBBASEFEE` opcode to return 1Wei (the minimum useful), not the
actual blobbasefee - as we don't support blob transactions.

Missing line to set base blob fee in initial message frame, which is where the `BLOBBASEFEE` opcode looks
for the current blob fee.  (It propagates to child frames correctly.)

**Related issue(s)**:

Fixes #16091

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameBuilderTest.java [hunk 1]
```diff
@@ -382,6 +387,7 @@ void constructsExpectedFrameForCreate() {
         assertEquals(transaction.gasAvailable(INTRINSIC_GAS), frame.getRemainingGas());
         assertSame(EIP_1014_ADDRESS, frame.getOriginatorAddress());
         assertEquals(Wei.of(NETWORK_GAS_PRICE), frame.getGasPrice());
+        assertEquals(Wei.ONE, frame.getBlobGasPrice());
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameBuilderTest.java:390]: At first glance, it looks like all of these assertions are the same.  If they are can they be consolidated?

**Review by lukelee-sl — APPROVED** [review]
LGTM

File: hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameBuilderTest.java (hunk 1 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameBuilderTest.java:390]: I thought of refactoring that ... but (I admit it) just wanted to get it in.  Let me look agian.
