### PR TITLE
HIP-24 testing plan and fixes

### LINKED ISSUE #2303: Write + execute testing plan for HIP-24
### Problem

Need an extensive test plan for HIP-24 changes.

### Solution

- [ ] Create a test plan for HIP-24 in markdown format (i.e., something that could be easily copied and used in other PRs).

- [ ] Execute this test plan.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by anighanta**
**Description**:

**Related issue(s)**:

Fixes #2303 

Provides a (retrospective) testing plan for HIP-24.
Implements the testing plan.

Below are the deliverables:

### :ice_cube:&nbsp;State validation
   - [x] _(EET framework)_ `GetTokenInfo` assert for pause status of the Token.
   - [x] _(EET framework)_ `GetTokenInfo` assert for pause key of the Token.

### :cactus:&nbsp;Migration
   - [x] _(Unit)_ A `MerkleToken` now serializes its pause Key and pause status.
   - [x] _(Unit)_ A `MerkleToken` can be deserialized from a prior-version state.
   - [x] _(Unit)_ A `MerkleToken` can be deserialized from a current-version state.

### :white_check_mark:&nbsp;Positive functional
   - [x] _(EET)_ A `TokenCreate` with a `pauseKey` and `TokenPause` transaction signed by the this `pausekey` will set the token pause status as `Paused`. `tokenGetInfo` asserts this pause status.
   - [x] _(EET)_ To the `paused` token above we perform a `TokenUnpause` transaction signed by the same `pauseKey` which will set the token pause status as `Unpasued`. `tokenGetInfo` asserts this pause status.
   - [x] _(EET)_ A newly created Token is asserted for a `Unpaused` token status.

### :x:&nbsp;Negative functional
   - [x] _(EET)_ Setup with a A `TokenCreate` with a `pauseKey` and `TokenPause` transaction signed by the this `pausekey` will set the token pause status as `Paused`. `tokenGetInfo` asserts this pause status.
   - [x] _(EET)_ A `TokenCreate` fails with this paused token as denominating token for custom fee.
   - [x] _(EET)_ A `TokenUpdate` fails on this paused token.
   - [x] _(EET)_ A `TokenAssociate` fails on this paused token.
   - [x] _(EET)_ A `TokenDissociate` fails on this paused token.
   - [x] _(EET)_ A `TokenDelete` fails on this paused token.
   - [x] _(EET)_ A `TokenMint` fails on this paused token.
   - [x] _(EET)_ A `TokenWipe` fails on this paused token.
   - [x] _(EET)_ A `TokenBurn` fails on this paused token.
   - [x] _(EET)_ A `TokenFeeze` fails on this paused token.
   - [x] _(EET)_ A `TokenUnfreeze` fails on this paused token.
   - [x] _(EET)_ A `TokenGrantKyc` fails on this paused token.
   - [x] _(EET)_ A `TokenRevokeKyc` fails on this paused token.
   - [x] _(EET)_ A `TokenFeeScheduleUpdate` fails on this paused token.
   - [x] _(EET)_ A `CryptoTransfer` involving this paused token will fail.
   - [x] _(EET)_ A multi-party `CryptoTransfer` rolls back all side-effects if it fails due to a paused Token.

### :receipt:&nbsp;Custom fee interplays
   - [x] _(EET)_ A `paused` token as denominating token of a custom fee will result in a failure to any transaction that triggers this custom fee.

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenPauseSpecs.java [hunk 1]
```diff
@@ -77,14 +81,70 @@ protected Logger getResultsLogger() {
 	@Override
 	protected List<HapiApiSpec> getSpecsInSuite() {
 		return List.of(new HapiApiSpec[] {
-				cannotChangePauseStatusIfMissingPauseKey(),
-				pausedFungibleTokenCannotBeUsed(),
-				pausedNonFungibleUniqueCannotBeUsed(),
-				unpauseWorks(),
-				basePauseAndUnpauseHaveExpectedPrices()
+//				cannotChangePauseStatusIfMissingPauseKey(),
```
Comment (shemnon) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenPauseSpecs.java:84]: Are these test cases currently not working or did dev code sneak in?

File: docs/test-plans/hip-24.md [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+
+Tests needed to cover the above scope.
+
+Careful unit testing should suffice for **migration** tests, as
+the change to state is very small---two fields added to the 
+`MerkleToken` leaf. 
+
+:white_check_mark:&nbsp;**Positive functional** testing will require EET specs 
+ that perform all variants of `TokenCreate`s with a `pauseKey` and test if the token's pause status is toggled 
+ appropriately using the new `tokenPause` and `tokenUpause` transactions.
```
Comment (Neeharika-Sompalli) [inline docs/test-plans/hip-24.md:42]: nit : `TokenPause` , `TokenUnpause` to be consistent and typo in `tokenUpause`

File: docs/test-plans/hip-24.md [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+   - [x] _(Unit)_ A `MerkleToken` can be deserialized from a prior-version state.
+   - [x] _(Unit)_ A `MerkleToken` can be deserialized from a current-version state.
+
+### :white_check_mark:&nbsp;Positive functional
+   - [x] _(EET)_ A `TokenCreate` with a `pauseKey` and `TokenPause` transaction signed by the this `pausekey` will set the token pause status as `Paused`. `tokenGetInfo` asserts this pause status.
+   - [x] _(EET)_ To the `paused` token above we perform a `TokenUnpause` transaction signed by the same `pauseKey` which will set the token pause status as `Unpasued`. `tokenGetInfo` asserts this pause status.
+   - [x] _(EET)_ A newly created Token is asserted for a `Unpaused` token status.
+
+### :x:&nbsp;Negative functional
+   - [x] _(EET)_ Setup with a A `TokenCreate` with a `pauseKey` and `TokenPause` transaction signed by the this `pausekey` will set the token pause status as `Paused`. `tokenGetInfo` asserts this pause status.
```
Comment (Neeharika-Sompalli) [inline docs/test-plans/hip-24.md:84]: typo A
