### PR TITLE
Fix remaining eth isomers delete contract resources

### LINKED ISSUE #3318: Analyse and adjust existing E2E to run with eth tx

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:

- Fix or refuse conversion of remaining E2E eth isomers
- Remove ContractResources class from test-clients
- Remove obsolete solidity resource files

**Related issue(s)**:

Fixes #3318 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java [hunk 1]
```diff
@@ -211,14 +211,15 @@ private HapiApiSpec whitelistingAliasedContract() {
 								DEFAULT_PAYER, WHITELISTER, literalInitcodeFor("Whitelister"))),
 						sourcing(() -> createLargeFile(
 								DEFAULT_PAYER, CREATOR, literalInitcodeFor("Creator"))),
+//						uploadInitCode(WHITELISTER, CREATOR),
```
Comment (stoqnkpL) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java:214]: we should delete these lines if we don't need them anymore instead of commenting them out

File: test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/GracePeriodRestrictionsSuite.java [hunk 2]
```diff
@@ -81,37 +86,35 @@ public static void main(String... args) {
 	@Override
 	public List<HapiApiSpec> getSpecsInSuite() {
 		return List.of(new HapiApiSpec[] {
-						gracePeriodRestrictionsSuiteSetup(),
+//						gracePeriodRestrictionsSuiteSetup(),
```
Comment (tinker-michaelj) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/GracePeriodRestrictionsSuite.java:89]: Here I think we want to restore what's in `master`.

**Review by tinker-michaelj — COMMENTED** [review]
Everything LGTM other than the note on commented specs in `GracePeriodRestrictions`. 👍

**Review by tinker-michaelj — APPROVED** [review]
LGTM!
