### PR TITLE
fix: 24802 Disable EVM hook count validation for TestNet 

### LINKED ISSUE #24802: Need to disable EVM hook count validation for PreviewNet and TestNet till reset
Due to https://github.com/hiero-ledger/hiero-consensus-node/issues/24729, the state is inconsistent. The fix prevents the issue from happening but doesn't correct the existing state. 

We need to disable EVM hook count validation till the moment when we have PreviewNet and TestNet reset.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This is a cherry-pick of https://github.com/hiero-ledger/hiero-consensus-node/pull/24817 into `release/0.73` branch

(cherry picked from commit 9a5f9762e7ac15cc0ec2ef65b023b59545cc3a67)

**Related issue(s)**:

Fixes #24802 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by artemananiev — APPROVED** [review]

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/EntityIdCountValidator.java [hunk 1]
```diff
@@ -104,22 +105,40 @@ public void processLeafBytes(long dataLocation, @NonNull final VirtualLeafBytes<
...
+                    && entityCounts.numStakingInfos() == stakingInfoCount.get()
+                    && entityCounts.numTopics() == topicCount.get()
+                    && entityCounts.numFiles() == fileCount.get()
+                    && entityCounts.numNodes() == nodesCount.get()
+                    //      To be investigated - https://github.com/hiero-ledger/hiero-consensus-node/issues/20993
+                    //      && entityCounts.numSchedules() == scheduleCount.get()
+                    //      && entityCounts.numContractStorageSlots() == contractStorageCount.get()
+                    && entityCounts.numContractBytecodes() == contractBytecodeCount.get()
+                    && entityCounts.numHooks() == hookCount.get()
+                    && entityCounts.numEvmHookStorageSlots() == evmHookStorageCount.get();
```
Comment (artemananiev) [inline hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/EntityIdCountValidator.java:125]: It should be quite opposite, this check should only be enabled for mainnet, correct?

Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/EntityIdCountValidator.java:125]: yes, you're right. fixed
