### PR TITLE
Expand signatures from latest signed state

### LINKED ISSUE #2019: Expand required signing keys from last signed state instead of working state
⚠️ Many of the implementation details suggested below were refined in #2686, but no major design decisions varied.

### Problem

It is almost always redundant to [expand the required signing keys ](https://github.com/hashgraph/hedera-services/blob/a24d4e91ff3985ceaef05b2d7e7d05ea1f3ebaab/hedera-node/src/main/java/com/hedera/services/sigs/Rationalization.java#L108) in `Rationalization.execute()`. That is, unless the key of an entity linked to the transaction was invalidated since `expandSignatures()`, no new information is gained.

### Solution

1️⃣ &nbsp;Define a `KeyHistory` type,
```
interface KeyHistory {
    /* Has the entity with the given number been invalidated since the given consensus time? */
    boolean hasKeyBeenInvalidatedSince(long entityNum, Instant then);

    /* Mark the entity with the given number as invalidated at the given consensus time. */
    void invalidateKeyAt(long entityNum, Instant now);

    /* Forget any invalidations no longer applicable to "recent" transactions. */
    void purgeExpiredInvalidations(Instant now);
}
```
Note that to keep the implementation simple, there is no harm in returning some false positives from `hasKeyBeenInvalidatedSince()`; false negative must of course be impossible. 

But the implementation can be little more than a wrapper around two data structures and a static property `keys.invalidationWindow=10`:

1. A `Map<PermHashInteger, Long> lastInvalidationInWindow`; and,
2. A `MonotonicFullQueueExpiries<Long> invalidationExpiries`; where,

each call to `invalidateKeyAt()` upserts an entry in the map; and each call to `purgeExpiredInvalidations()` removes map entries whose values are not at least `now.getEpochSecond() - ${keys.invalidationWindow}`. So,
- [x] Add the static `keys.invalidationWindow=10` property.
- [x] Implement the `KeyHistory` as above.
- [x] Call `keyHistory.purgeExpiredInvalidations()` at the beginning of `handleTransaction()`.

--- 

2️⃣ &nbsp;In each `*Create`, `*Delete`, and `*Update` transition logic, call `keyHistory.invalidateEntityAt()` as appropriate.
 - [x] Make these calls in the `Crypto*` variants.
 - [x] Make these calls in the `Contract*` variants.
 - [x] Make these calls in the `File*` variants.
 - [x] Make these calls in the `Schedule*` variants.
 - [x] Make these calls in the `Topic*` variants.
 - [x] Make these calls in the `Token*` variants.

----

3️⃣ &nbsp;Augment signing order results with the entity numbers of linked keys.
 - [x] Update the `SigningOrderResult` type. 
 - [x] Provide this information via `HederaSigningOrder`.

---

4️⃣ &nbsp;Maintain the latest `SignedState` in the context as a convenient source of keys.
- [x] Maintain a `AtomicReference<Pair<StateChildren, Instant>> signedStateMeta` to the context.
- [x] Create a `signedStateKeySource` that implements a `SigMetadataLookup` backed by this metadata.
- [x] Update `HederaSigningOrder` to take a `SigMetadataLookup` as an argument to `keysForPayer()` and `keysForOtherParties()`.
- [x] Use the (same) `signedStateKeySource` when calling`HederaSigningOrder` methods in `ServicesState.expandSignatures()`.

---

5️⃣ &nbsp;Don't repeat key-expansion work in `handleTransaction()` unless necessary.
- [x] Add `TxnAccessor` fields `long payerKeyNum`, `long[] otherPartyKeyNums`, and `Instant expansionTime` (where `expansionTime` of course derives from `signedStateMeta.getValue()`).
- [x] Set these fields in `expandSignatures()`.
- [x] In `Rationalization`, if the relevant linked entity numbers have not had their keys invalidated since `expansionTime`, do not re-expand the connected keys.

### LINKED ISSUE #2633: Generated `DaggerServicesApp.initialState` holds on to resources that are never released
### Description

It's mostly a heap use issue. The hidden class member may link in a lot of state that is not needed after initialization is complete and adds to heap waste. For example, the state may reference multiple implementation database instances which even if closed may still keep a lot of stuff (things are much worse when those instances are not closed but that is another issue on every occasion). 

### Steps to reproduce

Take a heap dump, find `DaggerServicesApp.initialState` [, compute its retained size].

### Additional context

_No response_

### Hedera network

other

### Version

dev

### Operating system

Linux

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Closes #2019
- Closes #2633 

**Description**:
- Switches to expanding signatures from the [latest signed state](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/ServicesState.java#L191) (or the working state if no signed state is available).
- Introduces [the `SigImpactHistorian`](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/ledger/SigImpactHistorian.java#L39) to track which entities have aliases that have changed since a given consensus time (e.g., since the time a state was signed).
    * The historian only tracks changes within a window of up to the last [`ledger.changeHistorian.memorySecs=20`](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/resources/bootstrap.properties#L68) seconds of consensus time (which is invalidated on reconnect).
    * The historian answers any question about changes outside its window with `ChangeStatus.UNKNOWN`, forcing related signatures to be re-expanded in `handleTransaction()`---in particular, since the working state is ["signed at" `Instant.ZERO`](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/context/MutableStateChildren.java#L64), the historian never treats working state references as `ChangeStatus.UNCHANGED`.
- For each transaction type that can impact the result of calling `SigRequirements.keysForPayer()` or `SigRequirements.keysForOtherParties()`, adds an appropriate call to `SigImpactHistorian.markChanged()`---e.g. [here](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/txns/schedule/ScheduleCreateTransitionLogic.java#L147) for schedule creation, [here](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/txns/consensus/TopicUpdateTransitionLogic.java#L118) for a topic update, etc.
- **IF** the historian can certify that [none the entities and aliases linked to a `TxnAccessor` have changed](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/sigs/Rationalization.java#L82) since the last signed state, immediately terminates `Rationalization.performFor()` with the status and sig metadata created during `expandSignatures()`; **ELSE** proceeds as before to re-expand signatures (and verify them synchronously if necessary).
- Cleans up the Dagger2 dependency graph to avoid binding the `ServicesState initialState` instance (c.f. #2633).
    * Instead, binds the node's address book `memo` and the initial `Hash`.

**Notes to reviewer:**
- ⚠️ Moves the `SCHEDULED_TRANSACTION_NOT_IN_WHITELIST` check [into the `HederaScheduleStore`](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/store/schedule/HederaScheduleStore.java#L124) because it is no longer safe to use `GlobalDynamicProperties` in `SigRequirements` (the `dynamicProperties` singleton is not scoped to a signed state, and its impacts must _always_ be re-tested in `handleTransaction`).

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java [hunk 1]
```diff
@@ -60,21 +59,24 @@ public static AnswerFlow provideAnswerFlow(
...
+				transactionPrecheck,
+				hapiOpPermissions,
+				queryFeeCheck);
+
+		final var zeroStakeFlow = new ZeroStakeAnswerFlow(
+				queryHeaderValidity,
+				stateViews,
+				hapiThrottling);
+
+		return new StakeAwareAnswerFlow(nodeInfo, stakedFlow, zeroStakeFlow);
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java:79]: Can we check `nodeInfo.isSelfZeroStake()` here and return needed object, since wont need both objects at same time ?

File: hedera-node/src/main/java/com/hedera/services/queries/answering/StakeAwareAnswerFlow.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
+package com.hedera.services.queries.answering;
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/queries/answering/StakeAwareAnswerFlow.java:2]: This class can be deleted if we check as above. If not need a copyright header here

File: hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java [hunk 3]
```diff
@@ -59,85 +61,103 @@ public StateAccessor(final ServicesState initialState) {
...
 	 * from the previous state and some references from the updated state.
 	 *
-	 * @param state the new working state to update children from
+	 * @param state
+	 * 		the new working state to update children from
 	 */
 	public void updateChildrenFrom(final ServicesState state) {
-		mapStateOnto(state, children);
+		if (children instanceof ImmutableStateChildren) {
+			throw new IllegalStateException("Can only replace immutable children");
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java:69]: typo `mutable` children

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java [hunk 4]
```diff
@@ -358,6 +362,7 @@ private void internalInit(
 			networkCtx().setStateVersion(CURRENT_VERSION);
 
 			metadata = new StateMetadata(app);
+			app.workingState().updateChildrenFrom(this);
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/ServicesState.java:365]: This is needed for `genesisInit` as well?

Comment (anighanta) [reply hedera-node/src/main/java/com/hedera/services/ServicesState.java:365]: `genesisInit` delegates to `internalInit` as well right

File: hedera-node/src/main/java/com/hedera/services/context/StateChildren.java [hunk 5]
```diff
@@ -1,25 +1,5 @@
 package com.hedera.services.context;
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/context/StateChildren.java:2]: missing copyrights

File: hedera-node/src/main/java/com/hedera/services/grpc/GrpcStarter.java [hunk 6]
```diff
@@ -92,8 +95,8 @@ void logInfoWithConsoleEcho(String s) {
 	}
 
 	private boolean thisNodeIsDefaultListener() {
-		final var thisAccount = nodeAddress.getMemo();
 		final var blessedNodeAccount = nodeLocalProperties.devListeningAccount();
-		return blessedNodeAccount.equals(thisAccount);
+		final var staticBook = addressBook.get();
+		return blessedNodeAccount.equals(staticBook.getAddress(nodeId.getId()).getMemo());
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/grpc/GrpcStarter.java:100]: @tinker-michaelj aren't we going to deprecate usage of memo field from the NodeAddress proto? Would this need a refactor when we do that ??

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/main/java/com/hedera/services/ServicesState.java:365]: yeah , I was wondering if we need to do that for `genesisInit` since it is going to be default children with no entities. But nvm understood.

File: hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java [hunk 7]
```diff
@@ -41,7 +43,7 @@
 import java.time.Instant;
 
 public class StateAccessor {
-	private StateChildren children = new StateChildren();
+	private volatile StateChildren children = new MutableStateChildren();
 
 	public StateAccessor() {
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java:48]: could remove `public StateAccessor(final ServicesState initialState)` constructor as it only used in unit test

File: test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java [hunk 8]
```diff
@@ -86,32 +86,32 @@ public static void main(String... args) {
...
+//				detectsKeysChangedBetweenExpandSigsAndHandleTxn(),
+//				doesntTriggerUntilPayerSigns(),
+//				requiresExtantPayer(),
+//				rejectsFunctionlessTxn(),
+//				whitelistWorks(),
+//				preservesRevocationServiceSemanticsForFileDelete(),
+//				worksAsExpectedWithDefaultScheduleId(),
+//				infoIncludesTxnIdFromCreationReceipt(),
+//				suiteCleanup(),
+//				validateSignersInInfo()
```
Comment (anighanta) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java:114]: uncomment these specs.

**Review by anighanta — DISMISSED** [review]
LGTM

File: hedera-node/src/main/java/com/hedera/services/txns/file/FileAppendTransitionLogic.java [hunk 9]
```diff
@@ -95,8 +95,9 @@ public void doStateTransition() {
 				return;
 			}
 
-			var result = hfs.append(target, data);
-			txnCtx.setStatus(result.outcome());
+			final var result = hfs.append(target, data);
+			final var status = result.outcome();
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/main/java/com/hedera/services/txns/file/FileAppendTransitionLogic.java:99]: We dont need to mark entity changed here ? `sigImpactHistorian.markEntityChanged`

File: hedera-node/src/test/java/com/hedera/services/queries/answering/StakeAwareAnswerFlowTest.java [hunk 10]
```diff
@@ -0,0 +1,51 @@
+package com.hedera.services.queries.answering;
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/src/test/java/com/hedera/services/queries/answering/StakeAwareAnswerFlowTest.java:2]: copyright missing

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM , other than few questions as posted above.

File: hedera-node/src/main/java/com/hedera/services/txns/file/FileAppendTransitionLogic.java (hunk 9 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/txns/file/FileAppendTransitionLogic.java:99]: In the future, we may want to generalize the `sigImpactHistorian` to a `changeHistorian`; so that **any** change to an entity causes it to be marked as changed.

But right now, **only** changes that can impact the result of `SigRequirements.keyForPayer()` and `SigRequirements.keysForOtherPayers()` cause anything to be marked as changed.

Comment (Neeharika-Sompalli) [reply hedera-node/src/main/java/com/hedera/services/txns/file/FileAppendTransitionLogic.java:99]: Ah I see. Got it. Thank you!

File: hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java:79]: If we call `nodeInfo.isSelfZeroStake()` here, it will cause a NPE because the working `StateAccessor` will not yet have had its children updated [here](https://github.com/hashgraph/hedera-services/blob/02019-M-TrackReferencedEntities/hedera-node/src/main/java/com/hedera/services/ServicesState.java#L365).

File: hedera-node/src/main/java/com/hedera/services/grpc/GrpcStarter.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/grpc/GrpcStarter.java:100]: The `AddressBook` object here doesn't come from a protobuf message, but from _config.txt_; and until Platform changes, the memos there will always contain account ids.

File: hedera-node/src/main/java/com/hedera/services/context/ImmutableStateChildren.java [hunk 11]
```diff
@@ -0,0 +1,42 @@
+package com.hedera.services.context;
+
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/context/ImmutableStateChildren.java:2]: 😖

File: hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java (hunk 7 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/state/StateAccessor.java:48]: Done.

File: hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/main/java/com/hedera/services/queries/QueriesModule.java:79]: I see. Thank you!

File: test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java (hunk 8 above)
Comment (tinker-michaelj) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleCreateSpecs.java]: Done.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

File: hedera-node/src/main/java/com/hedera/services/grpc/GrpcStarter.java (hunk 6 above)
Comment (anighanta) [reply hedera-node/src/main/java/com/hedera/services/grpc/GrpcStarter.java:100]: Got it. The protobuf message is built from this config.txt anyway right.

File: hedera-node/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java [hunk 12]
```diff
@@ -141,6 +141,7 @@ public void submitRecordsTo(final AccountRecordsHistorian recordsHistorian) {
 			final var syntheticCreation = pendingCreation.syntheticBody();
 			final var childRecord = pendingCreation.recordBuilder();
 			sigImpactHistorian.markAliasChanged(childRecord.getAlias());
+			sigImpactHistorian.markEntityChanged(childRecord.getReceiptBuilder().getAccountId().num());
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java:144]: which entity would this be ?

**Review by Neeharika-Sompalli — APPROVED** [review]
