### PR TITLE
fix: fix schedules-by-equality migration, fractional custom fees, and special reward situations

### LINKED ISSUE #11805: (02/18 - 23:45:43) Expected `IDENTICAL_SCHEDULE_ALREADY_CREATED` but was `SUCCESS`
### Description

Transaction in HashScan [here](https://hashscan.io/mainnet/transaction/1708299943.039072763).

A scheduled transaction with the below body **should** have been detected as identical to the existing schedule `0.0.4714734`. Instead mod-service scheduled a new transfer.
```
scheduleCreate {
  scheduledTransactionBody {
    transactionFee: 100000000
    cryptoTransfer {
      transfers {
      }
      tokenTransfers {
        token {
          tokenNum: 1779935
        }
        transfers {
          accountID {
            accountNum: 540219
          }
          amount: -5593457986
        }
        transfers {
          accountID {
            accountNum: 657396
          }
          amount: 5593457986
        }
      }
    }
  }
  memo: "0xae51619b0d4e347be924d743afb9419abe33d652b40e1848f066657396e31f65-26"
  payerAccountID {
    accountNum: 540286
  }
}
```

### Steps to reproduce

Re-run events from round 162876015

### Additional context

_No response_

### Hedera network

other

### Version

`develop`

### Operating system

None

### LINKED ISSUE #11813: (02/19 - 00:00:37) Mismatched amount values
Transaction in HashScan [here](https://hashscan.io/mainnet/transaction/1708300837.774136717). 

Token transfer should have been split between 5 recipients. Instead, all tokens went to first recipient.

Matching field 'amount'  ==> expected: <9134535000000> but was: <9522942856020>

```
transactionID {
  transactionValidStart {
    seconds: 1708300827
    nanos: 386418344
  }
  accountID {
    accountNum: 1061772
  }
}
nodeAccountID {
  accountNum: 19
}
transactionFee: 100000000
transactionValidDuration {
  seconds: 120
}
memo: "Drop Reward - 96153 REV"
cryptoTransfer {
  transfers {
  }
  tokenTransfers {
    token {
      tokenNum: 1704513
    }
    transfers {
      accountID {
        accountNum: 729874
      }
      amount: 9615300000000
      is_approval: true
    }
    transfers {
      accountID {
        accountNum: 1396809
      }
      amount: -9615300000000
      is_approval: true
    }
  }
}
```

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #11805 
 - Closes #11813
 - Migrate to correct key for schedule-by-equality map
 - Assess multiple fractional fees to a debit _always in terms of the initial debit_; and not in terms of what remained after applying earlier fractional fees.
 - Include `rewardRate` and `SUCCESS` status in `NodeStakeUpdateTransactionBody`.
 - Support two mono-service special cases for reward situations (on top-level `SUCCESS`): 
    1. Accounts in a `CryptoTransfer` transfer list with a `0` adjustment amount.
    2. Called contracts in a contract operation.

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 1]
```diff
@@ -609,6 +615,59 @@ private void handleUserTransaction(
...
 
+    /**
+     * Returns a set of "extra" account ids that should be considered as eligible for
+     * staking rewards with the given transaction info and record builder. Needed for
+     * mono-service fidelity.
+     *
+     * <p>There are two cases.
+     * <ol>
+     *     <li>For a crypto transfer, any account explicitly given a zero amount
+     *     should be considered as eligible for staking rewards.</li>
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:626]: Is this because we actually don't change that account in state, so its not in modifications ? Also isn't mono-service behavior wrong ?

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchema.java [hunk 2]
```diff
@@ -144,26 +146,30 @@ public void value(long scheduleId) {
...
+                            final var existingList = schedulesByEquality.get(equalityKey);
+                            final List<Schedule> existingSchedules = existingList == null
+                                    ? new ArrayList<>()
+                                    : new ArrayList<>(existingList.schedulesOrElse(Collections.emptyList()));
+                            existingSchedules.add(schedule);
+                            schedulesByEquality.put(
+                                    equalityKey,
+                                    ScheduleList.newBuilder()
+                                            .schedules(existingSchedules)
+                                            .build());
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/schemas/InitialModServiceScheduleSchema.java:165]: Great catch 💯

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java [hunk 3]
```diff
@@ -58,19 +61,12 @@ public static void logSuccessfulFungibleTransfer(
...
-            } else {
-                senderId = adjust.accountIDOrThrow();
-            }
+        final var credit = adjusts.getFirst();
+        if (credit.amount() < 0) {
+            throw new IllegalArgumentException("Credit adjustment must appear first");
         }
-        frame.addLog(builderFor(tokenId, senderId, receiverId, accountStore)
-                .forDataItem(amount)
+        frame.addLog(builderFor(tokenId, adjusts.getLast().accountIDOrThrow(), credit.accountIDOrThrow(), accountStore)
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java:68]: `adjusts.getLast()`. Do we know what will be the last adjust all the times ? 🤔 
Is this to make it behave like mono-service balance changes?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java [hunk 4]
```diff
@@ -94,32 +92,29 @@ public void assessFractionalFees(
...
                 continue;
             }
+            final var fractionalFee = fee.fractionalFeeOrThrow();
 
-            // calculate amount that should be paid for fractional custom fee
-            var assessedAmount = amountOwed(unitsLeft, fractionalFee);
+            // calculate amount that should be paid for fractional custom fee;
+            // note the fraction is always calculated from the initial adjustment,
+            // not from the units left after previous fees
+            var assessedAmount = amountOwed(-initialAdjustment, fractionalFee);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java:104]: Makes sense. Thank you!

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM , just have few minor questions/comments. Thanks @tinker-michaelj

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java]: Yes mono-service has "false positives" in its reward situation detection, because it is triggered by presence of the `BALANCE` property in an entity's `TransactionalLedger` change set. (As you well know. 😁)

Updated the javadoc here to reflect this.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java (hunk 3 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/TransferEventLoggingUtils.java:68]: This utility is only used to log ERC-style transfers (exactly two adjustments---one credit, one debit). And this method throws an `IllegalArgumentException` if the first adjustment is a debit. 

I.e., the input `List<AccountAmount>` always has the form `[(0.0.<receiver>, +X), (0.0.<sender>, -X)]`.

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @tinker-michaelj !

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by iwsimon — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java [hunk 5]
```diff
@@ -165,6 +168,9 @@ public class SingleTransactionRecordBuilderImpl
     // These are not persisted to the record file
     private final Map<AccountID, AccountID> deletedAccountBeneficiaries = new HashMap<>();
 
+    @Nullable
```
Comment (lukelee-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:171]: A comment here to explain this field would be great.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java [hunk 6]
```diff
@@ -168,7 +168,7 @@ public void validateSemantics(
 
             // Verify that the current total number of (counted) fungible transfers does not exceed the limit
             validateTrue(
-                    totalFungibleTransfers < ledgerConfig.tokenTransfersMaxLen(),
+                    totalFungibleTransfers <= ledgerConfig.tokenTransfersMaxLen(),
```
Comment (lukelee-sl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java:171]: Was this just to match mono service?  Did this actually make a difference?

**Review by lukelee-sl — APPROVED** [review]
LGTM.  Generally makes sense to me but what a lot of extra code to match odd mono service behavior.  Mostly, focused on the smart contract related classes.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 5 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:171]: Ah yes, adding in current branch. 💯

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java:171]: Yes it makes a difference; we want to allow up to 10 adjustments in this list, so `<=` is necessary given the default property value.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java (hunk 5 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java:171]: Oh wait that field is gone in my current branch. 🤷
