### PR TITLE
fix: Fix casting exception for event-stream recover

### LINKED ISSUE #14048: PCLI `event-stream recover` broken on `develop`
### Description

I tried to replay events for diff testing and got,
```
java.lang.ClassCastException: class com.swirlds.platform.event.PlatformEvent cannot be cast to class com.swirlds.platform.system.events.DetailedConsensusEvent (com.swirlds.platform.event.PlatformEvent and com.swirlds.platform.system.events.DetailedConsensusEvent are in unnamed module of loader 'app')
	at com.swirlds.platform.recovery.EventRecoveryWorkflow.handleNextRound(EventRecoveryWorkflow.java:381)
	at com.swirlds.platform.recovery.EventRecoveryWorkflow.reapplyTransactions(EventRecoveryWorkflow.java:337)
	at com.swirlds.platform.recovery.EventRecoveryWorkflow.recoverState(EventRecoveryWorkflow.java:173)
	at com.swirlds.platform.cli.EventStreamRecoverCommand.call(EventStreamRecoverCommand.java:129)
	at com.swirlds.platform.cli.EventStreamRecoverCommand.call(EventStreamRecoverCommand.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
```

### Steps to reproduce

Run PCLI `event-stream recover` starting from round `173775308`.

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### PR DESCRIPTION
**Pull request by timo0**
Fix #14048

### CODE REVIEW

**Review by edward-swirldslabs — APPROVED** [review]

**Review by edward-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java [hunk 1]
```diff
@@ -378,8 +377,8 @@ private static ReservedSignedState handleNextRound(
         final Instant currentRoundTimestamp = getRoundTimestamp(round);
         previousState.get().getState().throwIfImmutable();
         final MerkleRoot newState = previousState.get().getState().copy();
-        final DetailedConsensusEvent lastEvent = (DetailedConsensusEvent) getLastEvent(round);
-        new StatefulEventHasher().hashEvent(lastEvent.getPlatformEvent());
+        final PlatformEvent lastEvent = (PlatformEvent) getLastEvent(round);
+        new StatefulEventHasher().hashEvent(lastEvent);
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java:381]: Is this where the event's hash is set?  I'm not familiar with this code enough to determine if this is the right solution.  I think @cody-littley  or @litt3 should weigh in.

Comment (litt3) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java:381]: This hashing bit seems alright to me (since it's where the hash was being set in this workflow before, too)

As to the PR in general, it's not clear to me why `PlatformEvent` is being modified.

**Review by edward-swirldslabs — APPROVED** [review]

**Review by litt3 — CHANGES_REQUESTED** [review]
@timo0 Could you explain the requirement to modify `PlatformEvent` in this PR? I'm not understanding why the `EventRecoveryWorkflow` (which is on the way out the door anyway) would precipitate a seemingly hacky change to the `PlatformEvent`

**Review by litt3 — DISMISSED** [review]
lgtm

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java (hunk 1 above)
Comment (timo0) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java:382]: I've talked with Lazar and we changed the Event Iterator

**Review by litt3 — APPROVED** [review]

**Review by lpetrovic05 — APPROVED** [review]
