### PR TITLE
00906 d token test failure

### LINKED ISSUE #906: Token Test Scenarios Failing
**Summary of the defect**
Token test scenarios failing in test `Misc-Basic-1-11m.json`
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609263264345900
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609445428398600

**Service logs (if applicable)**
```
[hapi-client-combined.log](https://github.com/hashgraph/hedera-services/files/5758419/hapi-client-combined.log)

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #906 

**Summary of the change**:
1. The root cause is the api-permission.properties didn't get the right file from configuration/dev.  The one in Anirudh's branch doesn't have HTS permissions;
2. Added one test case to help quickly identifying the issue.

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java [hunk 1]
```diff
@@ -367,6 +368,22 @@ public HapiApiSpec creationRequiresAppropriateSigs() {
...
 	}
 
+	public HapiApiSpec creationRequiresAppropriateSigsHappyPath() {
+		return defaultHapiSpec("CreationRequiresAppropriateSigsHappyPath")
+				.given(
+						cryptoCreate("payer"),
+						cryptoCreate(TOKEN_TREASURY).balance(0L),
+						newKeyNamed("adminKey")
+				).when().then(
+						tokenCreate("shouldntWorkEither")
```
Comment (anighanta) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java:378]: looks good other than the name of this token should be "shouldWork" or anything appropriate

**Review by anighanta — CHANGES_REQUESTED** [review]

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java (hunk 1 above)
Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java]: Agree. Changed.

**Review by anighanta — APPROVED** [review]
