### PR TITLE
Generate sidecars for failing top-level contract creates

### LINKED ISSUE #3723: Create sidecar records for failing transactions
### Problem

There are some scenarios, e.g. when a ContractCreateTransaction fails, in which we don't create `ContractAction`, `ContractStateChange`, and `ContractBytecode` sidecar records. 
Users of the smart contract service may expect the sidecar records to exist in order to more easily debug the failures.
`ContractBytecode` sidecars can be created only for:
- all non-reverted creates
- a failing top-level create transaction, in which case we only need to populate the init bytecode and not the runtime bytecode

### Solution

Create the sidecar records for failing transactions

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by dimitar-dinev**
**Description**:
Modifies `TransactionRecordService` and `ContractCreateTransitionLogic` to include sidecars for failed creates where the initcode is extracted from a file (not inline in the transaction). 

**Related issue(s)**:

Fixes #3723 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java [hunk 1]
```diff
@@ -259,7 +259,15 @@ public void doStateTransitionOperation(
             txnCtx.setTargetedContract(newContractId);
             sigImpactHistorian.markEntityChanged(newContractId.getContractNum());
         } else {
-            recordService.externalizeUnsuccessfulEvmCreate(result);
+            if (properties.enabledSidecars().contains(SidecarType.CONTRACT_BYTECODE)
+                    && op.getInitcodeSourceCase() != INITCODE) {
```
Comment (IvanKavaldzhiev) [inline hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java:263]: Shouldn't we also track failing init bytes which are less than the Hedera maximum limit (not uploaded in File)?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Re-posting issue comment here:

The mirror node needs a contract ID to exist to associate with the state changes, actions and bytecode in the db and to query via the API. What would be the contract ID if a create fails and is not assigned a contract ID?

**Comment by stoqnkpL** [comment]
> Re-posting issue comment here:
> 
> The mirror node needs a contract ID to exist to associate with the state changes, actions and bytecode in the db and to query via the API. What would be the contract ID if a create fails and is not assigned a contract ID?

@steven-sheehy do you think we can proceed with merging these changes after our discussion on the last weekly sync?
