### PR TITLE
Fix NPE when DualState is null in older states

### LINKED ISSUE #2349: Fix NPE when DualState is null in an older state
When using `0.16` state as the DualState is not present in the state, migration tests fail with NPE. 
```
{"instant":{"epochSecond":1634710808,"nanoOfSecond":894225436},"thread":"main","level":"ERROR","loggerName":"com.swirlds.platform.Browser","marker":{"name":"EXCEPTION"},"message":"","thrown":{"commonElementCount":0,"localizedMessage":"Cannot invoke \"com.swirlds.common.SwirldDualState.getFreezeTime()\" because \"dualState\" is null","message":"Cannot invoke \"com.swirlds.common.SwirldDualState.getFreezeTime()\" because \"dualState\" is null","name":"java.lang.NullPointerException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","threadId":1,"threadPriority":5}
```
Add a null pointer check in ServicesState if we are loading from an older state.

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Closes #2349 

Add NPE check for older states version when dual state is null.

Passed migration test with older state :  https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1634750604120500

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/ServicesState.java [hunk 1]
```diff
@@ -441,6 +442,11 @@ private void internalInit(
 					.build();
 			APPS.save(selfId, app);
 		}
+
+		// When migrating from an older state dual state can be null
+		if (dualState == null) {
+			dualState = new DualStateImpl();
+		}
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/ServicesState.java:449]: is this required for just this migration iteration?
