### PR TITLE
Fix flaky qeuue thread busy time test.

### LINKED ISSUE #6792: busyTimeMetricTest() flake
I observed the following test flake on a branch of mine:

```
     ✘ busyTimeMetricTest() Test

      org.opentest4j.AssertionFailedError: 
      expected: 0.5
       but was: 1.0
          at app//com.swirlds.common.test.threading.QueueThreadTests.busyTimeMetricTest(QueueThreadTests.java:927)
```

https://github.com/hashgraph/hedera-services/actions/runs/5080743539/jobs/9128131550?pr=6705

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #6792

### CODE REVIEW

**Review by alittley — DISMISSED** [review]

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java [hunk 1]
```diff
@@ -920,11 +975,21 @@ void busyTimeMetricTest() throws InterruptedException {
...
+            NANOSECONDS.sleep(1);
+        }
         // advance time again
         time.tick(Duration.ofSeconds(1));
+        // allow the thread to unblock from polling
+        queue.unblockPolling();
 
         // then
-        assertThat(busyTimeMetric.get()).isEqualTo(0.5);
+        assertEventuallyEquals(0.5, busyTimeMetric::get, Duration.ofSeconds(1), "busy time was not measured correctly");
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java:990]: why eventually? shouldn't it be immediate?

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java [hunk 2]
```diff
@@ -884,6 +895,48 @@ void testQueueMaxMinSizeMetricsWithoutThreadStart() {
         assertThat(minSizeMetric.get()).isZero();
     }
 
+    /**
+     * This queue implementation allows us to artificially cause poll() to block.
+     */
+    private static class ControllableQueue extends AbstractBlockingQueue<Integer> {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java:901]: probably better to put this into a separate file

**Review by lpetrovic05 — DISMISSED** [review]

**Review by alittley — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/ControllableQueue.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+
+    public ControllableQueue() {
+        super(new LinkedBlockingQueue<>());
+    }
+
+    @Override
+    public synchronized Integer poll(long timeout, TimeUnit unit) throws InterruptedException {
+        pollBlockedCount.incrementAndGet();
+        pollLock.lock();
+        pollLock.unlock();
```
Comment (hendrikebbers) [inline platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/ControllableQueue.java:40]: I do not get the code / functionality of that class. Why do you lock a resource when you directly unlock it?
