### PR TITLE
fix: Fail cleanly on negative gas limit

### LINKED ISSUE #17470: throttle overflow

### PR DESCRIPTION
**Pull request by kimbor**
**Description**:
When a contract transaction is submitted with a negative gas limit, we currently throw an exception. Instead we should return INSUFFICIENT_GAS.

**Related issue(s)**:
Fixes #17470 
Issue #17523 is related to this one, as fixing that issue will make it impossible for negative gasLimits to occur for ethereum calls.

### CODE REVIEW

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java [hunk 1]
```diff
@@ -61,6 +61,9 @@ public boolean allow(@NonNull final Instant now, final long txGasLimit) {
             throw new IllegalArgumentException("Throttle timeline must advance, but " + now + " is not after "
                     + Instant.ofEpochSecond(lastDecisionTime.seconds(), lastDecisionTime.nanos()));
         }
+        if (txGasLimit < 0) {
+            throw new IllegalArgumentException("Gas limit must be non-negative, but was " + txGasLimit);
+        }
```
Comment (david-bakin-sl) [inline hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java:66]: Is this reasonable for it to throw on negative?  I traced back one call chain (the one through `ThrottleAccumulator.checkAndEnforceThrottle`) to `QueryWorkflowIMpl.handleQuery` which is the first one with a `try/catch` and it looks like that'll catch it as a `Exception`, emit an error, and than fail the transaction.  Instead of reporting `BUSY` (which, admittedly, is odd for negative gas, probably should be caught and translated to`INSUFFICIENT_GAS`).  There's another call chain too, I didn't follow it to the tops of it, but doesn't look like any close exception handler there either.  If we're sticking with the signature of this method so that it returns `boolean` maybe it should just return `false` - it's invalid input so just throttle it.

Or maybe it just needs to throw a `PrecheckException` instead of `IllegalArgumentException`.

Comment (david-bakin-sl) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java:66]: Also, should have a test for negative in `GasLimitDeterministicThrottleTest`.

Comment (david-bakin-sl) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java:66]: Also, I wonder if we should disallow anything less than the intrinsic gas limit here.  It's just going to get rejected at precheck anyway.  Is there a reason to disallow those txs earlier?  Some kind of fairness or DoS argument?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java [hunk 2]
```diff
@@ -277,6 +280,25 @@ private void assertThrottlingPreconditions(
...
+                    case ETHEREUM_TRANSACTION -> Optional.of(txInfo.txBody()
+                                    .ethereumTransactionOrThrow()
+                                    .ethereumData()
+                                    .toByteArray())
+                            .map(EthTxData::populateEthTxData)
+                            .map(EthTxData::gasLimit)
+                            .orElse(0L);
+                    default -> 0L;
+                };
+        if (gas < 0) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java:299]: Again, my question would be: Why `<0` instead of `<=0` or even `<= 21000`.   

(Don't know the answer here or above, which is why I'm asking.)

In this case you'd have to signal the `default` case - i.e., not a contract-related operation throttled by gas - separately than using `0L`.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java [hunk 3]
```diff
@@ -1272,4 +1272,29 @@ final Stream<DynamicTest> callHtsSystemContractTest() {
                                     .hasKnownStatus(SUCCESS));
                 }));
     }
+
+    @HapiTest
+    final Stream<DynamicTest> negativeGasFailsGracefully() {
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java:1277]: This tests new code at `IngestChecker.assertThrottlingPreconditions`.  Needs a separate test for new code at `GasLimitDeterministicThrottle.allow`.  If there's a way to hapispec test throttles, don't know.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java:299]: Needs a test in `IngestCheckerTest.ThrottleTests`?

Actually, I don't see a test for any of the conditions in `assertThrottlingPreconditions`.  Also actually, `assertThrottlingPreconditions` seems misnamed?  Until this code you just added it doesn't seem to be checking _throttling_ preconditions at all, just some interesting system preconditions.

**Review by david-bakin-sl — COMMENTED** [review]
Questions you could answer if you wish, and a request for some testi for the change to `GasLimitDeterministicThrottle`.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java:66]: For my first iteration of this PR, I had it throwing a `PreCheckException` here. I ended up changing that on the grounds that I didn't want to add a dependency on `com.hedera.node.app.spi` module. The throws `IllegalArgumentException` is just a sanity check, any execution path should fail long before it gets here.

Comment (kimbor) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java:66]: I will add a test for negative gasLimit in `GasLimitDeterministicThrottleTest`.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java (hunk 2 above)
Comment (kimbor) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java:299]: Most of the preconditions are checked during `pureChecks` methods on each transaction type. That's where we check whether the gas limit is <=intrinsicGas. But, checking throttles comes earlier in the ingest workflow than running pureChecks. Before we check throttles, we do just the bare minimum checks necessary to ensure that the throttle checking code will succeed. That's what this method is about.

Comment (kimbor) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java:299]: And yes, I'll add that test too.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java (hunk 3 above)
Comment (kimbor) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java:1277]: The GasLimitDeterministicThrottle.allow txGasLimit<0 code path should never execute. I'll create a unit test for it but I don't think there's any way to create a hapi test.

File: hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java:66]: New test added

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java (hunk 2 above)
Comment (kimbor) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java:299]: Test added

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java (hunk 3 above)
Comment (kimbor) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java:1277]: Unit test created

**Review by david-bakin-sl — DISMISSED** [review]
LGTM

**Review by david-bakin-sl — APPROVED** [review]
LGTM

**Review by tinker-michaelj — APPROVED** [review]
LGTM, tyvm @kimbor !
