### PR TITLE
fix(23907): ReconnectControllerTest flakiness

### LINKED ISSUE #23907: Flaky Test: `ReconnectControllerTest.controllerGracefullyStopsWhenStopReconnectLoopIsCalledAndThreadIsInterrupted()`
Test Flake: https://scans.gradle.com/s/sxqgfhk6wcrd2

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
Adding async verification for async operation

**Related issue(s)**:

Fixes #23907

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: platform-sdk/consensus-reconnect-impl/src/test/java/org/hiero/consensus/reconnect/impl/ReconnectControllerTest.java [hunk 1]
```diff
@@ -787,12 +787,13 @@ void controllerGracefullyStopsWhenStopReconnectLoopIsCalledAndThreadIsInterrupte
...
-        assertNull(
-                systemExitCalled.get(),
+        assertEventuallyTrue(
+                () -> !systemExitCalled.get(),
+                LONG_TIMEOUT,
                 "SystemExitUtils.exitSystem should not have been called on expected InterruptedException");
 
         // Verify the thread finished correctly
-        assertFalse(scenario.isControllerAlive());
+        assertEventuallyTrue(() -> !scenario.isControllerAlive(), LONG_TIMEOUT, "Controller should have been stopped");
```
Comment (poulok) [inline platform-sdk/consensus-reconnect-impl/src/test/java/org/hiero/consensus/reconnect/impl/ReconnectControllerTest.java:796]: nit: it would be nice to implement the inverse method, `assertEventuallyFalse` so we don't have to invert the logic of this code. Up to you if you want to do this.

Comment (mxtartaglia-sl) [reply platform-sdk/consensus-reconnect-impl/src/test/java/org/hiero/consensus/reconnect/impl/ReconnectControllerTest.java:796]: Makes sense to avoid duplication, but I will leave implementing that version for the future when more cases require it. My goal was not to be dependent on this method at all; I had to use it, but it seems to me that, unless absolutely necessary, the fewer versions of it we have throughout the codebase, the better.
