### PR TITLE
fix: fixed a few issues on Dynamic Address Book

### LINKED ISSUE #14242: Fixed a few issues on Dynamic Address Book
Updated NodeUpdateTest, NodeCreateTest
Fixed HapiSpecRegistry.saveNodeMeta()
Fixed V053AddressBookSchema.migrate() adminKey default by checking account 55 key first.
Organized code so some common methods can be used.
Changed name to "node"+(nodeid+1) from node.description.

### LINKED ISSUE #14329: Assume node self-name is `node<NODE_ID+1>`, decouple from `Node#description` field
### Problem

We temporarily used the [`Node#description`](https://github.com/hashgraph/hedera-protobufs/blob/0deeafce2451b620aaddac291896e8d5cb257fcd/services/state/addressbook/node.proto#L62) protobuf type to allow test clients to inform the network of non-standard "self names" used in the test _config.txt_.

This was not a permanent change, as we want to standardize all self-names to `node<NODE_ID+1>`.

### Solution

Remove the `NodeInfo#selfName` [field](https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/spi/info/NodeInfo.java#L109) and decouple `Node#description` from _config.txt_ self names.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by iwsimon**
**Description**:

Updated NodeUpdateTest, NodeCreateTest
Fixed HapiSpecRegistry.saveNodeMeta()
Fixed V053AddressBookSchema.migrate() adminKey default by checking account 55 key first.
Organized code so some common methods can be used.
Changed name to "node"+(nodeid+1) from node.description.

**Related issue(s)**:

Fixes #14242 
Fixes #14329

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java [hunk 1]
```diff
@@ -263,13 +270,12 @@ final Stream<DynamicTest> failOnTooManyServiceEndpoints() {
...
         return hapiTest(
                 newKeyNamed(ED_25519_KEY).shape(KeyShape.ED25519),
-                overriding("nodes.gossipFqdnRestricted", "false"),
                 nodeCreate("nodeCreate")
                         .description("hello")
                         .gossipCaCertificate("gossip".getBytes())
                         .grpcCertificateHash("hash".getBytes())
                         .accountId(asAccount("0.0.100"))
-                        .gossipEndpoint(GOSSIP_ENDPOINTS)
+                        .gossipEndpoint(GOSSIP_ENDPOINTS_IPS)
```
Comment (kimbor) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:278]: Why did you change this? With this change, the test becomes identical to allFieldsSetHappyCaseForIps() case defined below.

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java [hunk 2]
```diff
@@ -65,13 +70,30 @@ public void migrate(@NonNull final MigrationContext ctx) {
...
-                Key.newBuilder().ed25519(bootstrapConfig.genesisPublicKey()).build();
+        final var accountConfig = ctx.configuration().getConfigData(AccountsConfig.class);
+        var adminKey = Key.DEFAULT;
+        if (readableAccounts != null) {
+            final var adminAccount = readableAccounts.get(AccountID.newBuilder()
+                    .accountNum(accountConfig.addressBookAdmin())
+                    .build());
+            if (adminAccount != null) {
+                adminKey = adminAccount.keyOrElse(Key.DEFAULT);
+            }
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java:90]: If this is null it is error right ?

File: hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+package com.hedera.node.app.service.addressbook;
+
+import static java.util.Objects.requireNonNull;
+import static java.util.Spliterator.DISTINCT;
+
+import com.hedera.hapi.node.state.common.EntityNumber;
+import edu.umd.cs.findbugs.annotations.NonNull;
+import java.util.Spliterators;
+import java.util.stream.StreamSupport;
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:26]: nit: javadoc for class

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java [hunk 4]
```diff
@@ -220,13 +219,12 @@ private void extractAndReplaceArtifacts(
             FileUtils.cleanDirectory(artifactsDir);
             UnzipUtility.unzip(archiveData.toByteArray(), artifactsLoc);
             log.info("Finished unzipping {} bytes for {} update into {}", size, desc, artifactsLoc);
-            if (desc.equals(PREPARE_UPGRADE_DESC)) {
-                requireNonNull(nodes, "Cannot generate config.txt without a valid list of active nodes");
+            if (nodes != null) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java:222]: Why is this condition changed?

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java [hunk 5]
```diff
@@ -235,6 +233,13 @@ private void extractAndReplaceArtifacts(
         }
     }
 
+    private long getNextNodeID(@NonNull List<ActiveNode> nodes) {
+        requireNonNull(nodes);
+        final long maxNodeId =
+                nodes.stream().mapToLong(a -> a.node.nodeId()).max().orElse(-1L);
+        return maxNodeId + 1;
+    }
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java:242]: Can we move this also to `AddressBookHelper` ? Can we re-use one version of this method?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java [hunk 6]
```diff
@@ -443,6 +450,33 @@ final Stream<DynamicTest> failsAtIngestForUnAuthorizedTxns() {
                         .via("nodeCreation"));
     }
 
+    @LeakyHapiTest(overrides = {"nodes.maxNumber"})
```
Comment (tinker-michaelj) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:453]: These tests are so (admirably!) focused that it barely matters, but the [checklist](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/README.md#the-hapitest-checklist) advises using an explicit `@DisplayName`.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:278]: They not the same. I wanted to test the default nodes.gossipFqdnRestricted setting without overriding, gossipEndpoint can only accept ip address, not domain name. You had nodes.gossipFqdnRestricted overrides in both allFieldsSetHappyCaseForDomains and allFieldsSetHappyCaseForIps.

File: hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java (hunk 2 above)
Comment (iwsimon) [reply hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V053AddressBookSchema.java:90]: readableAccounts.get(AccountID) is @Nullable. So I checked the null here.

File: hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java (hunk 3 above)
Comment (iwsimon) [reply hedera-node/hedera-addressbook-service/src/main/java/com/hedera/node/app/service/addressbook/AddressBookHelper.java:26]: Added.

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java (hunk 4 above)
Comment (iwsimon) [reply hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java:222]: Because we have this check earlier:
 final var activeNodes = desc.equals(PREPARE_UPGRADE_DESC) ? allActiveNodes() : null;

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java (hunk 5 above)
Comment (iwsimon) [reply hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java:242]: The reason I created AddressBookHelper initially is tried to re-use getNextNodeID(@NonNull final ReadableNodeStore nodeStore) here. But I kept on getting failed immutable exception during DabEnabledUpgradeTest by using it, I was going to check with you and @tinker-michaelj later. This small function get me to pass that error for now.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java (hunk 6 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:454]: Added @DisplayName.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java (hunk 1 above)
Comment (kimbor) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:279]: Ok, but now there is no place that domain names are being tested. There needs to be a test that overrides gossipFqdnRestricted and then uses domain names.

Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:279]: Updated the test with domain names.

Comment (kimbor) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip869/NodeCreateTest.java:279]: Looks good, thanks!

File: hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java (hunk 5 above)
Comment (iwsimon) [reply hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java:242]: Since this is called in ExecutorService thread, we can't use ReadableStore directly.

**Review by kimbor — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @iwsimon
