### PR TITLE
06677 pces discontinuity

### LINKED ISSUE #6677: Detect and handle fragmented PCES
Until we require state saving after reconnect to be synchronous (i.e. we wait until the state is on disk before starting gossip), there is the possibility that an untimely crash will leave the preconsensus event stream in a fragmented state. That is, we may load the latest state from disk and start replaying the stream, but find out that we are missing events before we get to the end of the stream.

We need to 
1) detect when we do a replay across a fragmentation boundary
2) enable automated cleanup of a fragmented stream
3) events "deleted" when repairing a fragmented stream should be stored in directory that we can get access to if things go really, really wrong

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #6677

### CODE REVIEW

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java [hunk 1]
```diff
@@ -191,13 +297,28 @@ public PreConsensusEventMutableFile getMutableFile() throws IOException {
      *
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java:297]: Perhaps add a note to the javadoc that this method permanently deletes the file, without going to a recycle bin

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java [hunk 2]
```diff
@@ -252,11 +375,13 @@ private static Path buildParentDirectory(final Path rootDirectory, final Instant
...
      * @return the file name
      */
+    @NonNull
     private static String buildFileName(
             final long sequenceNumber,
             final long minimumGeneration,
             final long maximumGeneration,
-            final Instant timestamp) {
+            @NonNull final Instant timestamp,
+            final boolean discontinuity) {
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java:384]: new parameter missing param doc

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 3]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
+            return Collections.emptyIterator();
+        }
+
+        // Edge case: our first file comes after the requested starting generation
+        if (files.getFirst().getMinimumGeneration() >= minimumGeneration) {
+            // Unless we observe at least one file with a minimum generation less than the requested minimum,
+            // then we can't know for certain that we have all data for the requested minimum generation.
+            logger.warn(
+                    STARTUP.getMarker(),
+                    "The preconscious event stream has insufficient data to guarantee that all events with the "
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:308]: "preconscious" implies that the event streams may eventually become conscious, which I think we should do our best to prevent

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 4]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
+                            + "requested generation of {} are present, the first file has a minimum  generation of {}",
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:309]: nit: extra space between words `minimum  generation`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 5]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
-                return Collections.emptyIterator();
+            logger.warn(STARTUP.getMarker(), "No preconsensus event files available");
+            return Collections.emptyIterator();
+        }
+
+        // Edge case: our first file comes after the requested starting generation
+        if (files.getFirst().getMinimumGeneration() >= minimumGeneration) {
+            // Unless we observe at least one file with a minimum generation less than the requested minimum,
+            // then we can't know for certain that we have all data for the requested minimum generation.
+            logger.warn(
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:306]: Is a warning stern enough for this edge case?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 6]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
-            // may not land on the first file in the sequence. Shift to the left until the first file
-            // with the desired maximum generation is discovered.
-            while (index > 0 && files.get(index - 1).maximumGeneration() == minimumGeneration) {
-                index--;
+        // Edge case: all of our data comes before the requested starting generation
+        if (files.getLast().getMaximumGeneration() < minimumGeneration) {
+            logger.warn(
+                    STARTUP.getMarker(),
+                    "The preconscious event stream has insufficient data to guarantee that "
+                            + "all events with the requested minimum generation of {}, "
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:324]: This sentence is incomplete

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 7]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
+                            + "first deleted file: {}, last file in stream: {}",
+                    files.get(indexOfDiscontinuity),
+                    files.getLast());
+        } else {
+            final PreConsensusEventFile lastUndeletedFile =
+                    files.size() == 0 ? null : files.get(indexOfDiscontinuity - 1);
+
+            logger.error(
+                    EXCEPTION.getMarker(),
+                    "Discontinuity detected in preconscious event stream, "
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:388]: "preconscious"

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java [hunk 8]
```diff
@@ -192,6 +194,31 @@ public void writeEvent(@NonNull final EventImpl event) {
...
+        if (currentMutableFile != null) {
+            closeFile();
+        }
+
+        final PreConsensusEventFile file = fileManager.getNextFileDescriptor(0, 0, true);
+
+        try {
+            Files.createFile(file.getPath());
+        } catch (final IOException e) {
+            throw new UncheckedIOException("unable create file to mark discontinuity", e);
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java:218]: "unable *to* create file..."

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 3 above)
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:308]: We're operating at the speed of the autonomic nervous system.  No time for consciousness to be involved.

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java [hunk 9]
```diff
@@ -161,11 +161,16 @@ public static void assertEventsAreEqual(final EventImpl expected, final EventImp
...
-     * @param platformContext the platform context
+     * @param events             the events that were written to the stream
+     * @param platformContext    the platform context
+     * @param truncatedFileCount the expected number of truncated files
+     * @param fixDiscontinuities whether to fix discontinuities in the stream
      */
     static void verifyStream(
-            final List<EventImpl> events, final PlatformContext platformContext, final int truncatedFileCount)
+            final List<EventImpl> events,
+            final PlatformContext platformContext,
```
Comment (edward-swirldslabs) [inline platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java:171]: Nullity marking

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreConsensusEventWriter.java [hunk 10]
```diff
@@ -266,4 +288,18 @@ private void flushRequestedHandler(@NonNull final FlushRequested flushRequested)
             Thread.currentThread().interrupt();
         }
     }
+
+    /**
+     * Notify the wrapped writer that there is a discontinuity.
+     */
+    private void discontinuityHandler(final Discontinuity discontinuity) {
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreConsensusEventWriter.java:295]: Oversight, would have added it if I had remembered. Fixed.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java [hunk 11]
```diff
@@ -87,6 +85,57 @@ public record PreConsensusEventFile(
      */
     public static final String MAXIMUM_GENERATION_PREFIX = "maxg";
 
+    private final long sequenceNumber;
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java:88]: done

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java:384]: added

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java:297]: Updated, let me know if you want additional clarification.

```
Delete a file (permanently).
```

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 3 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:308]: Good catch, we wouldn't accidentally want to create a skynet situation.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 4 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:309]: fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 5 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:306]: The main problem is that I think we may hit this edge case often (or always) when restarting from a state saved during a reconnect.

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 12]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
-            // If there are multiple files in a row with the same maximum generation then the binary search
-            // may not land on the first file in the sequence. Shift to the left until the first file
-            // with the desired maximum generation is discovered.
-            while (index > 0 && files.get(index - 1).maximumGeneration() == minimumGeneration) {
-                index--;
+        // Edge case: all of our data comes before the requested starting generation
+        if (files.getLast().getMaximumGeneration() < minimumGeneration) {
+            logger.warn(
+                    STARTUP.getMarker(),
+                    "The preconscious event stream has insufficient data to guarantee that "
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:323]: fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 6 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:324]: fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 13]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
+     * Resolve a discontinuity at a specified index by deleting all files written after the discontinuity.
+     *
+     * @param indexOfDiscontinuity the file index of the discontinuity
+     */
+    private void resolveDiscontinuity(final int indexOfDiscontinuity) {
+
+        if (indexOfDiscontinuity == 0) {
+            logger.error(
+                    EXCEPTION.getMarker(),
+                    "Discontinuity detected at beginning of preconscious event stream, "
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:376]: fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java (hunk 7 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:388]: fixed

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java [hunk 14]
```diff
@@ -259,79 +274,145 @@ private static void fileSanityChecks(
...
+                            + "unable to replay any events in the stream. "
+                            + "All events in the stream will be deleted. "
+                            + "first deleted file: {}, last file in stream: {}",
+                    files.get(indexOfDiscontinuity),
+                    files.getLast());
+        } else {
+            final PreConsensusEventFile lastUndeletedFile =
+                    files.size() == 0 ? null : files.get(indexOfDiscontinuity - 1);
```
[the remark this answers is not in the document]
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java:384]: Good suggestion, done

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java (hunk 8 above)
Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java:218]: fixed

**Review by edward-swirldslabs — APPROVED** [review]
