### PR TITLE
fix: TokenUpdateNftsHandler throwing HandleException in preHandle

### LINKED ISSUE #14595: TokenUpdateNfts is throwing a HandeException in preHandle
https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java

2024-08-05 12:31:31.561 ERROR 149  PreHandleWorkflowImpl - Possibly CATASTROPHIC failure while running the pre-handle workflow
com.hedera.node.app.spi.workflows.HandleException: INVALID_NFT_ID
	at com.hedera.node.app.spi.workflows.HandleException.validateTrue(HandleException.java:84) ~[app-spi-0.53.0-alpha.2.jar:?]
	at com.hedera.node.app.service.token.impl.util.TokenHandlerHelper.getIfUsable(TokenHandlerHelper.java:332) ~[app-service-token-impl-0.53.0-alpha.2.jar:?]
	at com.hedera.node.app.service.token.impl.handlers.TokenUpdateNftsHandler.lambda$serialNumbersInTreasury$0(TokenUpdateNftsHandler.java:183) ~[app-service-token-impl-0.53.0-alpha.2.jar:?]

### PR DESCRIPTION
**Pull request by derektriley**
**Description**:
This PR fixes `TokenUpdateNftsHandler` to not throw a `HandleException` when the Token or Nft cannot be retrieved. Instead a `PreCheckException` will be thrown.

**Related issue(s)**:
#14204 

Fixes #14595 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java [hunk 1]
```diff
@@ -85,7 +84,8 @@ public void preHandle(@NonNull final PreHandleContext context) throws PreCheckEx
         final var txn = context.body();
         final var op = txn.tokenUpdateNftsOrThrow();
         final var tokenStore = context.createStore(ReadableTokenStore.class);
-        final var token = getIfUsable(op.tokenOrElse(TokenID.DEFAULT), tokenStore);
+        final var token = tokenStore.get(op.tokenOrElse(TokenID.DEFAULT));
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:87]: Line 78 also should be `validateTruePrecheck`

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java [hunk 2]
```diff
@@ -178,15 +178,20 @@ private boolean serialNumbersInTreasury(
...
-                        NftID.newBuilder()
-                                .tokenId(tokenId)
-                                .serialNumber(serialNumber)
-                                .build(),
-                        nftStore))
-                .allMatch(nft ->
-                        nft != null && (nft.ownerId() == null || Objects.equals(nft.ownerId(), treasuryAccount)));
+            @NonNull final TokenID tokenId)
+            throws PreCheckException {
+        for (Long serialNumber : serialNumbers) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:183]: can be `final long serialNumber`

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java (hunk 1 above)
Comment (derektriley) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:87]: Updated this.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java (hunk 2 above)
Comment (derektriley) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java]: Updated.

**Review by kimbor — APPROVED** [review]
lgtm!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateNftsHandler.java:87]: I didn't see it was updated
```
validateTrue(!op.serialNumbers().isEmpty(), MISSING_SERIAL_NUMBERS);
```
