### PR TITLE
Merge relevant work from `replay-develop`

### LINKED ISSUE #5883: Create test assets for contract service JUnit regression testing
### Problem

As we modularize the smart contract service (and its supporting token and file services), we want a way to do comprehensive regression testing that:
 - Is  faster and more repeatable than end-to-end `HapiSpec`'s; and,
 - Does not require all workflows and facilities to be available.

### Solution

- [x] :one: Create a `recording.mockFacilities` Java system property, where a "mocked facility" is a component that,
 - Is used by the `mono-service` contract, file, or token service business logic; and,
 - Would require a complex `mono-service` adapter (especially one that depends on the `mono-service` Merkle tree); or a large amount of implementation effort in the new `hedera-app` module.

- [x] :two: When the JVM is started with `-Drecording.mockFacilities=true`, make the component provision logic detect this flag when provisioning a mocked facility. Instead of the normal component, provision a subclass that delegates to it, and appends all the relevant delegate's responses to a _facility-responses.json_ that is a list of JSON objects like,
```
{
    "facility": "FeeCalculator",
    "method": "computeFee",
    "response": {
        "nodeFee": 1,
        "networkFee": 2,
        "serviceFee": 3
    } 
}
```
(Examples will include `FeeCalculator`, `EntityNumSource`, etc.)

- [x] :three: Also when `-Drecording.mockFacilities=true`, update genesis init to write the initialized `accounts` and `blobs` maps to some _genesis-state.json_; and `StandardProcessLogic` to append every consensus `Transaction` to some _well-known-transactions.json_; and `FreezeTransitionLogic` to write the freeze state `accounts`, `blobs`, and `storage` maps to some _final-state.json_.

- [x] :four: As the need arises in the modularized service implementations, write a mock facility  implementation such as `ReplayFeeCalculator` that replays the `FeeCalculator` responses it finds in the _src/test/resources/facility-responses.json_ test asset.

- [x] :five: Use these test assets to and `Replay*` facilities to write a JUnit test that fully exercises the business logic in `smart-contract-service-impl`, `file-service-impl`, and `token-service-impl` for all transactions in _well-known-transactions.json_.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #5883 (in companion with work on the long-lived `replay-develop` branch).

1️⃣ Updates the `Service` interface to have both `registerSchemas()` and `registerMonoAdapterSchemas()` methods.
   - The `registerMonoAdapterSchemas()` method is to be used when running EET's with `workflows.enabled` and a `MerkleHederaState` whose `States` will be used by `mono-service` facility adapters (c.f. [here](https://github.com/hashgraph/hedera-services/blob/05883-merge-relevant-work-from-replay-develop/hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java#L207)).
  - The `registerSchemas()` method is for use when running in a context that **doesn't** depend on any `mono-service` adapter (e.g. in a replay test [here](https://github.com/hashgraph/hedera-services/blob/replay-develop/hedera-node/hedera-app/src/test/java/com/hedera/node/app/integration/infra/InMemoryWritableStoreFactory.java#L55)).

2️⃣ Refactors several `hedera-app` components to reduce their dependence on `mono-service`; and isolates the parts that still do depend on `mono-service`:
  - Eliminates dependence on mono `OptionValidator` in `ExpiryValidator` and `AttributeValidator` implementations.
  - Isolates the deprecated parts of `TransactionDispatcher` in a `MonoTransactionDispatcher` (for example, calling `topicStore.commit()` instead of leaving to be done properly by the workflow). 
  - Isolates the `mono-service` account validation in `MonoExpiryValidator`, separates the rest of expiry validation logic into `StandardizedExpiryValidator`.
  - Makes `WritableStoreFactory` an interface to allow the replay test machinery to provide [its own implementation](https://github.com/hashgraph/hedera-services/blob/replay-develop/hedera-node/hedera-app/src/test/java/com/hedera/node/app/integration/infra/InMemoryWritableStoreFactory.java#L52).
  - Cleans up Dagger2 `@Module`'s a bit to support reuse on `replay-develop`.

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+import javax.inject.Singleton;
+
+/**
+ * A {@link TransactionDispatcher} subclass that supports use of the {@code mono-service} workflow
+ * in end-to-end tests (EETs) that run with {@code workflows.enabled}.
+ *
+ * <p>This mostly means a "premature" call to {@code topicStore.commit()}; but also requires
+ * transferring information from the {@code recordBuilder} to the {@code txnCtx} for transactions
+ * of type {@code topicCreate} and {@code submitMessage}.
+ */
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java:42]: Is this class needed because we still have `handle` workflow not implemented?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+    }
+
+    /**
+     * Current behavior is to only invalidate a simple key structure if it has no explicit type. Other validations,
+     * like on the number of bytes in the public key; or on the size of the threshold key; are done elsewhere.
+     *
+     * @param key the key to validate
+     */
+    private void validateSimple(@NonNull final Key key) {
+        if (key.key().kind() == Key.KeyOneOfType.UNSET) {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java:126]: We should probably check the `isValid` method as added [here](https://github.com/hashgraph/hedera-services/blob/move-to-account-pbj-type/hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyUtils.java#L64)?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+            validateSimple(key);
+        } else if (key.hasThresholdKey()
+                && key.thresholdKeyOrThrow().hasKeys()
+                && key.thresholdKeyOrThrow().keysOrThrow().hasKeys()) {
+            key.thresholdKeyOrThrow().keysOrThrow().keysOrThrow().forEach(k -> validateKeyAtLevel(k, level + 1));
+        } else if (key.keyListOrThrow().hasKeys()) {
+            key.keyListOrThrow().keysOrThrow().forEach(k -> validateKeyAtLevel(k, level + 1));
+        }
+    }
+
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java:118]: Do you think this method can be moved to `KeyUtils` ?

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM , other than few questions. Also need to merge develop back

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java [hunk 4]
```diff
@@ -43,136 +36,24 @@
...
-            accountStore.loadAccountOrFailWith(autoRenewId, PbjConverter.fromPbj(INVALID_AUTORENEW_ACCOUNT));
-        } catch (final InvalidTransactionException e) {
-            throw new HandleException(PbjConverter.toPbj(e.getResponseCode()));
-        }
+        super(
+                id -> {
+                    try {
+                        accountStore.loadAccountOrFailWith(id, PbjConverter.fromPbj(INVALID_AUTORENEW_ACCOUNT));
+                    } catch (final InvalidTransactionException e) {
+                        throw new HandleException(PbjConverter.toPbj(e.getResponseCode()));
```
Comment (hendrikebbers) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java:52]: Why do we not add `e` as cause?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+    public static final int MAX_NESTED_KEY_LEVELS = 15;
+
+    private final long maxEntityLifetime;
+    private final LongSupplier consensusSecondNow;
+    private final GlobalDynamicProperties dynamicProperties;
+
+    @Inject
+    public StandardizedAttributeValidator(
+            @NonNull final LongSupplier consensusSecondNow,
+            @NonNull final @CompositeProps PropertySource properties,
```
Comment (hendrikebbers) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java:55]: Having 1 annotation before final and the other one after `final` makes it harder to read from my point of view

**Review by hendrikebbers — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java:52]: I don't think the stack trace will be relevant for `HandleException`'s anywhere.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java (hunk 5 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java]: Put both first.

**Review by Neeharika-Sompalli — APPROVED** [review]
