### PR TITLE
Fix ScheduleSignHandler signature trim and verification building

### LINKED ISSUE #9869: ScheduleSignHandler doesn't verify signature properly
1. Schedule verification may be off by one failing to add the last item to the signatories (verified)
2. Trim of keys is trimming based on what is not in remaining required, should be total required.

```
currentSignatoriesSetBeforeFilter: []
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]
Key lev Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=1, keys=KeyList[keys=[Key[key=OneOf[kind=ED25519, value=Bytes[49,54,171,228,124,248,36,36,159,228,185,67,122,83,31,66,222,191,188,230,92,85,98,88,193,77,241,219,221,255,157,28]]], Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=2, keys=KeyList[keys=[Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,71,67,242,35,148,173,193,2,237,136,244,168,57,37,54,92,48,9,142,81,139,80,130,101,254,42,100,120,83,158,172,222]]], Key[key=OneOf[kind=ED25519, value=Bytes[225,71,97,185,60,16,8,156,246,191,172,57,132,199,64,73,165,244,214,208,0,239,173,73,78,199,148,102,15,27,74,68]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,68,239,248,194,192,246,156,43,183,242,38,13,87,208,182,46,205,153,127,159,250,216,68,46,107,40,206,105,12,222,157,41]]]]]]]]]]]]]
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[49,54,171,228,124,248,36,36,159,228,185,67,122,83,31,66,222,191,188,230,92,85,98,88,193,77,241,219,221,255,157,28]]]
Key lev Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=2, keys=KeyList[keys=[Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,71,67,242,35,148,173,193,2,237,136,244,168,57,37,54,92,48,9,142,81,139,80,130,101,254,42,100,120,83,158,172,222]]], Key[key=OneOf[kind=ED25519, value=Bytes[225,71,97,185,60,16,8,156,246,191,172,57,132,199,64,73,165,244,214,208,0,239,173,73,78,199,148,102,15,27,74,68]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,68,239,248,194,192,246,156,43,183,242,38,13,87,208,182,46,205,153,127,159,250,216,68,46,107,40,206,105,12,222,157,41]]]]]]]]
Key lev Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,71,67,242,35,148,173,193,2,237,136,244,168,57,37,54,92,48,9,142,81,139,80,130,101,254,42,100,120,83,158,172,222]]]
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[225,71,97,185,60,16,8,156,246,191,172,57,132,199,64,73,165,244,214,208,0,239,173,73,78,199,148,102,15,27,74,68]]]
Key lev Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,68,239,248,194,192,246,156,43,183,242,38,13,87,208,182,46,205,153,127,159,250,216,68,46,107,40,206,105,12,222,157,41]]]
remainingRequiredKeysSet: []
currentSignatoriesSet: [Key[key=OneOf[kind=ED25519, value=Bytes[225,71,97,185,60,16,8,156,246,191,172,57,132,199,64,73,165,244,214,208,0,239,173,73,78,199,148,102,15,27,74,68]]], Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,71,67,242,35,148,173,193,2,237,136,244,168,57,37,54,92,48,9,142,81,139,80,130,101,254,42,100,120,83,158,172,222]]]]
currentSignatoriesSetTrim: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]]
remainingSignatories: []
validSignatories: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]]
2023-11-13 15:55:44.193 INFO  832  MiscUtils - Reset DeterministicThrottle{name='ThroughputLimits', mtps=273000000, capacity=4095000000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.193 INFO  832  MiscUtils - Reset DeterministicThrottle{name='OffHeapQueryLimits', mtps=700000, capacity=700000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.193 INFO  832  MiscUtils - Reset DeterministicThrottle{name='PriorityReservations', mtps=10000, capacity=30000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.193 INFO  832  MiscUtils - Reset DeterministicThrottle{name='CreationLimits', mtps=100000, capacity=1500000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.193 INFO  832  MiscUtils - Reset DeterministicThrottle{name='FreeQueryLimits', mtps=1000000000, capacity=1000000000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.193 INFO  123  NetworkUtilizationManagerImpl - Reset DeterministicThrottle.UsageSnapshot{used=0, last decision @ <N/A>} with saved gas throttle usage snapshot
currentSignatoriesSetBeforeFilter: []
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]
Key lev Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=1, keys=KeyList[keys=[Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]], Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=2, keys=KeyList[keys=[Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]]]]]]]]]]
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]]
Key lev Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=2, keys=KeyList[keys=[Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]]]]]
Key lev Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]]
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]]
Key lev Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]
remainingRequiredKeysSet: [Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]
currentSignatoriesSet: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]]]
currentSignatoriesSetTrim: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]]
remainingSignatories: [Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]
validSignatories: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]]
2023-11-13 15:55:44.737 INFO  832  MiscUtils - Reset DeterministicThrottle{name='ThroughputLimits', mtps=273000000, capacity=4095000000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.737 INFO  832  MiscUtils - Reset DeterministicThrottle{name='OffHeapQueryLimits', mtps=700000, capacity=700000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.737 INFO  832  MiscUtils - Reset DeterministicThrottle{name='PriorityReservations', mtps=10000, capacity=30000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.737 INFO  832  MiscUtils - Reset DeterministicThrottle{name='CreationLimits', mtps=100000, capacity=1500000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.737 INFO  832  MiscUtils - Reset DeterministicThrottle{name='FreeQueryLimits', mtps=1000000000, capacity=1000000000000000000 (used=0)} with saved usage snapshot
2023-11-13 15:55:44.737 INFO  123  NetworkUtilizationManagerImpl - Reset DeterministicThrottle.UsageSnapshot{used=0, last decision @ <N/A>} with saved gas throttle usage snapshot
currentSignatoriesSetBeforeFilter: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]]]
Key lev Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=1, keys=KeyList[keys=[Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]], Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=2, keys=KeyList[keys=[Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]]]]]]]]]]
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]]
Key lev Key[key=OneOf[kind=THRESHOLD_KEY, value=ThresholdKey[threshold=2, keys=KeyList[keys=[Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]]]]]
Key lev Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]]
Key lev Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]]
Key lev Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]
remainingRequiredKeysSet: [Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]]]
currentSignatoriesSet: [Key[key=OneOf[kind=ED25519, value=Bytes[10,168,226,16,100,198,30,171,134,226,169,193,100,86,91,78,122,154,65,70,16,110,10,108,208,58,140,57,90,17,14,146]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,15,64,234,205,49,48,230,13,91,169,234,205,52,167,206,186,160,62,47,12,165,53,229,158,182,50,242,246,206,154,102,125]]]]
currentSignatoriesSetTrim: []
remainingSignatories: [Key[key=OneOf[kind=ED25519, value=Bytes[231,251,116,78,212,118,226,120,37,225,232,122,39,244,174,235,12,22,147,54,40,46,213,224,27,26,200,157,69,21,33,33]]], Key[key=OneOf[kind=ED25519, value=Bytes[235,94,203,191,181,255,78,147,234,160,191,108,145,110,202,117,214,182,62,24,12,92,134,40,20,61,95,225,208,100,232,89]]], Key[key=OneOf[kind=ECDSA_SECP256K1, value=Bytes[2,35,226,75,5,77,101,194,102,86,118,47,247,3,123,113,159,73,7,13,146,114,227,220,110,151,168,127,33,41,76,19,121]]]]
validSignatories: []
```

### PR DESCRIPTION
**Pull request by jsync-swirlds**
* Fixed some general signature verification and record building issues previously identified
* Changed the trim to walk the key structure for required keys, rather than attempting a direct match (which will often fail incorrectly) in trim
* Added check in SignHandler to throw exception if a ScheduleSign transaction does not result in a change to signatories, or execution.
* Enabled 17 HapiTest specs in ScheduleSignSpecs.

Fixes #9869

### CODE REVIEW

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM!

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java [hunk 1]
```diff
@@ -259,13 +260,16 @@ static TransactionID transactionIdForScheduled(@NonNull Schedule valueInState) {
         // original create transaction and its transaction ID will never be null, but Sonar...
         final TransactionBody originalTransaction = valueInState.originalCreateTransactionOrThrow();
         final TransactionID parentTransactionId = originalTransaction.transactionIDOrThrow();
-        // payer on parent transaction ID will also never be null...
-        final AccountID payerAccount = valueInState.payerAccountIdOrElse(parentTransactionId.accountIDOrThrow());
-        // Scheduled transaction ID is the same as its parent except
-        //     if scheduled is set true, payer *might* be modified, and the nonce is incremented.
-        final TransactionID.Builder builder = TransactionID.newBuilder().accountID(payerAccount);
-        builder.transactionValidStart(parentTransactionId.transactionValidStart());
-        builder.scheduled(true).nonce(parentTransactionId.nonce() + 1);
```
Comment (iwsimon) [inline hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java:268]: nouce setting is removed here. Don't you need that for parent/child transaction?

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java [hunk 2]
```diff
@@ -142,17 +142,15 @@ public void handle(@NonNull final HandleContext context) throws HandleException
...
-                if (scheduleStore.numSchedulesInState() + 1 > schedulingConfig.maxNumber()) {
+                if (scheduleStore.numSchedulesInState() + 1 > schedulingConfig.maxNumber())
                     throw new HandleException(ResponseCodeEnum.MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED);
-                }
                 // Need to process the child transaction again, to get the *primitive* keys possibly required
                 final ScheduleKeysResult requiredKeysResult = allKeysForTransaction(provisionalSchedule, context);
                 final Set<Key> allRequiredKeys = requiredKeysResult.remainingRequiredKeys();
                 final Set<Key> updatedSignatories = requiredKeysResult.updatedSignatories();
-                final long nextId = getNextId(context);
+                final long nextId = context.newEntityNum();
```
Comment (iwsimon) [inline hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java:153]: context.newEntityNum() doesn't do config.numReservedSystemEntities() check as in getNextId(). Should we check?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java [hunk 3]
```diff
@@ -691,27 +724,29 @@ public HapiSpec overlappingKeysTreatedAsExpected() {
                         getAccountBalance(ADDRESS_BOOK_CONTROL).hasTinyBars(changeFromSnapshot("before", +2)));
     }
 
+    @HapiTest
     public HapiSpec retestsActivationOnSignWithEmptySigMap() {
         return defaultHapiSpec("RetestsActivationOnCreateWithEmptySigMap")
                 .given(newKeyNamed("a"), newKeyNamed("b"), newKeyListNamed("ab", List.of("a", "b")), newKeyNamed(ADMIN))
                 .when(
-                        cryptoCreate(SENDER).key("ab").balance(667L),
+                        cryptoCreate(SENDER).key("ab").balance(665L),
```
Comment (iwsimon) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java:732]: Those numbers should not be changed.

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java [hunk 4]
```diff
@@ -280,4 +284,35 @@ private static long calculateExpiration(
...
         }
     }
+
+    static void filterSignatoriesToRequired(Set<Key> signatories, Set<Key> required) {
+        final Set<Key> incomingSignatories = Set.copyOf(signatories);
+        signatories.clear();
+        filterSignatoriesToRequired(signatories, required, incomingSignatories);
+    }
+
+    private static void filterSignatoriesToRequired(
```
Comment (iwsimon) [inline hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java:294]: It would be good to add javadoc for each @param.

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java (hunk 2 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java:153]: no, that method was temporary to work around a test issue that's no longer relevant.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java (hunk 3 above)
Comment (jsync-swirlds) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java:728]: They're just random-ish values; they aren't significant...

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java (hunk 1 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java:268]: No.  Workflow sets those values and mostly ignores what I set here.
This Transaction ID needs to be _exactly_ the same as the original Create transaction except for the "scheduled" flag (many tests depend on that exact match).

File: hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java (hunk 4 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/HandlerUtility.java:294]: We generally don't javadoc private methods.
Is it needed for this to be understandable?  I can add it, but it likely won't say much more than the parameter name does...

**Review by iwsimon — APPROVED** [review]
LGTM
