### PR TITLE
Fix action sidecars missing expected fields

### LINKED ISSUE #5169: Contract action sidecars can be missing expected fields (in the protobuf) that are expected to be present
### Description

Uncovered in previewnet, certain failed contract executions are missing required (semantically required, obviously not _protobuf_ required) fields.

Happens when a top-level contract call calls out to a contract which ends in a revert (or other failure?).  Missing fields include `result_data`, `gas_used`, and perhaps others.

Result is that these sidecars can't get imported into the mirror node (reported as "parsing error") which then breaks the mirror node importing flow.

### Steps to reproduce

Working on a reproduction.  Reported by customer but can't yet provide an in-house failure case.

### Additional context

TBS when we have an in-house failure case.

### Hedera network

previewnet

### Version

v0.36.0-alpha.1

### Operating system

None

### PR DESCRIPTION
**Pull request by david-bakin-sl**
**Description**:

**_Why_**

Finalization of the contracts actions (as part of the flow of producing `CONTRACT_ACTION` sidecars) was not performed when the frame state == `COMPLETED_FAILURE`. The state diagram in `org.hyperledger.besu.evm.frame.MessageFrame` shows you can't get to `COMPLETED_FAILURE` without going through `EXCEPTIONAL_HALT` - which _was_ being handled. But there we are.

(You can see the BESU state diagram [here](https://github.com/hyperledger/besu/blob/d48403d1852e270b2c58cc867885f448b04e1518/evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java#L86). It clearly shows you only get to `COMPLETED_FAILURE` by going first to `EXCEPTIONAL_HALT`.  But it shows the same for getting to `COMPLETED_SUCCESS` only after `CODE_SUCCESS` while our _existing_ code [here](https://github.com/hashgraph/hedera-services/blob/1c9e74a9fd1e9892771e53c39c14ce1e05ddaef8/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java#L136) clearly _does_ test both those alternatives ...)

**_What_**

* Add `COMPLETED_FAILED` state to be the same as s`EXCEPTIONAL_HALT` in `finalizeActionFor()`
   * to handle the case where you can get there _without_ going through `EXCEPTIONAL_HALT` first (contrary to documentation)
   * and changed an if-ladder to a switch so `javac` will tell us if there are any states not handled at all
* Ensure that all action sidecars have correct semantics (i.e., the correct fields supplied, and _all_ of the necessary fields supplied) by construction, and
* Validate that all action sidecars have correct semantics:
  * Add `invalidActions` list in `HederaTracer` to capture actions that failed validation
     * Each action is validated when created or updated 
  * Add `HederaEvmOperationTracer.finalizeOperation(messageFrame initialFrame)` to log all validation failures after all actions for this transaction have been saved in the tracer
  * All this validation work is gated by new dynamic property `contracts.sidecarValidationEnabled` (default is **not enabled**)
    * Pass that property through the `HederaTracer` constructor
    * And since that constructor would otherwise now take two separate boolean flags (and be confusing), updated the signature to take (self-describing) enum values `HederaTracer.EmitActionSidecars` and `HederaTracer.ValidateActionSidecars`

**_Results_**

1. We handle `EXCEPTIONAL_HALT` which is we believe is the state that broke things
1. We now have improved logging to give us an idea of the state in case that occurs or any other state
1. We don't create any actions for states not called out in the switch - and ensure that the switch is complete
1. We have a validation flow to give us coverage of checking action details, notable the oneofs
1. We've got new units tests to confirm that invalid action sidecars are detected and logged

**Related issue(s)**:

Fixes #5169 

**Notes for reviewer**:

Validation is enabled by a new feature flag.  Adding a new feature flag touches a surprising number of files even before you actually _use_ it.

The question of what level to log validation at (if enabled) (and whether it should have a throttle if logged at INFO or higher) is TBD and tracked in #5514 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 1]
```diff
@@ -133,9 +166,93 @@ private void trackNewAction(final MessageFrame messageFrame, final Consumer<Soli
     }
 
     private void finalizeActionFor(final SolidityAction action, final MessageFrame frame, final State frameState) {
+
+        switch (frameState) {
+            case NOT_STARTED, CODE_EXECUTING, CODE_SUSPENDED:
+                {
+                    // these states are not "final" states needing to finalize the actions
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:173]: Good luck testing this.  It's not worth putting in an induced failure, I'm OK with these being expected as non-reachable and hence untested.  With this line in place it will at least put the idea in people heads if they are debugging this is what could be wrong.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 2]
```diff
@@ -133,9 +166,93 @@ private void trackNewAction(final MessageFrame messageFrame, final Consumer<Soli
     }
 
     private void finalizeActionFor(final SolidityAction action, final MessageFrame frame, final State frameState) {
+
+        switch (frameState) {
+            case NOT_STARTED, CODE_EXECUTING, CODE_SUSPENDED:
+                {
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:172]: This "extra-bracing" style appears to be out of style, but I cannot find any code style statements permitting or denying it.  Closest is https://google.github.io/styleguide/javaguide.html#s4.8.4-switch which shows a non-braced statement.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 3]
```diff
@@ -133,9 +166,93 @@ private void trackNewAction(final MessageFrame messageFrame, final Consumer<Soli
...
+                    }
+                    if (frame.getType().equals(CONTRACT_CREATION)) {
+                        action.setRecipientContract(null);
+                    }
+                }
+                break;
+        }
+    }
+
+    private void finalizeActionFor2(
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:250]: Is this dead code?  Please remove if so.  It should improve the side-by-side diff.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 4]
```diff
@@ -248,4 +368,46 @@ private Address asMirrorAddress(final Address addressOrAlias, final MessageFrame
...
         return aliases.resolveForEvm(addressOrAlias);
     }
+
+    private Optional<SolidityAction> popActionStack(final MessageFrame frame) {
+        if (!currentActionsStack.isEmpty()) {
+            return Optional.of(currentActionsStack.pop());
+        } else {
+            log.atDebug().log(
+                    "HederaTracer action stack prematurely empty ({})", () -> formatFrameContextForLog(frame));
+            return Optional.empty();
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:378]: This appears to indicate things are very broken (is it even impossible to inducde in tests?), so a log at debug seems too low.  I wounder if the stack trace from poping an empty stack would be more usefule for devops, because it would result in a TX level exception that will receive scary logs.  I know sonar is bugging you about the exeption but I think we want it, or at least log it at error with a stack trace.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 5]
```diff
@@ -73,6 +83,27 @@ public void init(final MessageFrame initialFrame) {
...
+    public void finalizeOperation(final MessageFrame initialFrame) {
+        if (areActionSidecarsEnabled) {
+            // make sure only valid actions are left in allActions
+            final var validActions =
+                    allActions.stream().filter(SolidityAction::isValid).toList();
+
+            if (!currentActionsStack.isEmpty() || validActions.size() != allActions.size()) {
+                log.atDebug().log(
+                        "HederaTracer invalid at end of EVM run: {} ({})",
+                        () -> formatAnomaliesAtFinalizationForLog(validActions),
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:96]: Should anomalies be at debug?  This to me indicates we got the logic wrong in potentially unsafe ways.  I expect they should never happen, so an anomoly should be logged at least at info.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java [hunk 6]
```diff
@@ -32,7 +34,7 @@ public class SolidityAction {
     private EntityId recipientContract;
     private byte[] invalidSolidityAddress;
     private final long value;
-    private long gasUsed;
+    private Long gasUsed;
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java:37]: Why box?  Could we use a sentinel value of MIN_VALUE or -1 instead? Negative gas is _always_ invalid.

**Review by Nana-EC — COMMENTED** [review]
LG on 1st pass.
Single comment request. Will circle back today

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 1 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:176]: Yes, it is mainly for readers.  And for `javac` pointing out missing cases (enum values not handled).  Which was what the problem initially was: no handling for the `COMPLETED_FAILED` condition.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:175]: Are you suggesting I'm not fashionable? Hmm. Actually, I'm less interested in what other random committees writing style guides think than I am in my own opinion of what is readable and what is not.  I happen to think it is more readable to have these blocks - with their very divergent handling of the cases - really separated in the reader's mind.

But of course I'll go with prevailing (Swirlds Labs) standards.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 4 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:320]: I wondered about that level myself, but thought that this followed the recent logging policy announcement.  Those guidelines say not to log anything at `info` or above that is going to possibly spew, possibly for a lot of transactions.  And I suppose that is possible here: some app, being tested, may trigger this over and over.  (Another solution would be a higher level + a throttle.  I'll look into that.)

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java (hunk 6 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java:40]: Ok. My sense of style and readability (alluded to above) makes me want to have _all_ of these similar tests for "not set" be similar, and all but this one are nullable and tested that way.  So I wanted this one nullable too.

I don't believe it's too expensive.  One boxed value per action record.  I don't yet have a good sense of the memory pressure we're under.  Is that too much?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 7]
```diff
@@ -68,11 +77,56 @@ public HederaTracer(final boolean areActionSidecarsEnabled) {
...
     }
 
+    @Override
+    public void finalizeOperation(final MessageFrame initialFrame) {
+        if (areActionSidecarsEnabled) {
+            // make sure only valid actions are left in allActions
+            final var validActions =
+                    allActions.stream().filter(SolidityAction::isValid).toList();
+
+            if (!currentActionsStack.isEmpty() || validActions.size() != allActions.size()) {
```
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:95]: There's a state machine here that runs through these states.  Unfortunately, it is not actually "here".  It's over somewhere in the EVM machinery and all we have here are these callbacks for certain transitions - and it isn't even clear at this point what happens in what order, or what could interrupt the state machine's progress over there in the EVM machinery.  At least as far as I can see.  (Because: nothing's documented that I can point to.)

So I don't _expect_ there's anything wrong at all.  But I can't show that by pointing to a state diagram and mapping things out.  And if there's a `pop` and there's nothing to be popped - that's a hard error (throws an exception).  As long as I'm making things safe for field values (by validation and tossing records that don't work) I thought I'd check for this too.  And log in both cases.

I will add a comment as suggested once I figure out how to word it.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 4 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:320]: (w.r.t. include in tests: it is of course testable in _unit_ tests and I _do_ test it there.  I don't think I can drive it to this state in the integration tests though.  At least, I hope not.)

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 5 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: let's talk offline about these logs - I may have misunderstood the latest instructions

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 3 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: oops, forgot, thanks

**Review by dimitar-dinev — COMMENTED** [review]
Overall LGTM. What's most important is that we need to clear up whether we are going to be setting the `targetedAddress` on failed `CREATE`s. Logging level seems too low for me as well, IMO it should be @`WARN`.

I'm slightly concerned about all of the action validation we will be performing **on each EVM execution**, looks like overkill to me. However (apparently) we can't completely trust the underlying message frame transitions, so maybe it's warranted, and we need to be paranoid.  

If we are doing such validations for actions, though, shouldn't we also do them for state changes and bytecodes as well? Invalid sidecars of those types could also potentially break the mirror node. I'm also not sure whether the mirror node should actually completely break upon receiving an invalid sidecar, it's not as essential as the main record  (for which we also do not have such validations before exporting it) --- couldn't the mirror node log @ warn the invalid sidecar, discard it, and continue operating?

**Comment by david-bakin-sl** [comment]
> I'm slightly concerned about all of the action validation we will be performing **on each EVM execution**, looks like overkill to me.

Yes.  I think I'll put it behind a feature flag so we can have it for dev/test environments but not in production.

**Comment by Nana-EC** [comment]
> If we are doing such validations for actions, though, shouldn't we also do them for state changes and bytecodes as well? Invalid sidecars of those types could also potentially break the mirror node. I'm also not sure whether the mirror node should actually completely break upon receiving an invalid sidecar, it's not as essential as the main record (for which we also do not have such validations before exporting it) --- couldn't the mirror node log @ warn the invalid sidecar, discard it, and continue operating?

This will require further coordination.
For now we should only send actions in paths we're confident about.
Looks like we hit an unknown path and therefore created an action we weren't fully comfortable with.
Mirror Node is also planning to add future logic to not halt on a single side car failure, though it'll be interesting to see how it decides to circle back on it.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java [hunk 8]
```diff
@@ -52,6 +57,52 @@ public SolidityAction(
...
+     * Check that the fields are set correctly for the semantics of the underlying protobuf
+     *
+     * (Respecting, for example, protobuf `oneof` unions...)
+     */
+    public boolean isValid() {
+        boolean ok = true;
+        ok &= null != getCallType() && ContractActionType.NO_ACTION != getCallType();
+        ok &= 1 == countNonNulls(getCallingAccount(), getCallingContract());
+        ok &= null != getInput();
+        ok &= 1 == countNonNulls(getRecipientAccount(), getRecipientContract(), getInvalidSolidityAddress());
```
Comment (Nana-EC) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java:70]: Would now have to remove this case for recipients

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 2 above)
Comment (shemnon) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:180]: "out of style" being the decreed Swirlds code style, which uses Google's as a default. I'm only arguing for consistency.  I honestly think "blocks" is a java language feature most don't know about.  The typical value added (creating variable scope and reducing name collisions) is not commonly needed.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java [hunk 9]
```diff
@@ -4330,6 +4330,8 @@ private HapiSpec traceabilityE2EScenario17() {
                                                 .setGas(931868)
                                                 .setCallDepth(1)
                                                 .setGasUsed(201)
+                                                // TODO: need to setTargetedAddress here, but with what???
+                                                // (also scenarios 18 and 20)
```
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java]: as per off-chain discussion, targetedAddress no longer being set.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 10]
```diff
@@ -73,6 +85,34 @@ public void init(final MessageFrame initialFrame) {
         }
     }
 
+    @Override
+    public void finalizeOperation(final MessageFrame initialFrame) {
+        if (areActionSidecarsEnabled) {
+            // make sure only valid actions are left in allActions
+            final var validActions =
+                    allActions.stream().filter(SolidityAction::isValid).toList();
+
```
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: not only that, but it's just cleaner that way, it turns out.  done.

[the remark this answers is not in the document]
Comment (dimitar-dinev) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: Hmm, the action is not in its final state after `trackNewAction`,  though --- `finalizeActionFor` alters the action again. We should do the validation after action is finalized

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java [hunk 11]
```diff
@@ -131,8 +133,13 @@ protected TransactionProcessingResult execute(
...
         // static call
-        final HederaTracer hederaTracer =
-                new HederaTracer(!isStatic && isSideCarTypeEnabled(SidecarType.CONTRACT_ACTION));
+        final HederaTracer.EmitActionSidecars doEmitActionSidecars =
+                !isStatic && isSideCarTypeEnabled(SidecarType.CONTRACT_ACTION)
+                        ? EmitActionSidecars.ENABLED
+                        : EmitActionSidecars.DISABLED;
+        final HederaTracer.ValidateActionSidecars doValidateActionSidecars =
+                isSidecarValidationEnabled() ? ValidateActionSidecars.ENABLED : ValidateActionSidecars.DISABLED;
+        final HederaTracer hederaTracer = new HederaTracer(doEmitActionSidecars, doValidateActionSidecars);
```
Comment (dimitar-dinev) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java:142]: Much more readable with the `enum`s IMO 👍🏽

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java (hunk 6 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java]: huh.  ok, well replaced now with a long and IDC if it is invalid because missing => 0 turns out to be ok.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java (hunk 11 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java:142]: Funny thing about sonar: Some things that (I consider) to be NOT code smells are marked as code smells, and some things that (I consider) TO BE code smells (like this was) are NOT marked that way.  If only I was in charge!

(IMO, even with IDE help to prompt with parameter names, boolean parameters are not that good, and if you have more than one on a method: that's to be avoided.  And Java/C#/C++ allow nice tightly scoped enums - C++ was the holdout but added `enum class` 10+ years ago ...)

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java (hunk 8 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java]: done

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:199]: yes and sonar complains about blocks in some cases where they're nicely used to group statements that are logically very tightly connected but aren't strictly required.  but in this case it does _not_ complain.  and, as you pointed out, the google style guide says nothing about blocks used to group statements only (it only talks about blocks and "block-like constructs" in terms of indentation and such.  so ... what do you think?  ["whatever is not prohibited is allowed"](https://en.wikipedia.org/wiki/Everything_which_is_not_forbidden_is_allowed) - or vice versa?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: good catch! will fix - still one-at-a-time though.

[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: fixed!

File: hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java [hunk 12]
```diff
@@ -168,6 +168,8 @@ public HederaEvmTransactionProcessingResult execute(
         this.gasUsed = calculateGasUsedByTX(gasLimit, initialFrame);
         this.sbhRefund = updater.getSbhRefund();
 
+        tracer.finalizeOperation(initialFrame);
+
```
Comment (dimitar-dinev) [inline hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java:172]: Actually, we should have this called in `EvmTxProcessor`, since the `process` call at line 165 may throw a `ResourceLimitException` exception, which is [caught in EvmTxProcessor](https://github.com/hashgraph/hedera-services/blob/cdcfb8885cef3dc43d3a919b2ef120807ae400ee/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java#L138-L140).
If thrown, this call here will be skipped.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (dimitar-dinev) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: Can't see an obvious reason why we wouldn't be able to add to the list only after the finalization in `finalizeActionFor()`, sounds more prudent as well.

[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: the one that does this is the "synthetic" one, right? what seems weird to me is that that's where that is done at all (but I didn't want to change that). 

but wait ... i thought you earlier suggested to _not_ validate in one place but instead to validate one-at-a-time as actions were created/updated (to avoid a list traversal)?

(w.r.t. removing invalid actions from all actions: though all actions might get large certainly we don't believe that invalid actions will be? though I do get that remove from an arraylist is `O(nm)` ...)

**Review by Nana-EC — APPROVED** [review]

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 2 above)
Comment (shemnon) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:196]: It will diff better if removed and is not strictly necessary.  The switch labels already nicely group it.  I'm of the opinion that it reduces readability and because it's a non-standard pattern it will distract readers on the style instead of focusing on the code.  I'm not aware of any other place in hedera code that uses free blocks.  While not strictly prohibited the code would be better if it was removed.  But this issue alone will not block the PR.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 4 above)
Comment (shemnon) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:347]: Log level should be warn.  If it spews it is horribly broken and needs to be turned off.  Based on the construction of the tracer the number of logs should be zero if we have the logic correct.  So normal operation is zero logs, and it is a recoverable error, hence warn not error.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 13]
```diff
@@ -60,29 +78,68 @@ public class HederaTracer implements HederaOperationTracer {
...
+    public void finalizeOperation(final MessageFrame initialFrame) {
+        if (areActionSidecarsEnabled() && isActionSidecarValidationEnabled()) {
+            // Two possible error conditions are that invalid actions (mainly `oneof` fields that
+            // don't have _exactly_ one alternative set) are added to the set of actions (which can
+            // cause problems when ingesting sidecar records elsewhere) and that the current actions
+            // stack is out-of-sync (due to some error elsewhere).  (The latter condition has not yet
+            // been observed outside deliberate fault injection and probably doesn't happen in a
+            // running system.)
+            if (!currentActionsStack.isEmpty() || !invalidActions.isEmpty()) {
+                log.atLevel(logLevel)
```
Comment (shemnon) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:117]: Log level is debug by default, this is too low.  Should be warn.  If we are executing this code either (a) we have the actions code wrong and need to fix it or (b) something else has gone horribly wrong in the EVM for the stack to be out of sync, and warrants disabling the feature at runtime.  Defense in depth is great, but we should be aiming to get the code executing this block never because we have the action code right.  so the code can stay, but we need to acknowledge this is not an ignorable error.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java]: > the one that does this is the "synthetic" one, right? what seems weird to me is that that's where that is done at all (but I didn't want to change that).

Correct.

> but wait ... i thought you earlier suggested to _not_ validate in one place but instead to validate one-at-a-time as actions were created/updated (to avoid a list traversal)?

I'm saying having all the add and validation operations done one at a time in one function. For later though if it makes sense with the ordering comment


> (w.r.t. removing invalid actions from all actions: though all actions might get large certainly we don't believe that invalid actions will be? though I do get that remove from an arraylist is `O(nm)` ...)

Exactly

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java [hunk 14]
```diff
@@ -52,6 +57,53 @@ public SolidityAction(
         this.callDepth = callDepth;
     }
 
+    /**
+     * Check that the fields are set correctly for the semantics of the underlying protobuf
+     *
+     * Respecting, for example, protobuf `oneof` unions... (but allowing for `oneof recipient` to be missing
+     * entirely, because that's ok)
+     */
+    public boolean isValid() {
```
Comment (tinker-michaelj) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java:66]: Would it not be simpler to convert to a gRPC object and check the resulting object via `has*()` methods?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java [hunk 15]
```diff
@@ -133,83 +190,96 @@ private void trackNewAction(final MessageFrame messageFrame, final Consumer<Soli
...
+                        syntheticInvalidAction.setTargetedAddress(
+                                Words.toAddress(frame.getStackItem(1)).toArray());
+                        syntheticInvalidAction.setError(
+                                INVALID_SOLIDITY_ADDRESS.name().getBytes(StandardCharsets.UTF_8));
+                        syntheticInvalidAction.setCallOperationType(
+                                toCallOperationType(frame.getCurrentOperation().getOpcode()));
+                        allActions.add(syntheticInvalidAction);
+                    }
+                } else {
+                    action.setError(new byte[0]);
```
Comment (tinker-michaelj) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java:253]: Do we have any compact summary of when an exceptional halt will fail to set an error?

**Review by tinker-michaelj — DISMISSED** [review]
LGTM, tyvm @david-bakin-sl!
