### PR TITLE
fix: resolve stream validation to scan all subdirs

### LINKED ISSUE #23858: Test flake: StreamValidationTest > streamsAreValid()
```
> Task :test-clients:testSubprocess

  com.hedera.services.bdd.suites.validation.StreamValidationTest > streamsAreValid() ✘ as written (18.5s)

    java.lang.AssertionError: Block stream validation failed:
      - Field blockFooter is null
      - Block must end with a block proof
```

https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/22391134658/job/64814349644?pr=23831
https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/22661288469/job/65682427536?pr=23927

Find the root cause and fix the issue.

### PR DESCRIPTION
**Pull request by AlexKehayov**
**Description**:
StreamValidationOp.readMaybeBlockStreamsFor() called node.getExternalPath(BLOCK_STREAMS_DIR) which resolves to a single block-X.Y.Z subdirectory based on the node's current account ID (e.g., data/blockStreams/block-0.0.3). In tests that rotate nodes in/out (like hapiTestRestart), a node's account ID changes over time, creating multiple block-* directories under the same blockStreams/ parent:

  ```
blockStreams/
    block-11.12.5/     → blocks [0, 228]
    block-11.12.905/   → blocks [229, 462]
    block-11.12.2055/  → blocks [463, 510]
    block-11.12.2056/  → blocks [511, 682]
```
Reading from just one subdirectory returned an incomplete block set. The validator then reported null block footers and missing block proofs - even though all blocks existed on disk with valid, parseable footers. The same issue affected validateProofs() for marker file discovery.

Fix:
In StreamValidationOp.java, resolve each node's block stream path to its parent blockStreams/ directory instead of the specific block-X.Y.Z subdirectory. Since BlockStreamAccess.readBlocks() uses Files.walk(), it naturally discovers all .blk files across all subdirectories.
- readMaybeBlockStreamsFor() - extracted readBlocksFromNodeBlockPaths() which applies .getParent() to each node path, deduplicates, then reads blocks
- validateProofs() - same .getParent() fix for marker file discovery
- Regression test - StreamValidationOpTest - two tests that create blocks spread across multiple block-X.Y.Z subdirectories and verify readBlocksFromNodeBlockPaths finds all of them. Confirmed these fail without the .getParent() fix and pass with it.

Fixes #23858

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java [hunk 1]
```diff
@@ -239,8 +253,11 @@ private static void validateProofs(@NonNull final HapiSpec spec) {
         log.info("Beginning block proof validation for each node in the network");
         spec.getNetworkNodes().forEach(node -> {
             try {
-                // Get all marker file numbers
-                final var path = node.getExternalPath(BLOCK_STREAMS_DIR).toAbsolutePath();
+                // Use the parent blockStreams directory to find marker files across all
+                // account ID subdirectories (a node may have multiple block-X.Y.Z dirs
+                // if its account ID changed during the test)
+                final var path =
+                        node.getExternalPath(BLOCK_STREAMS_DIR).getParent().toAbsolutePath();
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java]: I suspect there are more places we'll need to make a similar adjustment, e.g. [here](https://github.com/hiero-ledger/hiero-consensus-node/blob/70914949a35c77400346b4f7cbb3029811856982/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/AbstractNode.java#L99-L99). We may want an entirely new enum value like `BLOCK_STREAMS_PARENT_DIR` instead; having multiple blocks directories available on a single node violates what was previously an invariant for this API

Comment (AlexKehayov) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/StreamValidationOp.java]: @mhess-swl The changes are applied. Thanks.
