### PR TITLE
Fix HCS-Restart-Performance-Testnet-10k-46m

### LINKED ISSUE #1008: HCS-Restart-Performance-Testnet-10k-46m fails on master
**Summary of the defect**
HCS-Restart-Performance-Testnet-10k-46m fails on master with 0 TPS . Investigate the reason for it and fix the issue.

**How to reproduce (if possible)**
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1611476677006700
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1611562896008600

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
**Related issue(s)**:
Closes #1008 

**Summary of the change**:
Allow to use single payer which is the sender while testing with public testnet state

Passed test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1611699444050000

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java [hunk 1]
```diff
@@ -176,7 +188,8 @@ private static HapiApiSpec runSubmitMessages() {
 					randomUtf8Bytes( msgSize - 8)))
 				.noLogging()
 				.payingWith(senderId)
-				.signedBy(GENESIS, GENESIS)
+				.signedBy(senderKey, submitKey)
+				//.signedBy(GENESIS, GENESIS)
```
Comment (ljianghedera) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java:192]: This line can be removed.

**Review by ljianghedera — DISMISSED** [review]
Looks good overall.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java [hunk 2]
```diff
@@ -163,10 +162,23 @@ private static HapiApiSpec runSubmitMessages() {
 				:  settings.getIntProperty("messageSize", messageSize)
 				        - r.nextInt(settings.getHcsSubmitMessageSizeVar());
 
-		// maybe use some more realistic distributions to simulate real world scenarios
-		String senderId = String.format("0.0.%d", TEST_ACCOUNT_STARTS_FROM + r.nextInt(settings.getTotalAccounts()));
-		String topicId  = String.format("0.0.%d", TEST_ACCOUNT_STARTS_FROM + settings.getTotalAccounts()
-				+ r.nextInt(settings.getTotalTopics() ));
+		String senderId = "sender";
+		String topicId = "topic";
+		String senderKey= "sender";
```
Comment (anighanta) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java:167]: Are these keys already added to the key Map? How would a test client know which key to pick when you use it below in line 191 ?

LGTM otherwise.

Comment (ljianghedera) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java:167]: These keys are created just before the LoadTest run, so they are already in the key map.

File: test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply test-clients/src/main/java/com/hedera/services/bdd/suites/perf/SubmitMessageLoadTest.java]: Fixed. Thanks Leo!

**Review by anighanta — APPROVED** [review]

**Review by ljianghedera — APPROVED** [review]
LGTM.
