### PR TITLE
fix: Include gRPC cert hash in synthetic `Node{Create,Update}`

### LINKED ISSUE #20286: When `*-network.json` includes gRPC cert hashes, should be used in synthetic `NodeTx`
Although [here](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hapi/hedera-protobuf-java-api/src/main/proto/services/state/addressbook/node.proto#L103) a _genesis-network.json_ can specify gRPC cert hashes, we are not including this in the synthetic `NodeCreate` dispatched at genesis [here](https://github.com/hiero-ledger/hiero-consensus-node/blob/main/hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SystemTransactions.java#L313).

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #20286

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java [hunk 1]
```diff
@@ -519,6 +520,17 @@ public RepeatableEmbeddedHedera repeatableEmbeddedHederaOrThrow() {
...
 
+    /**
+     * Returns the {@link SubProcessNetwork} if the target network is of that type, or throws.
+     * @return the target subprocess network
+     */
+    public SubProcessNetwork subProcessNetworkOrThrow() {
+        if (!(targetNetworkOrThrow() instanceof SubProcessNetwork network)) {
+            throw new IllegalStateException("Target network is not subprocess");
+        }
+        return network;
```
Comment (timfn-hg) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java:531]: TIL! I figured the scope of the pattern variable - `network` - would be limited to within the if block. In hindsight it makes sense, but I never connected those dots until now. Neat!

**Review by anthony-swirldslabs — APPROVED** [review]
* platform-sdk/swirlds-state-api/src/main/java/com/swirlds/state/lifecycle/info/NodeInfo.java

LGTM. Thanks!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java:531]: Yes I'm curious how many goodies are in Java 25...

**Review by anthony-swirldslabs — APPROVED** [review]
