### PR TITLE
Fix More Txn Receipt Tests

### LINKED ISSUE #9534: TxnReceiptRegression
- [x] ~~receiptUnavailableAfterCacheTtl~~ – Won't fix; not passing in mono code either
- [x] returnsNotSupportedForMissingOp
- [x] receiptUnavailableIfRejectedInPrecheck

### PR DESCRIPTION
**Pull request by mhess-swl**
Closes #9534 

#### Notes For Reviewer
* The changes to `QueryWorkflowImpl` aren't as extensive as the git diff makes them look. Some braces had to shift a little bit, and there's a tiny bit of re-ordering. It may be helpful to do a side-by-side diff _with "Hide whitespace" enabled_ for this file instead of the unified diff (my default). 
* The `receiptUnavailableIfRejectedInPrecheck` test is slightly modified so that it doesn't submit a transaction with `DEFAULT_PAYER`, which was causing an invalid signature error in both the modular _and_ the mono code.

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java [hunk 1]
```diff
@@ -105,13 +106,14 @@ private HapiSpec receiptAvailableWithinCacheTtl() {
...
+    @HapiTest
     private HapiSpec receiptUnavailableIfRejectedInPrecheck() {
         return defaultHapiSpec("ReceiptUnavailableIfRejectedInPrecheck")
-                .given(usableTxnIdNamed("failingTxn"), cryptoCreate("misc").balance(1_000L))
+                .given(cryptoCreate("misc").balance(1_000L))
                 .when(cryptoCreate("nope")
                         .payingWith("misc")
                         .hasPrecheck(INSUFFICIENT_PAYER_BALANCE)
-                        .txnId("failingTxn"))
+                        .via("failingTxn"))
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java:116]: See PR notes for why this test was modified

**Review by jsync-swirlds — APPROVED** [review]

**Review by jsync-swirlds — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM, thanks @mhess-swl !
