### PR TITLE
Fix deserialization for 0.24.x versions

### LINKED ISSUE #3185: Deserialization for 0.24.X versions to 0.25 (master) version fails
### Description

ExpirableTxnRecord with versions `0.23.0` and `0.24.0` serialized 3 empty allowance maps sizes. But those maps are removed from `0.25.0` in the TxnRecord. So for the versions` >=23.0 and < 0.25.0` while deserializing we need to read 3 Integers.

### Steps to reproduce

Create a state from `0.24.2` and try to load to `master`

### Additional context

_No response_

### Hedera network

other

### Version

master

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Signed-off-by: Neeharika-Sompalli [neeharika.sompalli@hedera.com](mailto:neeharika.sompalli@hedera.com)

Closes #3185 

- `ExpirableTxnRecord` with versions 0.23.0 and 0.24.0 serialized 3 empty allowance maps sizes. 
- But those maps are removed from 0.25.0 in the TxnRecord
- So for the versions **>=23.0** and **< 0.25.0** while deserializing we need to read 3 Integers.

### CODE REVIEW

**Review by tinker-michaelj — DISMISSED** [review]
LGTM

File: hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordSerdeTest.java [hunk 1]
```diff
@@ -39,20 +38,6 @@ protected int getNumTestCasesFor(int version) {
 		return version == RELEASE_0230_VERSION ? MIN_TEST_CASES_PER_VERSION : NUM_TEST_CASES;
 	}
 
-	@Override
```
Comment (rjuang) [inline hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordSerdeTest.java:42]: Please revert these changes. These tests are here for a good reason

File: hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java [hunk 2]
```diff
@@ -140,11 +132,14 @@ public static <T extends SelfSerializable> T deserializeFromBytes(
 
 		final var bais = new ByteArrayInputStream(serializedForm);
 		final var in = new SerializableDataInputStream(bais);
+		byte[] leftover;
 		try {
 			reconstruction.deserialize(in, version);
+			leftover = in.readAllBytes();
```
Comment (rjuang) [inline hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java:138]: I'm not sure if this is a good idea. It's possible the same byte stream will be used for other tests.

**Review by rjuang — CHANGES_REQUESTED** [review]

File: hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java]: Changed as discussed

**Review by rjuang — APPROVED** [review]
