### PR TITLE
Allowance transfers fixes 

### LINKED ISSUE #9284: Fix allowance tests in CryptoTransferSuite
Fix the following tests in `CryptoTransferSuite`

- [x] allowanceTransfersWithComplexTransfersWork
- [x] allowanceTransfersWorkAsExpected

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixed allowance transfers tests in `CryptoTransferSuite`

Fixes #9284 
Fixes https://github.com/hashgraph/hedera-services/issues/9321

- Added missing validation that is_approval=true NFT transfer has owner's approval
- Fixed false positive detection of repeated AccountAmount's by including the is_approval value in AccountAmount "identity"

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java [hunk 1]
```diff
@@ -215,13 +220,17 @@ private record CustomFeeAssessmentResult(
             List<CryptoTransferTransactionBody> assessedTxns, List<AssessedCustomFee> assessedCustomFees) {}
 
     private void validateTotalAdjustments(final CryptoTransferTransactionBody op, final int maxTransfersDepth) {
-        final var hbarTransfers = op.transfersOrElse(TransferList.DEFAULT)
-                .accountAmountsOrElse(emptyList())
+        final var hbarTransfers = op.transfersOrElse(TransferList.DEFAULT).accountAmountsOrElse(emptyList()).stream()
+                .map(AccountAmount::accountID)
+                .collect(Collectors.toSet())
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java:225]: It shouldn't matter because this is a set, but will this code's implementation deterministically map to equivalent set objects every time? Or is this another subtle case where we might get an occasional ISS?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/NFTOwnersChangeStep.java [hunk 2]
```diff
@@ -123,7 +123,7 @@ public void doIn(final TransferContext transferContext) {
      * @param tokenId token id of the nft
      * @param nft nft to be transferred
      */
-    private void validateSpenderHasAllowance(
+    public static void validateSpenderHasAllowance(
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/NFTOwnersChangeStep.java:126]: Does this need to be `public`? I thought package private would work
```suggestion
   static void validateSpenderHasAllowance(
```

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java [hunk 3]
```diff
@@ -199,7 +204,7 @@ public CustomFeeAssessmentResult assessFees(
             throw new IllegalStateException("Custom fee charging exceeded max recursion depth");
         }
 
-        if (!hbarTransfers.isEmpty()) {
+        if (!hbarTransfers.isEmpty() || !tokenTransfers.isEmpty()) {
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java:207]: Good catch!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java (hunk 1 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java:225]: It just needs size. So it doesn't matter if they are in order

Comment (mhess-swl) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/CustomFeeAssessmentStep.java:225]: oh I missed that, nevermind thanks!

**Review by tinker-michaelj — APPROVED** [review]
LGTM! 🙌
