### PR TITLE
fix: Add helpers and HAPI tests for code delegations with type 4 transactions

### LINKED ISSUE #23047: Pectra - HAPI tests for setting up delegations (type 4 and native)
Extend the HAPI test suite with more tests:
- Targeting code delegation setting and reseting cases via type 4 ethereum calls 
- Also include cases combining native and type 4 calls
- Extend the helper test tools to ease the creation of authorisation lists
- Update test plan to include covered cases

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:

Includes helper methods and HAPI tests including type 4 ethereum transactions

**Related issue(s)**:

Fixes #23047 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java [hunk 1]
```diff
@@ -207,6 +210,16 @@ public HapiGetAccountInfo loggingHexedKeys() {
         return this;
     }
 
+    public HapiGetAccountInfo hasDelegationAddress(Address address) {
+        this.delegationAddress = Optional.of(address);
+        return this;
+    }
+
+    public HapiGetAccountInfo hasNoDelegationAddress() {
```
Comment (lukasz-hashgraph) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java]: We're missing an assertion for this case.

File: platform-sdk/base-utility/src/main/java/org/hiero/base/utility/ByteUtils.java [hunk 2]
```diff
@@ -246,4 +246,13 @@ public static Bytes leftPad32(@NonNull final com.hedera.pbj.runtime.io.buffer.By
         bytes.getBytes(0, padded, 32 - n, n);
         return com.hedera.pbj.runtime.io.buffer.Bytes.wrap(padded);
     }
+
+    public static boolean isEmptyOrAllZeros(Bytes bytes) {
```
Comment (mxtartaglia-sl) [inline platform-sdk/base-utility/src/main/java/org/hiero/base/utility/ByteUtils.java]: nit: Please add NonNull and final

Comment (lukasz-hashgraph) [reply platform-sdk/base-utility/src/main/java/org/hiero/base/utility/ByteUtils.java]: done 👍
