### PR TITLE
fix: SELFDESTRUCT now deletes contracts properly

### LINKED ISSUE #14835: SELFDESTRUCT does not actually delete contract (in same transaction, post cancun)
Contracts that are self-destructed in the same transaction as they were created (post cancun) are not being deleted.

Thus, the following contract + test fails - after running the test you'll find the contract still exists (in hashscan):

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

contract DepositHandler {
    function destroy(address etherDestination) external {
        selfdestruct(payable(etherDestination));
    }
}

contract SelfDestruct {
    event DepositHandlerAddr(address indexed, bytes32 indexed);

    function burnToken() external {
        DepositHandler depositHandler = new DepositHandler();
        emit DepositHandlerAddr(address(depositHandler), address(depositHandler).codehash);
        depositHandler.destroy(address(this));
    }
}
```

```typescript
const { expect } = require("chai");
const { ethers } = require("hardhat");

describe.only("SelfDestruct", function () {
    it("should", async function () {
        const ContractFactory = await ethers.getContractFactory("SelfDestruct");
        const contract = await ContractFactory.deploy();
        console.log('contract address', await contract.getAddress());

        const tx = await contract.burnToken();
        console.log('burn token tx', tx.hash);
        const event = (await tx.wait()).logs[0];

        console.log(event.address, event.topics);
        console.log('selfdestructed contract address', (topic => '0x' + topic.slice(-40))(event.topics[1]))
    });
});
```

Reason is:

BESU's `ContractCreationProcessor` has a call to `MessageFrame.addCreate()` to add the new contract created to the tx's list of contracts created so it can later tell if the contract was created in the same transaction or not.

Our version `CustomContractCreationProcessor` is missing that call.

### PR DESCRIPTION
**Pull request by david-bakin-sl**
**Description**:

SELFDESTRUCT opcode wasn't deleting contracts when it should.  An unnoticed BESU update needed to be made in our override classes.

Also:  For the HAPI test suite adds an easy way to create multiple entities (accounts, contracts, ...) at a deterministic time and in order.  Useful for some test cases where you need to predict entity numbers for entities created by smart contracts (e.g., via contract create, or HTS).

**Related issue(s)**:

Fixes #14835

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by lukelee-sl — DISMISSED** [review]
LGTM

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java [hunk 1]
```diff
@@ -198,27 +292,34 @@ final Stream<DynamicTest> selfDestructFailsWhenBeneficiaryHasReceiverSigRequired
...
         final AtomicLong deployer = new AtomicLong();
         final var nonExistingAccountsOps = createOpsArray(
                 nonExistingSystemAccounts,
                 SELF_DESTRUCT_CALLABLE_CONTRACT,
                 DESTROY_EXPLICIT_BENEFICIARY,
                 INVALID_SOLIDITY_ADDRESS);
-        final var existingAccountsOps = createOpsArray(
-                existingSystemAccounts, SELF_DESTRUCT_CALLABLE_CONTRACT, DESTROY_EXPLICIT_BENEFICIARY, SUCCESS);
-        final var opsArray = new HapiSpecOperation[nonExistingAccountsOps.length + existingAccountsOps.length];
+        //        final var existingAccountsOps = createOpsArray(
```
Comment (stoyanov-st) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java:311]: Is this commented on purpose?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/SpecEntity.java [hunk 2]
```diff
@@ -71,6 +71,28 @@ default void registerOrCreateWith(@NonNull final HapiSpec spec) {
...
+     * smart contracts which themselves create contracts, or which use HTS.
+     *
+     * <p>Always use with <code>&#64;LeakyHapiTest(requirement = NO_CONCURRENT_CREATIONS)</code>.
+     *
+     * <p>(See, e.g., {@link com.hedera.services.bdd.suites.contract.opcodes.SelfDestructSuite#selfDestructedContractIsDeletedInSameTx(String)}.)
+     *
+     * @param spec the spec to use to create an entity if it is not already created
+     * @param entities - the entities to create, in order
+     */
+    static void forceCreateAndRegister(@NonNull final HapiSpec spec, final SpecEntity... entities) {
```
Comment (stoyanov-st) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/SpecEntity.java:89]: Nice addition here!

**Review by stoyanov-st — COMMENTED** [review]
TYVM @david-bakin-sl!
Left a comment and also needs spotless.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java (hunk 1 above)
Comment (david-bakin-sl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java:311]: Meant to remove it - unused in current (existing) test.

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by stoyanov-st — APPROVED** [review]
LGTM
