### PR TITLE
remove reconnect abort

### LINKED ISSUE #9450: Reconnect abort is not thread safe
```
new ReconnectTeacher(
                            threadManager,
                            connection,
                            reconnectSocketTimeout,
                            connection.getSelfId(),
                            connection.getOtherId(),
                            state.get().getRound(),
                            fallenBehindManager::hasFallenBehind,    <-- will abort reconnect if returns true
                            reconnectMetrics,
                            configuration)
```

When a node falls behind while it is teaching, the reconnect protocol attempts to abort. However, this abort operation is asynchronous. The reconnect protocol may still be sending data over the socket by the time that control is returned back to the protocol negotiator. This may cause bytes from both sources to intermingle.

Even if aborting a reconnect is fully synchronous, there are problems. Unless the reconnect-abort procedure is closely coordinated with the learner, it is very unlikely that the connection will be salvageable. Unless the learner knows exactly which bytes should be discarded w.r.t. the failed reconnect, its stream alignment will be wrong, and it won't be able to interpret the bytes sent by the protocol negotiator.

We either need to break the socket when we want to abort a reconnect, or we need to coordinate the operation with all threads on both the teacher and the learner.

### LINKED ISSUE #9678: Reconnect protocol violation causes havoc on the learner side.
### Description

If in a reconnect session, the teacher itself falls behind it silently stops sending lessons assuming the learner will eventually abandon the reconnect attempt. That's not, however, how it actually plays out. The teacher is not stopped and it starts sending a new tree to the learner. Since the learner is still expecting lessons from the previous tree, the new lesson creates havoc: a range of different errors depending on a particular context in which the previous tree stopped sending. 
Eventually, the teacher does not receive a proper response from the learner and closes the connection.

See also: #9477

### Steps to reproduce

The bug requires a network under heavy load. The actual reason the teacher fell behind was memory pressure (ZGC allocation stalls). Here is an excerpt  from teacher's `swirlds.log` supporting the bug description:
```
2023-11-04 01:49:37.323 678875   INFO  RECONNECT        <<platform-core: SyncProtocolWith28 23 to 28>> ReconnectTeacher: Starting reconnect in the role of the sender {"receiving":false,"nodeId":23,"otherNodeId":28,"round":449853} [com.swirlds.logging.payloads.ReconnectStartPayload]
...
2023-11-04 01:56:28.480 684060   INFO  RECONNECT        <<platform-core: SyncProtocolWith28 23 to 28>> TeachingSynchronizer: sending tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 1 -> 1]
...
2023-11-04 02:48:52.662 722790   INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 23.7 m in CHECKING. Now in BEHIND {"oldStatus":"CHECKING","newStatus":"BEHIND"} [com.swirlds.logging.payloads.PlatformStatusPayload]
...
2023-11-04 02:48:53.221 722801   INFO  RECONNECT        <<work group teaching-synchronizer: sender #2>> TeacherSendingThread: Teacher's sending thread is requested to stop teaching (fallen behind?)
2023-11-04 02:48:53.625 722808   INFO  RECONNECT        <<platform-core: SyncProtocolWith28 23 to 28>> TeachingSynchronizer: finished sending tree
2023-11-04 02:48:54.639 722820   INFO  RECONNECT        <<platform-core: SyncProtocolWith28 23 to 28>> TeachingSynchronizer: sending tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 3 -> 1]
2023-11-04 02:48:54.937 722922   INFO  RECONNECT        <<work group teaching-synchronizer: sender #2>> TeacherSendingThread: Teacher's sending thread is requested to stop teaching (fallen behind?)
...
2023-11-04 02:53:55.130 726011   ERROR EXCEPTION        <<platform-core: SyncProtocolWith28 23 to 28>> StandardWorkGroup: Work Group Exception [ groupName = teaching-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
2023-11-04 02:53:55.587 726023   ERROR EXCEPTION        <<platform-core: SyncProtocolWith28 23 to 28>> NetworkUtils: Connection broken: 23 -> 28
```

### Additional context

_No response_

### Hedera network

other

### Version

v0.43.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by lpetrovic05**
closes #9450
closes #9678

### CODE REVIEW

**Review by cody-littley — DISMISSED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

**Review by timo0 — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java [hunk 1]
```diff
@@ -123,6 +129,9 @@ public String toString() {
     void setup() {
         activeStatusGetter = mock(PlatformStatusGetter.class);
         when(activeStatusGetter.getCurrentStatus()).thenReturn(PlatformStatus.ACTIVE);
+
+        reconnectController = mock(ReconnectController.class);
+        when(reconnectController.blockLearnerPermit()).thenReturn(true);
```
Comment (imalygin) [inline platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java:134]: Should there be a test for "`blockLearnerPermit` returning false" scenario?

**Review by artemananiev — DISMISSED** [review]

File: platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java (hunk 1 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java:135]: Its an almost impossible scenario, but I added a test for it. Please re-approve

**Review by cody-littley — APPROVED** [review]

**Review by imalygin — APPROVED** [review]
