### PR TITLE
test: Re-enable event hash block stream validators with PCES-based stale event handling

### LINKED ISSUE #22479: Fix flaky BlockStream validation
Sometimes block stream validation fails with the following error
```
java.lang.AssertionError: Block stream validation failed:	
  - Unable to find event matching parent hash f133bc0de82b0c283a27aaf0128ae9d66f29d51c4c8bd0134ccd134b15ac43e3eabfc57dd4c226f8a12268523a9146b0	
  - Unable to find event matching parent hash f133bc0de82b0c283a27aaf0128ae9d66f29d51c4c8bd0134ccd134b15ac43e3eabfc57dd4c226f8a12268523a9146b0	
 ```

Example run - https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/19902111547/job/57057555166
Failure scan - https://scans.gradle.com/s/jjopllwi7kvtm/tests/overview

Investigate and fix the issue with `BlockStream` validation.

### LINKED ISSUE #22769: Update block stream validators to use PCES events as source of truth for parent hash verification
Block stream validation currently fails intermittently with "Unable to find event matching parent hash" errors during restart tests (see #22479).

Current Validator Limitation
The current BlockStreamEventBuilder validates parent references by checking if the parent hash exists in previously processed block stream events. This fails when:
  - A parent event was in PCES but never reached consensus
  - The child event references this non-consensused parent

Proposed Solution
Update the validators to read PCES events as the source of truth and compare block stream event hashes against PCES event hashes.

### PR DESCRIPTION
**Pull request by aderevets**
## Summary
- Re-enables `EventHashBlockStreamValidator` and `RedactingEventHashBlockStreamValidator` in `StreamValidationOp`
- Adds `PcesEventHashReader` that reads PCES files from node working directories and hashes events with `PbjStreamHasher` to build a set of known-valid event hashes
- Cross-block parent hash lookups now check both block stream events and PCES event hashes, tolerating stale events that went through gossip but never reached consensus
- Adds `PCES_DIR` to `ExternalPath` for resolving PCES file locations from test node metadata

## Test plan
- [x] `hapiTestRestart` CI suite passes without flaky `StreamValidationTest` failures

Fixes #22479
Closes #22769

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java [hunk 1]
```diff
@@ -96,10 +122,52 @@ static void validateEventHashChain(
...
                 events.stream().map(PlatformEvent::getHash).collect(Collectors.toSet());
 
+        final List<Hash> unresolvedHashes = new ArrayList<>();
         for (final Hash crossBlockParentHash : crossBlockParentHashes) {
-            if (!eventHashes.contains(crossBlockParentHash)) {
-                fail("Cross block parent hash {} not found among event hashes!", crossBlockParentHash);
+            if (!eventHashes.contains(crossBlockParentHash) && !pcesEventHashes.contains(crossBlockParentHash)) {
+                fail("Cross block parent hash {} not found among event or PCES hashes!", crossBlockParentHash);
+            }
+        }
```
Comment (poulok) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:158]: I think it's a good idea to keep track of the percentage and total number of events' parent hashes that were not found in the block stream and were found in PCES. If this number or percentage gets to be more than a very small number, it's an indication that something is wrong.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java [hunk 2]
```diff
@@ -96,10 +122,52 @@ static void validateEventHashChain(
...
+                : 100.0 * unresolvedHashes.size() / crossBlockParentHashes.size();
+        if (unresolvedPercent > MAX_UNRESOLVED_PARENT_PERCENT) {
+            fail(
+                    "Too many unresolved cross-block parent hashes: %d of %d (%.1f%% > %.1f%% threshold). Hashes: %s",
+                    unresolvedHashes.size(),
+                    crossBlockParentHashes.size(),
+                    unresolvedPercent,
+                    MAX_UNRESOLVED_PARENT_PERCENT,
+                    unresolvedHashes);
+        }
```
Comment (poulok) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java]: This block is unnecessary with the PCES event hash lookup. Even stale events will be in PCES.

Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java]: yeah sorry forgot to remove it.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java [hunk 3]
```diff
@@ -96,10 +130,215 @@ static void validateEventHashChain(
...
+        final var testDir = anyNode.getExternalPath(ExternalPath.WORKING_DIR)
+                .toAbsolutePath()
+                .normalize()
+                .getParent();
+        if (testDir != null && Files.isDirectory(testDir)) {
+            try (final var dirs = Files.list(testDir)) {
+                dirs.filter(Files::isDirectory)
+                        .filter(d -> d.getFileName().toString().startsWith("node"))
+                        .forEach(nodeDir -> {
+                            final var dirName = nodeDir.getFileName().toString();
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:303]:
```suggestion
                            final var dirName = nodeDir.getFileName().toString();
                            log.info("Scanning dir {} for PCES files", dirName);                            
```

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/PcesEventHashReader.java [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+import org.hiero.consensus.crypto.PbjStreamHasher;
+import org.hiero.consensus.model.event.EventOrigin;
+import org.hiero.consensus.model.event.PlatformEvent;
+
+/**
+ * Reads PCES (Pre-Consensus Event Stream) files from disk and extracts event hashes and metadata.
+ * These hashes serve as the source of truth for validating cross-block parent references in the
+ * block stream, since some events may exist in PCES but never reach consensus (stale events).
+ */
+public final class PcesEventHashReader {
```
Comment (mhess-swl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/PcesEventHashReader.java:23]: Is there already a utility class or method somewhere to read these files? Seems odd to need to write more code to read them. Not a huge deal, just wondering

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java (hunk 3 above)
Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:303]: Done, added the log line.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/PcesEventHashReader.java (hunk 4 above)
Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/PcesEventHashReader.java:23]: Good question. PcesFileIteratorFactory exists in consensus-pces-impl testFixtures, but test-clients doesn't have module access to it adding it would require changes to both module-info files. Do you prefer switch to PcesFileIteratorFactory?

Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/PcesEventHashReader.java:23]: I decide to keep PcesEventHashReader to encapsulate pces reading but I reuse most of logic from PcesFileIteratorFactory. Should be cleaner now. Thanks!

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java [hunk 5]
```diff
@@ -96,10 +130,216 @@ static void validateEventHashChain(
...
+                if (pcesData.eventHashes().contains(ref.parentHash())) {
+                    pcesOnlyRefs.add(ref);
+                } else {
+                    unresolvedRefs.add(ref);
+                }
+            }
+        }
+
+        if (!pcesOnlyRefs.isEmpty()) {
+            logger.warn(
```
Comment (poulok) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:163]: A warning will not fail the test, correct? If a large number of events are only found in PCES, there is a problem and the test should fail. When I mean "large", I mean >1% of all events. Maybe even less

Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:163]: I got you and will add this

Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:163]: We're not validating the PCES files themselves--only loading them in order to reconstruct all of the event hashes. If we do want that validation that's fine, but I'd argue it's not an Execution layer test.

Comment (poulok) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:163]: @mhess-swl I'm not asking for PCES to be validated. I'm asking for the test to fail if a certain number or percentage of event parents are found in PCES and not in the blocks. This should exactly match the number of stale events from the run which are extremely rare. If we start seeing a lot of events like this, the test should fail.

Comment (mhess-swl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:163]: Ohhhhh I see, in other words validating that the vast majority of events _are in the block stream_, got it. Agreed that would be a valuable check to have.

Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java:163]: done. I added verification if we getting more than 1% of stale events

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java [hunk 6]
```diff
@@ -96,10 +137,223 @@ static void validateEventHashChain(
...
+                        ref.parentDescriptor().birthRound(),
+                        ref.parentHash(),
+                        ref.childCreatorId(),
+                        ref.childBirthRound(),
+                        ref.childBlockIndex());
+            }
+            if (pcesOnlyPercent > MAX_PCES_ONLY_PERCENT) {
+                fail(
+                        "%.2f%% of cross-block parent hashes (%d of %d) were resolved via PCES only,"
+                                + " exceeding the %.1f%% threshold. This indicates too many stale events.",
```
Comment (poulok) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java]: It doesn't indicate too many stale events - it indicates a problem with the event hashes in the block stream. Ideally, we would check every event that does not have it's parents in the block stream against stale events and make sure the missing parents are present in the list of stale events. Assuming stale events are extremely rare, then also the number of PCES only parents should also be rare. If we see a lot of PCES only parents, it is an indication that one of two things happened:
1. There were an unusually high number of stale events
2. There is something causing event hashes to be calculated incorrectly.

I suggest working the failure message more like this:

`%.2f%% of cross-block parent hashes (%d of %d) were resolved via PCES only, exceeding the %.1f%% threshold. Either this test run had an unusually high number of stale events, or event hashes are not being calculated properly from the block stream data.`

Comment (aderevets) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/block/EventHashBlockStreamValidator.java]: done) Thank you for suggestion!
