### PR TITLE
fix of the singleton state causing an modurun issue

### LINKED ISSUE #786: Starting from saved state, delay system file creation until ServicesMain#init
**Summary of the defect**
When starting from a saved state, it appears `BinaryObjectStore` recovery is not completed until _after_ `ServicesState#init`. In this case we must delay system file initialization to `ServicesMain#init`---as was done before reonnect.

**Service logs (if applicable)**
```
...
2020-11-18 17:44:58.635 INFO  445  SwirldsPlatform - Signed state loaded from disk has a valid hash.
2020-11-18 17:44:58.689 ERROR 703  Browser - Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Exception while reading signed state!
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:473) ~[swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:701) [swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:944) [swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:345) [swirlds-platform-core-0.7.5.jar:?]
Caused by: java.lang.NullPointerException
	at com.swirlds.blob.BinaryObject.getId(BinaryObject.java:130) ~[swirlds-platform-core-0.7.5.jar:?]
	at com.swirlds.blob.BinaryObjectStore.get(BinaryObjectStore.java:297) ~[swirlds-platform-core-0.7.5.jar:?]
	at com.hedera.services.state.merkle.MerkleOptionalBlob.getData(MerkleOptionalBlob.java:216) ~[?:?]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at com.hedera.services.files.store.FcBlobsBytesStore.get(FcBlobsBytesStore.java:111) ~[?:?]
	at com.hedera.services.files.store.FcBlobsBytesStore.get(FcBlobsBytesStore.java:37) ~[?:?]
	at com.hedera.services.files.store.BytesStoreAdapter.get(BytesStoreAdapter.java:79) ~[?:?]
	at com.hedera.services.files.TieredHederaFs.assertUsable(TieredHederaFs.java:326) ~[?:?]
	at com.hedera.services.files.TieredHederaFs.cat(TieredHederaFs.java:136) ~[?:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFrom(HfsSystemFilesManager.java:170) ~[?:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadConfigWithJutilPropsFallback(HfsSystemFilesManager.java:231) ~[?:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadApplicationProperties(HfsSystemFilesManager.java:123) ~[?:?]
	at com.hedera.services.ServicesState.initializeContext(ServicesState.java:244) ~[?:?]
	at com.hedera.services.ServicesState.init(ServicesState.java:220) ~[?:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:461) ~[swirlds-platform-core-0.7.5.jar:?]
	... 3 more
2020-11-18 17:44:58.700 DEBUG 210  BinaryObjectStore - Recovery Starting
2020-11-18 17:44:58.701 DEBUG 222  BinaryObjectStore - Recovering Objects [ objectCount = 13, uniqueObjectCount = 7 ]
2020-11-18 17:44:58.714 DEBUG 267  BinaryObjectStore - Recovery Finished
...
```

### PR DESCRIPTION
**Pull request by povolev15**
**Related issue(s)**:

Fixes # [7686](https://github.com/hashgraph/hedera-services/issues/7686)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java [hunk 1]
```diff
@@ -60,18 +63,28 @@ public class ReadableStoreFactory {
...
-            ReadableTopicStore.class, new StoreEntry(ConsensusService.NAME, ReadableTopicStoreImpl::new),
-            ReadableScheduleStore.class, new StoreEntry(ScheduleService.NAME, ReadableScheduleStoreImpl::new),
-            ReadableFileStore.class, new StoreEntry(FileService.NAME, ReadableFileStoreImpl::new),
-            ReadableUpdateFileStore.class, new StoreEntry(FreezeService.NAME, ReadableUpdateFileStoreImpl::new),
-            ReadableRunningHashLeafStore.class,
-                    new StoreEntry(NetworkService.NAME, ReadableRunningHashLeafStoreImpl::new),
-            ReadableTokenRelationStore.class, new StoreEntry(TokenService.NAME, ReadableTokenRelationStoreImpl::new));
+    private static final Map<Class<?>, StoreEntry> STORE_FACTORY = createFactoryMap();
+
+    private static final Map<Class<?>, StoreEntry> createFactoryMap() {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java:68]: Note: This had to change because `Map.of` is limited to 10 or fewer parameters.

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java [hunk 2]
```diff
@@ -70,7 +72,7 @@ public void resetFileContents() {
 
     @Nullable
     public File removeIf(@NonNull Predicate<File> predicate) {
-        return writableUpgradeFileState.get();
+        return null;
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:75]: Is this intentionally set to null ?

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java [hunk 3]
```diff
@@ -40,10 +42,12 @@
  * <p>This class is not exported from the module. It is an internal implementation detail.
  */
 public class ReadableUpgradeStoreImpl implements ReadableUpgradeStore {
+    private final FileID UPGRADE_FILE_ID = new FileID(0, 0, 150);
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java:45]: We should bring up with the team (perhaps next week) how to get configuration into object store implementations.

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java [hunk 4]
```diff
@@ -69,13 +73,13 @@ public String getFileStateKey() {
...
     public File peek() {
-        return upgradeFileState.get();
+        return upgradeFileState.get(UPGRADE_FILE_ID);
     }
 
     @Override
     @NonNull
     public Iterator<File> iterator() {
-        return List.of(upgradeFileState.get()).iterator();
+        return List.of(upgradeFileState.get(UPGRADE_FILE_ID)).iterator();
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java:82]: This is my error.  List.of will throw if the input is null, so here's a suggested change.
```suggestion
        final File upgradeFile = upgradeFileState.get(UPGRADE_FILE_ID);
        return upgradeFile != null 
                ? List.of(upgradeFile).iterator()
                : new ArrayList<File>(0).iterator();
```

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java [hunk 5]
```diff
@@ -70,7 +72,7 @@ public void resetFileContents() {
 
     @Nullable
     public File removeIf(@NonNull Predicate<File> predicate) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:74]: Just a question, because I don't recall.  Why did we implement `WritableQueueState` for this class?

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java [hunk 6]
```diff
@@ -276,11 +277,13 @@ protected void givenValidFile(boolean deleted, boolean withKeys) {
         fileWithNoContent = new File(fileId, expirationTime, withKeys ? keys : null, null, memo, deleted);
         fileSystem =
                 new File(fileSystemFileId, expirationTime, withKeys ? keys : null, Bytes.wrap(contents), memo, deleted);
+        upgradeFile = new File(
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java:280]: This is using the upgrade file a bit too consistently, which invalidates some of the testing.
The upgrade file probably shouldn't be set here.

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java [hunk 7]
```diff
@@ -50,10 +50,10 @@ void commitsUpgradeFileExist() {
         assertFalse(writableUpgradeStates.iterator().hasNext());
 
         writableUpgradeStates.add(file.contents());
-        writableUpgradeFileStates.put(file);
+        writableUpgradeFileStates.put(file.fileId(), file);
 
-        assertTrue(writableUpgradeFileStates.get().fileId().fileNum() == 150L);
-        final var writtenFile = writableUpgradeFileStates.get();
+        assertTrue(writableUpgradeFileStates.get(fileUpgradeFileId).fileId().fileNum() == 150L);
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java:55]: Nit: Probably should pull this magic number (150L) from a constant...

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java (hunk 2 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:75]: yes, removeIf returns null if there is nothing to remove, and this class never removes the file.
Really, I think we might have erred in implementing the WritableQueueState interface.

Comment (iwsimon) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:75]: Same question here.

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java (hunk 5 above)
Comment (netopyr) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:74]: I agree, this seems weird. `WritableQueueState` is on the same level as `WritableSingletonState` and `WritableKVState`. A store should be on a higher level, closer to the business logic.

**Review by netopyr — APPROVED** [review]
LGTM in regards to `hedera-base`

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:75]: @jsync-swirlds  The n we should probably throw `UnsupportedOperationException`

Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:75]: It's not unimplemented or unsupported, it's correctly returning that there is nothing left to remove.
That said, what we really need to do is not implement `WritableQueueState` here (I am now convinced that was a mistake), which will remove this method as unnecessary.
@povolev15 Can you make that change?  Remove the `implements WritableQueueState` clause and the overridden methods?  I believe it will not break anything and will simplify this class.

Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:75]: sure I will remove and test it

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java (hunk 3 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java:45]: sure will be done. we can also check with @netopyr

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java (hunk 4 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java:82]: fixed thanks

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java (hunk 5 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:74]: I removed it we had it before when we tried to implement singleton and to use queue as only state for upgrade file

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java (hunk 6 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java:280]: removed thanks

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java (hunk 7 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java:55]: done thanks

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java [hunk 8]
```diff
@@ -50,10 +50,10 @@ void commitsUpgradeFileExist() {
         assertFalse(writableUpgradeStates.iterator().hasNext());
 
         writableUpgradeStates.add(file.contents());
-        writableUpgradeFileStates.put(file);
+        writableUpgradeFileStates.put(file.fileId(), file);
 
-        assertTrue(writableUpgradeFileStates.get().fileId().fileNum() == 150L);
-        final var writtenFile = writableUpgradeFileStates.get();
+        assertTrue(writableUpgradeFileStates.get(fileUpgradeFileId).fileId().fileNum() == fileUpgradeFileId.fileNum());
```
Comment (jsync-swirlds) [inline hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java:55]: This is a bit tautological. The RHS would be better as a proper constant.

**Review by jsync-swirlds — APPROVED** [review]
One nit regarding a constant.  Otherwise LGTM.

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java [hunk 9]
```diff
@@ -33,11 +34,11 @@
  * <p>This class is not exported from the module. It is an internal implementation detail. This
  * class is not complete, it will be extended with other methods like remove, update etc.,
  */
-public class WritableUpgradeStore extends ReadableUpgradeStoreImpl implements WritableQueueState<File> {
+public class WritableUpgradeStore extends ReadableUpgradeStoreImpl {
     /** The underlying data storage class that holds the file data. */
     private final WritableQueueState<Bytes> writableUpgradeState;
 
-    private final WritableSingletonState<File> writableUpgradeFileState;
+    private final WritableKVState<FileID, File> writableUpgradeFileState;
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:41]: Do we need this store now ? Can we not use `WritableFileStore` , since it almost seems the same ? Am I missing something

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java [hunk 10]
```diff
@@ -40,10 +43,12 @@
  * <p>This class is not exported from the module. It is an internal implementation detail.
  */
 public class ReadableUpgradeStoreImpl implements ReadableUpgradeStore {
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java:45]: Same for this, why can't we use `ReadableFileStoreImpl` ?

**Review by Neeharika-Sompalli — COMMENTED** [review]
Not a blocker for this PR, I am unsure why we need `WritableUpgradeStore.java` and `ReadableUpgradeStore.java` when it is almost same as FileStore to store upgrade file also.

File: hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java (hunk 8 above)
Comment (povolev15) [reply hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableUpgradeStoreTest.java]: fixed

**Comment by jsync-swirlds** [comment]
We need the Upgrade stores so we can store the content in a FCQueue via WritableQueueState and ReadableQueueState.  They're intentionally as close to the base file stores as possible without putting switches all over those stores for "is this the upgrade file".

**Review by jsync-swirlds — APPROVED** [review]

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java (hunk 9 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:41]: Upgrade file has to use the WritableQueueState for the file content.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:41]: It is not implementing `WritableQueueState` anymore. So how does it store the content in `WritableQueueState` ? Is it added somewhere else?

**Review by netopyr — APPROVED** [review]
LGTM in regards to files in `hedera-app`

I have to admit though, the design of `ReadableUpgradeStore` and `WritableUpgradeStore` is not really comprehensible to me.

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java (hunk 9 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableUpgradeStore.java:41]: It absolutely does still read from the queue state.  The `File` is in KV state, the *content* (the bytes of the file) are still filled in from the queue state.  If it did not do that it would level the node.
Look at lines 39, 58, 64, etc...  The readable mirror is similar.
There are two states in each class (WritableUpgradeState/WritableUpgradeFileState and ReadableUpgradeState/ReadableUpgradeFileState).

File: hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java (hunk 10 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableUpgradeStoreImpl.java:45]: The File is in KV state, the content (the bytes of the file) are still filled in from the queue state. If it did not do that it would level the node.
This is still necessary to avoid if/else in every method of `ReadableFileStoreImpl`.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! The questions can be addressed in next PR once clarified
