### PR TITLE
02282: Standalone test suites for testing network upgrade

### LINKED ISSUE #2282: Create standalone test suites for testing network upgrade
as described here https://github.com/swirlds/swirlds-platform-regression/issues/1632#issuecomment-934537812

### PR DESCRIPTION
**Pull request by qnswirlds**
Close #2282

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CommonUpgradeResources.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+			final var fileBytes = Files.readAllBytes(Paths.get(upgradeFilePath()));
+			return noThrowSha384HashOf(fileBytes);
+		} catch (final InvalidPathException | IOException ignore) {
+		}
+		return new byte[0];
+	}
+
+	public static int upgradeDelay() {
+		return settings.getIntProperty("upgradeDelay", DEFAULT_UPGRADE_DELAY);
+	}
```
Comment (qnswirlds) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CommonUpgradeResources.java:69]: Sample json config:
```
"hederaServicesConfig": {
  "ciPropsMap": "upgradeFileId=0.0.150,upgradeFilePath=upgrade.zip,upgradeDelay=2"
}
```

**Review by JeffreyDallas — APPROVED** [review]
