### PR TITLE
Retry starting Netty at configurable interval, up to configurable max times

### LINKED ISSUE #1523: add retries of port bind for GRPC ports
**Summary of the defect**
GRPC ports configured for 50211 Non-TLS and 50212 TLS sporadically fail to bind on application start, resulting in the application terminating. These ports are likely failing to bind because they are in the ephemeral port range. However, it appears that the port binds for GRPC may not include any logic to retry, as they appear to attempt to bind and fail almost immediately

Note that the gossip port is also configured to use a port in the ephemeral range at 50111, however platform includes logic to retry the port bind until it is successful. As a result, we do not see these issues on binding the gossip port

Long-term a solution could be to use ports outside the ephemeral range, however this would be a change that requires lots of coordination and implications to many parties. If such a change is possible it will be a long time before it can be made

In the more immediate term, it would be best to retry binding the GRPC ports until they are able to successfully bind

**How to reproduce (if possible)**
Issue exhibits sporadically when services is started. On a network of just about any size it often exhibits with just one or two nodes out of the network failing to bind the GRPC ports

**Service logs (if applicable)**
```
2021-06-02 22:31:34.306 INFO  151  ServicesMain - System files rationalized.
2021-06-02 22:31:34.314 INFO  105  BackedSystemAccountsCreator - Ledger float is 5000000000000000000 tinyBars in 228 accounts.
2021-06-02 22:31:34.314 INFO  153  ServicesMain - System accounts initialized.
2021-06-02 22:31:34.314 INFO  155  ServicesMain - Migrations complete.
2021-06-02 22:31:34.357 INFO  157  ServicesMain - Ledger state ok.
2021-06-02 22:31:34.357 INFO  159  ServicesMain - Platform is configured.
2021-06-02 22:31:34.362 INFO  161  ServicesMain - Platform callbacks registered.
2021-06-02 22:31:34.364 INFO  163  ServicesMain - ReconnectCompleteListener registered.
2021-06-02 22:31:34.364 INFO  165  ServicesMain - Accounts exported.
2021-06-02 22:31:34.380 INFO  167  ServicesMain - Stats initialized.
2021-06-02 22:31:34.380 INFO  209  ServicesMain - TLS is turned on by default on node 4
2021-06-02 22:31:34.380 INFO  211  ServicesMain - Active profile: PROD
2021-06-02 22:31:34.522 INFO  260  ServicesMain - Starting Netty on port 50211...
2021-06-02 22:31:34.522 INFO  65   ConfigDrivenNettyFactory - Configuring a Netty server on port 50211 (TLS OFF) for TEST environment
2021-06-02 22:31:34.806 INFO  260  ServicesMain - ...done starting Netty on port 50211.
2021-06-02 22:31:34.807 INFO  260  ServicesMain - Starting Netty with TLS support on port 50212...
2021-06-02 22:31:34.807 INFO  65   ConfigDrivenNettyFactory - Configuring a Netty server on port 50212 (TLS ON) for TEST environment
2021-06-02 22:31:35.079 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#4!
java.lang.IllegalStateException: java.io.IOException: Failed to bind
        at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:72) ~[HGCApp.jar:?]
        at com.hedera.services.ServicesMain.startNettyIfAppropriate(ServicesMain.java:224) ~[HGCApp.jar:?]
        at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:168) ~[HGCApp.jar:?]
        at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HGCApp.jar:?]
        at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:867) [swirlds-platform-core-0.15.0-alpha.1.jar:?]
        at com.swirlds.platform.Browser.startPlatforms(Browser.java:978) [swirlds-platform-core-0.15.0-alpha.1.jar:?]
        at com.swirlds.platform.Browser.main(Browser.java:360) [swirlds-platform-core-0.15.0-alpha.1.jar:?]
Caused by: java.io.IOException: Failed to bind
        at io.grpc.netty.NettyServer.start(NettyServer.java:264) ~[grpc-netty-1.33.0.jar:1.33.0]
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:183) ~[grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.33.0.jar:1.33.0]
        at com.hedera.services.grpc.NettyGrpcServerManager.startOneNettyServer(NettyGrpcServerManager.java:83) ~[HGCApp.jar:?]
        at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:65) ~[HGCApp.jar:?]
        ... 6 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2021-06-02 22:31:35.085 INFO  260  ServicesMain - Terminating Netty on port 50211...
```

**Environment:**
- OS: Exhibited on any Linux OS hedera-services has been run on 
- Java: OpenJDK 12.0.1
- Hedera Services Version: current stable v0.14.0, current bleeding edge builds, indefinite previous releases

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Closes #1523

**Summary of the change**:
- When starting Netty, retry every `netty.startRetryIntervalMs=1000` milliseconds up to `netty.startRetries=30` times.

**External impacts**:
Should make Services resilient to short-lived port binding conflicts on the ephemeral 50211/50212 ports.

### CODE REVIEW

File: hedera-node/src/test/java/com/hedera/services/grpc/NettyGrpcServerManagerTest.java [hunk 1]
```diff
@@ -85,15 +106,80 @@ private void setup() throws Exception {
...
+		assertThrows(IOException.class, () ->
+				subject.startOneNettyServer(false, port, ignore -> {}, mockPause));
+
+		// then:
+		verify(mockPause, times(startRetries)).forMs(startRetryIntervalMs);
+		verify(server, times(startRetries + 1)).start();
+		assertThat(logCaptor.warnLogs(), contains(
+				"(Attempts=1) Still trying to start Netty on port 8080...Failed to bind",
+				"(Attempts=2) Still trying to start Netty on port 8080...Failed to bind",
+				"(Attempts=3) Still trying to start Netty on port 8080...Failed to bind"));
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/grpc/NettyGrpcServerManagerTest.java:159]: Beautiful tests! Great job!

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java [hunk 2]
```diff
@@ -73,14 +81,29 @@ public void start(int port, int tlsPort, Consumer<String> println) {
...
+				break;
+			} catch (IOException e) {
+				final var summaryMsg = nettyAction("Still trying to start", sslEnabled, port, true);
+				log.warn("(Attempts=" + retryNo + ") " + summaryMsg + e.getMessage());
+				pause.forMs(nodeProperties.nettyStartRetryIntervalMs());
+			}
+		}
+		if (retryNo == n + 1) {
+			server.start();
+		}
```
Comment (ljianghedera) [inline hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java:106]: Can this `if` statement be removed if line 94 is `final var n = Math.max(1, nodeProperties.nettyStartRetries());`?

File: hedera-node/src/test/java/com/hedera/services/grpc/NettyGrpcServerManagerTest.java [hunk 3]
```diff
@@ -85,15 +106,80 @@ private void setup() throws Exception {
...
+
+		// expect:
+		assertThrows(IOException.class, () ->
+				subject.startOneNettyServer(false, port, ignore -> {}, mockPause));
+
+		// then:
+		verify(mockPause, never()).forMs(startRetryIntervalMs);
+		verify(server).start();
+		assertTrue(logCaptor.warnLogs().isEmpty());
+	}
```
Comment (qnswirlds) [inline hedera-node/src/test/java/com/hedera/services/grpc/NettyGrpcServerManagerTest.java:179]: beautiful as well :D

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java [hunk 4]
```diff
@@ -41,18 +46,21 @@
...
 	public NettyGrpcServerManager(
 			Consumer<Thread> hookAdder,
+			NodeLocalProperties nodeProperties,
 			List<BindableService> bindableServices,
 			ConfigDrivenNettyFactory nettyBuilder,
 			List<ServerServiceDefinition> serviceDefinitions
 	) {
 		this.hookAdder = hookAdder;
 		this.nettyBuilder = nettyBuilder;
+		this.nodeProperties = nodeProperties;
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java:63]: nit: Maybe we could save only `nettyStartRetries` and `nettyStartRetryIntervalMs` in this class. We don't need the whole `nodeProperties` object.

**Review by qnswirlds — DISMISSED** [review]
Other than a nit, things look excellent to me. Great job!

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM

**Review by ljianghedera — APPROVED** [review]
LGTM

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java [hunk 5]
```diff
@@ -73,14 +81,29 @@ public void start(int port, int tlsPort, Consumer<String> println) {
...
+			try {
+				server.start();
+				break;
+			} catch (IOException e) {
+				final var summaryMsg = nettyAction("Still trying to start", sslEnabled, port, true);
+				log.warn("(Attempts=" + retryNo + ") " + summaryMsg + e.getMessage());
+				pause.forMs(nodeProperties.nettyStartRetryIntervalMs());
+			}
+		}
+		if (retryNo == n + 1) {
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java:104]: Another nit: It's always safer doing `retryNo > n` than this strict expectation. Also, I don't know why Codecov complains about the `server.start();` in this if, but you did cover it in the `givesUpIfMaxRetriesExhaustedAndPropagatesIOException` test.

**Review by tannerjfco — APPROVED** [review]
Thanks so much for implementing this fix! DevOps team is eternally grateful for this work that will improve stability of our automations. Cheers to many green builds in our future 🎉 

@tinker-michaelj just one question on the configurable nature of this retry support - Which configuration file does this configuration go into if we were to need to adjust it? Would it be node.properties or bootstrap.properties or other? (The defaults look reasonable, so I'm not too worried but want to make sure if we do need to play with this we know what file to change)

**Review by anighanta — APPROVED** [review]

**Comment by tinker-michaelj** [comment]
> Thanks so much for implementing this fix! DevOps team is eternally grateful for this work that will improve stability of our automations. Cheers to many green builds in our future 🎉
> 
> @tinker-michaelj just one question on the configurable nature of this retry support - Which configuration file does this configuration go into if we were to need to adjust it? Would it be node.properties or bootstrap.properties or other? (The defaults look reasonable, so I'm not too worried but want to make sure if we do need to play with this we know what file to change)

My pleasure! 🎉  Overrides for `netty.startRetries` and `netty.startRetryIntervalMs` will be in the _node.properties_ file. 👍

**Review by abhishek-hedera — DISMISSED** [review]
LGTM

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java:110]: It could, but then there would need to be an `if` inside the `catch` to log with the same pattern... 😁

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java]: Captured properties in constructor instead.

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java [hunk 6]
```diff
@@ -90,15 +94,15 @@ Server startOneNettyServer(boolean sslEnabled, int port, Consumer<String> printl
 		Server server = builder.build();
 
 		var retryNo = 1;
-		final var n = Math.max(0, nodeProperties.nettyStartRetries());
+		final var n = Math.max(0, startRetries);
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java:97]: Should move this logic to the constructor and remove `var n` altogether.

File: hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java (hunk 2 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/grpc/NettyGrpcServerManager.java:110]: Hmm, I don't see why an `if` is needed in the `catch` block. My understanding is if `server.start()` inside the `for` is successful, nothing will happen and the `break` will end the loop and move on. If it's not successful, the `catch` block will log the attempt times, pause, and then re-run `server.start()` till the `server.start()` finishes successful or the max retry number is reached.

**Review by ljianghedera — APPROVED** [review]
LGTM
