### PR TITLE
fix: revert ces name

### LINKED ISSUE #13198: Revert CES directory naming
In 0.50, the naming schema for the CES directory changed. This is causing problems for node managers.

Original CES directory: `events_${X}` where X is equal to the memo field of the node's address if it is present, or equal to the node ID if the memo field is not present.

New CES directory: `events_${NODE_ID}`

### PR DESCRIPTION
**Pull request by cody-littley**
closes #13198 
PR for develop: https://github.com/hashgraph/hedera-services/pull/13199

### CODE REVIEW

**Review by poulok — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java [hunk 1]
```diff
@@ -587,11 +588,23 @@ public PlatformComponentBuilder withConsensusEventStream(@NonNull final Consensu
     @NonNull
     public ConsensusEventStream buildConsensusEventStream() {
         if (consensusEventStream == null) {
+
+            // Required for conformity with legacy behavior. This sort of funky logic is normally something
+            // we'd try to move away from, but since we will be removing the CES entirely, it's simpler
+            // to just wait until the entire component disappears.
+            final Address address = blocks.initialState().get().getAddressBook().getAddress(blocks.selfId());
```
Comment (hendrikebbers) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java:595]: are we sure that address is never null? That is a quite long expression

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java [hunk 2]
```diff
@@ -587,11 +588,23 @@ public PlatformComponentBuilder withConsensusEventStream(@NonNull final Consensu
...
+            } else {
+                consensusEventStreamName = String.valueOf(blocks.selfId());
+            }
+
             consensusEventStream = new DefaultConsensusEventStream(
                     blocks.platformContext(),
                     blocks.selfId(),
                     (byte[] data) -> new PlatformSigner(blocks.keysAndCerts()).sign(data),
-                    "" + blocks.selfId().id(),
+                    consensusEventStreamName,
```
Comment (hendrikebbers) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java:607]: It looks to me that it would be quite easy to add a unit tests to the given change.

Comment (cody-littley) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/builder/PlatformComponentBuilder.java:607]: This already merged to develop, this is just a cherry pick. Was developed without tests because this issue is currently causing devops grief -- intent was to get a fix out the door ASAP. I created a ticket to add this test as a follow up. https://github.com/hashgraph/hedera-services/issues/13232

**Review by lpetrovic05 — APPROVED** [review]
