### PR TITLE
fix: Enable NFT Airdrop to distribute multiple serials

### LINKED ISSUE #17409: Airdropping an NFT with multiple serials in one TokenTransferList only sends the first serial
### Description

When we try to send multiple serials of the same NFT in one transaction using a TokenTransferList with a nested array of NftTransfers, the first serial is sent correctly to the receiver, but all the subsequent ones are not. 

The expected behavior is all of them to be sent successfully to the appropriate receiver, not just the first one.

### Steps to reproduce

1. Send multiple serials of the same NFT to different receivers using a TokenTranferList with multiple nested NftTransfer items.
2. Observe the transfers in the transaction
3. Check the owner of the serials other than the first one

### Additional context

_No response_

### Hedera network

_No response_

### Version

0.57.3

### Operating system

None

### PR DESCRIPTION
**Pull request by stoyanov-st**
**Description**:

This PR fixes the limit of one NFT serial Airdropped with a single transaction.
WIth this logic we can now distribute a NFT to multiple receivers.
The configured limits for airdrops are still applied here.

**Related issue(s)**:

Fixes #17409 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java [hunk 1]
```diff
@@ -492,4 +492,108 @@ public Stream<DynamicTest> failToUpdateNFTsMetadata(
...
+                    receiver3.getBalance().andAssert(balance -> balance.hasTokenBalance(nft.name(), 1L)),
+                    nft.serialNo(1L).assertOwnerIs(receiver1),
+                    nft.serialNo(2L).assertOwnerIs(receiver2),
+                    nft.serialNo(3L).assertOwnerIs(receiver3));
+        }));
+    }
+
+    @HapiTest
+    @Order(13)
+    @DisplayName("Cannon Distribute 11 NFTs to multiple accounts")
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:535]: "Cannon" -> "Cannot" typo

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java [hunk 2]
```diff
@@ -492,4 +492,108 @@ public Stream<DynamicTest> failToUpdateNFTsMetadata(
                         .andAssert(txn ->
                                 txn.hasKnownStatuses(CONTRACT_REVERT_EXECUTED, INVALID_TOKEN_NFT_SERIAL_NUMBER)));
     }
+
+    @HapiTest
+    @Order(12)
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:497]: Out of curiosity: What is it about airdrops, or this suite, that these tests must be `@OrderedInIsolation`?  Each individual test looks like it is getting new accounts and tokens injected (or at least that's what I assume those annotations on test method parameters are) so how do they interfere with each other?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java [hunk 3]
```diff
@@ -492,4 +492,108 @@ public Stream<DynamicTest> failToUpdateNFTsMetadata(
...
+    @DisplayName("Distribute NFTs to multiple accounts")
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:498]: Perhaps also a test w/ multiple airdrops but one or more fail?  (I'm not even sure what the behavior of that should be, must be in the HIP though ...)

**Review by david-bakin-sl — COMMENTED** [review]
I think I'd like to see a test with multiple airdrops where one or more (but not all, and not #1 in the list) fail.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 2 above)
Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:497]: Even though we have new tokens and accounts injected the naming logic of the specs is the same e.g. if we have receiver1 used in 2 separate tests getting the balance would most likely result in a race condition (and it did before adding the ordering) as we are accessing them by the name.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 3 above)
Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:498]: I believe we have such tests done or incoming with future PR

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 1 above)
Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java]: Thanks. Fixed

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 2 above)
Comment (david-bakin-sl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:497]: Is there something we could suggest to improve the bdd framework that could make it easier to write tests that didn't have this constraint?  Becuase of course `@Ordered` reduces parallelism in test runs making them take more wall clock time, and `@OrderedInIsolation` is worse.  If the framework could be improved multiple suites, including this one, could benefit, and CI runs would be faster.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 3 above)
Comment (david-bakin-sl) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:498]: Ok.  I would have thought this was a natural place for them, but ok.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 2 above)
Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:497]: I think we need to spend some time to brainstorm this and come up with a solution and adapt all affected suites

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/airdrops/TokenAirdropDecoder.java [hunk 4]
```diff
@@ -99,18 +99,22 @@ private TokenAirdropTransactionBody bodyForAirdrop(
...
-                final var receiver = addressIdConverter.convert(nftAmount.get(NFT_RECEIVER));
-                checkForSystemAccount(receiver);
-                final var isApproval = (boolean) nftAmount.get(NFT_IS_APPROVAL);
-                tokenTransferList.nftTransfers(NftTransfer.newBuilder()
-                        .senderAccountID(sender)
-                        .receiverAccountID(receiver)
-                        .serialNumber(serial)
-                        .isApproval(isApproval)
-                        .build());
+                final var nftTransfersList = new ArrayList<NftTransfer>();
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/airdrops/TokenAirdropDecoder.java:102]: Is it possible to create a unit test for this?  I realize the method is private but it seems we can maybe create tuples that have more than one not

**Review by lukelee-sl — DISMISSED** [review]
LGTM.  Just a comment on an additional test if possible.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/airdrops/TokenAirdropDecoder.java (hunk 4 above)
Comment (stoyanov-st) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/airdrops/TokenAirdropDecoder.java:102]: Added the test.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java (hunk 3 above)
Comment (stoyanov-st) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/airdrops/AirdropSystemContractTest.java:500]: Added the test

**Review by lukelee-sl — APPROVED** [review]
LGTM.  tyvm.
