### PR TITLE
`CryptoUpdate` PreTxnHandler

### LINKED ISSUE #4227: Implement the `UpdateAccount` PreTransactionHandler
We need to implement PreTransactionHandler logic that supports `CryptoUpdateAccount` for signing requirements

Implement the below method in `CryptoPreTransactionHandlerImpl`
```
    @Override
    /** {@inheritDoc} */
    public TransactionMetadata preHandleUpdateAccount(TransactionBody txn) {
        throw new NotImplementedException();
    }

### PR DESCRIPTION
**Pull request by Neeharika-Sompalli**
Fixes #4227 

- Adds `CryptoUpdate` Pre-transaction handler implemntation
- Since the implemntation depends on existing [SignatureWaivers](https://github.com/hashgraph/hedera-services/blob/4227-D-cryptoUpdate-preTxnHdlr/hedera-node/hedera-mono-service/src/main/java/com/hedera/services/sigs/order/SignatureWaivers.java) class , added a placeholder interfaces [SigWaivers](https://github.com/hashgraph/hedera-services/blob/4227-D-cryptoUpdate-preTxnHdlr/hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/SigWaivers.java) in spi, [CryptoSignatureWaivers](https://github.com/hashgraph/hedera-services/blob/4227-D-cryptoUpdate-preTxnHdlr/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java) extending SigWaivers.
- Implementation of `CryptoSignatureWaiversImpl` is not done in this PR , since it depends on moving `EntityNumbers` class to spi.
- Added interfaces for AccountNumbers, FileNumbers  in SPI as [HederaAccountNumbers](https://github.com/hashgraph/hedera-services/blob/4227-D-cryptoUpdate-preTxnHdlr/hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/numbers/HederaAccountNumbers.java), [HederaFileNumbers](https://github.com/hashgraph/hedera-services/blob/4227-D-cryptoUpdate-preTxnHdlr/hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/numbers/HederaFileNumbers.java)
- NOTE : Next PR will move `AccountNumbers`, `FileNumbers` to spi package and adds implementation for `CryptoSignatureWaiversImpl`

### CODE REVIEW

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/PreHandleContext.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+/**
+ * Contextual information needed to perform pre-handle. Currently, provides extra information needed
+ * for signing requirements using {@link SigWaivers} to validate if any account's signature can be
+ * waived it contains
+ *
+ * @param signatureWaivers provides information about signature waiver special cases for some
+ *     transactions
+ */
+public record PreHandleContext(SigWaivers signatureWaivers) {}
```
Comment (rbair23) [inline hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/PreHandleContext.java:26]: Should we check for null and throw?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java [hunk 2]
```diff
@@ -114,8 +116,26 @@ public TransactionMetadata preHandleDeleteAllowances(TransactionBody txn) {
...
+        final var payer = txn.getTransactionID().getAccountID();
+        final var updateAccountId = op.getAccountIDToUpdate();
+        final var meta = new SigTransactionMetadata(accountStore, txn, payer);
+
+        final var newAccountKeyMustSign =
+                !((CryptoSignatureWaivers) ctx.signatureWaivers())
+                        .isNewKeySignatureWaived(txn, payer);
+        final var targetAccountKeyMustSign =
+                !((CryptoSignatureWaivers) ctx.signatureWaivers())
+                        .isTargetAccountSignatureWaived(txn, payer);
```
Comment (rbair23) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java:130]: I'm not liking the cast. I'm also a little confused as to how this works. The `ctx` is created by the application before it calls the service. It needs to know what the right type of signature waiver is that it needs to create. How will it do that?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+package com.hedera.node.app.service.token;
+
+import com.hedera.node.app.spi.SigWaivers;
+import com.hederahashgraph.api.proto.java.AccountID;
+import com.hederahashgraph.api.proto.java.TransactionBody;
+
+/** Signature waivers needed for transactions in {@link CryptoService} */
+public interface CryptoSignatureWaivers extends SigWaivers {
+    /**
+     * Advises if the target account's key must sign a given crypto update. Since, accounts 0.0.2
```
Comment (mhess-swl) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java:25]: Stray comma after 'Since'

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+     * and 0.0.50 can update any non-0.0.2 system accounts with no other signatures. Checks if the
+     * target account being updated by the above accounts.
+     *
+     * @param cryptoUpdateTxn a crypto update transaction
+     * @return whether the target account's key must sign
+     */
+    boolean isTargetAccountSignatureWaived(TransactionBody cryptoUpdateTxn, final AccountID payer);
+
+    /**
+     * Advises if the new key for an account must sign a given crypto update. Since, accounts 0.0.2
```
Comment (mhess-swl) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java:35]: Another stray comma after 'Since'

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java (hunk 2 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java:130]: So, is it better to inject `HederaAccountNumbers` into `PreHandleContext`. So the `CryptoSignatureWaiversImpl` can be constructed in the `preHandleUpdateAccount` method ?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java (hunk 3 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java]: Fixed. Thanks!

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java (hunk 4 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java]: Fixed. Thanks!

**Review by tinker-michaelj — APPROVED** [review]
LGTM

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java [hunk 5]
```diff
@@ -28,15 +28,16 @@ public interface Service {
...
+    PreTransactionHandler createPreTransactionHandler(
+            @NonNull States states, @NonNull PreHandleContext ctx);
 
     /**
      * Creates and returns a new {@link TransactionHandler}
      *
      * @return A new {@link TransactionHandler}
      */
-    default @Nonnull TransactionHandler createTransactionHandler(@Nonnull States states) {
+    default @NonNull TransactionHandler createTransactionHandler(@NonNull States states) {
```
Comment (hendrikebbers) [inline hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java:40]: Please merge develop in your branch since this interfaces have been moved

File: hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/numbers/HederaAccountNumbersTest.java [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+                    }
+
+                    @Override
+                    public long stakingRewardAccount() {
+                        return 801L;
+                    }
+
+                    @Override
+                    public long nodeRewardAccount() {
+                        return 800L;
```
Comment (hendrikebbers) [inline hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/numbers/HederaAccountNumbersTest.java:78]: can you throw an IllegalAccessException in all method that should not be visited by the test?

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+public interface CryptoSignatureWaivers extends SigWaivers {
+    /**
+     * Advises if the target account's key must sign a given crypto update. Since accounts 0.0.2 and
+     * 0.0.50 can update any non-0.0.2 system accounts with no other signatures. Checks if the
+     * target account being updated by the above accounts.
+     *
+     * @param cryptoUpdateTxn a crypto update transaction
+     * @return whether the target account's key must sign
+     */
+    boolean isTargetAccountSignatureWaived(TransactionBody cryptoUpdateTxn, final AccountID payer);
```
Comment (hendrikebbers) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java:32]:
```suggestion
    boolean isTargetAccountSignatureWaived(TransactionBody cryptoUpdateTxn, AccountID payer);
```

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+     * Advises if the new key for an account must sign a given crypto update. Since accounts 0.0.2
+     * and 0.0.50 can update any non-0.0.2 system accounts with no other signatures. Checks if the
+     * target account being updated by the above accounts. When updating the treasury account 0.0.2
+     * key, the new key must also sign the transaction. Checks if the account being updated is
+     * treasury account.
+     *
+     * @param cryptoUpdateTxn a crypto update transaction
+     * @return whether the new key from the transaction must sign
+     */
+    boolean isNewKeySignatureWaived(TransactionBody cryptoUpdateTxn, final AccountID payer);
```
Comment (hendrikebbers) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java:44]:
```suggestion
    boolean isNewKeySignatureWaived(TransactionBody cryptoUpdateTxn, AccountID payer);
```

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java [hunk 9]
```diff
@@ -158,4 +177,15 @@ private TransactionMetadata createAccountSigningMetadata(
         }
         return meta;
     }
+
+    /**
+     * This method is needed for testing until {@link CryptoSignatureWaiversImpl} is implemented.
+     * FUTURE: This method should be removed once {@link CryptoSignatureWaiversImpl} is implemented.
```
Comment (hendrikebbers) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java:183]: Based on that can we add @Depreated(forRemoval=true)

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/services/config/AccountNumbers.java [hunk 10]
```diff
@@ -52,76 +54,87 @@ public AccountNumbers(@CompositeProps PropertySource properties) {
         this.properties = properties;
     }
 
+    @Override
     public long treasury() {
         if (treasury == UNKNOWN_NUMBER) {
```
Comment (hendrikebbers) [inline hedera-node/hedera-mono-service/src/main/java/com/hedera/services/config/AccountNumbers.java:59]: is it ok that the class is not thread safe?

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java (hunk 5 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java:40]: I did merge develop into my branch. But, Service should be in spi right ?

File: hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/numbers/HederaAccountNumbersTest.java (hunk 6 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/numbers/HederaAccountNumbersTest.java:78]: Since this method is inherited , it asks to add exception to base method as well ...

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/numbers/HederaAccountNumbersTest.java:78]: Used `IllegalCallerException` instead as `IllegalAccessException` is not a RunTime exception

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/services/config/AccountNumbers.java (hunk 10 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/services/config/AccountNumbers.java:59]: It will be a singleton class and loaded once at start up.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java (hunk 9 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java:183]: I like this. Thanks Fixed.

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java (hunk 8 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java:44]: Fixed. Thanks !

File: hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java (hunk 7 above)
Comment (Neeharika-Sompalli) [reply hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java:32]: Fixed. Thanks !

File: hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java (hunk 5 above)
Comment (hendrikebbers) [reply hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java:40]: you are right

**Review by hendrikebbers — APPROVED** [review]
