### PR TITLE
fix: 12247 Remove incorrect assert from `reopenFileChannel` (#12665)

### LINKED ISSUE #12247: Unit test failure - `DataFileCollectionTest.merge()`
### Description

`DataFileCollectionTest.merge()` is flaky and needs to be investigated. 

See https://scans.gradle.com/s/6zdhtwz2bmcoo/tests/overview?outcome=FAILED

### Steps to reproduce

Run `DataFileCollectionTest.merge()` and hope for the worst. 

### Additional context

_No response_

### Hedera network

other

### Version

v0.49

### Operating system

None

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This is a cherry-pick of https://github.com/hashgraph/hedera-services/pull/12665

The failure re-occurred on release/0.49 branch, so I decided to backport the fix. 

**Related issue(s)**:

Fixes #12247

### CODE REVIEW

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java [hunk 1]
```diff
@@ -316,10 +318,11 @@ protected void openNewFileChannel(final int index) throws IOException {
      */
     protected void reopenFileChannel(final int index, final FileChannel closedChannel) throws IOException {
         assert index < MAX_FILE_CHANNELS;
-        // May be closedChannel or may be already reopened in a different thread
-        assert fileChannels.get(index) != null;
```
Comment (jsync-swirlds) [inline platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:320]: Just for discussion, would it be reasonable to have an `if (fileChannels.get(index) == null) return;` type of test instead of the assert to shortcut the file channel open/close combination?

**Review by jsync-swirlds — APPROVED** [review]

File: platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java (hunk 1 above)
Comment (imalygin) [reply platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReaderPbj.java:320]: Yes, it would be reasonable to have this kind of check because we don't ever pass `null` value in `closedChannel` parameter.
