### PR TITLE
Isolate token relationship linked-list management in `CommitInterceptor`

### LINKED ISSUE #3240: `TokenCreate` record shows "repeat" auto-association when treasury associated to other tokens
### Description

I created a token `0.0.1003` with treasury `0.0.1001`.

I then created a token `0.0.1004`, also using treasury `0.0.1001`. The record included,
```
automatic_token_associations {
  token_id {
    tokenNum: 1003
  }
  account_id {
    accountNum: 1001
  }
}
automatic_token_associations {
  token_id {
    tokenNum: 1004
  }
  account_id {
    accountNum: 1001
  }
}
```

### Steps to reproduce

Run `TokenCreateSpecs.creationHappyPath()` EET on branch `03240-do-assoc-mgmt-with-interceptor`, it will fail [here](https://github.com/hashgraph/hedera-services/blob/03240-do-assoc-mgmt-with-interceptor/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java#L509).

### Hedera network

other

### Version

v0.25.0

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Related issue(s)**:
- Fixes #3240

**Description**:
- Isolates logic for the `tokenAssociations` linked list management in [the `TokenRelsLinkManager`](https://github.com/hashgraph/hedera-services/blob/03240-do-assoc-mgmt-with-interceptor/hedera-node/src/main/java/com/hedera/services/ledger/interceptors/TokenRelsLinkManager.java#L53).
- Provides the `TokenRelsLinkManager` singleton with the change set that needs updated links via an [interceptor](https://github.com/hashgraph/hedera-services/blob/03240-do-assoc-mgmt-with-interceptor/hedera-node/src/main/java/com/hedera/services/ledger/interceptors/LinkAwareTokenRelsCommitInterceptor.java#L75) on the [`tokenRelsLedger` singleton](https://github.com/hashgraph/hedera-services/blob/03240-do-assoc-mgmt-with-interceptor/hedera-node/src/main/java/com/hedera/services/store/StoresModule.java#L124)---which is now [also bound](https://github.com/hashgraph/hedera-services/blob/03240-do-assoc-mgmt-with-interceptor/hedera-node/src/main/java/com/hedera/services/store/StoresModule.java#L107) as the token associations `BackingStore`.
    * 🗯 This binding is necessary for the interceptor to see changes created via the `TypedTokenStore`!
- Completes implementation of the `TransactionalLedger`/`CommitInterceptor` contract by exposing pending removals in the `EntityChangeSet` as entries with a `null` change set.
- Makes `TransactionalLedger.begin()` safer to use by doing a manual rollback if it is called without a preceding `commit()`/`rollback()`.

_Note:_ also adds a number of missing license headers.

### CODE REVIEW

File: hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java [hunk 1]
```diff
@@ -65,7 +64,6 @@ public class TransferLogic {
 	public static final List<AccountProperty> TOKEN_TRANSFER_SIDE_EFFECTS = List.of(
 			NUM_POSITIVE_BALANCES,
 			NUM_ASSOCIATIONS,
-			HEAD_TOKEN_NUM,
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java:68]: we do need this right ?? for auto associations on transfer

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/TokenRelProperty.java [hunk 2]
```diff
@@ -71,37 +70,4 @@ public Function<MerkleTokenRelStatus, Object> getter() {
 			return MerkleTokenRelStatus::isAutomaticAssociation;
 		}
 	},
-	KEY {
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/TokenRelProperty.java:74]: So we would always need a mutable MerkleTokenRelStatus when ever we want to change the keys ?

File: hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java:68]: Only the `TokenRelsLinkManager` changes this now.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/TokenRelProperty.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/TokenRelProperty.java:74]: True; the `MapValueListUtils` ensure this.

File: hedera-node/src/main/java/com/hedera/services/store/models/Account.java [hunk 3]
```diff
@@ -216,76 +203,53 @@ public void setNumPositiveBalances(final int numPositiveBalances) {
...
 	public List<TokenRelationship> associateWith(
 			final List<Token> tokens,
 			final TypedTokenStore tokenStore,
 			final boolean isAutomaticAssociation,
 			final boolean shouldEnableRelationship,
-			final GlobalDynamicProperties dynamicProperties) {
-		List<TokenRelationship> tokenRelationshipsToPersist = new ArrayList<>();
-
+			final GlobalDynamicProperties dynamicProperties
+	) {
```
Comment (anighanta) [inline hedera-node/src/main/java/com/hedera/services/store/models/Account.java:221]: How are the commit interceptors used now in case of tokenAssociate and tokenDissociate transitionLogics ?

**Review by anighanta — APPROVED** [review]
LGTM.
