### PR TITLE
fix: Fix missing validation in ThrottleAccumulator

### LINKED ISSUE #21052: Fix missing validation in `ThrottleAccumulator`
Currently we are not checking if the `ScheduleCreateTransactionBody ` has a scheduled transaction body in it. This causes a NPE in `ThrottleAccumulator`.

```
2025-09-12 10:24:36.339 ERROR 92   IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field scheduledTransactionBody is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at com.hedera.hapi.node.scheduled.ScheduleCreateTransactionBody.scheduledTransactionBodyOrThrow(ScheduleCreateTransactionBody.java:607)
	at com.hedera.node.app.throttle.ThrottleAccumulator.shouldThrottleScheduleCreate(ThrottleAccumulator.java:500)
	at com.hedera.node.app.throttle.ThrottleAccumulator.shouldThrottleTxn(ThrottleAccumulator.java:468)
	at com.hedera.node.app.throttle.ThrottleAccumulator.checkAndEnforceThrottle(ThrottleAccumulator.java:188)
	at com.hedera.node.app.throttle.SynchronizedThrottleAccumulator.shouldThrottle(SynchronizedThrottleAccumulator.java:59)
	at com.hedera.node.app.workflows.ingest.IngestChecker.checkThrottles(IngestChecker.java:344)
	at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:286)
	at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:235)
	at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:75)
```

**Solution:** 

Add a precheck validation if `ScheduleCreateTransactionBody` has a scheduled transaction body or throttle if there is no scheduled transaction body
```
  if(!op.hasScheduledTransactionBody()){
          // throttle the transaction, if it is not valid
            return true;
        }
```

### PR DESCRIPTION
**Pull request by aderevets**
**Description**:
Currently we are not checking if the ScheduleCreateTransactionBody  has a scheduled transaction body in it. This causes a NPE in ThrottleAccumulator.

```
2025-09-12 10:24:36.339 ERROR 92   IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field scheduledTransactionBody is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at com.hedera.hapi.node.scheduled.ScheduleCreateTransactionBody.scheduledTransactionBodyOrThrow(ScheduleCreateTransactionBody.java:607)
	at com.hedera.node.app.throttle.ThrottleAccumulator.shouldThrottleScheduleCreate(ThrottleAccumulator.java:500)
	at com.hedera.node.app.throttle.ThrottleAccumulator.shouldThrottleTxn(ThrottleAccumulator.java:468)
	at com.hedera.node.app.throttle.ThrottleAccumulator.checkAndEnforceThrottle(ThrottleAccumulator.java:188)
	at com.hedera.node.app.throttle.SynchronizedThrottleAccumulator.shouldThrottle(SynchronizedThrottleAccumulator.java:59)
	at com.hedera.node.app.workflows.ingest.IngestChecker.checkThrottles(IngestChecker.java:344)
	at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:286)
	at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:235)
	at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:75)

```
**Related issue(s)**:

Fixes #21052 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java [hunk 1]
```diff
@@ -622,11 +616,19 @@ private boolean isGasExhausted(
...
             List<ThrottleUsage> throttleUsages) {
-        final int numNfts = op.metadata().size();
+        var txnBody = txnInfo.txBody();
+        if (!txnBody.hasTokenMint()) {
+            return true;
+        }
+        final var tokenMint = txnBody.tokenMint();
+        if (!tokenMint.hasToken()) {
+            return true;
+        }
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: I think this will also change SDK behavior. Instead of `INVALID_TOKEN_ID` we will throw `BUSY` 😇

Comment (aderevets) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: let I change to false to prevent throttling here.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: Then why do we need to check anything here ? We don't need any checks here if we are not throttling

Comment (aderevets) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleAccumulator.java]: Got your point. If return a true here we could not pass to validation part after this code. I reverted this code
