### PR TITLE
Fixed code to pass CryptoDeleteSuite e2e test.

### LINKED ISSUE #8122: Start testing CryptoDeleteSuite
- [ ] deletedAccountCannotBePayer
- [x] canQueryForRecordsWithDeletedPayers
- [x] fundsTransferOnDelete
- [x] cannotDeleteAccountsWithNonzeroTokenBalances
- [x] cannotDeleteAlreadyDeletedAccount
- [x] cannotDeleteAccountWithSameBeneficiary
- [x] cannotDeleteTreasuryAccount

### PR DESCRIPTION
**Pull request by iwsimon**
Fixed code to pass CryptoDeleteSuite e2e test.
Added payer.deleted status check in prehandle and handle.

**Description**:

**Related issue(s)**:

Fixes #8122 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java [hunk 1]
```diff
@@ -317,6 +318,13 @@ private TransactionBody handleUserTransaction(
             } else {
                 feeAccumulator.charge(payer, fees);
                 try {
+                    final var storeFactory = new ReadableStoreFactory(state);
+                    final var accountStore = storeFactory.getStore(ReadableAccountStore.class);
+                    final var payerAccount = accountStore.getAccountById(payer);
+                    if (payerAccount != null && payerAccount.deleted()) {
```
Comment (iwsimon) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: This check might be changed to other lines when #8224 is completed.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java [hunk 2]
```diff
@@ -109,7 +111,8 @@ private HapiSpec deletedAccountCannotBePayer() {
                                 .logged());
     }
 
-    private HapiSpec canQueryForRecordsWithDeletedPayers() {
+    @HapiTest
+    HapiSpec canQueryForRecordsWithDeletedPayers() {
```
Comment (jsync-swirlds) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java:115]: Why did we expand the access modifier for this method (and the one above)l do we actually need to?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java [hunk 3]
```diff
@@ -156,6 +156,9 @@ protected void changeSupply(
         copyToken.totalSupply(newTotalSupply);
         copyTreasuryRel.balance(newTreasuryBalance);
 
+        // also need to update this
```
Comment (jsync-swirlds) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:159]: Can we mark this TODO so we do not lose track?  This seems somewhat important to not forget.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java [hunk 4]
```diff
@@ -74,7 +74,7 @@ public ExpiryMeta resolveCreationAttempt(
         context.attributeValidator().validateExpiry(effectiveExpiry);
 
         // Even if the effective expiry is valid, we still also require any explicit auto-renew period to be valid
-        if (creationMeta.hasAutoRenewPeriod()) {
+        if (creationMeta.hasAutoRenewPeriod() && creationMeta.autoRenewPeriod() != 0) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:77]: Probably should be `>=`, so we're defensive against an accidental negative value.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java (hunk 2 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java]: Accidentally removed. Thanks for catching it. Updated.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java (hunk 3 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:159]: This comment is for the follow line which I added to fix one of the issues in the test. It's not a TODO.

Comment (jsync-swirlds) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:159]: Ahh, it was a bit confusing.
Perhaps a tiny bit more detail (e.g. `We also need to update the Titles count on the copy`) would make the comment clearer.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java [hunk 5]
```diff
@@ -79,7 +80,8 @@ public List<HapiSpec> getSpecsInSuite() {
                 canQueryForRecordsWithDeletedPayers());
     }
 
-    private HapiSpec deletedAccountCannotBePayer() {
+    // @HapiTest, node fee need to be implemented before running this test
+    HapiSpec deletedAccountCannotBePayer() {
```
Comment (jsync-swirlds) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java:84]: This should still be private as well.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java (hunk 4 above)
Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:77]: ExpiryMeta.autoRenewPeriod could have value Long.MIN_VALUE. Here is only skip 0 check.

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java (hunk 5 above)
Comment (iwsimon) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java]: Updated. Thanks.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java (hunk 4 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:77]: Interesting, we allow negative auto renew periods?  Seems like that might cause unexpected issues.  Something to note for later.

**Review by jsync-swirlds — DISMISSED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java [hunk 6]
```diff
@@ -91,7 +91,7 @@ public void validateExpiry(long expiry) {
                 context.configuration().getConfigData(EntitiesConfig.class).maxLifetime();
         final var now = context.consensusNow().getEpochSecond();
         final var expiryGivenMaxLifetime = now + maxEntityLifetime;
-        validateTrue(expiry > now && expiry <= expiryGivenMaxLifetime, INVALID_EXPIRATION_TIME);
+        validateTrue(expiry >= now && expiry <= expiryGivenMaxLifetime, INVALID_EXPIRATION_TIME);
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java:94]: Why would we want to allow an expiry time of now?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java [hunk 7]
```diff
@@ -156,6 +156,9 @@ protected void changeSupply(
         copyToken.totalSupply(newTotalSupply);
         copyTreasuryRel.balance(newTreasuryBalance);
 
+        // We also need to update the Titles count on the copy
+        copyTreasuryAccount.numberTreasuryTitles(treasuryAccount.numberTreasuryTitles() + 1);
```
Comment (mhess-swl) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:160]: This method is only meant to change the supply. Why would we increment the treasury titles on a token burn?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java (hunk 6 above)
Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java:94]: In TokenCreateHandler, when calls context.expiryValidator().resolveCreationAttempt(false, givenExpiryMeta); which calls context.attributeValidator().validateExpiry(effectiveExpiry); This effectiveExpiry is context.consensusNow().getEpochSecond() (=now) if you don't have autoRenewAccount. If you don't add now check here, you will get INVALID_EXPIRATION_TIME, test cannotDeleteTreasuryAccount will fail.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java (hunk 7 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:160]: In CryptoDeleteSuite,  validateFalse(deletedAccount.numberTreasuryTitles() > 0, ACCOUNT_IS_TREASURY); is checking if this is set in test cannotDeleteTreasuryAccount. During token create, if we set the treasury, we need to update this value. It's hard to explain in a couple sentences. This is the the number of tokens for which this account is treasury. This change made the test pass as well.

Comment (mhess-swl) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java:160]: Yes, `numberTreasuryTitles` needs to increase in a token create, so this code should be inside of the token create handler. It shouldn't be in this method because this method is also used for burns

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java (hunk 6 above)
Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java:94]: I agree with @mhess-swl. It is kind of weird to modify this check, which already exists in mono. Can we be sure that none of the dozens of other places that call this method are affected by this change? Is it possible to fix this in `TokenCreateHandler`?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java (hunk 4 above)
Comment (netopyr) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java:77]: Does it make sense to allow an autoRenewPeriod of 0? Maybe the calling code should have set to be `ExpiryMeta.NA` instead.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: This looks like a workaround. We should not use the payer from pre-handle, but re-read it from state in handle and recheck its state. Let's fix it correctly right away. You can go ahead and do it or file an issue and assign it to me.

Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: Updated with getting payer (AccountID) from transaction. payerAccount was from state in handle on line 323.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java (hunk 6 above)
Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java]: Removed the code change to TokenCreateHandler.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java (hunk 7 above)
Comment (iwsimon) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java]: Removed the code change to TokenCreateHandler.

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java (hunk 4 above)
Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java]: Removed the code change to TokenCreateHandler.

**Review by jsync-swirlds — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (mhess-swl) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: Should we also be checking for other special cases? Specifically, deleted contracts and expired accounts

File: hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImplTest.java [hunk 8]
```diff
@@ -103,7 +103,7 @@ void allowsFutureExpiryBeforeMaxLifetime() {
     void rejectsAnyNonFutureExpiry() {
         final var now = 1_234_567L;
         given(context.consensusNow()).willReturn(Instant.ofEpochSecond(now));
-        assertThatThrownBy(() -> subject.validateExpiry(now))
+        assertThatThrownBy(() -> subject.validateExpiry(now - 1))
```
Comment (mhess-swl) [inline hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImplTest.java:106]: Since the expiry change was moved, would this still pass with `now`?

Comment (iwsimon) [reply hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImplTest.java]: Yes，changed it back to the original.

**Review by jsync-swirlds — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java (hunk 1 above)
Comment (iwsimon) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: This PAYER_ACCOUNT_DELETED is specific to payerAccount. If we have to check deleted contracts and expired account here, we can address it in another issue.  I will let @netopyr comment on deleted contracts and expired account.

Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: There is a whole facility for expired items that needs to be added still.  It would be outside the scope of this PR.

Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java:324]: Is there more to do to detect a deleted contract?

I have only a very basic understanding of how expiration will work. Let's discuss it today.

**Review by netopyr — APPROVED** [review]
LGTM in regards to `hedera-app`
