### PR TITLE
fix: only skip event from missing creator

### LINKED ISSUE #14607: Removed node events should be skipped, not rounds
### Description

Skipping events from a missing node should be isolated to events, not rounds. (Even if in practice a skipped event implies the whole round will be skipped.)

### Steps to reproduce

Run [this embedded test](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/DuplicateManagementTest.java#L158), observe that there is no `endRound()` call in the dynamic context of `handleConsensusRound()` for the transaction submitted with a missing node id. 

### Additional context

_No response_

### Hedera network

other

### Version

develop

### Operating system

None

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #14607

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/HgcaaLogValidator.java [hunk 1]
```diff
@@ -55,6 +55,8 @@ private static class ProblemTracker {
         private static final List<List<String>> PROBLEM_PATTERNS_TO_IGNORE = List.of(
                 List.of("not in the address book"),
                 List.of("Specified TLS cert", "doesn't exist"),
+                // Stopping an embedded node can interrupt signature verification of background traffic
+                List.of("Interrupted while waiting for signature verification"),
```
Comment (david-bakin-sl) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/support/validators/HgcaaLogValidator.java:59]: Huh, so that's an example of when and where you see `InterruptedException`.

**Review by david-bakin-sl — APPROVED** [review]
LGTM

**Review by iwsimon — APPROVED** [review]
LGTM. Thanks @tinker-michaelj

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @tinker-michaelj
