### PR TITLE
Check for `null` bytecode in traceability migration

### LINKED ISSUE #3922: NPE with contract sidecars v0.30.0-alpha.2 prevents starting of platform
### Description

Attempting migration testing of v0.29.2 => v0.30.0-alpha.2 and receive this error on startup:

```2022-09-12 21:17:45.802 ERROR 162  ServicesTxnManager - Possibly CATASTROPHIC failure in txn processing :: signedTransactionBytes: "\n\201\002\n\022\n\f\b\302\303\376\230\006\020\305\334\205\227\002\022\002\030X\022\002\030\t\030\200\224\353\334\003\"\002\bx2]1663017423571 Monitor topic.ping on staging-sm-monitor-hedera-mirror-monitor-76bb785567-b88zs\302\001}\n,1663017423571 Mirror node created test topic\022\"\022 {\002\355=L\315\263m\315\2345|\334vI\324XI\225\322t\266\f\337\225\271S\226\302\375\344\372\032\"\022 {\002\355=L\315\263m\315\2345|\334vI\324XI\225\322t\266\f\337\225\271S\226\302\375\344\3722\005\b\200\316\332\003\022f\nd\n {\002\355=L\315\263m\315\2345|\334vI\324XI\225\322t\266\f\337\225\271S\226\302\375\344\372\032@\311\355\262\207\201\323\rY\332\360\331mJ\313\304\250\312\237\244\250\026\366\266U\262\231\371\224\334\231\216\372U.27\354\355\203Rp\211(\370|\035\314L\345\233\351z\352\2068\016\365\242V\323\246\210\373\t"
 ==>> --- ACCOUNTS ---
{}
--- TOKEN RELATIONSHIPS ---
{}
--- NFTS ---
{}
--- TOKENS ---
{} ==>>
java.lang.NullPointerException: Cannot invoke "org.apache.tuweni.bytes.Bytes.toArrayUnsafe()" because "runtimeCode" is null
	at com.hedera.services.state.migration.MigrationRecordsManager.generateMigrationBytecodeSidecarFor(MigrationRecordsManager.java:357) ~[?:?]
	at com.hedera.services.state.migration.MigrationRecordsManager.lambda$publishTraceabilityMigrationRecords$3(MigrationRecordsManager.java:324) ~[?:?]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at com.hedera.services.state.migration.MigrationRecordsManager.publishTraceabilityMigrationRecords(MigrationRecordsManager.java:316) ~[?:?]
	at com.hedera.services.state.migration.MigrationRecordsManager.attemptToPublishTraceabilityMigrationRecords(MigrationRecordsManager.java:294) ~[?:?]
	at com.hedera.services.state.migration.MigrationRecordsManager.publishMigrationRecords(MigrationRecordsManager.java:155) ~[?:?]
	at com.hedera.services.state.logic.ServicesTxnManager.process(ServicesTxnManager.java:101) ~[?:?]
	at com.hedera.services.state.logic.StandardProcessLogic.doProcess(StandardProcessLogic.java:152) ~[?:?]
	at com.hedera.services.state.logic.StandardProcessLogic.incorporateConsensusTxn(StandardProcessLogic.java:99) ~[?:?]
	at com.hedera.services.txns.ProcessLogic.lambda$incorporateConsensus$0(ProcessLogic.java:39) ~[?:?]
	at com.swirlds.common.system.Round.forEachEventTransaction(Round.java:80) ~[swirlds-common-0.30.0-alpha.0.jar:?]
	at com.hedera.services.txns.ProcessLogic.incorporateConsensus(ProcessLogic.java:38) ~[?:?]
	at com.hedera.services.ServicesState.handleConsensusRound(ServicesState.java:216) ~[?:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:180) ~[swirlds-platform-core-0.30.0-alpha.0.jar:?]
	at com.swirlds.platform.state.SwirldStateManagerDouble.handleConsensusRound(SwirldStateManagerDouble.java:154) ~[swirlds-platform-core-0.30.0-alpha.0.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:311) ~[swirlds-platform-core-0.30.0-alpha.0.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.waitForItem(QueueThreadImpl.java:249) ~[swirlds-common-0.30.0-alpha.0.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:229) ~[swirlds-common-0.30.0-alpha.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:573) ~[swirlds-common-0.30.0-alpha.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:204) ~[swirlds-common-0.30.0-alpha.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2022-09-12 21:17:45.839 INFO  60   CurrentRecordStreamType - Record stream file header is [6, 0, 30, 0]```

The platform is expected to go to ACTIVE and start servicing requests. 

### Steps to reproduce

1. Run a v0.29.2 network with basic bootstrap.properties
2. Upgrade to v0.30.0-alpha.2 with ```hedera.recordStream.enableTraceabilityMigration=true
contracts.sidecars=CONTRACT_STATE_CHANGE,CONTRACT_BYTECODE,CONTRACT_ACTION``` in the bootstrap.properties
3. Instead of ACTIVE, two of the nodes in a 7 node network receive NPE error as above. 

### Additional context

_No response_

### Hedera network

other

### Version

v0.30.0-alpha.2

### Operating system

Linux

### PR DESCRIPTION
**Pull request by dimitar-dinev**
Signed-off-by: Dimitar Dinev <mitkojc@gmail.com>

**Description**:

* Changes traceability migration logic in `MigrationRecordsManager` to check for `null` bytecode for a contract and not export any sidecars in such cases.

**Related issue(s)**:

Fixes #3922

### CODE REVIEW

**Review by stoqnkpL — COMMENTED** [review]
LGTM. 
However, I have some concerns that we may still have a problem if some of the nodes have bytecode saved in state for given contracts, and some of the nodes don't. Also, we can't figure out why contracts would exist without any bytecode related to them stored in state.

File: hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java [hunk 1]
```diff
@@ -580,6 +580,37 @@ void traceabilityMigrationDoesNotAddStateChangesWhenSmartContractDoesNotHaveAnyS
                 sidecarRecords.build());
     }
 
+    @Test
+    void traceabilityMigrationDoesNotCreateMigrationRecordsForContractWithoutBytecodeInState() {
+        given(consensusTimeTracker.unlimitedPreceding()).willReturn(true);
+        given(networkCtx.areMigrationRecordsStreamed()).willReturn(false);
+        given(networkCtx.consensusTimeOfLastHandledTxn()).willReturn(now);
+        MigrationRecordsManager.setExpiryJustEnabled(false);
+        given(txnAccessor.getFunction()).willReturn(HederaFunctionality.ConsensusCreateTopic);
```
Comment (Nana-EC) [inline hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java:589]: Should this not be for Contract related transaction?
```suggestion
        given(txnAccessor.getFunction()).willReturn(HederaFunctionality.ContractCreate);
```

File: hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java [hunk 2]
```diff
@@ -580,6 +580,37 @@ void traceabilityMigrationDoesNotAddStateChangesWhenSmartContractDoesNotHaveAnyS
                 sidecarRecords.build());
     }
 
+    @Test
+    void traceabilityMigrationDoesNotCreateMigrationRecordsForContractWithoutBytecodeInState() {
```
Comment (Nana-EC) [inline hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java:584]: Q: doesn't this need a test case for the null runtime_bytecode check added?

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Missing coverage

File: hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java (hunk 1 above)
Comment (dimitar-dinev) [reply hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java:589]: The traceability migration is triggered only by a non-contract related transaction that changes state, i.e. all except `ContractCall`, `ContractCreate`, `EthereumTransaction`, since they themselves will have sidecars generated from their execution. That is why the transaction in the test is set as `ConsensusCreateTopic`.

We have [separate tests](https://github.com/hashgraph/hedera-services/blob/7140ff130efad054ac35d0f130f5364ed052d645/hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java#L234-L280)that verify that these 3 transactions do not trigger the migration.

File: hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java (hunk 2 above)
Comment (dimitar-dinev) [reply hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java:584]: Correct, it was just that the `null` return of [`entityAccess.fethCodeIfPresent()` was implicit by the mock.](https://github.com/hashgraph/hedera-services/blob/7140ff130efad054ac35d0f130f5364ed052d645/hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java#L360-L363)

Added    

```
given(entityAccess.fetchCodeIfPresent(contractEntityNum.toGrpcAccountId()))
                .willReturn(null);
```

for better clarity.

**Review by Nana-EC — APPROVED** [review]
LG, but please get a sign off from a Services engineer given the context of the causing bug

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM. Will let @tinker-michaelj  also have a look

**Review by tinker-michaelj — APPROVED** [review]
LGTM
