### PR TITLE
Fix flaky preconsensus event stream test

### LINKED ISSUE #5838: Review hedera-util-service for problems following merge from develop

### PR DESCRIPTION
**Pull request by cody-littley**
Closes #5838

### CODE REVIEW

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java [hunk 1]
```diff
@@ -134,13 +127,22 @@ void standardOperationTest() throws IOException, InterruptedException {
...
+            final EventImpl event = iterator.next();
+
             sequencer.assignStreamSequenceNumber(event);
 
             minimumGenerationNonAncient =
                     Math.max(minimumGenerationNonAncient, event.getGeneration() - generationsUntilAncient);
             writer.setMinimumGenerationNonAncient(minimumGenerationNonAncient);
 
+            if (event.getGeneration() < minimumGenerationNonAncient) {
+                // Although it's not common, it's actually possible that the generator will generate
```
Comment (alittley) [inline platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java:141]: Would it make sense to extend the functionality of the generator, to be able to specify min generation?

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java (hunk 1 above)
Comment (cody-littley) [reply platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java:141]: The main problem with that strategy is that the minimum generation non-ancient increases over time and is tracked externally to the generator, meaning that the generator has no knowledge of it.

**Review by edward-swirldslabs — APPROVED** [review]
