### PR TITLE
5383: IOException during warm() call

### LINKED ISSUE #5383: `IOException` during `warm()` call
Application makes multiple `warm()` calls from tasks submitted to a thread pool. Occasionally, the following exception can be seen in the log:

> 2023-02-06 23:29:42.640 79761    WARN  EXCEPTION        <pool-4-thread-7> DataFileCollection: Store [tokenRelStore:internalHashes] had IOException while trying to read key [4] at offset [224] from file [202257] on retry [0]. Current files are [[143776, 202249, 202250, 202251, 202252, 202253, 202254, 202255, 202256, 202257]], validKeyRange=(0,199432530), storeDir=[/ssd/HEDERA/data/saved/swirlds-tmp/1-jasperdb-tokenRelStore/internalHashStoreDisk]
java.io.IOException: Got a data location from index for a file that doesn't exist. dataLocation={202257,224} fileIndex=202257 validKeyRange=(0,199432530)
currentIndexedFileList=[143776, 202249, 202250, 202251, 202252, 202253, 202254, 202255, 202256]
        at com.swirlds.jasperdb.files.DataFileCollection.readDataItem(DataFileCollection.java:593) ~[swirlds-jasperdb-0.35.0.jar:?]
        at com.swirlds.jasperdb.files.DataFileCollection.readDataItemUsingIndex(DataFileCollection.java:662) ~[swirlds-jasperdb-0.35.0.jar:?]
        at com.swirlds.jasperdb.files.MemoryIndexDiskKeyValueStore.get(MemoryIndexDiskKeyValueStore.java:277) ~[swirlds-jasperdb-0.35.0.jar:?]
        at com.swirlds.jasperdb.VirtualDataSourceJasperDB.loadInternalRecord(VirtualDataSourceJasperDB.java:867) ~[swirlds-jasperdb-0.35.0.jar:?]
        at com.swirlds.jasperdb.VirtualDataSourceJasperDB.warmInternalRecord(VirtualDataSourceJasperDB.java:879) ~[swirlds-jasperdb-0.35.0.jar:?]
        at com.swirlds.virtualmap.internal.merkle.RecordAccessorImpl.warmInternalRecord(RecordAccessorImpl.java:138) ~[swirlds-virtualmap-0.35.0.jar:?]
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.warmInternalNodesForLeaf(VirtualRootNode.java:1335) ~[swirlds-virtualmap-0.35.0.jar:?]
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.warm(VirtualRootNode.java:1312) ~[swirlds-virtualmap-0.35.0.jar:?]
        at com.swirlds.virtualmap.VirtualMap.warm(VirtualMap.java:512) ~[swirlds-virtualmap-0.35.0.jar:?]
        at com.hedera.node.app.service.mono.sigs.order.MapWarmer.lambda$newTokenRunnable$3(MapWarmer.java:140) ~[hedera-mono-service-0.34.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

The exception is due to accessing a stale version of a `VirtualMap`:
-  a warmup task accesses the current copy of a `VirtualMap` and stores it in a local variable, `vmap`
- it then calls `vmap.get()` once and `vmap.warm()` twice
- somewhere between the calls, the map is released and gets merged/flushed
- a `warm()` call does not find the key in `VirtualNodeCache` (its `fastCopyVersion` is now obsolete) and tries to load the key from the database
- the database is in the middle of another flush and updates the index for the key
- using the newly updated index to read the record leads to the exception above

Making each warmup task reserve and release a reference to the `VirtualMap` is going to be expensive and intrusive (may keep copies of VirtualMap in memory for longer than needs be).

`warm()` implementation may immediately return if the current copy is immutable: there is little benefit in warming up a key that has already been used (whether warming up path hashes may still be useful is uncertain). Without a guarantee provided by copy reservation, there remains a probability, however small, of getting the exception even with that check. A failed warm() call is harmless but the exception is reported in the log and creates unnecessary noise.

Another possible approach is to fix database so that newly created files (from flush and compaction) are immediately readable. That's a more generic robustness fix that would cover the scenario at hand as well.

### PR DESCRIPTION
**Pull request by OlegMazurov**
Accessing hashes before they are computed causes exceptions in the database.
[Partially?] fixes #5383.

### CODE REVIEW

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java [hunk 1]
```diff
@@ -1479,27 +1479,13 @@ public void endLearnerReconnect() {
...
-
-        // Warm node hashes for all siblings on the path to root.
-        // Those are used when rehashing the tree due to a changed leaf.
-        for (long path = leafRecord.getPath(); path > 0; path = getParentPath(path)) {
-            final long siblingPath = getSiblingPath(path);
-            if (siblingPath != INVALID_PATH) {
-                records.findHash(siblingPath);
-            }
-        }
+        records.findLeafRecord(key, false);
```
Comment (jsync-swirlds) [inline platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:1488]: We should watch this in testing.  It's very possible that the JIT will remove this call entirely when this method is compiled because the result is not used and the call lacks detectable side effects.

**Review by jsync-swirlds — APPROVED** [review]

**Review by artemananiev — APPROVED** [review]

File: platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java (hunk 1 above)
Comment (OlegMazurov) [reply platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java:1488]: I'll verify the effect of this call as well as that of the removed part with further benchmarking.
