### PR TITLE
fix: fix some sonar bugs and suppress others

### LINKED ISSUE #9898: Fix bugs reported by Sonar
Sonar is reporting several bugs that we need to take a look at.

### PR DESCRIPTION
**Pull request by povolev15**
Fix solar bugs and suppress some
https://sonarcloud.io/project/issues?cleanCodeAttributeCategories=INTENTIONAL&resolved=false&sinceLeakPeriod=true&types=BUG&id=com.hedera.hashgraph%3Ahedera-services&open=AYuRicFHeU6avJIOCgmy

**Related issue(s)**:

Fixes #9898

### CODE REVIEW

**Review by edward-swirldslabs — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java [hunk 1]
```diff
@@ -179,9 +179,6 @@ public FeeCalculator createFeeCalculator(
         // If it is not known, that is, if we have no fee data for that transaction, then we MUST NOT execute that
         // transaction! We will not be able to charge appropriately for it.
         final var feeData = getFeeData(functionality, consensusTime, subType);
-        if (feeData == null) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java:182]: Would it be better to check against DEFAULT_FEE_DATA, rather than remove this check entirely?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java [hunk 2]
```diff
@@ -221,9 +221,6 @@ private long estimateAdditionalCosts(
     private long estimatedGasPriceInTinybars(
             @NonNull final HederaFunctionality functionality, @NonNull final Instant consensusTime) {
         final var feeData = feeManager.getFeeData(functionality, consensusTime, SubType.DEFAULT);
-        if (feeData == null) {
```
Comment (jsync-swirlds) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java:224]: Would it be better to check against DEFAULT_FEE_DATA, rather than remove this check entirely?

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java [hunk 3]
```diff
@@ -243,6 +243,7 @@ private record Counters(@NonNull ObjectCounter onRamp, @NonNull ObjectCounter of
      * @param outerCounter the counter provided by the outer scope, or null if not provided
      * @return the combined counter, or a no op counter if both are null
      */
+    @SuppressWarnings("java:S6416")
```
[the remark this answers is not in the document]
Comment (povolev15) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java:246]: Screenshot 2023-12-05 at 8 37 19 AM

It is inside as you can see on the screenshot

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java (hunk 1 above)
Comment (povolev15) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java:182]: the getFeeData will return the DEFAULT_FEE_DATA thats why I don't need it here. it  cannot be null

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java (hunk 2 above)
Comment (povolev15) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java:224]: sam here

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/InProcessHapiTestNode.java [hunk 4]
```diff
@@ -268,15 +269,17 @@ public void clearState() {
...
+        if (Files.exists(saved)) {
+            try {
+                paths = Files.walk(saved);
+                paths.sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(File::delete);
+
+            } catch (IOException e) {
+                throw new RuntimeException("Could not delete saved state " + saved, e);
+            } finally {
+                if (paths != null) paths.close();
             }
```
Comment (jsync-swirlds) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/InProcessHapiTestNode.java:282]: Try this:
```suggestion
            try(paths = Files.walk(saved)) {
               
 paths.sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(File::delete);
            } catch (IOException e) {
                throw new RuntimeException("Could not delete saved state " + saved, e);
            }
```

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (edward-swirldslabs) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java:246]: Approved.  We must not be running with the same sonar rules at play, odd.

**Review by edward-swirldslabs — APPROVED** [review]

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java [hunk 5]
```diff
@@ -284,15 +285,16 @@ public void clearState() {
...
-                        .map(Path::toFile)
-                        .forEach(File::delete);
+                paths = Files.walk(saved);
+                paths.sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(File::delete);
             }
         } catch (IOException e) {
             throw new RuntimeException("Could not delete saved state " + saved, e);
+        } finally {
+            if (paths != null) paths.close();
         }
```
Comment (jsync-swirlds) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java:298]: Try this (github won't let me do a suggestion here):
```java
        if (Files.exists(saved)) {
            try(paths = Files.walk(saved)) {
                paths.sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(File::delete);
            } catch (IOException e) {
                throw new RuntimeException("Could not delete saved state " + saved, e);
            }
        }
```

Comment (povolev15) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java:298]: done thanks

**Review by jsync-swirlds — DISMISSED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java [hunk 6]
```diff
@@ -83,6 +83,7 @@ public FullResult computeFully(@NonNull final Bytes input, @NonNull final Messag
         return resultOfExecuting(attempt, call, input, frame);
     }
 
+    @SuppressWarnings({"java:S2637", "java:S2259"}) // this function is going to be refactored soon.
```
Comment (kimbor) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java:86]: Is there a ticket out there to refactor it? You should include the ticket number and a @todo tag

**Review by tinker-michaelj — APPROVED** [review]
LGTM

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java (hunk 6 above)
Comment (povolev15) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java:86]: @tinker-michaelj told me he is going to do a major refactoring during the last 3 weeks of Decmeber for smart contracts he is aware about it. That's why I didn't raise a ticket.

**Review by Nana-EC — DISMISSED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java (hunk 2 above)
Comment (jsync-swirlds) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java:224]: As we discussed, this appears to be a case of mismatch between intent-in-code and intent-in-requirements.  The topic will be brought up with the prior author(s) to determine which path is actually correct (default fees will be charged in some cases, or the lack of explicit fee definitions will fail the transaction).  Additional changes are necessary in either case.

**Review by jsync-swirlds — APPROVED** [review]

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java (hunk 1 above)
Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java:182]: This is a leftover from a fix we did a while ago. If no fee data is available, we must not fail but use the default instead. (One could question if this is the desired behavior, but it is what mono does.)

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java [hunk 7]
```diff
@@ -390,6 +390,8 @@ private Fees cryptoUpdateFees(
         final var keySize = op.hasKey() ? getAccountKeyStorageSize(fromPbj(op.key())) : 0L;
         final var baseSize = baseSizeOf(op, keySize);
         final var newMemoSize = op.memoOrElse("").getBytes(StandardCharsets.UTF_8).length;
+
+        @SuppressWarnings("java:S2259") // account cannot be null after the condition
```
Comment (netopyr) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:394]: Can `account.memo()` be `null`?

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java [hunk 8]
```diff
@@ -63,7 +63,7 @@ private record Entry(HederaFunctionality function, SubType subType) {}
 
     private static final FeeComponents DEFAULT_FEE_COMPONENTS =
             FeeComponents.newBuilder().min(DEFAULT_FEE).max(DEFAULT_FEE).build();
-    private static final FeeData DEFAULT_FEE_DATA = FeeData.newBuilder()
+    public static final FeeData DEFAULT_FEE_DATA = FeeData.newBuilder()
```
Comment (netopyr) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java:66]: Why is this public now?

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java [hunk 9]
```diff
@@ -332,6 +330,7 @@ private String getClasspath() {
                 .collect(Collectors.joining(":"));
     }
 
+    @SuppressWarnings("java:S2142")
```
Comment (netopyr) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java:333]: Can you please add a comment on which warning we are suppressing here?

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SystemExitUtils.java [hunk 10]
```diff
@@ -41,6 +41,7 @@ private SystemExitUtils() {}
      * @param message          a message to log, if not null
      * @param haltRuntime      whether to halt the java runtime or not
      */
+    @SuppressWarnings("java:S2583")
```
Comment (netopyr) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SystemExitUtils.java:44]: Can you please add a comment on which warning we are suppressing here?

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java (hunk 3 above)
Comment (netopyr) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java:246]: Can you please add a comment on which warning we are suppressing here?

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java [hunk 11]
```diff
@@ -541,6 +541,7 @@ public static SecureRandom getNonDetRandom() {
      * 		the current configuration
      * @return a map of KeysAndCerts objects, one for each node
      */
+    @SuppressWarnings("java:S2142")
```
Comment (netopyr) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java:544]: Can you please add a comment on which warning we are suppressing here?

**Review by netopyr — CHANGES_REQUESTED** [review]
If it is not clear from the code, we should have a comment that explains what kind of warning we are suppressing (and ideally an explanation why the warning can be ignored).

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java (hunk 7 above)
Comment (povolev15) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:394]: as I see it cannot
public String memoOrElse(@NonNull final String defaultValue) {
        return hasMemo() ? memo : defaultValue;
    }

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java (hunk 8 above)
Comment (povolev15) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java:66]: revert it back

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java (hunk 9 above)
Comment (povolev15) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java:333]: done sure

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java (hunk 11 above)
Comment (povolev15) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java:544]: Just spoke with @cody-littley. He proposed we will not add any suppress on that class just mark it as not fix on the Sonar side.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SystemExitUtils.java (hunk 10 above)
Comment (povolev15) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SystemExitUtils.java:44]: fixed and removed the supress

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java (hunk 3 above)
Comment (povolev15) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java:246]: Just spoke with @cody-littley. He proposed we will not add any suppress on that class just mark it as not fix on the Sonar side.

**Review by edward-swirldslabs — APPROVED** [review]

**Review by edward-swirldslabs — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by jsync-swirlds — APPROVED** [review]

**Review by anthony-swirldslabs — APPROVED** [review]

**Review by netopyr — CHANGES_REQUESTED** [review]

**Review by netopyr — DISMISSED** [review]

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java (hunk 7 above)
Comment (povolev15) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java:394]: fixed it thank you

**Review by tinker-michaelj — APPROVED** [review]
LGTM!

**Review by timo0 — APPROVED** [review]
