### PR TITLE
fix: log4j initialization in 'test-client' test runs

### LINKED ISSUE #19786: Test Logs Not Properly Segmented in IDE and CI After gradle configuration change
**Summary**:
After applying the recent fix related to Log4j configuration, we are experiencing issues with how test logs are displayed both in the IDE and in the CI pipeline.
Current Behavior:
	•	When running tests in the IDE, logs are no longer segmented by individual test. Instead, all logs are grouped together, making it difficult to debug specific tests. 

Image
Image

	•	In the CI pipeline, clicking on a failing test loads the entire log file (e.g., 68,000+ lines) instead of just the relevant test output. This makes it very hard to identify the root cause of test failures.

https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/15735056815/job/44347333437?pr=19767

### PR DESCRIPTION
**Pull request by jjohannes**
**Description**:

This fixes log4j initialization in `test-client` tests to have the tests run on the `--module-path` with correct log output segmentation.

It is required due to a bug, or design flaw, in Gradle. The root cause is that Gradle itself uses SLF4J for logging. If you have LOG4J on the module path, things may become "tricky". Most of the time it works due to some elaborated classloading (or hacks) in Gradle.
In our case, we have the `log4j-slf4j2-impl` bride on the module path to bridge the logging of libraries that use SLF4J into our LOG4J logging world. However, the bridge is loaded early when Gradle itself does logging via SLF4J. This then causes a partial initialization of LOG4J itself which can lead to some state being initialized too early.
In essence, there is code in LOG4J that reads (and remembers) the current `System.out` stream and then there is code in Gradle that modifies `System.out`. If this runs in the wrong order, we get the effect described in #19786.

By choosing a custom name for the XML config file and loading it explicitly inside JUnit code, we postpone the initialization to a point where Gradle has completed the `System.out` modification.

For more detail, see the Gradle bug report: https://github.com/gradle/gradle/issues/36861

**Related issue(s)**:

Fixes #19786

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/hip1313/Hip1313EnabledTest.java [hunk 1]
```diff
@@ -712,7 +713,8 @@ private static VisibleItemsValidator feeMultiplierValidator(
 
     private static ByteString simpleFeesWithoutCryptoCreatePricingCurve() {
         try {
-            final JsonNode root = MAPPER.readTree(TxnUtils.resourceAsString("genesis/simpleFeesSchedules.json"));
+            final JsonNode root =
+                    MAPPER.readTree(V0490FileSchema.loadResourceInPackage("genesis/simpleFeesSchedules.json"));
```
Comment (jjohannes) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/hip1313/Hip1313EnabledTest.java:717]: `genesis` is treated as a private package. Resources can only be loaded from code within the module that owns the package (`com.hedera.node.app.service.file.impl`).

The code here was introduced since we disabled module path execution and thus these issues were not exposed by the tests.

For reference, see earlier adjustments in this area: #19088

File: hedera-node/test-clients/src/main/java/module-info.java [hunk 2]
```diff
@@ -83,6 +83,7 @@
     requires com.hedera.node.app.service.contract;
     requires com.hedera.node.app.service.entityid.impl;
     requires com.hedera.node.app.service.entityid;
+    requires com.hedera.node.app.service.file.impl;
```
Comment (jjohannes) [inline hedera-node/test-clients/src/main/java/module-info.java:86]: If we keep the fix for loading `genesis/simpleFeesSchedules.json` as proposed above, it is consequential that the module is now explicitly required as we load a resource directly from that module.

This was a hidden direct requirement before.

**Review by ibankov — APPROVED** [review]
LGTM, ty @jjohannes
