### PR TITLE
fix(node-rewards): require PUBLISH API on BlockNodeEndpoint for reward eligibility

### LINKED ISSUE #23968: (HIP-1357) Block node rewards
For HIP-1357, we'll want to:
- [ ] Ensure there are `@HapiTest` DSL "verbs" to do convenient CRUD operations for registered block nodes.
- [ ] Add `@Tag(INTEGRATION)` `@HapiTest`s that assert expected payments across the full matrix of node reward eligibility scenarios (via a reusable net-of-normal-rewards assertion pattern):
  - [ ] Inactive, no registered block node
  - [ ] Inactive, one registered block node
  - [ ] Inactive, multiple registered block nodes
  - [ ] Active, no registered block node
  - [ ] Active, one registered block node
  - [ ] Active, multiple registered block nodes
- [ ] Implement extra payments for `Node`s w/ registered block nodes.

### PR DESCRIPTION
**Pull request by viniciusjssouza**
Enhances the `isBlockNodeType` method to ensure BlockNodes are eligible only if their API supports the `PUBLISH` type. Introduces a new test case to verify behavior for nodes with non-publishable endpoints.

 ### Description:
                                                                                                                                                                                                                                                                                                                    
  Restrict block node reward eligibility to registered nodes exposing a PUBLISH API endpoint (HIP-1357).                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                    
  * Update isBlockNodeType to require BlockNodeEndpoint with endpoint_api == PUBLISH instead of only checking hasBlockNode();                                                                                                                                                                                       
  * Set BlockNodeApi.PUBLISH on test helper givenRegisteredBlockNode to match the new condition;                                                                                                                                                                                                                    
  * Add test for a block node with a non-PUBLISH API (STATUS) that must not be eligible;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    
  ### Related issue(s):                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                    
  Fixes #23968                                                                                                                                                                                                                                                                                                      
                                                            
  ### Notes for reviewer:

  The previous condition (hasBlockNode()) accepted any BlockNodeEndpoint regardless of its API type. Per the updated HIP, only nodes with a PUBLISH endpoint should qualify for block node rewards.                                                                                                                 
   
  ### Checklist:                                                                                                                                                                                                                                                                                                    
                                                            
  - [x] Documented (Code comments, README, etc.)
  - [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java [hunk 1]
```diff
@@ -584,10 +584,14 @@ Set<Long> findBlockNodeEligibleNodeIds(
...
     /**
-     * Returns {@code true} if the given registered node has at least one Block Node service endpoint.
+     * Returns {@code true} if the given registered node has at least one Block Node service endpoint
+     * with a {@link RegisteredServiceEndpoint.BlockNodeEndpoint.BlockNodeApi#PUBLISH PUBLISH} API.
      */
     private static boolean isBlockNodeType(@NonNull final RegisteredNode registeredNode) {
-        return registeredNode.serviceEndpoint().stream().anyMatch(RegisteredServiceEndpoint::hasBlockNode);
+        return registeredNode.serviceEndpoint().stream()
+                .anyMatch(endpoint -> endpoint.hasBlockNode()
+                        && requireNonNull(endpoint.blockNode()).endpointApi()
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/NodeRewardManager.java]: nit: Instead of requireNonNull, you can do `endpoint.blockNodeOrThrow()` after checking `hasBlockNode`

**Comment by andrewb1269** [comment]
Merged. Mirror PR #24671 passed all checks.
