### PR TITLE
fix: Fix generated metric names

### LINKED ISSUE #11417: Fix metrics name
Some of our metric names are assembled during runtime and were missed during the name cleanup and need to be fixed.

### PR DESCRIPTION
**Pull request by netopyr**
This PR fixes metric names that are generated.

Closes #11417

### CODE REVIEW

**Review by iwsimon — APPROVED** [review]
LGTM

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! Thanks @netopyr

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java [hunk 1]
```diff
@@ -185,7 +185,7 @@ public void invoke(
             @NonNull final Metrics metrics,
             @NonNull final String nameTemplate,
             @NonNull final String descriptionTemplate) {
-        final var baseName = serviceName + "/" + methodName;
+        final var baseName = serviceName + ":" + methodName;
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java:188]: Why do we need this ? Because only "/" is not an acceptable character ?

Comment (Neeharika-Sompalli) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java:188]: Also don't we need to change lines 
```
private static final String SPEEDOMETER_HANDLED_NAME_TPL = "%sHdl/sec";
private static final String SPEEDOMETER_RECEIVED_NAME_TPL = "%sRcv/sec";
```

Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java:188]: Yes. Prometheus is very strict and allows only alphanumeric characters plus ':' and '_'.

Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java:188]: I think you are looking at outdated code. This has already been fixed recently.

Comment (Neeharika-Sompalli) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/MethodBase.java:188]: Ah yes! thanks

**Review by Neeharika-Sompalli — APPROVED** [review]
