### PR TITLE
fix: correct owner/spender priority addresses

### LINKED ISSUE #10313: `ContractMusicalChairsSuite.playGame()`

### LINKED ISSUE #10326: Use only `null` for unset NFT spender / treasury owner in mod `TokenService`, never `AccountID.DEFAULT`
### Problem

Currently both `AccountID.DEFAULT` and `null` are used for an NFT's `spenderId` and `ownerId` fields (the former when it is unset, the latter when the NFT is treasury-owned).

### Solution

Only use `null` for these cases so a `nft.hasSpenderId()` or `nft.hasOwnerId()` check allows us to apply conditional logic targeting these cases.

### Alternatives

_No response_

### LINKED ISSUE #10331: `ContractUpdateSuite.fridayThe13thSpec()`
Should use `MODIFYING_IMMUTABLE_CONTRACT` instead of `INVALID_SIGNATURE` when update targets an immutable contract.

### LINKED ISSUE #10333: `ContractUpdateSuite.canMakeContractImmutableWithEmptyKeyList()`

### LINKED ISSUE #10350: `Create2OperationSuite.canDeleteViaAlias()`
Need to enforce `OBTAINER_SAME_CONTRACT_ID`; and clear the alias mapping for a contract deleted via HAPI.

### LINKED ISSUE #10351: `Create2OperationSuite.priorityAddressIsCreate2ForStaticHapiCalls()`
For mono-service fidelity, we should permit `0.0.X` ids for HAPI calls to contracts with priority EVM addresses.

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Closes #10326 
 - Closes #10331 
 - Closes #10333
 - Closes #10313 
 - Closes #10350 
 - Closes #10351 
 - Updates `TokenService` components to consistently use `null` to reflect (1) treasury NFT ownership and (2) missing NFT `spender` ids.
 - Fixes `nftTokenInfoTupleFor()` to return priority addresses for NFT owners and spenders.

### CODE REVIEW

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/NFTOwnersChangeStep.java [hunk 1]
```diff
@@ -87,18 +87,12 @@ public void doIn(final TransferContext transferContext) {
                     validateSpenderHasAllowance(senderAccount, topLevelPayer, tokenId, nft);
                 }
 
-                final var copyNft = nft.copyBuilder();
-                // If the nft owner is not set then set it to the treasury account
-                if (!nft.hasOwnerId() || nft.ownerId().equals(AccountID.DEFAULT)) {
-                    copyNft.ownerId(treasury);
-                }
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/NFTOwnersChangeStep.java:94]: Should we delete this ? Or just change the condition in `if` to see if owner is null ?

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java [hunk 2]
```diff
@@ -489,7 +489,12 @@ public void deleteAndTransfer(
         // get the account from account store that has all balance changes
         // commit the account with deleted flag set to true
         final var updatedDeleteAccount = requireNonNull(accountStore.getForModify(deletedId));
-        accountStore.put(updatedDeleteAccount.copyBuilder().deleted(true).build());
+        accountStore.removeAlias(updatedDeleteAccount.alias());
+        accountStore.put(updatedDeleteAccount
+                .copyBuilder()
+                .alias(Bytes.EMPTY)
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java:495]: For mono-service fidelity with `GetContractInfo` query, we need to.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM ! tyvm @tinker-michaelj 🙂

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java [hunk 3]
```diff
@@ -233,17 +236,28 @@ public static Tuple nftTokenInfoTupleFor(
...
+        requireNonNull(token);
+        requireNonNull(ledgerId);
+        requireNonNull(nativeOperations);
 
+        final var nftMetaData = nft.metadata() != null ? nft.metadata().toByteArray() : Bytes.EMPTY.toByteArray();
         return Tuple.of(
                 tokenInfoTupleFor(token, ledgerId),
                 serialNumber,
-                headlongAddressOf(ownerAccount),
+                priorityAddressOf(nft.ownerIdOrElse(token.treasuryAccountIdOrElse(ZERO_ACCOUNT_ID)), nativeOperations),
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:251]: Oh actually `Token.DEFAULT` can be passed into that method, so we do need the `OrElse(ZERO_ACCOUNT_ID)` construct. 😝

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java [hunk 4]
```diff
@@ -233,17 +236,30 @@ public static Tuple nftTokenInfoTupleFor(
...
+                // The odd construct allowing a token to not have a treasury account set is to accommodate
+                // Token.DEFAULT being passed into this method, which a few HtsCall implementations do
+                priorityAddressOf(nft.ownerIdOrElse(token.treasuryAccountIdOrElse(ZERO_ACCOUNT_ID)), nativeOperations),
                 nft.mintTimeOrElse(new Timestamp(0, 0)).seconds(),
                 nftMetaData,
-                headlongAddressOf(nft.spenderIdOrElse(ZERO_ACCOUNT_ID)));
+                priorityAddressOf(nft.spenderIdOrElse(ZERO_ACCOUNT_ID), nativeOperations));
+    }
+
+    private static Address priorityAddressOf(
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:257]: Haven't seen the term "priority address" before.  It's in the title of this PR but otherwise not.  What does it mean?

I do see a comment way over at `EvmFrameState` which is not an obvious spot to look. Maybe the comment here?  (And based on that comment I'm still not sure why it is a "priority" address.) (We really do need a glossary of addresses ...)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java [hunk 5]
```diff
@@ -62,7 +65,7 @@ public static Tuple expiryTupleFor(@NonNull final Token token) {
         return Tuple.of(
                 token.expirationSecond(),
                 headlongAddressOf(token.autoRenewAccountIdOrElse(ZERO_ACCOUNT_ID)),
-                (token.autoRenewSeconds() > 0 ? token.autoRenewSeconds() : 0));
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:65]: I don't see anywhere in the code where non-negativity of autoRenewSeconds is enforced, if not here. Maybe it doesn't belong here but instead over at Token.Builder.autoRenewSeconds (which unfortunately is generated by PBJ).

Anyway, I may have missed it.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmStaticTransactionFactory.java [hunk 6]
```diff
@@ -65,18 +70,15 @@ public HederaEvmTransaction fromHapiQuery(@NonNull final Query query) {
         final var op = query.contractCallLocalOrThrow();
         assertValidCall(op);
         final var senderId = op.hasSenderId() ? op.senderIdOrThrow() : payerId;
+        var targetId = op.contractIDOrThrow();
+        // For mono-service fidelity, allow calls using 0.0.X id even to contracts with a priority EVM address
+        final var maybeContract =
+                context.createStore(ReadableAccountStore.class).getContractById(targetId);
+        if (maybeContract != null && maybeContract.alias().length() == EVM_ADDRESS_LENGTH_AS_LONG) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmStaticTransactionFactory.java:77]: I think `alias()` can return `null` (in general, perhaps not in this case?)

**Review by david-bakin-sl — COMMENTED** [review]
Got part way though this and realized I didn't have sufficient knowledge to complete it.  Pinged Luke to do this properly.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java [hunk 7]
```diff
@@ -233,17 +236,30 @@ public static Tuple nftTokenInfoTupleFor(
...
                 nft.mintTimeOrElse(new Timestamp(0, 0)).seconds(),
                 nftMetaData,
-                headlongAddressOf(nft.spenderIdOrElse(ZERO_ACCOUNT_ID)));
+                priorityAddressOf(nft.spenderIdOrElse(ZERO_ACCOUNT_ID), nativeOperations));
+    }
+
+    private static Address priorityAddressOf(
+            @NonNull final AccountID accountId, @NonNull final HederaNativeOperations nativeOperations) {
+        requireNonNull(accountId);
+        return (ZERO_ACCOUNT_ID == accountId)
```
Comment (lukelee-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:260]: Should we use `equals`?  I realize that `ZERO_ACCOUNT_ID` is static and probably what was used but what if someone creates a constant somewhere else?  Maybe I worry too much.

**Comment by lukelee-sl** [comment]
Are we really using `ZERO_ADDRESS` instead of null to mark unset spender, treasury account?

**Review by lukelee-sl — APPROVED** [review]
LGTM, I wonder if there are other places where there needs to be similar changes.  Thank you

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java (hunk 4 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:257]: Any time a contract has an `0xab...cd` EVM address (outside the long-zero subspace), it _must_ be referenced by that address anywhere inside the EVM. (This is to avoid creating issues with contracts that use addresses as e.g. keys in a ERC-20 `balances` map; or store a particular address as a privileged account.) 

I.e. `0xab...cd` addresses take "priority" over long-zero addresses.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java (hunk 5 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:65]: `TokenCreateHandler` should not be creating `Token`'s with negative `autoRenewSeconds`.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java (hunk 7 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/TokenTupleUtils.java:260]: This use of `ZERO_ACCOUNT_ID` is internal to `TokenTupleUtils`...could also make the first argument here `@Nullable` and then `return (accountId == null)`...semantics should be the same.

Will ponder doing elsewhere...but...passing checks 😳

**Comment by tinker-michaelj** [comment]
> Are we really using `ZERO_ADDRESS` instead of null to mark unset spender, treasury account? Maybe the issue should be corrected if this is the case.

Apparently for info of a missing token we return all zeros in its `Token` struct (including e.g. its `treasury` address)? I'm not entirely sure...didn't dig deep in that direction. 🤔
