### PR TITLE
Minor fixes from previous PR

### LINKED ISSUE #8151: Fix child transaction handling
- Set general properties in `childRecordBuilder`
- Set `status` to `SUCCESS`
- Fix signature verification for child records

### PR DESCRIPTION
**Pull request by netopyr**
Minor fixes from previous PR #8197 

- Disable all child verifications per default until handled properly
- Fixed serialization of transactions

Closes #8151

### CODE REVIEW

File: hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java [hunk 1]
```diff
@@ -446,11 +445,9 @@ private void dispatchSyntheticTxn(
         final var transaction = Transaction.newBuilder()
                 .signedTransactionBytes(signedTransactionBytes)
                 .build();
-        final var transactionBytes =
-                Bytes.wrap(PbjConverter.fromPbj(transaction).toByteArray());
         childRecordBuilder
                 .transaction(transaction)
-                .transactionBytes(transactionBytes)
+                .transactionBytes(signedTransactionBytes)
```
Comment (rbair23) [inline hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java:450]: Is this right?

Comment (netopyr) [reply hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java:450]: That's what we do in `HandleWorkflow`. And I think the code there was changed to its current form after a discussion with @tinker-michaelj

**Review by rbair23 — APPROVED** [review]

**Review by lukelee-sl — APPROVED** [review]
LGTM
