### PR TITLE
fix: ensure configuration loading and name resolution is resilient

### LINKED ISSUE #15921: Improve Platform SDK configuration loading and initialization mechanism resilience
### Problem

In a kubernetes environment DNS resolution and persistent/projected volumes might not be immediately available during the first few seconds of container boot up. Due to brittle nature of the Platform configuration loading and DNS resolution implementations, this causes intermittent failures when using the deterministic container image in a K8S environment. 

### Solution

- Enhance the actual Platform SDK initialization mechanisms to be more durable and resilient to running in kubernetes environment.

### Alternatives

- Not Applicable

### PR DESCRIPTION
**Pull request by nathanklick**
## Description

This pull request changes the following:

- Adds a reusable `Retry` utility class to the `swirlds-base` module.
- Adds a reusable `FileSystem` utility class to `swirlds-base` module.
- Adds a reusable `Network` utility class to the `swirlds-base` module.
- Implements a `Network.isNameResolvable` which supports retryable DNS lookups to be resilient to DNS delays.
- Implements a `FileSystem.waitForPathPresence` which supports retryable file/directory/symlink existence checks.
- Ensures the Platform/Services bootstrap is resilient to Kubernetes edge cases where DNS resolution and file mounts may be slightly delayed.

### Related Issues 

- Closes #15921

### CODE REVIEW

File: platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Network.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+    /**
+     * Internal implementation used by the {@link #isNameResolvable(String, int, int)} method.
+     *
+     * @param name the domain name fragment, fully qualified domain name (FQDN), or IP address to be resolved.
+     * @return true if the name resolves to one or more valid IP addresses; otherwise false.
+     */
+    private static boolean isNameResolvableInternal(@NonNull final String name) {
+        Objects.requireNonNull(name, "name must not be null");
+        try {
+            final InetAddress[] addresses = InetAddress.getAllByName(name);
```
Comment (leninmehedy) [inline platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Network.java:88]: Just wondering if `InetAddress.getByName` would suffice here instead of  `InetAddress.getAllByName(name)`

Also I can see `InetAddress.getByName()` is used in the code (in config.txt parser) to resolve to an IP, so it would make the code consistent.

File: platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Retry.java [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+                }
+            }
+        } catch (final Throwable e) {
+            // If an exception other than UnknownHostException or InterruptedException is thrown, then we should
+            // immediately skip any further retry attempts.
+            throw new ExecutionException("Unhandled exception thrown during a retryable operation attempt", e);
+        }
+
+        // If we failed to resolve the name to an IP address within the maximum retry threshold, then we should fall
+        // through to here to fail.
```
Comment (leninmehedy) [inline platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Retry.java:85]: The comment in the body (line 79-80, 84-85) needs to be polished a bit without referring to resolving an IP or UnknownHostException

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java [hunk 3]
```diff
@@ -178,11 +177,8 @@ public static Address parseAddressText(@NonNull final String addressText) throws
         }
         // FQDN Support: The original string value is preserved, whether it is an IP Address or a FQDN.
         final String internalHostname = parts[5];
-        try {
-            // validate that an InetAddress can be created from the internal hostname.
-            InetAddress.getByName(internalHostname);
-        } catch (UnknownHostException e) {
-            throw new ParseException("Cannot parse ip address from '" + parts[5] + "'", 5);
+        if (!isNameResolvable(internalHostname)) {
+            throw new ParseException("Cannot parse ip address from '" + internalHostname + "'", 5);
```
Comment (leninmehedy) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java:181]: nitpick: `Cannot parse` -> `Cannot resolve`

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java [hunk 4]
```diff
@@ -192,11 +188,8 @@ public static Address parseAddressText(@NonNull final String addressText) throws
         }
         // FQDN Support: The original string value is preserved, whether it is an IP Address or a FQDN.
         final String externalHostname = parts[7];
-        try {
-            // validate that an InetAddress can be created from the external hostname.
-            InetAddress.getByName(externalHostname);
-        } catch (UnknownHostException e) {
-            throw new ParseException("Cannot parse ip address from '" + parts[7] + "'", 7);
+        if (!isNameResolvable(externalHostname)) {
+            throw new ParseException("Cannot parse ip address from '" + externalHostname + "'", 7);
```
Comment (leninmehedy) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/address/AddressBookUtils.java:192]: nitpick: `Cannot parse` -> `Cannot resolve`

**Review by leninmehedy — DISMISSED** [review]
Awesome, looks good. thank you.
I've added some minor comments.

File: platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/FileSystem.java [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+import java.io.IOException;
+import java.nio.file.Files;
+import java.nio.file.Path;
+import java.util.Objects;
+import java.util.concurrent.ExecutionException;
+
+/**
+ * Provides file system-related utility methods.
+ */
+public final class FileSystem {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/FileSystem.java:29]: I dont think `FileSystem` is an accurate name for this utility, maybe `FileSystemUtils`

File: platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/FileSystem.java [hunk 6]
```diff
@@ -0,0 +1,106 @@
...
+     *
+     * @param path        the path to check for existence.
+     * @param maxAttempts the maximum number of retry attempts.
+     * @param delayMs     the delay between retry attempts.
+     * @return true if the file exists before the retries have been exhausted; otherwise false.
+     * @throws IllegalArgumentException if the {@code maxAttempts} argument is less than or equal to zero (0) or the
+     *                                 {@code delayMs} argument is less than zero (0).
+     * @throws NullPointerException    if the {@code path} argument is a {@code null} value.
+     */
+    public static boolean waitForPathPresence(@NonNull Path path, int maxAttempts, int delayMs) {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/FileSystem.java:68]: Rather then using `int maxAttempts, int delayMs`, I suggested just a single parameter `Duration waitTime` with possibly a `Duration retryTime` as well, but I think this second one is not needed, we can just use a sane default. Using an `int` to represent milliseconds can be more confusing

File: platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/FileSystem.java [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+    }
+
+    /**
+     * Internal method to evaluate a given {@code path} to ensure it is present.
+     *
+     * @param path the path to check for existence.
+     * @return true if the file, directory, block device, or symlink exists and is not empty if the path references a
+     * file; otherwise false.
+     */
+    private static boolean waitForPathPresenceInternal(@NonNull final Path path) {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/FileSystem.java:87]: I would remove the wait from this method name since it doesnt actually wait

File: platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Retry.java [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+            for (int i = 0; i < maxAttempts; i++) {
+                if (checkFn.apply(value)) {
+                    return true;
+                }
+
+                if (delayMs > 0) {
+                    TimeUnit.MILLISECONDS.sleep(delayMs);
+                }
+            }
+        } catch (final Throwable e) {
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-base/src/main/java/com/swirlds/base/utility/Retry.java:78]: this seems to suppress `InterruptedException`. Also, I don't see why we should catch unchecked exceptions and rethrow them as checked

File: platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java [hunk 9]
```diff
@@ -55,6 +57,9 @@ public PropertyFileConfigSource(@NonNull final Path filePath, final int ordinal)
      */
     @NonNull
     protected BufferedReader getReader() throws IOException {
+        if (!FileSystem.waitForPathPresence(filePath)) {
+            throw new FileNotFoundException("File not found: " + filePath);
+        }
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java:62]: I feel like this wait should happen before this instance is constructed

**Review by rbarkerSL — APPROVED** [review]

**Review by andrewb1269hg — DISMISSED** [review]

**Review by kimbor — DISMISSED** [review]
I'm not clear why I was asked to review this. When I filter on 'Only files owned by you' I see only `hedera-node/infrastructure/docker/containers/production-next/consensus-node/entrypoint.sh`. I don't know why this file would be owned by the services team.

In my extremely limited knowledge of this area, it lgtm.

**Review by leninmehedy — DISMISSED** [review]

**Review by kimbor — APPROVED** [review]

**Review by rbarkerSL — DISMISSED** [review]
Lgtm

File: platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java (hunk 9 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java]: I still think none of these config classes should be waiting, we should do the wait before we try to initialize the config

Comment (nathanklick) [reply platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java]: If I move the logic, it results in duplicated code in multiple locations. Should we disregard being `DRY` simply to avoid the configuration logic from waiting for file existence?

Comment (nathanklick) [reply platform-sdk/swirlds-config-extensions/src/main/java/com/swirlds/config/extensions/sources/PropertyFileConfigSource.java]: I've gone ahead and moved the logic to the 4 known immediate callers of `PropertyFileConfigSource` not including test code locations.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM from hedera-base changes! Thanks @nathanklick

**Review by lpetrovic05 — APPROVED** [review]

**Review by rbarkerSL — APPROVED** [review]

**Review by andrewb1269hg — APPROVED** [review]
Reviewed the following files:
`gradle/plugins/src/main/kotlin/com.hedera.gradle.java.gradle.kts`
`hedera-node/infrastructure/docker/containers/production-next/consensus-node/entrypoint.sh`
`platform-sdk/swirlds-base/build.gradle.kts`
`platform-sdk/swirlds-config-impl/build.gradle.kts`
