### PR TITLE
reconnect end msg

### LINKED ISSUE #9725: Reconnect protocol needs to finish cleanly
### Description

When the teacher node finishes a reconnect session it switches to next protocol on the same connection. The learner node, however, may take time before it exits reconnect and becomes ready to respond to the next protocol. The [former] teacher does not receive the expected response and closes the connection. If the learner is still in the reconnect protocol, it considers the closed connection as a fatal error and aborts reconnect (despite the fact that it has received all information).

A good indication of this error is a log message on the teacher side about finishing reconnect followed by another message about a broken connection. The learner reports a new connection from the teacher node and then may or may not fail reconnect depending on timing.

### Steps to reproduce

The bug is reproduced in performance networks with a large state.
Here is an excerpt from `swirlds.log` supporting the bug description:

### teacher
```
2023-11-04 12:45:41.369 63332    INFO  RECONNECT        <<platform-core: SyncProtocolWith6 5 to 6>> ReconnectTeacher: Starting reconnect in the role of the sender {"receiving":false,"nodeId":5,"otherNodeId":6,"round":271152} [com.swirlds.logging.payloads.ReconnectStartPayload]
...
2023-11-04 12:56:36.636 64468    INFO  RECONNECT        <<platform-core: SyncProtocolWith6 5 to 6>> ReconnectTeacher: Finished reconnect in the role of the sender. {"receiving":false,"nodeId":5,"otherNodeId":6,"round":271152,"success":false} [ReconnectFinishPayload]
2023-11-04 12:56:41.641 64478    WARN  SOCKET_EXCEPTIONS <<platform-core: SyncProtocolWith6 5 to 6>> NetworkUtils: Connection broken: 5 -> 6 Caused By: {Exception: SocketTimeoutException Message: Read timed out }
```

### learner
```
2023-11-04 12:45:41.382 1399     INFO  RECONNECT        <<reconnect: reconnect-controller>> ReconnectHelper: Starting reconnect in role of the receiver. {"receiving":true,"nodeId":6,"otherNodeId":5,"round":268231} [com.swirlds.logging.payloads.ReconnectStartPayload]
...
2023-11-04 12:56:12.299 1633     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 11 -> 1]
2023-11-04 12:56:41.699 1643     WARN  SOCKET_EXCEPTIONS <<sync_server #4>> InboundConnectionManager: 6 got new connection from 5, disconnecting old one
2023-11-04 12:56:42.010 1644     ERROR EXCEPTION        <<reconnect: reconnect-controller>> StandardWorkGroup: Work Group Exception [ groupName = learning-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID -7441057967105127907(0x98BC0D340D9BCA1D) (class com.swirlds.common.merkle.synchronization.internal.Lesson)
Caused by: java.io.IOException: Stream closed
```

### Additional context

See also #9678

### Hedera network

other

### Version

v0.43.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by lpetrovic05**
closes #9725

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java [hunk 1]
```diff
@@ -156,6 +156,7 @@ public ReservedSignedState execute(@NonNull final SignedStateValidator validator
             receiveSignatures();
             final ReservedSignedState reservedSignedState = reconnect();
             validator.validate(reservedSignedState.get(), addressBook, stateValidationData);
+            ReconnectUtils.endReconnectHandshake(connection);
```
Comment (alittley) [inline platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java:159]: Could this handshake take place _before_ validating the received state?

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java (hunk 1 above)
Comment (lpetrovic05) [reply platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearner.java:159]: The whole idea of the handshake is to tell our peer that we are done with all the work. If we placed it before validation, and validation takes a long time, we have the same issue we are trying to solve.
