### PR TITLE
fix(23170): Improve result reporting

### LINKED ISSUE #23170: Benchmark should suport a simple network expected TPS mechanism
Once indicated, the benchmark should sent transactions to the node to acomodate achieving the expected tps.
The only strategy supported will be even, leaving support for bursts, redirecting etc to the future.
The benchmark should make sure that events are sent evenly to all nodes in the network

### PR DESCRIPTION
**Pull request by mxtartaglia-sl**
**Description**:
Few changes to improve how results are reported

**Related issue(s)**:

Fixes #23170

### CODE REVIEW

File: platform-sdk/consensus-otter-tests/src/testPerformance/java/org/hiero/otter/test/performance/benchmark/fixtures/MeasurementsCollector.java [hunk 1]
```diff
@@ -166,29 +166,82 @@ public Statistics computeStatistics() {
...
         final Statistics totalStats = computeStatistics();
 
         if (totalStats.sampleCount() == 0) {
             jmhStyleReport.append("No benchmark data recorded.\n");
             return jmhStyleReport.toString();
         }
 
-        // JMH-style header
+        final org.hiero.base.utility.StringTable table = org.hiero.base.utility.StringTable.column("Benchmark")
+                .column("Cnt")
```
Comment (abies) [inline platform-sdk/consensus-otter-tests/src/testPerformance/java/org/hiero/otter/test/performance/benchmark/fixtures/MeasurementsCollector.java]: This way of specifying columns is very unreadable. Given that spotless will mess up any explici formatting we do, only choice would be probably something like
```
Builder builder = ....

builder.column("Benchmark");
builder.column("Cnt");
builder.column("Score").typeFloat(10,3);
builder.headlessColumn().withFixedValue(UNIT)
...
```

File: platform-sdk/base-utility/src/main/java/org/hiero/base/utility/StringTable.java [hunk 2]
```diff
@@ -0,0 +1,248 @@
...
+            return this;
+        }
+
+        /**
+         * Adds a headless (unnamed) column.
+         *
+         * @return this builder
+         */
+        @NonNull
+        public Builder headlessColumn() {
```
Comment (abies) [inline platform-sdk/base-utility/src/main/java/org/hiero/base/utility/StringTable.java]: I think that column("") is more readable than headlessColumn(). I would get rid of this method

File: platform-sdk/base-utility/src/main/java/org/hiero/base/utility/StringTable.java [hunk 3]
```diff
@@ -0,0 +1,248 @@
...
+        return sb.toString();
+    }
+
+    @NonNull
+    private static String formatCell(@NonNull final ColumnDef col, @NonNull final Object value) {
+        if (col.fixedValue != null) {
+            return col.fixedValue;
+        }
+        return switch (col.type) {
+            case INT -> String.format("%d", ((Number) value).longValue());
```
Comment (abies) [inline platform-sdk/base-utility/src/main/java/org/hiero/base/utility/StringTable.java:119]: This is an overkill compared to just String.valueOf or Long.toString()

File: platform-sdk/consensus-otter-tests/src/testPerformance/java/org/hiero/otter/test/performance/benchmark/ConsensusLayerBenchmark.java [hunk 4]
```diff
@@ -44,7 +44,7 @@ public class ConsensusLayerBenchmark {
     private static final int TRANSACTION_COUNT = 1000;
     private static final int MAX_TPS = 20;
     // Setup simulation with 4 nodes
-    public static final int NUMBER_OF_NODES = 4;
+    public static final int NUMBER_OF_NODES = 2;
```
Comment (abies) [inline platform-sdk/consensus-otter-tests/src/testPerformance/java/org/hiero/otter/test/performance/benchmark/ConsensusLayerBenchmark.java]: Was it supposed to be there? If yes, then please update the comment, but I think it is an accident

Comment (mxtartaglia-sl) [reply platform-sdk/consensus-otter-tests/src/testPerformance/java/org/hiero/otter/test/performance/benchmark/ConsensusLayerBenchmark.java]: it is a mistake, thanks

File: platform-sdk/base-utility/src/main/java/org/hiero/base/utility/StringTable.java (hunk 3 above)
Comment (mxtartaglia-sl) [reply platform-sdk/base-utility/src/main/java/org/hiero/base/utility/StringTable.java:119]: Lets keep it, makes it consistent with the float formating
