### PR TITLE
Fix contract creation ids, enforce entity limits

### LINKED ISSUE #8718: Implement correct `getCreatedContractIDs()` behaviour
It looks like we don't add the correct contract ids in the `ContractFunctionResult` externalized in records and that leads to some tests failing. Example of such failing tests (both from `ContractCreateSuite`):
- `childCreationsHaveExpectedKeysWithOmittedAdminKey`
- `vanillaSuccess`

### LINKED ISSUE #8780: Resolve `LogsSuite` errors
### Problem

We have the following tests suite `LogsSuite` that has problems when it's running against modularization codebase.

### Solution

Resolve issues with the test suite. When ready add @hapitest annotations to the passing tests.

### Alternatives

_No response_

### LINKED ISSUE #8898: Fix FileUpdateSuite (6) tests and FileCreateSuite (1)

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
- Closes #8718 
- Closes #8780 
- Closes #8898 

1️⃣ `XTest` improvements
 - Refactors to support both `ContractService` and `TokenService` x-tests.
 - Adds `context` strings to give more informative failure messages on helper methods.
 - Adds `ContractLimitsXTest` to validate creation limits on contracts.
 - Adds sample `RoyaltyCollectorAutoAssociationXTest` token x-test.

2️⃣ Misc fixes
 - Removes `FILE_CONTENT_EMPTY` response from `FileService`.
 - Enforces schedules creation limit in `ScheduleCreateHandler`.
 - Enforces contract creation limit in `CustomContractCreationProcessor` and `ProxyWorldUpdater`.
 - Enforces storage limits in `RootProxyWorldUpdater.commit()`.
 - Removes `stack.addFirst(frame)` in `FrameRunner`---Besu `MessageFrame.Builder` now does this automatically.
 - Removes superfluous `.updater()` call in `AbstractCustomCreateOperation` (in mono-service this was merely wasteful; in mod-service, it's catastrophic bug as it causes the savepoint stack to get out of sync with the `MessageFrame` stack).
 - Ensures the fees-only updater used when a `ResourceExhaustedException` is thrown by the root `WorldUpdater.commit()` begins with a fresh savepoint; and that the previous updater has reverted. 
 - Makes `ProxyWorldUpdater` savepoint stack mutations safe under the Besu revert-then-commit pattern in `AbstractMessageProcessor`.
 - Fixes the `newContractIds` detection in `RootProxyWorldUpdater.commit()`.
 - Fixes ~~`spender`~~ -> `sender` typo in `ERCGrantApprovalCall`.
 - Adds gas limit precheck validations to `ContractCallLocalHandler`.
 - Fills out revert reason query responses.

Fixes https://github.com/hashgraph/hedera-services/issues/8718

### CODE REVIEW

**Review by povolev15 — APPROVED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionModule.java [hunk 1]
```diff
@@ -90,7 +90,10 @@ static HederaEvmContext provideHederaEvmContext(
     @TransactionScope
     static Supplier<HederaWorldUpdater> provideFeesOnlyUpdater(
             @NonNull final HederaWorldUpdater.Enhancement enhancement, @NonNull final EvmFrameStateFactory factory) {
-        return () -> new ProxyWorldUpdater(enhancement, requireNonNull(factory), null);
+        return () -> {
+            enhancement.operations().begin();
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionModule.java:94]: Is this to start anew after the `updater.revert` at `TransactionProcessor` L155 below?  

If so, then this is a "matched set" that is unfortunately widely separated in the source code.  And also _all_ new feesOnlyUpdaters will start a child operation - is that intended? 

Anyway it would be nicer IMO that _if_ it is a matched set and _if_ this is the only place it happens (I mean over there in `TransactionProcessor` that the `updater.revert` and `operations.begin` were closer together in the source code in some fashion.  (perhaps wrapped up in a method together)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java [hunk 2]
```diff
@@ -282,6 +291,11 @@ public boolean isSuccess() {
         return stateChangesFrom(frame, false);
     }
 
+    private static String errorMessageForRevert(@NonNull final Bytes reason) {
+        requireNonNull(reason);
+        return "0x" + reason.toHex();
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java:296]: ooookay ... why?  (someone external must need it?)

**Review by rbair23 — DISMISSED** [review]

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java [hunk 3]
```diff
@@ -118,10 +125,12 @@ public ResponseCodeEnum finalStatus() {
         if (haltReason != null) {
             return CustomExceptionalHaltReason.statusFor(haltReason);
         } else if (revertReason != null) {
-            if (revertReason.length() == 0) {
-                return ResponseCodeEnum.CONTRACT_REVERT_EXECUTED;
+            if (revertReason.equals(MAX_STORAGE_EXCEEDED_REASON)) {
+                return MAX_CONTRACT_STORAGE_EXCEEDED;
+            } else if (revertReason.equals(MAX_TOTAL_STORAGE_EXCEEDED_REASON)) {
+                return MAX_STORAGE_IN_PRICE_REGIME_HAS_BEEN_USED;
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java:131]: Do these just represent the only ones known at this time and this list will be added to as needed?  Or this is it?

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java [hunk 4]
```diff
@@ -149,25 +149,19 @@ private void spawnChildMessage(@NonNull final MessageFrame frame) {
 
         final var childGasStipend = gasCalculator().gasAvailableForChildCreate(frame.getRemainingGas());
         frame.decrementRemainingGas(childGasStipend);
-        final var childFrame = MessageFrame.builder()
+        // Child frame automatically added to parent messageFrameStack
+        MessageFrame.builder()
                 .parentMessageFrame(frame)
                 .type(MessageFrame.Type.CONTRACT_CREATION)
-                .worldUpdater(frame.getWorldUpdater().updater())
```
Comment (david-bakin-sl) [inline hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java:155]: (This is the catastrophic "superfluous `.updater()` call" mixed in here with these other things being removed - had to look a couple of times to spot it.)

**Review by david-bakin-sl — COMMENTED** [review]
Comments on _code_.  I did spot everything you mentioned in your PR comment which was nicely comprehensive, thank you! 

Tests coming.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java [hunk 5]
```diff
@@ -149,25 +149,19 @@ private void spawnChildMessage(@NonNull final MessageFrame frame) {
 
         final var childGasStipend = gasCalculator().gasAvailableForChildCreate(frame.getRemainingGas());
         frame.decrementRemainingGas(childGasStipend);
-        final var childFrame = MessageFrame.builder()
+        // Child frame automatically added to parent messageFrameStack
```
[the remark this answers is not in the document]
Comment (lukelee-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java:152]: This change was added as part of Besu 27.3.2

File: hedera-node/hedera-app/src/xtest/java/contract/XTestConstants.java [hunk 6]
```diff
@@ -149,4 +130,8 @@ public static void addErc20Relation(
     public static Consumer<org.apache.tuweni.bytes.Bytes> assertSuccess() {
         return output -> assertEquals(SUCCESS_AS_BYTES, output);
     }
+
+    public static Consumer<org.apache.tuweni.bytes.Bytes> assertSuccess(String failureMessage) {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/xtest/java/contract/XTestConstants.java:134]: Perhaps rename this (instead of overloading) because it's kind of weird to have `assertSuccess` with a parameter that is `failureMessage`.  Maybe `assertSuccessWithMessage()`?  Or maybe just rename the parameter to simply `message`?

File: hedera-node/hedera-app/src/xtest/java/token/RoyaltyCollectorAutoAssociationXTest.java [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+import com.hedera.hapi.node.base.AccountID;
+import com.hedera.hapi.node.base.TokenID;
+import com.hedera.hapi.node.state.common.EntityIDPair;
+import com.hedera.hapi.node.state.token.Account;
+import com.hedera.hapi.node.state.token.Token;
+import com.hedera.hapi.node.state.token.TokenRelation;
+import com.hedera.pbj.runtime.io.buffer.Bytes;
+import java.util.Map;
+
+public class RoyaltyCollectorAutoAssociationXTest extends AbstractTokenXTest {
```
Comment (david-bakin-sl) [inline hedera-node/hedera-app/src/xtest/java/token/RoyaltyCollectorAutoAssociationXTest.java:28]: Per our discussion offline please add an override for `assertExpectedAccounts` and/or `assertExpectedTokens` and/or `assertExpectedNfts` that simply have a comment that says "this is where validation of assesed royaltys should occur".

IOW an xtest should go deeper than just transaction response code to actually check the state, fees, etc.  (Same for the `PausesXTest` for example: it should really be checking that the state of the nfts reflects the pause.)  But a) this sample doesn't need to provide it yet and b) we should develop (as we discussed) helper methods that make these validations smooth and easy.)

**Review by lukelee-sl — DISMISSED** [review]
LGTM

**Review by david-bakin-sl — APPROVED** [review]
Looked at the Xtests (not the BDDs).  This new structure is great and I hope it encourages not just the creation of more Token Service xtests but more xtests over more services!

(As we discussed offline:) Still to do are the _validations_ of _state_.  Not just tx response code, but looking inside the state to make sure that token fees were assessed, contract bytecode was added, tokens were frozen or unfrozen as specified, etc.

But I'm more convinced than ever that these xtests will be much much much nicer for validating _semantics_ of Hedera than the BDD suite is, and thus encourage even more comprehensive testing.  (Especially as, though we haven't gotten there yet, they'll also lend themselves to parameterized and cartesian product testing as well.)

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (david-bakin-sl) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/operations/AbstractCustomCreateOperation.java:152]: (You mean the self-linking aspect of this builder is new, I think.  But now, what remains: The use of a builder `.build()` method without assigning it to _anything_ is something you don't see every day.)

File: hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandlerTest.java [hunk 8]
```diff
@@ -195,6 +198,33 @@ void handleRejectsNonWhitelist() throws HandleException, PreCheckException {
         }
     }
 
+    @Test
+    void handleRefusesToExceedCreationLimit() throws HandleException, PreCheckException {
+        final Set<HederaFunctionality> configuredWhitelist =
+                scheduleConfig.whitelist().functionalitySet();
+        // make sure we have at least four items in the whitelist to test.
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandlerTest.java]: Cleaned up.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomContractCreationProcessor.java [hunk 9]
```diff
@@ -63,8 +67,14 @@ public CustomContractCreationProcessor(
...
     public void start(@NonNull final MessageFrame frame, @NonNull final OperationTracer tracer) {
         final var addressToCreate = frame.getContractAddress();
-        final var contract =
-                frame.getWorldUpdater().getOrCreate(addressToCreate).getMutable();
+        final MutableAccount contract;
+        try {
+            contract = frame.getWorldUpdater().getOrCreate(addressToCreate).getMutable();
+        } catch (ResourceExhaustedException ignore) {
+            halt(frame, FAILED_CREATION_HALT_REASON);
+            tracer.traceAccountCreationResult(frame, FAILED_CREATION_HALT_REASON);
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomContractCreationProcessor.java]: Yes seems better, moved this to `halt()` and added a `HaltShouldTraceAccountCreation.YES/NO` enum.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java [hunk 10]
```diff
@@ -256,43 +267,23 @@ public List<Long> getModifiedAccountNumbers() {
...
-                // do not return payer and funding account in newly createdContractIds list
-                .filter(accountID -> !List.of(payerAccountID, fundingAccountID).contains(accountID.accountNum()))
-                .map(accountId -> ContractID.newBuilder()
-                        .contractNum(accountId.accountNumOrThrow())
-                        .build())
-                .sorted(CONTRACT_ID_NUM_COMPARATOR)
-                .toList();
+        final var contractChangeSummary = tokenServiceApi.summarizeContractChanges();
+        contractChangeSummary.newContractIds().sort(CONTRACT_ID_NUM_COMPARATOR);
+        contractChangeSummary.updatedContractNonces().sort(NONCE_INFO_CONTRACT_ID_COMPARATOR);
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java]: `sort()` is required for differential testing; moved it into the compact constructor for the `ContractChangeSummary` record.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java [hunk 11]
```diff
@@ -81,7 +87,7 @@ public HandleHederaOperations(@NonNull final LedgerConfig ledgerConfig, @NonNull
      */
     @Override
     public void commit() {
-        // Currently the savepoint stack only supports reverting savepoints; then commits all remaining at the end
+        context.savepointStack().commit();
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java:84]: Yes it's correct afaik.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java [hunk 12]
```diff
@@ -209,6 +211,11 @@ private void validateSemantics(
         final var ledgerConfig = context.configuration().getConfigData(LedgerConfig.class);
         final var entitiesConfig = context.configuration().getConfigData(EntitiesConfig.class);
         final var tokensConfig = context.configuration().getConfigData(TokensConfig.class);
+        final var accountConfig = context.configuration().getConfigData(AccountsConfig.class);
+
+        if (accountStore.getNumberOfAccounts() + 1 > accountConfig.maxNumber()) {
+            throw new HandleException(MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java:217]: Nice .. Thank you!

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java [hunk 13]
```diff
@@ -138,7 +138,7 @@ private void chargeRoyalty(
                 adjustHbarFees(result, account, fee);
             } else {
                 // exchange is for token
-                adjustHtsFees(result, account, feeCollector, feeMeta, amount, denom);
+                adjustHtsFees(result, account, feeCollector, feeMeta, royalty, denom);
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java:141]: I thought this is merged to develop 😮

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionModule.java (hunk 1 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionModule.java:94]: Hmm yes you're right, this is `begin()` will only be correct we have already `revert()`-ed the `RootProxyWorldUpdater` whose `commit()` threw a `ResourceExhaustedException`. 

Will ponder how we might reorganize this. 🤔

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java (hunk 2 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java:296]: Haha backward compatibility, I have no clear sense why we are externalizing these in hex 😵‍💫

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java (hunk 3 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java:131]: We will need all 5 from [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/ResponseCodeUtil.java#L60).

File: hedera-node/hedera-app/src/xtest/java/contract/XTestConstants.java (hunk 6 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/xtest/java/contract/XTestConstants.java]: Renamed parameter to `orElseMessage`, so `assertSuccess(orElseMessage)`. 🤔

File: hedera-node/hedera-app/src/xtest/java/token/RoyaltyCollectorAutoAssociationXTest.java (hunk 7 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/xtest/java/token/RoyaltyCollectorAutoAssociationXTest.java:32]: Added overrides with such comments.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java (hunk 13 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java]: Ah it is, this is just a quirk of GitHub since I hadn't merged `develop` since branching off. 😁

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java [hunk 14]
```diff
@@ -169,7 +170,12 @@ protected boolean submitOp(HapiSpec spec) throws Throwable {
                             "{} Status resolution failed due to unrecoverable runtime exception, "
                                     + "possibly network connection lost.",
                             TxnUtils.toReadableString(txn));
-                    throw new HapiTxnCheckStateException("Unable to resolve txn status!");
+                    if (unavailableStatusIsOk) {
+                        // If we expect the status to be unavailable treat this as a success
+                        return true;
```
Comment (Neeharika-Sompalli) [inline hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java:175]: Is this for some test to pass ?

File: hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java [hunk 15]
```diff
@@ -49,6 +49,12 @@ public interface ReadableAccountStore {
     @Nullable
     AccountID getAccountIDByAlias(@NonNull final Bytes alias);
 
+    /**
+     *
+     * @return
+     */
```
Comment (Neeharika-Sompalli) [inline hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java:55]: javadoc missing

**Review by Neeharika-Sompalli — APPROVED** [review]
Have some minor comments. LGTM otherwise.

**Review by vtronkov — APPROVED** [review]

File: hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java (hunk 15 above)
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java]: Added

File: hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java (hunk 14 above)
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java]: Yep, elaborated in the comment here; allows tests that submit transactions > 6144 bytes to pass.

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM !

**Review by vtronkov — APPROVED** [review]

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM!

File: hedera-node/hedera-app/src/xtest/java/common/AbstractXTest.java [hunk 16]
```diff
@@ -0,0 +1,391 @@
...
+import java.util.Objects;
+import java.util.concurrent.atomic.AtomicReference;
+import java.util.function.Consumer;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+import org.mockito.Mock;
+import org.mockito.junit.jupiter.MockitoExtension;
+
+@ExtendWith(MockitoExtension.class)
+public abstract class AbstractXTest {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-app/src/xtest/java/common/AbstractXTest.java:94]: Added.

**Review by lukelee-sl — APPROVED** [review]

File: hedera-node/test-clients/src/main/resource/bootstrap.properties [hunk 17]
```diff
@@ -49,7 +49,7 @@ staking.startupHelper.recompute=NODE_STAKES,PENDING_REWARDS
 tokens.storeRelsOnDisk=true
 hedera.workflows.enabled=
 # Dynamic properties
-accounts.maxNumber=20_000_000
+accounts.maxNumber=20000000
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/test-clients/src/main/resource/bootstrap.properties:52]: We can't put `_` numeric separators in this file because its the source of default values for `@HapiTest`'s; and the mod config service doesn't parse them.

**Review by Neeharika-Sompalli — DISMISSED** [review]
LGTM!

**Review by lukelee-sl — APPROVED** [review]

**Review by Neeharika-Sompalli — APPROVED** [review]
🎉

**Review by lukelee-sl — APPROVED** [review]

File: hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/ContractChangeSummary.java [hunk 18]
```diff
@@ -0,0 +1,25 @@
...
+ * limitations under the License.
+ */
+
+package com.hedera.node.app.service.token.api;
+
+import com.hedera.hapi.node.base.ContractID;
+import com.hedera.hapi.node.contract.ContractNonceInfo;
+import java.util.List;
+
+public record ContractChangeSummary(List<ContractID> newContractIds, List<ContractNonceInfo> updatedContractNonces) {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/ContractChangeSummary.java:31]: Moved sort to constructor.

File: hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/failure/ResourceExhaustedException.java [hunk 19]
```diff
@@ -23,9 +23,7 @@
 import edu.umd.cs.findbugs.annotations.NonNull;
 
 /**
- * A {@link HandleException} specialization that indicates that a resource limit
- * has been exceeded. Unlike a "normal" {@link HandleException}, this generally
- * means the entire transaction needs to be reverted.
+ * A {@link HandleException} specialization that indicates that a resource limit has been exceeded.
  */
 public class ResourceExhaustedException extends HandleException {
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/failure/ResourceExhaustedException.java:27]: Moved.

File: hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java [hunk 20]
```diff
@@ -209,6 +211,11 @@ private void validateSemantics(
         final var ledgerConfig = context.configuration().getConfigData(LedgerConfig.class);
         final var entitiesConfig = context.configuration().getConfigData(EntitiesConfig.class);
         final var tokensConfig = context.configuration().getConfigData(TokensConfig.class);
+        final var accountConfig = context.configuration().getConfigData(AccountsConfig.class);
+
+        if (accountStore.getNumberOfAccounts() >= accountConfig.maxNumber()) {
+            throw new HandleException(MAX_ENTITIES_IN_PRICE_REGIME_HAVE_BEEN_CREATED);
```
[the remark this answers is not in the document]
Comment (tinker-michaelj) [reply hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java:217]: Moved.
