### PR TITLE
Fix blocker and critical sonar issues.

### LINKED ISSUE #1436: 1428 child-issue: Clean up SonarCloud Critical and Blockers
Related to #1428

Resolve 4 Critcal and 1 Blockers security vulnerabilities in SonarCloud https://sonarcloud.io/project/issues?id=com.hedera.hashgraph%3Ahedera-services&resolved=false&severities=BLOCKER%2CCRITICAL&types=BUG

### PR DESCRIPTION
**Pull request by ljianghedera**
**Related issue(s)**:
Closes #1436

**Summary of the change**:

1. Changes to hopefully get rid of the 1 blocker and 4 critical bug reported by sonar;

**External impacts**:
None.

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java [hunk 1]
```diff
@@ -213,6 +213,8 @@ private long lcm(long a, long b) {
 	}
 
 	private long gcd(long a, long b) {
+		// The assert is to comfort sonar. assertMinimalOpsPerSec already guarantees this, but sonar is not smart enough.
+		assert(a != 0 || b != 0);
```
Comment (qnswirlds) [inline hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java:217]: I don't think we need to comfort sonar at all cost. If it is not smart enough there, it's sonar's problem. And there should be an issue filed on their side!

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 2]
```diff
@@ -78,10 +78,11 @@
 		public BiConsumer<MerkleAccount, Object> setter() {
 			return (a, v) -> {
 				try {
-					a.setBalance((long) v);
+					a.setBalance((long)v);
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:81]: the cast should have the original spacing

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 3]
```diff
@@ -78,10 +78,11 @@
...
 				} catch (NegativeAccountBalanceException nabe) {
+					// The cast here is to make sonar happy
 					throw new IllegalArgumentException(String.format(
-							"Argument 'v=%d' would cause account 'a=%s' to have a negative balance!", v, a));
+							"Argument 'v=%d' would cause account 'a=%s' to have a negative balance!", (long)v, a));
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:85]: same here, should have the spacing `(long) v`

**Review by qnswirlds — CHANGES_REQUESTED** [review]
Please see inline comments

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java (hunk 2 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java]: Done.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java (hunk 3 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java]: Changed.

File: hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java (hunk 1 above)
Comment (ljianghedera) [reply hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java:217]: I agree we don't need to comfort sonar at all cost. This we need a little more thinking.

Comment (rbair23) [reply hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java:217]: I think that unless -ea is passed to the JVM it will skip the assertion during runtime. Is that right?
Does Sonar have a way to disable an error on a single line of code?

I think the answer to those questions will help us to understand whether this line is really worth it.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 4]
```diff
@@ -80,8 +80,9 @@
 				try {
 					a.setBalance((long) v);
 				} catch (NegativeAccountBalanceException nabe) {
+					// The cast here is to make sonar happy
```
Comment (rbair23) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:83]: It isn't just sonar, Intellij complains about it too. I think the code though should be fixed to handle a potential ClassCastException because we're taking an Object and assuming it will be a long. Perhaps modify the try/catch so that it also catches ClassCastException and deals with a bad cast if it happens.

File: hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java (hunk 1 above)
Comment (ljianghedera) [reply hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java:217]: By default. The assert is disabled. By doing this, sonar seems not complaining.

Yeah, sonar has couple of ways to disable reporting errors. I think this should be a better solution in this case.

My original thought was to not resort to sonar's feature to disable reporting errors if it's not a big effort.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java (hunk 4 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:83]: Yeah, will make the changes as suggested.

**Review by abhishek-hedera — APPROVED** [review]

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 5]
```diff
@@ -78,10 +78,12 @@
...
 			return (a, v) -> {
 				try {
-					a.setBalance((long) v);
+					a.setBalance(((Number)v).longValue());
+				} catch (ClassCastException cce) {
+					throw new IllegalArgumentException("Wrong argument type. Argument needs to be of type int or long {}", cce);
 				} catch (NegativeAccountBalanceException nabe) {
 					throw new IllegalArgumentException(String.format(
-							"Argument 'v=%d' would cause account 'a=%s' to have a negative balance!", v, a));
+							"Argument 'v=%d' would cause account 'a=%s' to have a negative balance!", ((Number) v).longValue(), a));
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:86]: So why don't we just use string concatenation here so we don't need to cast object v to Number then get its long value? We can just by default use the `v.toString()` instead

Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java]: Yeah, Change.  This is better.  I guess the original intention was for readability.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 6]
```diff
@@ -78,10 +78,13 @@
 		public BiConsumer<MerkleAccount, Object> setter() {
 			return (a, v) -> {
 				try {
-					a.setBalance((long) v);
+					a.setBalance(((Number)v).longValue());
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:81]: nit: spacing `(Number) v`

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 7]
```diff
@@ -78,10 +78,13 @@
...
+				} catch (ClassCastException cce) {
+					throw new IllegalArgumentException(
+							"Wrong argument type. Argument needs to be of type int or long :" + v.toString());
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:84]: `"Wrong argument type! Argument needs to be of type int or long. Actual value: " + v.toString()`
and also add `cce` to be wrapped in this `IllegalArgumentException`

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java [hunk 8]
```diff
@@ -78,10 +78,13 @@
...
 				} catch (NegativeAccountBalanceException nabe) {
-					throw new IllegalArgumentException(String.format(
-							"Argument 'v=%d' would cause account 'a=%s' to have a negative balance!", v, a));
+					throw new IllegalArgumentException(
+							"Argument 'v=" + v.toString() +"' would cause account 'a=" + a + "' to have a negative balance!");
```
Comment (qnswirlds) [inline hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:87]: nit: spacing `+ "'`

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java (hunk 7 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:84]: Is there special reason to wrap the `cce`? I think the new description is clear enough.

Comment (qnswirlds) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:84]: For debugging purpose, it is always better to have all the info. If you don't wrap the cce, you will lose some info there. Another way to handle this is to log the cce.

Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:84]: I see and added. I had the `cce` originally and notices that the message was fairly clear to me. But if other developers look at it, it may not be obvious where the error comes from.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java (hunk 8 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:87]: Done.

File: hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java (hunk 6 above)
Comment (ljianghedera) [reply hedera-node/src/main/java/com/hedera/services/ledger/properties/AccountProperty.java:81]: Done/

**Review by qnswirlds — APPROVED** [review]
LGTM
