### PR TITLE
fix: 23296 Resolved OOM in `entityIds` validation

### LINKED ISSUE #23296: `entityIds` validation causes `OutOfMemoryError`
Here is an example of such a failure - https://github.com/hashgraph/hedera-state-validator/actions/runs/21646954511/job/62401464000
```
Rehash.reHash,reHash(DeserializedSignedState) - SUCCEEDED, time taken - 35 sec
Rehash.validateMerkleTree,validateMerkleTree(DeserializedSignedState, HashInfo) - SUCCEEDED, time taken - 0 sec
EntityIdUniqueness.validateIdCounts,validateIdCounts(MerkleNodeState) - SUCCEEDED, time taken - 17 sec
Error: Exception in thread "JNA Cleaner" java.lang.OutOfMemoryError: Java heap space
	at java.base/jdk.internal.logger.DefaultLoggerFinder.isSystem(DefaultLoggerFinder.java:144)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:652)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:720)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:703)
	at com.sun.jna.internal.Cleaner$CleanerThread.run(Cleaner.java:159)
```

This issue caused by the fact that the validation iterates over the whole map but never creates a copy to reset cache. Eventually, the whole VM content ends up in memory or fail with OOM, just like it happened in this case.

### PR DESCRIPTION
**Pull request by imalygin**
**Description**:

This PR resolves  `OutOfMemoryError` that may happen during `entityIds` validation. 

Misc:

Renamed `getState` method with no parameters to `getDefaultState`.

**Related issue(s)**:

Fixes #23296 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java [hunk 1]
```diff
@@ -47,71 +47,68 @@
...
-                servicesState.getReadableStates(ConsensusService.NAME).get(TOPICS_STATE_ID);
-        final ReadableKVState<FileID, File> fileState =
-                servicesState.getReadableStates(FileService.NAME).get(FILES_STATE_ID);
-        final ReadableKVState<ScheduleID, Schedule> scheduleState =
-                servicesState.getReadableStates(ScheduleService.NAME).get(SCHEDULES_BY_ID_STATE_ID);
-
         ParallelProcessingUtils.processRange(0, lastEntityIdNumber, number -> {
+                    if (idCounter.incrementAndGet() % 100_000 == 0) {
+                        // from time to time we need to create copies to limit cache growth and prevent OOM errors
+                        StateUtils.copyDefaultState();
```
Comment (artemananiev) [inline hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java]: Would it be easier to just call `reset()` on the readable KV states?

Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java]: I think we need to do both. The approach that I took clears `VirtualNodeCache` but you're correct - we need to clear the cache in readable KV states as well. I'll add this functionality

Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java]: Done

Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java]: I stand corrected - copy creation was excessive here, so I removed it

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java [hunk 2]
```diff
@@ -47,71 +47,67 @@
...
-        final ReadableKVState<FileID, File> fileState =
-                servicesState.getReadableStates(FileService.NAME).get(FILES_STATE_ID);
-        final ReadableKVState<ScheduleID, Schedule> scheduleState =
-                servicesState.getReadableStates(ScheduleService.NAME).get(SCHEDULES_BY_ID_STATE_ID);
+        final MerkleNodeState<?> state = StateUtils.getDefaultState();
 
         ParallelProcessingUtils.processRange(0, lastEntityIdNumber, number -> {
+                    if (idCounter.incrementAndGet() % 100_000 == 0) {
+                        // from time to time we need to create copies to limit cache growth and prevent OOM errors
+                        StateUtils.resetStateCache();
```
Comment (thenswan) [inline hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java:87]: If this is the only change that is needed (I mean adding and using resetStateCache in this class along with concurrent collections changes), I recommend reverting everything else

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java [hunk 3]
```diff
@@ -171,6 +193,10 @@ void validateIdCounts(MerkleNodeState servicesState) throws InterruptedException
         final AtomicLong evmHookStorageCount = new AtomicLong(0);
 
         ParallelProcessingUtils.processRange(metadata.getFirstLeafPath(), metadata.getLastLeafPath(), number -> {
+                    // from time to time we need to create copies to limit cache growth and prevent OOM errors
```
Comment (thenswan) [inline hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java]: Need to update comment

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java (hunk 2 above)
Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java:87]: I reverted the method and used a local variable for the state, as it used to be. I'll keep `getState` -> `getDefaultState` rename though.

File: hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java (hunk 3 above)
Comment (imalygin) [reply hedera-state-validator/src/main/java/com/hedera/statevalidation/validator/state/service/EntityIdUniqueness.java]: Updated the comment
