### PR TITLE
fix: platform should not use common fork join pool

### LINKED ISSUE #11265: Don't use common fork join pool for wiring
The wiring framework should not be using the common fork join pool.

### PR DESCRIPTION
**Pull request by cody-littley**
closes #11265

### CODE REVIEW

**Review by anthony-swirldslabs — DISMISSED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java [hunk 1]
```diff
@@ -86,6 +91,7 @@ public TaskSchedulerBuilder(@NonNull final StandardWiringModel model, @NonNull f
             throw new IllegalArgumentException("TaskScheduler name must not be empty");
         }
         this.name = name;
+        this.pool = Objects.requireNonNull(defaultPool);
```
Comment (OlegMazurov) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/schedulers/builders/TaskSchedulerBuilder.java:94]: Should `ForkJoinPool.commonPool()` still be used to initialize `this.pool` above? Looks like it's always overwritten here.

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java [hunk 2]
```diff
@@ -39,23 +39,15 @@ public interface WiringModel extends Startable, Stoppable {
...
-     * Build a new wiring model instance.
-     *
-     * @param metrics provides metrics
-     * @param time    provides wall clock time
-     * @return a new wiring model instance
-     */
-    @NonNull
-    static WiringModel create(@NonNull final Metrics metrics, @NonNull final Time time) {
-        return new StandardWiringModel(metrics, time);
+    static WiringModel create(
```
Comment (lpetrovic05) [inline platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java:46]: Overloading this method with the default pool seems like a better approach

**Review by lpetrovic05 — APPROVED** [review]

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java:46]: I'm not a fan of using overloaded constructors for optional arguments. Very quickly the constructors for a class grow in count and complexity. IMO, the best way of handling optional parameters is to use the builder model. 

If this is the path we decide to go down, I can open up a ticket and change this to a builder pattern as a stand alone PR. It's a small amount of work, probably a 1 or 2 point task, and I can get it done this week.

**Review by edward-swirldslabs — APPROVED** [review]

**Review by alittley — APPROVED** [review]

File: platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java (hunk 2 above)
Comment (cody-littley) [reply platform-sdk/swirlds-common/src/main/java/com/swirlds/common/wiring/model/WiringModel.java:46]: Marking this as resolved since it's minor, once we work out our plan I'm willing to make changes immediately as a follow up.
